import test from 'node:test';
import assert from 'node:assert/strict';
import { parseAttachmentFileIntent, parseAttachmentFileRecovery, attachmentFileCanCapture } from '../../src/hub/features/imports/attachment-file-state.ts';
const id=(n:number)=>`de730000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const mapping={link_id:id(1),pet_id:id(2),source_origin:'https://api.trial.ezyvet.com',source_site_uid:'synthetic',external_id:'77'};
const parent={animal_link_id:id(1),pet_id:id(2),client_id:id(3),animal_external_id:'77',source_origin:mapping.source_origin,source_site_uid:'synthetic',parent_type:'Animal' as const,parent_external_id:'77',parent_snapshot_id:id(4),parent_payload_hash:'a'.repeat(64),parent_observed_head_version:1};
const intent={id:id(5),actor:id(6),pet:id(2),runId:id(7),page:1,snapshotId:id(8),payloadHash:'b'.repeat(64),headVersion:1,externalId:'701',parent,name:'Synthetic source file'};
function recovery(){return {request:{id:intent.id,actor_id:intent.actor,pet_id:intent.pet,request_hash:'c'.repeat(64),status:'pending',request_payload:{run_id:intent.runId,page:1,snapshot_id:intent.snapshotId,payload_hash:intent.payloadHash,observed_head_version:1},source_context:{schema_version:1,run_id:intent.runId,page:1,parent,attachment_snapshot_id:intent.snapshotId,attachment_payload_hash:intent.payloadHash,attachment_observed_head_version:1,attachment_external_id:'701',attachment_metadata:{id:701,record_type:'Animal',record_id:77,mime_type:'application/pdf'}}},capture_intent:null,capture:null,worker:null,download_available:false};}
test('file intent is pinned to actor, mapping and patient',()=>{assert.equal(parseAttachmentFileIntent(intent,intent.actor,mapping).id,intent.id);assert.throws(()=>parseAttachmentFileIntent({...intent,actor:id(99)},intent.actor,mapping));assert.throws(()=>parseAttachmentFileIntent({...intent,parent:{...parent,pet_id:id(99)}},intent.actor,mapping));});
test('file recovery preserves exact selected page observation and source parent',()=>{const value=recovery();assert.equal(parseAttachmentFileRecovery(value,intent).status,'pending');for(const mutation of [{runId:id(99)},{snapshotId:id(99)},{payloadHash:'d'.repeat(64)},{headVersion:2},{externalId:'702'},{parent:{...parent,parent_observed_head_version:2}}])assert.throws(()=>parseAttachmentFileRecovery(value,{...intent,...mutation}));});
test('changed recovered actor, patient or request hash is rejected',()=>{for(const mutation of [{actor_id:id(99)},{pet_id:id(99)},{id:id(99)}]){const value=recovery();Object.assign(value.request,mutation);assert.throws(()=>parseAttachmentFileRecovery(value,intent));}assert.throws(()=>parseAttachmentFileRecovery(recovery(),{...intent,requestHash:'d'.repeat(64)}));});
test('captured status requires a matching private-file receipt',()=>{const value=recovery();value.request.status='captured';assert.throws(()=>parseAttachmentFileRecovery(value,intent));});
test('lease, cooldown and permanent failure state prevent capture',()=>{const value=parseAttachmentFileRecovery(recovery(),intent);assert.equal(attachmentFileCanCapture(value),true);const worker={attempt_no:1,lease_active:false,lease_until:'2099-01-01T00:00:00Z',error_code:null,retryable:true,retry_after:null};assert.equal(attachmentFileCanCapture({...value,worker:{...worker,lease_active:true}}),false);assert.equal(attachmentFileCanCapture({...value,worker:{...worker,retryable:false}}),false);assert.equal(attachmentFileCanCapture({...value,worker:{...worker,retry_after:'2099-01-01T00:00:00Z'}}),false);assert.equal(attachmentFileCanCapture({...value,status:'captured'}),false);});
