import test from 'node:test';
import assert from 'node:assert/strict';
import { parseAttachmentFileIntent, parseAttachmentFileRecovery, attachmentFileCanCapture, parseAttachmentFileHistory } from '../../src/hub/features/imports/attachment-file-state.ts';
const id=(n:number)=>`de730000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const mapping={link_id:id(1),pet_id:id(2),source_origin:'https://api.trial.ezyvet.com',source_site_uid:'synthetic',external_id:'77'};
const parent={animal_link_id:id(1),pet_id:id(2),client_id:id(3),animal_external_id:'77',source_origin:mapping.source_origin,source_site_uid:'synthetic',parent_type:'Animal' as const,parent_external_id:'77',parent_snapshot_id:id(4),parent_payload_hash:'a'.repeat(64),parent_observed_head_version:1};
const intent={id:id(5),actor:id(6),pet:id(2),runId:id(7),page:1,snapshotId:id(8),payloadHash:'b'.repeat(64),headVersion:1,externalId:'701',parent,name:'Synthetic source file'};
function recovery(){return {request:{id:intent.id,actor_id:intent.actor,pet_id:intent.pet,request_hash:'c'.repeat(64),status:'pending',request_payload:{run_id:intent.runId,page:1,snapshot_id:intent.snapshotId,payload_hash:intent.payloadHash,observed_head_version:1},source_context:{schema_version:1,run_id:intent.runId,page:1,parent,attachment_snapshot_id:intent.snapshotId,attachment_payload_hash:intent.payloadHash,attachment_observed_head_version:1,attachment_external_id:'701',attachment_metadata:{id:701,record_type:'Animal',record_id:77,mime_type:'application/pdf'}}},capture_intent:null,capture:null,worker:null,download_available:false};}
test('file intent is pinned to actor, mapping and patient',()=>{assert.equal(parseAttachmentFileIntent(intent,intent.actor,mapping).id,intent.id);assert.throws(()=>parseAttachmentFileIntent({...intent,actor:id(99)},intent.actor,mapping));assert.throws(()=>parseAttachmentFileIntent({...intent,parent:{...parent,pet_id:id(99)}},intent.actor,mapping));});
test('file recovery preserves exact selected page observation and source parent',()=>{const value=recovery();assert.equal(parseAttachmentFileRecovery(value,intent).status,'pending');for(const mutation of [{runId:id(99)},{snapshotId:id(99)},{payloadHash:'d'.repeat(64)},{headVersion:2},{externalId:'702'},{parent:{...parent,parent_observed_head_version:2}}])assert.throws(()=>parseAttachmentFileRecovery(value,{...intent,...mutation}));});
test('changed recovered actor, patient or request hash is rejected',()=>{for(const mutation of [{actor_id:id(99)},{pet_id:id(99)},{id:id(99)}]){const value=recovery();Object.assign(value.request,mutation);assert.throws(()=>parseAttachmentFileRecovery(value,intent));}assert.throws(()=>parseAttachmentFileRecovery(recovery(),{...intent,requestHash:'d'.repeat(64)}));});
test('captured status requires a matching private-file receipt',()=>{const value=recovery();value.request.status='captured';assert.throws(()=>parseAttachmentFileRecovery(value,intent));});
test('lease, cooldown and permanent failure state prevent capture',()=>{const value=parseAttachmentFileRecovery(recovery(),intent);assert.equal(attachmentFileCanCapture(value),true);const worker={attempt_no:1,lease_active:false,lease_until:'2099-01-01T00:00:00Z',error_code:null,retryable:true,retry_after:null};assert.equal(attachmentFileCanCapture({...value,worker:{...worker,lease_active:true}}),false);assert.equal(attachmentFileCanCapture({...value,worker:{...worker,retryable:false}}),false);assert.equal(attachmentFileCanCapture({...value,worker:{...worker,retry_after:'2099-01-01T00:00:00Z'}}),false);assert.equal(attachmentFileCanCapture({...value,status:'captured'}),false);});

function history(){const value=recovery();const {attachment_metadata,...source}=value.request.source_context;void attachment_metadata;return {requests:[{...value,request:{...value.request,created_at:'2026-09-13T00:00:00Z',resolved_at:null as string|null,source_context:source}}],has_more:false,next_cursor:null as null|{before_at:string;before_id:string}};}
test('request history binds actor/patient/source and rejects duplicate rows',()=>{assert.equal(parseAttachmentFileHistory(history(),intent.actor,mapping).requests[0].intent!.id,intent.id);for(const key of ['actor_id','pet_id'] as const){const p=history();p.requests[0].request[key]=id(99);assert.throws(()=>parseAttachmentFileHistory(p,intent.actor,mapping));}const p=history();p.requests.push(p.requests[0]);assert.throws(()=>parseAttachmentFileHistory(p,intent.actor,mapping));});
test('history cursor must identify the exact last row',()=>{const p=history();p.has_more=true;p.next_cursor={before_at:p.requests[0].request.created_at,before_id:intent.id};assert.equal(parseAttachmentFileHistory(p,intent.actor,mapping).has_more,true);p.next_cursor.before_id=id(99);assert.throws(()=>parseAttachmentFileHistory(p,intent.actor,mapping));});
test('abandonment tombstones remain discoverable without inventing source context',()=>{const p={requests:[{request:{id:intent.id,actor_id:intent.actor,pet_id:intent.pet,status:'abandoned',created_at:'2026-09-13T00:00:00Z',resolved_at:'2026-09-13T00:00:01Z',request_payload:null,request_hash:null,source_context:null},capture_intent:null,capture:null,worker:null,download_available:false}],has_more:false,next_cursor:null};assert.equal(parseAttachmentFileHistory(p,intent.actor,mapping).requests[0].intent,null);p.requests[0].request.status='pending';assert.throws(()=>parseAttachmentFileHistory(p,intent.actor,mapping));});
test('another source mapping stays visible but cannot be reopened under this mapping',()=>{const p=history();p.requests[0].request.source_context.parent={...parent,animal_link_id:id(99)};assert.equal(parseAttachmentFileHistory(p,intent.actor,mapping).requests[0].sameMapping,false);});
