import test from 'node:test';
import assert from 'node:assert/strict';
import { parseAttachmentParent, parseAttachmentObservations, parseAttachmentCleanups, parseAttachmentRuns, parseRecoveredAttachmentRun, attachmentScanCanContinue, parsePreparedAttachmentRun } from '../../src/hub/features/imports/attachment-discovery-state.ts';
const id = (n: number) => `de700000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const mapping = { link_id: id(1), pet_id: id(2), source_origin: 'https://api.trial.ezyvet.com', source_site_uid: 'synthetic', external_id: '77' };
const parent = { animal_link_id: mapping.link_id, pet_id: mapping.pet_id, client_id: id(3), animal_external_id: '77', source_origin: mapping.source_origin, source_site_uid: mapping.source_site_uid, parent_type: 'Animal' as const, parent_external_id: '77', parent_snapshot_id: id(4), parent_payload_hash: 'a'.repeat(64), parent_observed_head_version: 1 };
function page() { return { run_id: id(5), pet_id: mapping.pet_id, parent_context: parent, parent_is_current: true, observations: [{ run_id: id(5), pet_id: mapping.pet_id, page: 1, snapshot_id: id(6), payload_hash: 'b'.repeat(64), observed_head_version: 1, external_id: '701', current_snapshot_id: id(6) as string|null, current_head_version: 1 as number|null, is_current: true, metadata: { name: 'Source file', mime_type: 'text/plain', file_id: null, notes: 'Source notes', notes_truncated: false, name_truncated: false } }], has_more: false, next_cursor: null as null|{after_page:number;after_snapshot_id:string} }; }
const parse = (value: unknown) => parseAttachmentObservations(value,id(5),mapping,parent);
const owner = { actor: id(7), pet: mapping.pet_id, id: id(8), requestHash: 'c'.repeat(64), intentHash: 'd'.repeat(64) };
function cleanups() { return { request_id: owner.id, pet_id: owner.pet, cleanups: [{ attempt: { id: id(9), request_id: owner.id, actor_id: owner.actor, pet_id: owner.pet, request_hash: owner.requestHash, intent_hash: owner.intentHash, created_at: '2026-09-13T00:00:00Z', lease_until: '2026-09-13T00:01:30Z' }, receipt: { cleanup_id: id(9), request_id: owner.id, actor_id: owner.actor, intent_hash: owner.intentHash, verified_absent_at: '2026-09-13T00:00:10Z' }, lease_active: false }], has_more: false, next_cursor: null as null|{before_at:string;before_id:string} }; }
test('current parent is bound to reviewed mapping; absent head remains absent',()=>{assert.deepEqual(parseAttachmentParent(parent,mapping),parent);assert.equal(parseAttachmentParent(null,mapping),null);assert.throws(()=>parseAttachmentParent({...parent,pet_id:id(99)},mapping));});
test('observations preserve unsupported metadata for accounting',()=>{assert.equal(parse(page()).observations[0].metadata.mime_type,'text/plain');});
test('parent and file currentness remain independent',()=>{const p=page();p.parent_is_current=false;assert.equal(parse(p).observations[0].is_current,true);});
test('same snapshot at newer observed head is stale',()=>{const p=page();p.observations[0].current_head_version=2;p.observations[0].is_current=false;assert.equal(parse(p).observations[0].observed_head_version,1);p.observations[0].is_current=true;assert.throws(()=>parse(p));});
test('missing current head is represented without dropping the historical observation',()=>{const p=page();Object.assign(p.observations[0],{current_head_version:null,current_snapshot_id:null,is_current:false});assert.equal(parse(p).observations.length,1);p.observations[0].current_head_version=1;assert.throws(()=>parse(p));});
for(const field of ['run_id','pet_id'] as const)test(`wrong ${field} in page or observation rejects`,()=>{const p=page();p[field]=id(99);assert.throws(()=>parse(p));const q=page();q.observations[0][field]=id(99);assert.throws(()=>parse(q));});
test('changed parent pin rejects even with matching mapping',()=>{const p=page();p.parent_context={...parent,parent_observed_head_version:2};assert.throws(()=>parse(p));});
test('unvalidated expected parent cannot bypass exact pin comparison',()=>{assert.throws(()=>parseAttachmentObservations(page(),id(5),mapping,{} as typeof parent));});
test('provider URLs and hidden lease fields are not accepted in list data',()=>{const p=page();Object.assign(p.observations[0].metadata,{file_download_url:'https://untrusted.example.test'});assert.throws(()=>parse(p));const c=cleanups();Object.assign(c.cleanups[0].attempt,{lease_id:id(99)});assert.throws(()=>parseAttachmentCleanups(c,owner));});
test('bounded previews count Unicode characters like PostgreSQL',()=>{const p=page();p.observations[0].metadata.notes='🐕'.repeat(4000);p.observations[0].metadata.notes_truncated=true;assert.equal(parse(p).observations[0].metadata.notes_truncated,true);p.observations[0].metadata.notes+='x';assert.throws(()=>parse(p));});
test('duplicate observations and missing/mismatched page cursors reject',()=>{const p=page();p.observations.push(p.observations[0]);assert.throws(()=>parse(p));const q=page();q.has_more=true;assert.throws(()=>parse(q));q.next_cursor={after_page:1,after_snapshot_id:id(6)};assert.equal(parse(q).has_more,true);q.next_cursor.after_snapshot_id=id(99);assert.throws(()=>parse(q));});
test('cleanup history binds each receipt to the owned original request',()=>{const c=cleanups();assert.equal(parseAttachmentCleanups(c,owner).cleanups[0].receipt?.cleanup_id,id(9));c.cleanups[0].receipt.actor_id=id(99);assert.throws(()=>parseAttachmentCleanups(c,owner));});
test('another actor or changed original hash cannot appear in cleanup attempts',()=>{const c=cleanups();c.cleanups[0].attempt.actor_id=id(99);assert.throws(()=>parseAttachmentCleanups(c,owner));const d=cleanups();d.cleanups[0].attempt.intent_hash='e'.repeat(64);assert.throws(()=>parseAttachmentCleanups(d,owner));});
test('completed cleanup cannot claim an active lease',()=>{const c=cleanups();c.cleanups[0].lease_active=true;assert.throws(()=>parseAttachmentCleanups(c,owner));});
test('cleanup cursor identifies the exact last row; duplicate cleanup IDs reject',()=>{const c=cleanups();c.has_more=true;c.next_cursor={before_at:c.cleanups[0].attempt.created_at,before_id:id(9)};assert.equal(parseAttachmentCleanups(c,owner).has_more,true);c.next_cursor.before_id=id(99);assert.throws(()=>parseAttachmentCleanups(c,owner));const d=cleanups();d.cleanups.push(d.cleanups[0]);assert.throws(()=>parseAttachmentCleanups(d,owner));});

function runs(){return {runs:[{id:id(5),requested_by:owner.actor,resource:'attachment',source_origin:mapping.source_origin,source_site_uid:mapping.source_site_uid,status:'running',next_page:2,retry_after:null,last_error_code:null,created_at:'2026-09-13T00:00:00Z',updated_at:'2026-09-13T00:00:00Z',lease_active:false,scope:'parent_scoped',parent_context:parent}],has_more:false,next_cursor:null};}
test('scan discovery binds owner and patient mapping',()=>{assert.equal(parseAttachmentRuns(runs(),owner.actor,mapping).runs.length,1);const r=runs();r.runs[0].requested_by=id(99);assert.throws(()=>parseAttachmentRuns(r,owner.actor,mapping));});
test('scan discovery rejects duplicates and false pagination metadata',()=>{const r=runs();r.runs.push(r.runs[0]);assert.throws(()=>parseAttachmentRuns(r,owner.actor,mapping));const q=runs();q.has_more=true;assert.throws(()=>parseAttachmentRuns(q,owner.actor,mapping));});

function savedRun() { return {id:id(5),requested_by:owner.actor,resource:'attachment' as const,source_origin:mapping.source_origin,source_site_uid:mapping.source_site_uid,status:'running' as const,next_page:2,retry_after:null,last_error_code:null,created_at:'2026-09-13T00:00:00Z',updated_at:'2026-09-13T00:00:00Z',lease_active:false,scope:'parent_scoped' as const,parent_context:parent}; }
test('recovery preserves exact saved run and all immutable parent pins',()=>{const r=savedRun();assert.equal(parseRecoveredAttachmentRun(r,owner.actor,mapping,r).id,r.id);for(const change of [{id:id(99)},{requested_by:id(99)},{parent_context:{...parent,parent_observed_head_version:2}},{parent_context:{...parent,parent_snapshot_id:id(99)}}])assert.throws(()=>parseRecoveredAttachmentRun({...r,...change},owner.actor,mapping,r));assert.throws(()=>parseRecoveredAttachmentRun(null,owner.actor,mapping,r));});
test('terminal scans, active leases and future cooldowns cannot request pages',()=>{const r=savedRun(),now=Date.parse('2026-09-13T00:00:00Z');assert.equal(attachmentScanCanContinue(r,now),true);for(const change of [{status:'review_ready' as const},{status:'page_limit_reached' as const},{lease_active:true},{retry_after:'2026-09-13T00:01:00Z'}])assert.equal(attachmentScanCanContinue({...r,...change},now),false);assert.equal(attachmentScanCanContinue({...r,retry_after:'2026-09-12T00:01:00Z'},now),true);});

test('prepared scan is bound to operation, actor, mapping and every selected parent pin',()=>{const r=savedRun();assert.equal(parsePreparedAttachmentRun(r,r.id,owner.actor,mapping,parent).id,r.id);for(const change of [{id:id(99)},{requested_by:id(99)},{parent_context:{...parent,parent_observed_head_version:2}},{parent_context:{...parent,parent_external_id:'88'}}])assert.throws(()=>parsePreparedAttachmentRun({...r,...change},r.id,owner.actor,mapping,parent));assert.throws(()=>parsePreparedAttachmentRun(r,r.id,owner.actor,mapping,{...parent,pet_id:id(99)}));});
