export const actor = "11111111-1111-4111-8111-111111111111",
  pet = "22222222-2222-4222-8222-222222222222",
  client = "33333333-3333-4333-8333-333333333333",
  capture = "44444444-4444-4444-8444-444444444444",
  recordId = "55555555-5555-4555-8555-555555555555",
  request = "66666666-6666-4666-8666-666666666666",
  at = "2026-09-14T12:00:00Z";
export function record() {
  return {
    id: recordId,
    action_id: request,
    approved_by: actor,
    approved_at: at,
    pet_id: pet,
    client_id: client,
    patient_version: 1,
    animal_link_id: client,
    capture_id: capture,
    capture_request_id: capture,
    capture_hash: "a".repeat(64),
    request_hash: "b".repeat(64),
    record_hash: "c".repeat(64),
    source_origin: "https://api.trial.ezyvet.com",
    source_site_uid: "synthetic",
    source_animal_id: "22",
    source_attachment_id: "7",
    source_file_id: "8",
    snapshot_id: client,
    observed_head_version: 1,
    stable_metadata_sha256: "d".repeat(64),
    raw_record_sha256: "e".repeat(64),
    metadata: {
      id: "7",
      file_id: "8",
      record_type: "Animal",
      record_id: "22",
      name: "Synthetic original.pdf",
    },
    content_sha256: "f".repeat(64),
    mime_type: "application/pdf",
    file_size: 30,
    captured_at: at,
    entry_method: "staff_reviewed_ezyvet_api_attachment_v1",
    source_current_at_review: false,
    previous_record_id: null,
    version: 1,
    kind: "original",
    review_reason: "Reviewed historical original",
  };
}
export function candidate() {
  const r = record();
  return {
    capture_id: r.capture_id,
    capture_request_id: r.capture_request_id,
    pet_id: pet,
    client_id: client,
    animal_link_id: client,
    capture_hash: r.capture_hash,
    content_sha256: r.content_sha256,
    mime_type: r.mime_type,
    file_size: r.file_size,
    captured_at: at,
    metadata: r.metadata,
    source_origin: r.source_origin,
    source_site_uid: r.source_site_uid,
    source_animal_id: r.source_animal_id,
    source_attachment_id: r.source_attachment_id,
    source_file_id: r.source_file_id,
    source_current: false,
    patient_version: 1,
    mapping_current: true,
    latest_record: null,
    admitted_record: null,
  };
}
export function approvalIntent() {
  return {
    kind: "approve",
    args: {
      p_id: request,
      p_pet_id: pet,
      p_capture_id: capture,
      p_expected_capture_hash: "a".repeat(64),
      p_expected_patient_version: 1,
      p_previous_record_id: null,
      p_review_reason: "Reviewed historical original",
      p_attest: true,
    },
  };
}
