import { test } from 'node:test';
import assert from 'node:assert/strict';
import { parseAttachmentReviewHistory } from '../../src/hub/features/imports/attachment-review-state.ts';
const id=(n:number)=>`de700000-0000-4000-8000-${String(n).padStart(12,'0')}`,h='a'.repeat(64),at='2026-09-13T12:00:00.123456Z';
const parent={animal_link_id:id(3),pet_id:id(2),client_id:id(4),animal_external_id:'77',source_origin:'https://api.trial.ezyvet.com',source_site_uid:'test-site',parent_type:'Animal' as const,parent_external_id:'77',parent_snapshot_id:id(5),parent_payload_hash:h,parent_observed_head_version:1};
const expected={id:id(1),pet:id(2),externalId:'701',parent};
function fixture(){const r={id:id(6),actor_id:id(7),request_id:id(1),pet_id:id(2),animal_link_id:id(3),source_origin:parent.source_origin,source_site_uid:parent.source_site_uid,attachment_external_id:'701',request_hash:h,capture_hash:h,source_context:{schema_version:1,run_id:id(8),page:1,parent,attachment_snapshot_id:id(9),attachment_external_id:'701',attachment_payload_hash:h,attachment_observed_head_version:1},title:'Reviewed source',review_reason:'Original inspected',previous_record_id:null as string|null,version:1,entry_method:'staff_reviewed_api_attachment_v1',record_hash:h,created_at:at};return {request_id:id(1),pet_id:id(2),animal_link_id:id(3),attachment_external_id:'701',latest_record_id:id(6),records:[r],has_more:false,next_cursor:null as null|{before_at:string;before_id:string}};}
test('review history validates explicit API provenance and allows prior reviewer identity',()=>{assert.equal(parseAttachmentReviewHistory(fixture(),expected).records[0].actor_id,id(7));});
test('review history rejects wrong patient and source context',()=>{const p=fixture();p.pet_id=id(99);assert.throws(()=>parseAttachmentReviewHistory(p,expected));const q=fixture();q.records[0].source_site_uid='other';assert.throws(()=>parseAttachmentReviewHistory(q,expected));});
test('review history rejects raw provider metadata and manual-export relabeling',()=>{const p=fixture();Object.assign(p.records[0].source_context,{attachment_metadata:{file_download_url:'https://example.test'}});assert.throws(()=>parseAttachmentReviewHistory(p,expected));const q=fixture();q.records[0].entry_method='staff_reviewed_manual_export_v1';assert.throws(()=>parseAttachmentReviewHistory(q,expected));});
test('review history rejects broken lineage and substituted cursors',()=>{const p=fixture();p.records[0].previous_record_id=id(6);assert.throws(()=>parseAttachmentReviewHistory(p,expected));const q=fixture();q.has_more=true;q.next_cursor={before_at:at,before_id:id(99)};assert.throws(()=>parseAttachmentReviewHistory(q,expected));});
