begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select no_plan();
insert into auth.users(id,email,raw_user_meta_data) values('ac2d0000-0000-4000-8000-000000000001','care-delivery@example.test','{}');
update profiles set is_active=true,full_name='Synthetic care DVM' where id='ac2d0000-0000-4000-8000-000000000001';
insert into user_roles(user_id,role) values('ac2d0000-0000-4000-8000-000000000001','ADMIN'),('ac2d0000-0000-4000-8000-000000000001','DVM');
create temp table fx(k text primary key,id uuid);create temp table data(k text primary key,v jsonb);grant all on fx,data to authenticated,service_role;
insert into fx select k,gen_random_uuid() from unnest(array['default','plan','sibling-plan','wording','policy','job','policy-action']) k;
set local role authenticated;select set_config('request.jwt.claims','{"role":"authenticated","sub":"ac2d0000-0000-4000-8000-000000000001"}',true);
select save_recurring_care_template(gen_random_uuid(),(select id from fx where k='default'),null,'{"care_key":"synthetic-delivery","name":"Synthetic daily care","care_kind":"custom","interval_amount":1,"interval_unit":"days","anchor_mode":"completed_care","month_end":"clamp","active":true,"review_note":"Synthetic approved interval"}');
insert into fx select 'client',id from save_client(auth.uid(),null,null,'Synthetic','Care Delivery','+12025550189','synthetic-delivery@example.test','EMAIL',null,null);
insert into fx select 'pet',id from save_patient(null,(select id from fx where k='client'),null,'Synthetic quiet dog','Dog',null,null,'unknown',null,'unknown','unknown',null,null,null);
insert into fx select 'sibling',id from save_patient(null,(select id from fx where k='client'),null,'Synthetic active sibling','Dog',null,null,'unknown',null,'unknown','unknown',null,null,null);
insert into data values('plan',jsonb_build_object('template_id',(select id from fx where k='default'),'template_version',1,'name','Synthetic daily care','interval_amount',1,'interval_unit','days','anchor_mode','completed_care','month_end','clamp',
 'anchor_on',(clock_timestamp() at time zone 'America/Denver')::date-1,'due_on',(clock_timestamp() at time zone 'America/Denver')::date,'status','current','reminders_enabled',true,'override_reason','','review_note','Synthetic reviewed plan','replace_anchor_evidence',false));
select save_patient_care_plan(gen_random_uuid(),(select id from fx where k='plan'),(select id from fx where k='pet'),null,(select v from data where k='plan'));
select save_care_message_template((select id from fx where k='wording'),null,'Synthetic quiet wording','email',0,'{{patient_name}}: {{care_name}} due {{due_date}}',true,'Synthetic review');
insert into data values('quiet-policy',jsonb_build_object('channel','EMAIL','message_template_id',(select id from fx where k='wording'),'message_template_version',1,'subject','Synthetic quiet care','enabled',true,'review_note','Synthetic narrow send window',
 'start_minute',(extract(hour from clock_timestamp() at time zone 'America/Denver')::integer*60+extract(minute from clock_timestamp() at time zone 'America/Denver')::integer+720)%1440,
 'end_minute',(extract(hour from clock_timestamp() at time zone 'America/Denver')::integer*60+extract(minute from clock_timestamp() at time zone 'America/Denver')::integer+720)%1440+1));
insert into data values('policy-receipt',save_care_plan_delivery_policy((select id from fx where k='policy-action'),(select id from fx where k='policy'),null,(select v from data where k='quiet-policy')));
select is(read_care_workflow_action((select id from fx where k='policy-action'),'delivery_policy',(select id from fx where k='policy'),null,jsonb_build_object('expected_version',null,'values',(select v from data where k='quiet-policy'))),(select v from data where k='policy-receipt'),'Read-only exact receipt recovers a committed policy');
select throws_ok($$select read_care_workflow_action((select id from fx where k='policy-action'),'delivery_policy',(select id from fx where k='policy'),null,jsonb_build_object('expected_version',null,'values','{}'::jsonb))$$,'23505',null,'Read-only receipt cannot adopt another payload');
select is(jsonb_array_length(read_patient_360((select id from fx where k='pet'))#>'{signals,care_plans_awaiting_review}'),0,'Reviewed care needs no proposed signal');
set local role service_role;select set_config('request.jwt.claims','{"role":"service_role"}',true);
select is((queue_due_reminders()->>'queued')::integer,0,'Scheduler waits outside the reviewed recurring send window');
select enqueue_care_reminder((select id from fx where k='job'),'care_plan',(select id from fx where k='plan'),1,(select id from fx where k='wording'),1);
insert into fx select 'quiet-outbox',outbox_id from queue_reminder_outbox('care',(select id from fx where k='job'),(select id from fx where k='policy'));
select lives_ok($$select claim_communication()$$,'An existing handoff can be claimed after a worker delay');
select is((select state from start_communication_attempt((select id from fx where k='quiet-outbox'),(select lease_token from communication_outbox where id=(select id from fx where k='quiet-outbox')),'{"from":"verified@example.test","reply_to":"reply@example.test"}')),'pending','Outside-window attempt returns pending instead of provider-started');
reset role;
select is((select count(*) from communication_attempts where outbox_id=(select id from fx where k='quiet-outbox')),0::bigint,'Quiet-hours deferral creates no provider attempt');
select ok((select eligible_at>clock_timestamp() from care_delivery_deferrals where outbox_id=(select id from fx where k='quiet-outbox')),'Deferral stores a finite future send-window opening');
select ok((select lease_token is null and attempt_started_at is null and attempt_count=0 from communication_outbox where id=(select id from fx where k='quiet-outbox')),'Deferral releases the lease without changing attempt count');
set local role service_role;select set_config('request.jwt.claims','{"role":"service_role"}',true);
select is((select id from claim_communication()),null::uuid,'Claim skips future-deferred work');
set local role authenticated;select set_config('request.jwt.claims','{"role":"authenticated","sub":"ac2d0000-0000-4000-8000-000000000001"}',true);
select is(read_daily_communication('outbox',(select id from fx where k='quiet-outbox'))#>>'{record,status}','scheduled','Daily view shows deferred routine work as scheduled');
select ok((read_daily_communication('outbox',(select id from fx where k='quiet-outbox'))#>>'{record,reason}') like 'Deferred until %','Daily view explains the Denver send-window opening');
select ok(read_patient_care_plan((select id from fx where k='plan'),(select id from fx where k='pet'))->>'next_send_at' is not null,'Patient plan exposes the deferred opening');
select save_care_plan_delivery_policy(gen_random_uuid(),(select id from fx where k='policy'),1,(select v||'{"start_minute":0,"end_minute":1440,"review_note":"Synthetic full day"}' from data where k='quiet-policy'));
select save_patient_care_plan(gen_random_uuid(),(select id from fx where k='sibling-plan'),(select id from fx where k='sibling'),null,(select v from data where k='plan'));
set local role service_role;select set_config('request.jwt.claims','{"role":"service_role"}',true);
select is((queue_due_reminders()->>'queued')::integer,1,'Different living patient can queue independently of quiet work');
reset role;
insert into fx select 'sibling-outbox',link.outbox_id from reminder_outbox_links link join care_reminder_jobs j on j.id=link.job_id and link.job_kind='care' where j.source_id=(select id from fx where k='sibling-plan');
set local role service_role;select set_config('request.jwt.claims','{"role":"service_role"}',true);
select is((select id from claim_communication()),(select id from fx where k='sibling-outbox'),'Claim remains available for another eligible patient');
select is((select state from start_communication_attempt((select id from fx where k='sibling-outbox'),(select lease_token from communication_outbox where id=(select id from fx where k='sibling-outbox')),'{"from":"verified@example.test","reply_to":"reply@example.test"}')),'claimed','In-window final eligibility creates the canonical provider attempt');
select finish_communication_attempt((select id from fx where k='sibling-outbox'),(select lease_token from communication_outbox where id=(select id from fx where k='sibling-outbox')),'uncertain',null,'Synthetic provider outcome unknown');
set local role authenticated;select set_config('request.jwt.claims','{"role":"authenticated","sub":"ac2d0000-0000-4000-8000-000000000001"}',true);
select save_patient_care_plan(gen_random_uuid(),(select id from fx where k='sibling-plan'),(select id from fx where k='sibling'),1,(select v||'{"name":"Renamed care","override_reason":"Reviewed patient wording"}' from data where k='plan'));
select save_care_message_template((select id from fx where k='wording'),1,'Revised wording','email',0,'Care: {{patient_name}} {{care_name}} {{due_date}}',true,'Synthetic wording change');
select save_care_plan_delivery_policy(gen_random_uuid(),(select id from fx where k='policy'),2,(select v||'{"start_minute":0,"end_minute":1440,"message_template_version":2}' from data where k='quiet-policy'));
set local role service_role;select set_config('request.jwt.claims','{"role":"service_role"}',true);
select is((queue_due_reminders()->>'queued')::integer,0,'Wording and version changes cannot create another automatic attempt after unknown outcome');
reset role;
select is((select count(*) from communication_attempts where outbox_id=(select id from fx where k='sibling-outbox')),1::bigint,'Unknown attempt remains a single audited handoff');
select is((select state from communication_outbox where id=(select id from fx where k='sibling-outbox')),'uncertain','Editing source leaves historical uncertainty intact');
set local role authenticated;select set_config('request.jwt.claims','{"role":"authenticated","sub":"ac2d0000-0000-4000-8000-000000000001"}',true);
select save_care_message_template((select id from fx where k='wording'),2,'Retired wording','email',0,'Care {{patient_name}}',false,'Synthetic retirement');
select lives_ok($$select save_care_plan_delivery_policy(gen_random_uuid(),(select id from fx where k='policy'),3,(select v||'{"start_minute":0,"end_minute":1440,"message_template_version":2,"enabled":false}' from data where k='quiet-policy'))$$,'Administrator can disable a policy despite retired wording');
select throws_ok($$select save_care_plan_delivery_policy(gen_random_uuid(),(select id from fx where k='policy'),4,(select v||'{"start_minute":0,"end_minute":1440,"message_template_version":2,"enabled":true}' from data where k='quiet-policy'))$$,'23514',null,'Re-enabling requires a fresh active wording review');
select * from finish();rollback;
