begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,raw_user_meta_data) values
('31000000-0000-4000-8000-000000000001','clinical-staff@example.test','{"first_name":"Clinical","last_name":"Staff"}'),
('31000000-0000-4000-8000-000000000002','clinical-inactive@example.test','{"first_name":"Clinical","last_name":"Inactive"}');
update public.profiles set is_active = true where id in ('31000000-0000-4000-8000-000000000001','31000000-0000-4000-8000-000000000002');
insert into public.user_roles (user_id, role) values ('31000000-0000-4000-8000-000000000001','STAFF'),('31000000-0000-4000-8000-000000000002','STAFF');

update public.profiles set is_active=false where id='31000000-0000-4000-8000-000000000002';
create temp table fixture_ids(kind text primary key,id uuid);
grant all on fixture_ids to authenticated;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"31000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fixture_ids select 'client',id from public.save_client(auth.uid(),null,null,'Synthetic','Family','+13035550100','test@example.test','EMAIL','2619 Spruce Street','Housecall address');
insert into fixture_ids select 'pet',id from public.save_patient(null,(select id from fixture_ids where kind='client'),null,'Zero','Dog','Mixed',(now() at time zone 'America/Denver')::date-100,'estimated','Brown','male','neutered','0000123456789',null,null);
insert into fixture_ids select 'other-client',id from public.save_client(auth.uid(),null,null,'Other','Family',null,null,'EMAIL',null,null);
select throws_ok($$select public.save_patient((select id from fixture_ids where kind='pet'),(select id from fixture_ids where kind='other-client'),1,'Zero','Dog',null,null,'unknown',null,'unknown','unknown',null,null,null)$$,'40001','Record changed or no longer exists; reload before saving','Patient edit cannot change owner via another client ID');
select throws_ok($$update public.pets set client_id=(select id from fixture_ids where kind='other-client') where id=(select id from fixture_ids where kind='pet')$$,'23514','Patient ownership transfer requires a separate workflow','Direct writes cannot reparent a patient');
set local timezone='Pacific/Kiritimati';
select throws_ok($$select public.save_patient(null,(select id from fixture_ids where kind='client'),null,'Future','Dog',null,(now() at time zone 'America/Denver')::date+1,'exact',null,'unknown','unknown',null,null,null)$$,'23514','Patient dates are invalid','Birthday validation uses Denver day regardless of session timezone');
select throws_ok($$select public.record_patient_weight((select id from fixture_ids where kind='pet'),10,'kg',(now() at time zone 'America/Denver')::date+1)$$,'23514',null,'Weight validation uses Denver day regardless of session timezone');
select throws_ok($$select public.save_patient_problem(null,(select id from fixture_ids where kind='pet'),null,'Future onset','',(now() at time zone 'America/Denver')::date+1,'active','routine')$$,'23514',null,'Problem onset validation uses Denver day regardless of session timezone');
select throws_ok($$select public.save_clinical_encounter(null,(select id from fixture_ids where kind='pet'),null,now()+interval '6 minutes','clinic','','','','','')$$,'23514','Encounter date cannot exceed the current time by more than five minutes','Encounter rejects future beyond clock tolerance');
set local timezone='UTC';
select is((select microchip_id from public.pets where id=(select id from fixture_ids where kind='pet')),'0000123456789','Microchip leading zeros survive');
select is((select count(*) from public.search_clients('zero',250)),1::bigint,'Client search finds pet names');
update public.clients set primary_phone='+1 (303) 555-0100' where id=(select id from fixture_ids where kind='client');
select is((select count(*) from public.search_clients('+13035550100',250)),1::bigint,'Client search normalizes phone formatting');
select throws_ok($$select public.save_client('31000000-0000-4000-8000-000000000002',null,null,'Fake','Actor',null,null,'EMAIL',null,null)$$,'42501','Actor does not match signed-in staff','Cannot spoof client actor');
select throws_ok($$select public.save_client(auth.uid(),(select id from fixture_ids where kind='client'),0,'Stale','Family',null,null,'EMAIL',null,null)$$,'40001','Record changed or no longer exists; reload before saving','Stale client versions rejected');
select throws_ok($$select public.save_patient((select id from fixture_ids where kind='pet'),(select id from fixture_ids where kind='client'),0,'Stale','Dog',null,null,'unknown',null,'unknown','unknown',null,null,null)$$,'40001','Record changed or no longer exists; reload before saving','Stale patient versions rejected');
select lives_ok($$select public.record_patient_weight((select id from fixture_ids where kind='pet'),10,'kg',(now() at time zone 'America/Denver')::date-1)$$,'Record kilogram weight');
select lives_ok($$select public.record_patient_weight((select id from fixture_ids where kind='pet'),22.5,'lb',(now() at time zone 'America/Denver')::date)$$,'Record pound weight');
select is((select count(*) from public.patient_weights),2::bigint,'Weight history retains both units');
select is((select count(distinct unit) from public.patient_weights),2::bigint,'Original units retained');
select is((select count(*) from public.patient_weights where recorded_by=auth.uid()),2::bigint,'Weights stamped with signed-in actor');
select throws_ok($$select public.record_patient_weight((select id from fixture_ids where kind='pet'),-1,'kg',(now() at time zone 'America/Denver')::date)$$,'23514',null,'Reject negative weights');
select throws_ok($$select public.record_patient_weight((select id from fixture_ids where kind='pet'),10,'oz',(now() at time zone 'America/Denver')::date)$$,'23514',null,'Reject unsupported weight units');
select throws_ok($$select public.record_patient_weight((select id from fixture_ids where kind='pet'),10,'kg',(now() at time zone 'America/Denver')::date+1)$$,'23514',null,'Reject future measurements');
insert into fixture_ids select 'encounter',id from public.save_clinical_encounter(null,(select id from fixture_ids where kind='pet'),null,now(),'housecall','Housecall address','Patient history','Exam findings','','');
select throws_ok($$select public.sign_clinical_encounter((select id from fixture_ids where kind='encounter'),1)$$,'23514',null,'Cannot sign blank assessment and plan');
select throws_ok($$select public.add_clinical_addendum((select id from fixture_ids where kind='encounter'),'Correction')$$,'23514','Addenda require a signed encounter','Draft cannot receive addendum');
select throws_ok($$select public.save_clinical_encounter((select id from fixture_ids where kind='encounter'),(select id from fixture_ids where kind='pet'),0,now(),'housecall','','','','Assessment','Plan')$$,'40001','Record changed or no longer exists; reload before saving','Stale encounter version rejected');
select lives_ok($$select public.save_clinical_encounter((select id from fixture_ids where kind='encounter'),(select id from fixture_ids where kind='pet'),1,now(),'housecall','','History','Exam','Assessment','Plan')$$,'Draft can be saved with expected version');
select is((select version from public.clinical_encounters where id=(select id from fixture_ids where kind='encounter')),2,'Draft save increments version');
select lives_ok($$select public.sign_clinical_encounter((select id from fixture_ids where kind='encounter'),2)$$,'Complete encounter can be signed');
select is((select signed_by from public.clinical_encounters where id=(select id from fixture_ids where kind='encounter')),auth.uid(),'Signed actor derives from session');
select throws_ok($$select public.save_clinical_encounter((select id from fixture_ids where kind='encounter'),(select id from fixture_ids where kind='pet'),3,now(),'clinic','','Rewrite','Exam','Assessment','Plan')$$,'23514','Signed encounters are immutable; add an addendum','RPC cannot rewrite signed encounter');
select lives_ok($$select public.add_clinical_addendum((select id from fixture_ids where kind='encounter'),'Correction with retained original')$$,'Signed record accepts append-only addendum');
select throws_ok($$select public.add_clinical_addendum((select id from fixture_ids where kind='encounter'),'   ')$$,'23514',null,'Blank addendum rejected');
insert into fixture_ids select 'problem',id from public.save_patient_problem(null,(select id from fixture_ids where kind='pet'),null,'Vaccine reaction','Prior reaction',(now() at time zone 'America/Denver')::date-1,'active','high');
select is((select importance from public.patient_problems where id=(select id from fixture_ids where kind='problem')),'high','Important clinical problem retains high importance');
select throws_ok($$select public.save_patient_problem((select id from fixture_ids where kind='problem'),(select id from fixture_ids where kind='pet'),0,'Reaction','',null,'resolved','high')$$,'40001','Record changed or no longer exists; reload before saving','Stale problem version rejected');
select lives_ok($$select public.save_patient_problem((select id from fixture_ids where kind='problem'),(select id from fixture_ids where kind='pet'),1,'Reaction','Resolved with history',null,'resolved','high')$$,'Resolve problem while retaining history');
select throws_ok($$update public.clinical_encounters set assessment='spoofed'$$,'42501','permission denied for table clinical_encounters','Direct staff clinical writes denied');
select throws_ok($$insert into public.patient_weights(pet_id,weight,unit,measured_at,recorded_by) values((select id from fixture_ids where kind='pet'),5,'kg',(now() at time zone 'America/Denver')::date,'31000000-0000-4000-8000-000000000002')$$,'42501','permission denied for table patient_weights','Direct actor spoofing denied');
-- Definer maintenance context still obeys signed-history and actor triggers.
reset role;
with inserted as (insert into public.patient_weights(pet_id,weight,unit,measured_at,recorded_by) values((select id from fixture_ids where kind='pet'),5,'kg',(now() at time zone 'America/Denver')::date,'31000000-0000-4000-8000-000000000002') returning recorded_by) select is((select recorded_by from inserted),auth.uid(),'Trigger replaces a supplied actor with session identity');
select throws_ok($$update public.clinical_encounters set assessment='rewrite'$$,'23514','Signed encounters are immutable; add an addendum','Even privileged DML cannot rewrite signed history');
select throws_ok($$delete from public.clinical_encounters$$,'23514','Clinical history cannot be deleted','Even privileged DML cannot delete history');
select throws_ok($$update public.clinical_addenda set content='rewrite'$$,'23514','Clinical history is append-only','Addenda remain immutable under direct DML');
select throws_ok($$delete from public.pets where id=(select id from fixture_ids where kind='pet')$$,'23503',null,'Patient deletion cannot erase clinical history');
select throws_ok($$delete from public.clients where id=(select id from fixture_ids where kind='client')$$,'23503',null,'Client deletion cannot cascade erase patient');
select ok(exists(select 1 from public.audit_logs where table_name='clinical_encounters' and user_id='31000000-0000-4000-8000-000000000001'),'Clinical changes have authenticated audit attribution');
set local role authenticated;
update public.pets set archived_at=now() where id=(select id from fixture_ids where kind='pet');
select throws_ok($$select public.record_patient_weight((select id from fixture_ids where kind='pet'),10,'kg',(now() at time zone 'America/Denver')::date)$$,'23514','Weight entries require an active patient','Archived patients cannot receive new weights');
select throws_ok($$select public.save_clinical_encounter(null,(select id from fixture_ids where kind='pet'),null,now(),'clinic','','','','','')$$,'23514','New encounters require an active patient','Archived patients cannot receive new encounters');
select lives_ok($$select public.add_clinical_addendum((select id from fixture_ids where kind='encounter'),'Post-archive clarification')$$,'Archived patients retain addendum access');
update public.pets set archived_at=null,deceased_at=(now() at time zone 'America/Denver')::date where id=(select id from fixture_ids where kind='pet');
select throws_ok($$select public.record_patient_weight((select id from fixture_ids where kind='pet'),10,'kg',(now() at time zone 'America/Denver')::date)$$,'23514','Weight entries require an active patient','Deceased patients cannot receive new weights');
select throws_ok($$select public.save_clinical_encounter(null,(select id from fixture_ids where kind='pet'),null,now(),'clinic','','','','','')$$,'23514','New encounters require an active patient','Deceased patients cannot receive new encounters');
select set_config('request.jwt.claims','{"sub":"31000000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select is((select count(*) from public.clinical_encounters),0::bigint,'Inactive staff cannot read clinical records');
select throws_ok($$select public.search_clients('',250)$$,'42501','Active staff access required','Inactive staff cannot search clients');
select throws_ok($$select public.record_patient_weight((select id from fixture_ids where kind='pet'),10,'kg',(now() at time zone 'America/Denver')::date)$$,'42501','Active staff access required','Inactive staff cannot write clinical records');
set local role anon;
select throws_ok($$select * from public.clinical_encounters$$,'42501','permission denied for table clinical_encounters','Anonymous clinical reads denied');
select throws_ok($$select public.search_clients('',250)$$,'42501','permission denied for function search_clients','Anonymous RPC access denied');
reset role;
select * from finish();
rollback;
