begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();

-- The compatibility fixtures use the same mandatory prepare path as the browser.
create function pg_temp.queue_prepared(p_actor_id uuid,p_request_id uuid,p_conversation_id uuid,p_channel text,p_recipient text,p_subject text,p_body text,p_attachment_ids uuid[] default '{}') returns public.communication_outbox language plpgsql as $$
begin
 if not exists(select 1 from public.communication_prepared_requests where request_id=p_request_id) then
  perform public.prepare_message_request(p_actor_id,p_request_id,'fixture:'||p_request_id,p_conversation_id,p_channel,p_recipient,p_subject,p_body,p_attachment_ids);
 end if;
 return public.enqueue_communication(p_actor_id,p_request_id,p_conversation_id,p_channel,p_recipient,p_subject,p_body,p_attachment_ids);
end $$;

insert into auth.users(id,email,raw_user_meta_data) values
('51000000-0000-4000-8000-000000000001','outbox-staff@example.test','{"first_name":"Outbox","last_name":"Staff"}');
create temp table fixture_ids(kind text primary key,id uuid);
grant all on fixture_ids to authenticated,service_role;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"51000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fixture_ids select 'client',id from public.save_client(auth.uid(),null,null,'Outbox','Family','+13035550100','outbox@example.test','EMAIL',null,null);
reset role;
insert into public.conversations(id,client_id) values('51000000-0000-4000-8000-000000000002',(select id from fixture_ids where kind='client'));
set local role authenticated;
insert into fixture_ids select 'email',id from pg_temp.queue_prepared(auth.uid(),'51000000-0000-4000-8000-000000000003','51000000-0000-4000-8000-000000000002','EMAIL','outbox@example.test','Visit','Synthetic email');
select lives_ok($$select pg_temp.queue_prepared(auth.uid(),'51000000-0000-4000-8000-000000000003','51000000-0000-4000-8000-000000000002','EMAIL','outbox@example.test','Visit','Synthetic email')$$,'Unchanged stable UUID returns existing request');
select is((select count(*) from public.communication_outbox),1::bigint,'Duplicate intent creates one outbox row');
select is((select count(*) from public.messages where conversation_id='51000000-0000-4000-8000-000000000002'),1::bigint,'Duplicate intent creates one message');
select throws_ok($$select pg_temp.queue_prepared(auth.uid(),'51000000-0000-4000-8000-000000000003','51000000-0000-4000-8000-000000000002','EMAIL','outbox@example.test','Visit','Changed')$$,'23505',null,'UUID cannot be reused for changed content');
select throws_ok($$select pg_temp.queue_prepared(auth.uid(),gen_random_uuid(),'51000000-0000-4000-8000-000000000002','EMAIL','wrong@example.test','Visit','Synthetic')$$,'42501',null,'Recipient mismatch denied');
select throws_ok($$select pg_temp.queue_prepared(auth.uid(),gen_random_uuid(),'51000000-0000-4000-8000-000000000002','SMS','+13035550100','','Synthetic')$$,'42501',null,'SMS without consent denied');
select throws_ok($$select pg_temp.queue_prepared(auth.uid(),gen_random_uuid(),'51000000-0000-4000-8000-000000000002','EMAIL','outbox@example.test','Visit','Synthetic',array[gen_random_uuid()])$$,'23514',null,'Attachments rejected until authorized record release exists');
select throws_ok($$update public.communication_outbox set body='rewrite'$$,'42501',null,'Staff cannot rewrite immutable intent');
select throws_ok($$select public.claim_communication()$$,'42501',null,'Staff cannot claim service jobs');
reset role;
set local role service_role;
select set_config('request.jwt.claims','{"role":"service_role"}',true);
insert into fixture_ids select 'lease',lease_token from public.claim_communication();
select is((select state from public.communication_outbox where id=(select id from fixture_ids where kind='email')),'claimed','Worker atomically claims a lease');
select is((public.claim_communication()).id,null::uuid,'Second worker cannot claim active lease');
select lives_ok($$select public.start_communication_attempt((select id from fixture_ids where kind='email'),(select id from fixture_ids where kind='lease'),'{"from":"care@example.test","reply_to":"care@example.test"}')$$,'Worker starts audited provider attempt');
select throws_ok($$select public.start_communication_attempt((select id from fixture_ids where kind='email'),(select id from fixture_ids where kind='lease'),'{"from":"care@example.test","reply_to":"care@example.test"}')$$,'40001',null,'Same lease cannot start two provider requests');
select lives_ok($$select public.finish_communication_attempt((select id from fixture_ids where kind='email'),(select id from fixture_ids where kind='lease'),'uncertain',null,'network_timeout')$$,'Connection ambiguity persists as uncertain');
reset role;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"51000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
reset role;
update public.communication_outbox set first_attempt_at=now()-interval '24 hours' where id=(select id from fixture_ids where kind='email');
set local role authenticated;
select throws_ok($$select public.retry_communication(auth.uid(),(select id from fixture_ids where kind='email'))$$,'42501',null,'Legacy public retry cannot bypass reconciliation');
reset role;
update public.communication_outbox set first_attempt_at=now() where id=(select id from fixture_ids where kind='email');
set local role authenticated;
select throws_ok($$select public.retry_communication(auth.uid(),(select id from fixture_ids where kind='email'))$$,'42501',null,'Uncertain email is now service-reconciliation-only');
-- Owner-only historical retry fixture independently proves frozen sender/final-attempt guards.
reset role;update communication_outbox set state='pending',attempt_started_at=null where id=(select id from fixture_ids where kind='email');
reset role;
set local role service_role;
select set_config('request.jwt.claims','{"role":"service_role"}',true);
update fixture_ids set id=(public.claim_communication()).lease_token where kind='lease';
select throws_ok($$select public.start_communication_attempt((select id from fixture_ids where kind='email'),(select id from fixture_ids where kind='lease'),'{"from":"changed@example.test","reply_to":"care@example.test"}')$$,'23514',null,'Retry cannot change frozen sender metadata');
select lives_ok($$select public.start_communication_attempt((select id from fixture_ids where kind='email'),(select id from fixture_ids where kind='lease'),'{"from":"care@example.test","reply_to":"care@example.test"}')$$,'Unchanged provider payload retry allowed');
select lives_ok($$select public.finish_communication_attempt((select id from fixture_ids where kind='email'),(select id from fixture_ids where kind='lease'),'accepted','provider-email-id',null)$$,'Provider acceptance persists');
select is((select state from public.communication_outbox where id=(select id from fixture_ids where kind='email')),'accepted','Acceptance never means delivery');
select is((select delivered_at from public.communication_outbox where id=(select id from fixture_ids where kind='email')),null::timestamptz,'No delivery timestamp before provider event');
select lives_ok($$select public.record_communication_delivery('resend','event-1','provider-email-id','delivered')$$,'Verified delivery event marks delivered');
select lives_ok($$select public.record_communication_delivery('resend','event-1','provider-email-id','delivered')$$,'Duplicate delivery event is idempotent');
select is((select count(*) from public.communication_delivery_events),1::bigint,'Delivery event stored once');
select lives_ok($$select public.record_communication_delivery('resend','event-2','provider-email-id','failed')$$,'Late contradictory event retained');
select is((select state from public.communication_outbox where id=(select id from fixture_ids where kind='email')),'delivered','Late failure cannot regress delivered receipt');
reset role;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"51000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
reset role;
insert into public.sms_consent(client_id,phone_number,opted_in) values((select id from fixture_ids where kind='client'),'+13035550100',true);
set local role authenticated;
insert into fixture_ids select 'sms',id from pg_temp.queue_prepared(auth.uid(),gen_random_uuid(),'51000000-0000-4000-8000-000000000002','SMS','+13035550100','','Synthetic SMS');
reset role;
set local role service_role;
select set_config('request.jwt.claims','{"role":"service_role"}',true);
update fixture_ids set id=(public.claim_communication()).lease_token where kind='lease';
select lives_ok($$select public.start_communication_attempt((select id from fixture_ids where kind='sms'),(select id from fixture_ids where kind='lease'),'{"from":"+13035550199","account_sid":"ACsynthetic"}')$$,'SMS attempt starts only after consent');
reset role;
update public.communication_outbox set lease_expires_at=now()-interval '1 minute' where id=(select id from fixture_ids where kind='sms');
set local role service_role;
select is((public.claim_communication()).id,null::uuid,'Expired in-flight SMS is not reclaimed');
select is((select state from public.communication_outbox where id=(select id from fixture_ids where kind='sms')),'uncertain','Expired in-flight lease becomes uncertain');
select is((select outcome from public.communication_attempts where outbox_id=(select id from fixture_ids where kind='sms')),'uncertain','Expired attempt retains uncertainty audit');
reset role;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"51000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select throws_ok($$select public.retry_communication(auth.uid(),(select id from fixture_ids where kind='sms'))$$,'42501',null,'Uncertain SMS cannot blindly retry');
select lives_ok($$select public.suppress_communication(auth.uid(),'SMS','+13035550100','Client requested STOP')$$,'Staff can suppress a recipient');
select throws_ok($$select pg_temp.queue_prepared(auth.uid(),gen_random_uuid(),'51000000-0000-4000-8000-000000000002','SMS','+13035550100','','Synthetic SMS')$$,'42501',null,'Suppression overrides stored consent');
select throws_ok($$select public.reconcile_communication((select id from fixture_ids where kind='sms'),'accepted','SMreceipt','Provider dashboard evidence')$$,'42501',null,'Staff cannot manufacture reconciliation outcomes');
reset role;
set local role service_role;
select set_config('request.jwt.claims','{"role":"service_role"}',true);
select throws_ok($$select public.reconcile_communication((select id from fixture_ids where kind='sms'),'accepted','SMreceipt','')$$,'23514',null,'Reconciliation requires evidence reference');
select lives_ok($$select public.reconcile_communication((select id from fixture_ids where kind='sms'),'accepted','SMreceipt','Provider dashboard evidence record 123')$$,'Service can resolve unknown SMS to known provider receipt');
select is((select state from public.communication_outbox where id=(select id from fixture_ids where kind='sms')),'accepted','Reconciliation confirms acceptance not delivery');
select is((select count(*) from public.communication_reconciliations),1::bigint,'Reconciliation evidence retained once');
reset role;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"51000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fixture_ids select 'blocked',id from pg_temp.queue_prepared(auth.uid(),gen_random_uuid(),'51000000-0000-4000-8000-000000000002','EMAIL','outbox@example.test','Visit','Synthetic preflight suppression');
reset role;
set local role service_role;
select set_config('request.jwt.claims','{"role":"service_role"}',true);
update fixture_ids set id=(public.claim_communication()).lease_token where kind='lease';
reset role;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"51000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select public.suppress_communication(auth.uid(),'EMAIL','outbox@example.test','Stop emails');
reset role;
set local role service_role;
select set_config('request.jwt.claims','{"role":"service_role"}',true);
select is((public.start_communication_attempt((select id from fixture_ids where kind='blocked'),(select id from fixture_ids where kind='lease'),'{"from":"care@example.test","reply_to":"care@example.test"}')).state,'failed','Suppression after claim blocks provider attempt');
select is((select count(*) from public.communication_attempts where outbox_id=(select id from fixture_ids where kind='blocked')),0::bigint,'Blocked preflight creates no provider attempt');
reset role;
select throws_ok($$update public.messages set content='Altered' where id=(select message_id from public.communication_outbox where id=(select id from fixture_ids where kind='email'))$$,'23514',null,'Linked conversation message content cannot diverge from outbox');
select throws_ok($$update public.messages set is_internal=true where id=(select message_id from public.communication_outbox where id=(select id from fixture_ids where kind='email'))$$,'23514',null,'Queued outbound message cannot become an internal note');
select throws_ok($$delete from public.messages where id=(select message_id from public.communication_outbox where id=(select id from fixture_ids where kind='email'))$$,'23514',null,'Queued message history cannot be deleted');
select lives_ok($$update public.messages set triage_reason='Staff reviewed priority' where id=(select message_id from public.communication_outbox where id=(select id from fixture_ids where kind='email'))$$,'Non-content triage metadata remains editable');
select * from finish();
rollback;
