begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,raw_user_meta_data) values('db420000-0000-4000-8000-000000000001','external-admin@example.test','{}'),('db420000-0000-4000-8000-000000000002','external-dvm@example.test','{}'),('db420000-0000-4000-8000-000000000003','external-other-admin@example.test','{}');
insert into user_roles(user_id,role) values('db420000-0000-4000-8000-000000000001','ADMIN'),('db420000-0000-4000-8000-000000000002','DVM'),('db420000-0000-4000-8000-000000000003','ADMIN');
create temp table fx(k text primary key,id uuid);grant all on fx to authenticated,service_role;
create temp table data(k text primary key,v jsonb);grant all on data to authenticated,service_role;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"db420000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'client',id from save_client(auth.uid(),null,null,'External','Family',null,null,'EMAIL',null,null);
insert into fx select 'pet',id from save_patient(null,(select id from fx where k='client'),null,'One','Dog',null,null,'unknown',null,'unknown','unknown',null,null,null);
insert into fx select 'other',id from save_patient(null,(select id from fx where k='client'),null,'Two','Cat',null,null,'unknown',null,'unknown','unknown',null,null,null);
insert into fx select k,gen_random_uuid() from unnest(array['mapping','snapshot','doc','replacement-doc','other-doc','receipt','replacement-receipt','record','replacement-record','ack']) k;
reset role;
insert into ezyvet_import_snapshots(id,source_origin,source_site_uid,resource,external_id,payload,payload_hash,first_seen_by) values((select id from fx where k='snapshot'),'https://api.trial.ezyvet.com','external-test-site','animal','77','{"id":77}','synthetic-hash','db420000-0000-4000-8000-000000000001');
insert into ezyvet_record_links(id,request_id,request_hash,source_origin,source_site_uid,resource,external_id,snapshot_id,head_version,client_id,pet_id,local_version,action,reason,approved_by) values((select id from fx where k='mapping'),gen_random_uuid(),'mapping-hash','https://api.trial.ezyvet.com','external-test-site','animal','77',(select id from fx where k='snapshot'),1,(select id from fx where k='client'),(select id from fx where k='pet'),1,'link','Synthetic approved mapping','db420000-0000-4000-8000-000000000001');
-- Synthetic metadata/digests only; actual byte transport tested by the separate Edge fixture.
create function pg_temp.ready_doc(p_id uuid,p_pet uuid) returns void language plpgsql security definer set search_path=public as $$declare d public.patient_documents;begin
 d:=prepare_patient_document(p_id,p_pet,null,'synthetic.pdf','application/pdf',12,'medical_record','Manual export',null,'internal');
 insert into storage.objects(bucket_id,name,metadata) values('patient-documents',d.file_path,'{"size":12,"mimetype":"application/pdf"}');perform finalize_patient_document(p_id);
end $$;
select pg_temp.ready_doc((select id from fx where k='doc'),(select id from fx where k='pet'));
select pg_temp.ready_doc((select id from fx where k='replacement-doc'),(select id from fx where k='pet'));
select pg_temp.ready_doc((select id from fx where k='other-doc'),(select id from fx where k='other'));
insert into data values('received',jsonb_build_object('at',clock_timestamp()));
create function pg_temp.stage(p_id uuid,p_doc uuid,p_prior uuid default null,p_version integer default 1,p_reason text default 'Reviewed manual export') returns jsonb language sql as $$select to_jsonb(stage_external_record_receipt(p_id,(select id from fx where k='mapping'),p_version,p_doc,2,'export-1',(select (v->>'at')::timestamptz from data where k='received'),p_prior,p_reason));$$;
create function pg_temp.approve(p_id uuid,p_receipt text default 'receipt',p_capture text default 'capture') returns jsonb language sql as $$select to_jsonb(approve_external_record_import(p_id,(select (v->>'id')::uuid from data where k=p_receipt),(select v->>'receipt_hash' from data where k=p_receipt),(select v->>'capture_hash' from data where k=p_capture),true));$$;
insert into data select 'before',jsonb_build_object('encounters',(select count(*) from clinical_encounters),'problems',(select count(*) from patient_problems),'weights',(select count(*) from patient_weights),'invoices',(select count(*) from billing_invoices),'treatments',(select count(*) from patient_treatments),'stock',(select count(*) from inventory_movements),'payments',(select count(*) from invoice_payments),'pets',(select jsonb_agg(to_jsonb(p)) from pets p where id in (select id from fx where k in ('pet','other'))));
set local role authenticated;
select throws_ok($$select pg_temp.stage(gen_random_uuid(),(select id from fx where k='other-doc'))$$,'42501',null,'Mapped patient cannot use another patient document');
select throws_ok($$select pg_temp.stage(gen_random_uuid(),(select id from fx where k='doc'),null,0)$$,'40001',null,'Stale patient cannot stage');
insert into data select 'receipt',pg_temp.stage((select id from fx where k='receipt'),(select id from fx where k='doc'));
select lives_ok($$select pg_temp.stage((select id from fx where k='receipt'),(select id from fx where k='doc'))$$,'Exact staging retry returns original receipt');
select throws_ok($$select pg_temp.stage((select id from fx where k='receipt'),(select id from fx where k='doc'),null,1,'Changed reason')$$,'23505',null,'Changed retry cannot replace review');
select is(jsonb_array_length(list_external_record_receipts((select id from fx where k='pet'))->'receipts'),1,'Lost browser pointer can discover owned receipt');
select throws_ok($$select capture_external_record_bytes((select id from fx where k='receipt'),auth.uid(),(select v->>'receipt_hash' from data where k='receipt'),2,repeat('a',64),12,'application/pdf')$$,'42501',null,'Staff cannot assert verified bytes');
select throws_ok($$select pg_temp.approve((select id from fx where k='record'))$$,'42501',null,'Unverified file cannot be approved');
set local role service_role;
select throws_ok($$select external_record_capture_context((select id from fx where k='receipt'),'db420000-0000-4000-8000-000000000003')$$,'42501',null,'Capture binds original actor');
select throws_ok($$select capture_external_record_bytes((select id from fx where k='receipt'),'db420000-0000-4000-8000-000000000001',(select v->>'receipt_hash' from data where k='receipt'),2,repeat('a',64),13,'application/pdf')$$,'23514',null,'Capture rejects changed byte metadata');
insert into data select 'capture',to_jsonb(capture_external_record_bytes((select id from fx where k='receipt'),'db420000-0000-4000-8000-000000000001',(select v->>'receipt_hash' from data where k='receipt'),2,repeat('a',64),12,'application/pdf'));
select lives_ok($$select capture_external_record_bytes((select id from fx where k='receipt'),'db420000-0000-4000-8000-000000000001',(select v->>'receipt_hash' from data where k='receipt'),2,repeat('a',64),12,'application/pdf')$$,'Capture replay is exact');
select throws_ok($$select capture_external_record_bytes((select id from fx where k='receipt'),'db420000-0000-4000-8000-000000000001',(select v->>'receipt_hash' from data where k='receipt'),2,repeat('b',64),12,'application/pdf')$$,'23505',null,'New digest cannot overwrite original');
select throws_ok($$select pg_temp.approve((select id from fx where k='record'))$$,'42501',null,'Service cannot approve clinical preservation');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"db420000-0000-4000-8000-000000000003","role":"authenticated"}',true);
select is(recover_external_record_receipt((select id from fx where k='receipt')),null::jsonb,'Other administrator cannot recover original intent');
select is(jsonb_array_length(list_external_record_receipts((select id from fx where k='pet'))->'receipts'),0,'Owned discovery excludes other administrator');
select throws_ok($$select pg_temp.approve((select id from fx where k='record'))$$,'42501',null,'Other administrator cannot approve original intent');
select set_config('request.jwt.claims','{"sub":"db420000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select lives_ok($$select pg_temp.approve((select id from fx where k='record'))$$,'Exact verified original preserved');
select lives_ok($$select pg_temp.approve((select id from fx where k='record'))$$,'Approval replay creates no duplicate');
select throws_ok($$select pg_temp.approve(gen_random_uuid())$$,'40001',null,'Different UUID cannot duplicate series original');
select is(jsonb_array_length(read_external_record_history((select id from fx where k='pet'))#>'{records,0,acknowledgments}'),0,'Preservation never asserts clinician review');
select throws_ok($$select acknowledge_external_record((select id from fx where k='ack'),(select id from fx where k='record'),(select id from fx where k='pet'),(select v->>'capture_hash' from data where k='capture'),2,true)$$,'42501',null,'ADMIN alone cannot acknowledge as DVM');
select set_config('request.jwt.claims','{"sub":"db420000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select lives_ok($$select acknowledge_external_record((select id from fx where k='ack'),(select id from fx where k='record'),(select id from fx where k='pet'),(select v->>'capture_hash' from data where k='capture'),2,true)$$,'DVM independently acknowledges exact file');
select lives_ok($$select acknowledge_external_record((select id from fx where k='ack'),(select id from fx where k='record'),(select id from fx where k='pet'),(select v->>'capture_hash' from data where k='capture'),2,true)$$,'Acknowledgment retry idempotent');
select is((recover_external_record_acknowledgment((select id from fx where k='ack'))).id,(select id from fx where k='ack'),'DVM can recover exact acknowledgment after pointer loss');
select ok(recover_external_record_acknowledgment(gen_random_uuid()) is null,'Missing acknowledgment recovery is null');
select is(read_external_record_history((select id from fx where k='pet'))#>>'{records,0,source_site_uid}','external-test-site','Clinical projection distinguishes source account identity');
select is(jsonb_array_length(read_external_record_history((select id from fx where k='other'))->'records'),0,'History is patient-scoped');
select set_config('request.jwt.claims','{"sub":"db420000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select throws_ok($$select pg_temp.stage(gen_random_uuid(),(select id from fx where k='replacement-doc'))$$,'40001',null,'Replacement requires exact reviewed previous head');
insert into data select 'replacement-receipt',pg_temp.stage((select id from fx where k='replacement-receipt'),(select id from fx where k='replacement-doc'),(select id from fx where k='record'));
set local role service_role;
insert into data select 'replacement-capture',to_jsonb(capture_external_record_bytes((select id from fx where k='replacement-receipt'),'db420000-0000-4000-8000-000000000001',(select v->>'receipt_hash' from data where k='replacement-receipt'),2,repeat('b',64),12,'application/pdf'));
set local role authenticated;
select pg_temp.approve((select id from fx where k='replacement-record'),'replacement-receipt','replacement-capture');
select is(jsonb_array_length(read_external_record_history((select id from fx where k='pet'))->'records'),2,'Original retained alongside replacement');
select is((select jsonb_array_length(v->'acknowledgments') from jsonb_array_elements(read_external_record_history((select id from fx where k='pet'))->'records') v where v->>'id'=(select id::text from fx where k='replacement-record')),0,'Replacement does not inherit original acknowledgment');
select is((select v->>'kind' from jsonb_array_elements(read_external_record_history((select id from fx where k='pet'))->'records') v where v->>'id'=(select id::text from fx where k='replacement-record')),'replacement','Replacement labeled separately');
select public.void_patient_document((select id from fx where k='doc'),2,'Superseded original retained');
select lives_ok($$select pg_temp.approve((select id from fx where k='record'))$$,'Committed approval recovered even after document void');
select lives_ok($$select pg_temp.stage((select id from fx where k='receipt'),(select id from fx where k='doc'))$$,'Committed stage recovered after document void');
select is(recover_external_record_receipt((select id from fx where k='receipt'))#>>'{record,id}',(select id::text from fx where k='record'),'Historical recovery retains original approval');
select is(list_external_record_receipts((select id from fx where k='pet'),null,null,1)->>'has_more','true','Receipt history is bounded with continuation');
reset role;
select is(jsonb_build_object('encounters',(select count(*) from clinical_encounters),'problems',(select count(*) from patient_problems),'weights',(select count(*) from patient_weights),'invoices',(select count(*) from billing_invoices),'treatments',(select count(*) from patient_treatments),'stock',(select count(*) from inventory_movements),'payments',(select count(*) from invoice_payments),'pets',(select jsonb_agg(to_jsonb(p)) from pets p where id in (select id from fx where k in ('pet','other')))),(select v from data where k='before'),'Native chart and billing counts and patient values unchanged');
select throws_ok($$delete from external_record_receipts$$,'23514',null,'Receipt immutable');
select throws_ok($$update external_record_versions set review_reason='Changed'$$,'23514',null,'Approval immutable');
select throws_ok($$update external_record_byte_captures set content_sha256=repeat('f',64)$$,'23514',null,'Byte proof immutable');
select throws_ok($$delete from external_record_acknowledgments$$,'23514',null,'DVM acknowledgment immutable');
set local role authenticated;
select throws_ok($$select * from external_record_receipts$$,'42501',null,'Authenticated direct staging table read denied');
reset role;
update profiles set is_active=false where id='db420000-0000-4000-8000-000000000001';
set local role authenticated;
select throws_ok($$select recover_external_record_receipt((select id from fx where k='receipt'))$$,'42501',null,'Inactive actor recovery denied');
set local role anon;
select throws_ok($$select read_external_record_history((select id from fx where k='pet'))$$,'42501',null,'Anonymous history denied');
select * from finish();rollback;
