begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select no_plan();
-- FIXTURE_BEGIN: owner-only synthetic source observations and reviewed mapping.
insert into auth.users(id,email,raw_user_meta_data) values('db560000-0000-4000-8000-000000000001','clinical-import-admin@example.test','{}'),('db560000-0000-4000-8000-000000000002','clinical-import-other@example.test','{}');
update public.profiles set is_active = true where id in ('db560000-0000-4000-8000-000000000001','db560000-0000-4000-8000-000000000002');
insert into public.user_roles (user_id, role) values ('db560000-0000-4000-8000-000000000001','STAFF'),('db560000-0000-4000-8000-000000000002','STAFF');

insert into user_roles(user_id,role) values('db560000-0000-4000-8000-000000000001','ADMIN'),('db560000-0000-4000-8000-000000000002','ADMIN');
create temp table fx(k text primary key,id uuid);create temp table data(k text primary key,v jsonb);grant all on fx,data to authenticated,service_role;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db560000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'client',id from save_client(auth.uid(),null,null,'Clinical','Import','+13035550199','clinical-import@example.test','EMAIL',null,null);
insert into fx select 'pet',id from save_patient(null,(select id from fx where k='client'),null,'Scoped dog','Dog',null,null,'unknown',null,'unknown','unknown',null,null,null);
insert into fx select k,gen_random_uuid() from unnest(array['mapping','mapping2','snapshot','snapshot2','legacy','terminal','run','history','other-run']) k;
reset role;
insert into ezyvet_import_snapshots(id,source_origin,source_site_uid,resource,external_id,payload,payload_hash,first_seen_by) select id,'https://api.trial.ezyvet.com','prescriptionitem-test-site','animal',case when k='snapshot' then '77' else '88' end,jsonb_build_object('id',case when k='snapshot' then 77 else 88 end),k,'db560000-0000-4000-8000-000000000001' from fx where k in ('snapshot','snapshot2');
insert into ezyvet_record_links(id,request_id,request_hash,source_origin,source_site_uid,resource,external_id,snapshot_id,head_version,client_id,pet_id,local_version,action,reason,approved_by)
select id,gen_random_uuid(),k,'https://api.trial.ezyvet.com','prescriptionitem-test-site','animal',case when k='mapping' then '77' else '88' end,(select id from fx where k=case when m.k='mapping' then 'snapshot' else 'snapshot2' end),1,(select id from fx where k='client'),(select id from fx where k='pet'),1,'link','Synthetic approved mapping','db560000-0000-4000-8000-000000000001' from fx m where k in ('mapping','mapping2');
insert into fx values('prescription-run',gen_random_uuid());
insert into data select 'prescription-run',claim_ezyvet_prescription_import((select id from fx where k='prescription-run'),'db560000-0000-4000-8000-000000000001','prescriptionitem-test-site','prescription','https://api.trial.ezyvet.com',(select id from fx where k='mapping'));
select stage_ezyvet_import_page((select id from fx where k='prescription-run'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='prescription-run'),1,true,'[{"external_id":"101","payload":{"id":101,"animal_id":77,"instructions":"Source prescriptionation"}},{"external_id":"102","payload":{"id":102,"animal_id":77}}]');
insert into data select 'prescription',list_ezyvet_prescription_candidates((select id from fx where k='mapping'),'prescription')->'candidates'->0;
-- Choose external prescription 101 independent of creation-order ties.
update data set v=(select c from jsonb_array_elements(list_ezyvet_prescription_candidates((select id from fx where k='mapping'),'prescription')->'candidates') c where c->>'external_id'='101') where k='prescription';
insert into data values('items','[{"external_id":"501","payload":{"id":501,"prescription_id":101,"product_id":null,"date_start":null,"remaining":"unknown","qty":"outside units","serial_number":"outside author","instructions":"<script>outside prose</script>"}}]');
insert into data select 'legacy',to_jsonb(claim_ezyvet_import_core((select id from fx where k='legacy'),'db560000-0000-4000-8000-000000000001','prescriptionitem-test-site','prescriptionitem','https://api.trial.ezyvet.com'));
select stage_ezyvet_import_page_core((select id from fx where k='legacy'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='legacy'),1,false,(select v from data where k='items'));
update ezyvet_import_runs set retry_after=null,lease_until=null;
insert into data select 'terminal',to_jsonb(claim_ezyvet_import_core((select id from fx where k='terminal'),'db560000-0000-4000-8000-000000000001','prescriptionitem-test-site','prescriptionitem','https://api.trial.ezyvet.com'));
select stage_ezyvet_import_page_core((select id from fx where k='terminal'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='terminal'),1,true,'[]');
update ezyvet_import_runs set retry_after=null,lease_until=null;
reset role;
insert into data select 'review-run',claim_ezyvet_prescriptionitem_import((select id from fx where k='run'),'db560000-0000-4000-8000-000000000001','prescriptionitem-test-site','prescriptionitem','https://api.trial.ezyvet.com',(select id from fx where k='mapping'),(select (v->>'id')::uuid from data where k='prescription'),(select v->>'payload_hash' from data where k='prescription'),(select (v->>'observed_head_version')::integer from data where k='prescription'));
select stage_ezyvet_import_page((select id from fx where k='run'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='review-run'),1,false,(select v from data where k='items'));
update ezyvet_import_runs set retry_after=null where id=(select id from fx where k='run');
insert into data select 'repeat-claim',claim_ezyvet_prescriptionitem_import((select id from fx where k='run'),'db560000-0000-4000-8000-000000000001','prescriptionitem-test-site','prescriptionitem','https://api.trial.ezyvet.com',(select id from fx where k='mapping'),(select (v->>'id')::uuid from data where k='prescription'),(select v->>'payload_hash' from data where k='prescription'),1);
select stage_ezyvet_import_page((select id from fx where k='run'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='repeat-claim'),2,true,(select v from data where k='items'));

insert into data select 'context',ezyvet_prescription_source_context((select id from fx where k='pet'),(select id from fx where k='run'));

insert into fx values('product',gen_random_uuid());
insert into catalog_products(id,name,kind,unit,unit_price_cents,created_by) select id,'Synthetic medication','medication','tablet',1000,'db560000-0000-4000-8000-000000000001' from fx where k='product';
insert into data select 'review',jsonb_build_object('reason','Historical interpretation only','outside_author',null,'prescribed_on',null,'prescription_date_status','uninterpreted','status','unknown','completeness','partial','partial_reason','Parent source list not supplied','replaces_id',null,'expected_predecessor_hash',null,'items',jsonb_build_array(jsonb_build_object('snapshot_id',v#>'{items,0,snapshot_id}','start_on',null,'start_date_status','unknown','product_id',(select id from fx where k='product'),'product_version',1,'note','No dose or refill inferred'))) from data where k='context';

insert into user_roles(user_id,role) values('db560000-0000-4000-8000-000000000001','DVM'),('db560000-0000-4000-8000-000000000002','DVM');
insert into fx select k,gen_random_uuid() from unnest(array['approval','duplicate','correction','competing','stale','abandon']) k;
insert into data select 'payload',jsonb_build_object('item_run_id',(select id from fx where k='run'),'patient_version',(select version from pets where id=(select id from fx where k='pet')),'interpretation',v) from data where k='review';
insert into data values('side-effects',jsonb_build_object('treatments',(select count(*) from patient_treatments),'invoices',(select count(*) from billing_invoices),'stock',(select count(*) from inventory_movements),'certificates',(select count(*) from vaccine_certificates),'reminders',(select count(*) from care_reminder_jobs),'outbox',(select count(*) from communication_outbox)));

insert into ezyvet_identity_heads(source_origin,source_site_uid,resource,external_id,snapshot_id,version) select source_origin,source_site_uid,resource,external_id,id,1 from ezyvet_import_snapshots where id=(select id from fx where k='snapshot');
insert into fx select k,gen_random_uuid() from unnest(array['migration','scope','binding']) k;
set local role authenticated;
select prepare_ezyvet_migration_run((select id from fx where k='migration'),'https://api.trial.ezyvet.com','prescriptionitem-test-site',jsonb_build_array(jsonb_build_object('id',(select id from fx where k='scope'),'mapping_id',(select id from fx where k='mapping'),'resource','prescriptionitem','parent_type','prescription','parent_snapshot_id',(select (v->>'id')::uuid from data where k='prescription'),'parent_head_version',1,'disposition','required','reason','Synthetic prescription header scope')));
select bind_ezyvet_migration_child((select id from fx where k='binding'),(select id from fx where k='scope'),(select id from fx where k='run'),'Synthetic prescription items');
insert into data select 'item',i from jsonb_array_elements(list_ezyvet_migration_items((select id from fx where k='binding'))->'items') i where i->>'external_id'='501' and i->>'page'='1';
create function pg_temp.receipts(bef integer default null,lim integer default 20) returns jsonb language sql as $$select list_ezyvet_migration_prescription_item_evidence((select id from fx where k='binding'),1,(v->>'snapshot_id')::uuid,v->>'evidence_hash',bef,lim) from data where k='item';$$;
select is(jsonb_array_length(pg_temp.receipts()->'approvals'),0,'Staged header is not approval');
insert into data select 'prepared',prepare_ezyvet_prescription_review((select id from fx where k='approval'),(select id from fx where k='pet'),(select v from data where k='payload'));
select is(jsonb_array_length(pg_temp.receipts()->'approvals'),0,'Prepared prescription is not approval');
insert into data select 'approved',approve_ezyvet_prescription_review((select id from fx where k='approval'),(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='prepared'),true);
select is(pg_temp.receipts()#>>'{approvals,0,source_current}','true','Approved source_current preserved');
select is(pg_temp.receipts()#>>'{approvals,0,completeness}','partial','Approved completeness preserved');
select is(pg_temp.receipts()#>>'{approvals,0,disposition}','selected','Item disposition preserved');
select is(pg_temp.receipts()#>>'{approvals,0,parent_matches}','true','Item parent_matches preserved');
select is(pg_temp.receipts()#>>'{approvals,0,exact_occurrence}','true','Item exact_occurrence preserved');
select is(pg_temp.receipts()#>>'{approvals,0,identity_observations}','2','Item identity_observations preserved');
select is(pg_temp.receipts()#>>'{approvals,0,matching_source_observations}','2','Item matching_source_observations preserved');
select is(pg_temp.receipts()#>>'{approvals,0,catalog_matched}','true','Item catalog_matched preserved');
select is(pg_temp.receipts()#>>'{approvals,0,start_date_status}','unknown','Item start_date_status preserved');
select is((select list_ezyvet_migration_prescription_item_evidence((select id from fx where k='binding'),2,(i->>'snapshot_id')::uuid,i->>'evidence_hash')#>>'{approvals,0,disposition}' from jsonb_array_elements(list_ezyvet_migration_items((select id from fx where k='binding'))->'items') i where i->>'page'='2'),'selected','Repeated page observation shares one selected medication');

select is(pg_temp.receipts()->>'local_prescribing_verified','false','No inferred local_prescribing_verified');
select is(pg_temp.receipts()->>'complete_coverage_verified','false','No inferred complete_coverage_verified');
select ok(not pg_temp.receipts()::text ~ 'outside prose|outside author|reason|original|payload_hash|request_hash|Historical interpretation|dose','Private prescription prose excluded');
insert into data select 'correction-payload',jsonb_set(v,'{interpretation}',(v->'interpretation')||jsonb_build_object('reason','Corrected outside author after review','outside_author','Outside clinician','items','[]'::jsonb,'replaces_id',(select v#>>'{receipt,id}' from data where k='approved'),'expected_predecessor_hash',(select v#>>'{receipt,version_hash}' from data where k='approved'))) from data where k='payload';
insert into data select 'correction-prepared',prepare_ezyvet_prescription_review((select id from fx where k='correction'),(select id from fx where k='pet'),(select v from data where k='correction-payload'));
select approve_ezyvet_prescription_review((select id from fx where k='correction'),(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='correction-prepared'),true);
select is(pg_temp.receipts(null,1)->>'next_before_version','2','Bounded version cursor');
select is(pg_temp.receipts()#>>'{approvals,0,disposition}','omitted','Correction explicitly omits item');
select is(pg_temp.receipts()#>'{approvals,0,catalog_matched}','null'::jsonb,'Omitted item has no inferred catalog match');
select is(pg_temp.receipts(2,1)#>>'{approvals,0,disposition}','selected','Earlier selection retained');
select is(pg_temp.receipts(2,1)#>>'{approvals,0,superseded}','true','Earlier approval retained');
select is(pg_temp.receipts(2,1)->>'has_more','false','Terminal page');
select throws_ok($$select list_ezyvet_migration_prescription_item_evidence((select id from fx where k='binding'),1,(v->>'snapshot_id')::uuid,repeat('f',64)) from data where k='item'$$,'42501','Exact owned prescription item observation required','Forged hash denied');
select throws_ok($$select list_ezyvet_migration_prescription_item_evidence((select id from fx where k='binding'),3,(v->>'snapshot_id')::uuid,v->>'evidence_hash') from data where k='item'$$,'42501','Exact owned prescription item observation required','Wrong page denied');
select throws_ok($$select pg_temp.receipts(null,101)$$,'23514','Invalid prescription item evidence identity or cursor','Unbounded read denied');
reset role;
update ezyvet_identity_heads set version=version+2 where resource='prescription' and external_id='101';
set local role authenticated;
select is(pg_temp.receipts()#>>'{approvals,0,source_current}','false','Header A to B to A invalidates context');
reset role;
insert into fx select k,gen_random_uuid() from unnest(array['new-header-run','new-item-run','new-approval']) k;
update ezyvet_import_runs set retry_after=null where source_site_uid='prescriptionitem-test-site';
insert into data select 'new-header-claim',claim_ezyvet_prescription_import((select id from fx where k='new-header-run'),'db560000-0000-4000-8000-000000000001','prescriptionitem-test-site','prescription','https://api.trial.ezyvet.com',(select id from fx where k='mapping'));
select stage_ezyvet_import_page((select id from fx where k='new-header-run'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='new-header-claim'),1,true,'[{"external_id":"101","payload":{"id":101,"animal_id":77,"instructions":"Source prescriptionation"}}]');
insert into data select 'new-item-claim',claim_ezyvet_prescriptionitem_import((select id from fx where k='new-item-run'),'db560000-0000-4000-8000-000000000001','prescriptionitem-test-site','prescriptionitem','https://api.trial.ezyvet.com',(select id from fx where k='mapping'),(select (v->>'id')::uuid from data where k='prescription'),(select v->>'payload_hash' from data where k='prescription'),3);
select stage_ezyvet_import_page((select id from fx where k='new-item-run'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='new-item-claim'),1,true,(select jsonb_set(v,'{0,payload,remaining}', '"changed"') from data where k='items'));
set local role authenticated;
insert into data select 'new-payload',jsonb_set(jsonb_set(v,'{item_run_id}',to_jsonb((select id from fx where k='new-item-run'))),'{interpretation}',(v->'interpretation')||jsonb_build_object('replaces_id',(select id from fx where k='correction'),'expected_predecessor_hash',pg_temp.receipts()#>>'{approvals,0,version_hash}')) from data where k='correction-payload';
insert into data select 'new-prepared',prepare_ezyvet_prescription_review((select id from fx where k='new-approval'),(select id from fx where k='pet'),(select v from data where k='new-payload'));
select approve_ezyvet_prescription_review((select id from fx where k='new-approval'),(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='new-prepared'),true);
select is(pg_temp.receipts()#>>'{approvals,0,source_current}','true','New header approval can be current while different from saved observation');
select is(pg_temp.receipts()#>>'{approvals,0,parent_matches}','false','New parent version is distinguished');
select is(pg_temp.receipts()#>>'{approvals,0,exact_occurrence}','false','Different item run is distinguished');
select is(pg_temp.receipts()#>>'{approvals,0,disposition}','different_source_version','Same item identity with changed source payload is distinguished');
select is(pg_temp.receipts()#>>'{approvals,0,matching_source_observations}','0','Changed payload does not receive old version credit');
select is(pg_temp.receipts()#>>'{approvals,0,identity_observations}','1','Changed payload retains item identity');

reset role;
update ezyvet_identity_heads set version=version+2 where resource='prescriptionitem' and external_id='501';
set local role authenticated;
select is(pg_temp.receipts()#>>'{approvals,0,source_current}','false','Item A to B to A invalidates source context');
select set_config('request.jwt.claims','{"sub":"db560000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select throws_ok($$select pg_temp.receipts()$$,'42501','Exact owned prescription item observation required','Other administrator denied');
reset role;
update profiles set is_active=false where id='db560000-0000-4000-8000-000000000001';
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db560000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select throws_ok($$select pg_temp.receipts()$$,'42501','Active administrator required','Inactive administrator denied');
reset role;
select ok(not has_function_privilege('anon','public.list_ezyvet_migration_prescription_item_evidence(uuid,integer,uuid,text,integer,integer)','execute'),'Anonymous execution denied');
select ok(not has_function_privilege('service_role','public.list_ezyvet_migration_prescription_item_evidence(uuid,integer,uuid,text,integer,integer)','execute'),'Worker execution denied');
select is(jsonb_build_object('treatments',(select count(*) from patient_treatments),'invoices',(select count(*) from billing_invoices),'stock',(select count(*) from inventory_movements),'certificates',(select count(*) from vaccine_certificates),'reminders',(select count(*) from care_reminder_jobs),'outbox',(select count(*) from communication_outbox)),(select v from data where k='side-effects'),'No native clinical, stock, billing or delivery effects');
select * from finish();rollback;
