begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select no_plan();
-- FIXTURE_BEGIN

insert into auth.users(id,email,raw_user_meta_data) values('db700000-0000-4000-8000-000000000001','attachment-admin@example.test','{}'),('db700000-0000-4000-8000-000000000002','attachment-other@example.test','{}');
insert into user_roles(user_id,role) values('db700000-0000-4000-8000-000000000001','ADMIN'),('db700000-0000-4000-8000-000000000002','ADMIN');
create temp table fx(k text primary key,id uuid);create temp table data(k text primary key,v jsonb);grant all on fx,data to authenticated,service_role;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db700000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'client',id from save_client(auth.uid(),null,null,'Attachment','Owner','+13035550196','attachment@example.test','EMAIL',null,null);
insert into fx select 'pet',id from save_patient(null,(select id from fx where k='client'),null,'Metadata dog','Dog',null,null,'unknown',null,'unknown','unknown',null,null,null);
insert into fx select k,gen_random_uuid() from unnest(array['mapping','animal-run','run','run2','other-run']) k;
reset role;
insert into data select 'animal',to_jsonb(claim_ezyvet_import((select id from fx where k='animal-run'),'db700000-0000-4000-8000-000000000001','attachment-test-site','animal','https://api.trial.ezyvet.com'));
select stage_ezyvet_import_page((select id from fx where k='animal-run'),'db700000-0000-4000-8000-000000000001',(select(v->>'lease_id')::uuid from data where k='animal'),1,true,'[{"external_id":"77","payload":{"id":77}}]');
insert into ezyvet_record_links(id,request_id,request_hash,source_origin,source_site_uid,resource,external_id,snapshot_id,head_version,client_id,pet_id,local_version,action,reason,approved_by)
select (select id from fx where k='mapping'),gen_random_uuid(),'synthetic-approved-mapping',s.source_origin,s.source_site_uid,s.resource,s.external_id,s.id,h.version,(select id from fx where k='client'),(select id from fx where k='pet'),1,'link','Synthetic reviewed mapping','db700000-0000-4000-8000-000000000001' from ezyvet_import_snapshots s join ezyvet_identity_heads h on h.snapshot_id=s.id where s.resource='animal' and s.source_site_uid='attachment-test-site';
insert into data values('observation',jsonb_build_object('external_id','701','file_id','42','metadata',jsonb_build_object('id','701','file_id','42','record_type','Animal','record_id','77','name','Synthetic report','mime_type','application/pdf','notes',null),'raw_record_sha256',repeat('a',64),'stable_metadata_sha256',repeat('b',64),'file_sha256',null));
insert into data select 'page',jsonb_build_object('contract_version','ezyvet_animal_attachment_metadata_v1','parent',jsonb_build_object('record_type','Animal','record_id','77'),'page',1,'complete',true,'pagination',jsonb_build_object('items_page',1,'items_page_total',1,'items_page_size',10,'items_total',2),'observations',jsonb_build_array(v,jsonb_set(v,'{raw_record_sha256}',to_jsonb(repeat('c',64)))),'page_sha256',repeat('d',64)) from data where k='observation';
insert into data values('side-effects',jsonb_build_object('treatments',(select count(*) from patient_treatments),'invoices',(select count(*) from billing_invoices),'stock',(select count(*) from inventory_movements),'outbox',(select count(*) from communication_outbox),'objects',(select count(*) from storage.objects)));

insert into data select 'run',claim_ezyvet_attachment_import((select id from fx where k='run'),'db700000-0000-4000-8000-000000000001','attachment-test-site','https://api.trial.ezyvet.com',(select id from fx where k='mapping'));
select stage_ezyvet_attachment_page((select id from fx where k='run'),'db700000-0000-4000-8000-000000000001',(select(v->>'lease_id')::uuid from data where k='run'),(select v from data where k='page'));
update ezyvet_import_runs set retry_after=null where resource='attachment';
insert into fx select k,gen_random_uuid() from unnest(array['capture','capture2','capture3','capture4']) k;
insert into fx select 'attachment-snapshot',snapshot_id from ezyvet_attachment_page_observations where run_id=(select id from fx where k='run') and ordinal=1;
-- FIXTURE_END
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db700000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select throws_ok($$select prepare_ezyvet_attachment_capture((select id from fx where k='capture'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,3,(select id from fx where k='attachment-snapshot'),1,repeat('b',64))$$,'42501',null,'Unobserved ordinal rejected');
select throws_ok($$select prepare_ezyvet_attachment_capture((select id from fx where k='capture'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,1,(select id from fx where k='attachment-snapshot'),1,repeat('f',64))$$,'42501',null,'Wrong stable digest rejected');
insert into data select 'capture',prepare_ezyvet_attachment_capture((select id from fx where k='capture'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,1,(select id from fx where k='attachment-snapshot'),1,repeat('b',64));
select is((select v->>'status' from data where k='capture'),'prepared','Explicit owned observation prepared');
select is((select v->>'file_id' from data where k='capture'),'42','File identity retained separately from attachment identity');
select ok(not((select v from data where k='capture') ?| array['lease_id','intent','object_path']),'Browser projection hides service data');
select is(prepare_ezyvet_attachment_capture((select id from fx where k='capture'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,1,(select id from fx where k='attachment-snapshot'),1,repeat('b',64)),(select v from data where k='capture'),'Lost preparation reply recovers exact immutable request');
select throws_ok($$select prepare_ezyvet_attachment_capture((select id from fx where k='capture'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,2,(select id from fx where k='attachment-snapshot'),1,repeat('b',64))$$,'42501',null,'Same UUID cannot switch duplicate ordinal');
select set_config('request.jwt.claims','{"sub":"db700000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select throws_ok($$select recover_ezyvet_attachment_capture((select id from fx where k='capture'),(select id from fx where k='mapping'))$$,'42501',null,'Other administrator cannot recover');
select is(jsonb_array_length(list_ezyvet_attachment_captures((select id from fx where k='mapping'))->'captures'),0,'Discovery is owner scoped');
select throws_ok($$select prepare_ezyvet_attachment_capture((select id from fx where k='capture2'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,1,(select id from fx where k='attachment-snapshot'),1,repeat('b',64))$$,'42501',null,'Another admin cannot capture the owned metadata run');
reset role;set local role service_role;
insert into data select 'claimed',claim_ezyvet_attachment_capture((select id from fx where k='capture'),'db700000-0000-4000-8000-000000000001');
select ok((select v->>'lease_id' is not null from data where k='claimed'),'Service worker receives lease');
select throws_ok($$select claim_ezyvet_attachment_capture((select id from fx where k='capture'),'db700000-0000-4000-8000-000000000001')$$,'55P03',null,'Concurrent worker cannot duplicate claim');
select throws_ok($$select claim_ezyvet_attachment_import((select id from fx where k='other-run'),'db700000-0000-4000-8000-000000000001','attachment-test-site','https://api.trial.ezyvet.com',(select id from fx where k='mapping'))$$,'55P03',null,'Metadata scan respects original capture source lease');
select throws_ok($$select reserve_ezyvet_attachment_original((select id from fx where k='capture'),'db700000-0000-4000-8000-000000000001',null,repeat('e',64),'application/pdf',12,repeat('a',64),repeat('c',64))$$,'40001',null,'Reserve requires current lease');
insert into data select 'reserved',reserve_ezyvet_attachment_original((select id from fx where k='capture'),'db700000-0000-4000-8000-000000000001',(select(v->>'lease_id')::uuid from data where k='claimed'),repeat('e',64),'application/pdf',12,repeat('a',64),repeat('c',64));
select is((select v#>>'{request,status}' from data where k='reserved'),'reserved','Verified byte intent reserves private object');
select isnt((select v#>>'{intent,before_raw_sha256}' from data where k='reserved'),(select v#>>'{intent,after_raw_sha256}' from data where k='reserved'),'Raw URL renewal digests need not match');
select throws_ok($$select reserve_ezyvet_attachment_original((select id from fx where k='capture'),'db700000-0000-4000-8000-000000000001',(select(v->>'lease_id')::uuid from data where k='claimed'),repeat('f',64),'application/pdf',12,repeat('a',64),repeat('c',64))$$,'23514',null,'Intent bytes cannot change');
select throws_ok($$select complete_ezyvet_attachment_capture((select id from fx where k='capture'),'db700000-0000-4000-8000-000000000001',(select(v->>'lease_id')::uuid from data where k='claimed'),(select(v#>>'{intent,id}')::uuid from data where k='reserved'),repeat('e',64),'application/pdf',12)$$,'23514',null,'Missing object cannot complete');
reset role;set local role authenticated;select set_config('request.jwt.claims','{"sub":"db700000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select lives_ok($$insert into storage.objects(bucket_id,name,metadata) select 'ezyvet-attachment-originals',v#>>'{intent,object_path}','{"size":12,"mimetype":"application/pdf"}'::jsonb from data where k='reserved'$$,'Owning JWT may insert only reserved object');
select is((select count(*)::integer from storage.objects where bucket_id='ezyvet-attachment-originals'),0,'Direct object reads denied even to uploader');
select throws_ok($$insert into storage.objects(bucket_id,name,metadata) values('ezyvet-attachment-originals','other/path','{}')$$,'42501',null,'Unreserved object upload denied');
reset role;set local role service_role;
insert into data select 'ready',complete_ezyvet_attachment_capture((select id from fx where k='capture'),'db700000-0000-4000-8000-000000000001',(select(v->>'lease_id')::uuid from data where k='claimed'),(select(v#>>'{intent,id}')::uuid from data where k='reserved'),repeat('e',64),'application/pdf',12);
select is((select v#>>'{request,status}' from data where k='ready'),'ready','Readback-attested original becomes ready');
select is((select v#>>'{request,capture,entry_method}' from data where k='ready'),'ezyvet_api_attachment_original_v1','Capture never claims manual export provenance');
select is(complete_ezyvet_attachment_capture((select id from fx where k='capture'),'db700000-0000-4000-8000-000000000001',null,(select(v#>>'{intent,id}')::uuid from data where k='reserved'),repeat('e',64),'application/pdf',12),(select v from data where k='ready'),'Lost completion reply recovers before lease validation');
select throws_ok($$select begin_discard_ezyvet_attachment_capture((select id from fx where k='capture'),'db700000-0000-4000-8000-000000000001')$$,'23514',null,'Captured object cannot be discarded');
reset role;
insert into fx select 'approval',gen_random_uuid();insert into fx select 'correction',gen_random_uuid();
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"db700000-0000-4000-8000-000000000001","role":"authenticated"}',true);
create function pg_temp.approve_original(k text default 'approval',previous_id uuid default null,attest boolean default true,title text default 'Reviewed canonical original') returns public.ezyvet_attachment_record_versions language sql as $$
 select approve_ezyvet_attachment_record((select id from fx where fx.k=$1),(select id from fx where fx.k='capture'),(select id from fx where fx.k='pet'),(select v#>>'{request,capture,capture_hash}' from data where data.k='ready'),$2,$4,'Synthetic verified original inspection',$3);
$$;
select throws_ok($$select pg_temp.approve_original('approval',null,false)$$,'23514',null,'Original approval requires explicit attestation');
insert into data select 'approved',to_jsonb(pg_temp.approve_original());
select is((select v->>'entry_method' from data where k='approved'),'staff_reviewed_api_attachment_v2','Approval identifies canonical original contract');
select is((select v#>>'{source_context,capture_contract}' from data where k='approved'),'canonical_api_original_v1','Stable metadata and file identity retain canonical provenance');
select is(to_jsonb(pg_temp.approve_original()),(select v from data where k='approved'),'Exact approval replay preserves saved record');
select throws_ok($$select pg_temp.approve_original('approval',null,true,'Different title')$$,'23505',null,'Approval UUID cannot change reviewed intent');
select throws_ok($$select pg_temp.approve_original('correction')$$,'40001',null,'Correction requires exact predecessor');
insert into data select 'corrected',to_jsonb(pg_temp.approve_original('correction',(select id from fx where k='approval')));
select is((select(v->>'version')::integer from data where k='corrected'),2,'Canonical original correction appends version2');
select is((select v#>>'{source_context,file_id}' from data where k='corrected'),(select v#>>'{request,file_id}' from data where k='ready'),'Separate file ID remains bound to approval');
select throws_ok($$select * from ezyvet_attachment_record_versions$$,'42501',null,'Approval table is not directly readable');
reset role;
select throws_ok($$update ezyvet_attachment_record_versions set title='changed'$$,'23514',null,'Privileged approval rewrites are rejected');
select ok(not has_function_privilege('anon','approve_ezyvet_attachment_record(uuid,uuid,uuid,text,uuid,text,text,boolean)','execute'),'Anonymous approval denied');
select ok(not has_function_privilege('service_role','approve_ezyvet_attachment_record(uuid,uuid,uuid,text,uuid,text,text,boolean)','execute'),'Worker cannot approve');
update ezyvet_identity_heads set version=version+1 where resource='animal' and external_id='77';
set local role authenticated;
select is(recover_ezyvet_attachment_capture((select id from fx where k='capture'),(select id from fx where k='mapping'))->>'status','ready','Ready historical capture recovers after parent changes');
select is(to_jsonb(pg_temp.approve_original()),(select v from data where k='approved'),'Exact approval recovery survives later source changes');
select is(cancel_ezyvet_attachment_approval((select id from fx where k='approval'),(select id from fx where k='capture'),(select id from fx where k='pet'),(select v#>>'{request,capture,capture_hash}' from data where k='ready'),true)->>'status','approved','Cancellation cannot erase committed approval');
insert into fx select 'cancel-approval',gen_random_uuid();
create function pg_temp.cancel_original(attest boolean default true) returns jsonb language sql as $$select cancel_ezyvet_attachment_approval((select id from fx where k='cancel-approval'),(select id from fx where k='capture'),(select id from fx where k='pet'),(select v#>>'{request,capture,capture_hash}' from data where k='ready'),$1);$$;
select throws_ok($$select pg_temp.cancel_original(false)$$,'23514',null,'Cancellation requires explicit confirmation');
insert into data select 'canceled-approval',pg_temp.cancel_original();
select is((select v->>'status' from data where k='canceled-approval'),'canceled','Cancellation remains available for a historical capture');
select is(pg_temp.cancel_original(),(select v from data where k='canceled-approval'),'Exact canceled outcome recovers');
select is(recover_ezyvet_attachment_approval((select id from fx where k='cancel-approval'),(select id from fx where k='capture'),(select id from fx where k='pet'),(select v#>>'{request,capture,capture_hash}' from data where k='ready')),(select v from data where k='canceled-approval'),'Recovery returns immutable cancellation');
select throws_ok($$select pg_temp.approve_original('cancel-approval',(select id from fx where k='correction'))$$,'23514','Approval was canceled; use an explicitly new decision','Late approval cannot revive cancellation');
select throws_ok($$select * from ezyvet_attachment_approval_cancellations$$,'42501',null,'Cancellation ledger stays private');
select ok(not has_function_privilege('authenticated','approve_ezyvet_attachment_record_uncancelled(uuid,uuid,uuid,text,uuid,text,text,boolean)','execute'),'Staff cannot bypass cancellation wrapper');
select ok(not has_function_privilege('service_role','approve_ezyvet_attachment_record_uncancelled(uuid,uuid,uuid,text,uuid,text,text,boolean)','execute'),'Worker cannot bypass cancellation wrapper');

insert into data select 'review-page',list_ezyvet_attachment_record_versions((select id from fx where k='capture'),(select id from fx where k='pet'),null,null,1);
select is((select v#>>'{records,0,id}' from data where k='review-page'),(select id::text from fx where k='correction'),'History starts with latest correction');
select is((select v->>'latest_record_id' from data where k='review-page'),(select id::text from fx where k='correction'),'Latest review identified independently of page');
select is((select v->>'has_more' from data where k='review-page'),'true','Review history bounds page size');
select ok(not (select (v#>'{records,0}') ? 'source_context' from data where k='review-page'),'History omits private source context');
insert into data select 'review-older',list_ezyvet_attachment_record_versions((select id from fx where k='capture'),(select id from fx where k='pet'),(select (v#>>'{next_cursor,before_at}')::timestamptz from data where k='review-page'),(select (v#>>'{next_cursor,before_id}')::uuid from data where k='review-page'),1);
select is((select v#>>'{records,0,version}' from data where k='review-older'),'1','Cursor reaches earlier review without repeating latest');
select is((select v->>'has_more' from data where k='review-older'),'false','History terminates at earliest review');
select throws_ok($$select list_ezyvet_attachment_record_versions((select id from fx where k='capture'),(select id from fx where k='pet'),now(),null,20)$$,'23514',null,'History rejects partial cursor');
select throws_ok($$select list_ezyvet_attachment_record_versions((select id from fx where k='capture'),(select id from fx where k='client'))$$,'42501',null,'History rejects another patient');

select throws_ok($$select pg_temp.approve_original('capture3',(select id from fx where k='correction'))$$,'40001',null,'Fresh approval rejects changed parent source');
select is(recover_ezyvet_attachment_capture((select id from fx where k='capture'),(select id from fx where k='mapping'))->>'source_current','false','Historical capture honestly reports stale source');
select is(prepare_ezyvet_attachment_capture((select id from fx where k='capture'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,1,(select id from fx where k='attachment-snapshot'),1,repeat('b',64))->>'status','ready','Exact prepare replay remains available historically');
select throws_ok($$select prepare_ezyvet_attachment_capture((select id from fx where k='capture2'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,1,(select id from fx where k='attachment-snapshot'),1,repeat('b',64))$$,'40001',null,'Fresh request rejects stale parent');
reset role;
update ezyvet_identity_heads set version=version-1 where resource='animal' and external_id='77';
set local role authenticated;
insert into data select 'capture2',prepare_ezyvet_attachment_capture((select id from fx where k='capture2'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,2,(select id from fx where k='attachment-snapshot'),1,repeat('b',64));
reset role;set local role service_role;
insert into data select 'claimed2',claim_ezyvet_attachment_capture((select id from fx where k='capture2'),'db700000-0000-4000-8000-000000000001');
insert into data select 'reserved2',reserve_ezyvet_attachment_original((select id from fx where k='capture2'),'db700000-0000-4000-8000-000000000001',(select(v->>'lease_id')::uuid from data where k='claimed2'),repeat('e',64),'application/pdf',12,repeat('a',64),repeat('c',64));
reset role;
insert into storage.objects(bucket_id,name,metadata) select 'ezyvet-attachment-originals',v#>>'{intent,object_path}','{"size":12,"mimetype":"application/pdf"}'::jsonb from data where k='reserved2';
set local role service_role;
select is(begin_discard_ezyvet_attachment_capture((select id from fx where k='capture2'),'db700000-0000-4000-8000-000000000001')#>>'{request,status}','discarding','Discard fences an active worker');
select throws_ok($$select complete_ezyvet_attachment_capture((select id from fx where k='capture2'),'db700000-0000-4000-8000-000000000001',(select(v->>'lease_id')::uuid from data where k='claimed2'),(select(v#>>'{intent,id}')::uuid from data where k='reserved2'),repeat('e',64),'application/pdf',12)$$,'40001',null,'Fenced worker cannot finalize');
select throws_ok($$select complete_discard_ezyvet_attachment_capture((select id from fx where k='capture2'),'db700000-0000-4000-8000-000000000001')$$,'23514',null,'Discard must verify private object absence');
reset role;set local storage.allow_delete_query='true';delete from storage.objects where name=(select v#>>'{intent,object_path}' from data where k='reserved2');
set local role authenticated;
select throws_ok($$insert into storage.objects(bucket_id,name,metadata) select 'ezyvet-attachment-originals',v#>>'{intent,object_path}','{"size":12,"mimetype":"application/pdf"}'::jsonb from data where k='reserved2'$$,'42501',null,'Late upload cannot cross discard fence');
reset role;set local role service_role;
select is(complete_discard_ezyvet_attachment_capture((select id from fx where k='capture2'),'db700000-0000-4000-8000-000000000001')#>>'{request,status}','abandoned','Absent pending object finalizes discard');
select is(begin_discard_ezyvet_attachment_capture((select id from fx where k='capture2'),'db700000-0000-4000-8000-000000000001')#>>'{request,status}','abandoned','Lost discard reply recovers tombstone');
select throws_ok($$select claim_ezyvet_attachment_capture((select id from fx where k='capture2'),'db700000-0000-4000-8000-000000000001')$$,'23514',null,'Abandoned request cannot revive');
reset role;
select throws_ok($$update ezyvet_attachment_capture_requests set status='prepared' where id=(select id from fx where k='capture2')$$,'23514',null,'Privileged mutation cannot bypass discard state guard');
select throws_ok($$update ezyvet_attachment_original_captures set content_sha256=repeat('f',64)$$,'23514',null,'Capture receipt immutable');
select ok(not has_table_privilege('authenticated','ezyvet_attachment_capture_requests','select'),'No direct capture-request read grant');
select ok(not has_table_privilege('service_role','ezyvet_attachment_original_intents','insert'),'Service cannot forge intent rows directly');
select ok(not has_function_privilege('authenticated','get_ezyvet_attachment_capture_context(uuid,uuid)','execute'),'Private path/lease context denied to browser');
select ok(not has_function_privilege('service_role','ezyvet_attachment_capture_private(uuid)','execute'),'Raw private projection helper revoked');
select ok(not exists(select 1 from patient_documents),'API capture creates no patient document');
select ok(not exists(select 1 from external_record_receipts),'API capture creates no manual-export receipt');
select is((select count(*)::integer from ezyvet_attachment_page_observations),2,'Metadata observation count unchanged by capture');
set local role authenticated;
select is(jsonb_array_length(list_ezyvet_attachment_capture_mappings()->'mappings'),1,'Historical mappings are grouped for their owner');
select is(list_ezyvet_attachment_capture_mappings()#>>'{mappings,0,household_name}','Attachment Owner','Historical mapping keeps original household');
select throws_ok($$select list_ezyvet_attachment_capture_mappings(now(),null,20)$$,'23514',null,'Mapping cursor must be complete');
insert into fx select 'moved-client',id from save_client(auth.uid(),null,null,'Different','Household','+13035550197','other-household@example.test','EMAIL',null,null);
reset role;
-- Owner-only synthetic future household-transfer fixture.
alter table pets disable trigger pets_version;
update pets set client_id=(select id from fx where k='moved-client') where id=(select id from fx where k='pet');
set local role authenticated;
select is(list_ezyvet_attachment_capture_mappings()#>>'{mappings,0,household_name}','Attachment Owner','Moved patient remains discoverable under original capture household');
select is(abandon_ezyvet_attachment_capture_preparation((select id from fx where k='capture3'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,1,(select id from fx where k='attachment-snapshot'),1,repeat('b',64))->>'status','abandoned','Uncreated scoped preparation becomes abandoned');
reset role;
update pets set client_id=(select id from fx where k='client') where id=(select id from fx where k='pet');
alter table pets enable trigger pets_version;
set local role authenticated;
select is(prepare_ezyvet_attachment_capture((select id from fx where k='capture3'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,1,(select id from fx where k='attachment-snapshot'),1,repeat('b',64))->>'status','abandoned','Delayed prepare recovers abandoned tombstone');
select is(abandon_ezyvet_attachment_capture_preparation((select id from fx where k='capture'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,1,(select id from fx where k='attachment-snapshot'),1,repeat('b',64))->>'status','ready','Abandon preparation cannot alter an existing ready request');
select throws_ok($$select abandon_ezyvet_attachment_capture_preparation((select id from fx where k='capture3'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,2,(select id from fx where k='attachment-snapshot'),1,repeat('b',64))$$,'42501',null,'Preparation tombstone cannot change observation ordinal');
select set_config('request.jwt.claims','{"sub":"db700000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select throws_ok($$select list_ezyvet_attachment_record_versions((select id from fx where k='capture'),(select id from fx where k='pet'))$$,'42501',null,'Another administrator cannot list owned review history');
select is(jsonb_array_length(list_ezyvet_attachment_capture_mappings()->'mappings'),0,'Another administrator cannot discover historical mappings');
select throws_ok($$select abandon_ezyvet_attachment_capture_preparation((select id from fx where k='capture3'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,1,(select id from fx where k='attachment-snapshot'),1,repeat('b',64))$$,'42501',null,'Another administrator cannot recover preparation tombstone');
reset role;
select ok(not has_function_privilege('authenticated','ezyvet_attachment_capture_prepare_core(uuid,uuid,uuid,integer,integer,uuid,integer,text,boolean)','execute'),'Preparation core remains private');
select * from finish();rollback;
