begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select no_plan();
-- FIXTURE_BEGIN: isolated review sources.
insert into auth.users(id,email,raw_user_meta_data) values('db520000-0000-4000-8000-000000000001','clinical-import-admin@example.test','{}'),('db520000-0000-4000-8000-000000000002','clinical-import-other@example.test','{}');
update public.profiles set is_active = true where id in ('db520000-0000-4000-8000-000000000001','db520000-0000-4000-8000-000000000002');
insert into public.user_roles (user_id, role) values ('db520000-0000-4000-8000-000000000001','STAFF'),('db520000-0000-4000-8000-000000000002','STAFF');

insert into user_roles(user_id,role) values('db520000-0000-4000-8000-000000000001','ADMIN'),('db520000-0000-4000-8000-000000000002','ADMIN');
create temp table fx(k text primary key,id uuid);create temp table data(k text primary key,v jsonb);grant all on fx,data to authenticated,service_role;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db520000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'client',id from save_client(auth.uid(),null,null,'Clinical','Import','+13035550199','clinical-import@example.test','EMAIL',null,null);
insert into fx select 'pet',id from save_patient(null,(select id from fx where k='client'),null,'Scoped dog','Dog',null,null,'unknown',null,'unknown','unknown',null,null,null);
insert into fx select k,gen_random_uuid() from unnest(array['mapping','mapping2','snapshot','snapshot2','legacy','terminal','run','history','other-run']) k;
reset role;
insert into ezyvet_import_snapshots(id,source_origin,source_site_uid,resource,external_id,payload,payload_hash,first_seen_by) select id,'https://api.trial.ezyvet.com','vaccination-test-site','animal',case when k='snapshot' then '77' else '88' end,jsonb_build_object('id',case when k='snapshot' then 77 else 88 end),k,'db520000-0000-4000-8000-000000000001' from fx where k in ('snapshot','snapshot2');
insert into ezyvet_record_links(id,request_id,request_hash,source_origin,source_site_uid,resource,external_id,snapshot_id,head_version,client_id,pet_id,local_version,action,reason,approved_by)
select id,gen_random_uuid(),k,'https://api.trial.ezyvet.com','vaccination-test-site','animal',case when k='mapping' then '77' else '88' end,(select id from fx where k=case when m.k='mapping' then 'snapshot' else 'snapshot2' end),1,(select id from fx where k='client'),(select id from fx where k='pet'),1,'link','Synthetic approved mapping','db520000-0000-4000-8000-000000000001' from fx m where k in ('mapping','mapping2');
insert into fx values('consult-run',gen_random_uuid());
insert into data select 'consult-run',claim_ezyvet_clinical_import((select id from fx where k='consult-run'),'db520000-0000-4000-8000-000000000001','vaccination-test-site','consult','https://api.trial.ezyvet.com',(select id from fx where k='mapping'));
select stage_ezyvet_import_page((select id from fx where k='consult-run'),'db520000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='consult-run'),1,true,'[{"external_id":"101","payload":{"id":101,"animal_id":77,"description":"Source consultation"}},{"external_id":"102","payload":{"id":102,"animal_id":77}}]');
insert into data select 'consult',list_ezyvet_clinical_candidates((select id from fx where k='mapping'),'consult')->'candidates'->0;
-- Choose external consult 101 independent of creation-order ties.
update data set v=(select c from jsonb_array_elements(list_ezyvet_clinical_candidates((select id from fx where k='mapping'),'consult')->'candidates') c where c->>'external_id'='101') where k='consult';
insert into data values('items','[{"external_id":"501","payload":{"id":501,"consult_id":101,"product_id":null,"date_of_administration":null,"date_of_next_administration":"unknown","qty":"outside units","vet_id":"outside author","notes":"<script>outside prose</script>"}}]');
insert into data select 'legacy',to_jsonb(claim_ezyvet_import_core((select id from fx where k='legacy'),'db520000-0000-4000-8000-000000000001','vaccination-test-site','vaccination','https://api.trial.ezyvet.com'));
select stage_ezyvet_import_page_core((select id from fx where k='legacy'),'db520000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='legacy'),1,false,(select v from data where k='items'));
update ezyvet_import_runs set retry_after=null,lease_until=null;
insert into data select 'terminal',to_jsonb(claim_ezyvet_import_core((select id from fx where k='terminal'),'db520000-0000-4000-8000-000000000001','vaccination-test-site','vaccination','https://api.trial.ezyvet.com'));
select stage_ezyvet_import_page_core((select id from fx where k='terminal'),'db520000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='terminal'),1,true,'[]');
update ezyvet_import_runs set retry_after=null,lease_until=null;
insert into data select 'run',claim_ezyvet_vaccination_import((select id from fx where k='run'),'db520000-0000-4000-8000-000000000001','vaccination-test-site','vaccination','https://api.trial.ezyvet.com',(select id from fx where k='mapping'),(select (v->>'id')::uuid from data where k='consult'),(select v->>'payload_hash' from data where k='consult'),(select (v->>'observed_head_version')::integer from data where k='consult'));
select stage_ezyvet_import_page((select id from fx where k='run'),'db520000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='run'),1,true,(select v from data where k='items'));
insert into user_roles(user_id,role) values('db520000-0000-4000-8000-000000000001','DVM'),('db520000-0000-4000-8000-000000000002','DVM');
insert into data select 'candidate',list_ezyvet_vaccination_candidates((select id from fx where k='mapping'))->'candidates'->0;
insert into data select 'payload',jsonb_build_object('animal_link_id',c->'animal_link_id','patient_version',(select version from pets where id=(select id from fx where k='pet')),'snapshot_id',c->'id','payload_hash',c->'payload_hash','observed_head_version',c->'observed_head_version','consult_snapshot_id',c->'consult_snapshot_id','consult_payload_hash',c->'consult_payload_hash','consult_observed_head_version',c->'consult_observed_head_version','product_id',null,'product_version',null,'administered_on',null,'administration_date_status','unknown','source_next_due_on',null,'next_date_status','uninterpreted','status','unknown','outside_author',null,'reason','Reviewed outside source evidence','replaces_id',null,'expected_predecessor_hash',null) from(select v c from data where k='candidate') q;
insert into fx select k,gen_random_uuid() from unnest(array['review','duplicate','correction','tombstone','pending','product','stale-catalog']) k;
insert into catalog_products(id,name,kind,unit,unit_price_cents,created_by) select id,'Test vaccine','vaccine','dose',1000,'db520000-0000-4000-8000-000000000001' from fx where k='product';

insert into fx select k,gen_random_uuid() from unnest(array['generic-vaccination','foreign-site-vaccination']) k;
insert into ezyvet_import_snapshots(id,source_origin,source_site_uid,resource,external_id,payload,payload_hash,first_seen_by) select id,'https://api.trial.ezyvet.com',case when k='generic-vaccination' then 'vaccination-test-site' else 'other-source-site' end,'vaccination',case when k='generic-vaccination' then '901' else '902' end,jsonb_build_object('id',case when k='generic-vaccination' then 901 else 902 end,'consult_id',101),repeat('b',64),'db520000-0000-4000-8000-000000000001' from fx where k in('generic-vaccination','foreign-site-vaccination');
insert into ezyvet_identity_heads(source_origin,source_site_uid,resource,external_id,snapshot_id,version) select source_origin,source_site_uid,resource,external_id,id,1 from ezyvet_import_snapshots where id in(select id from fx where k in('generic-vaccination','foreign-site-vaccination'));
-- FIXTURE_END
insert into data values('side-effects',jsonb_build_object('treatments',(select count(*) from patient_treatments),'invoices',(select count(*) from billing_invoices),'stock',(select count(*) from inventory_movements),'certificates',(select count(*) from vaccine_certificates),'plans',(select count(*) from patient_vaccine_due_plans),'reminders',(select count(*) from care_reminder_jobs),'outbox',(select count(*) from communication_outbox)));
set local role authenticated;
select is(jsonb_array_length(list_ezyvet_vaccination_review_mappings((select id from fx where k='pet'))),2,'DVM discovers only patient mappings');
select is(jsonb_array_length(list_ezyvet_vaccination_review_candidates((select id from fx where k='pet'),(select id from fx where k='mapping'))->'candidates'),1,'DVM sees scoped vaccination candidate');
select throws_ok($$select prepare_ezyvet_vaccination_review(gen_random_uuid(),gen_random_uuid(),(select v from data where k='payload'))$$,'42501',null,'Wrong patient denied');
select throws_ok($$select prepare_ezyvet_vaccination_review(gen_random_uuid(),(select id from fx where k='pet'),(select v||'{"extra":1}' from data where k='payload'))$$,'23514',null,'Unknown fields denied');
select throws_ok($$select prepare_ezyvet_vaccination_review(gen_random_uuid(),(select id from fx where k='pet'),(select v||'{"payload_hash":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}' from data where k='payload'))$$,'42501',null,'Wrong vaccination hash denied');
select throws_ok($$select prepare_ezyvet_vaccination_review(gen_random_uuid(),(select id from fx where k='pet'),(select v||'{"consult_payload_hash":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}' from data where k='payload'))$$,'42501',null,'Wrong consult hash denied');
select throws_ok($$select prepare_ezyvet_vaccination_review(gen_random_uuid(),(select id from fx where k='pet'),(select v||'{"observed_head_version":99}' from data where k='payload'))$$,'40001',null,'Wrong vaccination revision denied');
select throws_ok($$select prepare_ezyvet_vaccination_review(gen_random_uuid(),(select id from fx where k='pet'),(select v||'{"consult_observed_head_version":99}' from data where k='payload'))$$,'40001',null,'Wrong consult revision denied');
select throws_ok($$select prepare_ezyvet_vaccination_review(gen_random_uuid(),(select id from fx where k='pet'),(select v||'{"patient_version":99}' from data where k='payload'))$$,'40001',null,'Changed patient denied');
select throws_ok($$select prepare_ezyvet_vaccination_review(gen_random_uuid(),(select id from fx where k='pet'),(select v||'{"administered_on":"2026-02-31","administration_date_status":"date"}' from data where k='payload'))$$,'23514',null,'Impossible date denied');
select throws_ok($$select prepare_ezyvet_vaccination_review(gen_random_uuid(),(select id from fx where k='pet'),(select v||'{"administered_on":"2026-01-01T00:00:00Z","administration_date_status":"date"}' from data where k='payload'))$$,'23514',null,'Timestamp cannot masquerade as date');
select throws_ok($$select prepare_ezyvet_vaccination_review(gen_random_uuid(),(select id from fx where k='pet'),(select v||'{"administration_date_status":"date"}' from data where k='payload'))$$,'23514',null,'Date interpretation requires date');
select throws_ok($$select prepare_ezyvet_vaccination_review(gen_random_uuid(),(select id from fx where k='pet'),(select v||jsonb_build_object('product_id',(select id from fx where k='product'),'product_version',99) from data where k='payload'))$$,'40001',null,'Changed catalog version denied');
select throws_ok($$select prepare_ezyvet_vaccination_review(gen_random_uuid(),(select id from fx where k='pet'),(select v||jsonb_build_object('snapshot_id',(select id from fx where k='generic-vaccination'),'payload_hash',repeat('b',64),'observed_head_version',1) from data where k='payload'))$$,'40001',null,'Generic-only vaccination snapshot cannot approve');
select throws_ok($$select prepare_ezyvet_vaccination_review(gen_random_uuid(),(select id from fx where k='pet'),(select v||jsonb_build_object('snapshot_id',(select id from fx where k='foreign-site-vaccination'),'payload_hash',repeat('b',64),'observed_head_version',1) from data where k='payload'))$$,'42501',null,'Different source site cannot approve');
insert into data select 'prepared',prepare_ezyvet_vaccination_review((select id from fx where k='review'),(select id from fx where k='pet'),(select v from data where k='payload'));
select is(recover_ezyvet_vaccination_review((select id from fx where k='review'),(select id from fx where k='pet')),(select v from data where k='prepared'),'Lost prepare response recovered exactly');
select is(prepare_ezyvet_vaccination_review((select id from fx where k='review'),(select id from fx where k='pet'),(select v from data where k='payload')),(select v from data where k='prepared'),'Exact prepare replay');
select throws_ok($$select prepare_ezyvet_vaccination_review((select id from fx where k='review'),(select id from fx where k='pet'),(select v||'{"reason":"Changed reason"}' from data where k='payload'))$$,'42501',null,'Retained UUID cannot change payload');
select throws_ok($$select approve_ezyvet_vaccination_review((select id from fx where k='review'),(select id from fx where k='pet'),'wrong',true)$$,'42501',null,'Wrong prepared hash denied');
select throws_ok($$select approve_ezyvet_vaccination_review((select id from fx where k='review'),(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='prepared'),false)$$,'23514',null,'Explicit confirmation required');
select abandon_ezyvet_vaccination_review((select id from fx where k='tombstone'),(select id from fx where k='pet'),true);
select throws_ok($$select prepare_ezyvet_vaccination_review((select id from fx where k='tombstone'),(select id from fx where k='pet'),(select v from data where k='payload'))$$,'42501',null,'Abandon tombstone prevents late prepare');
insert into data select 'catalog-prepared',prepare_ezyvet_vaccination_review((select id from fx where k='stale-catalog'),(select id from fx where k='pet'),(select v||jsonb_build_object('product_id',(select id from fx where k='product'),'product_version',1) from data where k='payload'));
reset role;
update catalog_products set version=2 where id=(select id from fx where k='product');
set local role authenticated;
select throws_ok($$select approve_ezyvet_vaccination_review((select id from fx where k='stale-catalog'),(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='catalog-prepared'),true)$$,'40001',null,'Catalog changed after prepare blocks approval');
select throws_ok($$select prepare_ezyvet_vaccination_review(gen_random_uuid(),(select id from fx where k='pet'),(select v||jsonb_build_object('animal_link_id',(select id from fx where k='mapping2')) from data where k='payload'))$$,'42501',null,'Same local patient mapping to different source animal denied');
insert into data select 'approved',approve_ezyvet_vaccination_review((select id from fx where k='review'),(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='prepared'),true);
select is((select v#>>'{receipt,reviewed,administration_date_status}' from data where k='approved'),'unknown','Unknown administration retained');
select is((select v#>'{receipt,reviewed,administered_on}' from data where k='approved'),'null'::jsonb,'No fabricated administration date');
select is((select v#>>'{receipt,original,qty}' from data where k='approved'),'outside units','Raw dose units retained');
select is((select v#>'{receipt,product}' from data where k='approved'),'null'::jsonb,'No inferred local product');
select is((select v#>>'{receipt,current,is_current}' from data where k='approved'),'true','Approved source current');
select is((select v#>>'{receipt,current,is_latest}' from data where k='approved'),'true','First approval latest');
select is(approve_ezyvet_vaccination_review((select id from fx where k='review'),(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='prepared'),true),(select v from data where k='approved'),'Lost approval exact recovery');
select set_config('request.jwt.claims','{"sub":"db520000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select throws_ok($$select recover_ezyvet_vaccination_review((select id from fx where k='review'),(select id from fx where k='pet'))$$,'42501',null,'Other clinician cannot recover owned operation');
insert into data select 'duplicate',prepare_ezyvet_vaccination_review((select id from fx where k='duplicate'),(select id from fx where k='pet'),(select v||'{"reason":"Second clinician same interpretation"}' from data where k='payload'));
select is(approve_ezyvet_vaccination_review((select id from fx where k='duplicate'),(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='duplicate'),true)#>>'{receipt,id}',(select id::text from fx where k='review'),'Different actor/UUID same evidence returns original receipt');
select throws_ok($$select prepare_ezyvet_vaccination_review(gen_random_uuid(),(select id from fx where k='pet'),(select v||'{"status":"administered"}' from data where k='payload'))$$,'40001',null,'Changed interpretation requires predecessor');
insert into data select 'correct-payload',v||jsonb_build_object('status','administered','administered_on','2026-09-01','administration_date_status','date','replaces_id',(select id from fx where k='review'),'expected_predecessor_hash',(select v#>>'{receipt,version_hash}' from data where k='approved'),'reason','Explicit source review correction') from data where k='payload';
insert into data select 'correct-prepared',prepare_ezyvet_vaccination_review((select id from fx where k='correction'),(select id from fx where k='pet'),(select v from data where k='correct-payload'));
insert into data select 'corrected',approve_ezyvet_vaccination_review((select id from fx where k='correction'),(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='correct-prepared'),true);
select throws_ok($$select prepare_ezyvet_vaccination_review(gen_random_uuid(),(select id from fx where k='pet'),(select v||jsonb_build_object('replaces_id',gen_random_uuid()) from data where k='correct-payload'))$$,'40001',null,'Even identical interpretation cannot invent predecessor');
select is((select v#>>'{receipt,version}' from data where k='corrected'),'2','Correction creates immutable next version');
select is(jsonb_array_length((select v#>'{receipt,correction_history}' from data where k='corrected')),2,'Correction lineage disclosed');
select is(list_patient_imported_vaccinations((select id from fx where k='pet'))->>'has_more','false','Chart pagination complete');
select is(jsonb_array_length(list_patient_imported_vaccinations((select id from fx where k='pet'))->'vaccinations'),2,'Chart retains both versions without duplicate');
select is(list_ezyvet_vaccination_review_requests((select id from fx where k='pet'),null,null,1)->>'has_more','true','Durable actor discovery paginates');
select throws_ok($$select list_ezyvet_vaccination_review_requests((select id from fx where k='pet'),now(),null,1)$$,'23514',null,'Invalid cursor denied');
select set_config('request.jwt.claims','{"sub":"db520000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into data select 'pending',prepare_ezyvet_vaccination_review((select id from fx where k='pending'),(select id from fx where k='pet'),(select v from data where k='correct-payload'));
reset role;
select throws_ok($$update ezyvet_imported_vaccinations set reason='rewrite'$$,'23514',null,'Approved evidence immutable');
select throws_ok($$update ezyvet_vaccination_review_requests set payload='{}'$$,'23514',null,'Prepared evidence immutable');
select is(ezyvet_vaccination_current((select id from fx where k='review'))->>'is_latest','false','Superseded version labeled');
select throws_ok($$select ezyvet_validate_reviewed_vaccinations((select id from fx where k='pet'),jsonb_build_array(jsonb_build_object('id',(select id from fx where k='review'),'version_hash',(select v#>>'{receipt,version_hash}' from data where k='approved'))))$$,'40001',null,'Superseded release source denied');
select is(jsonb_array_length(ezyvet_validate_reviewed_vaccinations((select id from fx where k='pet'),jsonb_build_array(jsonb_build_object('id',(select id from fx where k='correction'),'version_hash',(select v#>>'{receipt,version_hash}' from data where k='corrected'))))),1,'Current corrected release source accepted');
update ezyvet_identity_heads set version=version+2 where resource='consult' and external_id='101';
select is(ezyvet_vaccination_current((select id from fx where k='correction'))->>'is_current','false','Consult A-B-A discrepancy retained');
set local role authenticated;
select throws_ok($$select approve_ezyvet_vaccination_review((select id from fx where k='pending'),(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='pending'),true)$$,'40001',null,'Consult changed after prepare denies approval');
select is(recover_ezyvet_vaccination_review((select id from fx where k='review'),(select id from fx where k='pet'))#>>'{receipt,id}',(select id::text from fx where k='review'),'Terminal recovery survives source change');
reset role;
update ezyvet_identity_heads set version=version+2 where resource='vaccination' and external_id='501';
select is(ezyvet_vaccination_current((select id from fx where k='review'))->>'is_current','false','Vaccination A-B-A cannot revive review');
delete from user_roles where user_id='db520000-0000-4000-8000-000000000001' and role='DVM';
set local role authenticated;
select throws_ok($$select recover_ezyvet_vaccination_review((select id from fx where k='review'),(select id from fx where k='pet'))$$,'42501',null,'Revoked DVM cannot recover even approved operation');
select lives_ok($$select list_patient_imported_vaccinations((select id from fx where k='pet'))$$,'Active non-DVM staff reads chart');
select throws_ok($$select list_ezyvet_vaccination_review_mappings((select id from fx where k='pet'))$$,'42501',null,'ADMIN-only user cannot interpret clinical history');
reset role;
select is(jsonb_build_object('treatments',(select count(*) from patient_treatments),'invoices',(select count(*) from billing_invoices),'stock',(select count(*) from inventory_movements),'certificates',(select count(*) from vaccine_certificates),'plans',(select count(*) from patient_vaccine_due_plans),'reminders',(select count(*) from care_reminder_jobs),'outbox',(select count(*) from communication_outbox)),(select v from data where k='side-effects'),'No clinical, billing, stock, certificate, due-plan or delivery side effects');
select ok(not has_table_privilege('authenticated','ezyvet_imported_vaccinations','select,insert,update,delete'),'No direct authenticated evidence access');
select ok(not has_table_privilege('service_role','ezyvet_vaccination_review_requests','select,insert,update,delete'),'No direct service operation access');
select ok(not has_function_privilege('authenticated','ezyvet_vaccination_review_context(uuid,jsonb)','execute'),'Private source validation inaccessible');
select ok(not has_function_privilege('anon','list_patient_imported_vaccinations(uuid,timestamptz,uuid,integer)','execute'),'Anonymous chart denied');
select * from finish();rollback;
