begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select no_plan();
-- FIXTURE_BEGIN



insert into auth.users(id,email,raw_user_meta_data) values('db710000-0000-4000-8000-000000000001','attachment-admin@example.test','{}'),('db710000-0000-4000-8000-000000000002','attachment-other@example.test','{}');
insert into user_roles(user_id,role) values('db710000-0000-4000-8000-000000000001','ADMIN'),('db710000-0000-4000-8000-000000000002','ADMIN');
create temp table fx(k text primary key,id uuid);create temp table data(k text primary key,v jsonb);grant all on fx,data to authenticated,service_role;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db710000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'client',id from save_client(auth.uid(),null,null,'Attachment','Owner','+13035550196','attachment@example.test','EMAIL',null,null);
insert into fx select 'pet',id from save_patient(null,(select id from fx where k='client'),null,'Metadata dog','Dog',null,null,'unknown',null,'unknown','unknown',null,null,null);
insert into fx select k,gen_random_uuid() from unnest(array['mapping','animal-run','run','run2','other-run']) k;
reset role;
insert into data select 'animal',to_jsonb(claim_ezyvet_import((select id from fx where k='animal-run'),'db710000-0000-4000-8000-000000000001','attachment-test-site','animal','https://api.trial.ezyvet.com'));
select stage_ezyvet_import_page((select id from fx where k='animal-run'),'db710000-0000-4000-8000-000000000001',(select(v->>'lease_id')::uuid from data where k='animal'),1,true,'[{"external_id":"77","payload":{"id":77}}]');
insert into ezyvet_record_links(id,request_id,request_hash,source_origin,source_site_uid,resource,external_id,snapshot_id,head_version,client_id,pet_id,local_version,action,reason,approved_by)
select (select id from fx where k='mapping'),gen_random_uuid(),'synthetic-approved-mapping',s.source_origin,s.source_site_uid,s.resource,s.external_id,s.id,h.version,(select id from fx where k='client'),(select id from fx where k='pet'),1,'link','Synthetic reviewed mapping','db710000-0000-4000-8000-000000000001' from ezyvet_import_snapshots s join ezyvet_identity_heads h on h.snapshot_id=s.id where s.resource='animal' and s.source_site_uid='attachment-test-site';
insert into data values('observation',jsonb_build_object('external_id','701','file_id','42','metadata',jsonb_build_object('id','701','file_id','42','record_type','Animal','record_id','77','name','Synthetic report','mime_type','application/pdf','notes',null),'raw_record_sha256',repeat('a',64),'stable_metadata_sha256',repeat('b',64),'file_sha256',null));
insert into data select 'page',jsonb_build_object('contract_version','ezyvet_animal_attachment_metadata_v1','parent',jsonb_build_object('record_type','Animal','record_id','77'),'page',1,'complete',true,'pagination',jsonb_build_object('items_page',1,'items_page_total',1,'items_page_size',10,'items_total',2),'observations',jsonb_build_array(v,jsonb_set(v,'{raw_record_sha256}',to_jsonb(repeat('c',64)))),'page_sha256',repeat('d',64)) from data where k='observation';
insert into data values('side-effects',jsonb_build_object('treatments',(select count(*) from patient_treatments),'invoices',(select count(*) from billing_invoices),'stock',(select count(*) from inventory_movements),'outbox',(select count(*) from communication_outbox),'objects',(select count(*) from storage.objects)));

insert into data select 'run',claim_ezyvet_attachment_import((select id from fx where k='run'),'db710000-0000-4000-8000-000000000001','attachment-test-site','https://api.trial.ezyvet.com',(select id from fx where k='mapping'));
select stage_ezyvet_attachment_page((select id from fx where k='run'),'db710000-0000-4000-8000-000000000001',(select(v->>'lease_id')::uuid from data where k='run'),(select v from data where k='page'));
update ezyvet_import_runs set retry_after=null where resource='attachment';
insert into fx select k,gen_random_uuid() from unnest(array['capture','capture2','capture3','capture4']) k;
insert into fx select 'attachment-snapshot',snapshot_id from ezyvet_attachment_page_observations where run_id=(select id from fx where k='run') and ordinal=1;
insert into auth.users(id,email,raw_user_meta_data) values('db710000-0000-4000-8000-000000000003','original-dvm@example.test','{}'),('db710000-0000-4000-8000-000000000004','original-staff@example.test','{}');
insert into user_roles(user_id,role) values('db710000-0000-4000-8000-000000000003','DVM'),('db710000-0000-4000-8000-000000000004','STAFF') on conflict do nothing;
insert into fx select k,gen_random_uuid() from unnest(array['approve','approve2','approve3','ack','withdraw','abandon','ack-abandon','withdraw-abandon']) k;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db710000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select prepare_ezyvet_attachment_capture((select id from fx where k='capture'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,1,(select id from fx where k='attachment-snapshot'),1,repeat('b',64));
reset role;set local role service_role;
insert into data select 'claim1',claim_ezyvet_attachment_capture((select id from fx where k='capture'),'db710000-0000-4000-8000-000000000001');
insert into data select 'reserve1',reserve_ezyvet_attachment_original((select id from fx where k='capture'),'db710000-0000-4000-8000-000000000001',(select v#>>'{lease_id}' from data where k='claim1')::uuid,encode(sha256(convert_to('%PDF-test123','UTF8')),'hex'),'application/pdf',12,repeat('a',64),repeat('c',64));
reset role;
insert into storage.objects(bucket_id,name,metadata) values('ezyvet-attachment-originals',(select v#>>'{intent,object_path}' from data where k='reserve1'),'{"size":12,"mimetype":"application/pdf"}');
set local role service_role;
insert into data select 'ready1',complete_ezyvet_attachment_capture((select id from fx where k='capture'),'db710000-0000-4000-8000-000000000001',(select v#>>'{lease_id}' from data where k='claim1')::uuid,(select v#>>'{intent,id}' from data where k='reserve1')::uuid,encode(sha256(convert_to('%PDF-test123','UTF8')),'hex'),'application/pdf',12);
reset role;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db710000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select prepare_ezyvet_attachment_capture((select id from fx where k='capture2'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,1,(select id from fx where k='attachment-snapshot'),1,repeat('b',64));
reset role;set local role service_role;
insert into data select 'claim2',claim_ezyvet_attachment_capture((select id from fx where k='capture2'),'db710000-0000-4000-8000-000000000001');
insert into data select 'reserve2',reserve_ezyvet_attachment_original((select id from fx where k='capture2'),'db710000-0000-4000-8000-000000000001',(select v#>>'{lease_id}' from data where k='claim2')::uuid,encode(sha256(convert_to('%PDF-test123','UTF8')),'hex'),'application/pdf',12,repeat('a',64),repeat('c',64));
reset role;
insert into storage.objects(bucket_id,name,metadata) values('ezyvet-attachment-originals',(select v#>>'{intent,object_path}' from data where k='reserve2'),'{"size":12,"mimetype":"application/pdf"}');
set local role service_role;
insert into data select 'ready2',complete_ezyvet_attachment_capture((select id from fx where k='capture2'),'db710000-0000-4000-8000-000000000001',(select v#>>'{lease_id}' from data where k='claim2')::uuid,(select v#>>'{intent,id}' from data where k='reserve2')::uuid,encode(sha256(convert_to('%PDF-test123','UTF8')),'hex'),'application/pdf',12);
reset role;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db710000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select prepare_ezyvet_attachment_capture((select id from fx where k='capture3'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,1,(select id from fx where k='attachment-snapshot'),1,repeat('b',64));
reset role;set local role service_role;
insert into data select 'claim3',claim_ezyvet_attachment_capture((select id from fx where k='capture3'),'db710000-0000-4000-8000-000000000001');
insert into data select 'reserve3',reserve_ezyvet_attachment_original((select id from fx where k='capture3'),'db710000-0000-4000-8000-000000000001',(select v#>>'{lease_id}' from data where k='claim3')::uuid,encode(sha256(convert_to('%PDF-test123','UTF8')),'hex'),'application/pdf',12,repeat('a',64),repeat('c',64));
reset role;
insert into storage.objects(bucket_id,name,metadata) values('ezyvet-attachment-originals',(select v#>>'{intent,object_path}' from data where k='reserve3'),'{"size":12,"mimetype":"application/pdf"}');
set local role service_role;
insert into data select 'ready3',complete_ezyvet_attachment_capture((select id from fx where k='capture3'),'db710000-0000-4000-8000-000000000001',(select v#>>'{lease_id}' from data where k='claim3')::uuid,(select v#>>'{intent,id}' from data where k='reserve3')::uuid,encode(sha256(convert_to('%PDF-test123','UTF8')),'hex'),'application/pdf',12);
reset role;

set local role authenticated;select set_config('request.jwt.claims','{"sub":"db710000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into data select 'approved',approve_ezyvet_attachment_original((select id from fx where k='approve'),(select id from fx where k='pet'),(select v#>>'{request,capture,id}' from data where k='ready1')::uuid,(select v#>>'{request,capture,capture_hash}' from data where k='ready1'),1,null,'Reviewed original for explicit sharing',true);
insert into data select 'selection',jsonb_build_object('api_original_ids',jsonb_build_array(v#>'{record,id}')) from data where k='approved';
reset role;
-- FIXTURE_END
select throws_ok($$select release_preview_v9_internal((select id from fx where k='pet'),(select id from fx where k='client'),'EMAIL','attachment@example.test',(select v from data where k='selection'))$$,'40001',null,'Missing acknowledgment cannot enter release');
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db710000-0000-4000-8000-000000000003","role":"authenticated"}',true);
insert into data select 'acknowledged',acknowledge_ezyvet_attachment_original((select id from fx where k='ack'),(select id from fx where k='pet'),(select v#>>'{record,id}' from data where k='approved')::uuid,(select v#>>'{record,record_hash}' from data where k='approved'),(select v#>>'{record,capture_hash}' from data where k='approved'),true);
insert into data select 'preview',preview_record_release_v9((select id from fx where k='pet'),(select id from fx where k='client'),'EMAIL','attachment@example.test',(select v from data where k='selection'));
select is((select v#>'{snapshot,api_originals,0,record}' from data where k='preview'),(select v->'record' from data where k='approved'),'Frozen exact7100 record projection');
select is((select v#>'{snapshot,api_originals,0,acknowledgment}' from data where k='preview'),(select v->'acknowledgment' from data where k='acknowledged'),'Single exact earliest acknowledgment');
select is((select v#>>'{snapshot,schema_version}' from data where k='preview'),'9','API-only package schema9');
select is(jsonb_array_length((select v#>'{snapshot,attachments}' from data where k='preview')),0,'API originals do not become patient documents');
select is((list_record_release_sources_v9((select id from fx where k='pet'))->>'policy_v9_accepted')::boolean,false,'Policy9 remains unaccepted');
select is(jsonb_array_length(list_record_release_sources_v9((select id from fx where k='pet'))->'api_original_ids'),1,'Acknowledged ready record is discoverable');
select is((select_all_record_release_sources_v9((select id from fx where k='pet'))#>'{selection,api_original_ids}'),(select v->'api_original_ids' from data where k='selection'),'Select-all includes explicit eligible original');
insert into fx values('release',gen_random_uuid());
select throws_ok($$select confirm_record_release((select id from fx where k='release'),(select id from fx where k='pet'),(select id from fx where k='client'),'EMAIL','attachment@example.test',(select v from data where k='selection'),(select v->'snapshot' from data where k='preview'),(select v->>'source_hash' from data where k='preview'),true)$$,'42501',null,'Unaccepted policy prevents confirmation');
reset role;
insert into record_release_policy(id,enabled,accepted_schema_version,accepted_at,accepted_by,acceptance_reference) values(true,true,9,now(),'Synthetic DVM','Local SQL only') on conflict(id) do update set enabled=true,accepted_schema_version=9,accepted_at=now();
set local role authenticated;
insert into data select 'release',to_jsonb(confirm_record_release((select id from fx where k='release'),(select id from fx where k='pet'),(select id from fx where k='client'),'EMAIL','attachment@example.test',(select v from data where k='selection'),(select v->'snapshot' from data where k='preview'),(select v->>'source_hash' from data where k='preview'),true));
select is((read_record_release((select id from fx where k='release'))->>'eligible')::boolean,true,'Confirmed schema9 is eligible');
reset role;
select is((select source_kind from record_release_sources where release_id=(select id from fx where k='release')),'api_original','Separate source registry family');
select lives_ok($$select verify_release_api_original((select v#>'{snapshot,api_originals,0}' from data where k='preview'),'1-ezyvet-original-701.pdf','application/pdf',convert_to('%PDF-test123','UTF8'),1)$$,'Exact decoded API original accepted');
select throws_ok($$select verify_release_api_original((select v#>'{snapshot,api_originals,0}' from data where k='preview'),'1-ezyvet-original-701.pdf','application/pdf',convert_to('%PDF-test456','UTF8'),1)$$,'23514',null,'Same-size substitution rejected');
select throws_ok($$select verify_release_api_original((select v#>'{snapshot,api_originals,0}' from data where k='preview'),'2-ezyvet-original-701.pdf','application/pdf',convert_to('%PDF-test123','UTF8'),1)$$,'23514',null,'Reordered filename rejected');
select throws_ok($$select verify_release_api_original((select v#>'{snapshot,api_originals,0}' from data where k='preview'),'1-ezyvet-original-701.pdf','image/png',convert_to('%PDF-test123','UTF8'),1)$$,'23514',null,'Wrong MIME rejected');
select throws_ok($$select verify_release_api_original((select jsonb_set(v#>'{snapshot,api_originals,0}','{acknowledgment,capture_hash}',to_jsonb(repeat('0',64))) from data where k='preview'),'1-ezyvet-original-701.pdf','application/pdf',convert_to('%PDF-test123','UTF8'),1)$$,'23514',null,'Wrong acknowledgment evidence rejected');
-- Extra acknowledgment is append-only clinical evidence, not a source mutation.
insert into user_roles(user_id,role) values('db710000-0000-4000-8000-000000000002','DVM');
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db710000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select acknowledge_ezyvet_attachment_original(gen_random_uuid(),(select id from fx where k='pet'),(select v#>>'{record,id}' from data where k='approved')::uuid,(select v#>>'{record,record_hash}' from data where k='approved'),(select v#>>'{record,capture_hash}' from data where k='approved'),true);
select is(preview_record_release_v9((select id from fx where k='pet'),(select id from fx where k='client'),'EMAIL','attachment@example.test',(select v from data where k='selection')),(select v from data where k='preview'),'Later acknowledgment preserves earliest frozen entry');
select is((read_record_release((select id from fx where k='release'))->>'eligible')::boolean,true,'Later acknowledgment does not invalidate release');
reset role;
update ezyvet_identity_heads set version=version+1 where resource in('animal','attachment');
select is(release_preview_v9_internal((select id from fx where k='pet'),(select id from fx where k='client'),'EMAIL','attachment@example.test',(select v from data where k='selection')),(select v from data where k='preview'),'Provider head refresh preserves admitted original');
select is((release_read_internal((select id from fx where k='release'))->>'eligible')::boolean,true,'Provider head refresh does not invalidate API-only release');
savepoint replaced;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db710000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select approve_ezyvet_attachment_original((select id from fx where k='approve2'),(select id from fx where k='pet'),(select v#>>'{request,capture,id}' from data where k='ready2')::uuid,(select v#>>'{request,capture,capture_hash}' from data where k='ready2'),1,(select v#>>'{record,id}' from data where k='approved')::uuid,'Explicit replacement',true);
select is((read_record_release((select id from fx where k='release'))->>'eligible')::boolean,false,'Replacement invalidates pending release');
rollback to replaced;
savepoint withdrawn;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db710000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select withdraw_ezyvet_attachment_original((select id from fx where k='withdraw'),(select id from fx where k='pet'),(select v#>>'{record,id}' from data where k='approved')::uuid,(select v#>>'{record,record_hash}' from data where k='approved'),'Withdraw after review');
select is((read_record_release((select id from fx where k='release'))->>'eligible')::boolean,false,'Withdrawal invalidates pending release');
select is(jsonb_array_length(list_record_release_sources_v9((select id from fx where k='pet'))->'api_original_ids'),0,'Withdrawn record excluded from candidates');
rollback to withdrawn;
reset role;
select ok(not has_function_privilege('authenticated','public.get_release_api_original_context(text,uuid,uuid,uuid)','execute'),'Staff cannot get private byte locator');
select ok(has_function_privilege('service_role','public.get_release_api_original_context(text,uuid,uuid,uuid)','execute'),'Service can resolve exact prepared delivery context');
select ok(not has_function_privilege('anon','public.preview_record_release_v9(uuid,uuid,text,text,jsonb)','execute'),'Anonymous cannot preview');
select ok(not has_function_privilege('authenticated','public.release_api_original_entry(uuid)','execute'),'Private projection not callable');
select * from finish();rollback;
