begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select no_plan();
-- FIXTURE_BEGIN: synthetic scoped outside history and local actors.
insert into auth.users(id,email,raw_user_meta_data) values('db490000-0000-4000-8000-000000000001','clinical-import-admin@example.test','{}'),('db490000-0000-4000-8000-000000000002','clinical-import-other@example.test','{}');
insert into user_roles(user_id,role) values('db490000-0000-4000-8000-000000000001','ADMIN'),('db490000-0000-4000-8000-000000000002','DVM');
create temp table fx(k text primary key,id uuid);create temp table data(k text primary key,v jsonb);grant all on fx,data to authenticated,service_role;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db490000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'client',id from save_client(auth.uid(),null,null,'Clinical','Import','+13035550199','clinical-import@example.test','EMAIL',null,null);
insert into fx select 'pet',id from save_patient(null,(select id from fx where k='client'),null,'Scoped dog','Dog',null,null,'unknown',null,'unknown','unknown',null,null,null);
insert into fx select k,gen_random_uuid() from unnest(array['mapping','mapping2','snapshot','snapshot2','legacy','terminal','run','history','other-run']) k;
reset role;
insert into ezyvet_import_snapshots(id,source_origin,source_site_uid,resource,external_id,payload,payload_hash,first_seen_by) select id,'https://api.trial.ezyvet.com','clinical-test-site','animal',case when k='snapshot' then '77' else '88' end,jsonb_build_object('id',case when k='snapshot' then 77 else 88 end),k,'db490000-0000-4000-8000-000000000001' from fx where k in ('snapshot','snapshot2');
insert into ezyvet_record_links(id,request_id,request_hash,source_origin,source_site_uid,resource,external_id,snapshot_id,head_version,client_id,pet_id,local_version,action,reason,approved_by)
select id,gen_random_uuid(),k,'https://api.trial.ezyvet.com','clinical-test-site','animal',case when k='mapping' then '77' else '88' end,(select id from fx where k=case when m.k='mapping' then 'snapshot' else 'snapshot2' end),1,(select id from fx where k='client'),(select id from fx where k='pet'),1,'link','Synthetic approved mapping','db490000-0000-4000-8000-000000000001' from fx m where k in ('mapping','mapping2');
insert into data values('items','[{"external_id":"101","payload":{"id":101,"animal_id":77,"comments":"<script>outside prose</script>","vet_id":"outside-user","history_system":"opaque"}}]');
insert into fx select k,gen_random_uuid() from unnest(array['source-approval','extraction','linked','tombstone','second-extraction','later-source','discrepancy','release']) k;
set local role service_role;
insert into data select 'run',claim_ezyvet_clinical_import((select id from fx where k='run'),'db490000-0000-4000-8000-000000000001','clinical-test-site','history','https://api.trial.ezyvet.com',(select id from fx where k='mapping'));
select stage_ezyvet_import_page((select id from fx where k='run'),'db490000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='run'),1,true,(select v from data where k='items'));
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db490000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into data select 'candidate',list_ezyvet_clinical_candidates((select id from fx where k='mapping'),'history')#>'{candidates,0}';
insert into data select 'source-payload',jsonb_build_object('animal_link_id',(select id from fx where k='mapping'),'snapshot_id',v->'id','payload_hash',v->'payload_hash','observed_head_version',v->'head_version','patient_version',1,'consult_mode','not_referenced','consult_snapshot_id',null,'consult_payload_hash',null,'consult_head_version',null,'reason','PRIVATE administrator source review') from data where k='candidate';
insert into data select 'prepared-source',prepare_ezyvet_history_approval((select id from fx where k='source-approval'),(select id from fx where k='pet'),(select v from data where k='source-payload'));
insert into data select 'source-receipt',approve_ezyvet_history((select id from fx where k='source-approval'),(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='prepared-source'),true);
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db490000-0000-4000-8000-000000000002","role":"authenticated"}',true);
insert into data select 'extraction-payload',jsonb_build_object('sources',jsonb_build_array(jsonb_build_object('id',v#>'{receipt,id}','version_hash',v#>'{receipt,version_hash}')),'patient_version',1,'action','create','problem_id',null,'problem_version',null,'fields',jsonb_build_object('title','Reviewed vaccine reaction','notes','DVM-authored reviewed finding','onset_date',null,'status','active','importance','high'),'duplicate_decision','distinct_finding','reason','PRIVATE DVM duplicate review') from data where k='source-receipt';
insert into data select 'prepared-extraction',prepare_ezyvet_problem_extraction((select id from fx where k='extraction'),(select id from fx where k='pet'),(select v from data where k='extraction-payload'));
insert into data select 'extraction-receipt',approve_ezyvet_problem_extraction((select id from fx where k='extraction'),(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='prepared-extraction'),true);
insert into fx select 'problem',(v#>>'{receipt,problem_id}')::uuid from data where k='extraction-receipt';

reset role;
insert into ezyvet_identity_heads(source_origin,source_site_uid,resource,external_id,snapshot_id,version)
select source_origin,source_site_uid,resource,external_id,id,1 from ezyvet_import_snapshots where id=(select id from fx where k='snapshot');
insert into fx select k,gen_random_uuid() from unnest(array['migration','scope','binding','approval2']) k;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db490000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select prepare_ezyvet_migration_run((select id from fx where k='migration'),'https://api.trial.ezyvet.com','clinical-test-site',jsonb_build_array(jsonb_build_object('id',(select id from fx where k='scope'),'mapping_id',(select id from fx where k='mapping'),'resource','history','parent_type','animal','parent_snapshot_id',(select id from fx where k='snapshot'),'parent_head_version',1,'disposition','required','reason','Synthetic history coverage')));
select bind_ezyvet_migration_child((select id from fx where k='binding'),(select id from fx where k='scope'),(select id from fx where k='run'),'Synthetic history run');
insert into data select 'item',list_ezyvet_migration_items((select id from fx where k='binding'))#>'{items,0}';
create function pg_temp.receipts(bef integer default null,lim integer default 20) returns jsonb language sql as $$
select list_ezyvet_migration_history_evidence((select id from fx where k='binding'),1,(v->>'snapshot_id')::uuid,v->>'evidence_hash',bef,lim) from data where k='item';$$;
insert into data select 'first',pg_temp.receipts();
select is((select v#>>'{approvals,0,relationship}' from data where k='first'),'exact_source_version','Approval matches server-verified source evidence hash');
select is((select v#>>'{approvals,0,source_current}' from data where k='first'),'true','Initial reviewed source context is current');
select is((select v#>>'{approvals,0,extraction_receipts}' from data where k='first'),'1','DVM extraction by different actor is visible without exposing pending requests');
select is((select v#>>'{approvals,0,locally_edited_receipts}' from data where k='first'),'0','Unedited local finding is separate from source approval');
select ok(not (select v::text from data where k='first') ~ 'PRIVATE|outside prose|problem_fields|request_hash','Projection omits prose, reasons and request payloads');
select is(pg_temp.receipts()->>'complete_coverage_verified','false','Review receipts never imply accepted coverage');
select is(pg_temp.receipts()->>'discrepancies_assessed','false','Discrepancy assessment remains explicit');
select throws_ok($$select list_ezyvet_migration_history_evidence((select id from fx where k='binding'),1,(v->>'snapshot_id')::uuid,repeat('a',64)) from data where k='item'$$,'42501','Exact owned history observation required','Substituted hash denied');
select throws_ok($$select list_ezyvet_migration_history_evidence((select id from fx where k='binding'),2,(v->>'snapshot_id')::uuid,v->>'evidence_hash') from data where k='item'$$,'42501','Exact owned history observation required','Substituted page denied');
select throws_ok($$select pg_temp.receipts(null,101)$$,'23514','Invalid history evidence identity or cursor','Unbounded page denied');
insert into data select 'prepared2',prepare_ezyvet_history_approval((select id from fx where k='approval2'),(select id from fx where k='pet'),(select v from data where k='source-payload'));
select approve_ezyvet_history((select id from fx where k='approval2'),(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='prepared2'),true);
select is(pg_temp.receipts(null,1)#>>'{approvals,0,version}','2','Latest correction appears first');
select is(pg_temp.receipts(null,1)->>'has_more','true','Sentinel provides bounded version history');
select is(pg_temp.receipts(null,1)->>'next_before_version','2','Cursor is last selected version');
select is(pg_temp.receipts(2,1)#>>'{approvals,0,superseded}','true','Prior approval remains visible as superseded');
select is(pg_temp.receipts(2,1)->>'has_more','false','Last page is terminal');
reset role;
insert into fx select k,gen_random_uuid() from unnest(array['changed-run','approval3']) k;
update ezyvet_import_runs set retry_after=null where source_site_uid='clinical-test-site' and resource='history';
insert into data select 'changed-run',claim_ezyvet_clinical_import((select id from fx where k='changed-run'),'db490000-0000-4000-8000-000000000001','clinical-test-site','history','https://api.trial.ezyvet.com',(select id from fx where k='mapping'));
select stage_ezyvet_import_page((select id from fx where k='changed-run'),'db490000-0000-4000-8000-000000000001',(select(v->>'lease_id')::uuid from data where k='changed-run'),1,true,'[{"external_id":"101","payload":{"id":101,"animal_id":77,"comments":"Changed source prose"}}]');
set local role authenticated;
insert into data select 'changed-payload',old.v||jsonb_build_object('snapshot_id',c->'id','payload_hash',c->'payload_hash','observed_head_version',c->'head_version') from data old cross join lateral (select list_ezyvet_clinical_candidates((select id from fx where k='mapping'),'history')#>'{candidates,0}' c) candidate where old.k='source-payload';
insert into data select 'prepared3',prepare_ezyvet_history_approval((select id from fx where k='approval3'),(select id from fx where k='pet'),(select v from data where k='changed-payload'));
select approve_ezyvet_history((select id from fx where k='approval3'),(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='prepared3'),true);
select is(pg_temp.receipts()#>>'{approvals,0,relationship}','different_source_version','New source approval remains distinguishable from bound observation');
select is(pg_temp.receipts()#>>'{approvals,0,source_current}','true','Approval on changed source is independently current');
select is(pg_temp.receipts()#>>'{approvals,0,extraction_receipts}','0','Old extraction is not credited to a new approved version');
reset role;
-- Restore the original payload at a newer head to model A to B to A.
update ezyvet_identity_heads set snapshot_id=(select(v->>'snapshot_id')::uuid from data where k='item') where resource='history' and source_site_uid='clinical-test-site';
update patient_problems set version=version+1,notes='Later local clinician edit' where id=(select id from fx where k='problem');
update ezyvet_identity_heads set version=version+2 where resource='history' and source_site_uid='clinical-test-site';
set local role authenticated;
select is(pg_temp.receipts(2,1)#>>'{approvals,0,locally_edited_receipts}','1','Local edit is retained and reported');
select is(pg_temp.receipts(2,1)#>>'{approvals,0,source_current}','false','A to B to A invalidates currentness despite same payload');
select is(pg_temp.receipts(2,1)#>>'{approvals,0,relationship}','exact_source_version','Source drift does not rewrite the old observation receipt');
select is((select notes from patient_problems where id=(select id from fx where k='problem')),'Later local clinician edit','Evidence reads preserve local chart fields');
select set_config('request.jwt.claims','{"sub":"db490000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select throws_ok($$select pg_temp.receipts()$$,'42501','Active administrator required','DVM-only actor cannot read migration receipts');
reset role;insert into user_roles(user_id,role) values('db490000-0000-4000-8000-000000000002','ADMIN');set local role authenticated;
select throws_ok($$select pg_temp.receipts()$$,'42501','Exact owned history observation required','Different administrator cannot read owned observation');
reset role;
update profiles set is_active=false where id='db490000-0000-4000-8000-000000000001';
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db490000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select throws_ok($$select pg_temp.receipts()$$,'42501','Active administrator required','Inactive owner denied');
reset role;
select ok(not has_function_privilege('anon','public.list_ezyvet_migration_history_evidence(uuid,integer,uuid,text,integer,integer)','execute'),'Anonymous read denied');
select ok(not has_function_privilege('service_role','public.list_ezyvet_migration_history_evidence(uuid,integer,uuid,text,integer,integer)','execute'),'Worker read denied');
select * from finish();rollback;
