begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select no_plan();
select ok(exists(select 1 from ezyvet_migration_dependency_tables where table_name='ezyvet_identity_heads'),'Source heads are journaled');
select ok(exists(select 1 from ezyvet_migration_dependency_tables where table_name='ezyvet_migration_bindings'),'Binding changes are journaled');
select ok(exists(select 1 from ezyvet_migration_dependency_tables where table_name='patient_problems'),'Local clinical edits are journaled');
select ok(exists(select 1 from ezyvet_migration_dependency_tables where table_name='user_roles'),'Authorization changes are journaled');
select is((select count(*) from ezyvet_migration_dependency_tables where table_name in ('ezyvet_migration_preparations','ezyvet_migration_source_chunks','ezyvet_migration_review_pages')),0::bigint,'Report progress does not invalidate its own dependencies');
select is((select count(*) from ezyvet_migration_dependency_tables d where not exists(select 1 from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname=d.table_name and t.tgname='migration_dependency_change' and t.tgenabled='O')),0::bigint,'Every inventoried dependency has enabled journal trigger');
create temp table boundary as select coalesce(max(id),0) id from ezyvet_migration_dependency_changes;
update patient_problems set version=version where false;
select is((select count(*) from ezyvet_migration_dependency_changes where id>(select id from boundary)),1::bigint,'One journal event per statement, even empty conservative invalidation');
select is((select transaction_id from ezyvet_migration_dependency_changes where id>(select id from boundary)),pg_current_xact_id(),'Journal records top-level transaction identity');
select is((select operation from ezyvet_migration_dependency_changes where id>(select id from boundary)),'UPDATE','Journal retains mutation kind');
savepoint discarded_statement;
delete from patient_weights where false;
rollback to savepoint discarded_statement;
select is((select count(*) from ezyvet_migration_dependency_changes where id>(select id from boundary)),1::bigint,'Rolled-back statement leaves no committed journal evidence');
select ok(not has_table_privilege('authenticated','public.ezyvet_migration_dependency_changes','select'),'Journal is not exposed to staff');
select ok(not has_table_privilege('service_role','public.ezyvet_migration_dependency_changes','insert'),'Worker cannot fabricate journal entries directly');
select ok(not has_function_privilege('authenticated','public.record_ezyvet_migration_dependency_change()','execute'),'Journal writer is trigger-only');
select * from finish();rollback;
