begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select no_plan();
-- FIXTURE_BEGIN: owner-only synthetic source observations and reviewed mapping.
insert into auth.users(id,email,raw_user_meta_data) values('db560000-0000-4000-8000-000000000001','clinical-import-admin@example.test','{}'),('db560000-0000-4000-8000-000000000002','clinical-import-other@example.test','{}');
insert into user_roles(user_id,role) values('db560000-0000-4000-8000-000000000001','ADMIN'),('db560000-0000-4000-8000-000000000002','ADMIN');
create temp table fx(k text primary key,id uuid);create temp table data(k text primary key,v jsonb);grant all on fx,data to authenticated,service_role;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db560000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'client',id from save_client(auth.uid(),null,null,'Clinical','Import','+13035550199','clinical-import@example.test','EMAIL',null,null);
insert into fx select 'pet',id from save_patient(null,(select id from fx where k='client'),null,'Scoped dog','Dog',null,null,'unknown',null,'unknown','unknown',null,null,null);
insert into fx select k,gen_random_uuid() from unnest(array['mapping','mapping2','snapshot','snapshot2','legacy','terminal','run','history','other-run']) k;
reset role;
insert into ezyvet_import_snapshots(id,source_origin,source_site_uid,resource,external_id,payload,payload_hash,first_seen_by) select id,'https://api.trial.ezyvet.com','prescriptionitem-test-site','animal',case when k='snapshot' then '77' else '88' end,jsonb_build_object('id',case when k='snapshot' then 77 else 88 end),k,'db560000-0000-4000-8000-000000000001' from fx where k in ('snapshot','snapshot2');
insert into ezyvet_record_links(id,request_id,request_hash,source_origin,source_site_uid,resource,external_id,snapshot_id,head_version,client_id,pet_id,local_version,action,reason,approved_by)
select id,gen_random_uuid(),k,'https://api.trial.ezyvet.com','prescriptionitem-test-site','animal',case when k='mapping' then '77' else '88' end,(select id from fx where k=case when m.k='mapping' then 'snapshot' else 'snapshot2' end),1,(select id from fx where k='client'),(select id from fx where k='pet'),1,'link','Synthetic approved mapping','db560000-0000-4000-8000-000000000001' from fx m where k in ('mapping','mapping2');
insert into ezyvet_identity_heads(source_origin,source_site_uid,resource,external_id,snapshot_id,version)
select source_origin,source_site_uid,resource,external_id,id,1 from ezyvet_import_snapshots where id=(select id from fx where k='snapshot');
insert into fx select k,gen_random_uuid() from unnest(array['request','request2','tombstone','consult-source','consult-run','consult-request']) k;
insert into data select 'run',claim_ezyvet_attachment_import((select id from fx where k='run'),'db560000-0000-4000-8000-000000000001','prescriptionitem-test-site','https://api.trial.ezyvet.com',(select id from fx where k='mapping'),'Animal',(select id from fx where k='snapshot'),'snapshot',1);
select stage_ezyvet_import_page((select id from fx where k='run'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='run'),1,false,'[{"external_id":"701","payload":{"id":701,"record_type":"Animal","record_id":77,"mime_type":"application/pdf","file_download_url":"https://untrusted.example.test/file","name":"Source file"}}]');
insert into data select 'observation',jsonb_build_object('snapshot_id',s.id,'hash',s.payload_hash,'version',h.version) from ezyvet_import_snapshots s join ezyvet_identity_heads h on h.snapshot_id=s.id where s.resource='attachment' and s.external_id='701';
insert into data values('side-effects',jsonb_build_object('documents',(select count(*) from patient_documents),'treatments',(select count(*) from patient_treatments),'invoices',(select count(*) from billing_invoices),'stock',(select count(*) from inventory_movements),'outbox',(select count(*) from communication_outbox)));
create function pg_temp.prepare(k text default 'request') returns jsonb language sql as $$
 select prepare_ezyvet_attachment_download((select id from fx where fx.k=$1),(select id from fx where fx.k='pet'),(select id from fx where fx.k='run'),1,(v->>'snapshot_id')::uuid,v->>'hash',(v->>'version')::integer) from data where data.k='observation';
$$;
set local role authenticated;
insert into data select 'saved',pg_temp.prepare();
insert into data select 'saved2',pg_temp.prepare('request2');
reset role;
create function pg_temp.claim(k text default 'request') returns jsonb language sql as $$
 select claim_ezyvet_attachment_download((select id from fx where fx.k=$1),'db560000-0000-4000-8000-000000000001',(select id from fx where fx.k='pet'),(select v#>>'{request,request_hash}' from data where data.k='saved'));
$$;
create function pg_temp.fail(code text,seconds integer,lease_key text default 'lease') returns jsonb language sql as $$
 select fail_ezyvet_attachment_download((select id from fx where fx.k='request'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where data.k=$3),(select v#>>'{request,request_hash}' from data where data.k='saved'),$1,$2);
$$;
select throws_ok($$select pg_temp.claim()$$,'55P03',null,'Download honors metadata page cooldown');
update ezyvet_import_runs set retry_after=null,lease_until=null where id=(select id from fx where k='run');
set local role service_role;
insert into data select 'lease',pg_temp.claim();
select is((select v->>'attempt_no' from data where k='lease'),'1','First service claim records an attempt');
select throws_ok($$select pg_temp.claim()$$,'55P03',null,'Repeated claim cannot return an active worker lease');
select throws_ok($$select pg_temp.claim('request2')$$,'55P03',null,'Other download on same source is serialized');
select throws_ok($$select claim_ezyvet_attachment_download((select id from fx where k='request'),'db560000-0000-4000-8000-000000000002',(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='saved'))$$,'42501',null,'Wrong service actor rejected');
select throws_ok($$select claim_ezyvet_attachment_download((select id from fx where k='request'),'db560000-0000-4000-8000-000000000001',gen_random_uuid(),(select v#>>'{request,request_hash}' from data where k='saved'))$$,'42501',null,'Wrong patient rejected');
select throws_ok($$select claim_ezyvet_attachment_import(gen_random_uuid(),'db560000-0000-4000-8000-000000000001','prescriptionitem-test-site','https://api.trial.ezyvet.com',(select id from fx where k='mapping'),'Animal',(select id from fx where k='snapshot'),'snapshot',1)$$,'55P03',null,'Metadata import honors active download lease');
set local role authenticated;
select ok((recover_ezyvet_attachment_download((select id from fx where k='request'),(select id from fx where k='pet'))#>>'{worker,lease_active}')::boolean,'Owner can see active worker state');
select ok(not ((recover_ezyvet_attachment_download((select id from fx where k='request'),(select id from fx where k='pet'))::text) like '%'||(select v->>'lease_id' from data where k='lease')||'%'),'Service lease ID is absent from recovery');
select throws_ok($$select abandon_ezyvet_attachment_download((select id from fx where k='request'),(select id from fx where k='pet'),true)$$,'55P03',null,'Abandon cannot race an active worker');
set local role service_role;
select throws_ok($$select pg_temp.fail('TOKEN_OR_URL_NOT_ALLOWED',10)$$,'23514','Invalid download failure code','Failure code must be sanitized and allowlisted');
select throws_ok($$select pg_temp.fail('RATE_LIMITED',0)$$,'23514',null,'Retryable failure requires bounded delay');
select throws_ok($$select pg_temp.fail('ATTACHMENT_TOO_LARGE',10)$$,'23514',null,'Permanent discrepancy cannot masquerade as timed retry');
select throws_ok($$select fail_ezyvet_attachment_download((select id from fx where k='request'),'db560000-0000-4000-8000-000000000001',gen_random_uuid(),(select v#>>'{request,request_hash}' from data where k='saved'),'RATE_LIMITED',30)$$,'42501',null,'Unknown lease cannot publish failure');
insert into data select 'failure',pg_temp.fail('RATE_LIMITED',30);
select is(pg_temp.fail('RATE_LIMITED',30),(select v from data where k='failure'),'Lost failure acknowledgment recovers exactly');
select throws_ok($$select pg_temp.fail('RATE_LIMITED',31)$$,'40001',null,'Failure retry cannot change saved delay');
select throws_ok($$select pg_temp.claim()$$,'55P03',null,'Failed request retains cooldown');
select throws_ok($$select pg_temp.claim('request2')$$,'55P03',null,'Cooldown covers another request on the same site');
select throws_ok($$select claim_ezyvet_attachment_import(gen_random_uuid(),'db560000-0000-4000-8000-000000000001','prescriptionitem-test-site','https://api.trial.ezyvet.com',(select id from fx where k='mapping'),'Animal',(select id from fx where k='snapshot'),'snapshot',1)$$,'55P03',null,'Metadata respects download rate-limit receipt');
reset role;
-- Owner-only disposable fixture simulates elapsed wall time; production evidence is immutable.
set local session_replication_role=replica;
update ezyvet_attachment_download_failures set retry_after=clock_timestamp()-interval '1 second' where lease_id=(select (v->>'lease_id')::uuid from data where k='lease');
set local session_replication_role=origin;
set local role service_role;
insert into data select 'lease2',pg_temp.claim();
select is((select v->>'attempt_no' from data where k='lease2'),'2','Expired cooldown permits a new worker attempt');
select isnt((select v->>'lease_id' from data where k='lease2'),(select v->>'lease_id' from data where k='lease'),'Replacement attempt has a distinct service lease');
reset role;
set local session_replication_role=replica;
update ezyvet_attachment_download_attempts set created_at=clock_timestamp()-interval '100 seconds',lease_until=clock_timestamp()-interval '1 second' where lease_id=(select (v->>'lease_id')::uuid from data where k='lease2');
set local session_replication_role=origin;
set local role service_role;
insert into data select 'lease3',pg_temp.claim();
select is((select v->>'attempt_no' from data where k='lease3'),'3','Missing worker response can recover after lease expiry');
select throws_ok($$select pg_temp.fail('UPSTREAM_UNAVAILABLE',10,'lease2')$$,'40001',null,'Late superseded worker cannot publish a new failure');
insert into data select 'permanent',pg_temp.fail('ATTACHMENT_UNSUPPORTED_TYPE',0,'lease3');
select throws_ok($$select pg_temp.claim()$$,'23514',null,'Permanent discrepancy requires a new reviewed request');
set local role authenticated;
select is(recover_ezyvet_attachment_download((select id from fx where k='request'),(select id from fx where k='pet'))#>>'{worker,error_code}','ATTACHMENT_UNSUPPORTED_TYPE','Owner can inspect actionable discrepancy');
select is(abandon_ezyvet_attachment_download((select id from fx where k='request'),(select id from fx where k='pet'),true)#>>'{request,status}','abandoned','Failed lease permits abandonment');
set local role service_role;
select is(pg_temp.fail('ATTACHMENT_UNSUPPORTED_TYPE',0,'lease3'),(select v from data where k='permanent'),'Failure receipt recovers after abandonment');
select throws_ok($$select pg_temp.claim()$$,'23514',null,'Abandoned request cannot be claimed');
reset role;
update ezyvet_identity_heads set version=version+1 where resource='attachment' and external_id='701';
set local role service_role;
select throws_ok($$select pg_temp.claim('request2')$$,'40001','SOURCE_ATTACHMENT_STALE','Every fresh lease rechecks source currentness');
reset role;
select is((select count(*)::integer from ezyvet_attachment_download_attempts),3,'Invalid and busy requests created no extra attempts');
select throws_ok($$update ezyvet_attachment_download_attempts set request_hash=repeat('a',64)$$,'23514',null,'Attempt evidence cannot be rewritten');
select throws_ok($$delete from ezyvet_attachment_download_failures$$,'23514',null,'Failure receipts cannot be erased');
select ok(not has_table_privilege('service_role','public.ezyvet_attachment_download_attempts','insert'),'Service cannot bypass claim with direct insert');
select ok(not has_function_privilege('authenticated','public.claim_ezyvet_attachment_download(uuid,uuid,uuid,text)','execute'),'Browser cannot request a service lease');
select ok(not has_function_privilege('service_role','public.ezyvet_attachment_source_slot(text,text)','execute'),'Shared source slot helper remains private');
select is(jsonb_build_object('documents',(select count(*) from patient_documents),'treatments',(select count(*) from patient_treatments),'invoices',(select count(*) from billing_invoices),'stock',(select count(*) from inventory_movements),'outbox',(select count(*) from communication_outbox)),(select v from data where k='side-effects'),'Leases create no document, clinical, stock, billing or delivery effects');
select * from finish();rollback;
