begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select no_plan();
-- FIXTURE_BEGIN: owner-created legacy observations simulate a deployment predating4900.
insert into auth.users(id,email,raw_user_meta_data) values('db490000-0000-4000-8000-000000000001','clinical-import-admin@example.test','{}'),('db490000-0000-4000-8000-000000000002','clinical-import-other@example.test','{}');
update public.profiles set is_active = true where id in ('db490000-0000-4000-8000-000000000001','db490000-0000-4000-8000-000000000002');
insert into public.user_roles (user_id, role) values ('db490000-0000-4000-8000-000000000001','STAFF'),('db490000-0000-4000-8000-000000000002','STAFF');

insert into user_roles(user_id,role) values('db490000-0000-4000-8000-000000000001','ADMIN'),('db490000-0000-4000-8000-000000000002','ADMIN');
create temp table fx(k text primary key,id uuid);create temp table data(k text primary key,v jsonb);grant all on fx,data to authenticated,service_role;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db490000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'client',id from save_client(auth.uid(),null,null,'Clinical','Import','+13035550199','clinical-import@example.test','EMAIL',null,null);
insert into fx select 'pet',id from save_patient(null,(select id from fx where k='client'),null,'Scoped dog','Dog',null,null,'unknown',null,'unknown','unknown',null,null,null);
insert into fx select k,gen_random_uuid() from unnest(array['mapping','mapping2','snapshot','snapshot2','legacy','terminal','run','history','other-run']) k;
reset role;
insert into ezyvet_import_snapshots(id,source_origin,source_site_uid,resource,external_id,payload,payload_hash,first_seen_by) select id,'https://api.trial.ezyvet.com','clinical-test-site','animal',case when k='snapshot' then '77' else '88' end,jsonb_build_object('id',case when k='snapshot' then 77 else 88 end),k,'db490000-0000-4000-8000-000000000001' from fx where k in ('snapshot','snapshot2');
insert into ezyvet_record_links(id,request_id,request_hash,source_origin,source_site_uid,resource,external_id,snapshot_id,head_version,client_id,pet_id,local_version,action,reason,approved_by)
select id,gen_random_uuid(),k,'https://api.trial.ezyvet.com','clinical-test-site','animal',case when k='mapping' then '77' else '88' end,(select id from fx where k=case when m.k='mapping' then 'snapshot' else 'snapshot2' end),1,(select id from fx where k='client'),(select id from fx where k='pet'),1,'link','Synthetic approved mapping','db490000-0000-4000-8000-000000000001' from fx m where k in ('mapping','mapping2');
insert into data values('items','[{"external_id":"101","payload":{"id":101,"animal_id":77,"comments":"<script>outside prose</script>","vet_id":"outside-user","history_system":"opaque"}}]');
insert into data select 'legacy',to_jsonb(claim_ezyvet_import_core((select id from fx where k='legacy'),'db490000-0000-4000-8000-000000000001','clinical-test-site','consult','https://api.trial.ezyvet.com'));
select stage_ezyvet_import_page_core((select id from fx where k='legacy'),'db490000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='legacy'),1,false,(select v from data where k='items'));
update ezyvet_import_runs set retry_after=null where id=(select id from fx where k='legacy');
insert into data select 'terminal',to_jsonb(claim_ezyvet_import_core((select id from fx where k='terminal'),'db490000-0000-4000-8000-000000000001','clinical-test-site','history','https://api.trial.ezyvet.com'));
select stage_ezyvet_import_page_core((select id from fx where k='terminal'),'db490000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='terminal'),1,true,'[]');
update ezyvet_import_runs set retry_after=null where id=(select id from fx where k='terminal');
-- FIXTURE_END
-- A still-live legacy source lease remains authoritative after generic continuation is disabled.
update ezyvet_import_runs set lease_until=now()+interval '1 minute' where id=(select id from fx where k='legacy');
set local role service_role;
select throws_ok($$select claim_ezyvet_clinical_import((select id from fx where k='run'),'db490000-0000-4000-8000-000000000001','clinical-test-site','consult','https://api.trial.ezyvet.com',(select id from fx where k='mapping'))$$,'55P03',null,'New scoped UUID cannot bypass legacy lease');
reset role;update ezyvet_import_runs set lease_until=null where id=(select id from fx where k='legacy');
set local role authenticated;
select is(jsonb_array_length(list_ezyvet_clinical_candidates((select id from fx where k='mapping'),'consult')->'candidates'),0,'Generic matching snapshot is not eligible');
select is(recover_ezyvet_clinical_run((select id from fx where k='legacy'),(select id from fx where k='mapping'),'consult')->>'scope','legacy_unscoped','Legacy run recovery explicitly unscoped');
select is(jsonb_array_length(list_ezyvet_clinical_runs((select id from fx where k='mapping'),'consult')->'runs'),1,'Lost pointer legacy run discoverable');
select ok(not (list_ezyvet_clinical_runs((select id from fx where k='mapping'),'consult')::text like '%lease_id%'),'Safe discovery excludes lease token');
set local role service_role;
select throws_ok($$select claim_ezyvet_import(gen_random_uuid(),'db490000-0000-4000-8000-000000000001','clinical-test-site','consult','https://api.trial.ezyvet.com')$$,'23514',null,'Generic consult bypass denied');
select throws_ok($$select claim_ezyvet_import(gen_random_uuid(),'db490000-0000-4000-8000-000000000001','clinical-test-site','history','https://api.trial.ezyvet.com')$$,'23514',null,'Generic history bypass denied');
select throws_ok($$select claim_ezyvet_clinical_import((select id from fx where k='legacy'),'db490000-0000-4000-8000-000000000001','clinical-test-site','consult','https://api.trial.ezyvet.com',(select id from fx where k='mapping'))$$,'22023','CLINICAL_RUN_REQUIRES_NEW_MAPPING','Existing generic UUID cannot rebind');
select throws_ok($$select claim_ezyvet_clinical_import((select id from fx where k='terminal'),'db490000-0000-4000-8000-000000000001','clinical-test-site','history','https://api.trial.ezyvet.com',(select id from fx where k='mapping'))$$,'22023','CLINICAL_RUN_REQUIRES_NEW_MAPPING','Terminal generic UUID cannot rebind');
select throws_ok($$select stage_ezyvet_import_page((select id from fx where k='legacy'),'db490000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='legacy'),2,true,(select v from data where k='items'))$$,'22023','CLINICAL_RUN_REQUIRES_NEW_MAPPING','Late legacy page denied');
select is((select next_page from ezyvet_import_runs where id=(select id from fx where k='legacy')),2,'Late legacy denial retains cursor');
insert into data select 'run',claim_ezyvet_clinical_import((select id from fx where k='run'),'db490000-0000-4000-8000-000000000001','clinical-test-site','consult','https://api.trial.ezyvet.com',(select id from fx where k='mapping'));
select is((select v->>'animal_external_id' from data where k='run'),'77','Claim derives approved external patient');
select throws_ok($$select claim_ezyvet_clinical_import((select id from fx where k='other-run'),'db490000-0000-4000-8000-000000000001','clinical-test-site','consult','https://api.trial.ezyvet.com',(select id from fx where k='mapping2'))$$,'55P03',null,'Other mapped patient cannot bypass global source/resource lease');
select throws_ok($$select claim_ezyvet_clinical_import((select id from fx where k='run'),'db490000-0000-4000-8000-000000000001','clinical-test-site','consult','https://api.trial.ezyvet.com',(select id from fx where k='mapping2'))$$,'42501',null,'Run mapping cannot change');
select throws_ok($$select claim_ezyvet_clinical_import((select id from fx where k='run'),'db490000-0000-4000-8000-000000000002','clinical-test-site','consult','https://api.trial.ezyvet.com',(select id from fx where k='mapping'))$$,'42501',null,'Run actor cannot change');
select throws_ok($$select stage_ezyvet_import_page((select id from fx where k='run'),'db490000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='run'),1,true,(select v||'[{"external_id":"102","payload":{"id":102,"animal_id":88}}]' from data where k='items'))$$,'23514',null,'Mixed patient page fails atomically');
select is((select next_page from ezyvet_import_runs where id=(select id from fx where k='run')),1,'Rejected mixed page does not advance');
select throws_ok($$select stage_ezyvet_import_page((select id from fx where k='run'),'db490000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='run'),1,true,'[{"external_id":"101","payload":{"id":999,"animal_id":77}}]')$$,'23514',null,'Payload record ID checked in SQL');
select stage_ezyvet_import_page((select id from fx where k='run'),'db490000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='run'),1,false,(select v from data where k='items'));
select throws_ok($$select stage_ezyvet_import_page((select id from fx where k='run'),'db490000-0000-4000-8000-000000000001',null,2,true,'[]')$$,'40001',null,'Null cleared lease cannot advance a new clinical page');
set local role authenticated;
select is(jsonb_array_length(list_ezyvet_clinical_candidates((select id from fx where k='mapping'),'consult')->'candidates'),1,'Actual scoped observation makes dedup snapshot eligible');
select is(list_ezyvet_clinical_candidates((select id from fx where k='mapping'),'consult')#>>'{candidates,0,is_current}','true','Fresh scoped head is current');
select is(list_ezyvet_clinical_candidates((select id from fx where k='mapping'),'consult')#>>'{candidates,0,payload,comments}','<script>outside prose</script>','Original prose preserved without interpretation');
select is(recover_ezyvet_clinical_run((select id from fx where k='run'),(select id from fx where k='mapping'),'consult')->>'next_page','2','Lost page ACK recovers durable cursor');
select throws_ok($$select recover_ezyvet_clinical_run((select id from fx where k='run'),(select id from fx where k='mapping2'),'consult')$$,'42501',null,'Wrong mapping recovery denied');
set local role service_role;
select is((stage_ezyvet_import_page((select id from fx where k='run'),'db490000-0000-4000-8000-000000000001',gen_random_uuid(),1,false,(select v from data where k='items'))).next_page,2,'Exact committed retry recovers without old lease');
select throws_ok($$select stage_ezyvet_import_page((select id from fx where k='run'),'db490000-0000-4000-8000-000000000001',gen_random_uuid(),1,true,(select v from data where k='items'))$$,'40001',null,'Changed completion flag retry rejected');
select throws_ok($$select stage_ezyvet_import_page((select id from fx where k='run'),'db490000-0000-4000-8000-000000000001',gen_random_uuid(),1,false,'[{"external_id":"101","payload":{"id":101,"animal_id":77,"comments":"changed"}}]')$$,'40001',null,'Changed committed payload rejected');
reset role;
select is((select count(*)::integer from ezyvet_import_snapshots where resource='consult' and external_id='101'),1,'Generic and scoped duplicate share one snapshot');
select is((select count(*)::integer from ezyvet_clinical_pages),1,'One immutable clinical page receipt');
select throws_ok($$update ezyvet_clinical_runs set animal_external_id='88'$$,'23514',null,'Scoped context append-only');
select throws_ok($$delete from ezyvet_clinical_pages$$,'23514',null,'Page evidence append-only');
-- Simulate a previously generic source head A→B→A; it cannot manufacture a fresh scoped observation.
insert into ezyvet_import_snapshots(source_origin,source_site_uid,resource,external_id,payload,payload_hash,first_seen_by) values('https://api.trial.ezyvet.com','clinical-test-site','consult','101','{"id":101,"animal_id":77,"comments":"B"}','synthetic-B','db490000-0000-4000-8000-000000000001');
update ezyvet_identity_heads set snapshot_id=(select id from ezyvet_import_snapshots where payload_hash='synthetic-B'),version=version+1 where resource='consult' and source_site_uid='clinical-test-site';
update ezyvet_identity_heads set snapshot_id=(select snapshot_id from ezyvet_clinical_page_observations limit 1),version=version+1 where resource='consult' and source_site_uid='clinical-test-site';
set local role authenticated;
select is(list_ezyvet_clinical_candidates((select id from fx where k='mapping'),'consult')#>>'{candidates,0,is_current}','false','A→B→A does not revive older scoped head');
select is(list_ezyvet_clinical_candidates((select id from fx where k='mapping'),'consult')#>>'{candidates,0,is_current_snapshot}','true','Snapshot identity reversion remains accurately visible');
reset role;update ezyvet_import_runs set retry_after=null where id=(select id from fx where k='run');set local role service_role;
insert into data select 'continued',claim_ezyvet_clinical_import((select id from fx where k='run'),'db490000-0000-4000-8000-000000000001','clinical-test-site','consult','https://api.trial.ezyvet.com',(select id from fx where k='mapping'));
select stage_ezyvet_import_page((select id from fx where k='run'),'db490000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='continued'),2,true,(select v from data where k='items'));
set local role authenticated;
select is(list_ezyvet_clinical_candidates((select id from fx where k='mapping'),'consult')#>>'{candidates,0,is_current}','true','Fresh scoped re-observation captures current revision');
select is(list_ezyvet_clinical_candidates((select id from fx where k='mapping'),'consult')#>>'{candidates,0,observed_head_version}','3','A→B→A observed revision retained');
select is(recover_ezyvet_clinical_run((select id from fx where k='run'),(select id from fx where k='mapping'),'consult')->>'status','review_ready','Terminal state is traversal completion only');
select ok(not has_function_privilege('authenticated','claim_ezyvet_clinical_import(uuid,uuid,text,text,text,uuid)','EXECUTE'),'Browser cannot claim service lease');
select ok(not has_function_privilege('service_role','stage_ezyvet_import_page_core(uuid,uuid,uuid,integer,boolean,jsonb)','EXECUTE'),'Service cannot bypass clinical staging');
select ok(not has_table_privilege('authenticated','ezyvet_clinical_page_observations','SELECT'),'No direct observation table read');
set local role service_role;
select throws_ok($$select claim_ezyvet_clinical_import(gen_random_uuid(),'db490000-0000-4000-8000-000000000001','wrong-site','history','https://api.trial.ezyvet.com',(select id from fx where k='mapping'))$$,'42501',null,'Wrong source site mapping rejected');
insert into data select 'history',claim_ezyvet_clinical_import((select id from fx where k='history'),'db490000-0000-4000-8000-000000000001','clinical-test-site','history','https://api.trial.ezyvet.com',(select id from fx where k='mapping'));
select throws_ok($$select stage_ezyvet_import_page((select id from fx where k='history'),'db490000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='history'),1,true,(select jsonb_agg(jsonb_build_object('external_id',i::text,'payload',jsonb_build_object('id',i,'animal_id',77))) from generate_series(1,11) i))$$,'23514',null,'History SQL enforces documented ten item maximum');
insert into data values('history-items','[{"external_id":"301","payload":{"id":301,"animal_id":77,"chain":"opaque-chain","vet_id":"outside-author"}},{"external_id":"302","payload":{"id":302,"animal_id":77}}]');
select stage_ezyvet_import_page((select id from fx where k='history'),'db490000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='history'),1,true,(select v from data where k='history-items'));
select throws_ok($$select stage_ezyvet_import_page((select id from fx where k='history'),'db490000-0000-4000-8000-000000000001',gen_random_uuid(),1,true,(select jsonb_build_array(v->1,v->0) from data where k='history-items'))$$,'40001',null,'Original ordered page remains exact receipt identity despite sorted processing');
set local role authenticated;
select is(jsonb_array_length(list_ezyvet_clinical_candidates((select id from fx where k='mapping'),'history')->'candidates'),2,'History candidates independently patient-scoped');
select is(list_ezyvet_clinical_candidates((select id from fx where k='mapping'),'history',null,null,1)->>'has_more','true','Candidate pagination indicates more results');
insert into data select 'cursor',list_ezyvet_clinical_candidates((select id from fx where k='mapping'),'history',null,null,1)->'next_cursor';
select is(jsonb_array_length(list_ezyvet_clinical_candidates((select id from fx where k='mapping'),'history',(select (v->>'before_at')::timestamptz from data where k='cursor'),(select (v->>'before_id')::uuid from data where k='cursor'),1)->'candidates'),1,'Next candidate page contains remaining observation');
select is(list_ezyvet_clinical_runs((select id from fx where k='mapping'),'history',null,null,1)->>'has_more','true','Run history includes terminal legacy and scoped run with bounded paging');
select set_config('request.jwt.claims','{"sub":"db490000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select throws_ok($$select recover_ezyvet_clinical_run((select id from fx where k='run'),(select id from fx where k='mapping'),'consult')$$,'42501',null,'Another ADMIN cannot recover original actor run');
select is(jsonb_array_length(list_ezyvet_clinical_runs((select id from fx where k='mapping'),'consult')->'runs'),0,'Run discovery remains original-actor scoped');
reset role;delete from user_roles where user_id='db490000-0000-4000-8000-000000000002';set local role authenticated;
select throws_ok($$select list_ezyvet_clinical_candidates((select id from fx where k='mapping'),'consult')$$,'42501',null,'Staff without ADMIN cannot view source narratives');
-- Shared generic and healthstatus fresh-page lease regression.
reset role;set local role authenticated;select set_config('request.jwt.claims','{"sub":"db490000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx values('generic',gen_random_uuid());set local role service_role;insert into data select 'generic',to_jsonb(claim_ezyvet_import((select id from fx where k='generic'),'db490000-0000-4000-8000-000000000001','clinical-test-site','contact','https://api.trial.ezyvet.com'));
select throws_ok($$select stage_ezyvet_import_page((select id from fx where k='generic'),'db490000-0000-4000-8000-000000000001',null,1,false,'[ {"external_id":"901","payload":{"id":901,"animal_id":77,"weight":3,"weight_unit":"kg"}}]')$$,'40001',null,'generic: null caller lease cannot start page');
reset role;update ezyvet_import_runs set lease_until=now()-interval '1 second' where id=(select id from fx where k='generic');set local role service_role;
select throws_ok($$select stage_ezyvet_import_page((select id from fx where k='generic'),'db490000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='generic'),1,false,'[ {"external_id":"901","payload":{"id":901,"animal_id":77,"weight":3,"weight_unit":"kg"}}]')$$,'40001',null,'generic: expired lease denied');
reset role;update ezyvet_import_runs set lease_until=now()+interval '90 seconds' where id=(select id from fx where k='generic');set local role service_role;select stage_ezyvet_import_page((select id from fx where k='generic'),'db490000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='generic'),1,false,'[ {"external_id":"901","payload":{"id":901,"animal_id":77,"weight":3,"weight_unit":"kg"}}]');
select throws_ok($$select stage_ezyvet_import_page((select id from fx where k='generic'),'db490000-0000-4000-8000-000000000001',null,2,true,'[ {"external_id":"901","payload":{"id":901,"animal_id":77,"weight":3,"weight_unit":"kg"}}]')$$,'40001',null,'generic: cleared lease cannot advance page');
select is((stage_ezyvet_import_page((select id from fx where k='generic'),'db490000-0000-4000-8000-000000000001',null,1,false,'[ {"external_id":"901","payload":{"id":901,"animal_id":77,"weight":3,"weight_unit":"kg"}}]')).next_page,2,'generic: committed page still recovers after lease cleared');
reset role;update ezyvet_import_runs set retry_after=null where id=(select id from fx where k='generic');set local role service_role;update data set v=to_jsonb(claim_ezyvet_import((select id from fx where k='generic'),'db490000-0000-4000-8000-000000000001','clinical-test-site','contact','https://api.trial.ezyvet.com')) where k='generic';
select is((stage_ezyvet_import_page((select id from fx where k='generic'),'db490000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='generic'),2,true,'[ {"external_id":"901","payload":{"id":901,"animal_id":77,"weight":3,"weight_unit":"kg"}}]')).status,'review_ready','generic: renewed valid lease completes traversal');
set local role authenticated;
insert into fx values('weight',gen_random_uuid());set local role service_role;insert into data select 'weight',to_jsonb(claim_ezyvet_weight_import((select id from fx where k='weight'),'db490000-0000-4000-8000-000000000001','clinical-test-site','https://api.trial.ezyvet.com',(select id from fx where k='mapping')));
select throws_ok($$select stage_ezyvet_import_page((select id from fx where k='weight'),'db490000-0000-4000-8000-000000000001',null,1,false,'[ {"external_id":"901","payload":{"id":901,"animal_id":77,"weight":3,"weight_unit":"kg"}}]')$$,'40001',null,'weight: null caller lease cannot start page');
reset role;update ezyvet_import_runs set lease_until=now()-interval '1 second' where id=(select id from fx where k='weight');set local role service_role;
select throws_ok($$select stage_ezyvet_import_page((select id from fx where k='weight'),'db490000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='weight'),1,false,'[ {"external_id":"901","payload":{"id":901,"animal_id":77,"weight":3,"weight_unit":"kg"}}]')$$,'40001',null,'weight: expired lease denied');
reset role;update ezyvet_import_runs set lease_until=now()+interval '90 seconds' where id=(select id from fx where k='weight');set local role service_role;select stage_ezyvet_import_page((select id from fx where k='weight'),'db490000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='weight'),1,false,'[ {"external_id":"901","payload":{"id":901,"animal_id":77,"weight":3,"weight_unit":"kg"}}]');
select throws_ok($$select stage_ezyvet_import_page((select id from fx where k='weight'),'db490000-0000-4000-8000-000000000001',null,2,true,'[ {"external_id":"901","payload":{"id":901,"animal_id":77,"weight":3,"weight_unit":"kg"}}]')$$,'40001',null,'weight: cleared lease cannot advance page');
select is((stage_ezyvet_import_page((select id from fx where k='weight'),'db490000-0000-4000-8000-000000000001',null,1,false,'[ {"external_id":"901","payload":{"id":901,"animal_id":77,"weight":3,"weight_unit":"kg"}}]')).next_page,2,'weight: committed page still recovers after lease cleared');
reset role;update ezyvet_import_runs set retry_after=null where id=(select id from fx where k='weight');set local role service_role;update data set v=to_jsonb(claim_ezyvet_weight_import((select id from fx where k='weight'),'db490000-0000-4000-8000-000000000001','clinical-test-site','https://api.trial.ezyvet.com',(select id from fx where k='mapping'))) where k='weight';
select is((stage_ezyvet_import_page((select id from fx where k='weight'),'db490000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='weight'),2,true,'[ {"external_id":"901","payload":{"id":901,"animal_id":77,"weight":3,"weight_unit":"kg"}}]')).status,'review_ready','weight: renewed valid lease completes traversal');
set local role authenticated;
select * from finish();rollback;
