begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select no_plan();
-- FIXTURE_BEGIN

insert into auth.users(id,email,raw_user_meta_data) values('db700000-0000-4000-8000-000000000001','attachment-admin@example.test','{}'),('db700000-0000-4000-8000-000000000002','attachment-other@example.test','{}');
update public.profiles set is_active = true where id in ('db700000-0000-4000-8000-000000000001','db700000-0000-4000-8000-000000000002');
insert into public.user_roles (user_id, role) values ('db700000-0000-4000-8000-000000000001','STAFF'),('db700000-0000-4000-8000-000000000002','STAFF');

insert into user_roles(user_id,role) values('db700000-0000-4000-8000-000000000001','ADMIN'),('db700000-0000-4000-8000-000000000002','ADMIN');
create temp table fx(k text primary key,id uuid);create temp table data(k text primary key,v jsonb);grant all on fx,data to authenticated,service_role;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db700000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'client',id from save_client(auth.uid(),null,null,'Attachment','Owner','+13035550196','attachment@example.test','EMAIL',null,null);
insert into fx select 'pet',id from save_patient(null,(select id from fx where k='client'),null,'Metadata dog','Dog',null,null,'unknown',null,'unknown','unknown',null,null,null);
insert into fx select k,gen_random_uuid() from unnest(array['mapping','animal-run','run','run2','other-run']) k;
reset role;
insert into data select 'animal',to_jsonb(claim_ezyvet_import((select id from fx where k='animal-run'),'db700000-0000-4000-8000-000000000001','attachment-test-site','animal','https://api.trial.ezyvet.com'));
select stage_ezyvet_import_page((select id from fx where k='animal-run'),'db700000-0000-4000-8000-000000000001',(select(v->>'lease_id')::uuid from data where k='animal'),1,true,'[{"external_id":"77","payload":{"id":77}}]');
insert into ezyvet_record_links(id,request_id,request_hash,source_origin,source_site_uid,resource,external_id,snapshot_id,head_version,client_id,pet_id,local_version,action,reason,approved_by)
select (select id from fx where k='mapping'),gen_random_uuid(),'synthetic-approved-mapping',s.source_origin,s.source_site_uid,s.resource,s.external_id,s.id,h.version,(select id from fx where k='client'),(select id from fx where k='pet'),1,'link','Synthetic reviewed mapping','db700000-0000-4000-8000-000000000001' from ezyvet_import_snapshots s join ezyvet_identity_heads h on h.snapshot_id=s.id where s.resource='animal' and s.source_site_uid='attachment-test-site';
insert into data values('observation',jsonb_build_object('external_id','701','file_id','42','metadata',jsonb_build_object('id','701','file_id','42','record_type','Animal','record_id','77','name','Synthetic report','mime_type','application/pdf','notes',null),'raw_record_sha256',repeat('a',64),'stable_metadata_sha256',repeat('b',64),'file_sha256',null));
insert into data select 'page',jsonb_build_object('contract_version','ezyvet_animal_attachment_metadata_v1','parent',jsonb_build_object('record_type','Animal','record_id','77'),'page',1,'complete',true,'pagination',jsonb_build_object('items_page',1,'items_page_total',1,'items_page_size',10,'items_total',2),'observations',jsonb_build_array(v,jsonb_set(v,'{raw_record_sha256}',to_jsonb(repeat('c',64)))),'page_sha256',repeat('d',64)) from data where k='observation';
insert into data values('side-effects',jsonb_build_object('treatments',(select count(*) from patient_treatments),'invoices',(select count(*) from billing_invoices),'stock',(select count(*) from inventory_movements),'outbox',(select count(*) from communication_outbox),'objects',(select count(*) from storage.objects)));

insert into data select 'run',claim_ezyvet_attachment_import((select id from fx where k='run'),'db700000-0000-4000-8000-000000000001','attachment-test-site','https://api.trial.ezyvet.com',(select id from fx where k='mapping'));
select stage_ezyvet_attachment_page((select id from fx where k='run'),'db700000-0000-4000-8000-000000000001',(select(v->>'lease_id')::uuid from data where k='run'),(select v from data where k='page'));
update ezyvet_import_runs set retry_after=null where resource='attachment';
insert into fx select k,gen_random_uuid() from unnest(array['capture','capture2','capture3','capture4']) k;
insert into fx select 'attachment-snapshot',snapshot_id from ezyvet_attachment_page_observations where run_id=(select id from fx where k='run') and ordinal=1;
-- FIXTURE_END
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db700000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select throws_ok($$select prepare_ezyvet_attachment_capture((select id from fx where k='capture'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,3,(select id from fx where k='attachment-snapshot'),1,repeat('b',64))$$,'42501',null,'Unobserved ordinal rejected');
select throws_ok($$select prepare_ezyvet_attachment_capture((select id from fx where k='capture'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,1,(select id from fx where k='attachment-snapshot'),1,repeat('f',64))$$,'42501',null,'Wrong stable digest rejected');
insert into data select 'capture',prepare_ezyvet_attachment_capture((select id from fx where k='capture'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,1,(select id from fx where k='attachment-snapshot'),1,repeat('b',64));
select is((select v->>'status' from data where k='capture'),'prepared','Explicit owned observation prepared');
select is((select v->>'file_id' from data where k='capture'),'42','File identity retained separately from attachment identity');
select ok(not((select v from data where k='capture') ?| array['lease_id','intent','object_path']),'Browser projection hides service data');
select is(prepare_ezyvet_attachment_capture((select id from fx where k='capture'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,1,(select id from fx where k='attachment-snapshot'),1,repeat('b',64)),(select v from data where k='capture'),'Lost preparation reply recovers exact immutable request');
select throws_ok($$select prepare_ezyvet_attachment_capture((select id from fx where k='capture'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,2,(select id from fx where k='attachment-snapshot'),1,repeat('b',64))$$,'42501',null,'Same UUID cannot switch duplicate ordinal');
select set_config('request.jwt.claims','{"sub":"db700000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select throws_ok($$select recover_ezyvet_attachment_capture((select id from fx where k='capture'),(select id from fx where k='mapping'))$$,'42501',null,'Other administrator cannot recover');
select is(jsonb_array_length(list_ezyvet_attachment_captures((select id from fx where k='mapping'))->'captures'),0,'Discovery is owner scoped');
select throws_ok($$select prepare_ezyvet_attachment_capture((select id from fx where k='capture2'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,1,(select id from fx where k='attachment-snapshot'),1,repeat('b',64))$$,'42501',null,'Another admin cannot capture the owned metadata run');
reset role;set local role service_role;
insert into data select 'claimed',claim_ezyvet_attachment_capture((select id from fx where k='capture'),'db700000-0000-4000-8000-000000000001');
select ok((select v->>'lease_id' is not null from data where k='claimed'),'Service worker receives lease');
select throws_ok($$select claim_ezyvet_attachment_capture((select id from fx where k='capture'),'db700000-0000-4000-8000-000000000001')$$,'55P03',null,'Concurrent worker cannot duplicate claim');
select throws_ok($$select claim_ezyvet_attachment_import((select id from fx where k='other-run'),'db700000-0000-4000-8000-000000000001','attachment-test-site','https://api.trial.ezyvet.com',(select id from fx where k='mapping'))$$,'55P03',null,'Metadata scan respects original capture source lease');
select throws_ok($$select reserve_ezyvet_attachment_original((select id from fx where k='capture'),'db700000-0000-4000-8000-000000000001',null,repeat('e',64),'application/pdf',12,repeat('a',64),repeat('c',64))$$,'40001',null,'Reserve requires current lease');
insert into data select 'reserved',reserve_ezyvet_attachment_original((select id from fx where k='capture'),'db700000-0000-4000-8000-000000000001',(select(v->>'lease_id')::uuid from data where k='claimed'),repeat('e',64),'application/pdf',12,repeat('a',64),repeat('c',64));
select is((select v#>>'{request,status}' from data where k='reserved'),'reserved','Verified byte intent reserves private object');
select isnt((select v#>>'{intent,before_raw_sha256}' from data where k='reserved'),(select v#>>'{intent,after_raw_sha256}' from data where k='reserved'),'Raw URL renewal digests need not match');
select throws_ok($$select reserve_ezyvet_attachment_original((select id from fx where k='capture'),'db700000-0000-4000-8000-000000000001',(select(v->>'lease_id')::uuid from data where k='claimed'),repeat('f',64),'application/pdf',12,repeat('a',64),repeat('c',64))$$,'23514',null,'Intent bytes cannot change');
select throws_ok($$select complete_ezyvet_attachment_capture((select id from fx where k='capture'),'db700000-0000-4000-8000-000000000001',(select(v->>'lease_id')::uuid from data where k='claimed'),(select(v#>>'{intent,id}')::uuid from data where k='reserved'),repeat('e',64),'application/pdf',12)$$,'23514',null,'Missing object cannot complete');
reset role;set local role authenticated;select set_config('request.jwt.claims','{"sub":"db700000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select lives_ok($$insert into storage.objects(bucket_id,name,metadata) select 'ezyvet-attachment-originals',v#>>'{intent,object_path}','{"size":12,"mimetype":"application/pdf"}'::jsonb from data where k='reserved'$$,'Owning JWT may insert only reserved object');
select is((select count(*)::integer from storage.objects where bucket_id='ezyvet-attachment-originals'),0,'Direct object reads denied even to uploader');
select throws_ok($$insert into storage.objects(bucket_id,name,metadata) values('ezyvet-attachment-originals','other/path','{}')$$,'42501',null,'Unreserved object upload denied');
reset role;set local role service_role;
insert into data select 'ready',complete_ezyvet_attachment_capture((select id from fx where k='capture'),'db700000-0000-4000-8000-000000000001',(select(v->>'lease_id')::uuid from data where k='claimed'),(select(v#>>'{intent,id}')::uuid from data where k='reserved'),repeat('e',64),'application/pdf',12);
select is((select v#>>'{request,status}' from data where k='ready'),'ready','Readback-attested original becomes ready');
select is((select v#>>'{request,capture,entry_method}' from data where k='ready'),'ezyvet_api_attachment_original_v1','Capture never claims manual export provenance');
select is(complete_ezyvet_attachment_capture((select id from fx where k='capture'),'db700000-0000-4000-8000-000000000001',null,(select(v#>>'{intent,id}')::uuid from data where k='reserved'),repeat('e',64),'application/pdf',12),(select v from data where k='ready'),'Lost completion reply recovers before lease validation');
select throws_ok($$select begin_discard_ezyvet_attachment_capture((select id from fx where k='capture'),'db700000-0000-4000-8000-000000000001')$$,'23514',null,'Captured object cannot be discarded');
reset role;
insert into fx select 'approval',gen_random_uuid();insert into fx select 'correction',gen_random_uuid();
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"db700000-0000-4000-8000-000000000001","role":"authenticated"}',true);
create function pg_temp.approve_original(k text default 'approval',previous_id uuid default null,attest boolean default true,title text default 'Reviewed canonical original') returns public.ezyvet_attachment_record_versions language sql as $$
 select approve_ezyvet_attachment_record((select id from fx where fx.k=$1),(select id from fx where fx.k='capture'),(select id from fx where fx.k='pet'),(select v#>>'{request,capture,capture_hash}' from data where data.k='ready'),$2,$4,'Synthetic verified original inspection',$3);
$$;
select throws_ok($$select pg_temp.approve_original('approval',null,false)$$,'23514',null,'Original approval requires explicit attestation');
select is(jsonb_array_length(read_ezyvet_attachment_chart((select id from fx where k='pet'))->'records'),0,'Captured but unreviewed originals are absent from chart');
insert into data select 'approved',to_jsonb(pg_temp.approve_original());
select is((select v->>'entry_method' from data where k='approved'),'staff_reviewed_api_attachment_v2','Approval identifies canonical original contract');
select is((select v#>>'{source_context,capture_contract}' from data where k='approved'),'canonical_api_original_v1','Stable metadata and file identity retain canonical provenance');
select is(to_jsonb(pg_temp.approve_original()),(select v from data where k='approved'),'Exact approval replay preserves saved record');
select throws_ok($$select pg_temp.approve_original('approval',null,true,'Different title')$$,'23505',null,'Approval UUID cannot change reviewed intent');
select throws_ok($$select pg_temp.approve_original('correction')$$,'40001',null,'Correction requires exact predecessor');
insert into data select 'corrected',to_jsonb(pg_temp.approve_original('correction',(select id from fx where k='approval')));
select is((select(v->>'version')::integer from data where k='corrected'),2,'Canonical original correction appends version2');
select is((select v#>>'{source_context,file_id}' from data where k='corrected'),(select v#>>'{request,file_id}' from data where k='ready'),'Separate file ID remains bound to approval');
insert into data select 'chart-page',read_ezyvet_attachment_chart((select id from fx where k='pet'),null,null,1);
select is((select v#>>'{records,0,record,id}' from data where k='chart-page'),(select id::text from fx where k='correction'),'Chart starts at latest reviewed correction');
select is((select v#>>'{records,0,is_latest}' from data where k='chart-page'),'true','Latest review marked separately');
select is((select v#>>'{records,0,source_current}' from data where k='chart-page'),'true','Chart verifies canonical source currentness');
select ok(not (select (v#>'{records,0,record}') ? 'source_context' from data where k='chart-page'),'Chart omits raw source context');
insert into data select 'chart-older',read_ezyvet_attachment_chart((select id from fx where k='pet'),(select(v#>>'{next_cursor,before_at}')::timestamptz from data where k='chart-page'),(select(v#>>'{next_cursor,before_id}')::uuid from data where k='chart-page'),1);
select is((select v#>>'{records,0,is_latest}' from data where k='chart-older'),'false','Earlier reviewed version remains discoverable as superseded');
select is((select v->>'has_more' from data where k='chart-older'),'false','Chart pagination terminates');
select is(jsonb_array_length(read_ezyvet_attachment_chart((select id from fx where k='client'))->'records'),0,'Another patient scope cannot reveal reviews');
select throws_ok($$select read_ezyvet_attachment_chart((select id from fx where k='pet'),now(),null,20)$$,'23514',null,'Chart requires paired cursor');
select throws_ok($$select * from ezyvet_attachment_record_versions$$,'42501',null,'Approval table is not directly readable');
reset role;
create function pg_temp.release_original(k text default 'corrected',patient uuid default null) returns jsonb language sql as $$
 select ezyvet_validate_release_attachments(coalesce($2,(select id from fx where fx.k='pet')),jsonb_build_array(jsonb_build_object('id',(select v->>'id' from data where data.k=$1),'record_hash',(select v->>'record_hash' from data where data.k=$1))));
$$;
insert into data select 'release-original',pg_temp.release_original();
select is((select v#>>'{0,capture,object_path}' from data where k='release-original'),(select v#>>'{intent,object_path}' from data where k='reserved'),'Release validation binds exact canonical original path');
select is((select v#>>'{0,record,source_context,file_id}' from data where k='release-original'),(select v#>>'{request,file_id}' from data where k='ready'),'Release retains separate canonical file identity');
select ok(not (select(v#>'{0,record,source_context}') ? 'metadata' from data where k='release-original'),'Release provenance omits raw metadata');
select throws_ok($$select pg_temp.release_original('approved')$$,'40001',null,'Superseded approval cannot enter a new release');
select throws_ok($$select pg_temp.release_original('corrected',(select id from fx where k='client'))$$,'40001',null,'Release rejects another patient');
select throws_ok($$select ezyvet_validate_release_attachments((select id from fx where k='pet'),'[]')$$,'23514',null,'Empty API original selection rejected');
select throws_ok($$select ezyvet_validate_release_attachments((select id from fx where k='pet'),jsonb_build_array(jsonb_build_object('id',(select id from fx where k='correction'),'record_hash',repeat('f',64))))$$,'40001',null,'Release refuses altered approval digest');
select throws_ok($$select ezyvet_validate_release_attachments((select id from fx where k='pet'),jsonb_build_array(jsonb_build_object('id',(select id from fx where k='correction'),'record_hash',(select v->>'record_hash' from data where k='corrected')),jsonb_build_object('id',(select id from fx where k='correction'),'record_hash',(select v->>'record_hash' from data where k='corrected'))))$$,'23514',null,'Release rejects duplicate approval identities');
select ok(not has_function_privilege('authenticated','ezyvet_validate_release_attachments(uuid,jsonb)','execute'),'Private release validation unavailable directly to staff');
select ok(not has_function_privilege('service_role','ezyvet_validate_release_attachments(uuid,jsonb)','execute'),'Worker cannot invoke release validation directly');
create function pg_temp.api_preview(selection jsonb default null,recipient text default 'attachment@example.test') returns jsonb language sql as $$
 select release_preview_v9_internal((select id from fx where k='pet'),(select id from fx where k='client'),'EMAIL',$2,coalesce($1,jsonb_build_object('api_attachment_ids',jsonb_build_array((select id from fx where k='correction')))));
$$;
insert into data select 'api-preview',pg_temp.api_preview();
select is((select v#>>'{snapshot,schema_version}' from data where k='api-preview'),'9','Preview identifies schema9');
select is((select v#>>'{snapshot,attachments,0,bucket}' from data where k='api-preview'),'ezyvet-attachment-originals','API original uses canonical private bucket');
select is((select v#>>'{snapshot,attachments,0,api_attachment_ref,record_id}' from data where k='api-preview'),(select id::text from fx where k='correction'),'Preview binds latest approval to file reference');
select is(jsonb_array_length((select v#>'{snapshot,attachments}' from data where k='api-preview')),1,'API-only preview selects exactly one original');
select is(jsonb_array_length((select v#>'{snapshot,imported_prescriptions}' from data where k='api-preview')),0,'API-only preview does not invent prescriptions');
select is((select v->>'source_hash' from data where k='api-preview'),(select encode(sha256(convert_to((v->'snapshot')::text,'UTF8')),'hex') from data where k='api-preview'),'Preview digest binds the entire reviewed snapshot');
insert into fx select 'release-weight',id from record_patient_weight((select id from fx where k='pet'),12.3,'kg',(now() at time zone 'America/Denver')::date);
insert into data select 'mixed-api-preview',pg_temp.api_preview(jsonb_build_object('api_attachment_ids',jsonb_build_array((select id from fx where k='correction')),'weight_ids',jsonb_build_array((select id from fx where k='release-weight'))));
insert into data select 'legacy-weight-preview',release_preview_v8_internal((select id from fx where k='pet'),(select id from fx where k='client'),'EMAIL','attachment@example.test',jsonb_build_object('weight_ids',jsonb_build_array((select id from fx where k='release-weight'))));
select is(jsonb_array_length((select v#>'{snapshot,weights}' from data where k='mixed-api-preview')),1,'Mixed API preview retains explicitly selected native weight');
select is((select v#>'{snapshot,weights}' from data where k='mixed-api-preview'),(select v#>'{snapshot,weights}' from data where k='legacy-weight-preview'),'Mixed preview preserves schema8 native weight representation');
select is(jsonb_array_length((select v#>'{snapshot,attachments}' from data where k='mixed-api-preview')),1,'Mixed native/API selection includes only the selected original');
select throws_ok($$select pg_temp.api_preview(null,'other@example.test')$$,'42501',null,'API-only preview retains household recipient validation');
select throws_ok($$select pg_temp.api_preview('{"api_attachment_ids":[],"unknown_ids":[]}')$$,'23514',null,'Preview rejects unknown source families');
select throws_ok($$select pg_temp.api_preview('{}')$$,'23514',null,'Empty preview does not select records implicitly');
select throws_ok($$select pg_temp.api_preview(jsonb_build_object('api_attachment_ids',(select jsonb_agg(gen_random_uuid()) from generate_series(1,21))))$$,'23514',null,'Preview caps explicit API selection at20');
select throws_ok($$select pg_temp.api_preview(jsonb_build_object('api_attachment_ids',jsonb_build_array((select id from fx where k='correction')),'imported_prescription_ids',jsonb_build_array(gen_random_uuid())))$$,'23514',null,'Mixed preview still validates canonical prescription selection');
select throws_ok($$select release_api_attachment_document(jsonb_set((select v->0 from data where k='release-original'),'{capture,file_size}','20971521'))$$,'23514',null,'Original mapper rejects oversized file');
select throws_ok($$select release_api_attachment_document(jsonb_set((select v->0 from data where k='release-original'),'{capture,bucket_id}','"patient-documents"'))$$,'23514',null,'API source cannot masquerade as a native document');
select ok(not has_function_privilege('authenticated','release_preview_v9_internal(uuid,uuid,text,text,jsonb)','execute'),'Schema9 composition remains private behind authorized wrappers');
select ok(not has_function_privilege('service_role','release_api_attachment_document(jsonb)','execute'),'Original mapper is not a direct worker entrypoint');
-- Source discovery is current-only; chart history remains complete.
set local role authenticated;
insert into data select 'api-candidates',list_record_release_sources_v9((select id from fx where k='pet'));
select is(jsonb_array_length((select v->'api_attachment_ids' from data where k='api-candidates')),1,'Release chooser offers only latest approved API original');
select is((select v#>>'{api_attachment_ids,0,id}' from data where k='api-candidates'),(select id::text from fx where k='correction'),'Chooser identifies exact correction');
select is((select v#>>'{api_attachment_ids,0,record_hash}' from data where k='api-candidates'),(select v->>'record_hash' from data where k='corrected'),'Chooser retains reviewed hash');
select is((select v#>>'{api_attachment_ids,0,file_size}' from data where k='api-candidates'),'12','Chooser supplies original size without private path');
select ok(not (select (v#>'{api_attachment_ids,0}') ?| array['source_context','object_path','file_path','bucket_id'] from data where k='api-candidates'),'Chooser omits private original context');
select is((select v->>'policy_v9_accepted' from data where k='api-candidates'),'false','Discovery does not imply clinical acceptance');
select is((select (v-'api_attachment_ids'-'policy_v9_accepted')||jsonb_build_object('has_more',(v->'has_more')-'api_attachment_ids') from data where k='api-candidates'),list_record_release_sources_v8((select id from fx where k='pet')),'Schema9 discovery preserves every canonical schema8 source and disclosure');
select is(jsonb_array_length(list_record_release_sources_v9((select id from fx where k='pet'),1)->'api_attachment_ids'),0,'Next source page excludes already paged approval');
select throws_ok($$select list_record_release_sources_v9((select id from fx where k='pet'),-1)$$,'23514',null,'Negative source offset rejected');
select throws_ok($$select list_record_release_sources_v9((select id from fx where k='pet'),null)$$,'23514',null,'Null source offset rejected');
insert into data select 'all-api-sources',select_all_record_release_sources_v9((select id from fx where k='pet'));
select is((select v#>'{selection,api_attachment_ids}' from data where k='all-api-sources'),jsonb_build_array((select id from fx where k='correction')),'Select all retains exact current API approval');
select is((select (v->'selection')-'api_attachment_ids' from data where k='all-api-sources'),select_all_record_release_sources_v8((select id from fx where k='pet'))->'selection','Select all preserves canonical schema8 family choices');
reset role;
update storage.objects set metadata=jsonb_set(metadata,'{size}','13') where name=(select v#>>'{intent,object_path}' from data where k='reserved');
set local role authenticated;
select is(jsonb_array_length(list_record_release_sources_v9((select id from fx where k='pet'))->'api_attachment_ids'),0,'Changed Storage identity is omitted from discovery');
select is(jsonb_array_length(select_all_record_release_sources_v9((select id from fx where k='pet'))#>'{selection,api_attachment_ids}'),0,'Select all cannot include unavailable original');
reset role;
update storage.objects set metadata=jsonb_set(metadata,'{size}','12') where name=(select v#>>'{intent,object_path}' from data where k='reserved');
select ok(not has_function_privilege('authenticated','ezyvet_release_attachment_current(uuid)','execute'),'Private discovery currentness helper is not an API');
select ok(not has_function_privilege('anon','list_record_release_sources_v9(uuid,integer)','execute'),'Anonymous source discovery denied');
select ok(not has_function_privilege('service_role','select_all_record_release_sources_v9(uuid)','execute'),'Worker cannot act as staff choosing all sources');
-- Public confirmation and recovery on canonical schema9; acceptance is rollback-only.
insert into fx values('api-release',gen_random_uuid());
create function pg_temp.confirm_api_release() returns jsonb language sql as $$
 select to_jsonb(confirm_record_release((select id from fx where k='api-release'),(select id from fx where k='pet'),(select id from fx where k='client'),'EMAIL','attachment@example.test',(select v#>'{snapshot,selection}' from data where k='api-preview'),(select v->'snapshot' from data where k='api-preview'),(select v->>'source_hash' from data where k='api-preview'),true));
$$;
set local role authenticated;
select is(preview_record_release_v9((select id from fx where k='pet'),(select id from fx where k='client'),'EMAIL','attachment@example.test',jsonb_build_object('api_attachment_ids',jsonb_build_array((select id from fx where k='correction')))),(select v from data where k='api-preview'),'Public preview matches exact private canonical snapshot');
select throws_ok($$select pg_temp.confirm_api_release()$$,'42501',null,'Schema9 confirmation requires clinical acceptance');
reset role;
insert into record_release_policy(id,enabled,accepted_by,accepted_at,acceptance_reference,accepted_schema_version) values(true,true,'Synthetic rollback reviewer',now(),'TEST ONLY',8);
set local role authenticated;
select throws_ok($$select pg_temp.confirm_api_release()$$,'42501',null,'Schema8 acceptance cannot enable schema9');
reset role;update record_release_policy set accepted_schema_version=9;
set local role authenticated;
insert into data select 'confirmed-api',pg_temp.confirm_api_release();
select is((select v->'snapshot' from data where k='confirmed-api'),(select v->'snapshot' from data where k='api-preview'),'Confirmation preserves exact reviewed snapshot');
select is(pg_temp.confirm_api_release(),(select v from data where k='confirmed-api'),'Exact confirmation retry returns saved receipt');
select is(read_record_release((select id from fx where k='api-release'))->>'eligible','true','Staff recovery revalidates current canonical source');
reset role;
select is((select count(*)::integer from record_release_sources where release_id=(select id from fx where k='api-release') and source_kind='api_attachment' and source_id=(select id from fx where k='correction')),1,'Confirmation registers exact API approval for invalidation');
select set_config('request.jwt.claims','{"role":"service_role"}',true);
select is(release_read_internal((select id from fx where k='api-release'))->>'eligible','true','Trusted worker composition does not require a staff JWT');
set local role service_role;
select throws_ok($$select release_read_internal((select id from fx where k='api-release'))$$,'42501',null,'Service API cannot call private recovery directly');
select throws_ok($$select preview_record_release_v9((select id from fx where k='pet'),(select id from fx where k='client'),'EMAIL','attachment@example.test','{}')$$,'42501',null,'Service API cannot bypass staff preview authorization');
reset role;
select set_config('request.jwt.claims','{"sub":"db700000-0000-4000-8000-000000000001","role":"authenticated"}',true);
-- Synthetic byte-contract fixture derived from the canonical preview shape.
insert into data select 'byte-source',jsonb_set(jsonb_set(v#>'{snapshot,api_attachments,0}','{capture,content_sha256}',to_jsonb(encode(sha256(convert_to('%PDF-example','UTF8')),'hex'))),'{capture,file_size}',to_jsonb(octet_length(convert_to('%PDF-example','UTF8')))) from data where k='api-preview';
insert into data select 'byte-document',release_api_attachment_document(v) from data where k='byte-source';
insert into data select 'byte-snapshot',jsonb_set(jsonb_set(v->'snapshot','{api_attachments}',jsonb_build_array((select v from data where k='byte-source'))),'{attachments}',jsonb_build_array((select v from data where k='byte-document'))) from data where k='api-preview';
select lives_ok($$select verify_release_source_original_v5((select v from data where k='byte-snapshot'),(select v from data where k='byte-document'),convert_to('%PDF-example','UTF8'))$$,'Exact schema9 API package bytes verify');
select throws_ok($$select verify_release_source_original_v5((select v from data where k='byte-snapshot'),(select v from data where k='byte-document'),convert_to('%PDF-examplf','UTF8'))$$,'23514',null,'Same-size byte substitution rejected');
select throws_ok($$select verify_release_source_original_v5((select v from data where k='byte-snapshot'),(select v from data where k='byte-document'),null)$$,'23514',null,'Null original bytes rejected');
select throws_ok($$select verify_release_source_original_v5(jsonb_set((select v from data where k='byte-snapshot'),'{attachments}','[]'),(select v from data where k='byte-document'),convert_to('%PDF-example','UTF8'))$$,'23514',null,'Missing API original descriptor rejected');
select throws_ok($$select verify_release_source_original_v5(jsonb_set((select v from data where k='byte-snapshot'),'{attachments}',jsonb_build_array((select v from data where k='byte-document'),(select v from data where k='byte-document'))),(select v from data where k='byte-document'),convert_to('%PDF-example','UTF8'))$$,'23514',null,'Duplicate API original descriptors rejected');
select throws_ok($$select verify_release_source_original_v5(jsonb_set((select v from data where k='byte-snapshot'),'{selection,api_attachment_ids}','[]'),(select v from data where k='byte-document'),convert_to('%PDF-example','UTF8'))$$,'23514',null,'Unselected API approval rejected');
select throws_ok($$select verify_release_source_original_v5(jsonb_set((select v from data where k='byte-snapshot'),'{patient,id}',to_jsonb((select id from fx where k='client'))),(select v from data where k='byte-document'),convert_to('%PDF-example','UTF8'))$$,'23514',null,'Cross-patient package rejected');
select throws_ok($$select verify_release_source_original_v5((select v from data where k='byte-snapshot'),jsonb_set((select v from data where k='byte-document'),'{bucket}','"patient-documents"'),convert_to('%PDF-example','UTF8'))$$,'23514',null,'API original cannot be substituted as ordinary document');
insert into data select 'native-byte-ref',jsonb_build_object('family','lab_report','version_id',(select id from fx where k='run'),'receipt_id',(select id from fx where k='run2'),'receipt_hash',repeat('a',64),'capture_hash',repeat('b',64));
insert into data select 'native-byte-document',jsonb_build_object('id',(select id from fx where k='capture2'),'version',1,'bucket','patient-documents','file_path','synthetic/native.pdf','mime_type','application/pdf','file_size',octet_length(convert_to('%PDF-native','UTF8')),'content_sha256',encode(sha256(convert_to('%PDF-native','UTF8')),'hex'),'provenance_captures',jsonb_build_array((select v from data where k='native-byte-ref')));
insert into data select 'native-byte-source',jsonb_build_object('id',(select id from fx where k='run'),'document_id',v->'id','document_version',v->'version','mime_type',v->'mime_type','file_size',v->'file_size','content_sha256',v->'content_sha256','receipt_id',(select id from fx where k='run2'),'receipt_hash',repeat('a',64),'capture_hash',repeat('b',64)) from data where k='native-byte-document';
insert into data select 'mixed-byte-snapshot',jsonb_set(jsonb_set(v,'{attachments}',(v->'attachments')||jsonb_build_array((select v from data where k='native-byte-document'))),'{lab_reports}',jsonb_build_array((select v from data where k='native-byte-source'))) from data where k='byte-snapshot';
select lives_ok($$select verify_release_source_original_v5((select v from data where k='mixed-byte-snapshot'),(select v from data where k='native-byte-document'),convert_to('%PDF-native','UTF8'))$$,'Schema9 preserves valid native captured-source byte verification');
select throws_ok($$select verify_release_source_original_v5((select v from data where k='mixed-byte-snapshot'),(select v from data where k='native-byte-document'),convert_to('%PDF-nativf','UTF8'))$$,'23514',null,'Schema9 preserves native captured-source tamper rejection');
select lives_ok($$select verify_release_source_original_v5((select v from data where k='mixed-byte-snapshot'),(select v from data where k='byte-document'),convert_to('%PDF-example','UTF8'))$$,'Mixed native/API package retains API byte verification');
select ok(not has_function_privilege('authenticated','verify_release_source_original_legacy(jsonb,jsonb,bytea)','execute'),'Legacy byte helper remains private');
select ok(not has_function_privilege('service_role','verify_release_source_original_v5(jsonb,jsonb,bytea)','execute'),'Worker cannot bypass package operation authorization');
select throws_ok($$update ezyvet_attachment_record_versions set title='changed'$$,'23514',null,'Privileged approval rewrites are rejected');
select ok(not has_function_privilege('anon','approve_ezyvet_attachment_record(uuid,uuid,uuid,text,uuid,text,text,boolean)','execute'),'Anonymous approval denied');
select ok(not has_function_privilege('service_role','approve_ezyvet_attachment_record(uuid,uuid,uuid,text,uuid,text,text,boolean)','execute'),'Worker cannot approve');
update ezyvet_identity_heads set version=version+1 where resource='animal' and external_id='77';
select ok(exists(select 1 from record_release_events where release_id=(select id from fx where k='api-release') and kind='source_changed'),'Canonical Animal head change appends release invalidation');
select is(read_record_release((select id from fx where k='api-release'))->>'eligible','false','Changed source makes saved release ineligible');
select is(pg_temp.confirm_api_release(),(select v from data where k='confirmed-api'),'Exact saved receipt remains recoverable after source invalidation');
select is(jsonb_array_length(list_record_release_sources_v9((select id from fx where k='pet'))->'api_attachment_ids'),0,'Stale source disappears from release chooser while chart history survives');


select throws_ok($$select pg_temp.release_original()$$,'40001',null,'Source change prevents a new release of retained original');
set local role authenticated;
select is(read_ezyvet_attachment_chart((select id from fx where k='pet'))#>>'{records,0,source_current}','false','Latest review remains visible but stale after source changes');
select is(recover_ezyvet_attachment_capture((select id from fx where k='capture'),(select id from fx where k='mapping'))->>'status','ready','Ready historical capture recovers after parent changes');
select is(to_jsonb(pg_temp.approve_original()),(select v from data where k='approved'),'Exact approval recovery survives later source changes');
select is(cancel_ezyvet_attachment_approval((select id from fx where k='approval'),(select id from fx where k='capture'),(select id from fx where k='pet'),(select v#>>'{request,capture,capture_hash}' from data where k='ready'),true)->>'status','approved','Cancellation cannot erase committed approval');
insert into fx select 'cancel-approval',gen_random_uuid();
create function pg_temp.cancel_original(attest boolean default true) returns jsonb language sql as $$select cancel_ezyvet_attachment_approval((select id from fx where k='cancel-approval'),(select id from fx where k='capture'),(select id from fx where k='pet'),(select v#>>'{request,capture,capture_hash}' from data where k='ready'),$1);$$;
select throws_ok($$select pg_temp.cancel_original(false)$$,'23514',null,'Cancellation requires explicit confirmation');
insert into data select 'canceled-approval',pg_temp.cancel_original();
select is((select v->>'status' from data where k='canceled-approval'),'canceled','Cancellation remains available for a historical capture');
select is(pg_temp.cancel_original(),(select v from data where k='canceled-approval'),'Exact canceled outcome recovers');
select is(recover_ezyvet_attachment_approval((select id from fx where k='cancel-approval'),(select id from fx where k='capture'),(select id from fx where k='pet'),(select v#>>'{request,capture,capture_hash}' from data where k='ready')),(select v from data where k='canceled-approval'),'Recovery returns immutable cancellation');
select throws_ok($$select pg_temp.approve_original('cancel-approval',(select id from fx where k='correction'))$$,'23514','Approval was canceled; use an explicitly new decision','Late approval cannot revive cancellation');
select throws_ok($$select * from ezyvet_attachment_approval_cancellations$$,'42501',null,'Cancellation ledger stays private');
select ok(not has_function_privilege('authenticated','approve_ezyvet_attachment_record_uncancelled(uuid,uuid,uuid,text,uuid,text,text,boolean)','execute'),'Staff cannot bypass cancellation wrapper');
select ok(not has_function_privilege('service_role','approve_ezyvet_attachment_record_uncancelled(uuid,uuid,uuid,text,uuid,text,text,boolean)','execute'),'Worker cannot bypass cancellation wrapper');

insert into data select 'review-page',list_ezyvet_attachment_record_versions((select id from fx where k='capture'),(select id from fx where k='pet'),null,null,1);
select is((select v#>>'{records,0,id}' from data where k='review-page'),(select id::text from fx where k='correction'),'History starts with latest correction');
select is((select v->>'latest_record_id' from data where k='review-page'),(select id::text from fx where k='correction'),'Latest review identified independently of page');
select is((select v->>'has_more' from data where k='review-page'),'true','Review history bounds page size');
select ok(not (select (v#>'{records,0}') ? 'source_context' from data where k='review-page'),'History omits private source context');
insert into data select 'review-older',list_ezyvet_attachment_record_versions((select id from fx where k='capture'),(select id from fx where k='pet'),(select (v#>>'{next_cursor,before_at}')::timestamptz from data where k='review-page'),(select (v#>>'{next_cursor,before_id}')::uuid from data where k='review-page'),1);
select is((select v#>>'{records,0,version}' from data where k='review-older'),'1','Cursor reaches earlier review without repeating latest');
select is((select v->>'has_more' from data where k='review-older'),'false','History terminates at earliest review');
select throws_ok($$select list_ezyvet_attachment_record_versions((select id from fx where k='capture'),(select id from fx where k='pet'),now(),null,20)$$,'23514',null,'History rejects partial cursor');
select throws_ok($$select list_ezyvet_attachment_record_versions((select id from fx where k='capture'),(select id from fx where k='client'))$$,'42501',null,'History rejects another patient');

select throws_ok($$select pg_temp.approve_original('capture3',(select id from fx where k='correction'))$$,'40001',null,'Fresh approval rejects changed parent source');
select is(recover_ezyvet_attachment_capture((select id from fx where k='capture'),(select id from fx where k='mapping'))->>'source_current','false','Historical capture honestly reports stale source');
select is(prepare_ezyvet_attachment_capture((select id from fx where k='capture'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,1,(select id from fx where k='attachment-snapshot'),1,repeat('b',64))->>'status','ready','Exact prepare replay remains available historically');
select throws_ok($$select prepare_ezyvet_attachment_capture((select id from fx where k='capture2'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,1,(select id from fx where k='attachment-snapshot'),1,repeat('b',64))$$,'40001',null,'Fresh request rejects stale parent');
reset role;
update ezyvet_identity_heads set version=version-1 where resource='animal' and external_id='77';
set local role authenticated;
insert into data select 'capture2',prepare_ezyvet_attachment_capture((select id from fx where k='capture2'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,2,(select id from fx where k='attachment-snapshot'),1,repeat('b',64));
reset role;set local role service_role;
insert into data select 'claimed2',claim_ezyvet_attachment_capture((select id from fx where k='capture2'),'db700000-0000-4000-8000-000000000001');
insert into data select 'reserved2',reserve_ezyvet_attachment_original((select id from fx where k='capture2'),'db700000-0000-4000-8000-000000000001',(select(v->>'lease_id')::uuid from data where k='claimed2'),repeat('e',64),'application/pdf',12,repeat('a',64),repeat('c',64));
reset role;
insert into storage.objects(bucket_id,name,metadata) select 'ezyvet-attachment-originals',v#>>'{intent,object_path}','{"size":12,"mimetype":"application/pdf"}'::jsonb from data where k='reserved2';
set local role service_role;
select is(begin_discard_ezyvet_attachment_capture((select id from fx where k='capture2'),'db700000-0000-4000-8000-000000000001')#>>'{request,status}','discarding','Discard fences an active worker');
select throws_ok($$select complete_ezyvet_attachment_capture((select id from fx where k='capture2'),'db700000-0000-4000-8000-000000000001',(select(v->>'lease_id')::uuid from data where k='claimed2'),(select(v#>>'{intent,id}')::uuid from data where k='reserved2'),repeat('e',64),'application/pdf',12)$$,'40001',null,'Fenced worker cannot finalize');
select throws_ok($$select complete_discard_ezyvet_attachment_capture((select id from fx where k='capture2'),'db700000-0000-4000-8000-000000000001')$$,'23514',null,'Discard must verify private object absence');
reset role;set local storage.allow_delete_query='true';delete from storage.objects where name=(select v#>>'{intent,object_path}' from data where k='reserved2');
set local role authenticated;
select throws_ok($$insert into storage.objects(bucket_id,name,metadata) select 'ezyvet-attachment-originals',v#>>'{intent,object_path}','{"size":12,"mimetype":"application/pdf"}'::jsonb from data where k='reserved2'$$,'42501',null,'Late upload cannot cross discard fence');
reset role;set local role service_role;
select is(complete_discard_ezyvet_attachment_capture((select id from fx where k='capture2'),'db700000-0000-4000-8000-000000000001')#>>'{request,status}','abandoned','Absent pending object finalizes discard');
select is(begin_discard_ezyvet_attachment_capture((select id from fx where k='capture2'),'db700000-0000-4000-8000-000000000001')#>>'{request,status}','abandoned','Lost discard reply recovers tombstone');
select throws_ok($$select claim_ezyvet_attachment_capture((select id from fx where k='capture2'),'db700000-0000-4000-8000-000000000001')$$,'23514',null,'Abandoned request cannot revive');
reset role;
select throws_ok($$update ezyvet_attachment_capture_requests set status='prepared' where id=(select id from fx where k='capture2')$$,'23514',null,'Privileged mutation cannot bypass discard state guard');
select throws_ok($$update ezyvet_attachment_original_captures set content_sha256=repeat('f',64)$$,'23514',null,'Capture receipt immutable');
select ok(not has_table_privilege('authenticated','ezyvet_attachment_capture_requests','select'),'No direct capture-request read grant');
select ok(not has_table_privilege('service_role','ezyvet_attachment_original_intents','insert'),'Service cannot forge intent rows directly');
select ok(not has_function_privilege('authenticated','get_ezyvet_attachment_capture_context(uuid,uuid)','execute'),'Private path/lease context denied to browser');
select ok(not has_function_privilege('service_role','ezyvet_attachment_capture_private(uuid)','execute'),'Raw private projection helper revoked');
select ok(not exists(select 1 from patient_documents),'API capture creates no patient document');
select ok(not exists(select 1 from external_record_receipts),'API capture creates no manual-export receipt');
select is((select count(*)::integer from ezyvet_attachment_page_observations),2,'Metadata observation count unchanged by capture');
set local role authenticated;
select is(jsonb_array_length(list_ezyvet_attachment_capture_mappings()->'mappings'),1,'Historical mappings are grouped for their owner');
select is(list_ezyvet_attachment_capture_mappings()#>>'{mappings,0,household_name}','Attachment Owner','Historical mapping keeps original household');
select throws_ok($$select list_ezyvet_attachment_capture_mappings(now(),null,20)$$,'23514',null,'Mapping cursor must be complete');
insert into fx select 'moved-client',id from save_client(auth.uid(),null,null,'Different','Household','+13035550197','other-household@example.test','EMAIL',null,null);
reset role;
-- Owner-only synthetic future household-transfer fixture.
alter table pets disable trigger pets_version;
update pets set client_id=(select id from fx where k='moved-client') where id=(select id from fx where k='pet');
set local role authenticated;
select is(list_ezyvet_attachment_capture_mappings()#>>'{mappings,0,household_name}','Attachment Owner','Moved patient remains discoverable under original capture household');
select is(abandon_ezyvet_attachment_capture_preparation((select id from fx where k='capture3'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,1,(select id from fx where k='attachment-snapshot'),1,repeat('b',64))->>'status','abandoned','Uncreated scoped preparation becomes abandoned');
reset role;
update pets set client_id=(select id from fx where k='client') where id=(select id from fx where k='pet');
alter table pets enable trigger pets_version;
set local role authenticated;
select is(prepare_ezyvet_attachment_capture((select id from fx where k='capture3'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,1,(select id from fx where k='attachment-snapshot'),1,repeat('b',64))->>'status','abandoned','Delayed prepare recovers abandoned tombstone');
select is(abandon_ezyvet_attachment_capture_preparation((select id from fx where k='capture'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,1,(select id from fx where k='attachment-snapshot'),1,repeat('b',64))->>'status','ready','Abandon preparation cannot alter an existing ready request');
select throws_ok($$select abandon_ezyvet_attachment_capture_preparation((select id from fx where k='capture3'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,2,(select id from fx where k='attachment-snapshot'),1,repeat('b',64))$$,'42501',null,'Preparation tombstone cannot change observation ordinal');
select set_config('request.jwt.claims','{"sub":"db700000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select throws_ok($$select list_ezyvet_attachment_record_versions((select id from fx where k='capture'),(select id from fx where k='pet'))$$,'42501',null,'Another administrator cannot list owned review history');
select is(jsonb_array_length(list_ezyvet_attachment_capture_mappings()->'mappings'),0,'Another administrator cannot discover historical mappings');
select throws_ok($$select abandon_ezyvet_attachment_capture_preparation((select id from fx where k='capture3'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,1,(select id from fx where k='attachment-snapshot'),1,repeat('b',64))$$,'42501',null,'Another administrator cannot recover preparation tombstone');
reset role;
select ok(not has_function_privilege('authenticated','ezyvet_attachment_capture_prepare_core(uuid,uuid,uuid,integer,integer,uuid,integer,text,boolean)','execute'),'Preparation core remains private');
select ok(not has_function_privilege('anon','read_ezyvet_attachment_chart(uuid,timestamptz,uuid,integer)','execute'),'Anonymous chart access denied');
update profiles set is_active=false where id='db700000-0000-4000-8000-000000000002';
set local role authenticated;
select throws_ok($$select read_ezyvet_attachment_chart((select id from fx where k='pet'))$$,'42501','Active staff access required','Deactivated staff cannot read reviewed chart');
reset role;
select set_config('request.jwt.claims','{"sub":"db700000-0000-4000-8000-000000000001","role":"authenticated"}',true);
update profiles set is_active=true where id='db700000-0000-4000-8000-000000000002';
delete from user_roles where user_id='db700000-0000-4000-8000-000000000002' and role='ADMIN';
insert into user_roles(user_id,role) values('db700000-0000-4000-8000-000000000002','STAFF') on conflict do nothing;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"db700000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select is(jsonb_array_length(read_ezyvet_attachment_chart((select id from fx where k='pet'))->'records'),2,'Active non-owner staff can read explicitly reviewed history');
reset role;
select ok(not has_function_privilege('authenticated','get_reviewed_ezyvet_original_context(uuid,uuid,uuid,text)','execute'),'Private reviewed original context denied to browser');
select ok(not has_function_privilege('anon','get_reviewed_ezyvet_original_context(uuid,uuid,uuid,text)','execute'),'Private reviewed original context denied to anonymous');
set local role service_role;
insert into data select 'chart-original-context',get_reviewed_ezyvet_original_context('db700000-0000-4000-8000-000000000002',(select id from fx where k='approval'),(select id from fx where k='pet'),(select v->>'capture_hash' from data where k='approved'));
select is((select v->>'record_id' from data where k='chart-original-context'),(select id::text from fx where k='approval'),'Non-owner staff may retrieve earlier approved original');
select is((select v->>'object_path' from data where k='chart-original-context'),(select v#>>'{intent,object_path}' from data where k='reserved'),'Reviewed original resolves exact reserved private path');
select throws_ok($$select get_reviewed_ezyvet_original_context('db700000-0000-4000-8000-000000000002',(select id from fx where k='approval'),(select id from fx where k='client'),(select v->>'capture_hash' from data where k='approved'))$$,'42501',null,'Reviewed original rejects another patient');
select throws_ok($$select get_reviewed_ezyvet_original_context('db700000-0000-4000-8000-000000000002',(select id from fx where k='approval'),(select id from fx where k='pet'),repeat('f',64))$$,'42501',null,'Reviewed original rejects another capture hash');
select throws_ok($$select get_reviewed_ezyvet_original_context('db700000-0000-4000-8000-000000000002',(select id from fx where k='capture'),(select id from fx where k='pet'),(select v->>'capture_hash' from data where k='approved'))$$,'42501',null,'Unapproved identity cannot retrieve an original');
reset role;
select set_config('request.jwt.claims','{"sub":"db700000-0000-4000-8000-000000000001","role":"authenticated"}',true);
update profiles set is_active=false where id='db700000-0000-4000-8000-000000000002';
set local role service_role;
select throws_ok($$select get_reviewed_ezyvet_original_context('db700000-0000-4000-8000-000000000002',(select id from fx where k='approval'),(select id from fx where k='pet'),(select v->>'capture_hash' from data where k='approved'))$$,'42501','Active staff access required','Private original context rejects deactivated reader');
reset role;
select * from finish();rollback;
