begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select no_plan();
-- FIXTURE_BEGIN: synthetic scoped outside history and local actors.
insert into auth.users(id,email,raw_user_meta_data) values('db490000-0000-4000-8000-000000000001','clinical-import-admin@example.test','{}'),('db490000-0000-4000-8000-000000000002','clinical-import-other@example.test','{}');
insert into user_roles(user_id,role) values('db490000-0000-4000-8000-000000000001','ADMIN'),('db490000-0000-4000-8000-000000000002','DVM');
create temp table fx(k text primary key,id uuid);create temp table data(k text primary key,v jsonb);grant all on fx,data to authenticated,service_role;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db490000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'client',id from save_client(auth.uid(),null,null,'Clinical','Import','+13035550199','clinical-import@example.test','EMAIL',null,null);
insert into fx select 'pet',id from save_patient(null,(select id from fx where k='client'),null,'Scoped dog','Dog',null,null,'unknown',null,'unknown','unknown',null,null,null);
insert into fx select k,gen_random_uuid() from unnest(array['mapping','mapping2','snapshot','snapshot2','legacy','terminal','run','history','other-run']) k;
reset role;
insert into ezyvet_import_snapshots(id,source_origin,source_site_uid,resource,external_id,payload,payload_hash,first_seen_by) select id,'https://api.trial.ezyvet.com','clinical-test-site','animal',case when k='snapshot' then '77' else '88' end,jsonb_build_object('id',case when k='snapshot' then 77 else 88 end),k,'db490000-0000-4000-8000-000000000001' from fx where k in ('snapshot','snapshot2');
insert into ezyvet_record_links(id,request_id,request_hash,source_origin,source_site_uid,resource,external_id,snapshot_id,head_version,client_id,pet_id,local_version,action,reason,approved_by)
select id,gen_random_uuid(),k,'https://api.trial.ezyvet.com','clinical-test-site','animal',case when k='mapping' then '77' else '88' end,(select id from fx where k=case when m.k='mapping' then 'snapshot' else 'snapshot2' end),1,(select id from fx where k='client'),(select id from fx where k='pet'),1,'link','Synthetic approved mapping','db490000-0000-4000-8000-000000000001' from fx m where k in ('mapping','mapping2');
insert into data values('items','[{"external_id":"101","payload":{"id":101,"animal_id":77,"comments":"<script>outside prose</script>","vet_id":"outside-user","history_system":"opaque"}}]');
insert into fx select k,gen_random_uuid() from unnest(array['source-approval','extraction','linked','tombstone','second-extraction','later-source','discrepancy','release']) k;
set local role service_role;
insert into data select 'run',claim_ezyvet_clinical_import((select id from fx where k='run'),'db490000-0000-4000-8000-000000000001','clinical-test-site','history','https://api.trial.ezyvet.com',(select id from fx where k='mapping'));
select stage_ezyvet_import_page((select id from fx where k='run'),'db490000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='run'),1,true,(select v from data where k='items'));
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db490000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into data select 'candidate',list_ezyvet_clinical_candidates((select id from fx where k='mapping'),'history')#>'{candidates,0}';
insert into data select 'source-payload',jsonb_build_object('animal_link_id',(select id from fx where k='mapping'),'snapshot_id',v->'id','payload_hash',v->'payload_hash','observed_head_version',v->'head_version','patient_version',1,'consult_mode','not_referenced','consult_snapshot_id',null,'consult_payload_hash',null,'consult_head_version',null,'reason','PRIVATE administrator source review') from data where k='candidate';
insert into data select 'prepared-source',prepare_ezyvet_history_approval((select id from fx where k='source-approval'),(select id from fx where k='pet'),(select v from data where k='source-payload'));
insert into data select 'source-receipt',approve_ezyvet_history((select id from fx where k='source-approval'),(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='prepared-source'),true);
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db490000-0000-4000-8000-000000000002","role":"authenticated"}',true);
insert into data select 'extraction-payload',jsonb_build_object('sources',jsonb_build_array(jsonb_build_object('id',v#>'{receipt,id}','version_hash',v#>'{receipt,version_hash}')),'patient_version',1,'action','create','problem_id',null,'problem_version',null,'fields',jsonb_build_object('title','Reviewed vaccine reaction','notes','DVM-authored reviewed finding','onset_date',null,'status','active','importance','high'),'duplicate_decision','distinct_finding','reason','PRIVATE DVM duplicate review') from data where k='source-receipt';
insert into data select 'prepared-extraction',prepare_ezyvet_problem_extraction((select id from fx where k='extraction'),(select id from fx where k='pet'),(select v from data where k='extraction-payload'));
insert into data select 'extraction-receipt',approve_ezyvet_problem_extraction((select id from fx where k='extraction'),(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='prepared-extraction'),true);
insert into fx select 'problem',(v#>>'{receipt,problem_id}')::uuid from data where k='extraction-receipt';

reset role;
insert into ezyvet_identity_heads(source_origin,source_site_uid,resource,external_id,snapshot_id,version)
select source_origin,source_site_uid,resource,external_id,id,1 from ezyvet_import_snapshots where id=(select id from fx where k='snapshot');
insert into fx select k,gen_random_uuid() from unnest(array['migration','scope','binding','approval2']) k;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db490000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select prepare_ezyvet_migration_run((select id from fx where k='migration'),'https://api.trial.ezyvet.com','clinical-test-site',jsonb_build_array(jsonb_build_object('id',(select id from fx where k='scope'),'mapping_id',(select id from fx where k='mapping'),'resource','history','parent_type','animal','parent_snapshot_id',(select id from fx where k='snapshot'),'parent_head_version',1,'disposition','required','reason','Synthetic history coverage')));
select bind_ezyvet_migration_child((select id from fx where k='binding'),(select id from fx where k='scope'),(select id from fx where k='run'),'Synthetic history run');
insert into data select 'item',list_ezyvet_migration_items((select id from fx where k='binding'))#>'{items,0}';
create function pg_temp.receipts(bef integer default null,lim integer default 20) returns jsonb language sql as $$
select list_ezyvet_migration_history_evidence((select id from fx where k='binding'),1,(v->>'snapshot_id')::uuid,v->>'evidence_hash',bef,lim) from data where k='item';$$;
insert into data select 'first',pg_temp.receipts();
select is((select v#>>'{approvals,0,relationship}' from data where k='first'),'exact_source_version','Approval matches server-verified source evidence hash');
select is((select v#>>'{approvals,0,source_current}' from data where k='first'),'true','Initial reviewed source context is current');
select is((select v#>>'{approvals,0,extraction_receipts}' from data where k='first'),'1','DVM extraction by different actor is visible without exposing pending requests');
select is((select v#>>'{approvals,0,locally_edited_receipts}' from data where k='first'),'0','Unedited local finding is separate from source approval');
select ok(not (select v::text from data where k='first') ~ 'PRIVATE|outside prose|problem_fields|request_hash','Projection omits prose, reasons and request payloads');
select is(pg_temp.receipts()->>'complete_coverage_verified','false','Review receipts never imply accepted coverage');
select is(pg_temp.receipts()->>'discrepancies_assessed','false','Discrepancy assessment remains explicit');
select throws_ok($$select list_ezyvet_migration_history_evidence((select id from fx where k='binding'),1,(v->>'snapshot_id')::uuid,repeat('a',64)) from data where k='item'$$,'42501','Exact owned history observation required','Substituted hash denied');
select throws_ok($$select list_ezyvet_migration_history_evidence((select id from fx where k='binding'),2,(v->>'snapshot_id')::uuid,v->>'evidence_hash') from data where k='item'$$,'42501','Exact owned history observation required','Substituted page denied');
select throws_ok($$select pg_temp.receipts(null,101)$$,'23514','Invalid history evidence identity or cursor','Unbounded page denied');
insert into data select 'prepared2',prepare_ezyvet_history_approval((select id from fx where k='approval2'),(select id from fx where k='pet'),(select v from data where k='source-payload'));
select approve_ezyvet_history((select id from fx where k='approval2'),(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='prepared2'),true);
select is(pg_temp.receipts(null,1)#>>'{approvals,0,version}','2','Latest correction appears first');
select is(pg_temp.receipts(null,1)->>'has_more','true','Sentinel provides bounded version history');
select is(pg_temp.receipts(null,1)->>'next_before_version','2','Cursor is last selected version');
select is(pg_temp.receipts(2,1)#>>'{approvals,0,superseded}','true','Prior approval remains visible as superseded');
select is(pg_temp.receipts(2,1)->>'has_more','false','Last page is terminal');
reset role;
insert into fx select k,gen_random_uuid() from unnest(array['changed-run','approval3']) k;
update ezyvet_import_runs set retry_after=null where source_site_uid='clinical-test-site' and resource='history';
insert into data select 'changed-run',claim_ezyvet_clinical_import((select id from fx where k='changed-run'),'db490000-0000-4000-8000-000000000001','clinical-test-site','history','https://api.trial.ezyvet.com',(select id from fx where k='mapping'));
select stage_ezyvet_import_page((select id from fx where k='changed-run'),'db490000-0000-4000-8000-000000000001',(select(v->>'lease_id')::uuid from data where k='changed-run'),1,true,'[{"external_id":"101","payload":{"id":101,"animal_id":77,"comments":"Changed source prose"}}]');
set local role authenticated;
insert into data select 'changed-payload',old.v||jsonb_build_object('snapshot_id',c->'id','payload_hash',c->'payload_hash','observed_head_version',c->'head_version') from data old cross join lateral (select c from jsonb_array_elements(list_ezyvet_clinical_candidates((select id from fx where k='mapping'),'history')->'candidates') c where c->>'external_id'='101' and c->>'is_current'='true') candidate where old.k='source-payload';
insert into data select 'prepared3',prepare_ezyvet_history_approval((select id from fx where k='approval3'),(select id from fx where k='pet'),(select v from data where k='changed-payload'));
select approve_ezyvet_history((select id from fx where k='approval3'),(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='prepared3'),true);
select is(pg_temp.receipts()#>>'{approvals,0,relationship}','different_source_version','New source approval remains distinguishable from bound observation');
select is(pg_temp.receipts()#>>'{approvals,0,source_current}','true','Approval on changed source is independently current');
select is(pg_temp.receipts()#>>'{approvals,0,extraction_receipts}','0','Old extraction is not credited to a new approved version');
reset role;
-- Restore the original payload at a newer head to model A to B to A.
update ezyvet_identity_heads set snapshot_id=(select(v->>'snapshot_id')::uuid from data where k='item') where resource='history' and source_site_uid='clinical-test-site';
update patient_problems set version=version+1,notes='Later local clinician edit' where id=(select id from fx where k='problem');
update ezyvet_identity_heads set version=version+2 where resource='history' and source_site_uid='clinical-test-site';
set local role authenticated;
select is(pg_temp.receipts(2,1)#>>'{approvals,0,locally_edited_receipts}','1','Local edit is retained and reported');
select is(pg_temp.receipts(2,1)#>>'{approvals,0,source_current}','false','A to B to A invalidates currentness despite same payload');
select is(pg_temp.receipts(2,1)#>>'{approvals,0,relationship}','exact_source_version','Source drift does not rewrite the old observation receipt');
select is((select notes from patient_problems where id=(select id from fx where k='problem')),'Later local clinician edit','Evidence reads preserve local chart fields');
select set_config('request.jwt.claims','{"sub":"db490000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select throws_ok($$select pg_temp.receipts()$$,'42501','Active administrator required','DVM-only actor cannot read migration receipts');
reset role;insert into user_roles(user_id,role) values('db490000-0000-4000-8000-000000000002','ADMIN');set local role authenticated;
select throws_ok($$select pg_temp.receipts()$$,'42501','Exact owned history observation required','Different administrator cannot read owned observation');
reset role;
update profiles set is_active=false where id='db490000-0000-4000-8000-000000000001';
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db490000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select throws_ok($$select pg_temp.receipts()$$,'42501','Active administrator required','Inactive owner denied');
reset role;
select ok(not has_function_privilege('anon','public.list_ezyvet_migration_history_evidence(uuid,integer,uuid,text,integer,integer)','execute'),'Anonymous read denied');
select ok(not has_function_privilege('service_role','public.list_ezyvet_migration_history_evidence(uuid,integer,uuid,text,integer,integer)','execute'),'Worker read denied');

reset role;select set_config('request.jwt.claims','{"sub":"db490000-0000-4000-8000-000000000002","role":"authenticated"}',true);
update profiles set is_active=true where id='db490000-0000-4000-8000-000000000001';
select set_config('request.jwt.claims','{"sub":"db490000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select is((select count(distinct native_id) from ezyvet_migration_terminal_native_outcomes((select id from fx where k='migration')) where native_kind='problem'),1::bigint,'Historical extraction produces one distinct native problem');
select ok(exists(select 1 from ezyvet_migration_terminal_native_outcomes((select id from fx where k='migration')) where native_id=(select id from fx where k='problem') and provenance_id=(select id from fx where k='extraction') and local_changed),'Native problem retains exact extraction provenance and later edits');
select ok(not has_function_privilege('authenticated','public.ezyvet_migration_terminal_native_outcomes(uuid)','execute'),'Native outcome projection is not publicly exposed');
select is(ezyvet_migration_outcome_totals((select id from fx where k='migration'))#>>'{native_outcomes,problem,records}','1','Summary counts distinct native problems');
select is(ezyvet_migration_outcome_totals((select id from fx where k='migration'))#>>'{native_outcomes,problem,locally_changed_records}','1','Summary retains later local edits');
select is(ezyvet_migration_outcome_totals((select id from fx where k='migration'))#>>'{receipts,imported_history,versions}','3','Summary retains immutable history approval versions');
select is(ezyvet_migration_outcome_totals((select id from fx where k='migration'))->>'standalone_consult_approval','not_applicable','No standalone consult approval fabricated');
select is(ezyvet_migration_outcome_totals(gen_random_uuid()),null::jsonb,'Unknown manifest does not become empty success');
select ok(not has_function_privilege('authenticated','public.ezyvet_migration_outcome_totals(uuid)','execute'),'Outcome aggregation stays private before complete summary acceptance');
insert into fx values('preparation',gen_random_uuid());
select prepare_ezyvet_migration_projection((select id from fx where k='preparation'),(select id from fx where k='migration'));
select is(read_ezyvet_migration_dependency_state((select id from fx where k='preparation'))->>'dependencies_unchanged','true','Preparation excludes earlier own-transaction dependency writes');
select is(read_ezyvet_migration_dependency_state((select id from fx where k='preparation'))->>'journal_coverage_valid','true','Installed journal inventory is intact');
savepoint disabled_journal;
alter table patient_problems disable trigger migration_dependency_change;
select is(read_ezyvet_migration_dependency_state((select id from fx where k='preparation'))->>'dependencies_unchanged','false','Disabled trigger cannot imply unchanged dependencies');
select is(read_ezyvet_migration_dependency_state((select id from fx where k='preparation'))->'uncovered_tables','["patient_problems"]'::jsonb,'Missing coverage identifies table');
select throws_ok($$select assert_ezyvet_migration_dependencies((select id from fx where k='preparation'))$$,'55000','Dependency journal coverage incomplete','Coverage failure has repair-specific error');
rollback to savepoint disabled_journal;
savepoint new_dependency;
create table public.ezyvet_future_dependency(id uuid primary key);
select is(read_ezyvet_migration_dependency_state((select id from fx where k='preparation'))->>'journal_coverage_valid','false','New operational table requires journal registration');
select throws_ok($$select prepare_ezyvet_migration_source_chunk((select id from fx where k='preparation'),(select id from fx where k='binding'),1)$$,'55000','Dependency journal coverage incomplete','Uncovered table blocks new source capture');
rollback to savepoint new_dependency;
select is(read_ezyvet_migration_dependency_state((select id from fx where k='preparation'))->>'dependencies_unchanged','true','Rolling back schema test restores intact baseline');
select is(read_ezyvet_migration_report_progress((select id from fx where k='preparation'))->>'missing_source_chunks','1','Report progress begins with missing planned source chunk');
insert into fx values('attempt-page',gen_random_uuid());
insert into data select 'attempt-page',prepare_ezyvet_migration_attempt_page((select id from fx where k='attempt-page'),(select id from fx where k='preparation'),(select id from fx where k='binding'),null,1);
select is((select v->'evidence' from data where k='attempt-page'),list_ezyvet_migration_attempt_events((select id from fx where k='binding'),null,1),'Saved attempt page matches canonical bounded history before source chunks exist');
select is(prepare_ezyvet_migration_attempt_page((select id from fx where k='attempt-page'),(select id from fx where k='preparation'),(select id from fx where k='binding'),null,1),(select v from data where k='attempt-page'),'Attempt page retry recovers exact evidence');
select throws_ok($$select prepare_ezyvet_migration_attempt_page(gen_random_uuid(),(select id from fx where k='preparation'),(select id from fx where k='binding'),null,1)$$,'40001','Attempt history predecessor changed','Parallel root cannot replace selected history chain');
do $$declare tail jsonb;begin
 select v into tail from data where k='attempt-page';
 while (tail->>'has_more')::boolean loop
  tail:=prepare_ezyvet_migration_attempt_page(gen_random_uuid(),(select id from fx where k='preparation'),(select id from fx where k='binding'),(tail->>'id')::uuid,1);
 end loop;
 insert into data values('attempt-tail',tail);
end $$;
select is((select sum(jsonb_array_length(evidence->'events')) from ezyvet_migration_attempt_pages where preparation_id=(select id from fx where k='preparation')),(select count(*) from ezyvet_migration_attempt_events where child_run_id=(select (v->>'child_run_id')::uuid from data where k='attempt-tail')),'Full saved attempt chain retains every event');
select throws_ok($$select prepare_ezyvet_migration_attempt_page(gen_random_uuid(),(select id from fx where k='preparation'),(select id from fx where k='binding'),(select (v->>'id')::uuid from data where k='attempt-tail'),1)$$,'23514','Attempt history already ended','Cannot append beyond terminal attempt page');
select ok(not has_table_privilege('authenticated','public.ezyvet_migration_attempt_pages','select'),'Saved attempt pages remain private');
insert into data select 'source-chunk',prepare_ezyvet_migration_source_chunk((select id from fx where k='preparation'),(select id from fx where k='binding'),1);
create function pg_temp.prepared_history(bef integer default null,lim integer default 1) returns jsonb language sql as $$
 select read_ezyvet_migration_prepared_history_evidence((select id from fx where k='preparation'),(select id from fx where k='binding'),1,1,bef,lim);$$;
select is(pg_temp.prepared_history()->'approvals',pg_temp.receipts(null,1)->'approvals','Saved observation reuses canonical history approval interpretation');
select is(pg_temp.prepared_history()#>>'{approvals,0,version}','3','Prepared history reader starts at latest revision');
select is(pg_temp.prepared_history()->>'has_more','true','Approval revisions remain bounded with a sentinel');
select is(pg_temp.prepared_history(3)#>>'{approvals,0,version}','2','Prepared history cursor recovers earlier revision');
select is(pg_temp.prepared_history(2)#>>'{approvals,0,superseded}','true','Prepared history retains superseded approvals');
select is(pg_temp.prepared_history(2)#>>'{approvals,0,locally_edited_receipts}','1','Saved source retains canonical later local-edit evidence');
select is(pg_temp.prepared_history()->>'source_chunk_hash',(select v->>'evidence_hash' from data where k='source-chunk'),'Approval response binds exact saved source chunk');
select is(pg_temp.prepared_history()->>'dependency_consistency_verified','false','Paged approval read cannot claim cross-chunk consistency');
select throws_ok($$select pg_temp.prepared_history(null,101)$$,'23514','Invalid prepared history cursor','Prepared approval read refuses unbounded page');
select throws_ok($$select read_ezyvet_migration_prepared_history_evidence((select id from fx where k='preparation'),(select id from fx where k='binding'),1,2)$$,'23514','Saved history observation required','Missing saved observation rejected');
select ok(not has_function_privilege('authenticated','public.read_ezyvet_migration_prepared_history_evidence(uuid,uuid,integer,integer,integer,integer)','execute'),'Prepared history adapter remains internal');
select is(read_ezyvet_migration_prepared_versioned_evidence((select id from fx where k='preparation'),(select id from fx where k='binding'),1,1,null,1)->'approvals',pg_temp.prepared_history()->'approvals','Shared versioned adapter preserves history-specific interpretation');
select ok(not has_function_privilege('authenticated','public.read_ezyvet_migration_prepared_versioned_evidence(uuid,uuid,integer,integer,integer,integer)','execute'),'Shared versioned adapter remains private');


select throws_ok($$select read_ezyvet_migration_prepared_identity_evidence((select id from fx where k='preparation'),(select id from fx where k='binding'),1,1)$$,'23514','Saved identity observation required','Identity reader rejects history source');
select throws_ok($$select read_ezyvet_migration_prepared_timed_evidence((select id from fx where k='preparation'),(select id from fx where k='binding'),1,1)$$,'23514','Saved timed observation required','Timed reader rejects history source');
select throws_ok($$select read_ezyvet_migration_prepared_timed_evidence(null,null,1,1,now(),null)$$,'23514','Invalid prepared timed cursor','Incomplete time cursor rejected');
select throws_ok($$select read_ezyvet_migration_prepared_timed_evidence(null,null,1,1,'infinity',gen_random_uuid())$$,'23514','Invalid prepared timed cursor','Nonfinite time cursor rejected');
select throws_ok($$select read_ezyvet_migration_prepared_identity_evidence(null,null,1,0)$$,'23514','Invalid prepared identity observation','Invalid identity ordinal rejected');
select ok(not has_function_privilege('authenticated','public.read_ezyvet_migration_prepared_identity_evidence(uuid,uuid,integer,integer)','execute'),'Prepared identity stays private');
select ok(not has_function_privilege('authenticated','public.read_ezyvet_migration_prepared_timed_evidence(uuid,uuid,integer,integer,timestamptz,uuid,integer)','execute'),'Prepared timed reader stays private');
select throws_ok($$select read_ezyvet_migration_prepared_timed_evidence(gen_random_uuid(),gen_random_uuid(),1,1)$$,'42501','Owned source chunk required','Unknown timed chunk rejected');
create function pg_temp.prepared_native(approval_key text default 'source-approval',bef uuid default null,lim integer default 1) returns jsonb language sql as $$
 select read_ezyvet_migration_prepared_native_evidence((select id from fx where k='preparation'),(select id from fx where k='binding'),1,1,(select id from fx where k=approval_key),bef,lim);$$;
select is(pg_temp.prepared_native()#>>'{outcomes,0,provenance_id}',(select id::text from fx where k='extraction'),'Saved native provenance identifies exact DVM extraction');
select is(pg_temp.prepared_native()#>>'{outcomes,0,native_id}',(select id::text from fx where k='problem'),'Saved native provenance identifies local problem');
select is(pg_temp.prepared_native()#>>'{outcomes,0,local_changed}','true','Later local edits stay visible');
select is(pg_temp.prepared_native()#>>'{outcomes,0,action}','create','Native creation remains distinct from source approval');
select is(pg_temp.prepared_native('approval2')->'outcomes','[]'::jsonb,'Later same-source approval does not inherit earlier extraction');
select is(pg_temp.prepared_native('approval3')->'outcomes','[]'::jsonb,'Different source revision does not inherit earlier extraction');
select is(pg_temp.prepared_native('source-approval',(select id from fx where k='extraction'))->'outcomes','[]'::jsonb,'Strict native cursor excludes boundary receipt');
select is(pg_temp.prepared_native()->>'has_more','false','Single extraction reaches terminal page');
select is(pg_temp.prepared_native()->>'report_ready','false','Native receipt does not complete report');
select ok(not(pg_temp.prepared_native()::text ~ 'PRIVATE|notes|problem_fields|request_hash|DVM-authored'),'Native provenance omits chart prose and private review payload');
select throws_ok($$select pg_temp.prepared_native('source-approval',null,101)$$,'23514','Invalid prepared native cursor','Unbounded native page rejected');
select throws_ok($$select pg_temp.prepared_native('binding')$$,'42501','Related history approval required','Unrelated UUID cannot select native provenance');
select ok(not has_function_privilege('authenticated','public.read_ezyvet_migration_prepared_native_evidence(uuid,uuid,integer,integer,uuid,uuid,integer)','execute'),'Native preparation reader stays private');
insert into fx values('saved-review',gen_random_uuid());
create function pg_temp.save_review(kind text default 'native') returns jsonb language sql as $$
 select prepare_ezyvet_migration_review_page((select id from fx where k='saved-review'),(select id from fx where k='preparation'),(select id from fx where k='binding'),1,1,kind,null,null,null,case when kind='native' then (select id from fx where k='source-approval') else null end,1);$$;
insert into data select 'saved-review',pg_temp.save_review();
select is(pg_temp.save_review(),(select v from data where k='saved-review'),'Lost review reply returns exact saved receipt');
select is((select count(*) from ezyvet_migration_review_pages),1::bigint,'Retry stores only one review page');
select is(pg_temp.save_review()#>'{evidence,outcomes}',pg_temp.prepared_native()->'outcomes','Persisted native evidence matches bounded reader');
select is(pg_temp.save_review()->>'evidence_hash',encode(sha256(convert_to((pg_temp.save_review()->'evidence')::text,'UTF8')),'hex'),'Saved evidence digest binds exact contents');
select throws_ok($$select pg_temp.save_review('versioned')$$,'42501','Owned identical review request required','Saved UUID cannot switch review kind');
select throws_ok($$select prepare_ezyvet_migration_review_page(gen_random_uuid(),(select id from fx where k='preparation'),(select id from fx where k='binding'),1,1,'identity',1)$$,'23514','Invalid saved review request','Unused cursor arguments are rejected');
select is(read_ezyvet_migration_dependency_state((select id from fx where k='preparation'))->>'dependencies_unchanged','true','Saving chunks and review pages does not invalidate dependencies');
create function pg_temp.discover_reviews(bef timestamptz default null,bid uuid default null,lim integer default 1) returns jsonb language sql as $$
 select list_ezyvet_migration_review_pages((select id from fx where k='preparation'),bef,bid,lim);$$;
create function pg_temp.recover_review() returns jsonb language sql as $$
 select read_ezyvet_migration_review_page((select id from fx where k='preparation'),(select id from fx where k='saved-review'));$$;
select is(pg_temp.recover_review(),(select v from data where k='saved-review'),'Discovery recovery returns exact historical receipt');
select is(pg_temp.discover_reviews()#>>'{pages,0,id}',(select id::text from fx where k='saved-review'),'Preparation finds saved page without request arguments');
select ok(not ((pg_temp.discover_reviews()#>'{pages,0}') ? 'evidence'),'Discovery omits evidence payload');
select is(pg_temp.discover_reviews()->>'has_more','false','Single saved page has no continuation');
select prepare_ezyvet_migration_review_page(gen_random_uuid(),(select id from fx where k='preparation'),(select id from fx where k='binding'),1,1,'versioned');
select is((select count(*) from ezyvet_migration_review_requirements where preparation_id=(select id from fx where k='preparation') and kind='native'),0::bigint,'Unlinked history page does not establish native work coverage');
select append_ezyvet_migration_review_chain(gen_random_uuid(),(select id from ezyvet_migration_review_pages where preparation_id=(select id from fx where k='preparation') and kind='versioned'));
select is((select count(*) from ezyvet_migration_review_requirements where preparation_id=(select id from fx where k='preparation') and kind='native'),1::bigint,'Linked history approvals register exact extraction stream');
select is((select approval_id from ezyvet_migration_review_requirements where preparation_id=(select id from fx where k='preparation') and kind='native'),(select id from fx where k='source-approval'),'Native requirement binds original approved revision');
select is(read_ezyvet_migration_report_progress((select id from fx where k='preparation'))->>'missing_review_chunks','1','History chain alone leaves native review incomplete');
select throws_ok($$select complete_ezyvet_migration_chunk_reviews((select id from fx where k='preparation'),(select id from fx where k='binding'),1)$$,'23514','Required review streams are incomplete','Missing native stream prevents chunk completion');
select append_ezyvet_migration_review_chain(gen_random_uuid(),(select id from fx where k='saved-review'));
insert into data select 'native-aggregation',aggregate_ezyvet_migration_native_page((select id from ezyvet_migration_review_chain_links where review_page_id=(select id from fx where k='saved-review')));
select is(aggregate_ezyvet_migration_native_page((select id from ezyvet_migration_review_chain_links where review_page_id=(select id from fx where k='saved-review'))),(select v from data where k='native-aggregation'),'Native aggregation retry recovers exact receipt');
select is((select records from ezyvet_migration_native_counts where preparation_id=(select id from fx where k='preparation') and native_kind='problem' and metric='records'),1::bigint,'Selected extraction contributes one distinct local problem');
select is((select records from ezyvet_migration_native_counts where preparation_id=(select id from fx where k='preparation') and native_kind='problem' and metric='locally_changed_records'),1::bigint,'Native aggregate retains later local edit');
select aggregate_ezyvet_migration_native_page((select l.id from ezyvet_migration_review_chain_links l join ezyvet_migration_review_pages p on p.id=l.review_page_id where p.preparation_id=(select id from fx where k='preparation') and p.kind='versioned'));
select is((select sum(records) from ezyvet_migration_native_counts where preparation_id=(select id from fx where k='preparation') and metric='records'),1::numeric,'History approval alone does not add native outcome credit');

select complete_ezyvet_migration_chunk_reviews((select id from fx where k='preparation'),(select id from fx where k='binding'),1);
select is(read_ezyvet_migration_report_progress((select id from fx where k='preparation'))->>'bound_chunk_work_complete','true','Completed history and native streams close planned chunk work');
select is(read_ezyvet_migration_report_progress((select id from fx where k='preparation'))->>'completed_review_chunks','1','Report counts exact completed chunk once');
select is(read_ezyvet_migration_report_progress((select id from fx where k='preparation'))->>'report_ready','false','Completed bound work is not an assembled report');
insert into data select 'aggregation-work',list_ezyvet_migration_aggregation_work((select id from fx where k='preparation'),null,1);
select is((select v->>'has_more' from data where k='aggregation-work'),'true','Aggregation work has bounded continuation');
select is((select jsonb_array_length(v->'pages') from data where k='aggregation-work'),1,'Aggregation work honors page limit');
select is((select v#>>'{pages,0,native_aggregated}' from data where k='aggregation-work'),'true','Work discovery recognizes saved native aggregation');
select is((select v#>>'{pages,0,receipts_aggregated}' from data where k='aggregation-work'),'false','Collected review still exposes missing receipt aggregation');
select is((select list_ezyvet_migration_aggregation_work((select id from fx where k='preparation'),(v->>'next_after_id')::uuid,1)->>'has_more' from data where k='aggregation-work'),'false','Aggregation cursor reaches final selected page');
select isnt((select list_ezyvet_migration_aggregation_work((select id from fx where k='preparation'),(v->>'next_after_id')::uuid,1)#>>'{pages,0,id}' from data where k='aggregation-work'),(select v#>>'{pages,0,id}' from data where k='aggregation-work'),'Aggregation continuation does not repeat first page');
select is(read_ezyvet_migration_report_progress((select id from fx where k='preparation'))->>'missing_source_aggregations','1','Completed review does not imply source totals were calculated');
select aggregate_ezyvet_migration_source_chunk((select id from fx where k='preparation'),(select id from fx where k='binding'),1);
select is(read_ezyvet_migration_report_progress((select id from fx where k='preparation'))->>'aggregated_source_chunks','1','Progress recognizes exact source aggregation receipt');
select is(read_ezyvet_migration_report_progress((select id from fx where k='preparation'))->>'missing_source_aggregations','0','Source aggregation closes pending calculation count');
select is(read_ezyvet_migration_report_progress((select id from fx where k='preparation'))->>'missing_review_aggregations','1','Collected review with missing calculations remains incomplete');
select throws_ok($$select freeze_ezyvet_migration_calculations((select id from fx where k='preparation'))$$,'23514','Preparation calculations are incomplete','Pending receipt processing prevents calculation freeze');
insert into data select 'aggregation-batch',process_ezyvet_migration_aggregation_work((select id from fx where k='preparation'),null,1);
select is((select v#>>'{pages,0,receipts_aggregated}' from data where k='aggregation-batch'),'true','Batch calculates selected approval receipts');
select is((select count(*) from ezyvet_migration_approval_aggregations where preparation_id=(select id from fx where k='preparation')),1::bigint,'Single-page batch processes exactly one page');
select is(process_ezyvet_migration_aggregation_work((select id from fx where k='preparation'),null,1),(select v from data where k='aggregation-batch'),'Batch retry preserves exact page state');
select process_ezyvet_migration_aggregation_work((select id from fx where k='preparation'),(v->>'next_after_id')::uuid,1) from data where k='aggregation-batch';
select is((select count(*) from ezyvet_migration_approval_aggregations where preparation_id=(select id from fx where k='preparation')),2::bigint,'Continuation completes second page without duplicate receipts');
select is((select selected_pages from ezyvet_migration_chunk_work_counts where preparation_id=(select id from fx where k='preparation')),2::bigint,'Work counter records each selected page once');
select is((select native_pages from ezyvet_migration_chunk_work_counts where preparation_id=(select id from fx where k='preparation')),2::bigint,'Native retries do not inflate processed page count');
select is((select receipt_pages from ezyvet_migration_chunk_work_counts where preparation_id=(select id from fx where k='preparation')),2::bigint,'Receipt retries do not inflate processed page count');
select is(read_ezyvet_migration_report_progress((select id from fx where k='preparation'))->>'missing_review_aggregations','0','All selected review pages have both aggregation families');
select is(read_ezyvet_migration_report_progress((select id from fx where k='preparation'))->>'bound_aggregation_work_complete','true','Source and completed review calculations close bound work');
select is(read_ezyvet_migration_report_progress((select id from fx where k='preparation'))->>'report_ready','false','Calculated work is still not a frozen report');
select ok(not has_table_privilege('authenticated','public.ezyvet_migration_chunk_work_counts','select'),'Transactional work counters remain private');

select throws_ok($$select process_ezyvet_migration_aggregation_work((select id from fx where k='preparation'),null,11)$$,'23514','Invalid aggregation batch limit','Oversized processing batch rejected');
select ok(not has_function_privilege('authenticated','public.process_ezyvet_migration_aggregation_work(uuid,uuid,integer)','execute'),'Batch processing stays private');
select ok((select bool_and((p->>'receipts_aggregated')::boolean) from jsonb_array_elements(list_ezyvet_migration_aggregation_work((select id from fx where k='preparation'))->'pages') p),'Work discovery recognizes newly processed receipts');
select ok(not ((list_ezyvet_migration_aggregation_work((select id from fx where k='preparation'))#>'{pages,0}') ? 'evidence'),'Aggregation work omits clinical evidence payload');
select throws_ok($$select list_ezyvet_migration_aggregation_work((select id from fx where k='preparation'),null,101)$$,'23514','Invalid aggregation work limit','Unbounded work discovery rejected');
select throws_ok($$select list_ezyvet_migration_aggregation_work(gen_random_uuid())$$,'42501','Owned preparation required','Unknown preparation work rejected');
select ok(not has_function_privilege('authenticated','public.list_ezyvet_migration_aggregation_work(uuid,uuid,integer)','execute'),'Aggregation recovery remains private');
insert into data select 'discovery',pg_temp.discover_reviews();
select is((select v->>'has_more' from data where k='discovery'),'true','Discovery sentinel signals older page');
select is((select pg_temp.discover_reviews((v#>>'{next_cursor,before_at}')::timestamptz,(v#>>'{next_cursor,before_id}')::uuid)#>>'{pages,0,id}' from data where k='discovery'),(select id::text from fx where k='saved-review'),'Cursor recovers older saved native page');
select throws_ok($$select pg_temp.discover_reviews(now())$$,'23514','Invalid review discovery cursor','Partial discovery cursor rejected');
select throws_ok($$select pg_temp.discover_reviews(null,null,101)$$,'23514','Invalid review discovery cursor','Unbounded discovery rejected');
select throws_ok($$select read_ezyvet_migration_review_page(gen_random_uuid(),(select id from fx where k='saved-review'))$$,'42501','Owned review page required','Page cannot be reopened under substituted preparation');
select ok(not has_function_privilege('authenticated','public.list_ezyvet_migration_review_pages(uuid,timestamptz,uuid,integer)','execute'),'Review discovery remains private');
select ok(not has_function_privilege('authenticated','public.read_ezyvet_migration_review_page(uuid,uuid)','execute'),'Review recovery remains private');
select is((select count(*) from ezyvet_migration_selected_approvals((select l.id from ezyvet_migration_review_chain_links l join ezyvet_migration_review_pages p on p.id=l.review_page_id where p.preparation_id=(select id from fx where k='preparation') and p.kind='versioned'))),3::bigint,'Selected approval page retains all history revisions');
select is((select count(*) from ezyvet_migration_selected_approvals((select l.id from ezyvet_migration_review_chain_links l join ezyvet_migration_review_pages p on p.id=l.review_page_id where p.preparation_id=(select id from fx where k='preparation') and p.kind='versioned')) where facets->>'local_changed'='true'),1::bigint,'Only original extracted revision carries later chart edit');
select ok(not has_function_privilege('authenticated','public.ezyvet_migration_selected_approvals(uuid)','execute'),'Selected approval normalization stays private');
alter table ezyvet_migration_native_aggregations disable trigger migration_chunk_work;
select throws_ok($$select freeze_ezyvet_migration_calculations((select id from fx where k='preparation'))$$,'55000','Calculation guard coverage incomplete','Disabled processing counter prevents freeze');
alter table ezyvet_migration_native_aggregations enable trigger migration_chunk_work;
alter table ezyvet_migration_coverage_counts disable trigger migration_calculation_freeze;
select throws_ok($$select freeze_ezyvet_migration_calculations((select id from fx where k='preparation'))$$,'55000','Calculation guard coverage incomplete','Disabled derived counter freeze guard prevents snapshot');
alter table ezyvet_migration_coverage_counts enable trigger migration_calculation_freeze;
insert into data select 'frozen-calculations',freeze_ezyvet_migration_calculations((select id from fx where k='preparation'));
select is((select v->>'calculations_frozen' from data where k='frozen-calculations'),'true','Completed calculations freeze successfully');
select is(freeze_ezyvet_migration_calculations((select id from fx where k='preparation')),(select v from data where k='frozen-calculations'),'Freeze replay returns identical historical snapshot');
select is((select v->>'evidence_hash' from data where k='frozen-calculations'),(select encode(sha256(convert_to((v->'payload')::text,'UTF8')),'hex') from data where k='frozen-calculations'),'Frozen payload hash matches exact stored totals');
select throws_ok($$select prepare_ezyvet_migration_review_page(gen_random_uuid(),(select id from fx where k='preparation'),(select id from fx where k='binding'),1,1,'versioned')$$,'23514','Preparation calculations are frozen','New review pages cannot modify frozen preparation');
select ok(not has_table_privilege('authenticated','public.ezyvet_migration_calculation_snapshots','select'),'Calculation snapshot stays private');
insert into data select 'snapshot-read',read_ezyvet_migration_calculation_snapshot((select id from fx where k='preparation'));
select is((select v->'scan' from data where k='snapshot-read'),ezyvet_migration_scan_totals((select id from fx where k='migration')),'Frozen history scan summary equals full projection');
select is((select v->'source_resources' from data where k='snapshot-read'),ezyvet_migration_source_totals((select id from fx where k='migration'))->'resources','Frozen source rows equal full canonical counts');
select is((select v->'outcomes' from data where k='snapshot-read'),ezyvet_migration_outcome_totals((select id from fx where k='migration')),'Frozen history/native outcome presentation equals full canonical projection');
select is(ezyvet_migration_frozen_source_resources('{"plan":[{"resource":"history","disposition":"required"},{"resource":"history","disposition":"excluded"},{"resource":"history","disposition":"unsupported"}],"source_counts":[]}')#>>'{0,unbound_required_scopes}','1','Frozen source retains unbound required scope');
select is(ezyvet_migration_frozen_source_resources('{"plan":[{"resource":"history","disposition":"excluded"}],"source_counts":[]}')#>>'{0,excluded_scopes}','1','Excluded resource remains visible');
select is(ezyvet_migration_frozen_source_resources('{"plan":[{"resource":"history","disposition":"unsupported"}],"source_counts":[]}')#>>'{0,unsupported_scopes}','1','Unsupported resource remains visible');
select is(ezyvet_migration_frozen_source_resources('{"plan":[{"resource":"history","disposition":"required"}],"source_counts":[]}')#>'{0,provider_total}','null'::jsonb,'Frozen source does not invent provider denominator');
select is((select v->'review' from data where k='snapshot-read'),ezyvet_migration_review_totals((select id from fx where k='migration')),'Frozen history review presentation equals complete canonical projection');
select is((select v#>>'{dependency_state,dependencies_unchanged}' from data where k='snapshot-read'),'true','Frozen reader reports current dependency status separately');
select is(ezyvet_migration_frozen_review('{"plan":[{"resource":"consult"},{"resource":"history"}],"coverage_counts":[]}')#>>'{resources,0,approval_applicability}','not_applicable','Consultation approvals are not applicable');
select is(ezyvet_migration_frozen_review('{"plan":[{"resource":"consult"},{"resource":"history"}],"coverage_counts":[]}')#>'{resources,0,occurrences_without_approval}','null'::jsonb,'Consultation does not invent missing approvals');
select is(ezyvet_migration_frozen_review('{"plan":[{"resource":"consult"},{"resource":"history"}],"coverage_counts":[]}')#>>'{resources,1,observed_occurrences}','0','Unobserved planned resource remains present with zero observations');
select is(ezyvet_migration_frozen_review('{"plan":[{"resource":"history"}],"coverage_counts":[]}')#>>'{resources,0,occurrences_without_approval}','0','No observations does not invent unapproved records');
select throws_ok($$select read_ezyvet_migration_calculation_snapshot(gen_random_uuid())$$,'42501','Owned frozen calculations required','Unknown frozen calculation access rejected');
select ok(not has_function_privilege('authenticated','public.read_ezyvet_migration_calculation_snapshot(uuid)','execute'),'Frozen snapshot reader remains private');
update patient_problems set version=version+1 where id=(select id from fx where k='problem');
select is(read_ezyvet_migration_calculation_snapshot((select id from fx where k='preparation'))->'snapshot',(select v->'snapshot' from data where k='snapshot-read'),'Historical snapshot stays identical after chart changes');
select is(read_ezyvet_migration_calculation_snapshot((select id from fx where k='preparation'))#>>'{dependency_state,dependencies_unchanged}','false','Snapshot read exposes later drift separately from frozen evidence');

select is(freeze_ezyvet_migration_calculations((select id from fx where k='preparation')),(select v from data where k='frozen-calculations'),'Later source drift does not rewrite historical frozen totals');

select throws_ok($$select process_ezyvet_migration_aggregation_work((select id from fx where k='preparation'))$$,'40001','Prepared dependencies changed; create a new preparation','Processing stale preparation rejects even previously calculated pages');
select is(read_ezyvet_migration_report_progress((select id from fx where k='preparation'))#>>'{dependency_state,dependencies_unchanged}','false','Completed work still shows later dependency drift');
select is(read_ezyvet_migration_report_progress((select id from fx where k='preparation'))->>'bound_chunk_work_complete','true','Historical work completeness remains distinct from currentness');
select is(read_ezyvet_migration_dependency_state((select id from fx where k='preparation'))->>'dependencies_unchanged','false','Later own-transaction chart mutation invalidates baseline');
select is(read_ezyvet_migration_dependency_state((select id from fx where k='preparation'))->'changed_tables','["patient_problems"]'::jsonb,'Dependency state exposes table category only');
select is(read_ezyvet_migration_dependency_state((select id from fx where k='preparation'))->>'report_ready','false','Dependency read never claims complete report');
select ok(not has_function_privilege('authenticated','public.read_ezyvet_migration_dependency_state(uuid)','execute'),'Dependency checker stays private');
select throws_ok($$select prepare_ezyvet_migration_review_page(gen_random_uuid(),(select id from fx where k='preparation'),(select id from fx where k='binding'),1,1,'versioned')$$,'40001','Prepared dependencies changed; create a new preparation','New review page refuses changed dependencies');
select is((select count(*) from ezyvet_migration_review_pages),2::bigint,'Rejected review adds no partial receipt');
select is(pg_temp.save_review(),(select v from data where k='saved-review'),'Replay preserves recorded evidence after chart mutation');
select isnt(pg_temp.save_review()#>>'{evidence,outcomes,0,current_version}',pg_temp.prepared_native()#>>'{outcomes,0,current_version}','Fresh reader sees later chart version without rewriting receipt');
select is(pg_temp.save_review()->>'currentness_reverified','false','Recovered page is not a freshness check');
select is(pg_temp.save_review()->>'report_ready','false','Saved review is not complete report');
select ok(not has_table_privilege('authenticated','public.ezyvet_migration_review_pages','select'),'Review page ledger stays private');
select ok(not has_function_privilege('authenticated','public.prepare_ezyvet_migration_review_page(uuid,uuid,uuid,integer,integer,text,integer,timestamptz,uuid,uuid,integer)','execute'),'Review persistence function stays private');
select set_config('request.jwt.claims','{"sub":"db490000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select throws_ok($$select pg_temp.prepared_history()$$,'42501','Owned source chunk required','Foreign administrator cannot use saved source approval reader');
select throws_ok($$select read_ezyvet_migration_prepared_versioned_evidence((select id from fx where k='preparation'),(select id from fx where k='binding'),1,1)$$,'42501','Owned source chunk required','Shared adapter denies foreign administrator');
select throws_ok($$select pg_temp.prepared_native()$$,'42501','Owned source chunk required','Foreign administrator cannot read prepared native provenance');
select throws_ok($$select pg_temp.save_review()$$,'42501','Owned identical review request required','Foreign administrator cannot recover saved review');
select throws_ok($$select pg_temp.discover_reviews()$$,'42501','Owned preparation required','Foreign administrator cannot discover saved pages');
select throws_ok($$select pg_temp.recover_review()$$,'42501','Owned review page required','Foreign administrator cannot reopen saved page');
select throws_ok($$select read_ezyvet_migration_dependency_state((select id from fx where k='preparation'))$$,'42501','Owned preparation required','Foreign administrator cannot inspect dependency state');
select throws_ok($$select read_ezyvet_migration_report_progress((select id from fx where k='preparation'))$$,'42501','Owned preparation required','Foreign administrator cannot read report progress');
select throws_ok($$select read_ezyvet_migration_calculation_snapshot((select id from fx where k='preparation'))$$,'42501','Owned frozen calculations required','Foreign administrator cannot read frozen snapshot');
select * from finish();rollback;
