begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select no_plan();
-- FIXTURE_BEGIN: owner-only synthetic source observations and reviewed mapping.
insert into auth.users(id,email,raw_user_meta_data) values('db560000-0000-4000-8000-000000000001','clinical-import-admin@example.test','{}'),('db560000-0000-4000-8000-000000000002','clinical-import-other@example.test','{}');
insert into user_roles(user_id,role) values('db560000-0000-4000-8000-000000000001','ADMIN'),('db560000-0000-4000-8000-000000000002','ADMIN');
create temp table fx(k text primary key,id uuid);create temp table data(k text primary key,v jsonb);grant all on fx,data to authenticated,service_role;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db560000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'client',id from save_client(auth.uid(),null,null,'Clinical','Import','+13035550199','clinical-import@example.test','EMAIL',null,null);
insert into fx select 'pet',id from save_patient(null,(select id from fx where k='client'),null,'Scoped dog','Dog',null,null,'unknown',null,'unknown','unknown',null,null,null);
insert into fx select k,gen_random_uuid() from unnest(array['mapping','mapping2','snapshot','snapshot2','legacy','terminal','run','history','other-run']) k;
reset role;
insert into ezyvet_import_snapshots(id,source_origin,source_site_uid,resource,external_id,payload,payload_hash,first_seen_by) select id,'https://api.trial.ezyvet.com','prescriptionitem-test-site','animal',case when k='snapshot' then '77' else '88' end,jsonb_build_object('id',case when k='snapshot' then 77 else 88 end),k,'db560000-0000-4000-8000-000000000001' from fx where k in ('snapshot','snapshot2');
insert into ezyvet_record_links(id,request_id,request_hash,source_origin,source_site_uid,resource,external_id,snapshot_id,head_version,client_id,pet_id,local_version,action,reason,approved_by)
select id,gen_random_uuid(),k,'https://api.trial.ezyvet.com','prescriptionitem-test-site','animal',case when k='mapping' then '77' else '88' end,(select id from fx where k=case when m.k='mapping' then 'snapshot' else 'snapshot2' end),1,(select id from fx where k='client'),(select id from fx where k='pet'),1,'link','Synthetic approved mapping','db560000-0000-4000-8000-000000000001' from fx m where k in ('mapping','mapping2');
insert into fx values('prescription-run',gen_random_uuid());
insert into data select 'prescription-run',claim_ezyvet_prescription_import((select id from fx where k='prescription-run'),'db560000-0000-4000-8000-000000000001','prescriptionitem-test-site','prescription','https://api.trial.ezyvet.com',(select id from fx where k='mapping'));
select stage_ezyvet_import_page((select id from fx where k='prescription-run'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='prescription-run'),1,true,'[{"external_id":"101","payload":{"id":101,"animal_id":77,"instructions":"Source prescriptionation"}},{"external_id":"102","payload":{"id":102,"animal_id":77}}]');
insert into data select 'prescription',list_ezyvet_prescription_candidates((select id from fx where k='mapping'),'prescription')->'candidates'->0;
-- Choose external prescription 101 independent of creation-order ties.
update data set v=(select c from jsonb_array_elements(list_ezyvet_prescription_candidates((select id from fx where k='mapping'),'prescription')->'candidates') c where c->>'external_id'='101') where k='prescription';
insert into data values('items','[{"external_id":"501","payload":{"id":501,"prescription_id":101,"product_id":null,"date_start":null,"remaining":"unknown","qty":"outside units","serial_number":"outside author","instructions":"<script>outside prose</script>"}}]');
insert into data select 'legacy',to_jsonb(claim_ezyvet_import_core((select id from fx where k='legacy'),'db560000-0000-4000-8000-000000000001','prescriptionitem-test-site','prescriptionitem','https://api.trial.ezyvet.com'));
select stage_ezyvet_import_page_core((select id from fx where k='legacy'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='legacy'),1,false,(select v from data where k='items'));
update ezyvet_import_runs set retry_after=null,lease_until=null;
insert into data select 'terminal',to_jsonb(claim_ezyvet_import_core((select id from fx where k='terminal'),'db560000-0000-4000-8000-000000000001','prescriptionitem-test-site','prescriptionitem','https://api.trial.ezyvet.com'));
select stage_ezyvet_import_page_core((select id from fx where k='terminal'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='terminal'),1,true,'[]');
update ezyvet_import_runs set retry_after=null,lease_until=null;
reset role;
insert into data select 'review-run',claim_ezyvet_prescriptionitem_import((select id from fx where k='run'),'db560000-0000-4000-8000-000000000001','prescriptionitem-test-site','prescriptionitem','https://api.trial.ezyvet.com',(select id from fx where k='mapping'),(select (v->>'id')::uuid from data where k='prescription'),(select v->>'payload_hash' from data where k='prescription'),(select (v->>'observed_head_version')::integer from data where k='prescription'));
select stage_ezyvet_import_page((select id from fx where k='run'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='review-run'),1,true,(select v from data where k='items'));
insert into data select 'context',ezyvet_prescription_source_context((select id from fx where k='pet'),(select id from fx where k='run'));

insert into fx values('product',gen_random_uuid());
insert into catalog_products(id,name,kind,unit,unit_price_cents,created_by) select id,'Synthetic medication','medication','tablet',1000,'db560000-0000-4000-8000-000000000001' from fx where k='product';
insert into data select 'review',jsonb_build_object('reason','Historical interpretation only','outside_author',null,'prescribed_on',null,'prescription_date_status','uninterpreted','status','unknown','completeness','partial','partial_reason','Parent source list not supplied','replaces_id',null,'expected_predecessor_hash',null,'items',jsonb_build_array(jsonb_build_object('snapshot_id',v#>'{items,0,snapshot_id}','start_on',null,'start_date_status','unknown','product_id',(select id from fx where k='product'),'product_version',1,'note','No dose or refill inferred'))) from data where k='context';
insert into data select 'interpreted',ezyvet_prescription_interpretation_context((select v from data where k='context'),(select v from data where k='review'));
select is((select v#>>'{selected_items,0,source,original,qty}' from data where k='interpreted'),'outside units','Source quantity remains verbatim');
select is((select v#>>'{selected_items,0,source,original,instructions}' from data where k='interpreted'),'<script>outside prose</script>','Source instructions unchanged by review');
select is((select v#>>'{selected_items,0,product,unit}' from data where k='interpreted'),'tablet','Catalog unit retained separately');
select is((select v#>>'{selected_items,0,product,version}' from data where k='interpreted'),'1','Catalog revision pinned');
select is((select v#>>'{reviewed,prescription_date_status}' from data where k='interpreted'),'uninterpreted','No epoch date interpretation invented');
select throws_ok($$select ezyvet_prescription_interpretation_context((select v from data where k='context'),(select v||'{"completeness":"complete","partial_reason":null}' from data where k='review'))$$,'23514','Complete account requires matched source list and every observed item','Terminal scan with missing source list cannot claim complete');
select throws_ok($$select ezyvet_prescription_interpretation_context((select jsonb_set(v,'{consult,status}','"unresolved"') from data where k='context'),(select v from data where k='review'))$$,'40001',null,'Unresolved nonempty consult cannot be clinically reviewed');
select throws_ok($$select ezyvet_prescription_interpretation_context((select v from data where k='context'),(select v||'{"partial_reason":null}' from data where k='review'))$$,'23514',null,'Partial account requires explicit disclosure');
select throws_ok($$select ezyvet_prescription_interpretation_context((select v from data where k='context'),(select v||'{"prescribed_on":"2026-02-30","prescription_date_status":"date"}' from data where k='review'))$$,'23514','Invalid prescription date','Impossible prescription date rejected');
select throws_ok($$select ezyvet_prescription_interpretation_context((select v from data where k='context'),(select v||'{"prescribed_on":"2026-09-13","prescription_date_status":"unknown"}' from data where k='review'))$$,'23514',null,'Unknown precision cannot contain interpreted date');
select lives_ok($$select ezyvet_prescription_interpretation_context((select v from data where k='context'),(select v||'{"prescribed_on":"2026-09-13","prescription_date_status":"date"}' from data where k='review'))$$,'Explicit valid date accepted');
select throws_ok($$select ezyvet_prescription_interpretation_context((select v from data where k='context'),(select jsonb_set(v,'{items,0,snapshot_id}',to_jsonb(gen_random_uuid())) from data where k='review'))$$,'42501',null,'Unobserved selection rejected');
select throws_ok($$select ezyvet_prescription_interpretation_context((select v from data where k='context'),(select jsonb_set(v,'{items}',(v->'items')||(v->'items')) from data where k='review'))$$,'23514','Select each prescription item once','Duplicate selections rejected');
select throws_ok($$select ezyvet_prescription_interpretation_context((select v from data where k='context'),(select jsonb_set(v,'{items,0,original}','{}') from data where k='review'))$$,'23514',null,'Browser cannot replace original item evidence');
select throws_ok($$select ezyvet_prescription_interpretation_context((select v from data where k='context'),(select jsonb_set(v,'{items,0,product_version}','2') from data where k='review'))$$,'40001',null,'Stale catalog match rejected');
select throws_ok($$select ezyvet_prescription_interpretation_context((select v from data where k='context'),(select jsonb_set(v,'{items,0,product_version}','null') from data where k='review'))$$,'23514',null,'Incomplete catalog match rejected');
select is(jsonb_array_length(ezyvet_prescription_interpretation_context((select v from data where k='context'),(select v||'{"items":[]}' from data where k='review'))->'omitted_items'),1,'Unselected observed items remain explicit evidence');
select lives_ok($$select ezyvet_prescription_interpretation_context((select jsonb_set(v,'{reconciliation,status}','"matched"') from data where k='context'),(select v||'{"completeness":"complete","partial_reason":null}' from data where k='review'))$$,'Complete account accepted only for matched list and every item');
select throws_ok($$select ezyvet_prescription_interpretation_context((select jsonb_set(v,'{reconciliation,status}','"matched"') from data where k='context'),(select v||'{"completeness":"complete","partial_reason":null,"items":[]}' from data where k='review'))$$,'23514',null,'Complete account cannot omit an observed item');
select throws_ok($$select ezyvet_prescription_interpretation_context((select v from data where k='context'),(select v||'{"replaces_id":"invalid","expected_predecessor_hash":null}' from data where k='review'))$$,'23514',null,'Correction needs complete predecessor identity');
update catalog_products set active=false where id=(select id from fx where k='product');
select throws_ok($$select ezyvet_prescription_interpretation_context((select v from data where k='context'),(select v from data where k='review'))$$,'40001',null,'Inactive medication match rejected');
insert into fx values('service-product',gen_random_uuid());
insert into catalog_products(id,name,kind,unit,unit_price_cents,created_by) select id,'Synthetic service','service','visit',1000,'db560000-0000-4000-8000-000000000001' from fx where k='service-product';
update data set v=jsonb_set(v,'{items,0,product_id}',to_jsonb((select id from fx where k='service-product'))) where k='review';
select throws_ok($$select ezyvet_prescription_interpretation_context((select v from data where k='context'),(select v from data where k='review'))$$,'40001',null,'Service cannot masquerade as matched medication');
select ok(not has_function_privilege('authenticated','ezyvet_prescription_interpretation_context(jsonb,jsonb)','EXECUTE'),'Browser cannot supply fabricated source context');
select ok(not has_function_privilege('service_role','ezyvet_prescription_interpretation_context(jsonb,jsonb)','EXECUTE'),'Service cannot bypass scoped collector through interpreter');
select * from finish();rollback;
