begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select no_plan();
-- FIXTURE_BEGIN: owner-only synthetic source observations and reviewed mapping.
insert into auth.users(id,email,raw_user_meta_data) values('db560000-0000-4000-8000-000000000001','clinical-import-admin@example.test','{}'),('db560000-0000-4000-8000-000000000002','clinical-import-other@example.test','{}');
insert into user_roles(user_id,role) values('db560000-0000-4000-8000-000000000001','ADMIN'),('db560000-0000-4000-8000-000000000002','ADMIN');
create temp table fx(k text primary key,id uuid);create temp table data(k text primary key,v jsonb);grant all on fx,data to authenticated,service_role;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db560000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'client',id from save_client(auth.uid(),null,null,'Clinical','Import','+13035550199','clinical-import@example.test','EMAIL',null,null);
insert into fx select 'pet',id from save_patient(null,(select id from fx where k='client'),null,'Scoped dog','Dog',null,null,'unknown',null,'unknown','unknown',null,null,null);
insert into fx select k,gen_random_uuid() from unnest(array['mapping','mapping2','snapshot','snapshot2','legacy','terminal','run','history','other-run']) k;
reset role;
insert into ezyvet_import_snapshots(id,source_origin,source_site_uid,resource,external_id,payload,payload_hash,first_seen_by) select id,'https://api.trial.ezyvet.com','prescriptionitem-test-site','animal',case when k='snapshot' then '77' else '88' end,jsonb_build_object('id',case when k='snapshot' then 77 else 88 end),k,'db560000-0000-4000-8000-000000000001' from fx where k in ('snapshot','snapshot2');
insert into ezyvet_record_links(id,request_id,request_hash,source_origin,source_site_uid,resource,external_id,snapshot_id,head_version,client_id,pet_id,local_version,action,reason,approved_by)
select id,gen_random_uuid(),k,'https://api.trial.ezyvet.com','prescriptionitem-test-site','animal',case when k='mapping' then '77' else '88' end,(select id from fx where k=case when m.k='mapping' then 'snapshot' else 'snapshot2' end),1,(select id from fx where k='client'),(select id from fx where k='pet'),1,'link','Synthetic approved mapping','db560000-0000-4000-8000-000000000001' from fx m where k in ('mapping','mapping2');
insert into ezyvet_identity_heads(source_origin,source_site_uid,resource,external_id,snapshot_id,version)
select source_origin,source_site_uid,resource,external_id,id,1 from ezyvet_import_snapshots where id=(select id from fx where k='snapshot');
insert into fx select k,gen_random_uuid() from unnest(array['request','request2','tombstone','consult-source','consult-run','consult-request']) k;
insert into data select 'run',claim_ezyvet_attachment_import((select id from fx where k='run'),'db560000-0000-4000-8000-000000000001','prescriptionitem-test-site','https://api.trial.ezyvet.com',(select id from fx where k='mapping'),'Animal',(select id from fx where k='snapshot'),'snapshot',1);
select stage_ezyvet_import_page((select id from fx where k='run'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='run'),1,false,'[{"external_id":"701","payload":{"id":701,"record_type":"Animal","record_id":77,"mime_type":"application/pdf","file_download_url":"https://untrusted.example.test/file","name":"Source file"}}]');
insert into data select 'observation',jsonb_build_object('snapshot_id',s.id,'hash',s.payload_hash,'version',h.version) from ezyvet_import_snapshots s join ezyvet_identity_heads h on h.snapshot_id=s.id where s.resource='attachment' and s.external_id='701';
insert into data values('side-effects',jsonb_build_object('documents',(select count(*) from patient_documents),'treatments',(select count(*) from patient_treatments),'invoices',(select count(*) from billing_invoices),'stock',(select count(*) from inventory_movements),'outbox',(select count(*) from communication_outbox)));
create function pg_temp.prepare(k text default 'request') returns jsonb language sql as $$
 select prepare_ezyvet_attachment_download((select id from fx where fx.k=$1),(select id from fx where fx.k='pet'),(select id from fx where fx.k='run'),1,(v->>'snapshot_id')::uuid,v->>'hash',(v->>'version')::integer) from data where data.k='observation';
$$;
set local role authenticated;
insert into data select 'saved',pg_temp.prepare();
insert into data select 'saved2',pg_temp.prepare('request2');
reset role;
create function pg_temp.claim(k text default 'request') returns jsonb language sql as $$
 select claim_ezyvet_attachment_download((select id from fx where fx.k=$1),'db560000-0000-4000-8000-000000000001',(select id from fx where fx.k='pet'),(select v#>>'{request,request_hash}' from data where data.k='saved'));
$$;
create function pg_temp.fail(code text,seconds integer,lease_key text default 'lease') returns jsonb language sql as $$
 select fail_ezyvet_attachment_download((select id from fx where fx.k='request'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where data.k=$3),(select v#>>'{request,request_hash}' from data where data.k='saved'),$1,$2);
$$;
create function pg_temp.reserve(lease_key text default 'lease',sha text default repeat('a',64),mime text default 'application/pdf') returns jsonb language sql as $$
 select prepare_ezyvet_attachment_capture((select id from fx where k='request'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k=$1),(select v#>>'{request,request_hash}' from data where k='saved'),$2,37,$3,(select v#>'{request,source_context,attachment_metadata}' from data where k='saved'),(select v#>'{request,source_context,attachment_metadata}' from data where k='saved'));
$$;
create function pg_temp.complete(lease_key text default 'lease',sha text default repeat('a',64)) returns jsonb language sql as $$
 select complete_ezyvet_attachment_capture((select id from fx where k='request'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k=$1),(select v#>>'{request,request_hash}' from data where k='saved'),(select v->>'intent_hash' from data where k='intent'),$2,37,'application/pdf',(select v#>'{request,source_context,attachment_metadata}' from data where k='saved'));
$$;
select throws_ok($$select pg_temp.reserve()$$,'40001',null,'A current worker lease is required before reserving bytes');
update ezyvet_import_runs set retry_after=null,lease_until=null where id=(select id from fx where k='run');
set local role service_role;
insert into data select 'lease',pg_temp.claim();
select throws_ok($$select pg_temp.reserve('lease',repeat('a',64),'image/jpeg')$$,'23514','Capture MIME conflicts with source','Source MIME cannot be silently reinterpreted');
insert into data select 'intent',pg_temp.reserve();
select is(pg_temp.reserve(),(select v from data where k='intent'),'Lost reservation acknowledgment returns the exact same path and fingerprint');
select is((select v->>'bucket' from data where k='intent'),'ezyvet-attachments','API attachment has a dedicated private bucket');
select ok((select v->>'object_path' from data where k='intent') like 'db560000-0000-4000-8000-000000000001/'||(select id::text from fx where k='pet')||'/'||(select id::text from fx where k='request')||'/%/original','Object path is allocated by the server for this actor, patient and request');
select throws_ok($$select pg_temp.reserve('lease',repeat('b',64))$$,'40001',null,'Retry cannot replace reserved original bytes');
select throws_ok($$select pg_temp.complete()$$,'23514','Exact private original is unavailable','Capture cannot complete without the reserved object');
select throws_ok($$select pg_temp.complete('lease',repeat('b',64))$$,'42501',null,'Readback digest must match reservation');
select throws_ok($$select prepare_ezyvet_attachment_capture((select id from fx where k='request2'),'db560000-0000-4000-8000-000000000002',(select (v->>'lease_id')::uuid from data where k='lease'),(select v#>>'{request,request_hash}' from data where k='saved'),repeat('a',64),37,'application/pdf','{}','{}')$$,'42501',null,'Another actor cannot reserve an owned operation');
set local role authenticated;
select ok(ezyvet_attachment_storage_insert((select v->>'object_path' from data where k='intent')),'Active owner lease permits reserved upload');
select ok(not ezyvet_attachment_storage_insert('unreserved/original'),'Unreserved path cannot authorize upload');
select ok(ezyvet_attachment_storage_read((select v->>'object_path' from data where k='intent')),'Owner can recover private upload evidence');
select set_config('request.jwt.claims','{"sub":"db560000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select ok(not ezyvet_attachment_storage_insert((select v->>'object_path' from data where k='intent')),'Other administrator cannot upload to the owner path');
select ok(not ezyvet_attachment_storage_read((select v->>'object_path' from data where k='intent')),'Other administrator cannot read reserved original');
select set_config('request.jwt.claims','{"sub":"db560000-0000-4000-8000-000000000001","role":"authenticated"}',true);
-- Metadata-only Storage fixture: this SQL test does not claim a physical byte upload.
insert into storage.objects(bucket_id,name,owner,metadata) select 'ezyvet-attachments',v->>'object_path',auth.uid(),jsonb_build_object('size',37,'mimetype','application/pdf') from data where k='intent';
select is((select count(*)::integer from storage.objects where bucket_id='ezyvet-attachments'),1,'Owner can insert exactly the reserved object metadata');
with changed as(update storage.objects set metadata='{}' where bucket_id='ezyvet-attachments' returning id) select is(count(*)::integer,0,'No authenticated overwrite policy exists') from changed;
select throws_ok($$insert into storage.objects(bucket_id,name,owner,metadata) select 'ezyvet-attachments',v->>'object_path',auth.uid(),jsonb_build_object('size',37,'mimetype','application/pdf') from data where k='intent'$$,'23505',null,'A second insert cannot replace the immutable path');
select set_config('request.jwt.claims','{"sub":"db560000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select is((select count(*)::integer from storage.objects where bucket_id='ezyvet-attachments'),0,'Private object RLS hides owner bytes from another administrator');
select set_config('request.jwt.claims','{"sub":"db560000-0000-4000-8000-000000000001","role":"authenticated"}',true);
set local role service_role;
select throws_ok($$select pg_temp.complete('missing-lease')$$,'40001',null,'Fresh capture requires the current lease even after upload');
reset role;
update storage.objects set metadata=jsonb_build_object('size',38,'mimetype','application/pdf') where bucket_id='ezyvet-attachments';
set local role service_role;
select throws_ok($$select pg_temp.complete()$$,'23514','Exact private original is unavailable','Stored object metadata must match verified original');
reset role;
update storage.objects set metadata=jsonb_build_object('size',37,'mimetype','application/pdf') where bucket_id='ezyvet-attachments';
set local role service_role;
insert into data select 'capture',pg_temp.complete();
select is(pg_temp.complete(),(select v from data where k='capture'),'Lost final capture response recovers the exact immutable receipt');
select is(pg_temp.claim()->>'status','captured','Completed claim recovers receipt without issuing a new download lease');
select throws_ok($$select pg_temp.fail('STORAGE_UNAVAILABLE',30)$$,'40001',null,'Late worker cannot report a new failure after capture');
set local role authenticated;
select is(recover_ezyvet_attachment_download((select id from fx where k='request'),(select id from fx where k='pet'))#>>'{request,status}','captured','Owner recovery sees atomic capture completion');
select ok(not (recover_ezyvet_attachment_download((select id from fx where k='request'),(select id from fx where k='pet'))::text like '%'||(select v->>'lease_id' from data where k='lease')||'%'),'Staff projection hides both originating and completion leases');
select ok(not (recover_ezyvet_attachment_download((select id from fx where k='request'),(select id from fx where k='pet'))#>>'{worker,lease_active}')::boolean,'Captured request no longer reports an active worker');
select ok(not ezyvet_attachment_storage_insert((select v->>'object_path' from data where k='intent')),'Captured path cannot authorize another upload');
select throws_ok($$select abandon_ezyvet_attachment_download((select id from fx where k='request'),(select id from fx where k='pet'),true)$$,'23514','Captured evidence cannot be abandoned','Capture is retained for review rather than abandoned');
select ok(not exists(select 1 from jsonb_array_elements(list_ezyvet_attachment_downloads((select id from fx where k='pet'))->'requests') x where x#>'{capture_intent,before_metadata}' is not null or x#>'{capture_intent,after_metadata}' is not null),'Discovery omits full repeated capture metadata');
set local role service_role;
insert into data select 'other-lease',pg_temp.claim('request2');
select is((select v->>'attempt_no' from data where k='other-lease'),'1','Completed capture releases the shared source slot');
select throws_ok($$select prepare_ezyvet_attachment_capture((select id from fx where k='request2'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='other-lease'),(select v#>>'{request,request_hash}' from data where k='saved2'),repeat('a',64),37,'application/pdf','{}','{}')$$,'40001','SOURCE_ATTACHMENT_METADATA_CHANGED','Fresh reservation rejects metadata outside the owned observation');
insert into data select 'intent2',prepare_ezyvet_attachment_capture((select id from fx where k='request2'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='other-lease'),(select v#>>'{request,request_hash}' from data where k='saved2'),repeat('a',64),37,'application/pdf',(select v#>'{request,source_context,attachment_metadata}' from data where k='saved2'),(select v#>'{request,source_context,attachment_metadata}' from data where k='saved2'));
reset role;
update ezyvet_identity_heads set version=version+1 where resource='animal' and external_id='77';
set local role service_role;
select throws_ok($$select complete_ezyvet_attachment_capture((select id from fx where k='request2'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='other-lease'),(select v#>>'{request,request_hash}' from data where k='saved2'),(select v->>'intent_hash' from data where k='intent2'),repeat('a',64),37,'application/pdf',(select v#>'{request,source_context,attachment_metadata}' from data where k='saved2'))$$,'40001','SOURCE_ATTACHMENT_PARENT_STALE','Fresh completion revalidates the current parent even with an existing reservation');
select is(pg_temp.complete('missing-lease'),(select v from data where k='capture'),'Exact completed receipt recovers after lease and parent changes');
select is(pg_temp.reserve('missing-lease'),(select v from data where k='intent'),'Exact reservation remains recoverable after mutable source changes');
select is(pg_temp.claim()->>'status','captured','Terminal claim precedes source currentness checks');
reset role;
select is((select count(*)::integer from ezyvet_attachment_captures),1,'Only one immutable capture receipt exists');
select throws_ok($$update ezyvet_attachment_captures set content_sha256=repeat('b',64)$$,'23514',null,'Captured digest cannot be rewritten');
select throws_ok($$update ezyvet_attachment_capture_intents set object_path='replacement'$$,'23514',null,'Allocated path cannot be retargeted');
select throws_ok($$update ezyvet_attachment_download_requests set status='captured',resolved_at=clock_timestamp() where id=(select id from fx where k='request2')$$,'23514','Verified capture required','Status cannot claim capture without a verified receipt');
select ok(not (select public from storage.buckets where id='ezyvet-attachments'),'Attachment bucket is private');
select ok(not has_function_privilege('authenticated','public.complete_ezyvet_attachment_capture(uuid,uuid,uuid,text,text,text,bigint,text,jsonb)','execute'),'Browser cannot assert a verified digest');
select ok(not has_table_privilege('service_role','public.ezyvet_attachment_captures','insert'),'Service cannot bypass capture validation with direct insert');
select is(jsonb_build_object('documents',(select count(*) from patient_documents),'treatments',(select count(*) from patient_treatments),'invoices',(select count(*) from billing_invoices),'stock',(select count(*) from inventory_movements),'outbox',(select count(*) from communication_outbox)),(select v from data where k='side-effects'),'Private capture adds no manual document, clinical, stock, billing or delivery effects');
delete from user_roles where user_id='db560000-0000-4000-8000-000000000001' and role='ADMIN';
set local role authenticated;
select ok(not ezyvet_attachment_storage_read((select v->>'object_path' from data where k='intent')),'Role loss revokes access to captured private evidence');
set local role service_role;
select throws_ok($$select pg_temp.complete()$$,'42501','Active administrator required','Role loss also blocks receipt recovery through service completion');
reset role;
select * from finish();rollback;
