begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
select is(ezyvet_reconcile_prescription_items('[1,"2"]','[2,"1"]',true)->>'status','matched','Ordering and numeric-string identity do not invent differences');
select is(ezyvet_reconcile_prescription_items('[1]','[1]',false)->>'status','unresolved','Unfinished scan cannot match');
select is(ezyvet_reconcile_prescription_items('[]','[]',null)->>'status','unresolved','Unknown completion is not completion');
select is(ezyvet_reconcile_prescription_items('[]','[]',true)->>'status','matched','Explicit empty source list can match empty observed list');
select is(ezyvet_reconcile_prescription_items(null,'[]',true)->>'status','unresolved','Missing source list is unresolved');
select is(ezyvet_reconcile_prescription_items('null','[]',true)->>'sourceListPresent','false','Null source list is not empty');
select is(ezyvet_reconcile_prescription_items('"1,2"','[]',true)#>'{invalidSourceReferences,0,value}','"1,2"'::jsonb,'Malformed source list is retained exactly');
select is(ezyvet_reconcile_prescription_items('[1,"1",2,3]','[1,4,"4"]',true)->'missingIds','["2","3"]'::jsonb,'Missing IDs retain source order');
select is(ezyvet_reconcile_prescription_items('[1,"1",2,3]','[1,4,"4"]',true)->'unexpectedIds','["4"]'::jsonb,'Unexpected item retained');
select is(ezyvet_reconcile_prescription_items('[1,"1",2,3]','[1,4,"4"]',true)->'duplicateSourceIds','["1"]'::jsonb,'Duplicate source reference disclosed');
select is(ezyvet_reconcile_prescription_items('[1,"1",2,3]','[1,4,"4"]',true)->'duplicateObservedIds','["4"]'::jsonb,'Duplicate observed reference disclosed');
select is(ezyvet_reconcile_prescription_items('["01",null,{"id":2}]','[]',true)->'invalidSourceReferences','[{"index":0,"value":"01"},{"index":1,"value":null},{"index":2,"value":{"id":2}}]'::jsonb,'Malformed references preserve indices and values');
select is(ezyvet_reconcile_prescription_items('["9007199254740992","9007199254740993"]','["9007199254740992"]',true)->'missingIds','["9007199254740993"]'::jsonb,'Large string identifiers remain distinct');
select is(ezyvet_reconcile_prescription_items('[9007199254740992]','[]',true)#>>'{invalidSourceReferences,0,index}','0','Unsafe numeric identity is not rounded');
select throws_ok($$select ezyvet_reconcile_prescription_items('[]','{}',true)$$,'23514',null,'Malformed internal observed list fails closed');
select ok(not has_function_privilege('authenticated','ezyvet_reconcile_prescription_items(jsonb,jsonb,boolean)','EXECUTE'),'Browser cannot supply its own reconciliation for approval');
select ok(not has_function_privilege('service_role','ezyvet_prescription_reference_id(jsonb)','EXECUTE'),'Identity helper is private');
select * from finish();
rollback;
