begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select no_plan();
-- FIXTURE_BEGIN: owner-only synthetic source observations and reviewed mapping.
insert into auth.users(id,email,raw_user_meta_data) values('db560000-0000-4000-8000-000000000001','clinical-import-admin@example.test','{}'),('db560000-0000-4000-8000-000000000002','clinical-import-other@example.test','{}');
insert into user_roles(user_id,role) values('db560000-0000-4000-8000-000000000001','ADMIN'),('db560000-0000-4000-8000-000000000002','ADMIN');
create temp table fx(k text primary key,id uuid);create temp table data(k text primary key,v jsonb);grant all on fx,data to authenticated,service_role;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db560000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'client',id from save_client(auth.uid(),null,null,'Clinical','Import','+13035550199','clinical-import@example.test','EMAIL',null,null);
insert into fx select 'pet',id from save_patient(null,(select id from fx where k='client'),null,'Scoped dog','Dog',null,null,'unknown',null,'unknown','unknown',null,null,null);
insert into fx select k,gen_random_uuid() from unnest(array['mapping','mapping2','snapshot','snapshot2','legacy','terminal','run','history','other-run']) k;
reset role;
insert into ezyvet_import_snapshots(id,source_origin,source_site_uid,resource,external_id,payload,payload_hash,first_seen_by) select id,'https://api.trial.ezyvet.com','prescriptionitem-test-site','animal',case when k='snapshot' then '77' else '88' end,jsonb_build_object('id',case when k='snapshot' then 77 else 88 end),k,'db560000-0000-4000-8000-000000000001' from fx where k in ('snapshot','snapshot2');
insert into ezyvet_record_links(id,request_id,request_hash,source_origin,source_site_uid,resource,external_id,snapshot_id,head_version,client_id,pet_id,local_version,action,reason,approved_by)
select id,gen_random_uuid(),k,'https://api.trial.ezyvet.com','prescriptionitem-test-site','animal',case when k='mapping' then '77' else '88' end,(select id from fx where k=case when m.k='mapping' then 'snapshot' else 'snapshot2' end),1,(select id from fx where k='client'),(select id from fx where k='pet'),1,'link','Synthetic approved mapping','db560000-0000-4000-8000-000000000001' from fx m where k in ('mapping','mapping2');
insert into fx values('prescription-run',gen_random_uuid());
insert into data select 'prescription-run',claim_ezyvet_prescription_import((select id from fx where k='prescription-run'),'db560000-0000-4000-8000-000000000001','prescriptionitem-test-site','prescription','https://api.trial.ezyvet.com',(select id from fx where k='mapping'));
select stage_ezyvet_import_page((select id from fx where k='prescription-run'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='prescription-run'),1,true,'[{"external_id":"101","payload":{"id":101,"animal_id":77,"instructions":"Source prescriptionation"}},{"external_id":"102","payload":{"id":102,"animal_id":77,"consult_id":999}}]');
insert into data select 'prescription',list_ezyvet_prescription_candidates((select id from fx where k='mapping'),'prescription')->'candidates'->0;
-- Choose external prescription 101 independent of creation-order ties.
update data set v=(select c from jsonb_array_elements(list_ezyvet_prescription_candidates((select id from fx where k='mapping'),'prescription')->'candidates') c where c->>'external_id'='101') where k='prescription';
insert into data values('items','[{"external_id":"501","payload":{"id":501,"prescription_id":101,"product_id":null,"date_start":null,"remaining":"unknown","qty":"outside units","serial_number":"outside author","instructions":"<script>outside prose</script>"}}]');
insert into data select 'legacy',to_jsonb(claim_ezyvet_import_core((select id from fx where k='legacy'),'db560000-0000-4000-8000-000000000001','prescriptionitem-test-site','prescriptionitem','https://api.trial.ezyvet.com'));
select stage_ezyvet_import_page_core((select id from fx where k='legacy'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='legacy'),1,false,(select v from data where k='items'));
update ezyvet_import_runs set retry_after=null,lease_until=null;
insert into data select 'terminal',to_jsonb(claim_ezyvet_import_core((select id from fx where k='terminal'),'db560000-0000-4000-8000-000000000001','prescriptionitem-test-site','prescriptionitem','https://api.trial.ezyvet.com'));
select stage_ezyvet_import_page_core((select id from fx where k='terminal'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='terminal'),1,true,'[]');
update ezyvet_import_runs set retry_after=null,lease_until=null;
reset role;
insert into data select 'review-run',claim_ezyvet_prescriptionitem_import((select id from fx where k='run'),'db560000-0000-4000-8000-000000000001','prescriptionitem-test-site','prescriptionitem','https://api.trial.ezyvet.com',(select id from fx where k='mapping'),(select (v->>'id')::uuid from data where k='prescription'),(select v->>'payload_hash' from data where k='prescription'),(select (v->>'observed_head_version')::integer from data where k='prescription'));
select stage_ezyvet_import_page((select id from fx where k='run'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='review-run'),1,true,(select v from data where k='items'));
insert into data select 'context',ezyvet_prescription_source_context((select id from fx where k='pet'),(select id from fx where k='run'));

set local role authenticated;
select throws_ok($$select list_ezyvet_prescription_review_candidates((select id from fx where k='pet'))$$,'42501','Active veterinarian required','Administrator cannot read clinical review candidates without DVM role');
reset role;
insert into user_roles(user_id,role) values('db560000-0000-4000-8000-000000000002','DVM');
delete from user_roles where user_id='db560000-0000-4000-8000-000000000002' and role='ADMIN';
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"db560000-0000-4000-8000-000000000002","role":"authenticated"}',true);
insert into data select 'discovery',list_ezyvet_prescription_review_candidates((select id from fx where k='pet'));
select is(jsonb_array_length((select v->'candidates' from data where k='discovery')),1,'Non-admin DVM discovers another actor scoped intake only');
select is((select v#>>'{candidates,0,id}' from data where k='discovery'),(select id::text from fx where k='run'),'Discovery returns exact scoped item-run identity');
select is((select v#>>'{candidates,0,item_count}' from data where k='discovery'),'1','Candidate reports observed item count');
select is(jsonb_array_length(list_ezyvet_prescription_review_candidates(gen_random_uuid())->'candidates'),0,'Candidate discovery stays patient scoped');
select throws_ok($$select list_ezyvet_prescription_review_candidates((select id from fx where k='pet'),now(),null,20)$$,'23514',null,'Partial discovery cursor rejected');
select throws_ok($$select list_ezyvet_prescription_review_candidates((select id from fx where k='pet'),null,null,51)$$,'23514',null,'Unbounded discovery request rejected');
insert into data select 'preview',get_ezyvet_prescription_review_candidate((select id from fx where k='pet'),(select id from fx where k='run'));
select is((select v->>'eligible_for_review' from data where k='preview'),'true','Current scoped run may enter clinical interpretation');
select is((select v#>>'{source_context,reconciliation,status}' from data where k='preview'),'unresolved','Eligibility to interpret does not claim source completeness');
select is((select v#>>'{source_context,items,0,original,instructions}' from data where k='preview'),'<script>outside prose</script>','Preview retains exact untrusted source text');
select ok((select (v->>'patient_version')::integer>0 from data where k='preview'),'Preview supplies current patient version for preparation');
select throws_ok($$select get_ezyvet_prescription_review_candidate(gen_random_uuid(),(select id from fx where k='run'))$$,'42501',null,'Wrong patient cannot inspect run');
select throws_ok($$select get_ezyvet_prescription_review_candidate((select id from fx where k='pet'),(select id from fx where k='legacy'))$$,'42501',null,'Legacy generic snapshot cannot become review candidate');
reset role;
update ezyvet_identity_heads set version=version+2 where resource='prescriptionitem' and external_id='501';
set local role authenticated;
insert into data select 'stale-preview',get_ezyvet_prescription_review_candidate((select id from fx where k='pet'),(select id from fx where k='run'));
select is((select v->>'eligible_for_review' from data where k='stale-preview'),'false','Changed observation revision disables new review');
select is((select v->>'unavailable_reason' from data where k='stale-preview'),'SOURCE_CONTEXT_CHANGED','Stale eligibility failure is explicit');
select is((select v#>>'{source_context,items,0,original,qty}' from data where k='stale-preview'),'outside units','Stale run remains inspectable without rewriting quantity');
select is((select v#>>'{source_context,consult,status}' from data where k='stale-preview'),'not_checked','Fallback never claims a validated consult');
reset role;

insert into fx values('unresolved-run',gen_random_uuid());
select set_config('request.jwt.claims','{"sub":"db560000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into data select 'unresolved-parent',c from jsonb_array_elements(list_ezyvet_prescription_candidates((select id from fx where k='mapping'),'prescription')->'candidates') c where c->>'external_id'='102';
update ezyvet_import_runs set retry_after=null,lease_until=null;
insert into data select 'unresolved-claim',claim_ezyvet_prescriptionitem_import((select id from fx where k='unresolved-run'),'db560000-0000-4000-8000-000000000001','prescriptionitem-test-site','prescriptionitem','https://api.trial.ezyvet.com',(select id from fx where k='mapping'),(select (v->>'id')::uuid from data where k='unresolved-parent'),(select v->>'payload_hash' from data where k='unresolved-parent'),(select (v->>'observed_head_version')::integer from data where k='unresolved-parent'));
select stage_ezyvet_import_page((select id from fx where k='unresolved-run'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='unresolved-claim'),1,true,'[]');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"db560000-0000-4000-8000-000000000002","role":"authenticated"}',true);
insert into data select 'unresolved-preview',get_ezyvet_prescription_review_candidate((select id from fx where k='pet'),(select id from fx where k='unresolved-run'));
select is((select v->>'eligible_for_review' from data where k='unresolved-preview'),'false','Unresolved nonempty consult disables interpretation');
select is((select v->>'unavailable_reason' from data where k='unresolved-preview'),'SOURCE_CONSULT_UNRESOLVED','Missing consultation has specific visible reason');
select is((select v#>>'{source_context,consult,reference}' from data where k='unresolved-preview'),'999','Unresolved source consult identity stays inspectable');
insert into data select 'first-page',list_ezyvet_prescription_review_candidates((select id from fx where k='pet'),null,null,1);
select is((select v->>'has_more' from data where k='first-page'),'true','Candidate pagination reports remaining scoped run');
insert into data select 'next-page',list_ezyvet_prescription_review_candidates((select id from fx where k='pet'),(select (v#>>'{next_cursor,before_at}')::timestamptz from data where k='first-page'),(select (v#>>'{next_cursor,before_id}')::uuid from data where k='first-page'),1);
select ok((select v#>>'{candidates,0,id}' from data where k='first-page')<>(select v#>>'{candidates,0,id}' from data where k='next-page') and (select v->>'has_more' from data where k='next-page')='false','Cursor visits each saved run once');
reset role;
select ok(not has_function_privilege('anon','get_ezyvet_prescription_review_candidate(uuid,uuid)','EXECUTE'),'Anonymous candidate inspection denied');
select ok(not has_function_privilege('service_role','get_ezyvet_prescription_review_candidate(uuid,uuid)','EXECUTE'),'Service cannot impersonate DVM candidate inspection');
delete from user_roles where user_id='db560000-0000-4000-8000-000000000002' and role='DVM';
set local role authenticated;
select throws_ok($$select get_ezyvet_prescription_review_candidate((select id from fx where k='pet'),(select id from fx where k='run'))$$,'42501',null,'Role loss blocks stale as well as current previews');
select * from finish();rollback;
