begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select no_plan();
-- FIXTURE_BEGIN


insert into auth.users(id,email,raw_user_meta_data) values('db710000-0000-4000-8000-000000000001','attachment-admin@example.test','{}'),('db710000-0000-4000-8000-000000000002','attachment-other@example.test','{}');
insert into user_roles(user_id,role) values('db710000-0000-4000-8000-000000000001','ADMIN'),('db710000-0000-4000-8000-000000000002','ADMIN');
create temp table fx(k text primary key,id uuid);create temp table data(k text primary key,v jsonb);grant all on fx,data to authenticated,service_role;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db710000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'client',id from save_client(auth.uid(),null,null,'Attachment','Owner','+13035550196','attachment@example.test','EMAIL',null,null);
insert into fx select 'pet',id from save_patient(null,(select id from fx where k='client'),null,'Metadata dog','Dog',null,null,'unknown',null,'unknown','unknown',null,null,null);
insert into fx select k,gen_random_uuid() from unnest(array['mapping','animal-run','run','run2','other-run']) k;
reset role;
insert into data select 'animal',to_jsonb(claim_ezyvet_import((select id from fx where k='animal-run'),'db710000-0000-4000-8000-000000000001','attachment-test-site','animal','https://api.trial.ezyvet.com'));
select stage_ezyvet_import_page((select id from fx where k='animal-run'),'db710000-0000-4000-8000-000000000001',(select(v->>'lease_id')::uuid from data where k='animal'),1,true,'[{"external_id":"77","payload":{"id":77}}]');
insert into ezyvet_record_links(id,request_id,request_hash,source_origin,source_site_uid,resource,external_id,snapshot_id,head_version,client_id,pet_id,local_version,action,reason,approved_by)
select (select id from fx where k='mapping'),gen_random_uuid(),'synthetic-approved-mapping',s.source_origin,s.source_site_uid,s.resource,s.external_id,s.id,h.version,(select id from fx where k='client'),(select id from fx where k='pet'),1,'link','Synthetic reviewed mapping','db710000-0000-4000-8000-000000000001' from ezyvet_import_snapshots s join ezyvet_identity_heads h on h.snapshot_id=s.id where s.resource='animal' and s.source_site_uid='attachment-test-site';
insert into data values('observation',jsonb_build_object('external_id','701','file_id','42','metadata',jsonb_build_object('id','701','file_id','42','record_type','Animal','record_id','77','name','Synthetic report','mime_type','application/pdf','notes',null),'raw_record_sha256',repeat('a',64),'stable_metadata_sha256',repeat('b',64),'file_sha256',null));
insert into data select 'page',jsonb_build_object('contract_version','ezyvet_animal_attachment_metadata_v1','parent',jsonb_build_object('record_type','Animal','record_id','77'),'page',1,'complete',true,'pagination',jsonb_build_object('items_page',1,'items_page_total',1,'items_page_size',10,'items_total',2),'observations',jsonb_build_array(v,jsonb_set(v,'{raw_record_sha256}',to_jsonb(repeat('c',64)))),'page_sha256',repeat('d',64)) from data where k='observation';
insert into data values('side-effects',jsonb_build_object('treatments',(select count(*) from patient_treatments),'invoices',(select count(*) from billing_invoices),'stock',(select count(*) from inventory_movements),'outbox',(select count(*) from communication_outbox),'objects',(select count(*) from storage.objects)));

insert into data select 'run',claim_ezyvet_attachment_import((select id from fx where k='run'),'db710000-0000-4000-8000-000000000001','attachment-test-site','https://api.trial.ezyvet.com',(select id from fx where k='mapping'));
select stage_ezyvet_attachment_page((select id from fx where k='run'),'db710000-0000-4000-8000-000000000001',(select(v->>'lease_id')::uuid from data where k='run'),(select v from data where k='page'));
update ezyvet_import_runs set retry_after=null where resource='attachment';
insert into fx select k,gen_random_uuid() from unnest(array['capture','capture2','capture3','capture4']) k;
insert into fx select 'attachment-snapshot',snapshot_id from ezyvet_attachment_page_observations where run_id=(select id from fx where k='run') and ordinal=1;
insert into auth.users(id,email,raw_user_meta_data) values('db710000-0000-4000-8000-000000000003','original-dvm@example.test','{}'),('db710000-0000-4000-8000-000000000004','original-staff@example.test','{}');
insert into user_roles(user_id,role) values('db710000-0000-4000-8000-000000000003','DVM'),('db710000-0000-4000-8000-000000000004','STAFF') on conflict do nothing;
insert into fx select k,gen_random_uuid() from unnest(array['approve','approve2','approve3','ack','withdraw','abandon','ack-abandon','withdraw-abandon']) k;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db710000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select prepare_ezyvet_attachment_capture((select id from fx where k='capture'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,1,(select id from fx where k='attachment-snapshot'),1,repeat('b',64));
reset role;set local role service_role;
insert into data select 'claim1',claim_ezyvet_attachment_capture((select id from fx where k='capture'),'db710000-0000-4000-8000-000000000001');
insert into data select 'reserve1',reserve_ezyvet_attachment_original((select id from fx where k='capture'),'db710000-0000-4000-8000-000000000001',(select v#>>'{lease_id}' from data where k='claim1')::uuid,repeat('e',64),'application/pdf',12,repeat('a',64),repeat('c',64));
reset role;
insert into storage.objects(bucket_id,name,metadata) values('ezyvet-attachment-originals',(select v#>>'{intent,object_path}' from data where k='reserve1'),'{"size":12,"mimetype":"application/pdf"}');
set local role service_role;
insert into data select 'ready1',complete_ezyvet_attachment_capture((select id from fx where k='capture'),'db710000-0000-4000-8000-000000000001',(select v#>>'{lease_id}' from data where k='claim1')::uuid,(select v#>>'{intent,id}' from data where k='reserve1')::uuid,repeat('e',64),'application/pdf',12);
reset role;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db710000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select prepare_ezyvet_attachment_capture((select id from fx where k='capture2'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,1,(select id from fx where k='attachment-snapshot'),1,repeat('b',64));
reset role;set local role service_role;
insert into data select 'claim2',claim_ezyvet_attachment_capture((select id from fx where k='capture2'),'db710000-0000-4000-8000-000000000001');
insert into data select 'reserve2',reserve_ezyvet_attachment_original((select id from fx where k='capture2'),'db710000-0000-4000-8000-000000000001',(select v#>>'{lease_id}' from data where k='claim2')::uuid,repeat('e',64),'application/pdf',12,repeat('a',64),repeat('c',64));
reset role;
insert into storage.objects(bucket_id,name,metadata) values('ezyvet-attachment-originals',(select v#>>'{intent,object_path}' from data where k='reserve2'),'{"size":12,"mimetype":"application/pdf"}');
set local role service_role;
insert into data select 'ready2',complete_ezyvet_attachment_capture((select id from fx where k='capture2'),'db710000-0000-4000-8000-000000000001',(select v#>>'{lease_id}' from data where k='claim2')::uuid,(select v#>>'{intent,id}' from data where k='reserve2')::uuid,repeat('e',64),'application/pdf',12);
reset role;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db710000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select prepare_ezyvet_attachment_capture((select id from fx where k='capture3'),(select id from fx where k='mapping'),(select id from fx where k='run'),1,1,(select id from fx where k='attachment-snapshot'),1,repeat('b',64));
reset role;set local role service_role;
insert into data select 'claim3',claim_ezyvet_attachment_capture((select id from fx where k='capture3'),'db710000-0000-4000-8000-000000000001');
insert into data select 'reserve3',reserve_ezyvet_attachment_original((select id from fx where k='capture3'),'db710000-0000-4000-8000-000000000001',(select v#>>'{lease_id}' from data where k='claim3')::uuid,repeat('e',64),'application/pdf',12,repeat('a',64),repeat('c',64));
reset role;
insert into storage.objects(bucket_id,name,metadata) values('ezyvet-attachment-originals',(select v#>>'{intent,object_path}' from data where k='reserve3'),'{"size":12,"mimetype":"application/pdf"}');
set local role service_role;
insert into data select 'ready3',complete_ezyvet_attachment_capture((select id from fx where k='capture3'),'db710000-0000-4000-8000-000000000001',(select v#>>'{lease_id}' from data where k='claim3')::uuid,(select v#>>'{intent,id}' from data where k='reserve3')::uuid,repeat('e',64),'application/pdf',12);
reset role;
-- FIXTURE_END
reset role;set local role authenticated;select set_config('request.jwt.claims','{"sub":"db710000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select is(jsonb_array_length(list_ezyvet_attachment_original_candidates((select id from fx where k='pet'))->'candidates'),3,'Owned ready capture discovery');
select is((list_ezyvet_attachment_original_candidates((select id from fx where k='pet'),null,null,1)->>'has_more')::boolean,true,'Candidate page bounded');
select throws_ok($$select approve_ezyvet_attachment_original((select id from fx where k='approve'),(select id from fx where k='pet'),(select v#>>'{request,capture,id}' from data where k='ready1')::uuid,(select v#>>'{request,capture,capture_hash}' from data where k='ready1'),99,null,'Reviewed exact original',true)$$,'40001',null,'Wrong patient version cannot admit');
select throws_ok($$select approve_ezyvet_attachment_original((select id from fx where k='approve'),(select id from fx where k='pet'),(select v#>>'{request,capture,id}' from data where k='ready1')::uuid,(select v#>>'{request,capture,capture_hash}' from data where k='ready1'),1,null,null,true)$$,'23514',null,'Null reason rejected');
select throws_ok($$select approve_ezyvet_attachment_original((select id from fx where k='approve'),(select id from fx where k='pet'),(select v#>>'{request,capture,id}' from data where k='ready1')::uuid,(select v#>>'{request,capture,capture_hash}' from data where k='ready1'),1,null,'Reviewed exact original',null)$$,'23514',null,'Null attestation rejected');
reset role;set local role authenticated;select set_config('request.jwt.claims','{"sub":"db710000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select throws_ok($$select approve_ezyvet_attachment_original((select id from fx where k='approve'),(select id from fx where k='pet'),(select v#>>'{request,capture,id}' from data where k='ready1')::uuid,(select v#>>'{request,capture,capture_hash}' from data where k='ready1'),1,null,'Reviewed exact original',true)$$,'42501',null,'Another admin cannot admit owned capture');
reset role;set local role authenticated;select set_config('request.jwt.claims','{"sub":"db710000-0000-4000-8000-000000000004","role":"authenticated"}',true);
select throws_ok($$select approve_ezyvet_attachment_original((select id from fx where k='approve'),(select id from fx where k='pet'),(select v#>>'{request,capture,id}' from data where k='ready1')::uuid,(select v#>>'{request,capture,capture_hash}' from data where k='ready1'),1,null,'Reviewed exact original',true)$$,'42501',null,'Staff cannot approve');
reset role;set local role authenticated;select set_config('request.jwt.claims','{"sub":"db710000-0000-4000-8000-000000000001","role":"authenticated"}',true);
reset role;update ezyvet_identity_heads set version=version+1 where resource in('animal','attachment');
reset role;set local role authenticated;select set_config('request.jwt.claims','{"sub":"db710000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into data select 'approved',approve_ezyvet_attachment_original((select id from fx where k='approve'),(select id from fx where k='pet'),(select v#>>'{request,capture,id}' from data where k='ready1')::uuid,(select v#>>'{request,capture,capture_hash}' from data where k='ready1'),1,null,'Reviewed exact original',true);
select is((select v#>>'{record,entry_method}' from data where k='approved'),'staff_reviewed_ezyvet_api_attachment_v1','API lineage distinguished from manual export');
select is((select v#>>'{record,source_current_at_review}' from data where k='approved'),'false','Historical source head explicitly frozen stale');
select is(approve_ezyvet_attachment_original((select id from fx where k='approve'),(select id from fx where k='pet'),(select v#>>'{request,capture,id}' from data where k='ready1')::uuid,(select v#>>'{request,capture,capture_hash}' from data where k='ready1'),1,null,'Reviewed exact original',true),(select v from data where k='approved'),'Exact approval reply is stable');
select throws_ok($$select approve_ezyvet_attachment_original((select id from fx where k='approve2'),(select id from fx where k='pet'),(select v#>>'{request,capture,id}' from data where k='ready1')::uuid,(select v#>>'{request,capture,capture_hash}' from data where k='ready1'),1,(select v#>>'{record,id}' from data where k='approved')::uuid,'Reviewed exact original',true)$$,'23505',null,'Same capture cannot be admitted twice');
select throws_ok($$select approve_ezyvet_attachment_original((select id from fx where k='approve2'),(select id from fx where k='pet'),(select v#>>'{request,capture,id}' from data where k='ready2')::uuid,(select v#>>'{request,capture,capture_hash}' from data where k='ready2'),1,null,'Reviewed exact original',true)$$,'40001',null,'Replacement requires exact previous record');
select is(recover_ezyvet_attachment_review_action((select id from fx where k='approve'),(select id from fx where k='pet')),(select v from data where k='approved'),'Owned action recovery independent history');
reset role;set local role authenticated;select set_config('request.jwt.claims','{"sub":"db710000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select is(recover_ezyvet_attachment_review_action((select id from fx where k='approve'),(select id from fx where k='pet')),null::jsonb,'Other administrator cannot recover action');
reset role;set local role authenticated;select set_config('request.jwt.claims','{"sub":"db710000-0000-4000-8000-000000000004","role":"authenticated"}',true);
select is(jsonb_array_length(read_ezyvet_attachment_original_history((select id from fx where k='pet'))->'records'),1,'Active staff sees admitted metadata');
select throws_ok($$select acknowledge_ezyvet_attachment_original((select id from fx where k='ack'),(select id from fx where k='pet'),(select v#>>'{record,id}' from data where k='approved')::uuid,(select v#>>'{record,record_hash}' from data where k='approved'),(select v#>>'{record,capture_hash}' from data where k='approved'),true)$$,'42501',null,'Non-DVM cannot acknowledge');
reset role;set local role service_role;
select throws_ok($$select get_ezyvet_attachment_original_review_context((select v#>>'{record,id}' from data where k='approved')::uuid,(select id from fx where k='pet'),'db710000-0000-4000-8000-000000000001')$$,'42501',null,'Admin without DVM cannot download clinical original');
select is(get_ezyvet_attachment_original_review_context((select v#>>'{record,id}' from data where k='approved')::uuid,(select id from fx where k='pet'),'db710000-0000-4000-8000-000000000003')#>>'{original,content_sha256}',repeat('e',64),'DVM obtains verified private original context');
select throws_ok($$select get_ezyvet_attachment_original_review_context((select v#>>'{request,capture,id}' from data where k='ready2')::uuid,(select id from fx where k='pet'),'db710000-0000-4000-8000-000000000003')$$,'42501',null,'Unapproved capture ID cannot substitute admitted record');
reset role;set local role authenticated;select set_config('request.jwt.claims','{"sub":"db710000-0000-4000-8000-000000000003","role":"authenticated"}',true);
insert into data select 'acknowledged',acknowledge_ezyvet_attachment_original((select id from fx where k='ack'),(select id from fx where k='pet'),(select v#>>'{record,id}' from data where k='approved')::uuid,(select v#>>'{record,record_hash}' from data where k='approved'),(select v#>>'{record,capture_hash}' from data where k='approved'),true);
select is(acknowledge_ezyvet_attachment_original((select id from fx where k='ack'),(select id from fx where k='pet'),(select v#>>'{record,id}' from data where k='approved')::uuid,(select v#>>'{record,record_hash}' from data where k='approved'),(select v#>>'{record,capture_hash}' from data where k='approved'),true),(select v from data where k='acknowledged'),'Exact acknowledgment idempotent');
select throws_ok($$select acknowledge_ezyvet_attachment_original((select id from fx where k='ack-abandon'),(select id from fx where k='pet'),(select v#>>'{record,id}' from data where k='approved')::uuid,(select v#>>'{record,record_hash}' from data where k='approved'),(select v#>>'{record,capture_hash}' from data where k='approved'),true)$$,'23505',null,'Different action cannot duplicate same DVM acknowledgment');
reset role;set local role authenticated;select set_config('request.jwt.claims','{"sub":"db710000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into data select 'withdrawn',withdraw_ezyvet_attachment_original((select id from fx where k='withdraw'),(select id from fx where k='pet'),(select v#>>'{record,id}' from data where k='approved')::uuid,(select v#>>'{record,record_hash}' from data where k='approved'),'Incorrect admission; preserve history');
select is(withdraw_ezyvet_attachment_original((select id from fx where k='withdraw'),(select id from fx where k='pet'),(select v#>>'{record,id}' from data where k='approved')::uuid,(select v#>>'{record,record_hash}' from data where k='approved'),'Incorrect admission; preserve history'),(select v from data where k='withdrawn'),'Exact withdrawal idempotent');
reset role;set local role authenticated;select set_config('request.jwt.claims','{"sub":"db710000-0000-4000-8000-000000000003","role":"authenticated"}',true);
select is(acknowledge_ezyvet_attachment_original((select id from fx where k='ack'),(select id from fx where k='pet'),(select v#>>'{record,id}' from data where k='approved')::uuid,(select v#>>'{record,record_hash}' from data where k='approved'),(select v#>>'{record,capture_hash}' from data where k='approved'),true),(select v from data where k='acknowledged'),'Acknowledgment recovery survives withdrawal');
select throws_ok($$select acknowledge_ezyvet_attachment_original((select id from fx where k='ack-abandon'),(select id from fx where k='pet'),(select v#>>'{record,id}' from data where k='approved')::uuid,(select v#>>'{record,record_hash}' from data where k='approved'),(select v#>>'{record,capture_hash}' from data where k='approved'),true)$$,'40001',null,'Withdrawn record denies new acknowledgment');
reset role;set local role service_role;
select lives_ok($$select get_ezyvet_attachment_original_review_context((select v#>>'{record,id}' from data where k='approved')::uuid,(select id from fx where k='pet'),'db710000-0000-4000-8000-000000000003')$$,'Withdrawn historical original remains DVM evidence');
reset role;set local role authenticated;select set_config('request.jwt.claims','{"sub":"db710000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into data select 'replacement',approve_ezyvet_attachment_original((select id from fx where k='approve2'),(select id from fx where k='pet'),(select v#>>'{request,capture,id}' from data where k='ready2')::uuid,(select v#>>'{request,capture,capture_hash}' from data where k='ready2'),1,(select v#>>'{record,id}' from data where k='approved')::uuid,'Reviewed exact original',true);
select is((select v#>>'{record,version}' from data where k='replacement'),'2','Replacement appends version');
select is((select v#>>'{record,previous_record_id}' from data where k='replacement'),(select v#>>'{record,id}' from data where k='approved'),'Replacement links explicit previous');
select throws_ok($$select withdraw_ezyvet_attachment_original((select id from fx where k='withdraw-abandon'),(select id from fx where k='pet'),(select v#>>'{record,id}' from data where k='approved')::uuid,(select v#>>'{record,record_hash}' from data where k='approved'),'Incorrect admission; preserve history')$$,'40001',null,'Cannot withdraw superseded head');
select is(jsonb_array_length(read_ezyvet_attachment_original_history((select id from fx where k='pet'),null,null,1)->'records'),1,'History page bounded');
select is((read_ezyvet_attachment_original_history((select id from fx where k='pet'),null,null,1)->>'has_more')::boolean,true,'Older page remains discoverable');
select is(recover_ezyvet_attachment_review_action((select id from fx where k='approve'),(select id from fx where k='pet')),(select v from data where k='approved'),'Original approval recovery after off-page replacement');
select is(abandon_ezyvet_attachment_original_approval((select id from fx where k='abandon'),(select id from fx where k='pet'),(select v#>>'{request,capture,id}' from data where k='ready3')::uuid,(select v#>>'{request,capture,capture_hash}' from data where k='ready3'),999,null,'Reviewed exact original',true)->>'status','abandoned','Scoped abandonment ignores mutable patient version');
select is(approve_ezyvet_attachment_original((select id from fx where k='abandon'),(select id from fx where k='pet'),(select v#>>'{request,capture,id}' from data where k='ready3')::uuid,(select v#>>'{request,capture,capture_hash}' from data where k='ready3'),999,null,'Reviewed exact original',true)->>'status','abandoned','Delayed approval cannot cross tombstone');
reset role;set local role authenticated;select set_config('request.jwt.claims','{"sub":"db710000-0000-4000-8000-000000000003","role":"authenticated"}',true);
select is(abandon_ezyvet_attachment_original_acknowledgment((select id from fx where k='ack-abandon'),(select id from fx where k='pet'),(select v#>>'{record,id}' from data where k='approved')::uuid,(select v#>>'{record,record_hash}' from data where k='approved'),(select v#>>'{record,capture_hash}' from data where k='approved'),true)->>'status','abandoned','Superseded acknowledgment intent can be abandoned');
select is(acknowledge_ezyvet_attachment_original((select id from fx where k='ack-abandon'),(select id from fx where k='pet'),(select v#>>'{record,id}' from data where k='approved')::uuid,(select v#>>'{record,record_hash}' from data where k='approved'),(select v#>>'{record,capture_hash}' from data where k='approved'),true)->>'status','abandoned','Delayed acknowledgment is fenced');
reset role;set local role authenticated;select set_config('request.jwt.claims','{"sub":"db710000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select is(abandon_ezyvet_attachment_original_withdrawal((select id from fx where k='withdraw-abandon'),(select id from fx where k='pet'),(select v#>>'{record,id}' from data where k='approved')::uuid,(select v#>>'{record,record_hash}' from data where k='approved'),'Incorrect admission; preserve history')->>'status','abandoned','Superseded withdrawal intent can be abandoned');
select is(withdraw_ezyvet_attachment_original((select id from fx where k='withdraw-abandon'),(select id from fx where k='pet'),(select v#>>'{record,id}' from data where k='approved')::uuid,(select v#>>'{record,record_hash}' from data where k='approved'),'Incorrect admission; preserve history')->>'status','abandoned','Delayed withdrawal is fenced');
reset role;
select throws_ok($$update ezyvet_attachment_review_records set review_reason='overwrite'$$,'23514',null,'Admitted records immutable');
select throws_ok($$delete from ezyvet_attachment_review_actions$$,'23514',null,'Action receipts immutable');
select ok(not has_table_privilege('authenticated','ezyvet_attachment_review_actions','select'),'No direct actions read grant');
select ok(not has_table_privilege('authenticated','ezyvet_attachment_review_records','select'),'No direct records read grant');
select ok(not has_table_privilege('authenticated','ezyvet_attachment_review_acknowledgments','select'),'No direct acknowledgments read grant');
select ok(not has_table_privilege('authenticated','ezyvet_attachment_review_withdrawals','select'),'No direct withdrawals read grant');
select ok(not has_function_privilege('authenticated','get_ezyvet_attachment_original_review_context(uuid,uuid,uuid)','execute'),'Private context is service only');
select ok(not has_function_privilege('service_role','ezyvet_attachment_review_original(uuid)','execute'),'Private original helper revoked');
select ok(not exists(select 1 from patient_documents),'No native document promotion');
select ok(not exists(select 1 from external_record_versions),'No manual export provenance forged');
select ok(not exists(select 1 from record_release_sources),'No release inclusion');
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db710000-0000-4000-8000-000000000004","role":"authenticated"}',true);
select is(jsonb_array_length(list_record_release_sources_v8((select id from fx where k='pet'))->'document_ids'),0,'Current release candidates exclude API originals');
select is(jsonb_array_length(select_all_record_release_sources_v8((select id from fx where k='pet'))#>'{selection,external_record_ids}'),0,'Select-all does not mislabel API originals as manual exports');
select throws_ok($$select preview_record_release_v8((select id from fx where k='pet'),(select id from fx where k='client'),'EMAIL','attachment@example.test',jsonb_build_object('document_ids',jsonb_build_array((select v#>>'{record,id}' from data where k='approved'))))$$,'23514',null,'API chart record ID cannot substitute a release document');
reset role;
select * from finish();rollback;
