begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select no_plan();
-- FIXTURE_BEGIN: synthetic scoped outside history and local actors.
insert into auth.users(id,email,raw_user_meta_data) values('db490000-0000-4000-8000-000000000001','clinical-import-admin@example.test','{}'),('db490000-0000-4000-8000-000000000002','clinical-import-other@example.test','{}');
update public.profiles set is_active = true where id in ('db490000-0000-4000-8000-000000000001','db490000-0000-4000-8000-000000000002');
insert into public.user_roles (user_id, role) values ('db490000-0000-4000-8000-000000000001','STAFF'),('db490000-0000-4000-8000-000000000002','STAFF');

insert into user_roles(user_id,role) values('db490000-0000-4000-8000-000000000001','ADMIN'),('db490000-0000-4000-8000-000000000002','DVM');
create temp table fx(k text primary key,id uuid);create temp table data(k text primary key,v jsonb);grant all on fx,data to authenticated,service_role;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db490000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'client',id from save_client(auth.uid(),null,null,'Clinical','Import','+13035550199','clinical-import@example.test','EMAIL',null,null);
insert into fx select 'pet',id from save_patient(null,(select id from fx where k='client'),null,'Scoped dog','Dog',null,null,'unknown',null,'unknown','unknown',null,null,null);
insert into fx select k,gen_random_uuid() from unnest(array['mapping','mapping2','snapshot','snapshot2','legacy','terminal','run','history','other-run']) k;
reset role;
insert into ezyvet_import_snapshots(id,source_origin,source_site_uid,resource,external_id,payload,payload_hash,first_seen_by) select id,'https://api.trial.ezyvet.com','clinical-test-site','animal',case when k='snapshot' then '77' else '88' end,jsonb_build_object('id',case when k='snapshot' then 77 else 88 end),k,'db490000-0000-4000-8000-000000000001' from fx where k in ('snapshot','snapshot2');
insert into ezyvet_record_links(id,request_id,request_hash,source_origin,source_site_uid,resource,external_id,snapshot_id,head_version,client_id,pet_id,local_version,action,reason,approved_by)
select id,gen_random_uuid(),k,'https://api.trial.ezyvet.com','clinical-test-site','animal',case when k='mapping' then '77' else '88' end,(select id from fx where k=case when m.k='mapping' then 'snapshot' else 'snapshot2' end),1,(select id from fx where k='client'),(select id from fx where k='pet'),1,'link','Synthetic approved mapping','db490000-0000-4000-8000-000000000001' from fx m where k in ('mapping','mapping2');
insert into data values('items','[{"external_id":"101","payload":{"id":101,"animal_id":77,"comments":"<script>outside prose</script>","vet_id":"outside-user","history_system":"opaque"}}]');
insert into fx select k,gen_random_uuid() from unnest(array['source-approval','extraction','linked','tombstone','second-extraction','later-source','discrepancy','release']) k;
set local role service_role;
insert into data select 'run',claim_ezyvet_clinical_import((select id from fx where k='run'),'db490000-0000-4000-8000-000000000001','clinical-test-site','history','https://api.trial.ezyvet.com',(select id from fx where k='mapping'));
select stage_ezyvet_import_page((select id from fx where k='run'),'db490000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='run'),1,true,(select v from data where k='items'));
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db490000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into data select 'candidate',list_ezyvet_clinical_candidates((select id from fx where k='mapping'),'history')#>'{candidates,0}';
insert into data select 'source-payload',jsonb_build_object('animal_link_id',(select id from fx where k='mapping'),'snapshot_id',v->'id','payload_hash',v->'payload_hash','observed_head_version',v->'head_version','patient_version',1,'consult_mode','not_referenced','consult_snapshot_id',null,'consult_payload_hash',null,'consult_head_version',null,'reason','PRIVATE administrator source review') from data where k='candidate';
insert into data select 'prepared-source',prepare_ezyvet_history_approval((select id from fx where k='source-approval'),(select id from fx where k='pet'),(select v from data where k='source-payload'));
insert into data select 'source-receipt',approve_ezyvet_history((select id from fx where k='source-approval'),(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='prepared-source'),true);
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db490000-0000-4000-8000-000000000002","role":"authenticated"}',true);
insert into data select 'extraction-payload',jsonb_build_object('sources',jsonb_build_array(jsonb_build_object('id',v#>'{receipt,id}','version_hash',v#>'{receipt,version_hash}')),'patient_version',1,'action','create','problem_id',null,'problem_version',null,'fields',jsonb_build_object('title','Reviewed vaccine reaction','notes','DVM-authored reviewed finding','onset_date',null,'status','active','importance','high'),'duplicate_decision','distinct_finding','reason','PRIVATE DVM duplicate review') from data where k='source-receipt';
insert into data select 'prepared-extraction',prepare_ezyvet_problem_extraction((select id from fx where k='extraction'),(select id from fx where k='pet'),(select v from data where k='extraction-payload'));
insert into data select 'extraction-receipt',approve_ezyvet_problem_extraction((select id from fx where k='extraction'),(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='prepared-extraction'),true);
insert into fx select 'problem',(v#>>'{receipt,problem_id}')::uuid from data where k='extraction-receipt';
-- FIXTURE_END
select is((select v#>>'{receipt,problem_fields,importance}' from data where k='extraction-receipt'),'high','Explicit DVM importance preserved');
select is((select v#>>'{receipt,problem_fields,onset_date}' from data where k='extraction-receipt'),null,'Unknown onset remains null');
select ok(not (select v->'receipt' from data where k='extraction-receipt')::text like '%PRIVATE%','Private review reasons excluded from clinical projection');
select is(jsonb_array_length(list_patient_imported_histories((select id from fx where k='pet'))->'histories'),1,'Approved history visible to DVM without staging grant');
select is((select count(*)::integer from patient_problems where pet_id=(select id from fx where k='pet')),1,'One native problem created atomically');
select is(approve_ezyvet_problem_extraction((select id from fx where k='extraction'),(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='prepared-extraction'),true)#>>'{receipt,problem_id}',(select id::text from fx where k='problem'),'Exact committed approval retry reuses target');
select throws_ok($$select approve_ezyvet_problem_extraction((select id from fx where k='extraction'),(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='prepared-extraction'),null)$$,'23514',null,'Null attestation denied');
select throws_ok($$select prepare_ezyvet_problem_extraction(gen_random_uuid(),(select id from fx where k='pet'),(select jsonb_set(v,'{fields,onset_date}','"yesterday"') from data where k='extraction-payload'))$$,'23514',null,'Relative onset literals cannot change between preparation and approval');
select throws_ok($$select prepare_ezyvet_history_approval(gen_random_uuid(),(select id from fx where k='pet'),(select v from data where k='source-payload'))$$,'42501',null,'DVM alone cannot approve raw source history');
select throws_ok($$select prepare_ezyvet_problem_extraction((select id from fx where k='extraction'),(select id from fx where k='pet'),(select v||'{"reason":"Changed exact request"}' from data where k='extraction-payload'))$$,'42501',null,'Changed exact extraction retry denied');
select is(recover_ezyvet_history_request((select id from fx where k='extraction'),(select id from fx where k='pet'),'problem_extraction')#>>'{request,review_context,histories,0,original,comments}','<script>outside prose</script>','Pointer-loss recovery retains exact approved source context');
select is(abandon_ezyvet_history_request((select id from fx where k='tombstone'),(select id from fx where k='pet'),'problem_extraction',true)#>>'{request,status}','abandoned','Identity-only unknown preparation abandonment is durable');
select throws_ok($$select prepare_ezyvet_problem_extraction((select id from fx where k='tombstone'),(select id from fx where k='pet'),(select v from data where k='extraction-payload'))$$,'42501',null,'Delayed preparation cannot revive abandoned UUID');
select is(abandon_ezyvet_history_request((select id from fx where k='extraction'),(select id from fx where k='pet'),'problem_extraction',true)#>>'{request,status}','approved','Late abandonment recovers already committed extraction');
select is(jsonb_array_length(list_ezyvet_history_requests((select id from fx where k='pet'),'problem_extraction')->'requests'),2,'Server discovery includes approved and pointerless abandoned requests');
insert into data select 'second-prepared',prepare_ezyvet_problem_extraction((select id from fx where k='second-extraction'),(select id from fx where k='pet'),(select jsonb_set(v,'{fields,title}','"Distinct reviewed finding"') from data where k='extraction-payload'));
insert into data select 'second-receipt',approve_ezyvet_problem_extraction((select id from fx where k='second-extraction'),(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='second-prepared'),true);
select isnt((select v#>>'{receipt,problem_id}' from data where k='second-receipt'),(select id::text from fx where k='problem'),'One history can support multiple distinct native problems');
insert into data select 'link-payload',v||jsonb_build_object('action','link','problem_id',(select id from fx where k='problem'),'problem_version',1,'duplicate_decision','link_existing') from data where k='extraction-payload';
select throws_ok($$select prepare_ezyvet_problem_extraction(gen_random_uuid(),(select id from fx where k='pet'),(select jsonb_set(v,'{fields,title}','"Unreviewed target rewrite"') from data where k='link-payload'))$$,'40001',null,'Link cannot change local fields');
insert into data select 'link-prepared',prepare_ezyvet_problem_extraction((select id from fx where k='linked'),(select id from fx where k='pet'),(select v from data where k='link-payload'));
select approve_ezyvet_problem_extraction((select id from fx where k='linked'),(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='link-prepared'),true);
select is((select version from patient_problems where id=(select id from fx where k='problem')),1,'Link preserves native target version');
select is((select title from patient_problems where id=(select id from fx where k='problem')),'Reviewed vaccine reaction','Link preserves native title');
select save_patient_problem((select id from fx where k='problem'),(select id from fx where k='pet'),1,'Later local review','Separately authored local edit',null,'active','high');
select is(read_patient_problem_import_provenance((select id from fx where k='pet'),array[(select id from fx where k='problem')])#>>'{0,extractions,0,locally_edited}','true','Later local edit disclosed independently');
select is(read_patient_problem_import_provenance((select id from fx where k='pet'),array[(select id from fx where k='problem')])#>>'{0,extractions,0,problem_fields,title}','Reviewed vaccine reaction','Immutable original extraction fields survive local edits');
select is(jsonb_array_length(read_patient_treatment_alerts((select id from fx where k='pet'))#>'{snapshot,important_problems}'),2,'Important findings remain in live treatment alert review');
reset role;
create function pg_temp.observe_source(p_resource text,p_mapping uuid,p_items jsonb) returns jsonb language plpgsql security definer set search_path=public as $$declare r jsonb;rid uuid:=gen_random_uuid();begin
 update ezyvet_import_runs set retry_after=null where source_site_uid='clinical-test-site' and resource=p_resource;
 r:=claim_ezyvet_clinical_import(rid,'db490000-0000-4000-8000-000000000001','clinical-test-site',p_resource,'https://api.trial.ezyvet.com',p_mapping);
 perform stage_ezyvet_import_page(rid,'db490000-0000-4000-8000-000000000001',(r->>'lease_id')::uuid,1,true,p_items);
 return r;
end $$;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db490000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select throws_ok($$select prepare_ezyvet_problem_extraction(gen_random_uuid(),(select id from fx where k='pet'),(select v from data where k='extraction-payload'))$$,'42501',null,'ADMIN alone cannot author a clinical extraction');
-- Same head can be independently reapproved, but one extraction may select only one version per identity.
insert into fx values('duplicate-source',gen_random_uuid());
insert into data select 'duplicate-prepared',prepare_ezyvet_history_approval((select id from fx where k='duplicate-source'),(select id from fx where k='pet'),(select v from data where k='source-payload'));
insert into data select 'duplicate-receipt',approve_ezyvet_history((select id from fx where k='duplicate-source'),(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='duplicate-prepared'),true);
select set_config('request.jwt.claims','{"sub":"db490000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select throws_ok($$select prepare_ezyvet_problem_extraction(gen_random_uuid(),(select id from fx where k='pet'),(select jsonb_set(v,'{sources}',v->'sources'||jsonb_build_array(jsonb_build_object('id',(select id from fx where k='duplicate-source'),'version_hash',(select v#>>'{receipt,version_hash}' from data where k='duplicate-receipt')))) from data where k='extraction-payload'))$$,'23514',null,'One extraction cannot duplicate the same source identity across approved versions');
select pg_temp.observe_source('history',(select id from fx where k='mapping'),'[{"external_id":"101","payload":{"id":101,"animal_id":77,"comments":"Corrected outside history B","active":false}}]');
select is(read_patient_problem_import_provenance((select id from fx where k='pet'),array[(select id from fx where k='problem')])#>>'{0,extractions,0,discrepancy,required}','true','Changed/inactive source creates discrepancy attention');
select is((select importance from patient_problems where id=(select id from fx where k='problem')),'high','Source changes do not erase important reactions');
select throws_ok($$select prepare_ezyvet_problem_extraction(gen_random_uuid(),(select id from fx where k='pet'),(select v from data where k='extraction-payload'))$$,'40001',null,'Stale approved source cannot create a fresh extraction');
select set_config('request.jwt.claims','{"sub":"db490000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into data select 'later-candidate',value from jsonb_array_elements(list_ezyvet_clinical_candidates((select id from fx where k='mapping'),'history')->'candidates') where value->>'is_current'='true';
insert into data select 'later-payload',(select v from data where k='source-payload')||jsonb_build_object('snapshot_id',v->'id','payload_hash',v->'payload_hash','observed_head_version',v->'head_version') from data where k='later-candidate';
insert into data select 'later-prepared',prepare_ezyvet_history_approval((select id from fx where k='later-source'),(select id from fx where k='pet'),(select v from data where k='later-payload'));
insert into data select 'later-receipt',approve_ezyvet_history((select id from fx where k='later-source'),(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='later-prepared'),true);
select set_config('request.jwt.claims','{"sub":"db490000-0000-4000-8000-000000000002","role":"authenticated"}',true);
insert into data select 'discrepancy-payload',jsonb_build_object('extraction_id',(select id from fx where k='extraction'),'reviewed_sources',jsonb_build_array(jsonb_build_object('original_history_id',(select id from fx where k='source-approval'),'reviewed_history_id',(select id from fx where k='later-source'),'version_hash',v#>'{receipt,version_hash}')),'reason','PRIVATE DVM reviewed updated outside evidence') from data where k='later-receipt';
insert into data select 'discrepancy-prepared',prepare_ezyvet_history_discrepancy((select id from fx where k='discrepancy'),(select id from fx where k='pet'),(select v from data where k='discrepancy-payload'));
select approve_ezyvet_history_discrepancy((select id from fx where k='discrepancy'),(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='discrepancy-prepared'),true);
select is(recover_ezyvet_history_request((select id from fx where k='extraction'),(select id from fx where k='pet'),'problem_extraction')#>>'{receipt,discrepancy,required}','false','Exact current approved discrepancy review clears attention');
select is(recover_ezyvet_history_request((select id from fx where k='extraction'),(select id from fx where k='pet'),'problem_extraction')#>>'{receipt,discrepancy,changed_from_original}','true','Discrepancy review retains changed-from-original distinction');
select is((select version from patient_problems where id=(select id from fx where k='problem')),2,'Discrepancy review does not edit native fields');
select pg_temp.observe_source('history',(select id from fx where k='mapping'),(select v from data where k='items'));
select is(recover_ezyvet_history_request((select id from fx where k='extraction'),(select id from fx where k='pet'),'problem_extraction')#>>'{receipt,discrepancy,required}','true','A→B→A creates new attention despite reused original snapshot');
select is(approve_ezyvet_problem_extraction((select id from fx where k='extraction'),(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='prepared-extraction'),true)#>>'{receipt,problem_id}',(select id::text from fx where k='problem'),'Committed recovery survives source reversion without creating another problem');
select throws_ok($$select prepare_ezyvet_problem_extraction(gen_random_uuid(),(select id from fx where k='pet'),(select jsonb_set(v,'{fields,onset_date}','"yesterday"') from data where k='extraction-payload'))$$,'40001',null,'Stale source still denied before clinical field approval');
-- Known wrong-patient consult evidence cannot be hidden behind an unresolved label.
select pg_temp.observe_source('consult',(select id from fx where k='mapping2'),'[{"external_id":"900","payload":{"id":900,"animal_id":88}}]');
select pg_temp.observe_source('history',(select id from fx where k='mapping'),'[{"external_id":"101","payload":{"id":101,"animal_id":77,"consult_id":900,"comments":"Outside consult relation"}}]');
select set_config('request.jwt.claims','{"sub":"db490000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into data select 'conflict-candidate',value from jsonb_array_elements(list_ezyvet_clinical_candidates((select id from fx where k='mapping'),'history')->'candidates') where value->>'is_current'='true';
insert into data select 'conflict-payload',(select v from data where k='source-payload')||jsonb_build_object('snapshot_id',v->'id','payload_hash',v->'payload_hash','observed_head_version',v->'head_version','consult_mode','unresolved') from data where k='conflict-candidate';
select throws_ok($$select prepare_ezyvet_history_approval(gen_random_uuid(),(select id from fx where k='pet'),(select v from data where k='conflict-payload'))$$,'23514','Known consult conflicts with patient identity','Unresolved cannot conceal known wrong-patient consult');
select pg_temp.observe_source('consult',(select id from fx where k='mapping'),'[{"external_id":"901","payload":{"id":901,"animal_id":77,"vet_id":"outside-ref"}}]');
select pg_temp.observe_source('history',(select id from fx where k='mapping'),'[{"external_id":"101","payload":{"id":101,"animal_id":77,"consult_id":901,"comments":"Verified outside consult relation","active":false,"timestamp":"unknown source date"}}]');
insert into data select 'verified-candidate',value from jsonb_array_elements(list_ezyvet_clinical_candidates((select id from fx where k='mapping'),'history')->'candidates') where value->>'is_current'='true';
insert into data select 'consult-candidate',value from jsonb_array_elements(list_ezyvet_clinical_candidates((select id from fx where k='mapping'),'consult')->'candidates') where value->>'external_id'='901';
insert into data select 'verified-payload',(select v from data where k='source-payload')||jsonb_build_object('snapshot_id',v->'id','payload_hash',v->'payload_hash','observed_head_version',v->'head_version','consult_mode','verified','consult_snapshot_id',(select v->'id' from data where k='consult-candidate'),'consult_payload_hash',(select v->'payload_hash' from data where k='consult-candidate'),'consult_head_version',(select v->'head_version' from data where k='consult-candidate')) from data where k='verified-candidate';
insert into fx select k,gen_random_uuid() from unnest(array['verified-source','inactive-extraction']) k;
insert into data select 'verified-prepared',prepare_ezyvet_history_approval((select id from fx where k='verified-source'),(select id from fx where k='pet'),(select v from data where k='verified-payload'));
insert into data select 'verified-receipt',approve_ezyvet_history((select id from fx where k='verified-source'),(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='verified-prepared'),true);
select is((select v#>>'{receipt,consult,status}' from data where k='verified-receipt'),'verified','Exact current scoped consult context frozen');
select is((select v#>>'{receipt,original,timestamp}' from data where k='verified-receipt'),'unknown source date','Unknown original date is not replaced by import time');
select set_config('request.jwt.claims','{"sub":"db490000-0000-4000-8000-000000000002","role":"authenticated"}',true);
insert into data select 'inactive-payload',(select v from data where k='extraction-payload')||jsonb_build_object('sources',jsonb_build_array(jsonb_build_object('id',v#>'{receipt,id}','version_hash',v#>'{receipt,version_hash}'))) from data where k='verified-receipt';
insert into data select 'inactive-prepared',prepare_ezyvet_problem_extraction((select id from fx where k='inactive-extraction'),(select id from fx where k='pet'),(select v from data where k='inactive-payload'));
insert into data select 'inactive-receipt',approve_ezyvet_problem_extraction((select id from fx where k='inactive-extraction'),(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='inactive-prepared'),true);
select is((select v#>>'{receipt,problem_fields,status}' from data where k='inactive-receipt'),'active','Inactive outside source does not imply resolved native problem');
select pg_temp.observe_source('consult',(select id from fx where k='mapping'),'[{"external_id":"901","payload":{"id":901,"animal_id":77,"vet_id":"updated-outside-ref"}}]');
select is(recover_ezyvet_history_request((select id from fx where k='inactive-extraction'),(select id from fx where k='pet'),'problem_extraction')#>>'{receipt,discrepancy,required}','true','Verified consult-only revision creates discrepancy without history hash change');
select ok(not has_table_privilege('authenticated','ezyvet_imported_histories','SELECT'),'Approved clinical projection does not grant raw table access');
select ok(not has_function_privilege('authenticated','ezyvet_approve_history_request(uuid,uuid,text,text,boolean)','EXECUTE'),'Private actor-dispatch approval helper inaccessible');
reset role;
select throws_ok($$delete from ezyvet_problem_history_sources$$,'23514',null,'Clinical source association is append-only');
select throws_ok($$update ezyvet_imported_histories set original='{}'$$,'23514',null,'Approved original is immutable');
select * from finish();rollback;
