begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select no_plan();
-- FIXTURE_BEGIN: owner-only synthetic source observations and reviewed mapping.
insert into auth.users(id,email,raw_user_meta_data) values('db560000-0000-4000-8000-000000000001','clinical-import-admin@example.test','{}'),('db560000-0000-4000-8000-000000000002','clinical-import-other@example.test','{}');
insert into user_roles(user_id,role) values('db560000-0000-4000-8000-000000000001','ADMIN'),('db560000-0000-4000-8000-000000000002','ADMIN');
create temp table fx(k text primary key,id uuid);create temp table data(k text primary key,v jsonb);grant all on fx,data to authenticated,service_role;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db560000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'client',id from save_client(auth.uid(),null,null,'Clinical','Import','+13035550199','clinical-import@example.test','EMAIL',null,null);
insert into fx select 'pet',id from save_patient(null,(select id from fx where k='client'),null,'Scoped dog','Dog',null,null,'unknown',null,'unknown','unknown',null,null,null);
insert into fx select k,gen_random_uuid() from unnest(array['mapping','mapping2','snapshot','snapshot2','legacy','terminal','run','history','other-run']) k;
reset role;
insert into ezyvet_import_snapshots(id,source_origin,source_site_uid,resource,external_id,payload,payload_hash,first_seen_by) select id,'https://api.trial.ezyvet.com','prescriptionitem-test-site','animal',case when k='snapshot' then '77' else '88' end,jsonb_build_object('id',case when k='snapshot' then 77 else 88 end),k,'db560000-0000-4000-8000-000000000001' from fx where k in ('snapshot','snapshot2');
insert into ezyvet_record_links(id,request_id,request_hash,source_origin,source_site_uid,resource,external_id,snapshot_id,head_version,client_id,pet_id,local_version,action,reason,approved_by)
select id,gen_random_uuid(),k,'https://api.trial.ezyvet.com','prescriptionitem-test-site','animal',case when k='mapping' then '77' else '88' end,(select id from fx where k=case when m.k='mapping' then 'snapshot' else 'snapshot2' end),1,(select id from fx where k='client'),(select id from fx where k='pet'),1,'link','Synthetic approved mapping','db560000-0000-4000-8000-000000000001' from fx m where k in ('mapping','mapping2');
insert into fx values('prescription-run',gen_random_uuid());
insert into data select 'prescription-run',claim_ezyvet_prescription_import((select id from fx where k='prescription-run'),'db560000-0000-4000-8000-000000000001','prescriptionitem-test-site','prescription','https://api.trial.ezyvet.com',(select id from fx where k='mapping'));
select stage_ezyvet_import_page((select id from fx where k='prescription-run'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='prescription-run'),1,true,'[{"external_id":"101","payload":{"id":101,"animal_id":77,"instructions":"Source prescriptionation"}},{"external_id":"102","payload":{"id":102,"animal_id":77}}]');
insert into data select 'prescription',list_ezyvet_prescription_candidates((select id from fx where k='mapping'),'prescription')->'candidates'->0;
-- Choose external prescription 101 independent of creation-order ties.
update data set v=(select c from jsonb_array_elements(list_ezyvet_prescription_candidates((select id from fx where k='mapping'),'prescription')->'candidates') c where c->>'external_id'='101') where k='prescription';
insert into data values('items','[{"external_id":"501","payload":{"id":501,"prescription_id":101,"product_id":null,"date_start":null,"remaining":"unknown","qty":"outside units","serial_number":"outside author","instructions":"<script>outside prose</script>"}}]');
insert into data select 'legacy',to_jsonb(claim_ezyvet_import_core((select id from fx where k='legacy'),'db560000-0000-4000-8000-000000000001','prescriptionitem-test-site','prescriptionitem','https://api.trial.ezyvet.com'));
select stage_ezyvet_import_page_core((select id from fx where k='legacy'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='legacy'),1,false,(select v from data where k='items'));
update ezyvet_import_runs set retry_after=null,lease_until=null;
insert into data select 'terminal',to_jsonb(claim_ezyvet_import_core((select id from fx where k='terminal'),'db560000-0000-4000-8000-000000000001','prescriptionitem-test-site','prescriptionitem','https://api.trial.ezyvet.com'));
select stage_ezyvet_import_page_core((select id from fx where k='terminal'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='terminal'),1,true,'[]');
update ezyvet_import_runs set retry_after=null,lease_until=null;
reset role;
insert into data select 'review-run',claim_ezyvet_prescriptionitem_import((select id from fx where k='run'),'db560000-0000-4000-8000-000000000001','prescriptionitem-test-site','prescriptionitem','https://api.trial.ezyvet.com',(select id from fx where k='mapping'),(select (v->>'id')::uuid from data where k='prescription'),(select v->>'payload_hash' from data where k='prescription'),(select (v->>'observed_head_version')::integer from data where k='prescription'));
select stage_ezyvet_import_page((select id from fx where k='run'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='review-run'),1,true,(select v from data where k='items'));

insert into fx values('review',gen_random_uuid()),('abandoned-review',gen_random_uuid());
insert into data select 'payload',jsonb_build_object('item_run_id',(select id from fx where k='run'),'patient_version',(select version from pets where id=(select id from fx where k='pet')),'interpretation',jsonb_build_object('reason','Synthetic historical review','outside_author',null,'prescribed_on',null,'prescription_date_status','uninterpreted','status','unknown','completeness','partial','partial_reason','Source item list is missing','items','[]'::jsonb,'replaces_id',null,'expected_predecessor_hash',null));
set local role authenticated;
select throws_ok($$select prepare_ezyvet_prescription_review((select id from fx where k='review'),(select id from fx where k='pet'),(select v from data where k='payload'))$$,'42501','Active veterinarian required','Administrator alone cannot prepare clinical review');
reset role;
insert into user_roles(user_id,role) values('db560000-0000-4000-8000-000000000001','DVM'),('db560000-0000-4000-8000-000000000002','DVM');
set local role authenticated;
select throws_ok($$select prepare_ezyvet_prescription_review(gen_random_uuid(),(select id from fx where k='pet'),'{}')$$,'23514',null,'Missing context rejected');
select throws_ok($$select prepare_ezyvet_prescription_review(gen_random_uuid(),(select id from fx where k='pet'),(select v||'{"patient_version":9999999999}' from data where k='payload'))$$,'40001','Patient version changed','Stale patient version rejected without overflow');
select throws_ok($$select prepare_ezyvet_prescription_review(gen_random_uuid(),(select id from fx where k='pet'),(select v||'{"interpretation":{}}' from data where k='payload'))$$,'23514','Exact prescription interpretation required','New preparation enforces clinical interpretation shape');
insert into data select 'prepared',prepare_ezyvet_prescription_review((select id from fx where k='review'),(select id from fx where k='pet'),(select v from data where k='payload'));
select is((select v#>>'{request,status}' from data where k='prepared'),'prepared','Review preparation retained');
select is((select v#>>'{request,review_context,items,0,original,qty}' from data where k='prepared'),'outside units','Source quantities frozen separately from interpretation');
select is((select v#>>'{request,review_context,reconciliation,status}' from data where k='prepared'),'unresolved','Draft preserves unresolved source-list evidence');
select is((select v->>'clinical_approval_available' from data where k='prepared'),'true','Approval capability is reported separately from prepared status');
select is(prepare_ezyvet_prescription_review((select id from fx where k='review'),(select id from fx where k='pet'),(select v from data where k='payload')),(select v from data where k='prepared'),'Exact retry returns same frozen review');
select throws_ok($$select prepare_ezyvet_prescription_review((select id from fx where k='review'),(select id from fx where k='pet'),(select v||'{"interpretation":{}}' from data where k='payload'))$$,'42501',null,'Changed interpretation cannot overwrite original UUID');
select throws_ok($$select recover_ezyvet_prescription_review((select id from fx where k='review'),gen_random_uuid())$$,'42501',null,'Wrong patient recovery denied');
select is(jsonb_array_length(list_ezyvet_prescription_review_requests((select id from fx where k='pet'))->'requests'),1,'Owned request discoverable after local pointer loss');
select throws_ok($$select list_ezyvet_prescription_review_requests((select id from fx where k='pet'),now(),null,20)$$,'23514',null,'Partial pagination cursor rejected');
select set_config('request.jwt.claims','{"sub":"db560000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select throws_ok($$select recover_ezyvet_prescription_review((select id from fx where k='review'),(select id from fx where k='pet'))$$,'42501',null,'Other veterinarian cannot recover private draft');
select is(jsonb_array_length(list_ezyvet_prescription_review_requests((select id from fx where k='pet'))->'requests'),0,'Discovery excludes another clinician draft');
select set_config('request.jwt.claims','{"sub":"db560000-0000-4000-8000-000000000001","role":"authenticated"}',true);
reset role;
update ezyvet_identity_heads set version=version+2 where resource='prescriptionitem' and external_id='501';
set local role authenticated;
select is(recover_ezyvet_prescription_review((select id from fx where k='review'),(select id from fx where k='pet')),(select v from data where k='prepared'),'Original evidence recoverable after source revision change');
select is(prepare_ezyvet_prescription_review((select id from fx where k='review'),(select id from fx where k='pet'),(select v from data where k='payload')),(select v from data where k='prepared'),'Committed preparation retry precedes mutable eligibility');
select throws_ok($$select prepare_ezyvet_prescription_review(gen_random_uuid(),(select id from fx where k='pet'),(select v from data where k='payload'))$$,'40001','SOURCE_PRESCRIPTION_ITEM_STALE','New preparation cannot use stale evidence');
select throws_ok($$select abandon_ezyvet_prescription_review((select id from fx where k='review'),(select id from fx where k='pet'),false)$$,'23514',null,'Abandonment requires explicit confirmation');
select is(abandon_ezyvet_prescription_review((select id from fx where k='review'),(select id from fx where k='pet'),true)#>>'{request,status}','abandoned','Original draft explicitly abandoned');
select is(recover_ezyvet_prescription_review((select id from fx where k='review'),(select id from fx where k='pet'))#>'{request,review_context}',(select v#>'{request,review_context}' from data where k='prepared'),'Abandonment preserves original evidence');
select is(abandon_ezyvet_prescription_review((select id from fx where k='abandoned-review'),(select id from fx where k='pet'),true)#>>'{request,status}','abandoned','Unknown request receives tombstone for ambiguous response');
select throws_ok($$select prepare_ezyvet_prescription_review((select id from fx where k='abandoned-review'),(select id from fx where k='pet'),(select v from data where k='payload'))$$,'42501',null,'Tombstone prevents delayed prepare from reviving request');
select is(list_ezyvet_prescription_review_requests((select id from fx where k='pet'),null,null,1)->>'has_more','true','Discovery reports second page');
select throws_ok($$select * from ezyvet_prescription_review_requests$$,'42501',null,'Private evidence table inaccessible through browser');
reset role;
select throws_ok($$update ezyvet_prescription_review_requests set payload='{}' where id=(select id from fx where k='review')$$,'23514','Prescription review evidence is immutable','Owner-level modification cannot change saved evidence');
select ok(not has_function_privilege('service_role','prepare_ezyvet_prescription_review(uuid,uuid,jsonb)','EXECUTE'),'Service API cannot impersonate reviewing veterinarian');
select ok(not has_function_privilege('anon','recover_ezyvet_prescription_review(uuid,uuid)','EXECUTE'),'Anonymous API cannot recover reviews');
delete from user_roles where user_id='db560000-0000-4000-8000-000000000001' and role='DVM';
set local role authenticated;
select throws_ok($$select recover_ezyvet_prescription_review((select id from fx where k='review'),(select id from fx where k='pet'))$$,'42501','Active veterinarian required','Role loss denies even terminal recovery');
select * from finish();rollback;
