begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select no_plan();
-- FIXTURE_BEGIN: isolated review sources.
insert into auth.users(id,email,raw_user_meta_data) values('db520000-0000-4000-8000-000000000001','clinical-import-admin@example.test','{}'),('db520000-0000-4000-8000-000000000002','clinical-import-other@example.test','{}');
update public.profiles set is_active = true where id in ('db520000-0000-4000-8000-000000000001','db520000-0000-4000-8000-000000000002');
insert into public.user_roles (user_id, role) values ('db520000-0000-4000-8000-000000000001','STAFF'),('db520000-0000-4000-8000-000000000002','STAFF');

insert into user_roles(user_id,role) values('db520000-0000-4000-8000-000000000001','ADMIN'),('db520000-0000-4000-8000-000000000002','ADMIN');
create temp table fx(k text primary key,id uuid);create temp table data(k text primary key,v jsonb);grant all on fx,data to authenticated,service_role;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db520000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'client',id from save_client(auth.uid(),null,null,'Clinical','Import','+13035550199','clinical-import@example.test','EMAIL',null,null);
insert into fx select 'pet',id from save_patient(null,(select id from fx where k='client'),null,'Scoped dog','Dog',null,null,'unknown',null,'unknown','unknown',null,null,null);
insert into fx select k,gen_random_uuid() from unnest(array['mapping','mapping2','snapshot','snapshot2','legacy','terminal','run','history','other-run']) k;
reset role;
insert into ezyvet_import_snapshots(id,source_origin,source_site_uid,resource,external_id,payload,payload_hash,first_seen_by) select id,'https://api.trial.ezyvet.com','vaccination-test-site','animal',case when k='snapshot' then '77' else '88' end,jsonb_build_object('id',case when k='snapshot' then 77 else 88 end),k,'db520000-0000-4000-8000-000000000001' from fx where k in ('snapshot','snapshot2');
insert into ezyvet_record_links(id,request_id,request_hash,source_origin,source_site_uid,resource,external_id,snapshot_id,head_version,client_id,pet_id,local_version,action,reason,approved_by)
select id,gen_random_uuid(),k,'https://api.trial.ezyvet.com','vaccination-test-site','animal',case when k='mapping' then '77' else '88' end,(select id from fx where k=case when m.k='mapping' then 'snapshot' else 'snapshot2' end),1,(select id from fx where k='client'),(select id from fx where k='pet'),1,'link','Synthetic approved mapping','db520000-0000-4000-8000-000000000001' from fx m where k in ('mapping','mapping2');
insert into fx values('consult-run',gen_random_uuid());
insert into data select 'consult-run',claim_ezyvet_clinical_import((select id from fx where k='consult-run'),'db520000-0000-4000-8000-000000000001','vaccination-test-site','consult','https://api.trial.ezyvet.com',(select id from fx where k='mapping'));
select stage_ezyvet_import_page((select id from fx where k='consult-run'),'db520000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='consult-run'),1,true,'[{"external_id":"101","payload":{"id":101,"animal_id":77,"description":"Source consultation"}},{"external_id":"102","payload":{"id":102,"animal_id":77}}]');
insert into data select 'consult',list_ezyvet_clinical_candidates((select id from fx where k='mapping'),'consult')->'candidates'->0;
-- Choose external consult 101 independent of creation-order ties.
update data set v=(select c from jsonb_array_elements(list_ezyvet_clinical_candidates((select id from fx where k='mapping'),'consult')->'candidates') c where c->>'external_id'='101') where k='consult';
insert into data values('items','[{"external_id":"501","payload":{"id":501,"consult_id":101,"product_id":null,"date_of_administration":null,"date_of_next_administration":"unknown","qty":"outside units","vet_id":"outside author","notes":"<script>outside prose</script>"}}]');
insert into data select 'legacy',to_jsonb(claim_ezyvet_import_core((select id from fx where k='legacy'),'db520000-0000-4000-8000-000000000001','vaccination-test-site','vaccination','https://api.trial.ezyvet.com'));
select stage_ezyvet_import_page_core((select id from fx where k='legacy'),'db520000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='legacy'),1,false,(select v from data where k='items'));
update ezyvet_import_runs set retry_after=null,lease_until=null;
insert into data select 'terminal',to_jsonb(claim_ezyvet_import_core((select id from fx where k='terminal'),'db520000-0000-4000-8000-000000000001','vaccination-test-site','vaccination','https://api.trial.ezyvet.com'));
select stage_ezyvet_import_page_core((select id from fx where k='terminal'),'db520000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='terminal'),1,true,'[]');
update ezyvet_import_runs set retry_after=null,lease_until=null;
insert into data select 'run',claim_ezyvet_vaccination_import((select id from fx where k='run'),'db520000-0000-4000-8000-000000000001','vaccination-test-site','vaccination','https://api.trial.ezyvet.com',(select id from fx where k='mapping'),(select (v->>'id')::uuid from data where k='consult'),(select v->>'payload_hash' from data where k='consult'),(select (v->>'observed_head_version')::integer from data where k='consult'));
select stage_ezyvet_import_page((select id from fx where k='run'),'db520000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='run'),1,true,(select v from data where k='items'));
insert into user_roles(user_id,role) values('db520000-0000-4000-8000-000000000001','DVM'),('db520000-0000-4000-8000-000000000002','DVM');
insert into data select 'candidate',list_ezyvet_vaccination_candidates((select id from fx where k='mapping'))->'candidates'->0;
insert into data select 'payload',jsonb_build_object('animal_link_id',c->'animal_link_id','patient_version',(select version from pets where id=(select id from fx where k='pet')),'snapshot_id',c->'id','payload_hash',c->'payload_hash','observed_head_version',c->'observed_head_version','consult_snapshot_id',c->'consult_snapshot_id','consult_payload_hash',c->'consult_payload_hash','consult_observed_head_version',c->'consult_observed_head_version','product_id',null,'product_version',null,'administered_on',null,'administration_date_status','unknown','source_next_due_on',null,'next_date_status','uninterpreted','status','unknown','outside_author',null,'reason','Reviewed outside source evidence','replaces_id',null,'expected_predecessor_hash',null) from(select v c from data where k='candidate') q;
insert into fx select k,gen_random_uuid() from unnest(array['review','duplicate','correction','tombstone','pending','product','stale-catalog']) k;
insert into catalog_products(id,name,kind,unit,unit_price_cents,created_by) select id,'Test vaccine','vaccine','dose',1000,'db520000-0000-4000-8000-000000000001' from fx where k='product';

insert into fx select k,gen_random_uuid() from unnest(array['generic-vaccination','foreign-site-vaccination']) k;
insert into ezyvet_import_snapshots(id,source_origin,source_site_uid,resource,external_id,payload,payload_hash,first_seen_by) select id,'https://api.trial.ezyvet.com',case when k='generic-vaccination' then 'vaccination-test-site' else 'other-source-site' end,'vaccination',case when k='generic-vaccination' then '901' else '902' end,jsonb_build_object('id',case when k='generic-vaccination' then 901 else 902 end,'consult_id',101),repeat('b',64),'db520000-0000-4000-8000-000000000001' from fx where k in('generic-vaccination','foreign-site-vaccination');
insert into ezyvet_identity_heads(source_origin,source_site_uid,resource,external_id,snapshot_id,version) select source_origin,source_site_uid,resource,external_id,id,1 from ezyvet_import_snapshots where id in(select id from fx where k in('generic-vaccination','foreign-site-vaccination'));

insert into data values('side-effects',jsonb_build_array((select count(*) from patient_treatments),(select count(*) from billing_invoices),(select count(*) from inventory_movements),(select count(*) from vaccine_certificates),(select count(*) from patient_vaccine_due_plans),(select count(*) from care_reminder_jobs),(select count(*) from communication_outbox)));
insert into ezyvet_identity_heads(source_origin,source_site_uid,resource,external_id,snapshot_id,version) select source_origin,source_site_uid,resource,external_id,id,1 from ezyvet_import_snapshots where id=(select id from fx where k='snapshot');
insert into fx select k,gen_random_uuid() from unnest(array['migration','scope','binding','new-consult-run','new-vaccine-run','new-approval']) k;
set local role authenticated;
select prepare_ezyvet_migration_run((select id from fx where k='migration'),'https://api.trial.ezyvet.com','vaccination-test-site',jsonb_build_array(jsonb_build_object('id',(select id from fx where k='scope'),'mapping_id',(select id from fx where k='mapping'),'resource','vaccination','parent_type','consult','parent_snapshot_id',(select v->'id' from data where k='consult'),'parent_head_version',1,'disposition','required','reason','Synthetic consultation coverage')));
select bind_ezyvet_migration_child((select id from fx where k='binding'),(select id from fx where k='scope'),(select id from fx where k='run'),'Synthetic vaccination run');
insert into data select 'item',list_ezyvet_migration_items((select id from fx where k='binding'))#>'{items,0}';
create function pg_temp.receipts(bef integer default null,lim integer default 20) returns jsonb language sql as $$select list_ezyvet_migration_vaccination_evidence((select id from fx where k='binding'),1,(v->>'snapshot_id')::uuid,v->>'evidence_hash',bef,lim) from data where k='item';$$;
select is(jsonb_array_length(pg_temp.receipts()->'approvals'),0,'Staging is not approval');
insert into data select 'prepared',prepare_ezyvet_vaccination_review((select id from fx where k='review'),(select id from fx where k='pet'),(select v from data where k='payload'));
select is(jsonb_array_length(pg_temp.receipts()->'approvals'),0,'Prepared review is not approved history');
insert into data select 'approved',approve_ezyvet_vaccination_review((select id from fx where k='review'),(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='prepared'),true);
select is(pg_temp.receipts()#>>'{approvals,0,relationship}','exact_source_version','Exact vaccination and consult context match');
select is(pg_temp.receipts()#>>'{approvals,0,outside_status}','unknown','Unknown clinical interpretation is preserved');
select is(pg_temp.receipts()#>>'{approvals,0,administration_date_status}','unknown','Unknown administration date is preserved');
select is(pg_temp.receipts()#>>'{approvals,0,next_date_status}','uninterpreted','Uninterpreted source due date stays distinct');
select is(pg_temp.receipts()#>>'{approvals,0,source_current}','true','Current source context is independent of approval');
select is(pg_temp.receipts()->>'local_administration_verified','false','Outside approval does not establish local administration');
select is(pg_temp.receipts()->>'due_plan_adoption_verified','false','Outside date does not establish active due plan');
select is(pg_temp.receipts()->>'complete_coverage_verified','false','Approved row is not accepted migration coverage');
select ok(not pg_temp.receipts()::text ~ 'outside prose|outside author|reason|original|payload_hash|request_hash','Projection excludes source prose and private request fields');
insert into data select 'correct-payload',v||jsonb_build_object('status','not_administered','replaces_id',(select id from fx where k='review'),'expected_predecessor_hash',(select v#>>'{receipt,version_hash}' from data where k='approved'),'reason','Explicit source review correction') from data where k='payload';
insert into data select 'correct-prepared',prepare_ezyvet_vaccination_review((select id from fx where k='correction'),(select id from fx where k='pet'),(select v from data where k='correct-payload'));
insert into data select 'corrected',approve_ezyvet_vaccination_review((select id from fx where k='correction'),(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='correct-prepared'),true);
select is(pg_temp.receipts(null,1)#>>'{approvals,0,outside_status}','not_administered','Correction retains explicit non-administration interpretation');
select is(pg_temp.receipts(null,1)->>'next_before_version','2','Version cursor uses bounded final row');
select is(pg_temp.receipts(2,1)#>>'{approvals,0,superseded}','true','Superseded approval remains visible');
select is(pg_temp.receipts(2,1)->>'has_more','false','Oldest version is terminal');
select throws_ok($$select list_ezyvet_migration_vaccination_evidence((select id from fx where k='binding'),1,(v->>'snapshot_id')::uuid,repeat('f',64)) from data where k='item'$$,'42501','Exact owned vaccination observation required','Forged evidence hash denied');
select throws_ok($$select list_ezyvet_migration_vaccination_evidence((select id from fx where k='binding'),2,(v->>'snapshot_id')::uuid,v->>'evidence_hash') from data where k='item'$$,'42501','Exact owned vaccination observation required','Different observation denied');
select throws_ok($$select pg_temp.receipts(null,101)$$,'23514','Invalid vaccination evidence identity or cursor','Unbounded history denied');
reset role;
update ezyvet_identity_heads set version=version+2 where source_site_uid='vaccination-test-site' and resource='consult' and external_id='101';
set local role authenticated;
select is(pg_temp.receipts()#>>'{approvals,0,source_current}','false','Consult A to B to A invalidates currentness');
select is(pg_temp.receipts()#>>'{approvals,0,relationship}','exact_source_version','Source drift preserves historical scope relationship');
reset role;
update ezyvet_import_runs set retry_after=null where source_site_uid='vaccination-test-site';
insert into data select 'new-consult-run',claim_ezyvet_clinical_import((select id from fx where k='new-consult-run'),'db520000-0000-4000-8000-000000000001','vaccination-test-site','consult','https://api.trial.ezyvet.com',(select id from fx where k='mapping'));
select stage_ezyvet_import_page((select id from fx where k='new-consult-run'),'db520000-0000-4000-8000-000000000001',(select(v->>'lease_id')::uuid from data where k='new-consult-run'),1,true,'[{"external_id":"101","payload":{"id":101,"animal_id":77,"description":"Source consultation"}}]');
insert into data select 'new-vaccine-run',claim_ezyvet_vaccination_import((select id from fx where k='new-vaccine-run'),'db520000-0000-4000-8000-000000000001','vaccination-test-site','vaccination','https://api.trial.ezyvet.com',(select id from fx where k='mapping'),(select(v->>'id')::uuid from data where k='consult'),(select v->>'payload_hash' from data where k='consult'),3);
select stage_ezyvet_import_page((select id from fx where k='new-vaccine-run'),'db520000-0000-4000-8000-000000000001',(select(v->>'lease_id')::uuid from data where k='new-vaccine-run'),1,true,(select v from data where k='items'));
set local role authenticated;
insert into data select 'new-payload',v||jsonb_build_object('consult_observed_head_version',3,'replaces_id',(select id from fx where k='correction'),'expected_predecessor_hash',(select v#>>'{receipt,version_hash}' from data where k='corrected')) from data where k='correct-payload';
insert into data select 'new-prepared',prepare_ezyvet_vaccination_review((select id from fx where k='new-approval'),(select id from fx where k='pet'),(select v from data where k='new-payload'));
select approve_ezyvet_vaccination_review((select id from fx where k='new-approval'),(select id from fx where k='pet'),(select v#>>'{request,request_hash}' from data where k='new-prepared'),true);
select is(pg_temp.receipts()#>>'{approvals,0,relationship}','different_source_version','Same vaccination snapshot with later consult version is not credited to old scope');
select is(pg_temp.receipts()#>>'{approvals,0,source_current}','true','Later review currentness is evaluated independently');
reset role;
update ezyvet_identity_heads set version=version+2 where source_site_uid='vaccination-test-site' and resource='vaccination' and external_id='501';
set local role authenticated;
select is(pg_temp.receipts()#>>'{approvals,0,source_current}','false','Vaccination A to B to A also invalidates currentness');
select set_config('request.jwt.claims','{"sub":"db520000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select throws_ok($$select pg_temp.receipts()$$,'42501','Exact owned vaccination observation required','Other administrator cannot read owned migration evidence');
reset role;
update profiles set is_active=false where id='db520000-0000-4000-8000-000000000001';
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db520000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select throws_ok($$select pg_temp.receipts()$$,'42501','Active administrator required','Inactive owner denied');
reset role;
select ok(not has_function_privilege('anon','public.list_ezyvet_migration_vaccination_evidence(uuid,integer,uuid,text,integer,integer)','execute'),'Anonymous execution denied');
select ok(not has_function_privilege('service_role','public.list_ezyvet_migration_vaccination_evidence(uuid,integer,uuid,text,integer,integer)','execute'),'Worker execution denied');
select is(jsonb_build_array((select count(*) from patient_treatments),(select count(*) from billing_invoices),(select count(*) from inventory_movements),(select count(*) from vaccine_certificates),(select count(*) from patient_vaccine_due_plans),(select count(*) from care_reminder_jobs),(select count(*) from communication_outbox)),(select v from data where k='side-effects'),'No native administration, due-plan, certificate, billing, stock or delivery mutation');
select * from finish();rollback;
