begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select no_plan();
-- FIXTURE_BEGIN
insert into auth.users(id,email,raw_user_meta_data) values('ed900000-0000-4000-8000-000000000001','resolution-admin@example.test','{}'),('ed900000-0000-4000-8000-000000000002','resolution-other@example.test','{}'),('ed900000-0000-4000-8000-000000000003','resolution-staff@example.test','{}');
update public.profiles set is_active = true where id in ('ed900000-0000-4000-8000-000000000001','ed900000-0000-4000-8000-000000000002','ed900000-0000-4000-8000-000000000003');
insert into public.user_roles (user_id, role) values ('ed900000-0000-4000-8000-000000000001','STAFF'),('ed900000-0000-4000-8000-000000000002','STAFF'),('ed900000-0000-4000-8000-000000000003','STAFF');

insert into user_roles(user_id,role) values('ed900000-0000-4000-8000-000000000001','ADMIN'),('ed900000-0000-4000-8000-000000000002','ADMIN');
create temp table fx(k text primary key,id uuid);create temp table data(k text primary key,v jsonb);grant all on fx,data to authenticated,service_role;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"ed900000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'client',id from save_client(auth.uid(),null,null,'Resolution','Household',null,null,'EMAIL',null,null);
insert into fx select 'pet',id from save_patient(null,(select id from fx where k='client'),null,'Resolution patient','Dog',null,null,'unknown',null,'unknown','unknown',null,null,null);
insert into fx select k,gen_random_uuid() from unnest(array['mapping','child','migration','scope','excluded','unsupported','binding','root','reopen','item-root']) k;
reset role;
insert into data select 'child',to_jsonb(claim_ezyvet_import((select id from fx where k='child'),'ed900000-0000-4000-8000-000000000001','resolution-site','animal','https://api.trial.ezyvet.com'));
select stage_ezyvet_import_page((select id from fx where k='child'),'ed900000-0000-4000-8000-000000000001',(select(v->>'lease_id')::uuid from data where k='child'),1,true,'[{"external_id":"77","payload":{"id":77}}]');
insert into ezyvet_record_links(id,request_id,request_hash,source_origin,source_site_uid,resource,external_id,snapshot_id,head_version,client_id,pet_id,local_version,action,reason,approved_by)
select (select id from fx where k='mapping'),gen_random_uuid(),'synthetic-mapping',s.source_origin,s.source_site_uid,s.resource,s.external_id,s.id,h.version,(select id from fx where k='client'),(select id from fx where k='pet'),1,'link','Synthetic reviewed mapping','ed900000-0000-4000-8000-000000000001' from ezyvet_import_snapshots s join ezyvet_identity_heads h on h.snapshot_id=s.id where s.source_site_uid='resolution-site';
insert into data select 'scope-input',jsonb_build_object('id',(select id from fx where k='scope'),'mapping_id',m.id,'resource','animal','parent_type','animal','parent_snapshot_id',m.snapshot_id,'parent_head_version',m.head_version,'disposition','required','reason','Synthetic required source') from ezyvet_record_links m where id=(select id from fx where k='mapping');
insert into data values('target','{"kind":"scope","binding_id":null,"page":null,"ordinal":null,"snapshot_id":null,"evidence_hash":null}');
set local role authenticated;
insert into data select 'manifest',prepare_ezyvet_migration_run((select id from fx where k='migration'),'https://api.trial.ezyvet.com','resolution-site',(select jsonb_build_array(v,v||jsonb_build_object('id',(select id from fx where k='excluded'),'resource','healthstatus','disposition','excluded'),v||jsonb_build_object('id',(select id from fx where k='unsupported'),'resource','attachment','disposition','unsupported')) from data where k='scope-input'));
insert into data select 'context',read_ezyvet_migration_resolution_context((select id from fx where k='scope'),(select v from data where k='target'));
reset role;
-- FIXTURE_END
set local role authenticated;
select is((select v#>>'{context,binding,current_id}' from data where k='context'),null::text,'Required scope without binding has explicit missing attempt');
select is((select v->'context'->'scan' from data where k='context'),'null'::jsonb,'No binding does not imply a zero-record scan');
select is((select v#>>'{context,manifest_hash}' from data where k='context'),(select v->>'scope_manifest_hash' from data where k='manifest'),'Context pins canonical resolved manifest digest');
select is((select v->>'complete_coverage_verified' from data where k='context'),'false','Context does not imply coverage');
select throws_ok($$select save_ezyvet_migration_resolution(gen_random_uuid(),(select id from fx where k='scope'),(select v from data where k='target'),'reopen','No previous exception',(select v->>'context_hash' from data where k='context'))$$,'23514','Reopen requires a preceding exclusion','No synthetic reopen root');
insert into data select 'root',save_ezyvet_migration_resolution((select id from fx where k='root'),(select id from fx where k='scope'),(select v from data where k='target'),'exclude','Unavailable within reviewed pilot scope',(select v->>'context_hash' from data where k='context'));
select is(read_ezyvet_migration_resolution((select id from fx where k='root')),(select v from data where k='root'),'Exact immutable receipt recovery');
select is(save_ezyvet_migration_resolution((select id from fx where k='root'),(select id from fx where k='scope'),(select v from data where k='target'),'exclude','Unavailable within reviewed pilot scope',(select v->>'context_hash' from data where k='context')),(select v from data where k='root'),'Same UUID exact save recovers original');
select throws_ok($$select save_ezyvet_migration_resolution((select id from fx where k='root'),(select id from fx where k='scope'),(select v from data where k='target'),'exclude','Changed request',(select v->>'context_hash' from data where k='context'))$$,'42501','Resolution request identity cannot change','Changed same UUID refused');
select is(read_ezyvet_migration_run((select id from fx where k='migration')),(select v from data where k='manifest'),'Scope exclusion cannot change original required or unsupported declarations');
select is((read_ezyvet_migration_resolution_context((select id from fx where k='scope'),(select v from data where k='target'))#>>'{latest,id}'),(select id::text from fx where k='root'),'Latest decision discoverable without browser pointer');
select throws_ok($$select save_ezyvet_migration_resolution(gen_random_uuid(),(select id from fx where k='scope'),(select v from data where k='target'),'exclude','Competing root',(select v->>'context_hash' from data where k='context'))$$,'40001','Exact preceding resolution required','Competing root refused');
insert into data select 'reopen',save_ezyvet_migration_resolution((select id from fx where k='reopen'),(select id from fx where k='scope'),(select v from data where k='target'),'reopen','Scope returned for supervised review',(select v->>'context_hash' from data where k='context'),(select id from fx where k='root'));
select is((select v->>'version' from data where k='reopen'),'2','Reopen appends new version');
select throws_ok($$select save_ezyvet_migration_resolution(gen_random_uuid(),(select id from fx where k='scope'),(select v from data where k='target'),'reopen','Already open',(select v->>'context_hash' from data where k='context'),(select id from fx where k='reopen'))$$,'23514','Reopen requires a preceding exclusion','Reopen cannot follow reopen');
insert into data select 'history',list_ezyvet_migration_resolutions((select id from fx where k='scope'),(select v from data where k='target'),null,null,1);
select is((select v->>'has_more' from data where k='history'),'true','History uses sentinel');
select is((select v#>>'{resolutions,0,receipt,id}' from data where k='history'),(select id::text from fx where k='reopen'),'Newest decision first');
insert into data select 'older',list_ezyvet_migration_resolutions((select id from fx where k='scope'),(select v from data where k='target'),(v#>>'{next_cursor,before_at}')::timestamptz,(v#>>'{next_cursor,before_id}')::uuid,1) from data where k='history';
select is((select v#>>'{resolutions,0,receipt,id}' from data where k='older'),(select id::text from fx where k='root'),'Cursor preserves original root');
select is((select v#>>'{resolutions,0,superseded}' from data where k='older'),'true','Superseded receipt stays visible');
select is((select v->>'has_more' from data where k='older'),'false','History terminates');
select bind_ezyvet_migration_child((select id from fx where k='binding'),(select id from fx where k='scope'),(select id from fx where k='child'),'Synthetic source attempt');
select is(list_ezyvet_migration_resolutions((select id from fx where k='scope'))#>>'{resolutions,0,context_current}','false','Binding changes stale earlier operational context');
select is(read_ezyvet_migration_resolution((select id from fx where k='root')),(select v from data where k='root'),'Stale context does not block immutable recovery');
select is(save_ezyvet_migration_resolution((select id from fx where k='root'),(select id from fx where k='scope'),(select v from data where k='target'),'exclude','Unavailable within reviewed pilot scope',(select v->>'context_hash' from data where k='context')),(select v from data where k='root'),'Exact retry after evidence drift succeeds');
select throws_ok($$select save_ezyvet_migration_resolution(gen_random_uuid(),(select id from fx where k='scope'),(select v from data where k='target'),'exclude','Stale exclusion',(select v->>'context_hash' from data where k='context'),(select id from fx where k='reopen'))$$,'40001','Operational evidence changed; review again','New stale exclusion refused');
insert into data select 'item',jsonb_build_object('kind','observation','binding_id',(select id from fx where k='binding'),'page',i->'page','ordinal',i->'ordinal','snapshot_id',i->'snapshot_id','evidence_hash',i->'evidence_hash') from jsonb_array_elements(list_ezyvet_migration_items((select id from fx where k='binding'))->'items') i limit 1;
insert into data select 'item-context',read_ezyvet_migration_resolution_context((select id from fx where k='scope'),(select v from data where k='item'));
select is((select v#>'{context,observation,observed_head_version}' from data where k='item-context'),'null'::jsonb,'Legacy observation head remains unknown');
insert into data select 'item-root',save_ezyvet_migration_resolution((select id from fx where k='item-root'),(select id from fx where k='scope'),(select v from data where k='item'),'exclude','Exclude this observation only',(select v->>'context_hash' from data where k='item-context'));
select is((select v->>'version' from data where k='item-root'),'1','Observation has independent chain');
select throws_ok($$select save_ezyvet_migration_resolution(gen_random_uuid(),(select id from fx where k='scope'),(select v from data where k='item'),'reopen','Wrong predecessor',(select v->>'context_hash' from data where k='item-context'),(select id from fx where k='reopen'))$$,'40001','Exact preceding resolution required','Scope predecessor cannot become observation predecessor');
select throws_ok($$select read_ezyvet_migration_resolution_context((select id from fx where k='scope'),(select v||jsonb_build_object('evidence_hash',repeat('f',64)) from data where k='item'))$$,'42501','Exact owned migration target required','Forged occurrence evidence denied');
select throws_ok($$select read_ezyvet_migration_resolution_context((select id from fx where k='scope'),(select v||'{"page":null}' from data where k='item'))$$,'23514',null,'Partial observation rejected');
select throws_ok($$select read_ezyvet_migration_resolution_context((select id from fx where k='scope'),(select v||'{"actor_id":"spoof"}' from data where k='target'))$$,'23514',null,'Unknown target fields rejected');
select throws_ok($$select list_ezyvet_migration_resolutions((select id from fx where k='scope'),null,now(),null)$$,'23514',null,'Partial history cursor rejected');
select throws_ok($$select list_ezyvet_migration_resolutions((select id from fx where k='scope'),null,null,null,101)$$,'23514',null,'Unbounded history rejected');
select throws_ok($$select * from ezyvet_migration_resolutions$$,'42501',null,'Raw ledger private');
select throws_ok($$update ezyvet_migration_resolutions set reason='Rewrite'$$,'42501',null,'Client direct updates denied');
-- Patient-scoped weight observations: protect even against malformed historical source ledgers.
reset role;
insert into fx select k,gen_random_uuid() from unnest(array['weight-child','weight-migration','weight-scope','weight-binding','foreign-weight']) k;
insert into data select 'weight-child',claim_ezyvet_weight_import((select id from fx where k='weight-child'),'ed900000-0000-4000-8000-000000000001','resolution-site','https://api.trial.ezyvet.com',(select id from fx where k='mapping'));
select stage_ezyvet_import_page((select id from fx where k='weight-child'),'ed900000-0000-4000-8000-000000000001',(select(v->>'lease_id')::uuid from data where k='weight-child'),1,true,'[{"external_id":"90","payload":{"id":90,"animal_id":77,"weight":12}}]');
-- Privileged malformed historical row only; normal staging rejects another patient's record.
insert into ezyvet_import_snapshots(id,source_origin,source_site_uid,resource,external_id,payload,payload_hash,first_seen_by)
select (select id from fx where k='foreign-weight'),'https://api.trial.ezyvet.com','resolution-site','healthstatus','91','{"id":91,"animal_id":999}',repeat('b',64),'ed900000-0000-4000-8000-000000000001';
insert into ezyvet_import_page_items(run_id,page,snapshot_id) select (select id from fx where k='weight-child'),1,(select id from fx where k='foreign-weight');
set local role authenticated;
select prepare_ezyvet_migration_run((select id from fx where k='weight-migration'),'https://api.trial.ezyvet.com','resolution-site',(select jsonb_build_array(v||jsonb_build_object('id',(select id from fx where k='weight-scope'),'resource','healthstatus')) from data where k='scope-input'));
select bind_ezyvet_migration_child((select id from fx where k='weight-binding'),(select id from fx where k='weight-scope'),(select id from fx where k='weight-child'),'Reviewed patient weight scan');
select is(jsonb_array_length(list_ezyvet_migration_items((select id from fx where k='weight-binding'))->'items'),1,'Foreign patient weight is filtered before pagination');
insert into data select 'weight-item',jsonb_build_object('kind','observation','binding_id',(select id from fx where k='weight-binding'),'page',i->'page','ordinal',i->'ordinal','snapshot_id',i->'snapshot_id','evidence_hash',i->'evidence_hash') from jsonb_array_elements(list_ezyvet_migration_items((select id from fx where k='weight-binding'))->'items') i;
select lives_ok($$select read_ezyvet_migration_resolution_context((select id from fx where k='weight-scope'),(select v from data where k='weight-item'))$$,'Patient weight observation is reviewable');
reset role;
insert into data select 'foreign-target',jsonb_build_object('kind','observation','binding_id',(select id from fx where k='weight-binding'),'page',1,'ordinal',0,'snapshot_id',s.id,'evidence_hash',encode(sha256(convert_to(jsonb_build_object('version',1,'child_run_id',(select id from fx where k='weight-child'),'page',1,'ordinal',0,'source_origin',s.source_origin,'source_site_uid',s.source_site_uid,'resource',s.resource,'external_id',s.external_id,'snapshot_id',s.id,'payload_hash',s.payload_hash,'observed_head_version',null,'file_id',null,'raw_record_sha256',null,'stable_metadata_sha256',null)::text,'UTF8')),'hex')) from ezyvet_import_snapshots s where id=(select id from fx where k='foreign-weight');
set local role authenticated;
select throws_ok($$select read_ezyvet_migration_resolution_context((select id from fx where k='weight-scope'),(select v from data where k='foreign-target'))$$,'42501','Exact owned migration target required','Known exact hash cannot authorize foreign patient weight');
reset role;
update ezyvet_identity_heads set version=version+2 where source_site_uid='resolution-site' and resource='animal';
set local role authenticated;
select is(list_ezyvet_migration_resolutions((select id from fx where k='scope'),(select v from data where k='item'))#>>'{resolutions,0,context_current}','false','Same snapshot with advanced head does not revive decision');
select is(read_ezyvet_migration_resolution((select id from fx where k='item-root')),(select v from data where k='item-root'),'Source return preserves old receipt');
select is((read_ezyvet_migration_resolution_context((select id from fx where k='unsupported'),(select v from data where k='target'))#>>'{context,scope,disposition}'),'unsupported','Unsupported scope explicitly reviewable without claiming support');
insert into data select 'unsupported-context',read_ezyvet_migration_resolution_context((select id from fx where k='unsupported'),(select v from data where k='target'));
select lives_ok($$select save_ezyvet_migration_resolution(gen_random_uuid(),(select id from fx where k='unsupported'),(select v from data where k='target'),'exclude','Unsupported source remains exception',(select v->>'context_hash' from data where k='unsupported-context'))$$,'Unsupported scope receives explicit exception');
select set_config('request.jwt.claims','{"sub":"ed900000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select is(read_ezyvet_migration_resolution((select id from fx where k='root')),null::jsonb,'Other admin cannot recover receipt');
select throws_ok($$select read_ezyvet_migration_resolution_context((select id from fx where k='scope'),(select v from data where k='target'))$$,'42501',null,'Other admin cannot inspect context');
select throws_ok($$select list_ezyvet_migration_resolutions((select id from fx where k='scope'))$$,'42501',null,'Other admin cannot list history');
select set_config('request.jwt.claims','{"sub":"ed900000-0000-4000-8000-000000000003","role":"authenticated"}',true);
select throws_ok($$select read_ezyvet_migration_resolution((select id from fx where k='root'))$$,'42501','Active administrator required','Active non-admin denied');
reset role;select set_config('request.jwt.claims','{"sub":"ed900000-0000-4000-8000-000000000001","role":"authenticated"}',true);
update profiles set is_active=false where id='ed900000-0000-4000-8000-000000000001';
set local role authenticated;
select throws_ok($$select read_ezyvet_migration_resolution((select id from fx where k='root'))$$,'42501','Active administrator required','Inactive admin denied');
reset role;
select throws_ok($$delete from ezyvet_migration_resolutions$$,'23514',null,'Privileged deletion cannot erase decisions');
select ok(not has_function_privilege('anon','public.save_ezyvet_migration_resolution(uuid,uuid,jsonb,text,text,text,uuid)','execute'),'Anonymous save denied');
select ok(not has_function_privilege('service_role','public.save_ezyvet_migration_resolution(uuid,uuid,jsonb,text,text,text,uuid)','execute'),'Worker save denied');
select ok(not has_function_privilege('authenticated','public.ezyvet_migration_resolution_context(uuid,jsonb)','execute'),'Private context helper not exposed');
select is((select count(*) from patient_weights where pet_id=(select id from fx where k='pet')),0::bigint,'No native weight side effects');
select is((select count(*) from ezyvet_record_links where source_site_uid='resolution-site'),1::bigint,'No identity promotion side effects');
select is((select count(*) from ezyvet_import_runs where source_site_uid='resolution-site'),2::bigint,'No implicit child scans');
select * from finish();rollback;
