begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select no_plan();
-- FIXTURE_BEGIN: owner-only synthetic source observations and reviewed mapping.
insert into auth.users(id,email,raw_user_meta_data) values('db560000-0000-4000-8000-000000000001','clinical-import-admin@example.test','{}'),('db560000-0000-4000-8000-000000000002','clinical-import-other@example.test','{}');
insert into user_roles(user_id,role) values('db560000-0000-4000-8000-000000000001','ADMIN'),('db560000-0000-4000-8000-000000000002','ADMIN');
create temp table fx(k text primary key,id uuid);create temp table data(k text primary key,v jsonb);grant all on fx,data to authenticated,service_role;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"db560000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'client',id from save_client(auth.uid(),null,null,'Clinical','Import','+13035550199','clinical-import@example.test','EMAIL',null,null);
insert into fx select 'pet',id from save_patient(null,(select id from fx where k='client'),null,'Scoped dog','Dog',null,null,'unknown',null,'unknown','unknown',null,null,null);
insert into fx select k,gen_random_uuid() from unnest(array['mapping','mapping2','snapshot','snapshot2','legacy','terminal','run','history','other-run']) k;
reset role;
insert into ezyvet_import_snapshots(id,source_origin,source_site_uid,resource,external_id,payload,payload_hash,first_seen_by) select id,'https://api.trial.ezyvet.com','prescriptionitem-test-site','animal',case when k='snapshot' then '77' else '88' end,jsonb_build_object('id',case when k='snapshot' then 77 else 88 end),k,'db560000-0000-4000-8000-000000000001' from fx where k in ('snapshot','snapshot2');
insert into ezyvet_record_links(id,request_id,request_hash,source_origin,source_site_uid,resource,external_id,snapshot_id,head_version,client_id,pet_id,local_version,action,reason,approved_by)
select id,gen_random_uuid(),k,'https://api.trial.ezyvet.com','prescriptionitem-test-site','animal',case when k='mapping' then '77' else '88' end,(select id from fx where k=case when m.k='mapping' then 'snapshot' else 'snapshot2' end),1,(select id from fx where k='client'),(select id from fx where k='pet'),1,'link','Synthetic approved mapping','db560000-0000-4000-8000-000000000001' from fx m where k in ('mapping','mapping2');
insert into ezyvet_identity_heads(source_origin,source_site_uid,resource,external_id,snapshot_id,version)
select source_origin,source_site_uid,resource,external_id,id,1 from ezyvet_import_snapshots where id=(select id from fx where k='snapshot');
insert into fx select k,gen_random_uuid() from unnest(array['request','request2','tombstone','consult-source','consult-run','consult-request']) k;
insert into data select 'run',claim_ezyvet_attachment_import((select id from fx where k='run'),'db560000-0000-4000-8000-000000000001','prescriptionitem-test-site','https://api.trial.ezyvet.com',(select id from fx where k='mapping'),'Animal',(select id from fx where k='snapshot'),'snapshot',1);
select stage_ezyvet_import_page((select id from fx where k='run'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='run'),1,false,'[{"external_id":"701","payload":{"id":701,"record_type":"Animal","record_id":77,"mime_type":"application/pdf","file_download_url":"https://untrusted.example.test/file","name":"Source file"}}]');
insert into data select 'observation',jsonb_build_object('snapshot_id',s.id,'hash',s.payload_hash,'version',h.version) from ezyvet_import_snapshots s join ezyvet_identity_heads h on h.snapshot_id=s.id where s.resource='attachment' and s.external_id='701';
insert into data values('side-effects',jsonb_build_object('documents',(select count(*) from patient_documents),'treatments',(select count(*) from patient_treatments),'invoices',(select count(*) from billing_invoices),'stock',(select count(*) from inventory_movements),'outbox',(select count(*) from communication_outbox)));
create function pg_temp.prepare(k text default 'request') returns jsonb language sql as $$
 select prepare_ezyvet_attachment_download((select id from fx where fx.k=$1),(select id from fx where fx.k='pet'),(select id from fx where fx.k='run'),1,(v->>'snapshot_id')::uuid,v->>'hash',(v->>'version')::integer) from data where data.k='observation';
$$;
set local role authenticated;
insert into data select 'saved',pg_temp.prepare();
select is((select v#>>'{request,status}' from data where k='saved'),'pending','Committed page can prepare even while the rest of the list is unfinished');
select is(pg_temp.prepare(),(select v from data where k='saved'),'Exact preparation retry recovers the same immutable intent');
select is(recover_ezyvet_attachment_download((select id from fx where k='request'),(select id from fx where k='pet')),(select v from data where k='saved'),'Owned recovery returns the saved context');
select is((select v#>>'{request,source_context,attachment_external_id}' from data where k='saved'),'701','Download identity derives from the observed attachment rather than a URL');
select is((select v#>>'{request,source_context,parent,parent_external_id}' from data where k='saved'),'77','Parent association is frozen with the source observation');
select is((select v->>'download_available' from data where k='saved'),'false','Preparation does not claim an implemented byte transport');
select throws_ok($$select prepare_ezyvet_attachment_download((select id from fx where k='request'),(select id from fx where k='pet'),(select id from fx where k='run'),2,(v->>'snapshot_id')::uuid,v->>'hash',1) from data where k='observation'$$,'42501',null,'Same operation cannot change its selected page');
select throws_ok($$select prepare_ezyvet_attachment_download((select id from fx where k='request2'),(select id from fx where k='pet'),(select id from fx where k='run'),2,(v->>'snapshot_id')::uuid,v->>'hash',1) from data where k='observation'$$,'42501',null,'Unobserved page cannot authorize a download');
select throws_ok($$select prepare_ezyvet_attachment_download((select id from fx where k='request2'),(select id from fx where k='pet'),(select id from fx where k='run'),1,(v->>'snapshot_id')::uuid,repeat('b',64),1) from data where k='observation'$$,'42501',null,'Changed payload hash rejected');
select throws_ok($$select prepare_ezyvet_attachment_download((select id from fx where k='request2'),gen_random_uuid(),(select id from fx where k='run'),1,(v->>'snapshot_id')::uuid,v->>'hash',1) from data where k='observation'$$,'42501',null,'Other patient cannot reuse an observed file');
select throws_ok($$select prepare_ezyvet_attachment_download((select id from fx where k='request2'),(select id from fx where k='pet'),(select id from fx where k='run'),1,(v->>'snapshot_id')::uuid,null,1) from data where k='observation'$$,'23514',null,'Missing source pins rejected');
select throws_ok($$select prepare_ezyvet_attachment_download((select id from fx where k='request2'),(select id from fx where k='pet'),(select id from fx where k='run'),1,(v->>'snapshot_id')::uuid,v->>'hash',2) from data where k='observation'$$,'42501',null,'Unobserved head revision rejected');
reset role;
select is((select request_hash from ezyvet_attachment_download_requests where id=(select id from fx where k='request')),
 (select encode(digest(jsonb_build_array(request_payload,source_context)::text,'sha256'),'hex') from ezyvet_attachment_download_requests where id=(select id from fx where k='request')),'Request fingerprint binds both selection and verified context');
select throws_ok($$update ezyvet_attachment_download_requests set source_context='{}'$$,'23514',null,'Saved source context cannot be replaced');
select throws_ok($$delete from ezyvet_attachment_download_requests$$,'23514',null,'Owned requests retain their history');
-- Actual scoped ingestion A -> B -> A reuses the immutable snapshot at a new head version.
update ezyvet_import_runs set retry_after=null,lease_until=null where id=(select id from fx where k='run');
update data set v=claim_ezyvet_attachment_import((select id from fx where k='run'),'db560000-0000-4000-8000-000000000001','prescriptionitem-test-site','https://api.trial.ezyvet.com',(select id from fx where k='mapping'),'Animal',(select id from fx where k='snapshot'),'snapshot',1) where k='run';
select stage_ezyvet_import_page((select id from fx where k='run'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='run'),2,false,'[{"external_id":"701","payload":{"id":701,"record_type":"Animal","record_id":77,"name":"Changed"}}]');
update ezyvet_import_runs set retry_after=null,lease_until=null where id=(select id from fx where k='run');
update data set v=claim_ezyvet_attachment_import((select id from fx where k='run'),'db560000-0000-4000-8000-000000000001','prescriptionitem-test-site','https://api.trial.ezyvet.com',(select id from fx where k='mapping'),'Animal',(select id from fx where k='snapshot'),'snapshot',1) where k='run';
select stage_ezyvet_import_page((select id from fx where k='run'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='run'),3,true,jsonb_build_array(jsonb_build_object('external_id',s.external_id,'payload',s.payload))) from ezyvet_import_snapshots s where s.id=(select (v->>'snapshot_id')::uuid from data where k='observation');
select is((select h.version from ezyvet_identity_heads h where resource='attachment' and external_id='701'),3,'Actual A-to-B-to-A ingestion advances the observed revision twice');
set local role authenticated;
select is(pg_temp.prepare(),(select v from data where k='saved'),'Lost preparation acknowledgment recovers after source A-to-B-to-A revision change');
select throws_ok($$select pg_temp.prepare('request2')$$,'40001','SOURCE_ATTACHMENT_STALE','Fresh request rejects reused snapshot with newer observed revision');
reset role;
update ezyvet_identity_heads set version=version+1 where resource='animal' and external_id='77';
set local role authenticated;
select is(recover_ezyvet_attachment_download((select id from fx where k='request'),(select id from fx where k='pet')),(select v from data where k='saved'),'Recovery remains available after the parent changes');
select throws_ok($$select pg_temp.prepare('request2')$$,'40001','SOURCE_ATTACHMENT_PARENT_STALE','Fresh request revalidates parent revision before attachment');
select throws_ok($$select abandon_ezyvet_attachment_download((select id from fx where k='request'),(select id from fx where k='pet'),false)$$,'23514',null,'Abandonment requires an explicit choice');
insert into data select 'abandoned',abandon_ezyvet_attachment_download((select id from fx where k='request'),(select id from fx where k='pet'),true);
select is((select v#>>'{request,status}' from data where k='abandoned'),'abandoned','Source changes do not prevent abandonment');
select is((select v#>'{request,source_context}' from data where k='abandoned'),(select v#>'{request,source_context}' from data where k='saved'),'Abandonment retains original evidence');
select is(abandon_ezyvet_attachment_download((select id from fx where k='request'),(select id from fx where k='pet'),true),(select v from data where k='abandoned'),'Repeated abandonment has an exact receipt');
select throws_ok($$select pg_temp.prepare()$$,'42501',null,'Abandoned operation cannot be resurrected');
select is(abandon_ezyvet_attachment_download((select id from fx where k='tombstone'),(select id from fx where k='pet'),true)#>>'{request,status}','abandoned','Discard before acknowledgment records a tombstone');
select throws_ok($$select pg_temp.prepare('tombstone')$$,'42501',null,'Delayed prepare cannot revive a tombstone');
select is(jsonb_array_length(list_ezyvet_attachment_downloads((select id from fx where k='pet'))->'requests'),2,'Owner can discover both retained operations');
insert into data select 'page1',list_ezyvet_attachment_downloads((select id from fx where k='pet'),null,null,1);
select ok((select (v->>'has_more')::boolean from data where k='page1'),'Discovery is bounded');
select ok(not exists(select 1 from jsonb_array_elements(list_ezyvet_attachment_downloads((select id from fx where k='pet'))->'requests') r where r#>'{request,source_context,attachment_metadata}' is not null),'Discovery omits raw metadata while recovery retains it');
select is(jsonb_array_length(list_ezyvet_attachment_downloads((select id from fx where k='pet'),(v#>>'{next_cursor,before_at}')::timestamptz,(v#>>'{next_cursor,before_id}')::uuid,1)->'requests'),1,'Cursor recovers remaining operation') from data where k='page1';
select throws_ok($$select list_ezyvet_attachment_downloads((select id from fx where k='pet'),now(),null,1)$$,'23514',null,'Incomplete cursor rejected');
select throws_ok($$select recover_ezyvet_attachment_download((select id from fx where k='request'),gen_random_uuid())$$,'42501',null,'Wrong patient recovery rejected');
select set_config('request.jwt.claims','{"sub":"db560000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select throws_ok($$select recover_ezyvet_attachment_download((select id from fx where k='request'),(select id from fx where k='pet'))$$,'42501',null,'Other administrator cannot recover owner request');
select throws_ok($$select pg_temp.prepare('request2')$$,'42501',null,'Other administrator cannot prepare from owned intake');
select is(jsonb_array_length(list_ezyvet_attachment_downloads((select id from fx where k='pet'))->'requests'),0,'Other administrator discovery reveals no requests');
select set_config('request.jwt.claims','{"sub":"db560000-0000-4000-8000-000000000001","role":"authenticated"}',true);
reset role;
-- Scoped consultation path uses actual claim/stage receipts too.
update ezyvet_import_runs set retry_after=null,lease_until=null;
insert into data select 'consult-source',claim_ezyvet_clinical_import((select id from fx where k='consult-source'),'db560000-0000-4000-8000-000000000001','prescriptionitem-test-site','consult','https://api.trial.ezyvet.com',(select id from fx where k='mapping'));
select stage_ezyvet_import_page((select id from fx where k='consult-source'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='consult-source'),1,true,'[{"external_id":"201","payload":{"id":201,"animal_id":77}}]');
insert into data select 'consult-run',claim_ezyvet_attachment_import((select id from fx where k='consult-run'),'db560000-0000-4000-8000-000000000001','prescriptionitem-test-site','https://api.trial.ezyvet.com',(select id from fx where k='mapping'),'Consult',s.id,s.payload_hash,h.version) from ezyvet_import_snapshots s join ezyvet_identity_heads h on h.snapshot_id=s.id where s.resource='consult' and s.external_id='201';
select stage_ezyvet_import_page((select id from fx where k='consult-run'),'db560000-0000-4000-8000-000000000001',(select (v->>'lease_id')::uuid from data where k='consult-run'),1,true,'[{"external_id":"702","payload":{"id":702,"record_type":"Consult","record_id":201,"mime_type":"unsupported/example"}}]');
insert into data select 'consult-observation',jsonb_build_object('snapshot_id',s.id,'hash',s.payload_hash,'version',h.version) from ezyvet_import_snapshots s join ezyvet_identity_heads h on h.snapshot_id=s.id where s.resource='attachment' and s.external_id='702';
set local role authenticated;
insert into data select 'consult-saved',prepare_ezyvet_attachment_download((select id from fx where k='consult-request'),(select id from fx where k='pet'),(select id from fx where k='consult-run'),1,(v->>'snapshot_id')::uuid,v->>'hash',(v->>'version')::integer) from data where k='consult-observation';
select is((select v#>>'{request,source_context,parent,parent_type}' from data where k='consult-saved'),'Consult','Scoped consultation context can prepare a request');
select is((select v#>>'{request,source_context,attachment_metadata,mime_type}' from data where k='consult-saved'),'unsupported/example','Unsupported MIME remains evidence for actionable later discrepancy');
reset role;
delete from user_roles where user_id='db560000-0000-4000-8000-000000000001' and role='ADMIN';
set local role authenticated;
select throws_ok($$select recover_ezyvet_attachment_download((select id from fx where k='request'),(select id from fx where k='pet'))$$,'42501',null,'Role loss revokes recovery access');
select throws_ok($$select list_ezyvet_attachment_downloads((select id from fx where k='pet'))$$,'42501',null,'Role loss revokes discovery access');
reset role;
select ok(not has_table_privilege('authenticated','public.ezyvet_attachment_download_requests','select'),'Authenticated direct reads denied');
select ok(not has_table_privilege('service_role','public.ezyvet_attachment_download_requests','insert'),'Service cannot forge durable intent directly');
select ok(not has_function_privilege('service_role','public.ezyvet_attachment_download_context(uuid,uuid,uuid,integer,uuid,text,integer)','execute'),'Source collector is private');
select ok(not has_function_privilege('anon','public.prepare_ezyvet_attachment_download(uuid,uuid,uuid,integer,uuid,text,integer)','execute'),'Anonymous preparation denied');
select is(jsonb_build_object('documents',(select count(*) from patient_documents),'treatments',(select count(*) from patient_treatments),'invoices',(select count(*) from billing_invoices),'stock',(select count(*) from inventory_movements),'outbox',(select count(*) from communication_outbox)),(select v from data where k='side-effects'),'Intent creates no documents, clinical records, stock, billing or messages');
select * from finish();rollback;
