begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,raw_user_meta_data) values
('61000000-0000-4000-8000-000000000001','inbound-staff@example.test','{"first_name":"Inbound","last_name":"Staff"}'),
('61000000-0000-4000-8000-000000000002','inbound-other@example.test','{"first_name":"Other","last_name":"Staff"}');
create temp table fixture_ids(kind text primary key,id uuid);
grant all on fixture_ids to authenticated,service_role;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"61000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fixture_ids select 'client',id from public.save_client(auth.uid(),null,null,'Inbound','Family','+13035550100','family@example.test','EMAIL',null,null);
insert into public.sms_consent(client_id,phone_number,opted_in) values((select id from fixture_ids where kind='client'),'+13035550100',true);
select throws_ok($$select public.receive_communication_event('resend','event-1','email-1','inbound',repeat('a',64),'{}')$$,'42501',null,'Staff cannot forge provider events');
reset role;
set local role service_role;
select set_config('request.jwt.claims','{"role":"service_role"}',true);
select throws_ok($$select public.receive_communication_event('resend','early-receipt','unknown-provider-id','delivered',repeat('a',64),'{}')$$,'23503',null,'Unknown early receipt fails for provider retry, not silent acknowledgement');
insert into fixture_ids select 'event',id from public.receive_communication_event('resend','event-1','email-1','inbound',repeat('a',64),'{"from":"unknown@example.test","to":"care@example.test"}');
select lives_ok($$select public.receive_communication_event('resend','event-1','email-1','inbound',repeat('a',64),'{"from":"unknown@example.test","to":"care@example.test"}')$$,'Duplicate signed receipt idempotent');
select throws_ok($$select public.receive_communication_event('resend','event-1','email-1','inbound',repeat('b',64),'{}')$$,'23505',null,'Reused event ID with changed payload rejected');
insert into fixture_ids select 'lease',lease_token from public.claim_communication_event();
insert into fixture_ids select 'unknown',id from public.complete_inbound_communication((select id from fixture_ids where kind='event'),(select id from fixture_ids where kind='lease'),'unknown@example.test','care@example.test','Hello','Unknown sender',null,'<unknown@example.test>','{}','[]',now(),null);
select is((select message_id from public.communication_inbound where id=(select id from fixture_ids where kind='unknown')),null::uuid,'Unknown sender is not attached to a household');
select is((select review_reason from public.communication_inbound where id=(select id from fixture_ids where kind='unknown')),'Unknown or shared sender','Unknown message retained for staff review');
update fixture_ids set id=(public.receive_communication_event('resend','event-2','email-2','inbound',repeat('b',64),'{"from":"family@example.test","to":"care@example.test"}')).id where kind='event';
update fixture_ids set id=(public.claim_communication_event()).lease_token where kind='lease';
insert into fixture_ids select 'known',id from public.complete_inbound_communication((select id from fixture_ids where kind='event'),(select id from fixture_ids where kind='lease'),'family@example.test','care@example.test','Hello','Known sender',null,'<known@example.test>','{}','[]',now(),null);
insert into fixture_ids select 'conversation',conversation_id from public.communication_inbound where id=(select id from fixture_ids where kind='known');
select is((select client_id from public.communication_inbound where id=(select id from fixture_ids where kind='known')),(select id from fixture_ids where kind='client'),'Unique normalized sender links correct household');
reset role;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"61000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select is((select unread_count from public.list_communication_inbox() where conversation_id=(select id from fixture_ids where kind='conversation')),1::bigint,'New inbound unread for first staff');
select lives_ok($$select public.mark_conversation_read(auth.uid(),(select id from fixture_ids where kind='conversation'),(select message_id from public.communication_inbound where id=(select id from fixture_ids where kind='known')))$$,'Read cursor records exact rendered message');
select is((select unread_count from public.list_communication_inbox() where conversation_id=(select id from fixture_ids where kind='conversation')),0::bigint,'First staff read cursor clears own unread count');
select set_config('request.jwt.claims','{"sub":"61000000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select is((select unread_count from public.list_communication_inbox() where conversation_id=(select id from fixture_ids where kind='conversation')),1::bigint,'Reading never clears another staff unread count');
select throws_ok($$select public.list_communication_inbox('',null,null,null)$$,'23514',null,'Inbox cannot request unbounded page');
select throws_ok($$select public.mark_conversation_read('61000000-0000-4000-8000-000000000001',(select id from fixture_ids where kind='conversation'),(select message_id from public.communication_inbound where id=(select id from fixture_ids where kind='known')))$$,'42501',null,'Cannot spoof another staff read cursor');
select lives_ok($$select public.assign_inbound_communication(auth.uid(),(select id from fixture_ids where kind='unknown'),1,(select id from fixture_ids where kind='client'),(select id from fixture_ids where kind='conversation'),'Confirmed household by callback')$$,'Staff can explicitly resolve unknown sender with reason');
select throws_ok($$select public.assign_inbound_communication(auth.uid(),(select id from fixture_ids where kind='unknown'),1,(select id from fixture_ids where kind='client'),(select id from fixture_ids where kind='conversation'),'Stale duplicate assignment')$$,'40001',null,'Review assignment cannot duplicate message');
reset role;
set local role service_role;
select set_config('request.jwt.claims','{"role":"service_role"}',true);
update fixture_ids set id=(public.receive_communication_event('twilio','sms-stop','SMstop','inbound',repeat('c',64),'{"from":"+13035550100","to":"+13035550199","body":"STOP","opt_action":"STOP"}')).id where kind='event';
reset role;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"61000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select throws_ok($$select public.enqueue_communication(auth.uid(),gen_random_uuid(),(select id from fixture_ids where kind='conversation'),'SMS','+13035550100','','Do not send')$$,'42501',null,'Durably received STOP blocks outbound even before provider content fetch');
reset role;
set local role service_role;
select set_config('request.jwt.claims','{"role":"service_role"}',true);
update fixture_ids set id=(public.claim_communication_event()).lease_token where kind='lease';
select lives_ok($$select public.complete_inbound_communication((select id from fixture_ids where kind='event'),(select id from fixture_ids where kind='lease'),'+13035550100','+13035550199','','STOP',null,null,'{}','[]',now()-interval '1 hour','STOP')$$,'STOP records provider occurrence time and suppression');
select is((select opted_in from public.communication_phone_preferences where phone='+13035550100'),false,'STOP disables normalized number');
update fixture_ids set id=(public.receive_communication_event('twilio','sms-start','SMstart','inbound',repeat('d',64),'{"from":"+13035550100","to":"+13035550199","body":"START","opt_action":"START"}')).id where kind='event';
update fixture_ids set id=(public.claim_communication_event()).lease_token where kind='lease';
select lives_ok($$select public.complete_inbound_communication((select id from fixture_ids where kind='event'),(select id from fixture_ids where kind='lease'),'+13035550100','+13035550199','','START',null,null,'{}','[]',now(),'START')$$,'Later provider-verified START permits opt-in');
select is((select count(*) from public.communication_suppressions where channel='SMS' and recipient='+13035550100'),0::bigint,'START removes only provider STOP suppression');
update fixture_ids set id=(public.receive_communication_event('twilio','sms-old-stop','SMoldstop','inbound',repeat('e',64),'{"from":"+13035550100","to":"+13035550199","body":"STOP","opt_action":"STOP"}')).id where kind='event';
update fixture_ids set id=(public.claim_communication_event()).lease_token where kind='lease';
select lives_ok($$select public.complete_inbound_communication((select id from fixture_ids where kind='event'),(select id from fixture_ids where kind='lease'),'+13035550100','+13035550199','','STOP',null,null,'{}','[]',now()-interval '2 hours','STOP')$$,'Old delayed STOP retained without reversing newer START');
select is((select opted_in from public.communication_phone_preferences where phone='+13035550100'),true,'Consent follows provider occurrence order, not arrival order');
reset role;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"61000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fixture_ids select 'outbox',id from public.enqueue_communication(auth.uid(),gen_random_uuid(),(select id from fixture_ids where kind='conversation'),'EMAIL','family@example.test','Summary','Synthetic outbound');
reset role;
set local role service_role;
select set_config('request.jwt.claims','{"role":"service_role"}',true);
update fixture_ids set id=(public.claim_communication()).lease_token where kind='lease';
select public.start_communication_attempt((select id from fixture_ids where kind='outbox'),(select id from fixture_ids where kind='lease'),'{"from":"care@example.test","reply_to":"care@example.test"}');
select public.finish_communication_attempt((select id from fixture_ids where kind='outbox'),(select id from fixture_ids where kind='lease'),'accepted','provider-status-email',null);
update fixture_ids set id=(public.receive_communication_event('resend','sent-event','provider-status-email','sent',repeat('f',64),'{}')).id where kind='event';
update fixture_ids set id=(public.claim_communication_event()).lease_token where kind='lease';
select public.complete_communication_status((select id from fixture_ids where kind='event'),(select id from fixture_ids where kind='lease'));
select is((select state from public.communication_outbox where id=(select id from fixture_ids where kind='outbox')),'accepted','Sent callback never implies delivered');
update fixture_ids set id=(public.receive_communication_event('resend','delivered-event','provider-status-email','delivered',repeat('0',64),'{}')).id where kind='event';
update fixture_ids set id=(public.claim_communication_event()).lease_token where kind='lease';
select lives_ok($$select public.complete_communication_status((select id from fixture_ids where kind='event'),(select id from fixture_ids where kind='lease'))$$,'Known delivery callback updates matching outbox');
select is((select state from public.communication_outbox where id=(select id from fixture_ids where kind='outbox')),'delivered','Verified delivery callback records delivery');
update fixture_ids set id=(public.receive_communication_event('resend','bounce-event','provider-status-email','bounced',repeat('1',64),'{}')).id where kind='event';
update fixture_ids set id=(public.claim_communication_event()).lease_token where kind='lease';
select lives_ok($$select public.complete_communication_status((select id from fixture_ids where kind='event'),(select id from fixture_ids where kind='lease'))$$,'Bounce callback retains terminal failure evidence');
select is((select count(*) from public.communication_suppressions where channel='EMAIL' and recipient='family@example.test'),1::bigint,'Bounce suppresses immutable intended recipient');
select is((select delivery_failure_kind from public.communication_outbox where id=(select id from fixture_ids where kind='outbox')),'bounced','Bounce remains visible even after earlier delivery receipt');
reset role;
select throws_ok($$update public.messages set content='rewritten' where id=(select message_id from public.communication_inbound where id=(select id from fixture_ids where kind='known'))$$,'23514',null,'Inbound display content cannot diverge from received original');
select * from finish();
rollback;
