begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,raw_user_meta_data) values
('95000000-0000-4000-8000-000000000001','workspace@example.test','{"first_name":"Workspace","last_name":"Staff"}'),
('95000000-0000-4000-8000-000000000002','workspace-other@example.test','{"first_name":"Other","last_name":"Staff"}');
update public.profiles set is_active = true where id in ('95000000-0000-4000-8000-000000000001','95000000-0000-4000-8000-000000000002');
insert into public.user_roles (user_id, role) values ('95000000-0000-4000-8000-000000000001','STAFF'),('95000000-0000-4000-8000-000000000002','STAFF');

create temp table fixture_ids(kind text primary key,id uuid);
grant all on fixture_ids to authenticated;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"95000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fixture_ids select 'client',id from public.save_client(auth.uid(),null,null,'Workspace','Family','+13035550950','workspace@example.test','EMAIL',null,null);
insert into fixture_ids select 'conversation',id from public.ensure_active_conversation((select id from fixture_ids where kind='client'));
select is((public.ensure_active_conversation((select id from fixture_ids where kind='client'))).id,(select id from fixture_ids where kind='conversation'),'Ensure returns existing sole active thread');
select is((select count(*) from public.conversation_activity_audit),1::bigint,'Creation records actor audit exactly once');
select throws_ok($$insert into public.conversations(client_id) values((select id from fixture_ids where kind='client'))$$,'42501',null,'Direct conversation creation blocked');
select throws_ok($$update public.conversations set priority='URGENT'$$,'42501',null,'Direct metadata writes blocked');
select throws_ok($$select public.update_conversation_metadata('95000000-0000-4000-8000-000000000002',(select id from fixture_ids where kind='conversation'),1,'ACTIVE',null,'URGENT','{}')$$,'42501',null,'Metadata actor spoof rejected');
select lives_ok($$select public.update_conversation_metadata(auth.uid(),(select id from fixture_ids where kind='conversation'),1,'ACTIVE',auth.uid(),'URGENT',array['followup','followup'])$$,'Assigned priority and tags update atomically');
select is((select tags from public.conversations where id=(select id from fixture_ids where kind='conversation')),array['followup'],'Tags normalized and deduplicated');
select throws_ok($$select public.update_conversation_metadata(auth.uid(),(select id from fixture_ids where kind='conversation'),1,'ACTIVE',null,'NORMAL','{}')$$,'40001',null,'Stale metadata rejected');
reset role;
insert into public.messages(id,conversation_id,type,sender_type,content,created_at) values
('95000000-0000-4000-8000-000000000011',(select id from fixture_ids where kind='conversation'),'EMAIL','CLIENT','Initial question',now()-interval '1 minute');
set local role authenticated;
select is((select unread_conversations from public.inbox_unread_totals()),1::bigint,'Server unread aggregate includes inbound thread');
select is((select count(*) from public.list_inbox_workspace(p_assignment=>'staff',p_assigned_to_id=>auth.uid(),p_priority=>'URGENT',p_tags=>array['followup'],p_channel=>'EMAIL',p_search=>'Workspace',p_read=>'unread')),1::bigint,'Combined filters select expected thread');
select is((select count(*) from public.list_inbox_workspace(p_assignment=>'unassigned')),0::bigint,'Unassigned filter excludes assigned thread');
select throws_ok($$select * from public.list_inbox_workspace(p_before_id=>'95000000-0000-4000-8000-000000000011')$$,'23514',null,'Partial cursor rejected');
select public.mark_conversation_read(auth.uid(),(select id from fixture_ids where kind='conversation'),'95000000-0000-4000-8000-000000000011');
select is((select unread_conversations from public.inbox_unread_totals()),0::bigint,'Read clears only actor count');
select set_config('request.jwt.claims','{"sub":"95000000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select is((select unread_conversations from public.inbox_unread_totals()),1::bigint,'Other staff keeps independent unread count');
select set_config('request.jwt.claims','{"sub":"95000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select public.mark_conversation_unread(auth.uid(),(select id from fixture_ids where kind='conversation'));
select is((select unread_conversations from public.inbox_unread_totals()),1::bigint,'Manual unread flag restores thread badge');
select is((select unread_messages from public.inbox_unread_totals()),0::bigint,'Manual unread does not fabricate unseen messages');
insert into fixture_ids values('snapshot',public.capture_inbox_read_snapshot());
reset role;
insert into public.messages(id,conversation_id,type,sender_type,content,created_at) values
('95000000-0000-4000-8000-000000000012',(select id from fixture_ids where kind='conversation'),'SMS','CLIENT','Arrived after snapshot',now());
set local role authenticated;
select public.apply_inbox_read_snapshot(auth.uid(),(select id from fixture_ids where kind='snapshot'));
select is((select unread_messages from public.inbox_unread_totals()),1::bigint,'Bulk read preserves later arriving message');
select lives_ok($$select public.apply_inbox_read_snapshot(auth.uid(),(select id from fixture_ids where kind='snapshot'))$$,'Snapshot apply is idempotent');
update fixture_ids set id=public.capture_inbox_read_snapshot() where kind='snapshot';
select public.mark_conversation_unread(auth.uid(),(select id from fixture_ids where kind='conversation'));
select public.apply_inbox_read_snapshot(auth.uid(),(select id from fixture_ids where kind='snapshot'));
select is((select forced from public.conversation_unread_flags where user_id=auth.uid()),true,'Bulk snapshot cannot erase a later manual unread action');
select set_config('request.jwt.claims','{"sub":"95000000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select throws_ok($$select public.apply_inbox_read_snapshot(auth.uid(),(select id from fixture_ids where kind='snapshot'))$$,'23514',null,'Other actor cannot use snapshot token');
select set_config('request.jwt.claims','{"sub":"95000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select public.update_conversation_metadata(auth.uid(),(select id from fixture_ids where kind='conversation'),2,'ARCHIVED',null,'NORMAL','{}');
select is((select unread_conversations from public.inbox_unread_totals()),0::bigint,'Archived thread excluded from active aggregate');
select is((select count(*) from public.list_inbox_workspace(p_status=>'ARCHIVED')),1::bigint,'Archive filter returns retained conversation');
select throws_ok($$select public.delete_conversation_cascade((select id from fixture_ids where kind='conversation'))$$,'42501',null,'Legacy cascade delete disabled');
reset role;
select throws_ok($$delete from public.conversations where id=(select id from fixture_ids where kind='conversation')$$,'23514',null,'Archived history cannot be deleted through privileged table path');
set local role authenticated;
select isnt((public.ensure_active_conversation((select id from fixture_ids where kind='client'))).id,(select id from fixture_ids where kind='conversation'),'Compose creates a new thread after archive');
select throws_ok($$select public.update_conversation_metadata(auth.uid(),(select id from fixture_ids where kind='conversation'),3,'ACTIVE',null,'NORMAL','{}')$$,'23514',null,'Restore cannot create duplicate active threads');
select is((select count(*) from public.list_inbox_workspace(p_status=>null,p_limit=>1)),1::bigint,'Page limit applied server side');
select is((select count(*) from public.list_inbox_workspace(p_status=>null,p_before_at=>(select updated_at from public.list_inbox_workspace(p_status=>null,p_limit=>1)),p_before_id=>(select conversation_id from public.list_inbox_workspace(p_status=>null,p_limit=>1)))),1::bigint,'Keyset cursor returns only remaining older thread');
select throws_ok($$select public.update_conversation_metadata(auth.uid(),(select id from fixture_ids where kind='conversation'),3,'ARCHIVED',null,'NORMAL',array[''])$$,'23514',null,'Empty tags rejected');
select throws_ok($$update public.conversation_unread_flags set forced=false$$,'42501',null,'Read state cannot bypass actor RPC');
reset role;
set local role anon;
select throws_ok($$select * from public.list_inbox_workspace()$$,'42501',null,'Anonymous inbox access denied');
reset role;
select * from finish();
rollback;
