begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,raw_user_meta_data) values('db430000-0000-4000-8000-000000000001','processing-admin@example.test','{}'),('db430000-0000-4000-8000-000000000002','processing-staff@example.test','{}'),('db430000-0000-4000-8000-000000000003','processing-admin2@example.test','{}');
update public.profiles set is_active = true where id in ('db430000-0000-4000-8000-000000000001','db430000-0000-4000-8000-000000000002','db430000-0000-4000-8000-000000000003');
insert into public.user_roles (user_id, role) values ('db430000-0000-4000-8000-000000000001','STAFF'),('db430000-0000-4000-8000-000000000002','STAFF'),('db430000-0000-4000-8000-000000000003','STAFF');

insert into user_roles(user_id,role) values('db430000-0000-4000-8000-000000000001','ADMIN'),('db430000-0000-4000-8000-000000000003','ADMIN');
create temp table fx(k text primary key,id uuid);grant all on fx to authenticated,service_role;
create temp table data(k text primary key,v jsonb);grant all on data to authenticated,service_role;
create function pg_temp.suppressed() returns boolean language sql security definer set search_path=public as $$select communication_is_suppressed('SMS','+13035550943',null)$$;
insert into fx select k,gen_random_uuid() from unnest(array['retry','retry2']) k;
set local role service_role;
select set_config('request.jwt.claims','{"role":"service_role"}',true);
insert into fx select 'event',id from receive_communication_event('twilio','4300-stop','SM4300','inbound',repeat('a',64),'{"from":"+13035550943","to":"+13035550000","body":"STOP","opt_action":"STOP"}');
reset role;
-- Initial fixture starts at nine recorded failures, followed by an actual tenth claim/release.
update communication_provider_events set attempts=9,cycle_attempts=9,last_error='provider_fetch_or_persistence_retry' where id=(select id from fx where k='event');
set local role service_role;
insert into fx select 'lease',lease_token from claim_communication_event();
insert into data select 'release',release_communication_event_outcome((select id from fx where k='event'),(select id from fx where k='lease'),'provider_fetch_or_persistence_retry',false);
select is((select v->>'state' from data where k='release'),'review','Tenth failure returns durable review, not retry pending');
select is((select v->>'attempts' from data where k='release'),'10','Lifetime attempt count preserved');
select is((select v->>'cycle_attempts' from data where k='release'),'10','Cycle allowance exhausted');
select ok(pg_temp.suppressed(),'STOP remains suppressed in exhausted review');
reset role;
insert into data select 'original',jsonb_build_object('provider',provider,'event_id',event_id,'resource_id',resource_id,'payload_hash',payload_hash,'metadata',metadata) from communication_provider_events where id=(select id from fx where k='event');
insert into data select 'before',jsonb_build_object('inbound',(select count(*) from communication_inbound),'assignments',(select count(*) from communication_inbound_assignments),'consent',(select count(*) from sms_consent),'preferences',(select count(*) from communication_phone_preferences),'suppressions',(select count(*) from communication_suppressions),'deliveries',(select count(*) from communication_delivery_events));
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"db430000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select throws_ok($$select * from communication_provider_events$$,'42501',null,'Staff direct raw metadata and lease access removed');
select ok(not (list_communication_processing_queue('review')#>'{events,0}' ? 'lease_token'),'Staff queue excludes lease token');
select ok(not (list_communication_processing_queue('review')#>'{events,0}' ? 'metadata'),'Staff queue excludes raw metadata');
select throws_ok($$select preview_communication_event_retry((select id from fx where k='event'))$$,'42501',null,'Staff cannot preview administrator retry');
select throws_ok($$select requeue_communication_event((select id from fx where k='retry'),(select id from fx where k='event'),repeat('a',64),'provider_recovered',true)$$,'42501',null,'Staff cannot requeue');
select set_config('request.jwt.claims','{"sub":"db430000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into data select 'preview',preview_communication_event_retry((select id from fx where k='event'));
select is((select v->>'eligible' from data where k='preview'),'true','Only exhausted generic retry is eligible');
select throws_ok($$select requeue_communication_event((select id from fx where k='retry'),(select id from fx where k='event'),repeat('b',64),'provider_recovered',true)$$,'40001',null,'Changed work hash cannot requeue');
select throws_ok($$select requeue_communication_event((select id from fx where k='retry'),(select id from fx where k='event'),(select v->>'expected_work_hash' from data where k='preview'),'unsafe provider text',true)$$,'23514',null,'Retry reason bounded to safe enum');
select lives_ok($$select requeue_communication_event((select id from fx where k='retry'),(select id from fx where k='event'),(select v->>'expected_work_hash' from data where k='preview'),'provider_recovered',true)$$,'Administrator requeues exact reviewed failure');
select lives_ok($$select requeue_communication_event((select id from fx where k='retry'),(select id from fx where k='event'),(select v->>'expected_work_hash' from data where k='preview'),'provider_recovered',true)$$,'Exact lost-response retry returns original action');
select throws_ok($$select requeue_communication_event((select id from fx where k='retry'),(select id from fx where k='event'),(select v->>'expected_work_hash' from data where k='preview'),'processor_repaired',true)$$,'23505',null,'Altered UUID retry denied');
select throws_ok($$select requeue_communication_event((select id from fx where k='retry2'),(select id from fx where k='event'),(select v->>'expected_work_hash' from data where k='preview'),'provider_recovered',true)$$,'40001',null,'Competing stale retry cannot reset cycle twice');
select is((recover_communication_event_retry((select id from fx where k='retry'))).cycle_no,1,'Owned exact receipt recovery');
select is(jsonb_array_length(list_communication_event_retries()->'retries'),1,'Retry remains discoverable after browser pointer lost');
select set_config('request.jwt.claims','{"sub":"db430000-0000-4000-8000-000000000003","role":"authenticated"}',true);
select ok(recover_communication_event_retry((select id from fx where k='retry')) is null,'Other administrator cannot recover owned action');
select is(jsonb_array_length(list_communication_event_retries()->'retries'),0,'Discovery actor-scoped');
set local role service_role;
select set_config('request.jwt.claims','{"role":"service_role"}',true);
select ok(pg_temp.suppressed(),'Requeued STOP still suppresses');
insert into data select 'claimed',to_jsonb(claim_communication_event());
select is((select v->>'attempts' from data where k='claimed'),'11','New cycle preserves lifetime attempts');
select is((select v->>'cycle_attempts' from data where k='claimed'),'1','New cycle starts bounded allowance');
select ok(pg_temp.suppressed(),'Claimed STOP still suppresses');
select throws_ok($$select release_communication_event_outcome((select id from fx where k='event'),(select id from fx where k='lease'),'provider_fetch_or_persistence_retry',false)$$,'40001',null,'Old cycle lease cannot release new worker');
reset role;
select is(jsonb_build_object('provider',provider,'event_id',event_id,'resource_id',resource_id,'payload_hash',payload_hash,'metadata',metadata),(select v from data where k='original'),'Signed facts unchanged across retry') from communication_provider_events where id=(select id from fx where k='event');
select is(jsonb_build_object('inbound',(select count(*) from communication_inbound),'assignments',(select count(*) from communication_inbound_assignments),'consent',(select count(*) from sms_consent),'preferences',(select count(*) from communication_phone_preferences),'suppressions',(select count(*) from communication_suppressions),'deliveries',(select count(*) from communication_delivery_events)),(select v from data where k='before'),'Retry never assigns, changes consent, records delivery or inserts content');
update communication_provider_events set lease_expires_at=clock_timestamp()-interval '1 second' where id=(select id from fx where k='event');
set local role service_role;
select throws_ok($$select release_communication_event_outcome((select id from fx where k='event'),(select (v->>'lease_token')::uuid from data where k='claimed'),'provider_fetch_or_persistence_retry',false)$$,'40001',null,'Expired current lease cannot release');
select throws_ok($$select complete_inbound_communication((select id from fx where k='event'),(select (v->>'lease_token')::uuid from data where k='claimed'),'+13035550943','+13035550000','','STOP',null,null,'{}','[]',now(),'STOP')$$,'40001',null,'Expired current lease cannot complete inbound');
select throws_ok($$select complete_communication_status((select id from fx where k='event'),(select (v->>'lease_token')::uuid from data where k='claimed'))$$,'40001',null,'Expired current lease cannot complete status');
reset role;
-- Simulate final expired attempt; claims stop at ten instead of resetting indefinitely.
update communication_provider_events set attempts=20,cycle_attempts=10 where id=(select id from fx where k='event');
set local role service_role;
select ok(claim_communication_event() is null,'Exhausted crashed lease cannot claim an eleventh cycle attempt');
reset role;
select is((select last_error from communication_provider_events where id=(select id from fx where k='event')),'worker_lease_expired','Crash exhaustion retained distinctly');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"db430000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select is(preview_communication_event_retry((select id from fx where k='event'))->>'eligible','false','Crash-only exhaustion not silently released');
select throws_ok($$select requeue_communication_event((select id from fx where k='retry2'),(select id from fx where k='event'),preview_communication_event_retry((select id from fx where k='event'))->>'expected_work_hash','provider_recovered',true)$$,'23514',null,'Crash-only evidence cannot authorize retry');
reset role;
update communication_provider_events set last_error='provider_content_requires_review' where id=(select id from fx where k='event');
set local role authenticated;
select is(preview_communication_event_retry((select id from fx where k='event'))->>'eligible','false','Content mismatch review cannot be retried by generic recovery');
select throws_ok($$select requeue_communication_event((select id from fx where k='retry2'),(select id from fx where k='event'),preview_communication_event_retry((select id from fx where k='event'))->>'expected_work_hash','provider_recovered',true)$$,'23514',null,'Content review remains unresolved');
select throws_ok($$select list_communication_processing_queue(null,null,null,101)$$,'23514',null,'Unbounded list denied');
reset role;
select throws_ok($$update communication_provider_events set metadata='{}' where id=(select id from fx where k='event')$$,'23514',null,'Signed receipt metadata cannot be rewritten');
select throws_ok($$delete from communication_event_retry_actions$$,'23514',null,'Administrator retry history immutable');
select throws_ok($$delete from communication_processing_history$$,'23514',null,'Attempt history immutable');
select throws_ok($$delete from communication_provider_events where id=(select id from fx where k='event')$$,'23514',null,'Original event retained');
select ok((select count(*)>5 from communication_processing_history where event_id=(select id from fx where k='event')),'Transitions retain prior processing history');
update profiles set is_active=false where id='db430000-0000-4000-8000-000000000001';
set local role authenticated;
select throws_ok($$select recover_communication_event_retry((select id from fx where k='retry'))$$,'42501',null,'Inactive administrator cannot recover');
set local role anon;
select throws_ok($$select list_communication_processing_queue()$$,'42501',null,'Anonymous queue denied');
select * from finish();rollback;
