begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select no_plan();
-- FIXTURE_BEGIN
insert into auth.users(id,email,raw_user_meta_data) values
 ('a5510000-0000-4000-8000-000000000001','native-rx-dvm@example.test','{}'),
 ('a5510000-0000-4000-8000-000000000002','native-rx-staff@example.test','{}'),
 ('a5510000-0000-4000-8000-000000000003','native-rx-uncommissioned@example.test','{}'),
 ('a5510000-0000-4000-8000-000000000004','native-rx-admin@example.test','{}');
update profiles set full_name='Synthetic prescriber' where id='a5510000-0000-4000-8000-000000000001';
insert into user_roles(user_id,role) values('a5510000-0000-4000-8000-000000000001','DVM'),('a5510000-0000-4000-8000-000000000001','ADMIN'),('a5510000-0000-4000-8000-000000000003','DVM'),('a5510000-0000-4000-8000-000000000004','ADMIN');
create temp table fx(k text primary key,id uuid);create temp table data(k text primary key,v jsonb);grant all on fx,data to authenticated;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"a5510000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'client',id from save_client(auth.uid(),null,null,'Native','Household','+13035550123','native-release@example.test','EMAIL','2619 Synthetic Street',null);
insert into fx select 'pet',id from save_patient(null,(select id from fx where k='client'),null,'Native Patient','Dog',null,null,'unknown',null,'unknown','unknown',null,null,null);
insert into fx select 'product',id from save_catalog_product(null,null,'Synthetic medication','medication','','tablet',100,true);
insert into fx select k,gen_random_uuid() from unnest(array['config','save','draft','sign','save2','draft2']) k;
insert into data values('config-request',jsonb_build_object('user_id',auth.uid(),'expected_version',null,'attest_review',true,'fields',jsonb_build_object('active',true,'license_number','SYNTHETIC','license_state','CO','license_expires_on','2099-12-31','practice_name','Synthetic practice','practice_address','2619 Synthetic Street','practice_phone',null,'clinical_review_note','Synthetic fixture only')));
insert into data select 'fields',jsonb_build_object('encounter_id',null,'medication',jsonb_build_object('name','Synthetic medication','strength','Synthetic strength','form','Synthetic form','directions','Synthetic directions only','route','Synthetic route'),'quantity_per_fill','30','unit','tablet','refills_authorized',2,'fulfillment_mode','practice_stock','product_id',(select id from fx where k='product'),'starts_on',(now() at time zone 'America/Denver')::date,'expires_on','2099-12-31');
insert into data select 'save-request',jsonb_build_object('draft_id',(select id from fx where k='draft'),'pet_id',(select id from fx where k='pet'),'client_id',(select id from fx where k='client'),'expected_version',null,'fields',v) from data where k='fields';
-- FIXTURE_END
select configure_native_prescriber((select id from fx where k='config'),(select v from data where k='config-request'));
select save_native_prescription_draft((select id from fx where k='save'),(select v from data where k='save-request'));
insert into data select 'sign-request',jsonb_build_object('draft_id',(select id from fx where k='draft'),'pet_id',(select id from fx where k='pet'),'expected_version',1,'expected_context_hash',preview_native_prescription_sign((select id from fx where k='draft'),1)->>'context_hash','signature_name','Synthetic prescriber','attest_review',true);
insert into data select 'sign-receipt',sign_native_prescription((select id from fx where k='sign'),(select v from data where k='sign-request'));
insert into fx select k,gen_random_uuid() from unnest(array['release','release-fill','release-pickup','release-cancel','stale','invoice','lot','dispense','pickup','cancel']) k;
create function pg_temp.preview_native_release(selection jsonb) returns jsonb language sql as $$select preview_record_release_v10((select id from fx where k='pet'),(select id from fx where k='client'),'EMAIL','native-release@example.test',selection)$$;
create function pg_temp.confirm_native_release(id uuid,selection jsonb,preview jsonb) returns public.record_releases language sql as $$select confirm_record_release(id,(select id from fx where k='pet'),(select id from fx where k='client'),'EMAIL','native-release@example.test',selection,preview->'snapshot',preview->>'source_hash',true)$$;
insert into data select 'selection',jsonb_build_object('native_prescription_ids',jsonb_build_array(id)) from fx where k='sign';
insert into data select 'preview',pg_temp.preview_native_release(v) from data where k='selection';
select is((select v#>>'{snapshot,schema_version}' from data where k='preview'),'10','Native-only preview uses schema10');
select is(jsonb_array_length((select v#>'{snapshot,native_prescriptions}' from data where k='preview')),1,'Exactly one selected authorization');
select is(jsonb_array_length((select v#>'{snapshot,native_dispenses}' from data where k='preview')),0,'Authorization selection does not implicitly release fills');
select is((select v#>'{snapshot,native_prescriptions,0,artifact}' from data where k='preview'),(select v#>'{result,artifact}' from data where k='sign-receipt'),'Full signed artifact retained exactly');
select is(pg_temp.preview_native_release((select v from data where k='selection')),(select v from data where k='preview'),'No observation timestamp makes unchanged preview drift');
select ok(not ((select v#>'{snapshot,native_prescriptions,0}' from data where k='preview') ? 'context'),'Internal signing context excluded');
select ok(not ((select v#>'{snapshot,native_prescriptions,0,status}' from data where k='preview') ? 'checked_at'),'Status excludes volatile timestamp');
select is((select v#>>'{snapshot,native_prescriptions,0,usage,dispensed_quantity}' from data where k='preview'),'0.000','Usage records known native zero');
select is((select v#>>'{snapshot,native_prescriptions,0,usage,external_fulfillment}' from data where k='preview'),'unknown','Outside fulfillment remains unknown');
select throws_ok($$select pg_temp.preview_native_release('{}')$$,'23514',null,'Completely empty selection rejected');
select throws_ok($$select pg_temp.preview_native_release('{"unexpected":[]}')$$,'23514',null,'Unknown selection key rejected');
select throws_ok($$select pg_temp.preview_native_release('{"native_prescription_ids":null}')$$,'23514',null,'Null array rejected');
select throws_ok($$select pg_temp.preview_native_release('{"native_prescription_ids":[1]}')$$,'23514',null,'Nonstring ID rejected');
select throws_ok($$select pg_temp.preview_native_release('{"native_prescription_ids":["invalid"]}')$$,'23514',null,'Invalid UUID rejected');
select throws_ok($$select pg_temp.preview_native_release(jsonb_build_object('native_prescription_ids',jsonb_build_array((select id from fx where k='sign'),(select id from fx where k='sign'))))$$,'23514',null,'Duplicate authorization rejected');
select throws_ok($$select pg_temp.preview_native_release(jsonb_build_object('native_prescription_ids',(select jsonb_agg(gen_random_uuid()) from generate_series(1,21))))$$,'23514',null,'Family bound enforced before lookup');
select throws_ok($$select pg_temp.preview_native_release(jsonb_build_object('native_prescription_ids',jsonb_build_array((select id from fx where k='draft'))))$$,'23514',null,'Draft cannot be released as signed authorization');
select throws_ok($$select preview_record_release_v10(gen_random_uuid(),(select id from fx where k='client'),'EMAIL','native-release@example.test',(select v from data where k='selection'))$$,'42501',null,'Wrong patient denied');
select throws_ok($$select preview_record_release_v10((select id from fx where k='pet'),gen_random_uuid(),'EMAIL','native-release@example.test',(select v from data where k='selection'))$$,'42501',null,'Wrong household denied');
select throws_ok($$select preview_record_release_v10((select id from fx where k='pet'),(select id from fx where k='client'),'EMAIL','other@example.test',(select v from data where k='selection'))$$,'42501',null,'Other recipient denied');
select is(jsonb_array_length(list_record_release_sources_v10((select id from fx where k='pet'))->'native_prescription_ids'),1,'Discovery includes signed authorization');
select is(jsonb_array_length(list_record_release_sources_v10((select id from fx where k='pet'),1)->'native_prescription_ids'),0,'Native discovery offset honored');
select is((select_all_record_release_sources_v10((select id from fx where k='pet'))#>'{selection,native_prescription_ids}'),(select v->'native_prescription_ids' from data where k='selection'),'Select-all includes exact native family');
reset role;
insert into record_release_policy(id,enabled,accepted_schema_version,accepted_by,accepted_at,acceptance_reference) values(true,true,9,'Synthetic reviewer',now(),'TEST ONLY') on conflict(id) do update set enabled=true,accepted_schema_version=9,accepted_by=excluded.accepted_by,accepted_at=excluded.accepted_at,acceptance_reference=excluded.acceptance_reference;
set local role authenticated;
select throws_ok($$select pg_temp.confirm_native_release((select id from fx where k='release'),(select v from data where k='selection'),(select v from data where k='preview'))$$,'42501',null,'Acceptance9 does not authorize schema10');
select is(list_record_release_sources_v10((select id from fx where k='pet'))->>'policy_v10_accepted','false','Discovery reports explicit acceptance10 missing');
reset role;update record_release_policy set accepted_schema_version=10;set local role authenticated;
insert into data select 'release',to_jsonb(pg_temp.confirm_native_release((select id from fx where k='release'),(select v from data where k='selection'),(select v from data where k='preview')));
select is(to_jsonb(pg_temp.confirm_native_release((select id from fx where k='release'),(select v from data where k='selection'),(select v from data where k='preview'))),(select v from data where k='release'),'Exact UUID retry preserves saved receipt');
select throws_ok($$select pg_temp.confirm_native_release((select id from fx where k='release'),'{"native_dispense_ids":[]}',(select v from data where k='preview'))$$,'23514',null,'Changed request cannot reuse release UUID');
select is(read_record_release((select id from fx where k='release'))->>'eligible','true','Current native release is eligible');
reset role;
select is((select count(*)::int from record_release_sources where release_id=(select id from fx where k='release') and source_kind='native_prescription'),1,'Explicit native registry source recorded');
select is((select count(*)::int from native_dispenses where pet_id=(select id from fx where k='pet')),0,'Release has no dispensing side effect');
select set_config('request.jwt.claims','{"role":"service_role"}',true);
select is(release_preview_v10_internal((select id from fx where k='pet'),(select id from fx where k='client'),'EMAIL','native-release@example.test',(select v from data where k='selection')),(select v from data where k='preview'),'Authorized worker private composition does not require staff auth.uid');
select ok(not has_function_privilege('service_role','public.release_preview_v10_internal(uuid,uuid,text,text,jsonb)','execute'),'Service role cannot call private composition directly');
select ok(not has_function_privilege('authenticated','public.release_native_prescription(uuid,uuid,uuid)','execute'),'Private projection not exposed directly');
select set_config('request.jwt.claims','{"sub":"a5510000-0000-4000-8000-000000000001","role":"authenticated"}',true);set local role authenticated;
select receive_inventory(gen_random_uuid(),(select id from fx where k='lot'),(select id from fx where k='product'),'NATIVE-RELEASE',current_date+365,'Synthetic clinic',100,'Synthetic opening stock');
select create_billing_invoice((select id from fx where k='invoice'),(select id from fx where k='client'));
insert into data select 'target',jsonb_build_object('authorization_id',(select id from fx where k='sign'),'pet_id',(select id from fx where k='pet'),'slot_index',0,'expected_slot_version',null,'invoice_id',(select id from fx where k='invoice'),'quantity','10','allocations',jsonb_build_array(jsonb_build_object('lot_id',(select id from fx where k='lot'),'quantity','10')),'refill',null);
insert into data select 'dispense',record_native_dispense((select id from fx where k='dispense'),v||jsonb_build_object('expected_context_hash',preview_native_dispense(v)->>'context_hash','reason','Synthetic dispensing','attest_alert_review',true,'attest_dispense_review',true)) from data where k='target';
select is(read_record_release((select id from fx where k='release'))->>'eligible','false','Dispensing invalidates aggregate usage in prior release');
select throws_ok($$select pg_temp.confirm_native_release((select id from fx where k='stale'),(select v from data where k='selection'),(select v from data where k='preview'))$$,'40001',null,'Changed usage rejects stale confirmation');
select is(to_jsonb(pg_temp.confirm_native_release((select id from fx where k='release'),(select v from data where k='selection'),(select v from data where k='preview'))),(select v from data where k='release'),'Historical exact retry remains byte-equivalent after source change');
insert into data select 'fill-selection',jsonb_build_object('native_dispense_ids',jsonb_build_array(id)) from fx where k='dispense';
insert into data select 'fill-preview',pg_temp.preview_native_release(v) from data where k='fill-selection';
select is(jsonb_array_length((select v#>'{snapshot,native_prescriptions}' from data where k='fill-preview')),0,'Dispense-only does not fabricate selected parent');
select is((select v#>>'{snapshot,native_dispenses,0,prescription,id}' from data where k='fill-preview'),(select id::text from fx where k='sign'),'Dispense embeds exact required signed context');
select ok(not ((select v#>'{snapshot,native_dispenses,0,artifact}' from data where k='fill-preview') ? 'invoice_id'),'Release excludes invoice identity');
select is((select v#>'{snapshot,native_dispenses,0,artifact}' from data where k='fill-preview'),(select (v#>'{result,dispense,artifact}')-'invoice_id' from data where k='dispense'),'Public dispense artifact is exact redacted projection');
select is((select v#>>'{snapshot,native_dispenses,0,artifact_hash}' from data where k='fill-preview'),(select v#>>'{result,dispense,artifact_hash}' from data where k='dispense'),'Full original artifact hash retained as provenance');
select is((select v#>>'{snapshot,native_dispenses,0,prescription,usage,open_slot,remaining_quantity}' from data where k='fill-preview'),'20.000','Partial fill remainder disclosed');
select is((select v#>'{snapshot,native_dispenses,0,pickup}' from data where k='fill-preview'),'null'::jsonb,'Dispensing does not imply pickup');
insert into data select 'fill-release',to_jsonb(pg_temp.confirm_native_release((select id from fx where k='release-fill'),(select v from data where k='fill-selection'),(select v from data where k='fill-preview')));
insert into data select 'pickup',record_native_pickup((select id from fx where k='pickup'),jsonb_build_object('authorization_id',(select id from fx where k='sign'),'pet_id',(select id from fx where k='pet'),'dispense_id',(select id from fx where k='dispense'),'expected_context_hash',preview_native_pickup((select id from fx where k='dispense'),(select id from fx where k='pet'),null)->>'context_hash','recipient_name','Synthetic recipient','recipient_relationship','Household member','reason','Internal synthetic handoff note','attest_handoff',true,'refill_close',null));
select is(read_record_release((select id from fx where k='release-fill'))->>'eligible','false','Later pickup invalidates selected dispense release');
insert into data select 'pickup-preview',pg_temp.preview_native_release(v) from data where k='fill-selection';
select is((select v#>>'{snapshot,native_dispenses,0,pickup,recipient_name}' from data where k='pickup-preview'),'Synthetic recipient','Pickup identity disclosed separately');
select is((select v#>>'{snapshot,native_dispenses,0,pickup,picked_up_at}' from data where k='pickup-preview'),(select v#>>'{result,picked_up_at}' from data where k='pickup'),'Pickup maps actual saved timestamp');
select ok(not ((select v#>'{snapshot,native_dispenses,0,pickup}' from data where k='pickup-preview') ? 'reason'),'Internal handoff note excluded');
insert into data select 'pickup-release',to_jsonb(pg_temp.confirm_native_release((select id from fx where k='release-pickup'),(select v from data where k='fill-selection'),(select v from data where k='pickup-preview')));
insert into data select 'cancel',cancel_native_prescription((select id from fx where k='cancel'),jsonb_build_object('authorization_id',(select id from fx where k='sign'),'pet_id',(select id from fx where k='pet'),'expected_event_id',null,'expected_context_hash',preview_native_prescription_cancel((select id from fx where k='sign'),(select id from fx where k='pet'))->>'context_hash','reason','Synthetic cancellation','attest_review',true));
select is(read_record_release((select id from fx where k='release-pickup'))->>'eligible','false','Cancellation invalidates dispense-parent context');
insert into data select 'cancel-preview',pg_temp.preview_native_release(v) from data where k='fill-selection';
select is((select v#>>'{snapshot,native_dispenses,0,prescription,status,state}' from data where k='cancel-preview'),'cancelled','Cancelled authorization remains shareable as history');
select is((select v#>>'{snapshot,native_dispenses,0,prescription,status,reason}' from data where k='cancel-preview'),'Synthetic cancellation','Terminal reason disclosed');
select is((select v#>>'{snapshot,native_dispenses,0,artifact,quantity}' from data where k='cancel-preview'),'10.000','Cancellation does not erase actual dispense evidence');
select is(jsonb_array_length(list_record_release_sources_v10((select id from fx where k='pet'))->'native_prescription_ids'),1,'Cancelled history remains discoverable');
select lives_ok($$select pg_temp.confirm_native_release((select id from fx where k='release-cancel'),(select v from data where k='fill-selection'),(select v from data where k='cancel-preview'))$$,'Reviewed canceled history can be confirmed');
reset role;
select ok(exists(select 1 from record_release_events where release_id=(select id from fx where k='release') and kind='source_changed'),'Native invalidation appends immutable release events');
select throws_ok($$select verify_release_source_original_v5('{"schema_version":10,"api_attachments":[],"attachments":[],"selection":{"api_attachment_ids":[]}}','{}',decode('00','hex'))$$,'23514','Original is not an exact selected package file','Schema10 uses canonical original verification rather than legacy bypass');
select set_config('request.jwt.claims','{"sub":"a5510000-0000-4000-8000-000000000002","role":"authenticated"}',true);set local role authenticated;
select throws_ok($$select pg_temp.confirm_native_release((select id from fx where k='release'),(select v from data where k='selection'),(select v from data where k='preview'))$$,'23514',null,'Another actor cannot replay original confirmation');
reset role;select set_config('request.jwt.claims','{"sub":"a5510000-0000-4000-8000-000000000001","role":"authenticated"}',true);update profiles set is_active=false where id='a5510000-0000-4000-8000-000000000002';select set_config('request.jwt.claims','{"sub":"a5510000-0000-4000-8000-000000000002","role":"authenticated"}',true);set local role authenticated;
select throws_ok($$select pg_temp.preview_native_release((select v from data where k='selection'))$$,'42501',null,'Inactive staff denied preview');
select * from finish();rollback;
