begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select no_plan();
insert into auth.users(id,email,raw_user_meta_data) values('e5710000-0000-4000-8000-000000000001','estimate-admin@example.test','{}'),('e5710000-0000-4000-8000-000000000002','estimate-staff@example.test','{}');
update public.profiles set is_active = true where id in ('e5710000-0000-4000-8000-000000000001','e5710000-0000-4000-8000-000000000002');
insert into public.user_roles (user_id, role) values ('e5710000-0000-4000-8000-000000000001','STAFF'),('e5710000-0000-4000-8000-000000000002','STAFF');

insert into user_roles(user_id,role) values('e5710000-0000-4000-8000-000000000001','ADMIN');
create temp table fx(k text primary key,id uuid);create temp table data(k text primary key,v jsonb);grant all on fx,data to authenticated,service_role;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"e5710000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'client',id from save_client(auth.uid(),null,null,'Estimate','Household',null,'estimate@example.test','EMAIL',null,null);
insert into fx select 'client2',id from save_client(auth.uid(),null,null,'Other','Household',null,'other-estimate@example.test','EMAIL',null,null);
insert into fx select 'pet',id from save_patient(null,(select id from fx where k='client'),null,'Estimate Patient','Dog',null,null,'unknown',null,'unknown','unknown',null,null,null);
insert into fx select 'pet2',id from save_patient(null,(select id from fx where k='client2'),null,'Other Patient','Cat',null,null,'unknown',null,'unknown','unknown',null,null,null);
insert into fx select 'product',id from save_catalog_product(null,null,'Synthetic service','service','','visit',5,true);
insert into fx select k,gen_random_uuid() from unnest(array['estimate','estimate2','save','save2','closed','stale','line','line2'])k;
create function pg_temp.estimate_line(p_id uuid,p_quantity text,p_price jsonb,p_reason jsonb default 'null') returns jsonb language sql as $$select jsonb_build_object('id',p_id,'product_id',(select id from fx where k='product'),'product_version',1,'description','Chosen description','kind','service','unit','visit','quantity',p_quantity,'pricing',p_price,'pricing_reason',p_reason)$$;
insert into data select 'fields',jsonb_build_object('title','Care proposal','notes','','terms','Draft requires explicit later approval.','accept_by','2020-02-29','lines',jsonb_build_array(pg_temp.estimate_line((select id from fx where k='line'),'0.5','{"kind":"unit","unit_price_cents":"5"}'),pg_temp.estimate_line((select id from fx where k='line2'),'3','{"kind":"allocated","amount_cents":"0"}','"Included service"')));
insert into data select 'request',jsonb_build_object('estimate_id',(select id from fx where k='estimate'),'client_id',(select id from fx where k='client'),'pet_id',(select id from fx where k='pet'),'expected_version',null,'fields',v) from data where k='fields';
insert into data select 'receipt',save_native_estimate_draft((select id from fx where k='save'),v) from data where k='request';
insert into fx select k,gen_random_uuid() from unnest(array['prep1','prep2','prep3','pub1','pub2','withdraw','closepub'])k;
create function pg_temp.prepare_request(v integer) returns jsonb language sql as $$select jsonb_build_object('target',preview#>'{context,target}','draft_version',v,'expected_source_hash',preview->'source_hash','expected_publication_head',preview#>'{context,publication_head}','replaces_publication_id',preview#>'{context,current_publication_id}') from(select preview_native_estimate_publication((select id from fx where k='estimate'),(select id from fx where k='client'),v)preview)p$$;
create function pg_temp.publish_request(p_key text) returns jsonb language sql as $$select jsonb_build_object('target',v#>'{request,target}','preparation_id',v->'id','expected_draft_version',v#>'{request,draft_version}','expected_publication_head',v#>'{request,expected_publication_head}','expected_content_hash',v->'content_hash','expected_artifact_hash',v#>'{artifact,sha256}','replaces_publication_id',v#>'{request,replaces_publication_id}','attest_document_review',true,'attest_pricing_review',true,'attest_terms_review',true) from data where data.k=p_key$$;
select throws_ok($$select prepare_native_estimate_publication(gen_random_uuid(),pg_temp.prepare_request(1))$$,'23514',null,'Past draft deadline cannot be prepared');
insert into data select 'future-request',jsonb_set(jsonb_set(v,'{expected_version}','1'),'{fields,accept_by}','"2099-12-31"') from data where k='request';
select save_native_estimate_draft(gen_random_uuid(),(select v from data where k='future-request'));
insert into data select 'prep1-request',pg_temp.prepare_request(2);
insert into data select 'prep1',prepare_native_estimate_publication((select id from fx where k='prep1'),v) from data where k='prep1-request';
select is((select v->'artifact' from data where k='prep1'),'null'::jsonb,'Preparation alone captures no bytes and publishes nothing');
select is(read_native_estimate_publication((select id from fx where k='estimate'),(select id from fx where k='client'))->>'current_status','none','No implicit publication');
select is(prepare_native_estimate_publication((select id from fx where k='prep1'),(select v from data where k='prep1-request')),(select v from data where k='prep1'),'Preparation retry exact');
select throws_ok($$select prepare_native_estimate_publication((select id from fx where k='prep1'),jsonb_set((select v from data where k='prep1-request'),'{draft_version}','1'))$$,'23514',null,'Preparation cannot change identity');
select throws_ok($$select prepare_native_estimate_publication(gen_random_uuid(),jsonb_set((select v from data where k='prep1-request'),'{expected_source_hash}',to_jsonb(repeat('0',64))))$$,'40001',null,'Stale reviewed source hash rejected');
insert into data values('html',to_jsonb('<!doctype html><html><head><meta http-equiv="Content-Security-Policy" content="default-src ''none''; style-src ''unsafe-inline''; base-uri ''none''; form-action ''none''"></head><body><p>Synthetic captured estimate: $0.03 &lt;a href=&quot;javascript:alert(1)&quot;&gt;special&lt;/a&gt; &lt;img src=x onerror=&quot;bad&quot;&gt; url(example) @import text</p></body></html>'::text));
select throws_ok($$select capture_native_estimate_publication_artifact((select id from fx where k='prep1'),auth.uid(),(select v->>'content_hash' from data where k='prep1'),1,'')$$,'42501',null,'Staff cannot impersonate artifact renderer');
set local role service_role;select set_config('request.jwt.claims','{"sub":"e5710000-0000-4000-8000-000000000001","role":"service_role"}',true);
select is(native_estimate_capture_context((select id from fx where k='prep1'),'e5710000-0000-4000-8000-000000000001')->'captured','false'::jsonb,'Trusted renderer receives uncaptured context');
select throws_ok($$select native_estimate_capture_context((select id from fx where k='prep1'),'e5710000-0000-4000-8000-000000000002')$$,'42501',null,'Capture context binds creator');
select throws_ok($$select capture_native_estimate_publication_artifact((select id from fx where k='prep1'),'e5710000-0000-4000-8000-000000000001',(select v->>'content_hash' from data where k='prep1'),1,'!!!')$$,'23514',null,'Malformed artifact encoding rejected');
select throws_ok($$select capture_native_estimate_publication_artifact((select id from fx where k='prep1'),'e5710000-0000-4000-8000-000000000001',(select v->>'content_hash' from data where k='prep1'),1,replace(encode(convert_to((select v#>>'{}' from data where k='html')||'<script>alert(1)</script>','UTF8'),'base64'),E'\n',''))$$,'23514',null,'Active HTML capture rejected');
select throws_ok($$select capture_native_estimate_publication_artifact((select id from fx where k='prep1'),'e5710000-0000-4000-8000-000000000001',(select v->>'content_hash' from data where k='prep1'),1,replace(encode(convert_to((select v#>>'{}' from data where k='html')||'<p onclick="bad()">bad</p>','UTF8'),'base64'),E'\n',''))$$,'23514',null,'Literal active HTML attribute rejected');
insert into data select 'artifact',capture_native_estimate_publication_artifact((select id from fx where k='prep1'),'e5710000-0000-4000-8000-000000000001',(select v->>'content_hash' from data where k='prep1'),1,replace(encode(convert_to((select v#>>'{}' from data where k='html'),'UTF8'),'base64'),E'\n',''));
select is(capture_native_estimate_publication_artifact((select id from fx where k='prep1'),'e5710000-0000-4000-8000-000000000001',(select v->>'content_hash' from data where k='prep1'),1,replace(encode(convert_to((select v#>>'{}' from data where k='html'),'UTF8'),'base64'),E'\n','')),(select v from data where k='artifact'),'Exact byte capture retry permits escaped hostile prose');
select throws_ok($$select capture_native_estimate_publication_artifact((select id from fx where k='prep1'),'e5710000-0000-4000-8000-000000000001',(select v->>'content_hash' from data where k='prep1'),1,replace(encode(convert_to((select v#>>'{}' from data where k='html')||' ','UTF8'),'base64'),E'\n',''))$$,'23514',null,'Even trailing-space artifact changes rejected');
set local role authenticated;select set_config('request.jwt.claims','{"sub":"e5710000-0000-4000-8000-000000000001","role":"authenticated"}',true);
update data set v=recover_native_estimate_preparation((select id from fx where k='prep1')) where k='prep1';
select is(convert_from(decode(read_native_estimate_publication_artifact((select id from fx where k='prep1'),(select id from fx where k='client'),(select v->>'sha256' from data where k='artifact'))->>'content_base64','base64'),'UTF8'),(select v#>>'{}' from data where k='html'),'Stored artifact bytes returned exactly');
select set_config('request.jwt.claims','{"sub":"e5710000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select throws_ok($$select read_native_estimate_publication_artifact((select id from fx where k='prep1'),(select id from fx where k='client'),(select v->>'sha256' from data where k='artifact'))$$,'42501',null,'Unpublished artifact creator-only');
select set_config('request.jwt.claims','{"sub":"e5710000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into data select 'pub1-request',pg_temp.publish_request('prep1');
select throws_ok($$select publish_native_estimate(gen_random_uuid(),jsonb_set((select v from data where k='pub1-request'),'{attest_pricing_review}','false'))$$,'23514',null,'Pricing review explicit');
select throws_ok($$select publish_native_estimate(gen_random_uuid(),jsonb_set((select v from data where k='pub1-request'),'{expected_artifact_hash}',to_jsonb(repeat('0',64))))$$,'23514',null,'Publish binds exact bytes');
insert into data select 'pub1',publish_native_estimate((select id from fx where k='pub1'),v) from data where k='pub1-request';
select is(publish_native_estimate((select id from fx where k='pub1'),(select v from data where k='pub1-request')),(select v from data where k='pub1'),'Publication retry exact');
select is(read_native_estimate_publication((select id from fx where k='estimate'),(select id from fx where k='client'))->>'current_status','open','Reviewed captured publication becomes open');
select is(close_native_estimate_publication_operation((select id from fx where k='pub1'),jsonb_build_object('kind','publish','request',(select v from data where k='pub1-request')))->'receipt',(select v from data where k='pub1'),'Close recovers already published outcome');
-- Draft edits do not alter publication. Catalog changes do not reprice the saved quote.
select save_native_estimate_draft(gen_random_uuid(),jsonb_set(jsonb_set((select v from data where k='future-request'),'{expected_version}','2'),'{fields,title}','"Updated draft"'));
select is(read_native_estimate_publication((select id from fx where k='estimate'),(select id from fx where k='client'))#>>'{current,draft_version}','2','New draft not implicitly published');
select save_catalog_product((select id from fx where k='product'),1,'Catalog rename','service','','visit',9,false);
insert into data select 'prep2-request',pg_temp.prepare_request(3);
insert into data select 'prep2',prepare_native_estimate_publication((select id from fx where k='prep2'),v) from data where k='prep2-request';
select is((select v#>>'{snapshot,total_cents}' from data where k='prep2'),'3','Publication preserves saved prices despite inactive repriced catalog');
set local role service_role;select set_config('request.jwt.claims','{"sub":"e5710000-0000-4000-8000-000000000001","role":"service_role"}',true);
select capture_native_estimate_publication_artifact((select id from fx where k='prep2'),'e5710000-0000-4000-8000-000000000001',(select v->>'content_hash' from data where k='prep2'),1,replace(encode(convert_to((select v#>>'{}' from data where k='html'),'UTF8'),'base64'),E'\n',''));
set local role authenticated;select set_config('request.jwt.claims','{"sub":"e5710000-0000-4000-8000-000000000001","role":"authenticated"}',true);
update data set v=recover_native_estimate_preparation((select id from fx where k='prep2')) where k='prep2';
insert into data select 'pub2-stale',pg_temp.publish_request('prep2');
select save_client(auth.uid(),(select id from fx where k='client'),1,'Changed','Household',null,'estimate@example.test','EMAIL',null,null);
select throws_ok($$select publish_native_estimate((select id from fx where k='closepub'),(select v from data where k='pub2-stale'))$$,'40001',null,'Display change requires new captured publication review');
insert into data select 'closure',close_native_estimate_publication_operation((select id from fx where k='closepub'),jsonb_build_object('kind','publish','request',v)) from data where k='pub2-stale';
select is((select v->>'status' from data where k='closure'),'closed_unrecorded','Stale uncertain publication safely closed');
select is(close_native_estimate_publication_operation((select id from fx where k='closepub'),jsonb_build_object('kind','publish','request',(select v from data where k='pub2-stale'))),(select v from data where k='closure'),'Exact closure retry');
select throws_ok($$select publish_native_estimate((select id from fx where k='closepub'),(select v from data where k='pub2-stale'))$$,'23514',null,'Delayed publish cannot commit closed ID');
select is(recover_native_estimate_publication_operation((select id from fx where k='pub1')),(select v from data where k='pub1'),'Old receipt survives catalog/contact/draft change');
insert into data select 'prep3',prepare_native_estimate_publication((select id from fx where k='prep3'),pg_temp.prepare_request(3));
set local role service_role;select set_config('request.jwt.claims','{"sub":"e5710000-0000-4000-8000-000000000001","role":"service_role"}',true);
select capture_native_estimate_publication_artifact((select id from fx where k='prep3'),'e5710000-0000-4000-8000-000000000001',(select v->>'content_hash' from data where k='prep3'),1,replace(encode(convert_to((select v#>>'{}' from data where k='html'),'UTF8'),'base64'),E'\n',''));
set local role authenticated;select set_config('request.jwt.claims','{"sub":"e5710000-0000-4000-8000-000000000001","role":"authenticated"}',true);
update data set v=recover_native_estimate_preparation((select id from fx where k='prep3')) where k='prep3';
insert into data select 'pub2',publish_native_estimate((select id from fx where k='pub2'),pg_temp.publish_request('prep3'));
select is(read_native_estimate_published_revision((select id from fx where k='pub1'),(select id from fx where k='client'))->>'status','superseded','Explicit replacement supersedes previous publication');
select is(read_native_estimate_publication_history((select id from fx where k='estimate'),(select id from fx where k='client'),null,1)->'has_more','true'::jsonb,'Publication history paginated');
select is(read_native_estimate_publication_history((select id from fx where k='estimate'),(select id from fx where k='client'),2,1)#>>'{events,0,id}',(select id::text from fx where k='pub1'),'History preserves original publication');
insert into data select 'withdraw-request',jsonb_build_object('target',v#>'{result,target}','publication_id',(select id from fx where k='pub2'),'expected_publication_head',jsonb_build_object('event_id',v->'id','version',v#>'{result,version}','record_hash',v#>'{result,record_hash}'),'reason','Synthetic withdrawal','attest_review',true) from data where k='pub2';
insert into data select 'withdraw',withdraw_native_estimate((select id from fx where k='withdraw'),v) from data where k='withdraw-request';
select is(read_native_estimate_publication((select id from fx where k='estimate'),(select id from fx where k='client'))->>'current_status','withdrawn','Withdrawal closes current proposal');
select is(read_native_estimate_publication((select id from fx where k='estimate'),(select id from fx where k='client'))->'current','null'::jsonb,'Withdrawn proposal no longer current');
select is(read_native_estimate_published_revision((select id from fx where k='pub2'),(select id from fx where k='client'))->>'status','withdrawn','Withdrawn history explicit');
select is(withdraw_native_estimate((select id from fx where k='withdraw'),(select v from data where k='withdraw-request')),(select v from data where k='withdraw'),'Withdrawal exact retry');
select throws_ok($$select withdraw_native_estimate(gen_random_uuid(),(select v from data where k='withdraw-request'))$$,'40001',null,'Stale withdrawal cannot repeat');
select set_config('request.jwt.claims','{"sub":"e5710000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select lives_ok($$select read_native_estimate_publication_artifact((select id from fx where k='prep1'),(select id from fx where k='client'),(select v->>'sha256' from data where k='artifact'))$$,'Active staff can read superseded published bytes');
select throws_ok($$select recover_native_estimate_publication_operation((select id from fx where k='pub1'))$$,'42501',null,'Mutation recovery creator-only');
select throws_ok($$select close_native_estimate_publication_operation((select id from fx where k='closepub'),jsonb_build_object('kind','publish','request',(select v from data where k='pub2-stale')))$$,'42501',null,'Closure recovery creator-only');
select throws_ok($$select read_native_estimate_published_revision((select id from fx where k='pub1'),(select id from fx where k='client2'))$$,'23514',null,'Historical publication household scoped');
reset role;
select ok(not has_function_privilege('authenticated','native_estpub_record(uuid,jsonb)','execute'),'Internal mutation helper private');
select ok(not has_function_privilege('service_role','publish_native_estimate(uuid,jsonb)','execute'),'Service role cannot publish for staff');
select ok(not has_table_privilege('authenticated','native_estimate_publication_artifacts','select'),'Raw bytes not exposed');
select is((select count(*) from billing_invoices where client_id=(select id from fx where k='client')),0::bigint,'Publication creates no invoice or payment claim');
select is((select count(*) from communication_outbox where client_id=(select id from fx where k='client')),0::bigint,'Publication does not send messages');
select is((select(v#>>'{snapshot,acceptance,expires_at}')::timestamptz from data where k='prep1'),'2100-01-01T07:00:00Z'::timestamptz,'Acceptance ends at next Denver midnight');
select is((native_estpub_snapshot(gen_random_uuid(),jsonb_set((select v->'context' from data where k='prep1'),'{draft,fields,accept_by}','"2027-03-14"'),clock_timestamp())#>>'{acceptance,expires_at}')::timestamptz,'2027-03-15T06:00:00Z'::timestamptz,'Spring daylight-saving deadline uses Denver calendar midnight');
select is((native_estpub_snapshot(gen_random_uuid(),jsonb_set((select v->'context' from data where k='prep1'),'{draft,fields,accept_by}','"2027-11-07"'),clock_timestamp())#>>'{acceptance,expires_at}')::timestamptz,'2027-11-08T07:00:00Z'::timestamptz,'Fall daylight-saving deadline uses Denver calendar midnight');
set constraints all immediate;
create function pg_temp.corrupt_publication_bytes() returns void language plpgsql as $$begin
 alter table native_estimate_publication_artifacts disable trigger native_estimate_publication_immutable;
 update native_estimate_publication_artifacts set bytes=bytes||convert_to(' ','UTF8') where id=(select id from fx where k='prep1');
 alter table native_estimate_publication_artifacts enable trigger native_estimate_publication_immutable;
 perform native_estpub_lifecycle((select id from fx where k='estimate'));raise exception 'Corrupt bytes accepted' using errcode='P0001';end $$;
select throws_ok($$select pg_temp.corrupt_publication_bytes()$$,'23514',null,'Historical byte corruption fails current lifecycle verification');
select is(native_estpub_receipt((select id from fx where k='pub1')),(select v from data where k='pub1'),'Rejected corruption leaves history exact');
select * from finish();rollback;
