begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select no_plan();
insert into auth.users(id,email,raw_user_meta_data) values('e5710000-0000-4000-8000-000000000001','estimate-admin@example.test','{}'),('e5710000-0000-4000-8000-000000000002','estimate-staff@example.test','{}');
update public.profiles set is_active = true where id in ('e5710000-0000-4000-8000-000000000001','e5710000-0000-4000-8000-000000000002');
insert into public.user_roles (user_id, role) values ('e5710000-0000-4000-8000-000000000001','STAFF'),('e5710000-0000-4000-8000-000000000002','STAFF');

insert into user_roles(user_id,role) values('e5710000-0000-4000-8000-000000000001','ADMIN');
create temp table fx(k text primary key,id uuid);create temp table data(k text primary key,v jsonb);grant all on fx,data to authenticated,service_role;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"e5710000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'client',id from save_client(auth.uid(),null,null,'Estimate','Household',null,'estimate@example.test','EMAIL',null,null);
insert into fx select 'client2',id from save_client(auth.uid(),null,null,'Other','Household',null,'other-estimate@example.test','EMAIL',null,null);
insert into fx select 'pet',id from save_patient(null,(select id from fx where k='client'),null,'Estimate Patient','Dog',null,null,'unknown',null,'unknown','unknown',null,null,null);
insert into fx select 'pet2',id from save_patient(null,(select id from fx where k='client2'),null,'Other Patient','Cat',null,null,'unknown',null,'unknown','unknown',null,null,null);
insert into fx select 'product',id from save_catalog_product(null,null,'Synthetic service','service','','visit',5,true);
insert into fx select k,gen_random_uuid() from unnest(array['estimate','estimate2','save','save2','closed','stale','line','line2'])k;
create function pg_temp.estimate_line(p_id uuid,p_quantity text,p_price jsonb,p_reason jsonb default 'null') returns jsonb language sql as $$select jsonb_build_object('id',p_id,'product_id',(select id from fx where k='product'),'product_version',1,'description','Chosen description','kind','service','unit','visit','quantity',p_quantity,'pricing',p_price,'pricing_reason',p_reason)$$;
insert into data select 'fields',jsonb_build_object('title','Care proposal','notes','','terms','Draft requires explicit later approval.','accept_by','2020-02-29','lines',jsonb_build_array(pg_temp.estimate_line((select id from fx where k='line'),'0.5','{"kind":"unit","unit_price_cents":"5"}'),pg_temp.estimate_line((select id from fx where k='line2'),'3','{"kind":"allocated","amount_cents":"0"}','"Included service"')));
insert into data select 'request',jsonb_build_object('estimate_id',(select id from fx where k='estimate'),'client_id',(select id from fx where k='client'),'pet_id',(select id from fx where k='pet'),'expected_version',null,'fields',v) from data where k='fields';
insert into data select 'receipt',save_native_estimate_draft((select id from fx where k='save'),v) from data where k='request';
select is((select v#>>'{result,total_cents}' from data where k='receipt'),'3','Unit half-up rounding plus explicit allocated zero');
select is((select jsonb_array_length(v#>'{result,fields,lines}') from data where k='receipt'),2,'Same catalog product can appear on distinct lines');
select is((select v#>>'{result,fields,accept_by}' from data where k='receipt'),'2020-02-29','Past valid deadline allowed in draft');
select is(recover_native_estimate_draft((select id from fx where k='save')),(select v from data where k='receipt'),'Exact creator recovery');
select is(save_native_estimate_draft((select id from fx where k='save'),(select v from data where k='request')),(select v from data where k='receipt'),'Save retry returns exact original');
select is(read_native_estimate_draft((select id from fx where k='estimate'),(select id from fx where k='client'))->'draft',(select v->'result' from data where k='receipt'),'Current read returns complete draft');
select throws_ok($$select save_native_estimate_draft((select id from fx where k='save'),jsonb_set((select v from data where k='request'),'{fields,title}','"Different"'))$$,'23514',null,'Same operation cannot change request');
select throws_ok($$select save_native_estimate_draft(gen_random_uuid(),(select v from data where k='request'))$$,'40001',null,'Repeated create cannot overwrite');
select throws_ok($$select read_native_estimate_draft((select id from fx where k='estimate'),(select id from fx where k='client2'))$$,'23514',null,'Read binds household');
select throws_ok($$select save_native_estimate_draft(gen_random_uuid(),jsonb_set(jsonb_set((select v from data where k='request'),'{estimate_id}',to_jsonb(gen_random_uuid())),'{pet_id}',to_jsonb((select id from fx where k='pet2'))))$$,'23514',null,'Patient must belong to household');
-- Independent input failures happen before attempting any new root write.
select throws_ok(format('select save_native_estimate_draft(gen_random_uuid(),jsonb_set((select v from data where k=''request''),''{fields,lines,0,quantity}'',%L::jsonb))',to_jsonb(bad)::text),'23514',null,'Reject quantity '||bad) from unnest(array['0','01','1.0','.5','1e2','100000000000','0.0001','-1'])bad;
select throws_ok($$select save_native_estimate_draft(gen_random_uuid(),jsonb_set((select v from data where k='request'),'{fields,accept_by}','"2025-02-29"'))$$,'23514',null,'Impossible calendar date rejected');
select throws_ok($$select save_native_estimate_draft(gen_random_uuid(),jsonb_set((select v from data where k='request'),'{fields,lines,1,id}',(select v#>'{fields,lines,0,id}' from data where k='request')))$$,'23514',null,'Line identities unique');
select throws_ok($$select save_native_estimate_draft(gen_random_uuid(),jsonb_set((select v from data where k='request'),'{fields,lines,1,pricing_reason}','null'))$$,'23514',null,'Allocated zero requires reason');
select throws_ok($$select save_native_estimate_draft(gen_random_uuid(),jsonb_set((select v from data where k='request'),'{fields,lines,0,pricing,unit_price_cents}','"0"'))$$,'23514',null,'Zero unit amount requires reason');
select throws_ok($$select save_native_estimate_draft(gen_random_uuid(),jsonb_set((select v from data where k='request'),'{fields,lines,0,pricing,unit_price_cents}','"9223372036854775808"'))$$,'23514',null,'Unit price bigint overflow rejected');
select throws_ok($$select save_native_estimate_draft(gen_random_uuid(),jsonb_set(jsonb_set((select v from data where k='request'),'{fields,lines,0,quantity}','"2"'),'{fields,lines,0,pricing,unit_price_cents}','"9223372036854775807"'))$$,'23514',null,'Line total overflow rejected');
select throws_ok($$select save_native_estimate_draft(gen_random_uuid(),jsonb_set(jsonb_set((select v from data where k='request'),'{fields,lines,0,pricing}','{"kind":"allocated","amount_cents":"9223372036854775807"}'),'{fields,lines,0,pricing_reason}','"Allocation"') )$$,'40001',null,'Maximum exact allocated line passes arithmetic before optimistic conflict');
select throws_ok($$select save_native_estimate_draft(gen_random_uuid(),jsonb_set(jsonb_set(jsonb_set((select v from data where k='request'),'{fields,lines,0,pricing}','{"kind":"allocated","amount_cents":"9223372036854775807"}'),'{fields,lines,0,pricing_reason}','"Allocation"'),'{fields,lines,1,pricing,amount_cents}','"1"'))$$,'23514',null,'Summed exact line totals cannot overflow bigint');
select throws_ok($$select save_native_estimate_draft(gen_random_uuid(),jsonb_set(jsonb_set((select v from data where k='request'),'{fields,lines,0,quantity}','"0.001"'),'{fields,lines,0,pricing,unit_price_cents}','"1"'))$$,'23514',null,'Rounded zero unit amount still requires reason');
-- Version 2 changes prices explicitly; catalog price changes do not rewrite historical drafts.
select save_catalog_product((select id from fx where k='product'),1,'Renamed catalog service','service','','visit',7,true);
insert into data select 'stale-request',jsonb_set(v,'{expected_version}','1') from data where k='request';
select throws_ok($$select save_native_estimate_draft((select id from fx where k='stale'),(select v from data where k='stale-request'))$$,'40001',null,'Stale catalog version rejected');
select is(recover_native_estimate_draft((select id from fx where k='save')),(select v from data where k='receipt'),'Historical receipt independent of current catalog');
insert into data select 'request2',jsonb_set(jsonb_set(jsonb_set(v,'{fields,lines,0,product_version}','2'),'{fields,lines,1,product_version}','2'),'{fields,lines,0,pricing_reason}','"Honor original quote"') from data where k='stale-request';
select throws_ok($$select save_native_estimate_draft(gen_random_uuid(),jsonb_set((select v from data where k='request2'),'{fields,lines,0,pricing_reason}','null'))$$,'23514',null,'Current price override requires reason');
insert into data select 'receipt2',save_native_estimate_draft((select id from fx where k='save2'),v) from data where k='request2';
select is((select v#>>'{result,version}' from data where k='receipt2'),'2','Successful edit appends exact optimistic version');
select is((select v#>'{result,created_at}' from data where k='receipt2'),(select v#>'{result,created_at}' from data where k='receipt'),'Creation timestamp preserved');
select is((select v#>>'{result,fields,lines,0,description}' from data where k='receipt2'),'Chosen description','Catalog rename does not overwrite chosen description');
select throws_ok($$select save_native_estimate_draft(gen_random_uuid(),(select v from data where k='request2'))$$,'40001',null,'Concurrent stale edit rejected');
select throws_ok($$select save_native_estimate_draft(gen_random_uuid(),jsonb_set(jsonb_set((select v from data where k='request2'),'{expected_version}','2'),'{pet_id}',to_jsonb((select id from fx where k='pet2'))))$$,'23514',null,'Patient cannot change on an existing estimate');
select is(read_native_estimate_draft_history((select id from fx where k='estimate'),(select id from fx where k='client'),null,1)#>>'{revisions,0,version}','2','History starts newest');
select is(read_native_estimate_draft_history((select id from fx where k='estimate'),(select id from fx where k='client'),null,1)->'next_before_version','2'::jsonb,'History returns exact continuation');
select is(read_native_estimate_draft_history((select id from fx where k='estimate'),(select id from fx where k='client'),2,1)#>'{revisions,0}',(select v->'result' from data where k='receipt'),'Historical page preserves original complete revision');
select is(read_native_estimate_draft_history((select id from fx where k='estimate'),(select id from fx where k='client'),2,1)->'has_more','false'::jsonb,'History final page explicit');
insert into data select 'closure',close_native_estimate_draft((select id from fx where k='closed'),v) from data where k='stale-request';
select is((select v->>'status' from data where k='closure'),'closed_unrecorded','Stale uncertain operation safely closes');
select is(close_native_estimate_draft((select id from fx where k='closed'),(select v from data where k='stale-request')),(select v from data where k='closure'),'Closure retry exact');
select throws_ok($$select save_native_estimate_draft((select id from fx where k='closed'),(select v from data where k='stale-request'))$$,'23514',null,'Closed UUID cannot commit delayed save');
select throws_ok($$select close_native_estimate_draft((select id from fx where k='closed'),(select v from data where k='request2'))$$,'23514',null,'Closure cannot change original intent');
select is(close_native_estimate_draft((select id from fx where k='save'),(select v from data where k='request'))->'receipt',(select v from data where k='receipt'),'Close of committed operation recovers instead');
insert into data select 'receipt3',save_native_estimate_draft(gen_random_uuid(),jsonb_set(jsonb_set(v,'{estimate_id}',to_jsonb((select id from fx where k='estimate2'))),'{expected_version}','null')) from data where k='request2';
insert into data select 'page',list_native_estimate_drafts((select id from fx where k='client'),null,null,1);
select is((select v->'has_more' from data where k='page'),'true'::jsonb,'List exposes continuation');
select is((select jsonb_array_length(v->'drafts') from data where k='page'),1,'List respects limit');
select is(list_native_estimate_drafts((select id from fx where k='client'),(select(v#>>'{next_cursor,before_at}')::timestamptz from data where k='page'),(select(v#>>'{next_cursor,before_id}')::uuid from data where k='page'),1)#>>'{drafts,0,id}',(select id::text from fx where k='estimate'),'Cursor yields next exact draft');
select throws_ok($$select list_native_estimate_drafts((select id from fx where k='client'),null,gen_random_uuid(),1)$$,'23514',null,'Incomplete list cursor rejected');
select throws_ok($$select read_native_estimate_draft_history((select id from fx where k='estimate'),(select id from fx where k='client'),null,0)$$,'23514',null,'Invalid history limit rejected');
select set_config('request.jwt.claims','{"sub":"e5710000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select throws_ok($$select recover_native_estimate_draft((select id from fx where k='save'))$$,'42501',null,'Other staff cannot recover creator receipt');
select throws_ok($$select close_native_estimate_draft((select id from fx where k='closed'),(select v from data where k='stale-request'))$$,'42501',null,'Other staff cannot recover closure');
select lives_ok($$select read_native_estimate_draft((select id from fx where k='estimate'),(select id from fx where k='client'))$$,'Active staff may read household draft');
reset role;select set_config('request.jwt.claims','{"sub":"e5710000-0000-4000-8000-000000000001","role":"authenticated"}',true);update profiles set is_active=false where id='e5710000-0000-4000-8000-000000000002';set local role authenticated;select set_config('request.jwt.claims','{"sub":"e5710000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select throws_ok($$select list_native_estimate_drafts((select id from fx where k='client'),null,null,10)$$,'42501',null,'Inactive staff denied');
reset role;
select ok(not has_function_privilege('service_role','save_native_estimate_draft(uuid,jsonb)','execute'),'Service cannot impersonate staff');
select ok(not has_function_privilege('anon','read_native_estimate_draft(uuid,uuid)','execute'),'Anonymous read denied');
select ok(not has_function_privilege('authenticated','native_estimate_verified_revision(uuid,integer)','execute'),'Verifier private');
select ok(not has_table_privilege('authenticated','native_estimate_draft_revisions','insert'),'Raw revisions denied');
select throws_ok($$update native_estimate_draft_revisions set record_hash=repeat('0',64)$$,'23514',null,'Revisions immutable');
select is((select count(*) from billing_invoices where client_id in(select id from fx where k in('client','client2'))),0::bigint,'Draft estimates create no invoice');
select is((select count(*) from inventory_movements m join inventory_lots l on l.id=m.lot_id where l.product_id=(select id from fx where k='product')),0::bigint,'Draft estimates create no stock effect');
set constraints all immediate;
create function pg_temp.corrupt_estimate() returns void language plpgsql as $$begin
 alter table native_estimate_draft_revisions disable trigger native_estimate_immutable;
 update native_estimate_draft_revisions set document=jsonb_set(document,'{total_cents}','"99"') where estimate_id=(select id from fx where k='estimate') and version=1;
 alter table native_estimate_draft_revisions enable trigger native_estimate_immutable;
 perform native_estimate_verified_revision((select id from fx where k='estimate'),2);raise exception 'Corrupt revision accepted' using errcode='P0001';
end $$;
select throws_ok($$select pg_temp.corrupt_estimate()$$,'23514',null,'Corrupt historical revision fails current verification');
select is(native_estimate_verified_operation((select id from fx where k='save')),(select v from data where k='receipt'),'Rejected corruption preserves original receipt');
select * from finish();rollback;
