begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select no_plan();
-- FIXTURE_BEGIN
insert into auth.users(id,email,raw_user_meta_data) values
 ('a5510000-0000-4000-8000-000000000001','native-rx-dvm@example.test','{}'),
 ('a5510000-0000-4000-8000-000000000002','native-rx-staff@example.test','{}'),
 ('a5510000-0000-4000-8000-000000000003','native-rx-uncommissioned@example.test','{}'),
 ('a5510000-0000-4000-8000-000000000004','native-rx-admin@example.test','{}');
update public.profiles set is_active = true where id in ('a5510000-0000-4000-8000-000000000001','a5510000-0000-4000-8000-000000000002','a5510000-0000-4000-8000-000000000003','a5510000-0000-4000-8000-000000000004');
insert into public.user_roles (user_id, role) values ('a5510000-0000-4000-8000-000000000001','STAFF'),('a5510000-0000-4000-8000-000000000002','STAFF'),('a5510000-0000-4000-8000-000000000003','STAFF'),('a5510000-0000-4000-8000-000000000004','STAFF');

update profiles set full_name='Synthetic prescriber' where id='a5510000-0000-4000-8000-000000000001';
insert into user_roles(user_id,role) values('a5510000-0000-4000-8000-000000000001','DVM'),('a5510000-0000-4000-8000-000000000001','ADMIN'),('a5510000-0000-4000-8000-000000000003','DVM'),('a5510000-0000-4000-8000-000000000004','ADMIN');
create temp table fx(k text primary key,id uuid);create temp table data(k text primary key,v jsonb);grant all on fx,data to authenticated;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"a5510000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'client',id from save_client(auth.uid(),null,null,'Native','Household',null,null,'EMAIL','2619 Synthetic Street',null);
insert into fx select 'pet',id from save_patient(null,(select id from fx where k='client'),null,'Native Patient','Dog',null,null,'unknown',null,'unknown','unknown',null,null,null);
insert into fx select 'product',id from save_catalog_product(null,null,'Synthetic medication','medication','','tablet',100,true);
insert into fx select k,gen_random_uuid() from unnest(array['config','save','draft','sign','save2','draft2']) k;
insert into data values('config-request',jsonb_build_object('user_id',auth.uid(),'expected_version',null,'attest_review',true,'fields',jsonb_build_object('active',true,'license_number','SYNTHETIC','license_state','CO','license_expires_on','2099-12-31','practice_name','Synthetic practice','practice_address','2619 Synthetic Street','practice_phone',null,'clinical_review_note','Synthetic fixture only')));
insert into data select 'fields',jsonb_build_object('encounter_id',null,'medication',jsonb_build_object('name','Synthetic medication','strength','Synthetic strength','form','Synthetic form','directions','Synthetic directions only','route','Synthetic route'),'quantity_per_fill','30','unit','tablet','refills_authorized',2,'fulfillment_mode','practice_stock','product_id',(select id from fx where k='product'),'starts_on',(now() at time zone 'America/Denver')::date,'expires_on','2099-12-31');
insert into data select 'save-request',jsonb_build_object('draft_id',(select id from fx where k='draft'),'pet_id',(select id from fx where k='pet'),'client_id',(select id from fx where k='client'),'expected_version',null,'fields',v) from data where k='fields';
-- FIXTURE_END
select throws_ok($$select preview_native_prescription_sign((select id from fx where k='draft'),1)$$,'42501','Current native prescriber commissioning required','DVM cannot sign without separate commissioning');
insert into data select 'config-receipt',configure_native_prescriber((select id from fx where k='config'),(select v from data where k='config-request'));
select is(configure_native_prescriber((select id from fx where k='config'),(select v from data where k='config-request')),(select v from data where k='config-receipt'),'Configuration exact retry');
select throws_ok($$select configure_native_prescriber(gen_random_uuid(),(select v from data where k='config-request'))$$,'40001','Prescriber configuration changed','Duplicate first configuration fails');
select ok((list_native_prescribers()->'entries') @> '[{"user_id":"a5510000-0000-4000-8000-000000000001","eligible":true}]','Configured DVM eligible');
select throws_ok($$select configure_native_prescriber(gen_random_uuid(),(select jsonb_set(v||'{"expected_version":1}','{fields,clinical_review_note}',to_jsonb(E'\t\n'::text)) from data where k='config-request'))$$,'23514','Invalid prescription text','Whitespace-only commissioning rejected');
select throws_ok($$select configure_native_prescriber(gen_random_uuid(),(select jsonb_set(v||'{"expected_version":1}','{fields,clinical_review_note}',to_jsonb(chr(160)||chr(65279))) from data where k='config-request'))$$,'23514','Invalid prescription text','Unicode blank commissioning rejected');
reset role;update profiles set full_name=chr(160) where id='a5510000-0000-4000-8000-000000000001';set local role authenticated;
select ok((list_native_prescribers()->'entries') @> '[{"user_id":"a5510000-0000-4000-8000-000000000001","eligible":false}]','Directory rejects malformed signer name consistently');
select throws_ok($$select preview_native_prescription_sign((select id from fx where k='draft'),1)$$,'42501','Current native prescriber commissioning required','Malformed profile cannot sign');
reset role;update profiles set full_name='Synthetic prescriber' where id='a5510000-0000-4000-8000-000000000001';set local role authenticated;
select throws_ok($$select list_native_prescribers(null,101)$$,'23514',null,'Directory bounded');
select set_config('request.jwt.claims','{"sub":"a5510000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select throws_ok($$select configure_native_prescriber(gen_random_uuid(),(select v from data where k='config-request'))$$,'42501','Active administrator required','Staff cannot commission');
insert into data select 'save-receipt',save_native_prescription_draft((select id from fx where k='save'),(select v from data where k='save-request'));
select is((select v#>>'{result,fields,quantity_per_fill}' from data where k='save-receipt'),'30.000','Result quantity canonical');
select is((select v#>>'{request,fields,quantity_per_fill}' from data where k='save-receipt'),'30','Original request quantity exact');
select is(save_native_prescription_draft((select id from fx where k='save'),(select v from data where k='save-request')),(select v from data where k='save-receipt'),'Draft exact retry');
select is(recover_native_prescription_operation((select id from fx where k='save')),(select v from data where k='save-receipt'),'Draft UUID recovery');
select throws_ok($$select save_native_prescription_draft((select id from fx where k='save'),(select jsonb_set(v,'{fields,quantity_per_fill}','"31"') from data where k='save-request'))$$,'23514','Prescription operation identity cannot change','Same UUID altered request fails');
select throws_ok($$select save_native_prescription_draft(gen_random_uuid(),(select v from data where k='save-request'))$$,'40001','Prescription draft changed','Different create UUID cannot replace existing draft');
select throws_ok($$select preview_native_prescription_sign((select id from fx where k='draft'),1)$$,'42501','Configured veterinarian required','Staff cannot preview signing');
select is(read_native_prescription_draft((select id from fx where k='draft'),gen_random_uuid()),null::jsonb,'Wrong patient cannot read draft');
select throws_ok($$select list_native_prescription_drafts((select id from fx where k='pet'),now(),null)$$,'23514',null,'Half cursor rejected');
select throws_ok($$select save_native_prescription_draft(gen_random_uuid(),(select v||'{"forged_actor":true}' from data where k='save-request'))$$,'23514','Exact prescription fields required','Unknown operation field rejected');
select throws_ok($$select save_native_prescription_draft(gen_random_uuid(),(select jsonb_set(v||jsonb_build_object('draft_id',gen_random_uuid()),'{fields,medication,directions}',to_jsonb(E'Synthetic\rdirections'::text)) from data where k='save-request'))$$,'23514','Invalid prescription text','Carriage return rejected');
select throws_ok($$select save_native_prescription_draft(gen_random_uuid(),(select jsonb_set(v||jsonb_build_object('draft_id',gen_random_uuid()),'{fields,medication,name}',to_jsonb(E'\tSynthetic'::text)) from data where k='save-request'))$$,'23514','Invalid prescription text','Boundary whitespace rejected');
select throws_ok($$select save_native_prescription_draft(gen_random_uuid(),(select jsonb_set(v||jsonb_build_object('draft_id',gen_random_uuid()),'{fields,quantity_per_fill}','"0.0001"') from data where k='save-request'))$$,'23514','Invalid prescription quantity','Quantity never silently rounded');
select throws_ok($$select save_native_prescription_draft(gen_random_uuid(),(select jsonb_set(v||jsonb_build_object('draft_id',gen_random_uuid()),'{fields,unit}','"mL"') from data where k='save-request'))$$,'23514','Exact active medication product and unit required','No implicit unit conversion');
select throws_ok($$select save_native_prescription_draft(gen_random_uuid(),(select jsonb_set(v||jsonb_build_object('draft_id',gen_random_uuid()),'{fields,fulfillment_mode}','"external_pharmacy"') from data where k='save-request'))$$,'23514','External orders cannot select stock','External order cannot retain local product');
select throws_ok($$select save_native_prescription_draft(gen_random_uuid(),(select jsonb_set(v||jsonb_build_object('draft_id',gen_random_uuid()),'{fields,refills_authorized}','1001') from data where k='save-request'))$$,'23514','Invalid refill allowance','Refill bound enforced');
select throws_ok($$select save_native_prescription_draft(gen_random_uuid(),(select jsonb_set(v||jsonb_build_object('draft_id',gen_random_uuid()),'{fields,expires_on}','"2026-02-30"') from data where k='save-request'))$$,'23514','Invalid prescription date','Invalid calendar date rejected');
select set_config('request.jwt.claims','{"sub":"a5510000-0000-4000-8000-000000000004","role":"authenticated"}',true);
select throws_ok($$select preview_native_prescription_sign((select id from fx where k='draft'),1)$$,'42501','Configured veterinarian required','ADMIN alone cannot sign');
select set_config('request.jwt.claims','{"sub":"a5510000-0000-4000-8000-000000000003","role":"authenticated"}',true);
select throws_ok($$select preview_native_prescription_sign((select id from fx where k='draft'),1)$$,'42501','Current native prescriber commissioning required','Another DVM cannot inherit commissioning');
select set_config('request.jwt.claims','{"sub":"a5510000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select is(recover_native_prescription_operation((select id from fx where k='save')),null::jsonb,'Other actor cannot recover staff operation');
insert into data select 'preview',preview_native_prescription_sign((select id from fx where k='draft'),1);
insert into data select 'sign-request',jsonb_build_object('draft_id',(select id from fx where k='draft'),'pet_id',(select id from fx where k='pet'),'expected_version',1,'expected_context_hash',v->>'context_hash','signature_name','Synthetic prescriber','attest_review',true) from data where k='preview';
select save_patient_problem(null,(select id from fx where k='pet'),null,'Synthetic reaction','Synthetic warning',null,'active','high');
select throws_ok($$select sign_native_prescription((select id from fx where k='sign'),(select v from data where k='sign-request'))$$,'40001','Prescription signing context changed','Alert changes invalidate reviewed signature');
select is(recover_native_prescription_operation((select id from fx where k='sign')),null::jsonb,'Stale signing creates no receipt');
update data set v=preview_native_prescription_sign((select id from fx where k='draft'),1) where k='preview';
update data set v=jsonb_set(v,'{expected_context_hash}',(select v->'context_hash' from data where k='preview')) where k='sign-request';
select throws_ok($$select sign_native_prescription(gen_random_uuid(),(select v||'{"signature_name":"Different person"}' from data where k='sign-request'))$$,'23514','Signature must match reviewed veterinarian identity','Cannot forge signing name');
insert into data select 'sign-receipt',sign_native_prescription((select id from fx where k='sign'),(select v from data where k='sign-request'));
select is((select v#>>'{result,artifact,patient,id}' from data where k='sign-receipt'),(select id::text from fx where k='pet'),'Artifact preserves exact patient');
select is((select v#>>'{result,artifact,quantity_per_fill}' from data where k='sign-receipt'),'30.000','Artifact preserves canonical quantity');
select is((read_native_prescription_draft((select id from fx where k='draft'),(select id from fx where k='pet'))->>'status'),'signed','Draft becomes signed atomically');
select is(read_native_prescription_authorization((select id from fx where k='sign'),(select id from fx where k='pet')),(select v->'result' from data where k='sign-receipt'),'Immutable authorization recovery');
select is(read_native_prescription_authorization((select id from fx where k='sign'),gen_random_uuid()),null::jsonb,'Wrong patient authorization read empty');
select is(sign_native_prescription((select id from fx where k='sign'),(select v from data where k='sign-request')),(select v from data where k='sign-receipt'),'Exact signature retry');
select throws_ok($$select sign_native_prescription(gen_random_uuid(),(select v from data where k='sign-request'))$$,'40001','Prescription draft changed','A second UUID cannot sign twice');
select throws_ok($$select save_native_prescription_draft(gen_random_uuid(),(select v||'{"expected_version":1}' from data where k='save-request'))$$,'23514','Signed draft or patient identity cannot change','Signed fields cannot be rewritten');
select save_native_prescription_draft((select id from fx where k='save2'),(select v||jsonb_build_object('draft_id',(select id from fx where k='draft2')) from data where k='save-request'));
insert into fx values('edit2',gen_random_uuid());
insert into data select 'draft2-original',recover_native_prescription_operation((select id from fx where k='save2'));
insert into data select 'edit2-request',jsonb_set(v||jsonb_build_object('draft_id',(select id from fx where k='draft2'),'expected_version',1),'{fields,quantity_per_fill}','"31"') from data where k='save-request';
insert into data select 'edit2-receipt',save_native_prescription_draft((select id from fx where k='edit2'),(select v from data where k='edit2-request'));
select is((select v#>>'{result,version}' from data where k='edit2-receipt'),'2','Unsigned draft edit advances revision');
select is(save_native_prescription_draft((select id from fx where k='edit2'),(select v from data where k='edit2-request')),(select v from data where k='edit2-receipt'),'Unsigned edit exact retry preserves one revision');
select throws_ok($$select save_native_prescription_draft(gen_random_uuid(),(select v from data where k='edit2-request'))$$,'40001','Prescription draft changed','Stale unsigned revision refused');
select is(recover_native_prescription_operation((select id from fx where k='save2')),(select v from data where k='draft2-original'),'Earlier immutable receipt survives draft edits');
select is(read_native_prescription_draft((select id from fx where k='draft2'),(select id from fx where k='pet'))#>>'{fields,quantity_per_fill}','31.000','Current read exposes revised quantity');
insert into data select 'page',list_native_prescription_drafts((select id from fx where k='pet'),null,null,1);
select ok((select(v->>'has_more')::boolean from data where k='page'),'Draft sentinel exposes next page');
select is((select jsonb_array_length(list_native_prescription_drafts((select id from fx where k='pet'),(v#>>'{next_cursor,before_at}')::timestamptz,(v#>>'{next_cursor,before_id}')::uuid,1)->'drafts') from data where k='page'),1,'Draft cursor retains earlier record');
select configure_native_prescriber(gen_random_uuid(),(select jsonb_set(v||'{"expected_version":1}','{fields,active}','false') from data where k='config-request'));
select throws_ok($$select preview_native_prescription_sign((select id from fx where k='draft2'),1)$$,'42501','Current native prescriber commissioning required','Decommissioning blocks new signature');
select is(sign_native_prescription((select id from fx where k='sign'),(select v from data where k='sign-request')),(select v from data where k='sign-receipt'),'Decommissioning cannot erase exact committed signature recovery');
select throws_ok($$select * from native_prescription_authorizations$$,'42501',null,'Raw signed ledger inaccessible');
select throws_ok($$update native_prescription_drafts set fields='{}'$$,'42501',null,'Direct draft bypass denied');
reset role;
select is((select count(*) from audit_logs where table_name='native_prescriber_configurations' and record_id='a5510000-0000-4000-8000-000000000001' and user_id='a5510000-0000-4000-8000-000000000001'),2::bigint,'Configuration revisions audit target and actor');
select is((select count(*) from audit_logs where table_name='native_prescription_draft_revisions' and record_id=(select id from fx where k='save') and user_id='a5510000-0000-4000-8000-000000000002'),1::bigint,'Draft revision audit uses operation identity and actual author');
select is((select count(*) from native_prescription_authorizations where pet_id=(select id from fx where k='pet')),1::bigint,'One native authorization');
select is((select count(*) from native_prescription_draft_revisions where draft_id in(select id from fx where k in ('draft','draft2'))),3::bigint,'All draft revisions retained');
select is((select count(*) from inventory_movements where created_by='a5510000-0000-4000-8000-000000000001'),0::bigint,'Signing makes no stock movement');
select is((select count(*) from billing_invoice_items where created_by='a5510000-0000-4000-8000-000000000001'),0::bigint,'Signing makes no invoice line');
select is((select count(*) from patient_treatments where pet_id=(select id from fx where k='pet')),0::bigint,'Signing never fabricates administration');
select throws_ok($$update native_prescription_authorizations set document='{}'$$,'23514',null,'Even privileged signed history mutation denied');
select ok(not has_function_privilege('service_role','sign_native_prescription(uuid,jsonb)','execute'),'Worker cannot sign');
select ok(not has_function_privilege('anon','save_native_prescription_draft(uuid,jsonb)','execute'),'Anonymous cannot draft');
select ok(not has_function_privilege('authenticated','native_rx_finish(uuid,text,uuid,jsonb,jsonb)','execute'),'Private receipt writer inaccessible');
update profiles set is_active=false where id='a5510000-0000-4000-8000-000000000001';
set local role authenticated;
select throws_ok($$select recover_native_prescription_operation((select id from fx where k='sign'))$$,'42501','Active staff access required','Inactive actor cannot recover');
reset role;select * from finish();rollback;
