begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
create function pg_temp.allocation(q text default '10.000') returns jsonb language sql as $$select jsonb_build_array(jsonb_build_object('allocation_id','00000000-0000-0000-0000-000000000001','lot_id','00000000-0000-0000-0000-000000000002','quantity',q))$$;
create function pg_temp.event(seq integer,action text,q text,intake integer default null,target integer default null) returns jsonb language sql as $$select jsonb_build_object('id',lpad(seq::text,8,'0')||'-0000-0000-0000-000000000003','sequence',seq,'action',action,'intake_id',case when intake is null then null else lpad(intake::text,8,'0')||'-0000-0000-0000-000000000003' end,'correction_target_id',case when target is null then null else lpad(target::text,8,'0')||'-0000-0000-0000-000000000003' end,'allocations',pg_temp.allocation(q))$$;
create temp table replay_vectors(label text primary key,events jsonb);
insert into replay_vectors values('all',jsonb_build_array(pg_temp.event(1,'intake','8.000'),pg_temp.event(2,'dispose','3.000',1),pg_temp.event(3,'restock','2.000',1),pg_temp.event(4,'retract_disposal','1.000',1,2),pg_temp.event(5,'retract_restock','2.000',1,3),pg_temp.event(6,'retract_intake','4.000',1,1)));
select is(native_return_quantity_replay(pg_temp.allocation(),'[]')->'allocations',jsonb_build_array(jsonb_build_object('allocation_id','00000000-0000-0000-0000-000000000001','lot_id','00000000-0000-0000-0000-000000000002','dispensed_quantity','10.000','returned_quantity','0.000','remaining_returnable_quantity','10.000','held_quantity','0.000','disposed_quantity','0.000','restocked_quantity','0.000')),'empty history preserves original allowance');
select is(native_return_quantity_replay(pg_temp.allocation(),events)#>>'{allocations,0,returned_quantity}','4.000','intake retraction changes net received') from replay_vectors;
select is(native_return_quantity_replay(pg_temp.allocation(),events)#>>'{intakes,0,allocations,0,held_quantity}','2.000','both disposition reversals replenish held custody') from replay_vectors;
select is(native_return_quantity_replay(pg_temp.allocation(),events)#>>'{allocations,0,disposed_quantity}','2.000','partial disposal retraction') from replay_vectors;
select is(native_return_quantity_replay(pg_temp.allocation(),events)#>>'{allocations,0,restocked_quantity}','0.000','full restock retraction') from replay_vectors;
select is(native_return_quantity_replay(pg_temp.allocation(),events)#>>'{correction_remaining,0,allocations,0,quantity}','4.000','original intake correction capacity tracked') from replay_vectors;
select is(native_return_quantity_replay(pg_temp.allocation(),events)#>>'{correction_remaining,1,allocations,0,quantity}','2.000','original disposal correction capacity tracked') from replay_vectors;
select is(native_return_quantity_replay(pg_temp.allocation(),events)#>>'{historical,0,gross_intake_quantity}','8.000','gross intake preserved') from replay_vectors;
select is(native_return_quantity_replay(pg_temp.allocation(),events)#>>'{historical,0,retracted_restocked_quantity}','2.000','gross restock retraction preserved') from replay_vectors;
select is(native_return_quantity_replay(pg_temp.allocation(),jsonb_build_array(events->0,events->1))#>>'{intakes,0,allocations,0,held_quantity}','5.000','historical prefix excludes later corrections') from replay_vectors;
select lives_ok($$select native_return_quantity_replay(pg_temp.allocation('99999999999.999'),jsonb_build_array(pg_temp.event(1,'intake','99999999999.999'),pg_temp.event(2,'retract_intake','99999999999.999',1,1),pg_temp.event(3,'intake','99999999999.999')))$$,'gross histories exceed numeric14,3 safely');
select is(native_return_quantity_replay(pg_temp.allocation('99999999999.999'),jsonb_build_array(pg_temp.event(1,'intake','99999999999.999'),pg_temp.event(2,'retract_intake','99999999999.999',1,1),pg_temp.event(3,'intake','99999999999.999')))#>>'{historical,0,gross_intake_quantity}','199999999999.998','unbounded exact gross string');
select throws_ok($$select native_return_quantity_replay(pg_temp.allocation(),jsonb_build_array(pg_temp.event(1,'intake','11.000')))$$,'23514',null,'cannot exceed original');
select throws_ok($$select native_return_quantity_replay(pg_temp.allocation(),jsonb_build_array(pg_temp.event(1,'intake','5.000'),pg_temp.event(2,'dispose','6.000',1)))$$,'23514',null,'cannot dispose more than held');
select throws_ok($$select native_return_quantity_replay(pg_temp.allocation(),jsonb_build_array(pg_temp.event(1,'intake','5.000'),pg_temp.event(2,'dispose','4.000',1),pg_temp.event(3,'retract_intake','2.000',1,1)))$$,'23514',null,'cannot retract intake already dispositioned');
select throws_ok($$select native_return_quantity_replay(pg_temp.allocation(),jsonb_build_array(pg_temp.event(1,'intake','5.000'),pg_temp.event(2,'retract_disposal','1.000',1,1)))$$,'23514',null,'wrong correction target action rejected');
select throws_ok($$select native_return_quantity_replay(pg_temp.allocation(),jsonb_build_array(pg_temp.event(1,'intake','5.000'),pg_temp.event(2,'retract_intake','1.000',1,1),pg_temp.event(3,'retract_intake','1.000',1,2)))$$,'23514',null,'cannot target a correction');
select throws_ok($$select native_return_quantity_replay(pg_temp.allocation(),jsonb_build_array(pg_temp.event(1,'intake','5.000'),pg_temp.event(2,'retract_intake','3.000',1,1),pg_temp.event(3,'retract_intake','3.000',1,1)))$$,'23514',null,'cumulative correction bounded');
select throws_ok($$select native_return_quantity_replay(pg_temp.allocation(),jsonb_build_array(pg_temp.event(1,'intake','5.000'),pg_temp.event(2,'retract_intake','1.000',9,1)))$$,'23514',null,'foreign intake reference rejected');
select throws_ok($$select native_return_quantity_replay(pg_temp.allocation(),jsonb_build_array(pg_temp.event(2,'intake','5.000')))$$,'23514',null,'sequence gap rejected');
select throws_ok($$select native_return_quantity_replay(pg_temp.allocation(),jsonb_build_array(pg_temp.event(1,'intake','5.000'),pg_temp.event(1,'intake','5.000')||'{"sequence":2}'))$$,'23514',null,'duplicate event id rejected');
select throws_ok($$select native_return_quantity_replay(pg_temp.allocation(),jsonb_build_array(pg_temp.event(1,'intake','5.000')||'{"extra":null}'))$$,'23514',null,'extra event key rejected');
select throws_ok($$select native_return_quantity_replay(pg_temp.allocation(),jsonb_build_array(pg_temp.event(1,'intake','5.000')-'correction_target_id'))$$,'23514',null,'missing event key rejected');
select throws_ok($$select native_return_quantity_replay(pg_temp.allocation(),jsonb_build_array(pg_temp.event(1,'intake','5.000')||'{"sequence":"1"}'))$$,'23514',null,'sequence must be numeric');
select throws_ok($$select native_return_quantity_replay(pg_temp.allocation(),jsonb_build_array(pg_temp.event(1,'intake','5.000')||'{"id":"AAAAAAAA-0000-0000-0000-000000000003"}'))$$,'23514',null,'uppercase uuid rejected');
select throws_ok(format('select native_return_quantity_replay(%L::jsonb,''[]'')',pg_temp.allocation(q)),'23514',null,'reject nonpositive or noncanonical quantity '||q) from unnest(array['0.000','1','1.00','01.000','-1.000','1e1','100000000000.000'])q;
select throws_ok($$select native_return_quantity_replay(pg_temp.allocation()||pg_temp.allocation(),'[]')$$,'23514',null,'duplicate allocations rejected');
select throws_ok($$select native_return_quantity_replay('null','[]')$$,'23514',null,'null originals rejected');
select throws_ok($$select native_return_quantity_replay(pg_temp.allocation(),'{}')$$,'23514',null,'object events rejected');
select throws_ok($$select native_return_quantity_replay(pg_temp.allocation(),jsonb_build_array(jsonb_set(pg_temp.event(1,'intake','1.000'),'{allocations,0,lot_id}','"00000000-0000-0000-0000-000000000004"')))$$,'23514',null,'lot substitution rejected');
-- Every cycle must be valid at the time it occurs; no disclosure cap applies here.
insert into replay_vectors select 'long',jsonb_agg(pg_temp.event(n,case (n-1)%4 when 0 then 'intake' when 1 then 'dispose' when 2 then 'retract_disposal' else 'retract_intake' end,'0.001',case when (n-1)%4=0 then null else ((n-1)/4)*4+1 end,case (n-1)%4 when 2 then ((n-1)/4)*4+2 when 3 then ((n-1)/4)*4+1 else null end) order by n) from generate_series(1,160)n;
select is(native_return_quantity_replay(pg_temp.allocation(),events)#>>'{allocations,0,returned_quantity}','0.000','160-event history has no disclosure bound') from replay_vectors where label='long';
select is(native_return_quantity_replay(pg_temp.allocation(),events)#>>'{historical,0,gross_intake_quantity}','0.040','160-event exact gross history') from replay_vectors where label='long';
select throws_ok($$select native_return_quantity_replay(jsonb_set(pg_temp.allocation(),'{0,quantity}','1.000'),'[]')$$,'23514',null,'numeric quantity rejected; fixed3 must be string');
select throws_ok($$select native_return_quantity_replay(jsonb_build_array(pg_temp.allocation()->0||'{"extra":true}'),'[]')$$,'23514',null,'extra allocation key rejected');
select throws_ok($$select native_return_quantity_replay('[]','[]')$$,'23514',null,'empty originals rejected');
select throws_ok($$select native_return_quantity_replay((select jsonb_agg(jsonb_build_object('allocation_id',lpad(n::text,8,'0')||'-0000-0000-0000-000000000001','lot_id','00000000-0000-0000-0000-000000000002','quantity','1.000')) from generate_series(1,101)n),'[]')$$,'23514',null,'101 original allocations rejected');
select is(native_return_balances('00000000-0000-0000-0000-000000000001'),'[]'::jsonb,'missing dispense retains empty balances');
select is(native_return_intake_balance('00000000-0000-0000-0000-000000000001'),null::jsonb,'missing intake retains null');
select ok(not has_function_privilege(r,f,'execute'),r||' cannot call private '||f) from unnest(array['anon','authenticated','service_role'])r cross join unnest(array['native_return_quantity_allocations(jsonb)','native_return_quantity_replay(jsonb,jsonb)','native_return_balances(uuid,integer)','native_return_intake_balance(uuid,integer)'])f;
select is((select provolatile::text from pg_proc where oid='native_return_quantity_replay(jsonb,jsonb)'::regprocedure),'i','replay immutable');
select ok((select prosecdef from pg_proc where oid='native_return_quantity_replay(jsonb,jsonb)'::regprocedure),'replay SECURITY DEFINER');
select * from finish();rollback;
