begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select no_plan();
-- FIXTURE_BEGIN
insert into auth.users(id,email,raw_user_meta_data) values
 ('a5510000-0000-4000-8000-000000000001','native-rx-dvm@example.test','{}'),
 ('a5510000-0000-4000-8000-000000000002','native-rx-staff@example.test','{}'),
 ('a5510000-0000-4000-8000-000000000003','native-rx-uncommissioned@example.test','{}'),
 ('a5510000-0000-4000-8000-000000000004','native-rx-admin@example.test','{}');
update profiles set full_name='Synthetic prescriber' where id='a5510000-0000-4000-8000-000000000001';
insert into user_roles(user_id,role) values('a5510000-0000-4000-8000-000000000001','DVM'),('a5510000-0000-4000-8000-000000000001','ADMIN'),('a5510000-0000-4000-8000-000000000003','DVM'),('a5510000-0000-4000-8000-000000000004','ADMIN');
create temp table fx(k text primary key,id uuid);create temp table data(k text primary key,v jsonb);grant all on fx,data to authenticated;
set local role authenticated;select set_config('request.jwt.claims','{"sub":"a5510000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'client',id from save_client(auth.uid(),null,null,'Native','Household','+13035550123','native-release@example.test','EMAIL','2619 Synthetic Street',null);
insert into fx select 'pet',id from save_patient(null,(select id from fx where k='client'),null,'Native Patient','Dog',null,null,'unknown',null,'unknown','unknown',null,null,null);
insert into fx select 'product',id from save_catalog_product(null,null,'Synthetic medication','medication','','tablet',100,true);
insert into fx select k,gen_random_uuid() from unnest(array['config','save','draft','sign','save2','draft2']) k;
insert into data values('config-request',jsonb_build_object('user_id',auth.uid(),'expected_version',null,'attest_review',true,'fields',jsonb_build_object('active',true,'license_number','SYNTHETIC','license_state','CO','license_expires_on','2099-12-31','practice_name','Synthetic practice','practice_address','2619 Synthetic Street','practice_phone',null,'clinical_review_note','Synthetic fixture only')));
insert into data select 'fields',jsonb_build_object('encounter_id',null,'medication',jsonb_build_object('name','Synthetic medication','strength','Synthetic strength','form','Synthetic form','directions','Synthetic directions only','route','Synthetic route'),'quantity_per_fill','30','unit','tablet','refills_authorized',2,'fulfillment_mode','practice_stock','product_id',(select id from fx where k='product'),'starts_on',(now() at time zone 'America/Denver')::date,'expires_on','2099-12-31');
insert into data select 'save-request',jsonb_build_object('draft_id',(select id from fx where k='draft'),'pet_id',(select id from fx where k='pet'),'client_id',(select id from fx where k='client'),'expected_version',null,'fields',v) from data where k='fields';
-- FIXTURE_END
select configure_native_prescriber((select id from fx where k='config'),(select v from data where k='config-request'));
select save_native_prescription_draft((select id from fx where k='save'),(select v from data where k='save-request'));
insert into data select 'sign-request',jsonb_build_object('draft_id',(select id from fx where k='draft'),'pet_id',(select id from fx where k='pet'),'expected_version',1,'expected_context_hash',preview_native_prescription_sign((select id from fx where k='draft'),1)->>'context_hash','signature_name','Synthetic prescriber','attest_review',true);
insert into data select 'sign-receipt',sign_native_prescription((select id from fx where k='sign'),(select v from data where k='sign-request'));
insert into fx select k,gen_random_uuid() from unnest(array['release','release-fill','release-pickup','release-cancel','stale','invoice','lot','dispense','pickup','cancel']) k;
create function pg_temp.preview_native_release(selection jsonb) returns jsonb language sql as $$select preview_record_release_v10((select id from fx where k='pet'),(select id from fx where k='client'),'EMAIL','native-release@example.test',selection)$$;
create function pg_temp.confirm_native_release(id uuid,selection jsonb,preview jsonb) returns public.record_releases language sql as $$select confirm_record_release(id,(select id from fx where k='pet'),(select id from fx where k='client'),'EMAIL','native-release@example.test',selection,preview->'snapshot',preview->>'source_hash',true)$$;
insert into data select 'selection',jsonb_build_object('native_prescription_ids',jsonb_build_array(id)) from fx where k='sign';
insert into data select 'preview',pg_temp.preview_native_release(v) from data where k='selection';
select receive_inventory(gen_random_uuid(),(select id from fx where k='lot'),(select id from fx where k='product'),'CORRECTION-TEST',current_date+365,'Synthetic clinic',100,'Synthetic opening stock');
insert into fx values('lot2',gen_random_uuid());
select receive_inventory(gen_random_uuid(),(select id from fx where k='lot2'),(select id from fx where k='product'),'RETURN-SECOND',current_date+365,'Synthetic clinic',100,'Synthetic stock');
select create_billing_invoice((select id from fx where k='invoice'),(select id from fx where k='client'));
insert into data select 'target',jsonb_build_object('authorization_id',(select id from fx where k='sign'),'pet_id',(select id from fx where k='pet'),'slot_index',0,'expected_slot_version',null,'invoice_id',(select id from fx where k='invoice'),'quantity','10','allocations',(select jsonb_agg(jsonb_build_object('lot_id',id,'quantity','5') order by id) from fx where k in('lot','lot2')),'refill',null);
insert into data select 'dispense',record_native_dispense((select id from fx where k='dispense'),v||jsonb_build_object('expected_context_hash',preview_native_dispense(v)->>'context_hash','reason','Synthetic dispensing','attest_alert_review',true,'attest_dispense_review',true)) from data where k='target';
reset role;
insert into fx select 'allocation1',id from native_dispense_allocations where dispense_id=(select id from fx where k='dispense') and lot_id=(select id from fx where k='lot');
insert into fx select 'allocation2',id from native_dispense_allocations where dispense_id=(select id from fx where k='dispense') and lot_id=(select id from fx where k='lot2');
insert into data select 'original',jsonb_build_object('dispense',(select document from native_dispenses where id=(select id from fx where k='dispense')),'usage',native_rx_usage_context((select id from fx where k='sign')),'items',(select jsonb_agg(to_jsonb(i) order by id) from billing_invoice_items i where invoice_id=(select id from fx where k='invoice')),'invoice',(select to_jsonb(i) from billing_invoices i where id=(select id from fx where k='invoice')));
insert into record_release_policy(id,enabled,accepted_schema_version,accepted_by,accepted_at,acceptance_reference) values(true,true,11,'Synthetic reviewer',now(),'TEST ONLY') on conflict(id) do update set enabled=true,accepted_schema_version=11,accepted_by=excluded.accepted_by,accepted_at=excluded.accepted_at,acceptance_reference=excluded.acceptance_reference;
set local role authenticated;
insert into data select 'fill-selection',jsonb_build_object('native_dispense_ids',jsonb_build_array(id)) from fx where k='dispense';
insert into data select 'preview11',preview_record_release_v11((select id from fx where k='pet'),(select id from fx where k='client'),'EMAIL','native-release@example.test',v) from data where k='fill-selection';
insert into data select 'release11',to_jsonb(pg_temp.confirm_native_release((select id from fx where k='release'),(select v from data where k='fill-selection'),(select v from data where k='preview11')));
insert into fx select k,gen_random_uuid() from unnest(array['intake','dispose','restock','policy','release12','intake2'])k;
create function pg_temp.return_intent(action text,intake_id uuid,qty1 text,qty2 text) returns jsonb language sql as $$select jsonb_build_object('target',jsonb_build_object('authorization_id',(select id from fx where k='sign'),'pet_id',(select id from fx where k='pet'),'dispense_id',(select id from fx where k='dispense')),'action',action,'intake_id',intake_id,'allocations',(select jsonb_agg(jsonb_build_object('allocation_id',id,'quantity',q) order by id) from(select id,case k when 'allocation1' then qty1 else qty2 end q from fx where k in('allocation1','allocation2')) a where q is not null),'custody',case when action='intake' then 'clinic_retained' else null end,'package_condition',case when action='intake' then 'sealed_intact' else null end,'storage_history',case when action='intake' then 'controlled' else null end,'reason','Synthetic return custody review','note','Synthetic client-shareable return evidence')$$;
create function pg_temp.return_request(intent jsonb) returns jsonb language sql as $$select jsonb_build_object('intent',intent,'expected_context_hash',p->>'context_hash','expected_head',p#>'{context,head}','attest_review',true,'attest_restock',intent->>'action'='restock') from(select preview_native_dispense_return(intent)p)q$$;
create function pg_temp.return_read() returns jsonb language sql as $$select read_native_dispense_returns((select id from fx where k='sign'),(select id from fx where k='pet'),(select id from fx where k='dispense'))$$;
create function pg_temp.release12() returns jsonb language sql as $$select preview_record_release_v12((select id from fx where k='pet'),(select id from fx where k='client'),'EMAIL','native-release@example.test',(select v from data where k='fill-selection'))$$;
insert into data select 'intake-request',pg_temp.return_request(pg_temp.return_intent('intake',null,'2','3'));
insert into data select 'intake',record_native_dispense_return((select id from fx where k='intake'),v) from data where k='intake-request';
create function pg_temp.reconciliation_intent(act text,source_key text,q1 text,q2 text,case_key text default null) returns jsonb language sql as $$
 select (pg_temp.return_intent(case when act like 'retract_%' then 'dispose' else act end,case when act='intake' then null else(select id from fx where k='intake') end,q1,q2)||jsonb_build_object('action',act,'correction_target',case when source_key is null then null else(select jsonb_build_object('event_id',v#>'{result,id}','record_hash',v#>'{result,record_hash}') from data where k=source_key) end,'discrepancy_id',case when case_key is null then null else(select v#>'{result,id}' from data where k=case_key) end))
$$;
create function pg_temp.reconciliation_request(intent jsonb) returns jsonb language sql as $$select jsonb_build_object('intent',intent,'expected_context_hash',p->>'context_hash','expected_head',p#>'{context,head}','expected_discrepancy_head',p#>'{context,discrepancy_head}','attest_review',true,'attest_restock',intent->>'action'='restock','physical_attestations',jsonb_build_object('reviewed_physical_facts',true,'intake_claim_incorrect',intent->>'action'='retract_intake','remains_physically_held',intent->>'action' in('retract_disposal','retract_restock'),'was_not_destroyed',intent->>'action'='retract_disposal','removed_from_available_stock',intent->>'action'='retract_restock')) from(select preview_native_dispense_return_v2(intent)p)q$$;
create function pg_temp.reconciliation_read() returns jsonb language sql as $$select read_native_dispense_returns_v2((select id from fx where k='sign'),(select id from fx where k='pet'),(select id from fx where k='dispense'))$$;
create function pg_temp.discrepancy_intent(act text,source_key text,case_key text,q1 text,q2 text,correction_key text default null) returns jsonb language sql as $$select jsonb_build_object('target',pg_temp.return_intent('intake',null,q1,q2)->'target','action',act,'case_id',case when case_key is null then null else(select v#>'{result,id}' from data where k=case_key) end,'source',(select jsonb_build_object('event_id',v#>'{result,id}','record_hash',v#>'{result,record_hash}') from data where k=source_key),'allocations',pg_temp.return_intent('intake',null,q1,q2)->'allocations','observation','Synthetic physical fact review only','correction_ids',case when correction_key is null then '[]'::jsonb else(select jsonb_build_array(v#>'{result,id}') from data where k=correction_key) end)$$;
create function pg_temp.discrepancy_request(intent jsonb) returns jsonb language sql as $$select jsonb_build_object('intent',intent,'expected_context_hash',p->>'context_hash','expected_return_head',p#>'{context,return_head}','expected_discrepancy_head',p#>'{context,discrepancy_head}','attest_physical_review',true,'attest_original_quantities_custody_and_stock_accurate',intent->>'action'='resolve_confirmed_original') from(select preview_native_return_discrepancy(intent)p)q$$;
-- FIXTURE_RECONCILIATION_READY
select is(pg_temp.reconciliation_read()#>>'{head,version}','1','Mixed reader accepts historical v1 intake');
insert into data select 'dispose-v2',record_native_dispense_return_v2(gen_random_uuid(),pg_temp.reconciliation_request(pg_temp.reconciliation_intent('dispose',null,'1','0.5')));
select is((select sum((x->>'disposed_quantity')::numeric)::text from jsonb_array_elements(pg_temp.reconciliation_read()->'allocations')x),'1.500','v2 ordinary disposal works');
select throws_ok($$select pg_temp.return_read()$$,'23514',null,'Old current reader fails closed after v2');
select is(recover_native_dispense_return((select id from fx where k='intake')),(select v from data where k='intake'),'Historical receipt remains exact');
insert into data select 'retract-dispose-request',pg_temp.reconciliation_request(pg_temp.reconciliation_intent('retract_disposal','dispose-v2','0.25','0.25'));
insert into data select 'retract-dispose',record_native_dispense_return_v2(gen_random_uuid(),v) from data where k='retract-dispose-request';
select is((select sum((x->>'disposed_quantity')::numeric)::text from jsonb_array_elements(pg_temp.reconciliation_read()->'allocations')x),'1.000','Partial two-lot disposal compensation');
select is(recover_native_dispense_return_v2((select(v#>>'{result,id}')::uuid from data where k='retract-dispose')),(select v from data where k='retract-dispose'),'Actor-bound exact recovery');
select is(record_native_dispense_return_v2((select(v#>>'{result,id}')::uuid from data where k='retract-dispose'),(select v from data where k='retract-dispose-request')),(select v from data where k='retract-dispose'),'Exact operation replay returns same receipt');
select throws_ok($$select record_native_dispense_return_v2(gen_random_uuid(),(select v from data where k='retract-dispose-request'))$$,'40001',null,'Changed head prevents stale second correction');
select throws_ok($$select preview_native_dispense_return_v2(pg_temp.reconciliation_intent('retract_disposal','retract-dispose','0.1',null))$$,'23514',null,'Cannot correct correction');
select configure_native_return_policy(gen_random_uuid(),'{"expected_version":0,"enabled":true,"review_reference":"Synthetic only","attest_review":true}');
insert into data select 'restock-v2',record_native_dispense_return_v2(gen_random_uuid(),pg_temp.reconciliation_request(pg_temp.reconciliation_intent('restock',null,'0.5','0.5')));
select configure_native_return_policy(gen_random_uuid(),'{"expected_version":1,"enabled":false,"review_reference":"Synthetic disable","attest_review":true}');
insert into data select 'retract-restock',record_native_dispense_return_v2(gen_random_uuid(),pg_temp.reconciliation_request(pg_temp.reconciliation_intent('retract_restock','restock-v2','0.25','0.25')));
select is((select sum((x->>'restocked_quantity')::numeric)::text from jsonb_array_elements(pg_temp.reconciliation_read()->'allocations')x),'0.500','Policy-disabled removal compensates exact stock');
reset role;
select is((select sum(quantity)::text from inventory_movements where kind='native_return_compensation' and lot_id in(select id from fx where k in('lot','lot2'))),'-0.500','Negative stock compensation recorded');
select is((select count(*)::integer from native_return_compensation_links),2,'Both original positive stock links compensated');
set local role authenticated;
insert into data select 'retract-intake',record_native_dispense_return_v2(gen_random_uuid(),pg_temp.reconciliation_request(pg_temp.reconciliation_intent('retract_intake','intake','0.25','0.5')));
select is((select sum((x->>'returned_quantity')::numeric)::text from jsonb_array_elements(pg_temp.reconciliation_read()->'allocations')x),'4.250','Intake retraction reduces net received only');
insert into data select 'report',record_native_return_discrepancy(gen_random_uuid(),pg_temp.discrepancy_request(pg_temp.discrepancy_intent('report','restock-v2',null,'0.25','0.25')));
select is(pg_temp.reconciliation_read()#>>'{discrepancies,open_case_count}','1','Physical discrepancy remains open');
select is(jsonb_array_length(pg_temp.reconciliation_read()#>'{discrepancies,held_lot_ids}'),2,'Affected lots held for review');
select throws_ok($$select adjust_inventory(gen_random_uuid(),(select id from fx where k='lot'),1,'Attempt generic closure')$$,'23514',null,'Manual adjustment cannot evade review hold');
insert into data select 'case-correction',record_native_dispense_return_v2(gen_random_uuid(),pg_temp.reconciliation_request(pg_temp.reconciliation_intent('retract_restock','restock-v2','0.25','0.25','report')));
select is(pg_temp.reconciliation_read()#>>'{discrepancies,open_case_count}','1','Compensation alone does not silently close case');
select throws_ok($$select preview_native_return_discrepancy(pg_temp.discrepancy_intent('resolve_confirmed_original','restock-v2','report','0.25','0.25'))$$,'23514',null,'Compensated original cannot be confirmed unchanged');
insert into data select 'resolution',record_native_return_discrepancy(gen_random_uuid(),pg_temp.discrepancy_request(pg_temp.discrepancy_intent('resolve_corrected','restock-v2','report','0.25','0.25','case-correction')));
select is(pg_temp.reconciliation_read()#>>'{discrepancies,open_case_count}','0','Exact linked corrections resolve case');
select is(pg_temp.reconciliation_read()#>'{discrepancies,held_lot_ids}','[]'::jsonb,'Verified resolution releases lot holds');
select is(recover_native_return_discrepancy((select(v#>>'{result,id}')::uuid from data where k='report')),(select v from data where k='report'),'Original discrepancy receipt stays exact after resolution');
insert into data select 'report2',record_native_return_discrepancy(gen_random_uuid(),pg_temp.discrepancy_request(pg_temp.discrepancy_intent('report','intake',null,'0.1',null)));
insert into data select 'note',record_native_return_discrepancy(gen_random_uuid(),pg_temp.discrepancy_request(pg_temp.discrepancy_intent('note','intake','report2','0.1',null)));
select is(pg_temp.reconciliation_read()#>>'{discrepancies,open_case_count}','1','Note cannot close physical discrepancy');
insert into data select 'confirmed',record_native_return_discrepancy(gen_random_uuid(),pg_temp.discrepancy_request(pg_temp.discrepancy_intent('resolve_confirmed_original','intake','report2','0.1',null)));
select is(pg_temp.reconciliation_read()#>>'{discrepancies,open_case_count}','0','DVM factual confirmation explicit outcome');
insert into data select 'fresh-intake',record_native_dispense_return_v2(gen_random_uuid(),pg_temp.reconciliation_request(pg_temp.reconciliation_intent('intake',null,'0.25','0.5')));
select is((select sum((x->>'returned_quantity')::numeric)::text from jsonb_array_elements(pg_temp.reconciliation_read()->'allocations')x),'5.000','Fresh ordinary intake after correction supported');
select configure_native_return_policy(gen_random_uuid(),'{"expected_version":2,"enabled":true,"review_reference":"Synthetic only renewed","attest_review":true}');
insert into data select 'restock-low',record_native_dispense_return_v2(gen_random_uuid(),pg_temp.reconciliation_request(pg_temp.reconciliation_intent('restock',null,'0.2',null)));
select adjust_inventory(gen_random_uuid(),(select id from fx where k='lot'),0.1-(select sum(quantity) from inventory_movements where lot_id=(select id from fx where k='lot')),'Synthetic stock consumed before discrepancy');
select ok(preview_native_dispense_return_v2(pg_temp.reconciliation_intent('retract_restock','restock-low','0.2',null))->'blockers' ? 'insufficient_available_stock','Consumed stock blocks invented compensation');
select throws_ok($$select record_native_dispense_return_v2(gen_random_uuid(),pg_temp.reconciliation_request(pg_temp.reconciliation_intent('retract_restock','restock-low','0.2',null)))$$,'23514',null,'Insufficient stock creates no negative compensation');
insert into data select 'low-report',record_native_return_discrepancy(gen_random_uuid(),pg_temp.discrepancy_request(pg_temp.discrepancy_intent('report','restock-low',null,'0.2',null)));
select is(pg_temp.reconciliation_read()#>>'{discrepancies,open_case_count}','1','Consumed stock has persistent discrepancy path');
select receive_inventory(gen_random_uuid(),(select id from fx where k='lot'),(select id from fx where k='product'),'CORRECTION-TEST',current_date+365,'Synthetic clinic',1,'Synthetic identified replacement custody');
select is(jsonb_array_length(pg_temp.reconciliation_read()#>'{discrepancies,held_lot_ids}'),1,'Receiving does not release review hold');
select ok(preview_native_dispense_return_v2(pg_temp.reconciliation_intent('restock',null,'0.1',null))->'blockers' ? 'lot_review_hold','Positive restock blocked on held lot');
insert into data select 'low-correction',record_native_dispense_return_v2(gen_random_uuid(),pg_temp.reconciliation_request(pg_temp.reconciliation_intent('retract_restock','restock-low','0.2',null,'low-report')));
select record_native_return_discrepancy(gen_random_uuid(),pg_temp.discrepancy_request(pg_temp.discrepancy_intent('resolve_corrected','restock-low','low-report','0.2',null,'low-correction')));
select is(pg_temp.reconciliation_read()#>>'{discrepancies,open_case_count}','0','Actual later compensation resolves stock discrepancy');
select throws_ok($$select preview_native_dispense_return_v2(jsonb_set(pg_temp.reconciliation_intent('retract_intake','intake','0.1',null),'{correction_target,record_hash}',to_jsonb(repeat('0',64))))$$,'23514',null,'Wrong source hash rejected');
select throws_ok($$select preview_native_dispense_return_v2(jsonb_set(pg_temp.reconciliation_intent('retract_intake','intake','0.1',null),'{target,pet_id}',to_jsonb(gen_random_uuid())))$$,'23514',null,'Cross-patient correction rejected');
select set_config('request.jwt.claims','{"sub":"a5510000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select ok(preview_native_dispense_return_v2(pg_temp.reconciliation_intent('retract_intake','intake','0.1',null))->'blockers' ? 'dvm_required','Staff cannot authorize correction');
select throws_ok($$select recover_native_dispense_return_v2((select(v#>>'{result,id}')::uuid from data where k='retract-intake'))$$,'42501',null,'Wrong actor cannot recover receipt');
reset role;
select is((select document from native_dispenses where id=(select id from fx where k='dispense')),(select v->'dispense' from data where k='original'),'Original dispense unchanged');
select is(native_rx_usage_context((select id from fx where k='sign')),(select v->'usage' from data where k='original'),'Prescription allowance unchanged');
select is((select jsonb_agg(to_jsonb(i) order by id) from billing_invoice_items i where invoice_id=(select id from fx where k='invoice')),(select v->'items' from data where k='original'),'Invoice line items unchanged');
select ok(not has_function_privilege('authenticated','native_reconciliation_verified(uuid,uuid,uuid)','execute'),'Verifier private');
select ok(not has_function_privilege('service_role','record_native_dispense_return_v2(uuid,jsonb)','execute'),'Service role cannot impersonate staff writes');
select ok(exists(select 1 from audit_logs a join native_return_discrepancy_correction_links l on l.id=a.record_id where a.table_name='native_return_discrepancy_correction_links' and a.action='INSERT' and a.user_id='a5510000-0000-4000-8000-000000000001'),'Correction-to-resolution links have actor-attributed audit identities');
select * from finish();rollback;
