begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,raw_user_meta_data) values
 ('73500000-0000-4000-8000-000000000001','payment-staff@example.test','{}'),
 ('73500000-0000-4000-8000-000000000002','payment-other@example.test','{}'),
 ('73500000-0000-4000-8000-000000000003','payment-inactive@example.test','{}');
update public.profiles set is_active=false where id='73500000-0000-4000-8000-000000000003';
insert into public.user_roles(user_id,role) values ('73500000-0000-4000-8000-000000000001','ADMIN') on conflict do nothing;
create temp table fx(k text primary key,id uuid);grant all on fx to authenticated,service_role;
create temp table snapshots(k text primary key,v jsonb);grant all on snapshots to authenticated,service_role;
set local role service_role;
select public.configure_payment_provider('acct_test',false,'https://thelivingroom.vet');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"73500000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'client',id from public.save_client(auth.uid(),null,null,'Payment','Family',null,null,'EMAIL',null,null);
insert into fx select 'other-client',id from public.save_client(auth.uid(),null,null,'Different','Family',null,null,'EMAIL',null,null);
insert into fx select 'product',id from public.save_catalog_product(null,null,'Visit','service','','visit',10000,true);
insert into fx values('invoice','73500000-0000-4000-8000-000000000010'),('attempt','73500000-0000-4000-8000-000000000020'),('refund','73500000-0000-4000-8000-000000000030');
select public.create_billing_invoice((select id from fx where k='invoice'),(select id from fx where k='client'));
select public.add_invoice_service(gen_random_uuid(),(select id from fx where k='invoice'),null,(select id from fx where k='product'),1);
select public.issue_billing_invoice((select id from fx where k='invoice'),(select version from public.billing_invoices where id=(select id from fx where k='invoice')));
insert into snapshots select 'before',public.read_invoice_payment_state((select id from fx where k='invoice'),(select id from fx where k='client'));

insert into fx values('grant',gen_random_uuid());
select public.prepare_payment_collection((select id from fx where k='grant'),(select id from fx where k='invoice'),(select id from fx where k='client'),(select v->>'source_hash' from snapshots where k='before'),10000,now()+interval '6 days');
set local role service_role;
insert into snapshots select 'grant_capture',public.capture_payment_collection((select id from fx where k='grant'),'73500000-0000-4000-8000-000000000001','https://thelivingroom.vet','local-v1',repeat('a',64),repeat('b',64));
set local role authenticated;
select public.attest_payment_collection((select id from fx where k='grant'),(select v#>>'{capture,context_hash}' from snapshots where k='grant_capture'),true);
select public.prepare_invoice_checkout((select id from fx where k='attempt'),(select id from fx where k='invoice'),(select id from fx where k='client'),(select v->>'source_hash' from snapshots where k='before'),10000,'acct_test',false,'https://thelivingroom.vet/payment/return','https://thelivingroom.vet/payment/cancel');
set local role service_role;
select public.apply_checkout_evidence('evt_reconopen',(select id from fx where k='attempt'),'acct_test',false,'session_open','cs_test_recon',null,10000,'usd',(select v->>'source_hash' from snapshots where k='before'));
select public.record_payment_reconciliation('checkout',(select id from fx where k='attempt'),'provider_object_unavailable');
set local role authenticated;
insert into snapshots select 'preview',public.preview_payment_reconciliation((select id from fx where k='invoice'),'checkout',(select id from fx where k='attempt'),'cs_test_recon');
select is(jsonb_array_length((select v->'blocker_refs' from snapshots where k='preview')),1,'Preview has exact observation target');
select throws_ok($$select public.preview_payment_reconciliation((select id from fx where k='invoice'),'checkout',(select id from fx where k='attempt'),'cs_test_unknown')$$,'23514',null,'Unknown object cannot be reviewed');
insert into fx values('case','73500000-0000-4000-8000-000000000040');
select public.prepare_payment_reconciliation((select id from fx where k='case'),(select id from fx where k='invoice'),'checkout',(select id from fx where k='attempt'),'cs_test_recon',(select v->'blocker_refs' from snapshots where k='preview'),(select v->>'snapshot_hash' from snapshots where k='preview'));
select lives_ok($$select public.prepare_payment_reconciliation((select id from fx where k='case'),(select id from fx where k='invoice'),'checkout',(select id from fx where k='attempt'),'cs_test_recon',(select v->'blocker_refs' from snapshots where k='preview'),(select v->>'snapshot_hash' from snapshots where k='preview'))$$,'Exact prepare retry recovers case');
insert into snapshots select 'proof',jsonb_build_object('family','checkout','request_id',(select id from fx where k='attempt'),'object_id','cs_test_recon','account_id','acct_test','livemode',false,'amount_cents','10000','currency','usd','provider_observed_at',clock_timestamp()::text,'status','session_open','payment_id',null,'source_hash',(select v->>'source_hash' from snapshots where k='before'));
select throws_ok($$select public.capture_payment_reconciliation((select id from fx where k='case'),auth.uid(),(select v from snapshots where k='proof'))$$,'42501',null,'Staff cannot fabricate verified capture');
set local role service_role;
select throws_ok($$select public.capture_payment_reconciliation((select id from fx where k='case'),'73500000-0000-4000-8000-000000000001',(select v||'{"amount_cents":"9999"}' from snapshots where k='proof'))$$,'23514',null,'Wrong amount proof denied');
select throws_ok($$select public.capture_payment_reconciliation((select id from fx where k='case'),'73500000-0000-4000-8000-000000000001',(select v||'{"client_url":"https://secret.test"}' from snapshots where k='proof'))$$,'23514',null,'Raw URL cannot enter capture');
select throws_ok($$select public.capture_payment_reconciliation((select id from fx where k='case'),'73500000-0000-4000-8000-000000000001',(select v||jsonb_build_object('provider_observed_at',(clock_timestamp()-interval '6 minutes')::text) from snapshots where k='proof'))$$,'23514',null,'Stale provider proof rejected');
select throws_ok($$select public.capture_payment_reconciliation((select id from fx where k='case'),'73500000-0000-4000-8000-000000000001',(select v||'{"livemode":true}' from snapshots where k='proof'))$$,'23514',null,'Wrong mode proof rejected');
insert into snapshots select 'capture',public.capture_payment_reconciliation((select id from fx where k='case'),'73500000-0000-4000-8000-000000000001',(select v from snapshots where k='proof'));
select lives_ok($$select public.capture_payment_reconciliation((select id from fx where k='case'),'73500000-0000-4000-8000-000000000001',(select v from snapshots where k='proof'))$$,'Exact capture retry recovers proof');
select throws_ok($$select public.capture_payment_reconciliation((select id from fx where k='case'),'73500000-0000-4000-8000-000000000001',(select v||'{"status":"session_expired"}' from snapshots where k='proof'))$$,'23514',null,'Captured proof cannot change');
set local role authenticated;
select throws_ok($$select public.complete_payment_reconciliation((select id from fx where k='case'),(select v->>'proof_hash' from snapshots where k='capture'),(select v->>'snapshot_hash' from snapshots where k='preview'),false)$$,'23514',null,'Explicit reviewed attestation required');
select lives_ok($$select public.complete_payment_reconciliation((select id from fx where k='case'),(select v->>'proof_hash' from snapshots where k='capture'),(select v->>'snapshot_hash' from snapshots where k='preview'),true)$$,'Reviewed open proof resolves specific observation');
select lives_ok($$select public.complete_payment_reconciliation((select id from fx where k='case'),(select v->>'proof_hash' from snapshots where k='capture'),(select v->>'snapshot_hash' from snapshots where k='preview'),true)$$,'Lost acknowledgement exact completion replay');
select throws_ok($$select public.credit_billing_invoice(gen_random_uuid(),(select id from fx where k='invoice'),100,'Adjustment')$$,'23514',null,'Resolved observation does not release open checkout');
set local role service_role;
select is(public.provider_checkout_context((select id from fx where k='attempt'))->>'state','open','Verified open session remains reserved');
select public.record_payment_reconciliation('checkout',(select id from fx where k='attempt'),'provider_object_unavailable');
select is(public.provider_checkout_context((select id from fx where k='attempt'))->>'state','reconciliation','Same reason recurrence blocks again');
reset role;
select is((select count(*) from public.payment_reconciliation_observations where request_id=(select id from fx where k='attempt')),2::bigint,'Recurrence appends separate immutable observation');

create function pg_temp.resolve_known(p_status text,p_payment text default null) returns void language plpgsql as $$
declare t jsonb;c uuid:=gen_random_uuid();proof jsonb;cap jsonb;begin
 t:=public.preview_payment_reconciliation((select id from fx where k='invoice'),'checkout',(select id from fx where k='attempt'),'cs_test_recon');
 perform public.prepare_payment_reconciliation(c,(select id from fx where k='invoice'),'checkout',(select id from fx where k='attempt'),'cs_test_recon',t->'blocker_refs',t->>'snapshot_hash');
 proof:=(select v from snapshots where k='proof')||jsonb_build_object('status',p_status,'payment_id',p_payment,'provider_observed_at',clock_timestamp()::text);
 cap:=public.capture_payment_reconciliation(c,'73500000-0000-4000-8000-000000000001',proof);
 perform public.complete_payment_reconciliation(c,cap->>'proof_hash',t->>'snapshot_hash',true);
end $$;
select lives_ok($$select pg_temp.resolve_known('session_expired')$$,'Verified expiration resolves recurrence');
select is(public.checkout_state_internal((select id from fx where k='attempt')),'expired','Authoritative expiration releases reservation');
set local role service_role;
select is(public.inspect_payment_collection((select id from fx where k='grant'),repeat('a',64),'https://thelivingroom.vet','local-v1')->>'state','ready','Public inspection ignores resolved observations after verified expiration');
reset role;
select is((select count(*) from public.invoice_checkout_attempts where invoice_id=(select id from fx where k='invoice')),1::bigint,'Public inspection creates no new attempt');

select ok(not public.payment_invoice_has_observations((select id from fx where k='invoice')),'Resolved history no longer triggers invoice observation guard');
select is(public.read_invoice_payment_state((select id from fx where k='invoice'),(select id from fx where k='client'))#>>'{reconciliation_observations,0,resolved}','true','Staff history exposes resolved flag');
select public.record_payment_reconciliation('checkout',(select id from fx where k='attempt'),'provider_reconciliation_required');
set local role service_role;
select throws_ok($$select public.inspect_payment_collection((select id from fx where k='grant'),repeat('a',64),'https://thelivingroom.vet','local-v1')$$,'42501',null,'Public inspection retains new unresolved observation block');
reset role;

select throws_ok($$select pg_temp.resolve_known('session_open')$$,'23514',null,'Fresh open proof cannot override historical authoritative expiration');
select lives_ok($$select pg_temp.resolve_known('payment_succeeded','pi_recon')$$,'Matching payment resolves and applies cash atomically');
select is((select count(*) from public.invoice_payments where invoice_id=(select id from fx where k='invoice')),1::bigint,'One cash payment exists');
select public.record_payment_reconciliation('checkout',(select id from fx where k='attempt'),'provider_reconciliation_required');
select throws_ok($$select pg_temp.resolve_known('session_expired')$$,'23514',null,'Fresh expiration cannot resolve a contradiction with settled payment');
select lives_ok($$select pg_temp.resolve_known('payment_succeeded','pi_recon')$$,'Later matching review cannot duplicate payment');
select is((select count(*) from public.invoice_payments where invoice_id=(select id from fx where k='invoice')),1::bigint,'Payment remains counted once');
select public.credit_billing_invoice(gen_random_uuid(),(select id from fx where k='invoice'),3000,'Adjustment');
insert into fx select 'payment',id from public.invoice_payments where invoice_id=(select id from fx where k='invoice');
select public.prepare_invoice_refund((select id from fx where k='refund'),(select id from fx where k='invoice'),(select id from fx where k='payment'),2000,'Adjustment');
select public.apply_refund_evidence('evt_reconrefund',(select id from fx where k='refund'),'acct_test',false,'re_recon','pi_recon',2000,'usd','pending');
select public.record_payment_reconciliation('refund',(select id from fx where k='refund'),'provider_object_unavailable');
create function pg_temp.resolve_refund(p_status text) returns void language plpgsql as $$
declare t jsonb;c uuid:=gen_random_uuid();cap jsonb;begin
 t:=public.preview_payment_reconciliation((select id from fx where k='invoice'),'refund',(select id from fx where k='refund'),'re_recon');
 perform public.prepare_payment_reconciliation(c,(select id from fx where k='invoice'),'refund',(select id from fx where k='refund'),'re_recon',t->'blocker_refs',t->>'snapshot_hash');
 cap:=public.capture_payment_reconciliation(c,'73500000-0000-4000-8000-000000000001',jsonb_build_object('family','refund','request_id',(select id from fx where k='refund'),'object_id','re_recon','account_id','acct_test','livemode',false,'amount_cents','2000','currency','usd','provider_observed_at',clock_timestamp()::text,'status',p_status,'provider_payment_id','pi_recon'));
 perform public.complete_payment_reconciliation(c,cap->>'proof_hash',t->>'snapshot_hash',true);
end $$;
select lives_ok($$select pg_temp.resolve_refund('pending')$$,'Matching pending refund observation resolved');
select is(public.refund_state_internal((select id from fx where k='refund')),'pending','Pending refund reservation remains');
select public.record_payment_reconciliation('refund',(select id from fx where k='refund'),'provider_object_unavailable');
select lives_ok($$select pg_temp.resolve_refund('succeeded')$$,'Matching successful refund applies cash');
select is(public.refund_state_internal((select id from fx where k='refund')),'succeeded','Refund derives success after observation resolved');
select is((select count(*) from public.invoice_refunds where invoice_id=(select id from fx where k='invoice')),1::bigint,'Refund posted exactly once');
select public.record_payment_reconciliation('refund',(select id from fx where k='refund'),'provider_object_unavailable');
select throws_ok($$select pg_temp.resolve_refund('pending')$$,'23514',null,'Pending proof cannot resolve contradiction with settled refund');
select lives_ok($$select pg_temp.resolve_refund('succeeded')$$,'Matching settled refund review clears observation without duplicate cash');
insert into fx values('failed-refund',gen_random_uuid());
select public.prepare_invoice_refund((select id from fx where k='failed-refund'),(select id from fx where k='invoice'),(select id from fx where k='payment'),1000,'Adjustment');
select public.apply_refund_evidence('evt_reconfailed',(select id from fx where k='failed-refund'),'acct_test',false,'re_failed','pi_recon',1000,'usd','failed');
select public.record_payment_reconciliation('refund',(select id from fx where k='failed-refund'),'provider_object_unavailable');
select throws_ok($$select public.preview_payment_reconciliation((select id from fx where k='invoice'),'refund',(select id from fx where k='failed-refund'),'re_failed')$$,'23514',null,'Released failed refund remains outside reviewed resolution scope');
select is((public.apply_refund_evidence('evt_reconlate',(select id from fx where k='failed-refund'),'acct_test',false,'re_failed','pi_recon',1000,'usd','succeeded')).disposition,'quarantined','Late success after released failure still quarantined');
select public.record_payment_reconciliation('checkout',(select id from fx where k='attempt'),'provider_context_mismatch');
select throws_ok($$select pg_temp.resolve_known('payment_succeeded','pi_recon')$$,'23514',null,'Known matching object cannot clear unattributed context mismatch');
select is(public.checkout_state_internal((select id from fx where k='attempt')),'reconciliation','Context mismatch remains blocked');
select throws_ok($$delete from public.payment_reconciliation_resolutions$$,'23514',null,'Resolution history is append only');
select throws_ok($$update public.payment_reconciliation_captures set evidence='{}'$$,'23514',null,'Verified capture is immutable');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"73500000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select throws_ok($$select public.read_payment_reconciliation((select id from fx where k='case'))$$,'42501',null,'Non-admin staff cannot read review');
set local role anon;
select throws_ok($$select * from public.payment_reconciliation_captures$$,'42501',null,'Anonymous proof access denied');
select * from finish();
rollback;
