begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,raw_user_meta_data) values
 ('73700000-0000-4000-8000-000000000001','payment-staff@example.test','{}'),
 ('73700000-0000-4000-8000-000000000002','payment-other@example.test','{}'),
 ('73700000-0000-4000-8000-000000000003','payment-inactive@example.test','{}');
update public.profiles set is_active=false where id='73700000-0000-4000-8000-000000000003';
create temp table fx(k text primary key,id uuid);grant all on fx to authenticated,service_role;
create temp table snapshots(k text primary key,v jsonb);grant all on snapshots to authenticated,service_role;
set local role service_role;
select public.configure_payment_provider('acct_test',false,'https://thelivingroom.vet');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"73700000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'client',id from public.save_client(auth.uid(),null,null,'Payment','Family','+13035550404','payment@example.test','EMAIL',null,null);
insert into fx select 'other-client',id from public.save_client(auth.uid(),null,null,'Different','Family',null,null,'EMAIL',null,null);
insert into fx select 'product',id from public.save_catalog_product(null,null,'Visit','service','','visit',10000,true);
insert into fx values('invoice','73700000-0000-4000-8000-000000000010'),('attempt','73700000-0000-4000-8000-000000000020'),('refund','73700000-0000-4000-8000-000000000030');
select public.create_billing_invoice((select id from fx where k='invoice'),(select id from fx where k='client'));
select public.add_invoice_service(gen_random_uuid(),(select id from fx where k='invoice'),null,(select id from fx where k='product'),1);
select public.issue_billing_invoice((select id from fx where k='invoice'),(select version from public.billing_invoices where id=(select id from fx where k='invoice')));
insert into snapshots select 'before',public.read_invoice_payment_state((select id from fx where k='invoice'),(select id from fx where k='client'));

insert into fx values('grant',gen_random_uuid()),('conversation',gen_random_uuid()),('delivery',gen_random_uuid()),('second',gen_random_uuid());
reset role;
insert into public.conversations(id,client_id) select (select id from fx where k='conversation'),id from fx where k='client';
set local role authenticated;
select public.prepare_payment_collection((select id from fx where k='grant'),(select id from fx where k='invoice'),(select id from fx where k='client'),(select v->>'source_hash' from snapshots where k='before'),10000,now()+interval '6 days');
set local role service_role;
select set_config('request.jwt.claims','{"role":"service_role"}',true);
insert into snapshots select 'grant_capture',public.capture_payment_collection((select id from fx where k='grant'),'73700000-0000-4000-8000-000000000001','https://thelivingroom.vet','local-v1',repeat('a',64),repeat('b',64));
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"73700000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select public.attest_payment_collection((select id from fx where k='grant'),(select v#>>'{capture,context_hash}' from snapshots where k='grant_capture'),true);
select throws_ok($$select public.prepare_payment_delivery((select id from fx where k='delivery'),(select id from fx where k='grant'),(select id from fx where k='conversation'),'EMAIL','payment@example.test','Invoice','Missing link')$$,'23514',null,'Message requires exactly one payment placeholder');
select throws_ok($$select public.prepare_payment_delivery((select id from fx where k='delivery'),(select id from fx where k='grant'),(select id from fx where k='conversation'),'SMS','+13035550404','','Pay: {{payment_link}}')$$,'42501',null,'SMS without current consent denied');
select throws_ok($$select public.prepare_payment_delivery((select id from fx where k='second'),(select id from fx where k='grant'),(select id from fx where k='conversation'),'EMAIL','payment@example.test','Invoice','Pay: {{payment_link}} {{payment_link}}')$$,'23514',null,'Duplicate capability placeholders rejected');
select throws_ok($$select public.prepare_payment_delivery((select id from fx where k='second'),(select id from fx where k='grant'),(select id from fx where k='conversation'),'EMAIL','payment@example.test','Invoice','Pay: {{payment_link}} p1.'||repeat('a',43))$$,'23514',null,'Usable capability rejected at delivery persistence boundary');
select lives_ok($$select public.prepare_payment_delivery((select id from fx where k='delivery'),(select id from fx where k='grant'),(select id from fx where k='conversation'),'EMAIL','payment@example.test','Invoice','Pay: {{payment_link}}')$$,'Prepare distinct immutable delivery');
select lives_ok($$select public.prepare_payment_delivery((select id from fx where k='delivery'),(select id from fx where k='grant'),(select id from fx where k='conversation'),'EMAIL','payment@example.test','Invoice','Pay: {{payment_link}}')$$,'Prepare exact retry recovers');
select throws_ok($$select public.prepare_payment_delivery((select id from fx where k='delivery'),(select id from fx where k='grant'),(select id from fx where k='conversation'),'EMAIL','payment@example.test','Changed','Pay: {{payment_link}}')$$,'23505',null,'UUID cannot change reviewed intent');
select throws_ok($$select public.capture_payment_delivery((select id from fx where k='delivery'),auth.uid(),'{"from":"billing@thelivingroom.vet","reply_to":"billing@thelivingroom.vet"}',repeat('c',64),repeat('d',64))$$,'42501',null,'Staff cannot fabricate service digest');
set local role service_role;
select set_config('request.jwt.claims','{"role":"service_role"}',true);
select lives_ok($$select public.capture_payment_delivery((select id from fx where k='delivery'),'73700000-0000-4000-8000-000000000001','{"from":"billing@thelivingroom.vet","reply_to":"billing@thelivingroom.vet"}',repeat('c',64),repeat('d',64))$$,'Service captures sender and materialized hashes only');
select lives_ok($$select public.capture_payment_delivery((select id from fx where k='delivery'),'73700000-0000-4000-8000-000000000001','{"from":"billing@thelivingroom.vet","reply_to":"billing@thelivingroom.vet"}',repeat('c',64),repeat('d',64))$$,'Exact capture replay');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"73700000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select throws_ok($$select public.enqueue_payment_delivery((select id from fx where k='delivery'),repeat('c',64),repeat('d',64),false)$$,'42501',null,'Explicit review required');
insert into fx select 'outbox',id from public.enqueue_payment_delivery((select id from fx where k='delivery'),repeat('c',64),repeat('d',64),true);
select is((select body from public.communication_outbox where id=(select id from fx where k='outbox')),'Pay: {{payment_link}}','Outbox stores template only');
select lives_ok($$select public.enqueue_payment_delivery((select id from fx where k='delivery'),repeat('c',64),repeat('d',64),true)$$,'Queue retry recovers same receipt');
reset role;
update public.communication_outbox set state='claimed',lease_token='73700000-0000-4000-8000-000000000090',lease_expires_at=now()+interval '5 minutes' where id=(select id from fx where k='outbox');
set local role service_role;
select set_config('request.jwt.claims','{"role":"service_role"}',true);
select throws_ok($$select public.payment_delivery_context((select id from fx where k='outbox'),gen_random_uuid())$$,'40001',null,'Wrong worker lease cannot retrieve materialization context');
select is(public.payment_delivery_context((select id from fx where k='outbox'),'73700000-0000-4000-8000-000000000090')#>>'{capture,payload_hash}',repeat('d',64),'Leased context returns reviewed payload digest');
select is((public.start_communication_attempt((select id from fx where k='outbox'),'73700000-0000-4000-8000-000000000090','{"from":"billing@thelivingroom.vet","reply_to":"billing@thelivingroom.vet"}')).state,'failed','Existing worker without payment materialization proof fails closed');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"73700000-0000-4000-8000-000000000001","role":"authenticated"}',true);

insert into fx values('attachment',gen_random_uuid()),('attached-delivery',gen_random_uuid()),('sms-delivery',gen_random_uuid());
select public.prepare_invoice_email((select id from fx where k='attachment'),(select id from fx where k='invoice'),(select id from fx where k='client'),(select id from fx where k='conversation'),'payment@example.test','Invoice','Pay: {{payment_link}}',public.read_invoice_email_preview((select id from fx where k='invoice'),(select id from fx where k='client'))->>'source_hash');
insert into snapshots select 'invoice_payload',jsonb_build_object('from','billing@thelivingroom.vet','reply_to','billing@thelivingroom.vet','to',jsonb_build_array('payment@example.test'),'subject','Invoice','text','Pay: {{payment_link}}','attachments',jsonb_build_array(jsonb_build_object('filename','invoice-'||(select id::text from fx where k='invoice')||'.html','content_type','text/html','content',encode(convert_to('<h1>Synthetic reviewed invoice</h1>','UTF8'),'base64'))));
set local role service_role;
select set_config('request.jwt.claims','{"role":"service_role"}',true);
select public.capture_invoice_email_payload((select id from fx where k='attachment'),'73700000-0000-4000-8000-000000000001',(select v::text from snapshots where k='invoice_payload'));
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"73700000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into snapshots select 'invoice_recovery',public.recover_invoice_email((select id from fx where k='invoice'),(select id from fx where k='attachment'));
select lives_ok($$select public.prepare_payment_delivery((select id from fx where k='attached-delivery'),(select id from fx where k='grant'),(select id from fx where k='conversation'),'EMAIL','payment@example.test','Invoice','Pay: {{payment_link}}',(select id from fx where k='attachment'),(select v->>'payload_hash' from snapshots where k='invoice_recovery'))$$,'Email binds existing reviewed frozen invoice attachment');
set local role service_role;
select set_config('request.jwt.claims','{"role":"service_role"}',true);
select throws_ok($$select public.capture_payment_delivery((select id from fx where k='attached-delivery'),'73700000-0000-4000-8000-000000000001','{"from":"other@thelivingroom.vet","reply_to":"billing@thelivingroom.vet"}',repeat('e',64),repeat('f',64))$$,'23514',null,'Attachment sender must match materialized message sender');
select public.capture_payment_delivery((select id from fx where k='attached-delivery'),'73700000-0000-4000-8000-000000000001','{"from":"billing@thelivingroom.vet","reply_to":"billing@thelivingroom.vet"}',repeat('e',64),repeat('f',64));
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"73700000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'attached-outbox',id from public.enqueue_payment_delivery((select id from fx where k='attached-delivery'),repeat('e',64),repeat('f',64),true);
select public.record_sms_consent(auth.uid(),(select id from fx where k='client'),'+13035550404',true,'WRITTEN','Synthetic test only',null);
select lives_ok($$select public.prepare_payment_delivery((select id from fx where k='sms-delivery'),(select id from fx where k='grant'),(select id from fx where k='conversation'),'SMS','+13035550404','','Pay: {{payment_link}}')$$,'Consenting current SMS recipient supported');
set local role service_role;
select set_config('request.jwt.claims','{"role":"service_role"}',true);
select public.capture_payment_delivery((select id from fx where k='sms-delivery'),'73700000-0000-4000-8000-000000000001',jsonb_build_object('from','+13035550999','account_sid','AC'||repeat('a',32)),repeat('1',64),repeat('2',64));
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"73700000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'sms-outbox',id from public.enqueue_payment_delivery((select id from fx where k='sms-delivery'),repeat('1',64),repeat('2',64),true);
reset role;
update public.communication_outbox set state='claimed',lease_token='73700000-0000-4000-8000-000000000090',lease_expires_at=now()+interval '5 minutes' where id in (select id from fx where k in ('attached-outbox','sms-outbox'));
set local role service_role;
select set_config('request.jwt.claims','{"role":"service_role"}',true);
select is(public.payment_delivery_context((select id from fx where k='attached-outbox'),'73700000-0000-4000-8000-000000000090')#>>'{invoice_payload,attachments,0,content_type}','text/html','Leased worker gets exact supported frozen attachment');
select ok((public.start_communication_attempt((select id from fx where k='attached-outbox'),'73700000-0000-4000-8000-000000000090',jsonb_build_object('from','billing@thelivingroom.vet','reply_to','billing@thelivingroom.vet','payment_delivery_message_hash',repeat('e',64),'payment_delivery_payload_hash',repeat('f',64)))).attempt_started_at is not null,'Exact sender and materialization proof opens guarded attempt');
reset role;
select is((select provider_config from public.communication_outbox where id=(select id from fx where k='attached-outbox')),'{"from":"billing@thelivingroom.vet","reply_to":"billing@thelivingroom.vet"}'::jsonb,'Proof fields stripped before provider metadata persistence');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"73700000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select public.credit_billing_invoice(gen_random_uuid(),(select id from fx where k='invoice'),100,'Synthetic adjustment');
set local role service_role;
select set_config('request.jwt.claims','{"role":"service_role"}',true);
select is((public.start_communication_attempt((select id from fx where k='sms-outbox'),'73700000-0000-4000-8000-000000000090',jsonb_build_object('from','+13035550999','account_sid','AC'||repeat('a',32),'payment_delivery_message_hash',repeat('1',64),'payment_delivery_payload_hash',repeat('2',64)))).state,'failed','Invoice credit blocks pending send despite correct materialization proof');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"73700000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select public.revoke_payment_collection((select id from fx where k='grant'),'Synthetic revocation');
select lives_ok($$select public.enqueue_payment_delivery((select id from fx where k='delivery'),repeat('c',64),repeat('d',64),true)$$,'Committed receipt recovers before grant eligibility after revocation');
select is(public.recover_payment_delivery((select id from fx where k='delivery'))#>>'{receipt,state}','failed','Recovery reports actual receipt state');
select throws_ok($$select public.prepare_payment_delivery((select id from fx where k='second'),(select id from fx where k='grant'),(select id from fx where k='conversation'),'EMAIL','payment@example.test','Invoice','Pay: {{payment_link}}')$$,'42501',null,'Revocation prevents new delivery');

select is(jsonb_array_length(public.list_payment_deliveries((select id from fx where k='invoice'))->'deliveries'),3,'Original actor discovers all three delivery channels after revocation');
select is(public.list_payment_deliveries((select id from fx where k='invoice'))->>'client_id',(select id::text from fx where k='client'),'History binds current invoice household');
select is(public.list_payment_deliveries((select id from fx where k='invoice'))->>'has_more','false','Small history has no hidden page');
select is(jsonb_array_length(public.list_payment_deliveries((select id from fx where k='invoice'),(select id from fx where k='grant'))->'deliveries'),3,'Owned grant filter includes retained history');
select throws_ok($$select public.list_payment_deliveries(gen_random_uuid())$$,'42501',null,'Unknown invoice rejected');
select throws_ok($$select public.list_payment_deliveries((select id from fx where k='invoice'),gen_random_uuid())$$,'42501',null,'Unknown grant rejected');
insert into fx values('history-invoice',gen_random_uuid());
select public.create_billing_invoice((select id from fx where k='history-invoice'),(select id from fx where k='other-client'));
select throws_ok($$select public.list_payment_deliveries((select id from fx where k='history-invoice'),(select id from fx where k='grant'))$$,'42501',null,'Cross-invoice and household grant rejected');
select set_config('request.jwt.claims','{"sub":"73700000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select is(jsonb_array_length(public.list_payment_deliveries((select id from fx where k='invoice'))->'deliveries'),0,'Another staff actor cannot discover original deliveries');
select throws_ok($$select public.list_payment_deliveries((select id from fx where k='invoice'),(select id from fx where k='grant'))$$,'42501',null,'Another actor cannot select original grant history');
reset role;
-- Privileged synthetic history rows exercise bounded discovery, not delivery preparation.
insert into public.payment_delivery_requests(id,grant_id,actor_id,invoice_id,client_id,source_hash,amount_cents,conversation_id,channel,recipient,subject,body_template,created_at)
select gen_random_uuid(),r.grant_id,r.actor_id,r.invoice_id,r.client_id,r.source_hash,r.amount_cents,r.conversation_id,r.channel,r.recipient,r.subject,r.body_template,now()+n*interval '1 second' from public.payment_delivery_requests r cross join generate_series(1,100) n where r.id=(select id from fx where k='delivery');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"73700000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select is(jsonb_array_length(public.list_payment_deliveries((select id from fx where k='invoice'))->'deliveries'),100,'History limited to latest 100 envelopes');
select is(public.list_payment_deliveries((select id from fx where k='invoice'))->>'has_more','true','Additional history explicitly indicated');
select ok(not ((public.list_payment_deliveries((select id from fx where k='invoice'))->'deliveries')->0 ?| array['payload_text','capability','invoice_payload_text']),'Discovery excludes service materialization data');
select set_config('request.jwt.claims','{"sub":"73700000-0000-4000-8000-000000000003","role":"authenticated"}',true);
select throws_ok($$select public.list_payment_deliveries((select id from fx where k='invoice'))$$,'42501',null,'Inactive actor denied');
set local role anon;
select throws_ok($$select public.list_payment_deliveries((select id from fx where k='invoice'))$$,'42501',null,'Anonymous discovery denied');
set local role service_role;
select throws_ok($$select public.list_payment_deliveries((select id from fx where k='invoice'))$$,'42501',null,'Service cannot substitute for original staff discovery');
select * from finish();rollback;
