begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,raw_user_meta_data) values
 ('73400000-0000-4000-8000-000000000001','collection-staff@example.test','{}'),
 ('73400000-0000-4000-8000-000000000002','collection-other@example.test','{}'),
 ('73400000-0000-4000-8000-000000000003','collection-inactive@example.test','{}');
update public.profiles set is_active=false where id='73400000-0000-4000-8000-000000000003';
create temp table fx(k text primary key,id uuid);grant all on fx to authenticated,service_role;
create temp table snapshots(k text primary key,v jsonb);grant all on snapshots to authenticated,service_role;
set local role service_role;
select public.configure_payment_provider('acct_test',false,'https://thelivingroom.vet');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"73400000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'client',id from public.save_client(auth.uid(),null,null,'Payment','Family',null,null,'EMAIL',null,null);
insert into fx select 'other-client',id from public.save_client(auth.uid(),null,null,'Different','Family',null,null,'EMAIL',null,null);
insert into fx select 'product',id from public.save_catalog_product(null,null,'Visit','service','','visit',10000,true);
insert into fx values('invoice','73400000-0000-4000-8000-000000000010'),('attempt','73400000-0000-4000-8000-000000000020'),('refund','73400000-0000-4000-8000-000000000030');
select public.create_billing_invoice((select id from fx where k='invoice'),(select id from fx where k='client'));
select public.add_invoice_service(gen_random_uuid(),(select id from fx where k='invoice'),null,(select id from fx where k='product'),1);
select public.issue_billing_invoice((select id from fx where k='invoice'),(select version from public.billing_invoices where id=(select id from fx where k='invoice')));
insert into snapshots select 'before',public.read_invoice_payment_state((select id from fx where k='invoice'),(select id from fx where k='client'));
insert into fx values('grant','73400000-0000-4000-8000-000000000040');
insert into snapshots values('deadline',jsonb_build_object('expires',clock_timestamp()+interval '6 days'));
select throws_ok($$select public.prepare_payment_collection((select id from fx where k='grant'),(select id from fx where k='invoice'),(select id from fx where k='client'),(select v->>'source_hash' from snapshots where k='before'),10000,now()+interval '8 days')$$,'23514','Expiry must be within seven days','Collection lifetime bounded');
select lives_ok($$select public.prepare_payment_collection((select id from fx where k='grant'),(select id from fx where k='invoice'),(select id from fx where k='client'),(select v->>'source_hash' from snapshots where k='before'),10000,(select (v->>'expires')::timestamptz from snapshots where k='deadline'))$$,'Prepare exact reviewed amount');
select lives_ok($$select public.prepare_payment_collection((select id from fx where k='grant'),(select id from fx where k='invoice'),(select id from fx where k='client'),(select v->>'source_hash' from snapshots where k='before'),10000,(select (v->>'expires')::timestamptz from snapshots where k='deadline'))$$,'Exact preparation retry recovers original');
select throws_ok($$select public.prepare_payment_collection(gen_random_uuid(),(select id from fx where k='invoice'),(select id from fx where k='client'),(select v->>'source_hash' from snapshots where k='before'),10000,(select (v->>'expires')::timestamptz from snapshots where k='deadline'))$$,'23514','Recover existing payment collection draft','One unresolved draft per actor and source');
select throws_ok($$select public.capture_payment_collection((select id from fx where k='grant'),auth.uid(),'https://thelivingroom.vet','local-v1',repeat('a',64),repeat('b',64))$$,'42501',null,'Staff cannot write capability hashes');
select throws_ok($$select public.activate_payment_collection((select id from fx where k='grant'),repeat('a',64),'https://thelivingroom.vet','local-v1',true)$$,'42501',null,'Anonymous-facing service activation inaccessible to staff RPC');
select set_config('request.jwt.claims','{"sub":"73400000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select is(public.recover_payment_collection((select id from fx where k='invoice'),(select id from fx where k='grant')),null::jsonb,'Other actor cannot recover grant');
select throws_ok($$select public.revoke_payment_collection((select id from fx where k='grant'),'Other actor')$$,'42501',null,'Other actor cannot revoke grant');
set local role service_role;
select throws_ok($$select public.payment_collection_capture_context((select id from fx where k='grant'),'73400000-0000-4000-8000-000000000002','https://thelivingroom.vet','local-v1')$$,'42501',null,'Service capture validates owning actor');
select throws_ok($$select public.payment_collection_capture_context((select id from fx where k='grant'),'73400000-0000-4000-8000-000000000001','https://attacker.test','local-v1')$$,'42501',null,'Origin must match configured provider');
insert into snapshots select 'capture',public.capture_payment_collection((select id from fx where k='grant'),'73400000-0000-4000-8000-000000000001','https://thelivingroom.vet','local-v1',repeat('a',64),repeat('b',64));
select lives_ok($$select public.capture_payment_collection((select id from fx where k='grant'),'73400000-0000-4000-8000-000000000001','https://thelivingroom.vet','local-v1',repeat('a',64),repeat('b',64))$$,'Lost capture acknowledgement recovers exact hashes');
select throws_ok($$select public.capture_payment_collection((select id from fx where k='grant'),'73400000-0000-4000-8000-000000000001','https://thelivingroom.vet','local-v2',repeat('a',64),repeat('b',64))$$,'23505',null,'Captured key version cannot change');
select throws_ok($$select public.inspect_payment_collection((select id from fx where k='grant'),repeat('a',64),'https://thelivingroom.vet','local-v1')$$,'42501',null,'Captured but unreviewed grant cannot activate');
select throws_ok($$select public.read_payment_collection_status((select id from fx where k='grant'),repeat('b',64),'https://thelivingroom.vet','local-v1')$$,'42501',null,'Unreviewed status capability unavailable');
select is((select (v#>>'{grant,status_expires_at}')::timestamptz-(v#>>'{grant,expires_at}')::timestamptz from snapshots where k='capture'),interval '30 days','Status deadline is thirty days beyond collection deadline');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"73400000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select throws_ok($$select public.attest_payment_collection((select id from fx where k='grant'),repeat('f',64),true)$$,'23514',null,'Review binds exact context');
select public.attest_payment_collection((select id from fx where k='grant'),(select v#>>'{capture,context_hash}' from snapshots where k='capture'),true);
select is((public.recover_payment_collection((select id from fx where k='invoice'),(select id from fx where k='grant'))#>>'{grant,state}'),'reviewed','Staff review persists');
select is(jsonb_array_length(public.list_payment_collections((select id from fx where k='invoice'),(select id from fx where k='client'))),1,'Reviewed history remains discoverable');
set local role service_role;
select is(public.inspect_payment_collection((select id from fx where k='grant'),repeat('a',64),'https://thelivingroom.vet','local-v1')->>'state','ready','Inspect reviewed grant creates no provider attempt');
select throws_ok($$select public.inspect_payment_collection((select id from fx where k='grant'),repeat('b',64),'https://thelivingroom.vet','local-v1')$$,'42501',null,'Status capability cannot collect');
select throws_ok($$select public.read_payment_collection_status((select id from fx where k='grant'),repeat('a',64),'https://thelivingroom.vet','local-v1')$$,'42501',null,'Collection capability cannot substitute for status');
select throws_ok($$select public.inspect_payment_collection(gen_random_uuid(),repeat('a',64),'https://thelivingroom.vet','local-v1')$$,'42501',null,'Cross-grant capability unavailable');
select throws_ok($$select public.inspect_payment_collection((select id from fx where k='grant'),repeat('a',64),'https://thelivingroom.vet','missing-v1')$$,'42501',null,'Wrong key version unavailable');
select throws_ok($$select public.activate_payment_collection((select id from fx where k='grant'),repeat('a',64),'https://thelivingroom.vet','local-v1')$$,'42501','Payment collection creation paused','Omitted allow-create fails closed');
insert into snapshots select 'activated',public.activate_payment_collection((select id from fx where k='grant'),repeat('a',64),'https://thelivingroom.vet','local-v1',true);
insert into fx select 'active',(v#>>'{attempt,id}')::uuid from snapshots where k='activated';
select is(public.activate_payment_collection((select id from fx where k='grant'),repeat('a',64),'https://thelivingroom.vet','local-v1',true)#>>'{attempt,id}',(select id::text from fx where k='active'),'Repeated activation preserves uncertain attempt UUID');
select is(public.activate_payment_collection((select id from fx where k='grant'),repeat('a',64),'https://thelivingroom.vet','local-v1',false)#>>'{attempt,id}',(select id::text from fx where k='active'),'Paused collection can recover existing attempt');
select is((select v#>>'{attempt,return_context_version}' from snapshots where k='activated'),'2','New attempt uses versioned return context');
select is((select v#>>'{attempt,return_scope_id}' from snapshots where k='activated'),(select id::text from fx where k='grant'),'Return scope is original collection grant');
select is((select v#>>'{attempt,success_url}' from snapshots where k='activated'),'https://thelivingroom.vet/payment/return/'||(select id from fx where k='grant')||'#{{payment_status}}','Database stores canonical template without status token');
select is((select (v#>>'{attempt,session_expires_at}')::timestamptz-(v#>>'{attempt,created_at}')::timestamptz from snapshots where k='activated'),interval '2 hours','Immutable session lifetime two hours');
select is((select (v#>>'{attempt,retry_before}')::timestamptz-(v#>>'{attempt,created_at}')::timestamptz from snapshots where k='activated'),interval '23 hours','Immutable retry horizon 23 hours');
set local role authenticated;
select throws_ok($$select public.credit_billing_invoice(gen_random_uuid(),(select id from fx where k='invoice'),100,'Race with checkout')$$,'23514','Resolve existing checkout first','Activated attempt blocks competing credit');
set local role service_role;
select public.apply_checkout_evidence('evt_collection_expired',(select id from fx where k='active'),'acct_test',false,'session_expired','cs_test_first',null,10000,'usd',(select v->>'source_hash' from snapshots where k='before'));
select throws_ok($$select public.activate_payment_collection((select id from fx where k='grant'),repeat('a',64),'https://thelivingroom.vet','local-v1',false)$$,'42501','Payment collection creation paused','Paused collection never renews expired attempt');
insert into snapshots select 'renewed',public.activate_payment_collection((select id from fx where k='grant'),repeat('a',64),'https://thelivingroom.vet','local-v1',true);
insert into fx select 'renewed',(v#>>'{attempt,id}')::uuid from snapshots where k='renewed';
select isnt((select id from fx where k='renewed'),(select id from fx where k='active'),'Accepted expiry allows a new attempt');
select is(public.activate_payment_collection((select id from fx where k='grant'),repeat('a',64),'https://thelivingroom.vet','local-v1',true)#>>'{attempt,id}',(select id::text from fx where k='renewed'),'Renewal reuse selects unresolved attempt');
select public.apply_checkout_evidence('evt_collection_paid',(select id from fx where k='renewed'),'acct_test',false,'payment_succeeded','cs_test_second','pi_collection',10000,'usd',(select v->>'source_hash' from snapshots where k='before'));
select is(public.activate_payment_collection((select id from fx where k='grant'),repeat('a',64),'https://thelivingroom.vet','local-v1',true)->>'state','paid','Settled grant cannot create another session');
insert into snapshots select 'status',public.read_payment_collection_status((select id from fx where k='grant'),repeat('b',64),'https://thelivingroom.vet','local-v1');
select is((select v->>'confirmed_paid_cents' from snapshots where k='status'),'10000','Status reads confirmed scoped ledger cash');
select ok(not (select v ?| array['invoice_id','client_id','actor_id','source_hash','services','client_name'] from snapshots where k='status'),'Public status excludes household and medical details');
set local role authenticated;
select public.revoke_payment_collection((select id from fx where k='grant'),'Synthetic revocation');
select is(public.recover_payment_collection((select id from fx where k='invoice'),(select id from fx where k='grant'))#>>'{grant,state}','revoked','History recoverable after revocation');
set local role service_role;
select throws_ok($$select public.inspect_payment_collection((select id from fx where k='grant'),repeat('a',64),'https://thelivingroom.vet','local-v1')$$,'42501',null,'Revocation suppresses future collection response');
select is(public.read_payment_collection_status((select id from fx where k='grant'),repeat('b',64),'https://thelivingroom.vet','local-v1')->>'state','paid','Narrow status remains readable after revocation');
reset role;
select is((select count(*) from public.payment_collection_attempts where grant_id=(select id from fx where k='grant')),2::bigint,'Only original and authoritatively expired renewal exist');
select throws_ok($$update public.payment_collection_grants set amount_cents=1 where id=(select id from fx where k='grant')$$,'23514','Financial history is append-only','Grant metadata immutable');
select throws_ok($$delete from public.payment_collection_captures where grant_id=(select id from fx where k='grant')$$,'23514','Financial history is append-only','Capture cannot be erased');
set local role anon;
select throws_ok($$select * from public.payment_collection_grants$$,'42501',null,'Anonymous direct grant read denied');
select throws_ok($$select public.read_payment_collection_status(gen_random_uuid(),repeat('a',64),'https://thelivingroom.vet','local-v1')$$,'42501',null,'Anonymous cannot bypass Edge capability checks via RPC');
reset role;

set local role authenticated;
select set_config('request.jwt.claims','{"sub":"73400000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'payment',id from public.invoice_payments where invoice_id=(select id from fx where k='invoice');
select public.credit_billing_invoice(gen_random_uuid(),(select id from fx where k='invoice'),1000,'Synthetic partial adjustment');
select public.prepare_invoice_refund((select id from fx where k='refund'),(select id from fx where k='invoice'),(select id from fx where k='payment'),1000,'Synthetic partial refund');
set local role service_role;
select public.apply_refund_evidence('evt_collection_refund',(select id from fx where k='refund'),'acct_test',false,'re_collection','pi_collection',1000,'usd','succeeded');
select is(public.read_payment_collection_status((select id from fx where k='grant'),repeat('b',64),'https://thelivingroom.vet','local-v1')->>'state','partially_refunded','Partial refund is distinguished from full refund');
select is(public.read_payment_collection_status((select id from fx where k='grant'),repeat('b',64),'https://thelivingroom.vet','local-v1')->>'confirmed_refunded_cents','1000','Scoped status reports exact confirmed refund');

set local role authenticated;
insert into fx values('deadline45-invoice',gen_random_uuid()),('deadline45-grant',gen_random_uuid());
select public.create_billing_invoice((select id from fx where k='deadline45-invoice'),(select id from fx where k='client'));
select public.add_invoice_service(gen_random_uuid(),(select id from fx where k='deadline45-invoice'),null,(select id from fx where k='product'),1);
select public.issue_billing_invoice((select id from fx where k='deadline45-invoice'),(select version from public.billing_invoices where id=(select id from fx where k='deadline45-invoice')));
select public.prepare_payment_collection((select id from fx where k='deadline45-grant'),(select id from fx where k='deadline45-invoice'),(select id from fx where k='client'),public.read_invoice_payment_state((select id from fx where k='deadline45-invoice'),(select id from fx where k='client'))->>'source_hash',10000,now()+interval '45 minutes');
set local role service_role;
select public.capture_payment_collection((select id from fx where k='deadline45-grant'),'73400000-0000-4000-8000-000000000001','https://thelivingroom.vet','local-v1',repeat('c',64),repeat('d',64));
set local role authenticated;
select public.attest_payment_collection((select id from fx where k='deadline45-grant'),public.recover_payment_collection((select id from fx where k='deadline45-invoice'),(select id from fx where k='deadline45-grant'))#>>'{capture,context_hash}',true);
set local role service_role;
insert into snapshots select 'deadline45',public.activate_payment_collection((select id from fx where k='deadline45-grant'),repeat('c',64),'https://thelivingroom.vet','local-v1',true);
select is((select (v#>>'{attempt,session_expires_at}')::timestamptz from snapshots where k='deadline45'),now()+interval '45 minutes','Provider session never outlives collection deadline');

set local role authenticated;
insert into fx values('deadline30-invoice',gen_random_uuid()),('deadline30-grant',gen_random_uuid());
select public.create_billing_invoice((select id from fx where k='deadline30-invoice'),(select id from fx where k='client'));
select public.add_invoice_service(gen_random_uuid(),(select id from fx where k='deadline30-invoice'),null,(select id from fx where k='product'),1);
select public.issue_billing_invoice((select id from fx where k='deadline30-invoice'),(select version from public.billing_invoices where id=(select id from fx where k='deadline30-invoice')));
select public.prepare_payment_collection((select id from fx where k='deadline30-grant'),(select id from fx where k='deadline30-invoice'),(select id from fx where k='client'),public.read_invoice_payment_state((select id from fx where k='deadline30-invoice'),(select id from fx where k='client'))->>'source_hash',10000,now()+interval '30 minutes');
set local role service_role;
select public.capture_payment_collection((select id from fx where k='deadline30-grant'),'73400000-0000-4000-8000-000000000001','https://thelivingroom.vet','local-v1',repeat('c',64),repeat('d',64));
set local role authenticated;
select public.attest_payment_collection((select id from fx where k='deadline30-grant'),public.recover_payment_collection((select id from fx where k='deadline30-invoice'),(select id from fx where k='deadline30-grant'))#>>'{capture,context_hash}',true);
set local role service_role;
select throws_ok($$select public.activate_payment_collection((select id from fx where k='deadline30-grant'),repeat('c',64),'https://thelivingroom.vet','local-v1',true)$$,'42501','Payment collection deadline too close','Less than31minutes remaining cannot create session');
reset role;
select set_config('request.jwt.claims','{}',true);
update public.profiles set is_active=false where id='73400000-0000-4000-8000-000000000001';
set local role service_role;
select throws_ok($$select public.inspect_payment_collection((select id from fx where k='deadline45-grant'),repeat('c',64),'https://thelivingroom.vet','local-v1')$$,'42501',null,'Deactivated originating staff blocks existing attempt URL release');
reset role;
select * from finish();
rollback;
