begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,raw_user_meta_data) values
 ('73000000-0000-4000-8000-000000000001','payment-staff@example.test','{}'),
 ('73000000-0000-4000-8000-000000000002','payment-other@example.test','{}'),
 ('73000000-0000-4000-8000-000000000003','payment-inactive@example.test','{}');
update public.profiles set is_active = true where id in ('73000000-0000-4000-8000-000000000001','73000000-0000-4000-8000-000000000002','73000000-0000-4000-8000-000000000003');
insert into public.user_roles (user_id, role) values ('73000000-0000-4000-8000-000000000001','STAFF'),('73000000-0000-4000-8000-000000000002','STAFF'),('73000000-0000-4000-8000-000000000003','STAFF');

update public.profiles set is_active=false where id='73000000-0000-4000-8000-000000000003';
create temp table fx(k text primary key,id uuid);grant all on fx to authenticated,service_role;
create temp table snapshots(k text primary key,v jsonb);grant all on snapshots to authenticated,service_role;
set local role service_role;
select public.configure_payment_provider('acct_test',false,'https://thelivingroom.vet');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"73000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'client',id from public.save_client(auth.uid(),null,null,'Payment','Family',null,null,'EMAIL',null,null);
insert into fx select 'other-client',id from public.save_client(auth.uid(),null,null,'Different','Family',null,null,'EMAIL',null,null);
insert into fx select 'product',id from public.save_catalog_product(null,null,'Visit','service','','visit',10000,true);
insert into fx values('invoice','73000000-0000-4000-8000-000000000010'),('attempt','73000000-0000-4000-8000-000000000020'),('refund','73000000-0000-4000-8000-000000000030');
select public.create_billing_invoice((select id from fx where k='invoice'),(select id from fx where k='client'));
select public.add_invoice_service(gen_random_uuid(),(select id from fx where k='invoice'),null,(select id from fx where k='product'),1);
select public.issue_billing_invoice((select id from fx where k='invoice'),(select version from public.billing_invoices where id=(select id from fx where k='invoice')));
insert into snapshots select 'before',public.read_invoice_payment_state((select id from fx where k='invoice'),(select id from fx where k='client'));
select is((select v#>>'{balance,outstanding_cents}' from snapshots where k='before'),'10000','Issued obligation is exact integer cents');
select throws_ok($$select public.read_invoice_payment_state((select id from fx where k='invoice'),(select id from fx where k='other-client'))$$,'42501',null,'Wrong household denied');
select throws_ok($$select public.prepare_invoice_checkout((select id from fx where k='attempt'),(select id from fx where k='invoice'),(select id from fx where k='client'),(select v->>'source_hash' from snapshots where k='before'),9999,'acct_test',false,'https://thelivingroom.vet/payment/return','https://thelivingroom.vet/payment/cancel')$$,'40001',null,'Underpayment preparation rejected');
select throws_ok($$select public.configure_payment_provider('acct_fake',false,'https://attacker.test')$$,'42501',null,'Staff cannot commission a provider');
select throws_ok($$select public.prepare_invoice_checkout(gen_random_uuid(),(select id from fx where k='invoice'),(select id from fx where k='client'),(select v->>'source_hash' from snapshots where k='before'),10000,'acct_test',false,'https://attacker.test/payment/return','https://thelivingroom.vet/payment/cancel')$$,'23514','Payment provider or return destination not configured','Untrusted success URL rejected');
select throws_ok($$select public.prepare_invoice_checkout(gen_random_uuid(),(select id from fx where k='invoice'),(select id from fx where k='client'),(select v->>'source_hash' from snapshots where k='before'),10000,'acct_test',true,'https://thelivingroom.vet/payment/return','https://thelivingroom.vet/payment/cancel')$$,'23514','Payment provider or return destination not configured','Uncommissioned live mode rejected');
select lives_ok($$select public.prepare_invoice_checkout((select id from fx where k='attempt'),(select id from fx where k='invoice'),(select id from fx where k='client'),(select v->>'source_hash' from snapshots where k='before'),10000,'acct_test',false,'https://thelivingroom.vet/payment/return','https://thelivingroom.vet/payment/cancel')$$,'Prepare durable reviewed intent');
select lives_ok($$select public.prepare_invoice_checkout((select id from fx where k='attempt'),(select id from fx where k='invoice'),(select id from fx where k='client'),(select v->>'source_hash' from snapshots where k='before'),10000,'acct_test',false,'https://thelivingroom.vet/payment/return','https://thelivingroom.vet/payment/cancel')$$,'Exact retry recovers intent');
select is((select count(*) from public.invoice_checkout_attempts where invoice_id=(select id from fx where k='invoice')),1::bigint,'Retry creates no second attempt');
select throws_ok($$select public.prepare_invoice_checkout((select id from fx where k='attempt'),(select id from fx where k='invoice'),(select id from fx where k='client'),(select v->>'source_hash' from snapshots where k='before'),10000,'acct_other',false,'https://thelivingroom.vet/payment/return','https://thelivingroom.vet/payment/cancel')$$,'23514',null,'Retry cannot switch provider account');
select throws_ok($$select public.prepare_invoice_checkout(gen_random_uuid(),(select id from fx where k='invoice'),(select id from fx where k='client'),(select v->>'source_hash' from snapshots where k='before'),10000,'acct_test',false,'https://thelivingroom.vet/payment/return','https://thelivingroom.vet/payment/cancel')$$,'23514','Resolve existing checkout first','Second unresolved checkout rejected');
select throws_ok($$select public.credit_billing_invoice(gen_random_uuid(),(select id from fx where k='invoice'),100,'Adjustment')$$,'23514','Resolve existing checkout first','Prepared checkout blocks credits');
select throws_ok($$select public.void_billing_invoice((select id from fx where k='invoice'),(select version from public.billing_invoices where id=(select id from fx where k='invoice')),'Duplicate')$$,'23514','Resolve existing checkout first','Prepared checkout blocks void');
select throws_ok($$select public.apply_checkout_evidence('evt_fake',(select id from fx where k='attempt'),'acct_test',false,'payment_succeeded','cs_test_1','pi_test',10000,'usd',(select v->>'source_hash' from snapshots where k='before'))$$,'42501',null,'Staff cannot fabricate provider evidence');
select throws_ok($$update public.invoice_checkout_attempts set amount_cents=1$$,'42501',null,'Staff cannot mutate frozen intent');
select set_config('request.jwt.claims','{"sub":"73000000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select throws_ok($$select public.prepare_invoice_checkout((select id from fx where k='attempt'),(select id from fx where k='invoice'),(select id from fx where k='client'),(select v->>'source_hash' from snapshots where k='before'),10000,'acct_test',false,'https://thelivingroom.vet/payment/return','https://thelivingroom.vet/payment/cancel')$$,'23514',null,'Other actor cannot reuse request');
set local role service_role;
select throws_ok($$select public.checkout_payment_context((select id from fx where k='attempt'),'73000000-0000-4000-8000-000000000002')$$,'42501',null,'Service recovery validates owning actor');
select is(public.checkout_payment_context((select id from fx where k='attempt'),'73000000-0000-4000-8000-000000000001')->>'state','prepared','No local timeout marks intent expired');
select lives_ok($$select public.apply_checkout_evidence('evt_open',(select id from fx where k='attempt'),'acct_test',false,'session_open','cs_test_1',null,10000,'usd',(select v->>'source_hash' from snapshots where k='before'))$$,'Provider session linked without storing URL');
select is(public.provider_checkout_context((select id from fx where k='attempt'))->>'session_id','cs_test_1','Provider recovery obtains existing session identifier');
select lives_ok($$select public.apply_checkout_evidence('evt_expired_first',(select id from fx where k='attempt'),'acct_test',false,'session_expired','cs_test_1',null,10000,'usd',(select v->>'source_hash' from snapshots where k='before'))$$,'Authoritative expiration recorded');
select is(public.provider_checkout_context((select id from fx where k='attempt'))->>'state','expired','Only provider evidence releases collection intent');
select lives_ok($$select public.apply_checkout_evidence('evt_paid',(select id from fx where k='attempt'),'acct_test',false,'payment_succeeded','cs_test_1','pi_test',10000,'usd',(select v->>'source_hash' from snapshots where k='before'))$$,'Confirmed matching payment applied');
select lives_ok($$select public.apply_checkout_evidence('evt_paid',(select id from fx where k='attempt'),'acct_test',false,'payment_succeeded','cs_test_1','pi_test',10000,'usd',(select v->>'source_hash' from snapshots where k='before'))$$,'Same provider event replay accepted once');
select lives_ok($$select public.apply_checkout_evidence('evt_paid_duplicate',(select id from fx where k='attempt'),'acct_test',false,'payment_succeeded','cs_test_1','pi_test',10000,'usd',(select v->>'source_hash' from snapshots where k='before'))$$,'Different event for same payment accepted once');
select throws_ok($$select public.apply_checkout_evidence('evt_paid',(select id from fx where k='attempt'),'acct_test',false,'payment_succeeded','cs_test_1','pi_test',9999,'usd',(select v->>'source_hash' from snapshots where k='before'))$$,'23514',null,'Event replay cannot change evidence');
select lives_ok($$select public.apply_checkout_evidence('evt_expired_late',(select id from fx where k='attempt'),'acct_test',false,'session_expired','cs_test_1',null,10000,'usd',(select v->>'source_hash' from snapshots where k='before'))$$,'Late expiration retained');
select is(public.checkout_payment_context((select id from fx where k='attempt'),'73000000-0000-4000-8000-000000000001')->>'state','paid','Late expiration never erases payment');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"73000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select is((select count(*) from public.invoice_payments where invoice_id=(select id from fx where k='invoice')),1::bigint,'Provider payment counted exactly once');
insert into fx select 'payment',id from public.invoice_payments;
insert into snapshots select 'paid',public.read_invoice_payment_state((select id from fx where k='invoice'),(select id from fx where k='client'));
select is((select v#>>'{balance,outstanding_cents}' from snapshots where k='paid'),'0','Settled invoice has no outstanding amount');
select throws_ok($$select public.void_billing_invoice((select id from fx where k='invoice'),(select version from public.billing_invoices where id=(select id from fx where k='invoice')),'Duplicate')$$,'23514','Invoices with payment history cannot be voided','Payment history blocks void');
select throws_ok($$select public.prepare_invoice_refund((select id from fx where k='refund'),(select id from fx where k='invoice'),(select id from fx where k='payment'),2000,'Service adjustment')$$,'23514',null,'Uncredited settled obligation is not refundable');
select lives_ok($$select public.credit_billing_invoice(gen_random_uuid(),(select id from fx where k='invoice'),3000,'Service adjustment')$$,'Accounting credit changes obligation');
insert into snapshots select 'credited',public.read_invoice_payment_state((select id from fx where k='invoice'),(select id from fx where k='client'));
select isnt((select v->>'source_hash' from snapshots where k='credited'),(select v->>'source_hash' from snapshots where k='paid'),'Source hash includes credits independently of invoice version');
select is((select v#>>'{balance,refundable_cents}' from snapshots where k='credited'),'3000','Credit makes excess cash refundable');
select lives_ok($$select public.prepare_invoice_refund((select id from fx where k='refund'),(select id from fx where k='invoice'),(select id from fx where k='payment'),2000,'Service adjustment')$$,'Reserve refund capacity');
select lives_ok($$select public.prepare_invoice_refund((select id from fx where k='refund'),(select id from fx where k='invoice'),(select id from fx where k='payment'),2000,'Service adjustment')$$,'Refund retry idempotent');
select throws_ok($$select public.prepare_invoice_refund(gen_random_uuid(),(select id from fx where k='invoice'),(select id from fx where k='payment'),1001,'Excess')$$,'23514',null,'Pending refund prevents over-refund');
select is(public.read_invoice_payment_state((select id from fx where k='invoice'),(select id from fx where k='client'))#>>'{balance,net_cash_cents}','10000','Pending refund does not reduce settled cash');
set local role service_role;
select is(public.refund_payment_context((select id from fx where k='refund'),'73000000-0000-4000-8000-000000000001')->>'provider_payment_id','pi_test','Refund service gets correct captured payment');
select lives_ok($$select public.apply_refund_evidence('evt_refund_pending',(select id from fx where k='refund'),'acct_test',false,'re_test','pi_test',2000,'usd','pending')$$,'Provider pending refund preserved');
select lives_ok($$select public.apply_refund_evidence('evt_refund_success',(select id from fx where k='refund'),'acct_test',false,'re_test','pi_test',2000,'usd','succeeded')$$,'Confirmed refund applied');
select lives_ok($$select public.apply_refund_evidence('evt_refund_success',(select id from fx where k='refund'),'acct_test',false,'re_test','pi_test',2000,'usd','succeeded')$$,'Confirmed refund replay idempotent');
select lives_ok($$select public.apply_refund_evidence('evt_refund_late_failed',(select id from fx where k='refund'),'acct_test',false,'re_test','pi_test',2000,'usd','failed')$$,'Late failure retained without erasing settlement');
select is(public.refund_payment_context((select id from fx where k='refund'),'73000000-0000-4000-8000-000000000001')->>'state','succeeded','Successful refund cannot revert');
set local role authenticated;
select is((select count(*) from public.invoice_refunds where invoice_id=(select id from fx where k='invoice')),1::bigint,'Refund counted once');
select is(public.read_invoice_payment_state((select id from fx where k='invoice'),(select id from fx where k='client'))#>>'{balance,net_cash_cents}','8000','Confirmed refund reduces cash exactly');
select is(public.read_invoice_payment_state((select id from fx where k='invoice'),(select id from fx where k='client'))#>>'{balance,outstanding_cents}','0','Refund does not reopen credited obligation');
select is(public.read_invoice_payment_state((select id from fx where k='invoice'),(select id from fx where k='client'))#>>'{balance,refundable_cents}','1000','Remaining refundable capacity correct');
set local role service_role;
select is((public.apply_checkout_evidence('evt_wrong_mode',(select id from fx where k='attempt'),'acct_test',true,'payment_succeeded','cs_test_1','pi_other',10000,'usd',(select v->>'source_hash' from snapshots where k='before'))).disposition,'quarantined','Live/test mismatch quarantined');
select is((public.apply_checkout_evidence('evt_wrong_amount',(select id from fx where k='attempt'),'acct_test',false,'payment_succeeded','cs_test_1','pi_other',9000,'usd',(select v->>'source_hash' from snapshots where k='before'))).disposition,'quarantined','Wrong amount quarantined');
select is(public.checkout_payment_context((select id from fx where k='attempt'),'73000000-0000-4000-8000-000000000001')->>'state','reconciliation','Quarantine visible as unresolved reconciliation');
set local role authenticated;
select is((select count(*) from public.invoice_payments where invoice_id=(select id from fx where k='invoice')),1::bigint,'Mismatch never changes ledger');
select throws_ok($$select public.credit_billing_invoice(gen_random_uuid(),(select id from fx where k='invoice'),100,'Adjustment')$$,'23514','Resolve existing checkout first','Unresolved mismatch blocks financial changes');
select set_config('request.jwt.claims','{"sub":"73000000-0000-4000-8000-000000000003","role":"authenticated"}',true);
select is((select count(*) from public.invoice_payments where invoice_id=(select id from fx where k='invoice')),0::bigint,'Inactive staff cannot read financial history');
select throws_ok($$select public.read_invoice_payment_state((select id from fx where k='invoice'),(select id from fx where k='client'))$$,'42501',null,'Inactive staff RPC denied');
set local role anon;
select throws_ok($$select * from public.invoice_payments$$,'42501',null,'Anonymous direct ledger denied');
reset role;
select throws_ok($$update public.invoice_payments set amount_cents=1$$,'23514','Financial history is append-only','Even privileged accidental mutation rejected');
select throws_ok($$delete from public.invoice_payment_evidence$$,'23514','Financial history is append-only','Provider receipts cannot be erased');
select throws_ok($$update public.invoice_refunds set amount_cents=1$$,'23514','Financial history is append-only','Refund ledger immutable');
select set_config('request.jwt.claims','{}',true);
update public.profiles set is_active=false where id='73000000-0000-4000-8000-000000000001';
set local role service_role;
select throws_ok($$select public.checkout_payment_context((select id from fx where k='attempt'),'73000000-0000-4000-8000-000000000001')$$,'42501',null,'Deactivated actor cannot recover Checkout for staff delivery');
select is(public.provider_checkout_context((select id from fx where k='attempt'))->>'payment_id','pi_test','Provider reconciliation continues after staff deactivation');
select is(public.provider_refund_context((select id from fx where k='refund'))->>'refund_id','re_test','Refund reconciliation continues after staff deactivation');
select throws_ok($$select public.configure_payment_provider('acct_second',false,'https://example.test')$$,'23505',null,'Second provider profile cannot silently change account');
reset role;
select * from finish();
rollback;
