begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,raw_user_meta_data) values
 ('73300000-0000-4000-8000-000000000001','reconciliation-staff@example.test','{}'),
 ('73300000-0000-4000-8000-000000000002','reconciliation-other@example.test','{}'),
 ('73300000-0000-4000-8000-000000000003','reconciliation-inactive@example.test','{}');
update public.profiles set is_active = true where id in ('73300000-0000-4000-8000-000000000001','73300000-0000-4000-8000-000000000002','73300000-0000-4000-8000-000000000003');
insert into public.user_roles (user_id, role) values ('73300000-0000-4000-8000-000000000001','STAFF'),('73300000-0000-4000-8000-000000000002','STAFF'),('73300000-0000-4000-8000-000000000003','STAFF');

update public.profiles set is_active=false where id='73300000-0000-4000-8000-000000000003';
create temp table fx(k text primary key,id uuid);grant all on fx to authenticated,service_role;
create temp table snapshots(k text primary key,v jsonb);grant all on snapshots to authenticated,service_role;
set local role service_role;
select public.configure_payment_provider('acct_test',false,'https://thelivingroom.vet');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"73300000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'client',id from public.save_client(auth.uid(),null,null,'Payment','Family',null,null,'EMAIL',null,null);
insert into fx select 'other-client',id from public.save_client(auth.uid(),null,null,'Different','Family',null,null,'EMAIL',null,null);
insert into fx select 'product',id from public.save_catalog_product(null,null,'Visit','service','','visit',10000,true);
insert into fx values('invoice','73300000-0000-4000-8000-000000000010'),('attempt','73300000-0000-4000-8000-000000000020'),('refund','73300000-0000-4000-8000-000000000030');
select public.create_billing_invoice((select id from fx where k='invoice'),(select id from fx where k='client'));
select public.add_invoice_service(gen_random_uuid(),(select id from fx where k='invoice'),null,(select id from fx where k='product'),1);
select public.issue_billing_invoice((select id from fx where k='invoice'),(select version from public.billing_invoices where id=(select id from fx where k='invoice')));
insert into snapshots select 'before',public.read_invoice_payment_state((select id from fx where k='invoice'),(select id from fx where k='client'));
select public.prepare_invoice_checkout((select id from fx where k='attempt'),(select id from fx where k='invoice'),(select id from fx where k='client'),(select v->>'source_hash' from snapshots where k='before'),10000,'acct_test',false,'https://thelivingroom.vet/payment/return','https://thelivingroom.vet/payment/cancel');
select is(jsonb_array_length(public.read_invoice_payment_state((select id from fx where k='invoice'),(select id from fx where k='client'))->'reconciliation_observations'),0,'No invented observations');
select throws_ok($$select public.record_payment_reconciliation('checkout',(select id from fx where k='attempt'),'provider_context_mismatch')$$,'42501',null,'Staff cannot fabricate observations');
select throws_ok($$insert into public.payment_reconciliation_observations(family,request_id,invoice_id,reason) select 'checkout',id,id,'provider_context_mismatch' from fx where k='attempt'$$,'42501',null,'Staff direct writes denied');
set local role service_role;
select throws_ok($$select public.record_payment_reconciliation('unknown',(select id from fx where k='attempt'),'provider_context_mismatch')$$,'23514',null,'Unknown family rejected');
select throws_ok($$select public.record_payment_reconciliation('checkout',(select id from fx where k='attempt'),'raw provider response')$$,'23514',null,'Free-text provider data rejected');
select throws_ok($$select public.record_payment_reconciliation('checkout',gen_random_uuid(),'provider_context_mismatch')$$,'42501',null,'Unknown request rejected');
select throws_ok($$select public.record_payment_reconciliation('refund',(select id from fx where k='attempt'),'provider_context_mismatch')$$,'42501',null,'Request cannot switch family');
select public.apply_checkout_evidence('evt_recon_paid',(select id from fx where k='attempt'),'acct_test',false,'payment_succeeded','cs_test_recon','pi_recon',10000,'usd',(select v->>'source_hash' from snapshots where k='before'));
set local role authenticated;
insert into fx select 'payment',id from public.invoice_payments where invoice_id=(select id from fx where k='invoice');
select public.credit_billing_invoice(gen_random_uuid(),(select id from fx where k='invoice'),3000,'Synthetic adjustment');
select public.prepare_invoice_refund((select id from fx where k='refund'),(select id from fx where k='invoice'),(select id from fx where k='payment'),1000,'Synthetic adjustment');
set local role service_role;
insert into fx select 'observation',id from public.record_payment_reconciliation('refund',(select id from fx where k='refund'),'provider_context_mismatch');
select is((public.record_payment_reconciliation('refund',(select id from fx where k='refund'),'provider_context_mismatch')).id,(select id from fx where k='observation'),'Exact retry returns same observation');
select is(public.provider_refund_context((select id from fx where k='refund'))->>'state','reconciliation','Malformed refund produces durable reconciliation');
select is(public.provider_refund_context((select id from fx where k='refund'))->>'refund_id',null::text,'No fictional provider refund ID');
select throws_ok($$insert into public.payment_reconciliation_observations(family,request_id,invoice_id,reason) select 'refund',id,id,'provider_context_mismatch' from fx where k='refund'$$,'42501',null,'Service direct writes denied; RPC only');
set local role authenticated;
select is((select count(*) from public.payment_reconciliation_observations where invoice_id=(select id from fx where k='invoice')),1::bigint,'Active staff read one deduplicated observation');
select is((select count(*) from public.invoice_refund_evidence where request_id=(select id from fx where k='refund')),0::bigint,'Malformed response creates no invented refund evidence');
select is((select count(*) from public.invoice_refunds where request_id=(select id from fx where k='refund')),0::bigint,'Malformed response never changes settled refund cash');
insert into snapshots select 'review',public.read_invoice_payment_state((select id from fx where k='invoice'),(select id from fx where k='client'));
select is((select v#>>'{balance,pending_refund_cents}' from snapshots where k='review'),'1000','Reconciliation preserves reservation');
select is((select v#>>'{balance,net_cash_cents}' from snapshots where k='review'),'10000','Reconciliation does not reduce actual cash');
select is((select v#>>'{reconciliation_observations,0,reason}' from snapshots where k='review'),'provider_context_mismatch','Staff state exposes safe review reason');
select is((select v#>>'{reconciliation_observations,0,invoice_id}' from snapshots where k='review'),(select id::text from fx where k='invoice'),'Observation invoice derived from validated request');
select lives_ok($$select public.prepare_invoice_refund((select id from fx where k='refund'),(select id from fx where k='invoice'),(select id from fx where k='payment'),1000,'Synthetic adjustment')$$,'Existing immutable refund intent remains recoverable');
select throws_ok($$select public.prepare_invoice_refund(gen_random_uuid(),(select id from fx where k='invoice'),(select id from fx where k='payment'),500,'Another adjustment')$$,'23514','Resolve payment reconciliation first','New refund blocked even with remaining capacity');
select throws_ok($$select public.credit_billing_invoice(gen_random_uuid(),(select id from fx where k='invoice'),100,'Another adjustment')$$,'23514','Resolve payment reconciliation first','New accounting credit blocked during refund review');
select throws_ok($$select public.prepare_invoice_checkout(gen_random_uuid(),(select id from fx where k='invoice'),(select id from fx where k='client'),(select v->>'source_hash' from snapshots where k='review'),10000,'acct_test',false,'https://thelivingroom.vet/payment/return','https://thelivingroom.vet/payment/cancel')$$,'23514','Resolve existing refund first','New checkout blocked during refund review');
set local role service_role;
select lives_ok($$select public.apply_refund_evidence('evt_recon_refund_paid',(select id from fx where k='refund'),'acct_test',false,'re_recon','pi_recon',1000,'usd','succeeded')$$,'Authoritative settlement can still be recorded');
select is(public.provider_refund_context((select id from fx where k='refund'))->>'state','reconciliation','Later settlement cannot silently clear review');
select lives_ok($$select public.record_payment_reconciliation('checkout',(select id from fx where k='attempt'),'provider_object_unavailable')$$,'Checkout observation records missing object without fake evidence');
select is(public.provider_checkout_context((select id from fx where k='attempt'))->>'state','reconciliation','Checkout observation overrides paid display without erasing payment');
set local role authenticated;
select is((select count(*) from public.invoice_payments where invoice_id=(select id from fx where k='invoice')),1::bigint,'Original settled payment retained');
select is((select count(*) from public.invoice_refunds where invoice_id=(select id from fx where k='invoice')),1::bigint,'Verified refund retained during review');
select is(public.read_invoice_payment_state((select id from fx where k='invoice'),(select id from fx where k='client'))#>>'{balance,pending_refund_cents}','0','Settled refund under review is not reserved again');
select is(public.read_invoice_payment_state((select id from fx where k='invoice'),(select id from fx where k='client'))#>>'{balance,net_cash_cents}','9000','Settled refund cash is counted once under review');
select set_config('request.jwt.claims','{"sub":"73300000-0000-4000-8000-000000000003","role":"authenticated"}',true);
select is((select count(*) from public.payment_reconciliation_observations where invoice_id=(select id from fx where k='invoice')),0::bigint,'Inactive staff cannot read observations');
select throws_ok($$select public.read_invoice_payment_state((select id from fx where k='invoice'),(select id from fx where k='client'))$$,'42501',null,'Inactive staff cannot read payment summary');
set local role anon;
select throws_ok($$select * from public.payment_reconciliation_observations$$,'42501',null,'Anonymous observation read denied');
select throws_ok($$select public.record_payment_reconciliation('checkout',gen_random_uuid(),'provider_context_mismatch')$$,'42501',null,'Anonymous observation creation denied');
reset role;
select throws_ok($$update public.payment_reconciliation_observations set reason='provider_object_unavailable' where id=(select id from fx where k='observation')$$,'23514','Financial history is append-only','Privileged observation alteration rejected');
select throws_ok($$delete from public.payment_reconciliation_observations where id=(select id from fx where k='observation')$$,'23514','Financial history is append-only','Privileged observation deletion rejected');

-- Failed refund capacity was reused before observation obscured its display state.
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"73300000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx values('reg-observation-invoice',gen_random_uuid()),('reg-observation-checkout',gen_random_uuid()),('reg-observation-first',gen_random_uuid()),('reg-observation-replacement',gen_random_uuid());
select public.create_billing_invoice((select id from fx where k='reg-observation-invoice'),(select id from fx where k='client'));
select public.add_invoice_service(gen_random_uuid(),(select id from fx where k='reg-observation-invoice'),null,(select id from fx where k='product'),1);
select public.issue_billing_invoice((select id from fx where k='reg-observation-invoice'),(select version from public.billing_invoices where id=(select id from fx where k='reg-observation-invoice')));
insert into snapshots select 'reg-observation',public.read_invoice_payment_state((select id from fx where k='reg-observation-invoice'),(select id from fx where k='client'));
select public.prepare_invoice_checkout((select id from fx where k='reg-observation-checkout'),(select id from fx where k='reg-observation-invoice'),(select id from fx where k='client'),(select v->>'source_hash' from snapshots where k='reg-observation'),10000,'acct_test',false,'https://thelivingroom.vet/payment/return','https://thelivingroom.vet/payment/cancel');
set local role service_role;
select public.apply_checkout_evidence('evt_observation_paid',(select id from fx where k='reg-observation-checkout'),'acct_test',false,'payment_succeeded','cs_test_observation','pi_observation',10000,'usd',(select v->>'source_hash' from snapshots where k='reg-observation'));
set local role authenticated;
insert into fx select 'reg-observation-payment',id from public.invoice_payments where invoice_id=(select id from fx where k='reg-observation-invoice');
select public.credit_billing_invoice(gen_random_uuid(),(select id from fx where k='reg-observation-invoice'),3000,'Synthetic replacement adjustment');
select public.prepare_invoice_refund((select id from fx where k='reg-observation-first'),(select id from fx where k='reg-observation-invoice'),(select id from fx where k='reg-observation-payment'),3000,'First attempt');
set local role service_role;
select public.apply_refund_evidence('evt_observation_failed',(select id from fx where k='reg-observation-first'),'acct_test',false,'re_observation','pi_observation',3000,'usd','failed');
select is(public.provider_refund_context((select id from fx where k='reg-observation-first'))->>'state','failed','observation: first refund terminal failure recorded');
set local role authenticated;
select lives_ok($$select public.prepare_invoice_refund((select id from fx where k='reg-observation-replacement'),(select id from fx where k='reg-observation-invoice'),(select id from fx where k='reg-observation-payment'),3000,'Replacement attempt')$$,'observation: replacement reserves released capacity');
set local role service_role;
select public.record_payment_reconciliation('refund',(select id from fx where k='reg-observation-first'),'provider_context_mismatch');
select is(public.provider_refund_context((select id from fx where k='reg-observation-first'))->>'state','reconciliation','observation: presentation hides failed state');
insert into snapshots select 'reg-observation-late',to_jsonb(public.apply_refund_evidence('evt_observation_late',(select id from fx where k='reg-observation-first'),'acct_test',false,'re_observation','pi_observation',3000,'usd','succeeded'));
select is((select v->>'disposition' from snapshots where k='reg-observation-late'),'quarantined','observation: late success never bypasses terminal failure');
select is((select v->>'reason' from snapshots where k='reg-observation-late'),'success_after_terminal_failure','observation: late success requires explicit reconciliation');
set local role authenticated;
select is((select count(*) from public.invoice_refunds where invoice_id=(select id from fx where k='reg-observation-invoice')),0::bigint,'observation: late success does not post cash');
select is((select amount_cents from public.invoice_refund_requests where id=(select id from fx where k='reg-observation-replacement')),3000::bigint,'observation: replacement reservation retained exactly');
select is(public.read_invoice_payment_state((select id from fx where k='reg-observation-invoice'),(select id from fx where k='client'))#>>'{balance,net_cash_cents}','10000','observation: settled cash unchanged');
select is(public.read_invoice_payment_state((select id from fx where k='reg-observation-invoice'),(select id from fx where k='client'))#>>'{balance,refundable_cents}','0','observation: no capacity freed or double consumed');
reset role;

-- Failed refund capacity was reused before quarantined obscured its display state.
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"73300000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx values('reg-quarantined-invoice',gen_random_uuid()),('reg-quarantined-checkout',gen_random_uuid()),('reg-quarantined-first',gen_random_uuid()),('reg-quarantined-replacement',gen_random_uuid());
select public.create_billing_invoice((select id from fx where k='reg-quarantined-invoice'),(select id from fx where k='client'));
select public.add_invoice_service(gen_random_uuid(),(select id from fx where k='reg-quarantined-invoice'),null,(select id from fx where k='product'),1);
select public.issue_billing_invoice((select id from fx where k='reg-quarantined-invoice'),(select version from public.billing_invoices where id=(select id from fx where k='reg-quarantined-invoice')));
insert into snapshots select 'reg-quarantined',public.read_invoice_payment_state((select id from fx where k='reg-quarantined-invoice'),(select id from fx where k='client'));
select public.prepare_invoice_checkout((select id from fx where k='reg-quarantined-checkout'),(select id from fx where k='reg-quarantined-invoice'),(select id from fx where k='client'),(select v->>'source_hash' from snapshots where k='reg-quarantined'),10000,'acct_test',false,'https://thelivingroom.vet/payment/return','https://thelivingroom.vet/payment/cancel');
set local role service_role;
select public.apply_checkout_evidence('evt_quarantined_paid',(select id from fx where k='reg-quarantined-checkout'),'acct_test',false,'payment_succeeded','cs_test_quarantined','pi_quarantined',10000,'usd',(select v->>'source_hash' from snapshots where k='reg-quarantined'));
set local role authenticated;
insert into fx select 'reg-quarantined-payment',id from public.invoice_payments where invoice_id=(select id from fx where k='reg-quarantined-invoice');
select public.credit_billing_invoice(gen_random_uuid(),(select id from fx where k='reg-quarantined-invoice'),3000,'Synthetic replacement adjustment');
select public.prepare_invoice_refund((select id from fx where k='reg-quarantined-first'),(select id from fx where k='reg-quarantined-invoice'),(select id from fx where k='reg-quarantined-payment'),3000,'First attempt');
set local role service_role;
select public.apply_refund_evidence('evt_quarantined_failed',(select id from fx where k='reg-quarantined-first'),'acct_test',false,'re_quarantined','pi_quarantined',3000,'usd','failed');
select is(public.provider_refund_context((select id from fx where k='reg-quarantined-first'))->>'state','failed','quarantined: first refund terminal failure recorded');
set local role authenticated;
select lives_ok($$select public.prepare_invoice_refund((select id from fx where k='reg-quarantined-replacement'),(select id from fx where k='reg-quarantined-invoice'),(select id from fx where k='reg-quarantined-payment'),3000,'Replacement attempt')$$,'quarantined: replacement reserves released capacity');
set local role service_role;
select public.apply_refund_evidence('evt_quarantined_mismatch',(select id from fx where k='reg-quarantined-first'),'acct_test',false,'re_quarantined','pi_quarantined',2999,'usd','pending');
select is(public.provider_refund_context((select id from fx where k='reg-quarantined-first'))->>'state','reconciliation','quarantined: presentation hides failed state');
insert into snapshots select 'reg-quarantined-late',to_jsonb(public.apply_refund_evidence('evt_quarantined_late',(select id from fx where k='reg-quarantined-first'),'acct_test',false,'re_quarantined','pi_quarantined',3000,'usd','succeeded'));
select is((select v->>'disposition' from snapshots where k='reg-quarantined-late'),'quarantined','quarantined: late success never bypasses terminal failure');
select is((select v->>'reason' from snapshots where k='reg-quarantined-late'),'success_after_terminal_failure','quarantined: late success requires explicit reconciliation');
set local role authenticated;
select is((select count(*) from public.invoice_refunds where invoice_id=(select id from fx where k='reg-quarantined-invoice')),0::bigint,'quarantined: late success does not post cash');
select is((select amount_cents from public.invoice_refund_requests where id=(select id from fx where k='reg-quarantined-replacement')),3000::bigint,'quarantined: replacement reservation retained exactly');
select is(public.read_invoice_payment_state((select id from fx where k='reg-quarantined-invoice'),(select id from fx where k='client'))#>>'{balance,net_cash_cents}','10000','quarantined: settled cash unchanged');
select is(public.read_invoice_payment_state((select id from fx where k='reg-quarantined-invoice'),(select id from fx where k='client'))#>>'{balance,refundable_cents}','0','quarantined: no capacity freed or double consumed');
reset role;

-- A previously settled replacement acquires an observation after success.
set local role service_role;
select public.apply_refund_evidence('evt_replacement_success',(select id from fx where k='reg-observation-replacement'),'acct_test',false,'re_replacement','pi_observation',3000,'usd','succeeded');
select is(public.provider_refund_context((select id from fx where k='reg-observation-replacement'))->>'state','succeeded','Replacement succeeds before later observation');
select public.record_payment_reconciliation('refund',(select id from fx where k='reg-observation-replacement'),'provider_reconciliation_required');
select is(public.provider_refund_context((select id from fx where k='reg-observation-replacement'))->>'state','reconciliation','Later observation retains review for succeeded refund');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"73300000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select is(public.read_invoice_payment_state((select id from fx where k='reg-observation-invoice'),(select id from fx where k='client'))#>>'{balance,pending_refund_cents}','3000','Only original unresolved request reserves capacity; settled replacement adds zero');
select is(public.read_invoice_payment_state((select id from fx where k='reg-observation-invoice'),(select id from fx where k='client'))#>>'{balance,net_cash_cents}','7000','Post-success observation leaves settled net cash unchanged');
reset role;
select * from finish();
rollback;
