begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,raw_user_meta_data) values('78000000-0000-4000-8000-000000000001','release-history@example.test','{}');
update public.profiles set is_active = true where id in ('78000000-0000-4000-8000-000000000001');
insert into public.user_roles (user_id, role) values ('78000000-0000-4000-8000-000000000001','STAFF');

create temp table fx(k text primary key,id uuid);grant all on fx to authenticated;
create temp table data(k text primary key,v jsonb);grant all on data to authenticated;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"78000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'client',id from public.save_client(auth.uid(),null,null,'History','Family','+13035550200','history@example.test','EMAIL',null,null);
insert into fx select 'pet',id from public.save_patient(null,(select id from fx where k='client'),null,'History dog','Dog',null,null,'unknown',null,'unknown','unknown',null,null,null);
insert into fx select 'other',id from public.save_patient(null,(select id from fx where k='client'),null,'Other dog','Dog',null,null,'unknown',null,'unknown','unknown',null,null,null);
insert into fx select 'problem',id from public.save_patient_problem(null,(select id from fx where k='pet'),null,'Vaccine reaction','Initial clinical notes',(now() at time zone 'America/Denver')::date,'active','high');
select public.save_patient_problem((select id from fx where k='problem'),(select id from fx where k='pet'),1,'Vaccine reaction','Revised clinical notes <script>unsafe</script>',(now() at time zone 'America/Denver')::date,'resolved','high');
insert into fx select 'weight',id from public.record_patient_weight((select id from fx where k='pet'),12.3,'kg',(now() at time zone 'America/Denver')::date);
select public.record_patient_treatment('79000000-0000-4000-8000-000000000001',jsonb_build_object('historical',true,'kind','medication','pet_id',(select id from fx where k='pet'),'quantity',1,'product_name','Prior medication','manufacturer','External manufacturer','lot_number','UNKNOWN','dose','unknown','route','unknown','veterinarian','External veterinarian','administered_at',now()-interval '1 year','source','External medical record provenance'));
select public.correct_patient_treatment('79000000-0000-4000-8000-000000000002','79000000-0000-4000-8000-000000000001','Imported dose uncertain; retain original',null);
reset role;
update public.pets set allergies='Penicillin reaction',weight_lbs=28 where id=(select id from fx where k='pet');
insert into public.record_release_policy(id,enabled,accepted_by,accepted_at,acceptance_reference,accepted_schema_version) values(true,true,'Test reviewer',now(),'SYNTHETIC ONLY',2);
set local role authenticated;
insert into data select 'selection',public.select_all_record_release_sources((select id from fx where k='pet'))->'selection';
create function pg_temp.preview_history(s jsonb) returns jsonb language sql as $$select public.preview_record_release((select id from fx where k='pet'),(select id from fx where k='client'),'EMAIL','history@example.test',s)$$;
create function pg_temp.confirm_history(i uuid,p jsonb) returns public.record_releases language sql as $$select public.confirm_record_release(i,(select id from fx where k='pet'),(select id from fx where k='client'),'EMAIL','history@example.test',(select v from data where k='selection'),p->'snapshot',p->>'source_hash',true)$$;
insert into data select 'preview',pg_temp.preview_history((select v from data where k='selection'));
select is((select v#>>'{snapshot,schema_version}' from data where k='preview'),'3','Clinical history produces v3 snapshot');
select is((select v#>>'{snapshot,problems,0,current,importance}' from data where k='preview'),'high','Critical diagnosis flag retained');
select is((select v#>>'{snapshot,problems,0,current,status}' from data where k='preview'),'resolved','Resolved historical diagnosis retained');
select ok((select v::text like '%Initial clinical notes%' and v::text like '%Revised clinical notes%' from data where k='preview'),'Authored clinical revisions preserved');
select is((select v#>>'{snapshot,patient_summaries,0,allergies}' from data where k='preview'),'Penicillin reaction','Allergy summary preserved');
select is((select v#>>'{snapshot,weights,0,measured_at}' from data where k='preview'),(now() at time zone 'America/Denver')::date::text,'Dated weight retained');
select is((select v#>>'{snapshot,treatments,0,source}' from data where k='preview'),'External medical record provenance','Treatment provenance retained');
select is((select v#>>'{snapshot,treatments,0,corrections,0,reason}' from data where k='preview'),'Imported dose uncertain; retain original','Treatment corrections retained');
select ok((select not (v#>'{snapshot,treatments,0}') ? 'request' and not (v#>'{snapshot,treatments,0}') ? 'invoice_id' from data where k='preview'),'Transport retry and billing internals excluded');
select throws_ok($$select pg_temp.confirm_history('79000000-0000-4000-8000-000000000003',(select v from data where k='preview'))$$,'42501',null,'Earlier clinical form acceptance cannot activate new form');
select throws_ok($$select pg_temp.preview_history(jsonb_build_object('patient_summary_ids',jsonb_build_array((select id from fx where k='other'))))$$,'23514',null,'Cross-patient summary rejected');
select throws_ok($$select public.preview_record_release((select id from fx where k='other'),(select id from fx where k='client'),'EMAIL','history@example.test',(select v from data where k='selection'))$$,'23514',null,'Cross-patient diagnosis/treatment selection rejected');
select throws_ok($$select public.preview_record_release_v2((select id from fx where k='pet'),(select id from fx where k='client'),'EMAIL','history@example.test','{}')$$,'42501',null,'Version compatibility helper remains private');
reset role;
update public.record_release_policy set accepted_schema_version=3;
set local role authenticated;
select lives_ok($$select pg_temp.confirm_history('79000000-0000-4000-8000-000000000003',(select v from data where k='preview'))$$,'Confirm exact reviewed clinical history');
select is((select count(*) from public.record_release_sources where release_id='79000000-0000-4000-8000-000000000003'),4::bigint,'All four history families linked');
select is(public.read_record_release('79000000-0000-4000-8000-000000000003')->>'eligible','true','Current release eligible');
select public.save_patient_problem((select id from fx where k='problem'),(select id from fx where k='pet'),2,'Vaccine reaction','Later critical clarification',(now() at time zone 'America/Denver')::date,'active','high');
select is(public.read_record_release('79000000-0000-4000-8000-000000000003')->>'eligible','false','Diagnosis revision invalidates prior package');
select is(public.read_record_release('79000000-0000-4000-8000-000000000003')#>>'{release,snapshot,problems,0,current,status}','resolved','Previously reviewed diagnosis stays immutable');
select lives_ok($$select pg_temp.confirm_history('79000000-0000-4000-8000-000000000003',(select v from data where k='preview'))$$,'Original retry still resolves after invalidation');
select throws_ok($$select pg_temp.confirm_history('79000000-0000-4000-8000-000000000004',(select v from data where k='preview'))$$,'40001',null,'Stale clinical history cannot create another release');
select public.record_patient_treatment('79000000-0000-4000-8000-000000000005',jsonb_build_object('historical',true,'pet_id',(select id from fx where k='pet'),'quantity',1,'product_name','Prior vaccine','manufacturer','External','lot_number','UNKNOWN','dose','unknown','route','unknown','veterinarian','External veterinarian','administered_at',now()-interval '1 year','source','Original vaccine history'));
update data set v=public.select_all_record_release_sources((select id from fx where k='pet'))->'selection' where k='selection';
update data set v=pg_temp.preview_history((select v from data where k='selection')) where k='preview';
select lives_ok($$select pg_temp.confirm_history('79000000-0000-4000-8000-000000000004',(select v from data where k='preview'))$$,'New history can be reviewed and confirmed');
select public.correct_patient_treatment('79000000-0000-4000-8000-000000000006','79000000-0000-4000-8000-000000000005','Later vaccine correction',null);
select is(public.read_record_release('79000000-0000-4000-8000-000000000004')->>'eligible','false','Later vaccine correction invalidates package');
select ok(exists(select 1 from public.record_release_events where release_id='79000000-0000-4000-8000-000000000004' and reason like 'Reviewed treatment%'),'Correction appends explicit source event');
update data set v=pg_temp.preview_history((select v from data where k='selection')) where k='preview';
select lives_ok($$select pg_temp.confirm_history('79000000-0000-4000-8000-000000000007',(select v from data where k='preview'))$$,'Corrected treatment history can be re-reviewed');
reset role;
update public.pets set allergies='Updated allergy history' where id=(select id from fx where k='pet');
set local role authenticated;
select is(public.read_record_release('79000000-0000-4000-8000-000000000007')->>'eligible','false','Allergy change invalidates summary package');
select is(public.read_record_release('79000000-0000-4000-8000-000000000007')#>>'{release,snapshot,patient_summaries,0,allergies}','Penicillin reaction','Original allergy snapshot remains unchanged');
select public.record_patient_weight((select id from fx where k='pet'),10,'kg',(now() at time zone 'America/Denver')::date) from generate_series(1,100);
select is(jsonb_array_length(public.list_record_release_sources((select id from fx where k='pet'),100)->'weight_ids'),1,'Source pagination exposes the 101st dated weight');
select throws_ok($$select public.select_all_record_release_sources((select id from fx where k='pet'))$$,'23514',null,'All-page selection fails explicitly rather than truncating oversized family');
select throws_ok($$update public.record_releases set snapshot='{}' where id='79000000-0000-4000-8000-000000000003'$$,'42501',null,'Staff cannot rewrite release snapshot');
reset role;
set local role anon;
select throws_ok($$select public.select_all_record_release_sources('79000000-0000-4000-8000-000000000001')$$,'42501',null,'Anonymous all-record discovery denied');
reset role;
select * from finish();
rollback;
