begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select no_plan();

-- Test-only rollback probe exercises the real ADMIN preview on a pre-provider failure.
create function pg_temp.retry_source_probe(p_id uuid,p_change text default null) returns jsonb language plpgsql security definer as $$
declare result jsonb;actor uuid;begin
 begin
  select created_by into actor from communication_outbox where id=p_id;
  perform set_config('request.jwt.claims',jsonb_build_object('role','authenticated','sub',actor)::text,true);
  update communication_outbox set state='failed',lease_token=null,lease_expires_at=null where id=p_id;
  if p_change is not null then execute p_change;end if;
  result:=preview_outbox_retry(p_id);
  raise exception 'rollback probe';
 exception when raise_exception then return result;end;
end $$;

insert into auth.users(id,email,raw_user_meta_data) values('ae000000-0000-4000-8000-000000000001','reminder-approver@example.test','{"first_name":"Reminder","last_name":"Approver"}'),('ae000000-0000-4000-8000-000000000002','reminder-staff@example.test','{"first_name":"Reminder","last_name":"Staff"}');
update public.profiles set is_active = true where id in ('ae000000-0000-4000-8000-000000000001','ae000000-0000-4000-8000-000000000002');
insert into public.user_roles (user_id, role) values ('ae000000-0000-4000-8000-000000000001','STAFF'),('ae000000-0000-4000-8000-000000000002','STAFF');

insert into public.user_roles(user_id,role) values('ae000000-0000-4000-8000-000000000001','ADMIN') on conflict do nothing;
create temp table reminder_fixture(kind text primary key,id uuid);grant all on reminder_fixture to authenticated,service_role;
select ok(not has_function_privilege('authenticated','public.queue_due_reminders(integer)','EXECUTE'),'Staff cannot call service queue');
select ok(not has_function_privilege('service_role','public.start_communication_attempt_without_reminder_guard(uuid,uuid,jsonb)','EXECUTE'),'Service cannot bypass final reminder guard');
select ok(not has_function_privilege('authenticated','public.block_reminder_job(text,uuid,text)','EXECUTE'),'Internal blocker is not staff-callable');
select ok(not has_table_privilege('service_role','public.reminder_outbox_links','UPDATE'),'Service cannot rewrite frozen origin');
set local role authenticated;select set_config('request.jwt.claims','{"sub":"ae000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into reminder_fixture select 'client',id from public.save_client(auth.uid(),null,null,'Synthetic','Reminder','+13035550111','synthetic-reminder@example.test','EMAIL',null,null);
insert into reminder_fixture select 'pet',id from public.save_patient(null,(select id from reminder_fixture where kind='client'),null,'Juniper','Dog',null,null,'unknown',null,'unknown','unknown',null,null,null);
select lives_ok($$select public.save_care_message_template('ae100000-0000-4000-8000-000000000001',null,'Reviewed reminder','email',0,'{{patient_name}}: {{care_name}} due {{due_date}}',true,'Clinical wording reviewed')$$,'Approved care wording exists before policy');
select lives_ok($$select public.save_patient_lab_order('ae200000-0000-4000-8000-000000000001',(select id from reminder_fixture where kind='pet'),null,jsonb_build_object('test_name','Synthetic lab','status','planned','due_date',(now() at time zone 'America/Denver')::date),'')$$,'Eligible native source exists');
set local role service_role;select set_config('request.jwt.claims','{"role":"service_role"}',true);
select is((public.queue_due_reminders(25)->>'queued')::integer,0,'No seeded enabled policy means no automatic queue');
set local role authenticated;select set_config('request.jwt.claims','{"sub":"ae000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select lives_ok($$select public.save_reminder_automation_policy('ae300000-0000-4000-8000-000000000001',null,'lab','EMAIL','ae100000-0000-4000-8000-000000000001',1,'Reviewed care reminder',false,'Reviewed but disabled')$$,'Policy explicitly begins disabled');
set local role service_role;select set_config('request.jwt.claims','{"role":"service_role"}',true);
select is((public.queue_due_reminders(25)->>'queued')::integer,0,'Disabled policy cannot create outbox entries');
set local role authenticated;select set_config('request.jwt.claims','{"sub":"ae000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select lives_ok($$select public.save_reminder_automation_policy('ae300000-0000-4000-8000-000000000001',1,'lab','EMAIL','ae100000-0000-4000-8000-000000000001',1,'Reviewed care reminder',true,'Explicit synthetic enable for test')$$,'Administrator can explicitly enable reviewed policy');
set local role service_role;select set_config('request.jwt.claims','{"role":"service_role"}',true);
select is((public.queue_due_reminders(25)->>'queued')::integer,1,'Scheduler hands one source into durable outbox');
insert into reminder_fixture select 'outbox',outbox_id from public.reminder_outbox_links where job_kind='care';
insert into reminder_fixture select 'job',job_id from public.reminder_outbox_links where job_kind='care';
select is((public.queue_due_reminders(25)->>'queued')::integer,0,'Repeat scheduler tick cannot duplicate outbox intent');
select is((select created_by from public.communication_outbox where id=(select id from reminder_fixture where kind='outbox')),'ae000000-0000-4000-8000-000000000001'::uuid,'Original source approving actor is preserved without auth injection');
select is((select state from public.communication_outbox where id=(select id from reminder_fixture where kind='outbox')),'pending','Scheduler never claims accepted or delivered');
select is((select outbox_id from public.queue_reminder_outbox('care',(select id from reminder_fixture where kind='job'),'ae300000-0000-4000-8000-000000000001')),(select id from reminder_fixture where kind='outbox'),'Lost handoff response returns same outbox identity');
select is(pg_temp.retry_source_probe((select id from reminder_fixture where kind='outbox'))->>'eligible','true','Current reminder can be reviewed for pre-provider retry');
select lives_ok($$select public.claim_communication()$$,'Existing dispatcher can claim prepared reminder');
set local role authenticated;select set_config('request.jwt.claims','{"sub":"ae000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select lives_ok($$select public.save_patient_lab_order('ae200000-0000-4000-8000-000000000001',(select id from reminder_fixture where kind='pet'),1,jsonb_build_object('test_name','Synthetic lab','status','cancelled','due_date',(now() at time zone 'America/Denver')::date),'')$$,'Source cancellation after enqueue is allowed');
set local role service_role;select set_config('request.jwt.claims','{"role":"service_role"}',true);
select is((select state from public.start_communication_attempt((select id from reminder_fixture where kind='outbox'),(select lease_token from public.communication_outbox where id=(select id from reminder_fixture where kind='outbox')),'{"from":"verified@example.test","reply_to":"reply@example.test"}')),'failed','Final attempt guard blocks canceled lab before provider call');
select is((select count(*) from public.communication_attempts where outbox_id=(select id from reminder_fixture where kind='outbox')),0::bigint,'Blocked preflight creates no provider attempt');
set local role authenticated;select set_config('request.jwt.claims','{"sub":"ae000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select is(public.preview_outbox_retry((select id from reminder_fixture where kind='outbox'))->>'reason','source_ineligible','Reviewed retry refuses invalidated reminder');
select throws_ok($$select public.requeue_outbox_retry(gen_random_uuid(),(select id from reminder_fixture where kind='outbox'),public.preview_outbox_retry((select id from reminder_fixture where kind='outbox'))->>'expected_work_hash','source_reverified',true)$$,'42501',null,'Repair attestation cannot revive invalidated source');
-- Owner-only fixture restores pending to independently retain the existing final-worker regression.
reset role;update public.communication_outbox set state='pending' where id=(select id from reminder_fixture where kind='outbox');
set local role service_role;select set_config('request.jwt.claims','{"role":"service_role"}',true);
select lives_ok($$select public.claim_communication()$$,'Retry may be claimed');
select is((select state from public.start_communication_attempt((select id from reminder_fixture where kind='outbox'),(select lease_token from public.communication_outbox where id=(select id from reminder_fixture where kind='outbox')),'{"from":"verified@example.test","reply_to":"reply@example.test"}')),'failed','Retry cannot revive invalidated reminder');
set local role authenticated;select set_config('request.jwt.claims','{"sub":"ae000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select lives_ok($$select public.save_patient_lab_order('ae200000-0000-4000-8000-000000000002',(select id from reminder_fixture where kind='pet'),null,jsonb_build_object('test_name','Second synthetic lab','status','planned','due_date',(now() at time zone 'America/Denver')::date),'')$$,'Second reviewed source can enqueue independently');
select lives_ok($$select public.suppress_communication(auth.uid(),'EMAIL','synthetic-reminder@example.test','Synthetic suppression test')$$,'Explicit suppression recorded');
set local role service_role;select set_config('request.jwt.claims','{"role":"service_role"}',true);
select is((public.queue_due_reminders(25)->>'blocked')::integer,1,'Suppressed source becomes terminal blocked without outbox');
select is((select count(*) from public.communication_outbox where client_id=(select id from reminder_fixture where kind='client')),1::bigint,'Suppressed reminder created no additional outbound message');
select is((public.queue_due_reminders(25)->>'queued')::integer,0,'Suppressed job is not silently revived');
set local role authenticated;select set_config('request.jwt.claims','{"sub":"ae000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select lives_ok($$select public.save_care_message_template('ae100000-0000-4000-8000-000000000002',null,'Reviewed appointment SMS','sms',0,'{{patient_name}}: {{care_name}} on {{due_date}}',true,'Staff reviewed appointment wording')$$,'Appointment wording explicitly reviewed, never seeded');
select lives_ok($$select public.save_reminder_automation_policy('ae300000-0000-4000-8000-000000000002',null,'appointment','SMS','ae100000-0000-4000-8000-000000000002',1,'',true,'Approved synthetic appointment automation')$$,'Appointment channel policy reviewed');
select lives_ok($$select public.record_sms_consent(auth.uid(),(select id from reminder_fixture where kind='client'),'+13035550111',true,'WRITTEN','Synthetic written consent',null)$$,'Explicit SMS consent recorded');
insert into reminder_fixture select 'appointment',id from public.save_appointment(auth.uid(),null,null,(select id from reminder_fixture where kind='client'),(select id from reminder_fixture where kind='pet'),now()+interval '4 hours',30,'Synthetic exam','SCHEDULED',auth.uid(),'clinic','2619 Spruce Street, Boulder, CO',0,0,null,'',array[2]);
reset role;update public.appointment_reminders set remind_at=now()-interval '1 minute' where appointment_id=(select id from reminder_fixture where kind='appointment');
set local role service_role;select set_config('request.jwt.claims','{"role":"service_role"}',true);
select is((public.queue_due_reminders(25)->>'queued')::integer,1,'Due appointment job hands off exactly once');
insert into reminder_fixture select 'appointment-outbox',h.outbox_id from public.reminder_outbox_links h join public.appointment_reminders a on a.id=h.job_id where h.job_kind='appointment' and a.appointment_id=(select id from reminder_fixture where kind='appointment');
select ok((select body from public.communication_outbox where id=(select id from reminder_fixture where kind='appointment-outbox')) like '%America/Denver%2619 Spruce Street%','Appointment payload freezes actual time and location in reviewed wording');
select lives_ok($$select public.claim_communication()$$,'Appointment outbox claim succeeds');
set local role authenticated;select set_config('request.jwt.claims','{"sub":"ae000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select lives_ok($$select public.record_sms_consent(auth.uid(),(select id from reminder_fixture where kind='client'),'+13035550111',false,'VERBAL','Synthetic withdrawal',(select max(updated_at) from public.sms_consent where client_id=(select id from reminder_fixture where kind='client')))$$,'Consent can be withdrawn after enqueue');
set local role service_role;select set_config('request.jwt.claims','{"role":"service_role"}',true);
select is((select state from public.start_communication_attempt((select id from reminder_fixture where kind='appointment-outbox'),(select lease_token from public.communication_outbox where id=(select id from reminder_fixture where kind='appointment-outbox')),'{"from":"+13035550199","account_sid":"ACsynthetic"}')),'failed','Final preflight blocks newly suppressed appointment');
set local role authenticated;select set_config('request.jwt.claims','{"sub":"ae000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select lives_ok($$select public.record_sms_consent(auth.uid(),(select id from reminder_fixture where kind='client'),'+13035550111',true,'WRITTEN','New synthetic consent after review',(select max(updated_at) from public.sms_consent where client_id=(select id from reminder_fixture where kind='client')))$$,'New consent can be separately reviewed');
select is(public.preview_outbox_retry((select id from reminder_fixture where kind='appointment-outbox'))->>'reason','source_ineligible','Reviewed retry refuses invalidated reminder');
select throws_ok($$select public.requeue_outbox_retry(gen_random_uuid(),(select id from reminder_fixture where kind='appointment-outbox'),public.preview_outbox_retry((select id from reminder_fixture where kind='appointment-outbox'))->>'expected_work_hash','source_reverified',true)$$,'42501',null,'Repair attestation cannot revive invalidated source');
-- Owner-only fixture restores pending to independently retain the existing final-worker regression.
reset role;update public.communication_outbox set state='pending' where id=(select id from reminder_fixture where kind='appointment-outbox');
set local role service_role;select set_config('request.jwt.claims','{"role":"service_role"}',true);
select lives_ok($$select public.claim_communication()$$,'Old appointment retry may claim');
select is((select state from public.start_communication_attempt((select id from reminder_fixture where kind='appointment-outbox'),(select lease_token from public.communication_outbox where id=(select id from reminder_fixture where kind='appointment-outbox')),'{"from":"+13035550199","account_sid":"ACsynthetic"}')),'failed','Previously suppressed job remains invalidated after consent returns');
set local role authenticated;select set_config('request.jwt.claims','{"sub":"ae000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into reminder_fixture select 'cancel-appointment',id from public.save_appointment(auth.uid(),null,null,(select id from reminder_fixture where kind='client'),(select id from reminder_fixture where kind='pet'),now()+interval '8 hours',30,'Cancellation exam','SCHEDULED',auth.uid(),'clinic','2619 Spruce Street, Boulder, CO',0,0,null,'',array[2]);
reset role;update public.appointment_reminders set remind_at=now()-interval '1 minute' where appointment_id=(select id from reminder_fixture where kind='cancel-appointment');
set local role service_role;select set_config('request.jwt.claims','{"role":"service_role"}',true);
select is((public.queue_due_reminders(25)->>'queued')::integer,1,'New appointment intent queues independently');
insert into reminder_fixture select 'cancel-outbox',h.outbox_id from public.reminder_outbox_links h join public.appointment_reminders a on a.id=h.job_id where h.job_kind='appointment' and a.appointment_id=(select id from reminder_fixture where kind='cancel-appointment');
select lives_ok($$select public.claim_communication()$$,'Cancellation candidate claimed');
set local role authenticated;select set_config('request.jwt.claims','{"sub":"ae000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select lives_ok($$select public.save_appointment(auth.uid(),(select id from reminder_fixture where kind='cancel-appointment'),1,(select id from reminder_fixture where kind='client'),(select id from reminder_fixture where kind='pet'),now()+interval '8 hours',30,'Cancellation exam','CANCELLED',auth.uid(),'clinic','2619 Spruce Street, Boulder, CO',0,0,null,'',array[2])$$,'Appointment canceled after enqueue');
set local role service_role;select set_config('request.jwt.claims','{"role":"service_role"}',true);
select is((select state from public.start_communication_attempt((select id from reminder_fixture where kind='cancel-outbox'),(select lease_token from public.communication_outbox where id=(select id from reminder_fixture where kind='cancel-outbox')),'{"from":"+13035550199","account_sid":"ACsynthetic"}')),'failed','Final preflight blocks canceled appointment');
set local role authenticated;select set_config('request.jwt.claims','{"sub":"ae000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into reminder_fixture select 'valid-appointment',id from public.save_appointment(auth.uid(),null,null,(select id from reminder_fixture where kind='client'),(select id from reminder_fixture where kind='pet'),now()+interval '12 hours',30,'Reviewed valid exam','SCHEDULED',auth.uid(),'clinic','2619 Spruce Street, Boulder, CO',0,0,null,'',array[2]);
reset role;update public.appointment_reminders set remind_at=now()-interval '1 minute' where appointment_id=(select id from reminder_fixture where kind='valid-appointment');
set local role service_role;select set_config('request.jwt.claims','{"role":"service_role"}',true);
select is((public.queue_due_reminders(25)->>'queued')::integer,1,'Eligible appointment queues');
insert into reminder_fixture select 'valid-outbox',h.outbox_id from public.reminder_outbox_links h join public.appointment_reminders a on a.id=h.job_id where h.job_kind='appointment' and a.appointment_id=(select id from reminder_fixture where kind='valid-appointment');
select lives_ok($$select public.claim_communication()$$,'Eligible appointment claimed');
select is((select state from public.start_communication_attempt((select id from reminder_fixture where kind='valid-outbox'),(select lease_token from public.communication_outbox where id=(select id from reminder_fixture where kind='valid-outbox')),'{"from":"+13035550199","account_sid":"ACsynthetic"}')),'claimed','Eligible final preflight delegates to original attempt implementation');
select is((select attempt_count from public.communication_outbox where id=(select id from reminder_fixture where kind='valid-outbox')),1,'Original attempt audit remains in force');
select lives_ok($$select public.finish_communication_attempt((select id from reminder_fixture where kind='valid-outbox'),(select lease_token from public.communication_outbox where id=(select id from reminder_fixture where kind='valid-outbox')),'accepted','SMaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',null)$$,'Existing outbox records provider acceptance without claiming delivery');
select is((select state from public.communication_outbox where id=(select id from reminder_fixture where kind='valid-outbox')),'accepted','Accepted remains distinct from delivered');
select * from finish();rollback;
