begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,raw_user_meta_data) values ('96000000-0000-4000-8000-000000000001','consent-display@example.test','{"first_name":"Synthetic","last_name":"Consent"}');
create temp table fixture_ids(kind text primary key,id uuid);
grant all on fixture_ids to authenticated;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"96000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fixture_ids select 'client',id from public.save_client(auth.uid(),null,null,'Consent','Household','+13035550166',null,'SMS',null,null);
select is(public.current_sms_consent((select id from fixture_ids where kind='client'))->>'can_message','false','Missing consent is not messaging permission');
select is(public.current_sms_consent((select id from fixture_ids where kind='client'))->>'phone_number','+13035550166','Display uses normalized current household number');
select lives_ok($$select public.record_sms_consent(auth.uid(),(select id from fixture_ids where kind='client'),'+13035550166',true,'WRITTEN','Synthetic signed form',null)$$,'Staff records supported consent evidence');
select is(public.current_sms_consent((select id from fixture_ids where kind='client'))->>'can_message','true','Recorded affirmative consent is eligible');
select throws_ok($$select public.record_sms_consent(auth.uid(),(select id from fixture_ids where kind='client'),'+13035550166',false,'VERBAL','Synthetic withdrawal',null)$$,'40001',null,'Stale consent snapshot cannot overwrite current record');
reset role;
insert into public.communication_suppressions(channel,recipient,reason) values ('SMS','+13035550166','provider_complaint');
set local role authenticated;
select is(public.current_sms_consent((select id from fixture_ids where kind='client'))->>'opted_in','true','Consent history preserved while number suppressed');
select is(public.current_sms_consent((select id from fixture_ids where kind='client'))->>'can_message','false','Effective display includes shared suppression');
select lives_ok($$select public.record_sms_consent(auth.uid(),(select id from fixture_ids where kind='client'),'+13035550166',true,'VERBAL','Synthetic new preference',(public.current_sms_consent((select id from fixture_ids where kind='client'))->>'updated_at')::timestamptz)$$,'Reviewed current consent can be updated');
select is(public.current_sms_consent((select id from fixture_ids where kind='client'))->>'can_message','false','Manual opt-in cannot clear provider exclusion');
reset role;
set local role anon;
select throws_ok($$select public.current_sms_consent('96000000-0000-4000-8000-000000000002')$$,'42501',null,'Anonymous cannot read consent');
reset role;
select * from finish();
rollback;
