begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,raw_user_meta_data) values
 ('74000000-0000-4000-8000-000000000001','stripe-inbox-staff@example.test','{}'),
 ('74000000-0000-4000-8000-000000000002','stripe-inbox-other@example.test','{}'),
 ('74000000-0000-4000-8000-000000000003','stripe-inbox-inactive@example.test','{}');
update public.profiles set is_active = true where id in ('74000000-0000-4000-8000-000000000001','74000000-0000-4000-8000-000000000002','74000000-0000-4000-8000-000000000003');
insert into public.user_roles (user_id, role) values ('74000000-0000-4000-8000-000000000001','STAFF'),('74000000-0000-4000-8000-000000000002','STAFF'),('74000000-0000-4000-8000-000000000003','STAFF');

update public.profiles set is_active=false where id='74000000-0000-4000-8000-000000000003';
create temp table fx(k text primary key,id uuid);grant all on fx to authenticated,service_role;
create temp table snapshots(k text primary key,v jsonb);grant all on snapshots to authenticated,service_role;
set local role service_role;
select public.configure_payment_provider('acct_test',false,'https://thelivingroom.vet');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"74000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'client',id from public.save_client(auth.uid(),null,null,'Payment','Family',null,null,'EMAIL',null,null);
insert into fx select 'other-client',id from public.save_client(auth.uid(),null,null,'Different','Family',null,null,'EMAIL',null,null);
insert into fx select 'product',id from public.save_catalog_product(null,null,'Visit','service','','visit',10000,true);
insert into fx values('invoice','74000000-0000-4000-8000-000000000010'),('attempt','74000000-0000-4000-8000-000000000020'),('refund','74000000-0000-4000-8000-000000000030');
select public.create_billing_invoice((select id from fx where k='invoice'),(select id from fx where k='client'));
select public.add_invoice_service(gen_random_uuid(),(select id from fx where k='invoice'),null,(select id from fx where k='product'),1);
select public.issue_billing_invoice((select id from fx where k='invoice'),(select version from public.billing_invoices where id=(select id from fx where k='invoice')));
insert into snapshots select 'before',public.read_invoice_payment_state((select id from fx where k='invoice'),(select id from fx where k='client'));
select public.prepare_invoice_checkout((select id from fx where k='attempt'),(select id from fx where k='invoice'),(select id from fx where k='client'),(select v->>'source_hash' from snapshots where k='before'),10000,'acct_test',false,'https://thelivingroom.vet/payment/return','https://thelivingroom.vet/payment/cancel');
insert into snapshots values('receipt',jsonb_build_object('event_id','evt_inbox','event_type','checkout.session.completed','provider_created_at',1790000000,'account_id','acct_test','livemode',false,'object_id','cs_test_inbox','request_id',(select id from fx where k='attempt'),'raw_sha256',repeat('a',64),'disposition','queued','reason',''));
insert into snapshots values('evidence',jsonb_build_object('family','checkout','account_id','acct_test','livemode',false,'kind','payment_succeeded','session_id','cs_test_inbox','payment_id','pi_inbox','amount_cents','10000','currency','usd','source_hash',(select v->>'source_hash' from snapshots where k='before')));
select throws_ok($$select public.receive_stripe_event((select v from snapshots where k='receipt'))$$,'42501',null,'Staff cannot insert signed Stripe receipts');
select throws_ok($$select public.claim_stripe_event()$$,'42501',null,'Staff cannot claim payment work');
set local role service_role;
select throws_ok($$select public.receive_stripe_event((select v||'{"client_url":"https://checkout.stripe.com/secret"}' from snapshots where k='receipt'))$$,'23514',null,'Receipt rejects provider URLs and unknown fields');
select throws_ok($$select public.receive_stripe_event((select v||'{"provider_created_at":"1790000000"}' from snapshots where k='receipt'))$$,'23514',null,'Receipt requires typed provider timestamp');
insert into fx select 'receipt',public.receive_stripe_event((select v from snapshots where k='receipt'));
select is(public.receive_stripe_event((select v from snapshots where k='receipt')),(select id from fx where k='receipt'),'Exact duplicate returns original receipt');
select is(public.receive_stripe_event((select v||jsonb_build_object('raw_sha256',repeat('b',64)) from snapshots where k='receipt')),(select id from fx where k='receipt'),'Semantically identical envelope with different raw hash deduplicates');
select throws_ok($$select public.receive_stripe_event((select v||'{"raw_sha256":"bad"}' from snapshots where k='receipt'))$$,'23514',null,'Duplicate must still have a valid hash');
select throws_ok($$select public.receive_stripe_event((select v||'{"object_id":"cs_changed"}' from snapshots where k='receipt'))$$,'23514',null,'Conflicting object on same event denied');
insert into snapshots select 'claim',public.claim_stripe_event();
select is((select v#>>'{receipt,id}' from snapshots where k='claim'),(select id::text from fx where k='receipt'),'Claim selects queued signed receipt');
select is((select v->>'attempt_count' from snapshots where k='claim'),'1','First claim has first attempt');
select is(public.claim_stripe_event(),null::jsonb,'Unexpired lease cannot be claimed twice');
select throws_ok($$select public.finish_stripe_event((select id from fx where k='receipt'),gen_random_uuid(),(select v from snapshots where k='evidence'))$$,'42501',null,'Wrong lease cannot post payment');
select throws_ok($$select public.finish_stripe_event((select id from fx where k='receipt'),(select (v->>'lease_token')::uuid from snapshots where k='claim'),(select v||'{"session_id":"cs_other"}' from snapshots where k='evidence'))$$,'23514',null,'Completion must match receipt object');
select throws_ok($$select public.finish_stripe_event((select id from fx where k='receipt'),(select (v->>'lease_token')::uuid from snapshots where k='claim'),(select v||'{"client_url":"https://checkout.stripe.com/secret"}' from snapshots where k='evidence'))$$,'23514',null,'Completion rejects transient Checkout URL');
select is(public.provider_checkout_context((select id from fx where k='attempt'))->>'state','prepared','Rejected completion leaves ledger unchanged');
select is(public.finish_stripe_event((select id from fx where k='receipt'),(select (v->>'lease_token')::uuid from snapshots where k='claim'),(select v from snapshots where k='evidence')),'completed','Receipt completion applies payment atomically');
select is(public.provider_checkout_context((select id from fx where k='attempt'))->>'state','paid','Completed receipt produces confirmed ledger payment');
select throws_ok($$select public.finish_stripe_event((select id from fx where k='receipt'),(select (v->>'lease_token')::uuid from snapshots where k='claim'),(select v from snapshots where k='evidence'))$$,'42501',null,'Consumed lease cannot apply evidence again');
reset role;
select is((select raw_sha256 from public.stripe_event_receipts where id=(select id from fx where k='receipt')),repeat('a',64),'First raw hash preserved');
select is((select count(*) from public.invoice_payments where invoice_id=(select id from fx where k='invoice')),1::bigint,'Atomic completion posts exactly one payment');
select is((select state from public.stripe_event_work where receipt_id=(select id from fx where k='receipt')),'completed','Work terminalized with payment');
set local role authenticated;
select public.credit_billing_invoice(gen_random_uuid(),(select id from fx where k='invoice'),2000,'Refund fixture');
insert into fx select 'payment',id from public.invoice_payments where invoice_id=(select id from fx where k='invoice');
select public.prepare_invoice_refund((select id from fx where k='refund'),(select id from fx where k='invoice'),(select id from fx where k='payment'),2000,'Reviewed adjustment');
set local role service_role;
insert into fx select 'refund-receipt',public.receive_stripe_event((select v||jsonb_build_object('event_id','evt_refundinbox','event_type','refund.updated','object_id','re_inbox','request_id',(select id from fx where k='refund')) from snapshots where k='receipt'));
insert into snapshots select 'refund-claim',public.claim_stripe_event();
select is(public.finish_stripe_event((select id from fx where k='refund-receipt'),(select (v->>'lease_token')::uuid from snapshots where k='refund-claim'),jsonb_build_object('family','refund','account_id','acct_test','livemode',false,'refund_id','re_inbox','provider_payment_id','pi_inbox','amount_cents','2000','currency','usd','status','succeeded')),'completed','Refund receipt atomically applies confirmed refund');
select is(public.provider_refund_context((select id from fx where k='refund'))->>'state','succeeded','Refund state confirmed from completed receipt');
insert into fx select 'retry-receipt',public.receive_stripe_event((select v||'{"event_id":"evt_retryinbox"}' from snapshots where k='receipt'));
insert into snapshots select 'retry-claim',public.claim_stripe_event();
select throws_ok($$select public.retry_stripe_event((select id from fx where k='retry-receipt'),(select (v->>'lease_token')::uuid from snapshots where k='retry-claim'),'Provider says card ending 1234 failed')$$,'23514',null,'Retry cannot persist provider free text');
select is(public.retry_stripe_event((select id from fx where k='retry-receipt'),(select (v->>'lease_token')::uuid from snapshots where k='retry-claim'),'transport_unknown'),'queued','Transport uncertainty queues bounded retry');
select is(public.claim_stripe_event(),null::jsonb,'Backoff prevents immediate retry');
reset role;
update public.stripe_event_work set available_at=clock_timestamp()-interval '1 second' where receipt_id=(select id from fx where k='retry-receipt');
set local role service_role;
insert into snapshots select 'second-claim',public.claim_stripe_event();
select is((select v->>'attempt_count' from snapshots where k='second-claim'),'2','Retry increments claim count');
reset role;
update public.stripe_event_work set lease_expires_at=clock_timestamp()-interval '1 second' where receipt_id=(select id from fx where k='retry-receipt');
set local role service_role;
insert into snapshots select 'third-claim',public.claim_stripe_event();
select isnt((select v->>'lease_token' from snapshots where k='second-claim'),(select v->>'lease_token' from snapshots where k='third-claim'),'Expired lease is replaced');
select throws_ok($$select public.finish_stripe_event((select id from fx where k='retry-receipt'),(select (v->>'lease_token')::uuid from snapshots where k='second-claim'),'{"family":"quarantine","reason":"provider_reconciliation_required"}')$$,'42501',null,'Expired worker cannot complete after reclaim');
select is(public.finish_stripe_event((select id from fx where k='retry-receipt'),(select (v->>'lease_token')::uuid from snapshots where k='third-claim'),'{"family":"quarantine","reason":"provider_reconciliation_required"}'),'quarantined','Current lease can preserve reconciliation requirement');
insert into fx select 'exhaust-receipt',public.receive_stripe_event((select v||'{"event_id":"evt_exhaustinbox"}' from snapshots where k='receipt'));
reset role;
update public.stripe_event_work set attempt_count=5,cycle_attempt_count=5,state='processing',lease_token=gen_random_uuid(),lease_expires_at=clock_timestamp()-interval '1 second' where receipt_id=(select id from fx where k='exhaust-receipt');
set local role service_role;
select is(public.claim_stripe_event(),null::jsonb,'Expired fifth lease is never retried automatically');
reset role;
select is((select state from public.stripe_event_work where receipt_id=(select id from fx where k='exhaust-receipt')),'quarantined','Retry exhaustion is visible quarantine');
set local role service_role;
insert into fx select 'unknown-receipt',public.receive_stripe_event((select v||'{"event_id":"evt_unknowninbox","event_type":"charge.dispute.created"}' from snapshots where k='receipt'));
insert into fx select 'wrong-profile',public.receive_stripe_event((select v||'{"event_id":"evt_wronginbox","account_id":"acct_other"}' from snapshots where k='receipt'));
insert into fx select 'unattributed',public.receive_stripe_event((select v||jsonb_build_object('event_id','evt_unattributed','request_id',gen_random_uuid()) from snapshots where k='receipt'));
select is(public.claim_stripe_event(),null::jsonb,'Unsupported, unknown account and unattributed events cannot be processed');
reset role;
select is((select disposition from public.stripe_event_receipts where id=(select id from fx where k='unknown-receipt')),'quarantined','Unsupported queued event is quarantined in DB');
select is((select reason from public.stripe_event_receipts where id=(select id from fx where k='wrong-profile')),'provider_not_configured','Incoming account must match commissioned singleton');
select is((select reason from public.stripe_event_receipts where id=(select id from fx where k='unattributed')),'unattributed_provider_object','Unknown request is retained for review');
select throws_ok($$update public.stripe_event_receipts set raw_sha256=repeat('f',64)$$,'23514','Financial history is append-only','Receipt history cannot be rewritten');
select throws_ok($$delete from public.stripe_event_work_history$$,'23514','Financial history is append-only','Worker history cannot be erased');
set local role authenticated;
select ok(jsonb_array_length(public.read_stripe_event_queue(250))>=7,'Active staff can review bounded queue state');
select ok(not exists(select 1 from jsonb_array_elements(public.read_stripe_event_queue(250)) value where value ? 'lease_token'),'Staff queue does not disclose worker lease token');
select throws_ok($$select * from public.stripe_event_work$$,'42501',null,'Direct worker state is service private');
select set_config('request.jwt.claims','{"sub":"74000000-0000-4000-8000-000000000003","role":"authenticated"}',true);
select is((select count(*) from public.stripe_event_receipts),0::bigint,'Inactive staff cannot read receipts');
select throws_ok($$select public.read_stripe_event_queue()$$,'42501',null,'Inactive staff queue RPC denied');
set local role anon;
select throws_ok($$select public.receive_stripe_event('{}')$$,'42501',null,'Unsigned anonymous database receipt writes denied');
reset role;
select * from finish();
rollback;
