begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,raw_user_meta_data) values('97000000-0000-4000-8000-000000000001','inquiry-staff@example.test','{}'),('97000000-0000-4000-8000-000000000002','inquiry-inactive@example.test','{}');
update profiles set is_active=false where id='97000000-0000-4000-8000-000000000002';
create temp table fx(k text primary key,id uuid);grant all on fx to authenticated;
insert into contact_submissions(name,email,subject,message) values('Claimed Person','claim@example.test','Inquiry fixture','Please call');
set local role anon;
select throws_ok($$insert into contact_submissions(name,email,subject,message) values('Claimed Person','claim@example.test','Inquiry fixture','Please call')$$,'42501',null,'Public Data API insert now denied; verified endpoint required');
select throws_ok($$select * from contact_submissions$$,'42501',null,'Anonymous cannot read originals');
select throws_ok($$insert into contact_submissions(id,name,email,subject,message) values(gen_random_uuid(),'Name','claim@example.test','Subject','Message')$$,'42501',null,'Anonymous cannot choose ID');
select throws_ok($$insert into contact_submissions(created_at,name,email,subject,message) values(now(),'Name','claim@example.test','Subject','Message')$$,'42501',null,'Anonymous cannot choose timestamp');
reset role;
select throws_ok($$insert into contact_submissions(name,email,subject,message) values('Name','bad','Subject','Message')$$,'23514',null,'Email validated server-side');
select throws_ok($$insert into contact_submissions(name,email,subject,message) values('Name','ok@example.test','Subject',repeat('x',2001))$$,'23514',null,'Message limit enforced server-side');
set local role anon;
select throws_ok($$select website_inquiry_open_count()$$,'42501',null,'Anonymous cannot inspect counts');
reset role;
insert into fx select 'inquiry',id from contact_submissions where subject='Inquiry fixture';
select is((select count(*) from website_inquiry_triage where inquiry_id=(select id from fx where k='inquiry')),1::bigint,'Triage initialized atomically');
select throws_ok($$update contact_submissions set name='Changed' where id=(select id from fx where k='inquiry')$$,'23514',null,'Original immutable even through privileged update');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"97000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into fx select 'client',id from save_client(auth.uid(),null,null,'Confirmed','Household','+13035550199','verified@example.test','EMAIL',null,null);
select is((read_website_inquiry((select id from fx where k='inquiry'))#>>'{submission,email}'),'claim@example.test','Original claimed identity preserved');
select is((select count(*) from list_website_inquiries('open','Inquiry fixture')),1::bigint,'Filtered inquiry returned');
select throws_ok($$update website_inquiry_triage set status='resolved'$$,'42501',null,'Direct metadata writes denied');
select throws_ok($$select update_website_inquiry('97000000-0000-4000-8000-000000000002',(select id from fx where k='inquiry'),1,'in_progress',null,'Reviewed request')$$,'42501',null,'Forged actor denied');
select throws_ok($$select update_website_inquiry(auth.uid(),(select id from fx where k='inquiry'),1,'in_progress','97000000-0000-4000-8000-000000000002','Reviewed request')$$,'23514',null,'Inactive assignee denied');
select lives_ok($$select update_website_inquiry(auth.uid(),(select id from fx where k='inquiry'),1,'in_progress',auth.uid(),'Staff reviewing request')$$,'Authored assignment accepted');
select throws_ok($$select update_website_inquiry(auth.uid(),(select id from fx where k='inquiry'),1,'resolved',null,'Stale review')$$,'40001',null,'Stale version denied');
select throws_ok($$select authorize_website_inquiry_reply(auth.uid(),(select id from fx where k='inquiry'),2)$$,'42501',null,'Unreviewed reply denied');
select throws_ok($$select review_website_inquiry_household(auth.uid(),(select id from fx where k='inquiry'),2,(select id from fx where k='client'),'EMAIL','verified@example.test',false,'Independently checked')$$,'23514',null,'Explicit confirmation required');
select throws_ok($$select review_website_inquiry_household(auth.uid(),(select id from fx where k='inquiry'),2,(select id from fx where k='client'),'EMAIL','claim@example.test',true,'Independently checked')$$,'23514',null,'Claimed destination cannot substitute for household destination');
select lives_ok($$select review_website_inquiry_household(auth.uid(),(select id from fx where k='inquiry'),2,(select id from fx where k='client'),'SMS','+13035550199',true,'Telephone review complete')$$,'SMS review does not infer permission');
select throws_ok($$select authorize_website_inquiry_reply(auth.uid(),(select id from fx where k='inquiry'),3)$$,'42501',null,'SMS reply without consent denied');
select lives_ok($$select review_website_inquiry_household(auth.uid(),(select id from fx where k='inquiry'),3,(select id from fx where k='client'),'EMAIL','verified@example.test',true,'Confirmed reply destination')$$,'Reviewed email destination accepted');
select lives_ok($$select authorize_website_inquiry_reply(auth.uid(),(select id from fx where k='inquiry'),4)$$,'Reviewed current email handoff accepted');
select is((select count(*) from messages where conversation_id in (select id from conversations where client_id=(select id from fx where k='client'))),0::bigint,'Review does not create trusted inbound or outbound messages');
select is((select count(*) from website_inquiry_history where inquiry_id=(select id from fx where k='inquiry') and actor_id=auth.uid()),4::bigint,'Every mutation and handoff authored');
select lives_ok($$select save_client(auth.uid(),(select id from fx where k='client'),(select version from clients where id=(select id from fx where k='client')),'Confirmed','Household','+13035550199','changed@example.test','EMAIL',null,null)$$,'Household destination can change after review');
select throws_ok($$select authorize_website_inquiry_reply(auth.uid(),(select id from fx where k='inquiry'),4)$$,'42501',null,'Changed current destination blocks old review');
select is((select count(*) from list_website_inquiries('all','Inquiry fixture',null,(select created_at from contact_submissions where id=(select id from fx where k='inquiry')),(select id from fx where k='inquiry'),25)),0::bigint,'Keyset cursor excludes same row');
select throws_ok($$select * from list_website_inquiries('all','',null,now(),null,25)$$,'23514',null,'Incomplete cursor fails closed');
select lives_ok($$select update_website_inquiry(auth.uid(),(select id from fx where k='inquiry'),4,'resolved',auth.uid(),'Review finished')$$,'Resolution recorded');
select throws_ok($$select authorize_website_inquiry_reply(auth.uid(),(select id from fx where k='inquiry'),5)$$,'42501',null,'Resolved inquiry cannot authorize reply');
select is((select count(*) from list_website_inquiries('open','Inquiry fixture')),0::bigint,'Resolved excluded from open filter');
select set_config('request.jwt.claims','{"sub":"97000000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select throws_ok($$select read_website_inquiry((select id from fx where k='inquiry'))$$,'42501',null,'Inactive staff denied');
reset role;
select throws_ok($$delete from website_inquiry_history where inquiry_id=(select id from fx where k='inquiry')$$,'23514',null,'History cannot be deleted');
select * from finish();
rollback;
