export const id = (n: number) =>
  `ca000000-0000-4000-8000-${String(n).padStart(12, "0")}`;
export const actor = id(1),
  pet = id(2),
  client = id(3),
  mapping = id(4),
  at = "2026-09-13T12:00:00Z";
export const payload = () => ({
  animal_link_id: mapping,
  patient_version: 1,
  snapshot_id: id(5),
  payload_hash: "a".repeat(64),
  observed_head_version: 1,
  consult_snapshot_id: id(6),
  consult_payload_hash: "b".repeat(64),
  consult_observed_head_version: 2,
  product_id: null,
  product_version: null,
  administered_on: null,
  administration_date_status: "uninterpreted",
  source_next_due_on: null,
  next_date_status: "unknown",
  status: "unknown",
  outside_author: null,
  reason: "Reviewed ambiguous source evidence",
  replaces_id: null,
  expected_predecessor_hash: null,
});
export const candidate = () => ({
  id: id(5),
  payload: {
    id: "71",
    consult_id: "81",
    product_id: "99",
    active: "unrecognized",
    qty: "1",
    date_of_administration: "unknown units 100",
    date_of_next_administration: null,
    notes: "Outside source <img src=x onerror=alert(1)>",
  },
  payload_hash: "a".repeat(64),
  external_id: "71",
  resource: "vaccination",
  source_origin: "https://api.trial.ezyvet.com",
  source_site_uid: "synthetic-site",
  created_at: at,
  head_version: 1,
  current_snapshot_id: id(5),
  is_current: true,
  observed_head_version: 1,
  current_head_scoped: true,
  is_current_snapshot: true,
  animal_link_id: mapping,
  pet_id: pet,
  client_id: client,
  consult_snapshot_id: id(6),
  consult_payload_hash: "b".repeat(64),
  consult_observed_head_version: 2,
  consult_external_id: "81",
  consult_head_version: 2,
  consult_current_snapshot_id: id(6),
  consult_is_current: true,
  eligible_for_review: true,
});
export const receipt = () => ({
  id: id(7),
  pet_id: pet,
  client_id: client,
  animal_link_id: mapping,
  version: 1,
  version_hash: "c".repeat(64),
  source: {
    origin: "https://api.trial.ezyvet.com",
    site_uid: "synthetic-site",
    animal_id: "22",
    vaccination_id: "71",
  },
  snapshot_id: id(5),
  payload_hash: "a".repeat(64),
  observed_head_version: 1,
  original: candidate().payload,
  consult: {
    snapshot_id: id(6),
    payload_hash: "b".repeat(64),
    observed_head_version: 2,
    external_id: "81",
  },
  reviewed: {
    administered_on: null,
    administration_date_status: "uninterpreted",
    source_next_due_on: null,
    next_date_status: "unknown",
    status: "unknown",
    outside_author: null,
  },
  product: null,
  reason: payload().reason,
  replaces_id: null,
  expected_predecessor_hash: null,
  approved_by: actor,
  approved_at: at,
  current: {
    is_current: true,
    is_latest: true,
    snapshot_id: id(5),
    head_version: 1,
    consult_snapshot_id: id(6),
    consult_head_version: 2,
    identity_valid: true,
  },
  correction_history: [],
});
export const request = () => ({
  request: {
    id: id(8),
    actor_id: actor,
    pet_id: pet,
    status: "prepared",
    payload: payload(),
    request_hash: "d".repeat(64),
    review_context: reviewContext(),
    created_at: at,
    resolved_at: null,
    approved_record_id: null,
  },
  receipt: null,
});

export function reviewContext() {
  const v = receipt();
  return {
    pet_id: v.pet_id,
    client_id: v.client_id,
    animal_link_id: v.animal_link_id,
    source: v.source,
    snapshot_id: v.snapshot_id,
    payload_hash: v.payload_hash,
    observed_head_version: v.observed_head_version,
    original: v.original,
    consult: v.consult,
    reviewed: v.reviewed,
    product: v.product,
  };
}
