import { test, expect, type Page } from '@playwright/test';
interface SyntheticFileRequest {
 request: { id: string; actor_id: string; pet_id: string; request_hash: string; status: string; request_payload: Record<string, unknown>; source_context: { schema_version: number; run_id: string; page: number; parent: Record<string, unknown>; attachment_snapshot_id: string; attachment_payload_hash: string; attachment_observed_head_version: number; attachment_external_id: string; attachment_metadata: Record<string, unknown> } };
 capture_intent: Record<string, unknown> | null; capture: Record<string, unknown> | null; worker: null; download_available: boolean;
}
const uid=(n:number)=>`de700000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const actor=uid(1),pet=uid(2),link=uid(3),run=uid(4),snapshot=uid(5),at='2026-09-13T12:00:00.123456+00:00';
async function fixture(page:Page,admin=true){
 const user={id:actor,aud:'authenticated',role:'authenticated',email:'synthetic@example.test',app_metadata:{provider:'email',providers:['email']},user_metadata:{},created_at:at};
 const exp=Math.floor(Date.now()/1000)+3600;
 const session={access_token:`eyJhbGciOiJIUzI1NiJ9.${Buffer.from(JSON.stringify({sub:actor,exp,role:'authenticated',aud:'authenticated'})).toString('base64url')}.synthetic`,refresh_token:'synthetic',token_type:'bearer',expires_in:3600,expires_at:exp,user};
 await page.addInitScript(s=>localStorage.setItem('sb-127-auth-token',JSON.stringify(s)),session);
 const mapping={link_id:link,pet_id:pet,patient_name:'Synthetic Juniper',household_name:'Synthetic Family',source_origin:'https://api.trial.ezyvet.com',source_site_uid:'synthetic-site',external_id:'77',patient_version:1};
 const parent={animal_link_id:link,pet_id:pet,client_id:uid(6),animal_external_id:'77',source_origin:mapping.source_origin,source_site_uid:mapping.source_site_uid,parent_type:'Animal',parent_external_id:'77',parent_snapshot_id:uid(7),parent_payload_hash:'a'.repeat(64),parent_observed_head_version:1};
 const state={stale:false,wrong:false,empty:false,more:false,running:false,recoveryFails:false,fileRequest:null as SyntheticFileRequest|null,fileRecoveryFails:false,fileCaptureLost:false,fileCaptureDisabled:false,prepared:null as Record<string,unknown>|null,preparationLost:false,preparationStale:false,stageCode:"",stageFails:false,failAfterStage:false,lease:false,nextPage:1,calls:[] as Array<{path:string;body:Record<string,unknown>}>};
 await page.route('**/*',r=>new URL(r.request().url()).origin==='http://127.0.0.1:8080'?r.continue():r.abort());
 await page.route('http://127.0.0.1:54321/**',async r=>{
  const path=new URL(r.request().url()).pathname,body=r.request().method()==='POST'?r.request().postDataJSON():{};
  if(path==='/auth/v1/token')return r.fulfill({json:session});
  if(path==='/auth/v1/user')return r.fulfill({json:user});
  if(path==='/rest/v1/profiles')return r.fulfill({json:[{id:actor,first_name:'Synthetic',last_name:'Admin',full_name:'Synthetic Admin',role:admin?'ADMIN':'STAFF',is_active:true}]});
  if(path==='/rest/v1/user_roles')return r.fulfill({json:[{role:admin?'ADMIN':'STAFF'}]});
  state.calls.push({path,body});
  if(path.endsWith('search_ezyvet_mapped_patients'))return r.fulfill({json:[mapping,{...mapping,link_id:uid(30),pet_id:uid(31),patient_name:'Synthetic Other'}]});
  const saved={id:run,requested_by:actor,resource:'attachment',source_origin:mapping.source_origin,source_site_uid:mapping.source_site_uid,status:state.running?'running':'review_ready',next_page:state.nextPage,retry_after:null,last_error_code:null,created_at:at,updated_at:at,lease_active:state.lease,scope:'parent_scoped',parent_context:parent};
  if(path.endsWith('prepare_ezyvet_attachment_download')){
   state.fileRequest??={request:{id:body.p_id,actor_id:actor,pet_id:pet,request_hash:'f'.repeat(64),status:'pending',request_payload:{run_id:body.p_run_id,page:body.p_page,snapshot_id:body.p_snapshot_id,payload_hash:body.p_payload_hash,observed_head_version:body.p_observed_head_version},source_context:{schema_version:1,run_id:run,page:1,parent,attachment_snapshot_id:snapshot,attachment_payload_hash:'b'.repeat(64),attachment_observed_head_version:1,attachment_external_id:'701',attachment_metadata:{id:701,name:'Original report',record_type:'Animal',record_id:77,mime_type:'application/pdf'}}},capture_intent:null,capture:null,worker:null,download_available:false};
   return r.fulfill({json:state.fileRequest});
  }
  if(path.endsWith('recover_ezyvet_attachment_download'))return state.fileRecoveryFails?r.fulfill({status:503,json:{message:'synthetic unavailable'}}):r.fulfill({json:state.fileRequest});
  if(path==='/functions/v1/ezyvet-attachment-capture'){
   if(state.fileCaptureDisabled)return r.fulfill({status:503,json:{error:'CAPTURE_DISABLED'}});
   const request=state.fileRequest!.request,metadata=request.source_context.attachment_metadata;
   const common={request_id:request.id,actor_id:actor,pet_id:pet,request_hash:request.request_hash,intent_hash:'d'.repeat(64),bucket:'ezyvet-attachments',object_path:`${actor}/${pet}/${request.id}/${uid(75)}/original`,content_sha256:'a'.repeat(64),file_size:37,mime_type:'application/pdf'};
   state.fileRequest!.capture_intent={...common,before_metadata:metadata,after_metadata:metadata};state.fileRequest!.capture={...common,storage_object_id:uid(76),capture_hash:'e'.repeat(64)};request.status='captured';
   return state.fileCaptureLost?r.fulfill({status:503,json:{error:'CAPTURE_UNAVAILABLE'}}):r.fulfill({json:{request_id:request.id,status:'captured',capture_hash:'e'.repeat(64)}});
  }
  if(path.endsWith('get_ezyvet_attachment_animal_parent'))return r.fulfill({json:parent});
  if(path.endsWith('list_ezyvet_clinical_candidates'))return r.fulfill({json:{animal_link_id:link,resource:'consult',candidates:[{id:uid(40),payload:{id:91,animal_id:77},payload_hash:'c'.repeat(64),external_id:'91',resource:'consult',source_origin:mapping.source_origin,source_site_uid:mapping.source_site_uid,created_at:at,head_version:1,current_snapshot_id:uid(40),is_current:true,observed_head_version:1,current_head_scoped:true,is_current_snapshot:true,animal_link_id:link,pet_id:pet,client_id:uid(6)},{id:uid(41),payload:{id:92,animal_id:77},payload_hash:'d'.repeat(64),external_id:'92',resource:'consult',source_origin:mapping.source_origin,source_site_uid:mapping.source_site_uid,created_at:at,head_version:2,current_snapshot_id:uid(41),is_current:false,observed_head_version:1,current_head_scoped:false,is_current_snapshot:true,animal_link_id:link,pet_id:pet,client_id:uid(6)}],has_more:false,next_cursor:null}});
  if(path.endsWith('prepare_ezyvet_attachment_scan')){
   if(state.preparationStale)return r.fulfill({status:409,json:{code:'40001',message:'synthetic source changed'}});
   state.prepared??={...saved,id:body.p_id,status:'running',next_page:1,parent_context:{...parent,parent_type:body.p_parent_type,parent_external_id:body.p_parent_type==='Consult'?'91':'77',parent_snapshot_id:body.p_parent_snapshot_id,parent_payload_hash:body.p_parent_payload_hash,parent_observed_head_version:body.p_parent_observed_head_version}};
   return state.preparationLost?r.fulfill({status:503,json:{message:'synthetic response lost'}}):r.fulfill({json:state.prepared});
  }
  if(path.endsWith('recover_ezyvet_attachment_run'))return state.recoveryFails?r.fulfill({status:503,json:{message:'synthetic unavailable'}}):r.fulfill({json:saved});
  if(path==='/functions/v1/ezyvet-import'){if(state.stageCode)return r.fulfill({status:409,json:{error:state.stageCode}});if(state.failAfterStage)state.recoveryFails=true;state.nextPage++;state.running=false;return state.stageFails?r.fulfill({status:503,json:{error:'synthetic lost response'}}):r.fulfill({json:{run_id:run,review_only:true,status:'review_ready',next_page:state.nextPage}});}
  if(path.endsWith('list_ezyvet_attachment_runs'))return r.fulfill({json:{runs:state.empty||body.p_animal_link_id!==link?[]:[...(state.prepared?[state.prepared]:[]),saved],has_more:false,next_cursor:null}});
  if(path.endsWith('list_ezyvet_attachment_observations')){
   if(state.prepared&&body.p_run_id===state.prepared.id)return r.fulfill({json:{run_id:state.prepared.id,pet_id:pet,parent_context:state.prepared.parent_context,parent_is_current:true,observations:[],has_more:false,next_cursor:null}});
   const second=body.p_after_page!==null;
   return r.fulfill({json:{run_id:run,pet_id:state.wrong?uid(99):pet,parent_context:parent,parent_is_current:!state.stale,observations:[{run_id:run,pet_id:pet,page:second?2:1,snapshot_id:second?uid(8):snapshot,payload_hash:'b'.repeat(64),observed_head_version:1,external_id:second?'702':'701',current_snapshot_id:second?uid(8):snapshot,current_head_version:state.stale?2:1,is_current:!state.stale,metadata:{name:second?'Other source file':'Original report',mime_type:second?'text/plain':'application/pdf',file_id:null,notes:second?'Retained source notes':'<script>not executable</script>',notes_truncated:second,name_truncated:false}}],has_more:state.more&&!second,next_cursor:state.more&&!second?{after_page:1,after_snapshot_id:snapshot}:null}});
  }
  return r.fulfill({json:[]});
 });
 await page.goto('/hub/tools/ezyvet');
 const section=page.getByRole('region',{name:'Attachment scan history',exact:true});
 const select=async()=>{await section.getByLabel('Find attachment history patient').fill('Juniper');await section.getByRole('button',{name:'Synthetic Juniper · Synthetic Family',exact:true}).click();};
 const open=async()=>{await select();await section.getByRole('button',{name:`View files from scan ${run.slice(0,8)}`}).click();await expect(section.getByRole('heading',{name:'Original report'})).toBeVisible();};
 return {state,section,select,open};
}
test('operator finds scoped scan and sees escaped source metadata without file links',async({page})=>{const f=await fixture(page);await f.open();await expect(f.section.getByText('<script>not executable</script>',{exact:true})).toBeVisible();await expect(f.section.getByText('Latest observed file revision',{exact:true})).toBeVisible();await expect(f.section.locator('a')).toHaveCount(0);expect(f.state.calls.some(c=>c.path.startsWith('/functions/'))).toBe(false);});
test('changed source retains original observation and explains both stale states',async({page})=>{const f=await fixture(page);await f.open();f.state.stale=true;await f.section.getByRole('button',{name:'Recheck observed files'}).click();await expect(f.section.getByText('File source changed',{exact:true})).toBeVisible();await expect(f.section.getByText(/patient or consultation source has changed/)).toBeVisible();await expect(f.section.getByRole('heading',{name:'Original report'})).toBeVisible();});
test('file pagination preserves exact cursor and exposes unsupported file coverage',async({page})=>{const f=await fixture(page);f.state.more=true;await f.open();await f.section.getByRole('button',{name:'Next file page'}).click();await expect(f.section.getByRole('heading',{name:'Other source file'})).toBeVisible();await expect(f.section.getByText(/not supported by the current file capture/)).toBeVisible();await expect(f.section.getByText(/Notes preview shortened/)).toBeVisible();expect(f.state.calls.some(c=>c.body.p_after_page===1&&c.body.p_after_snapshot_id===snapshot)).toBe(true);await f.section.getByRole('button',{name:'First file page'}).click();await expect(f.section.getByRole('heading',{name:'Original report'})).toBeVisible();});
test('wrong-patient response hides cached evidence and exposes a recoverable error',async({page})=>{const f=await fixture(page);await f.open();f.state.wrong=true;await f.section.getByRole('button',{name:'Recheck observed files'}).click();await expect(f.section.getByRole('alert')).toContainText('File evidence is unavailable');await expect(f.section.getByRole('heading',{name:'Original report'})).toHaveCount(0);});
test('changing mapped patient clears selected scan without losing original history',async({page})=>{const f=await fixture(page);await f.open();await f.section.getByRole('button',{name:'Synthetic Other · Synthetic Family',exact:true}).click();await expect(f.section.getByText('No saved attachment scans on this page.')).toBeVisible();await expect(f.section.getByRole('heading',{name:'Original report'})).toHaveCount(0);});
test('non-administrator cannot see attachment discovery controls',async({page})=>{const f=await fixture(page,false);await expect(f.section).toHaveCount(0);expect(f.state.calls.some(c=>c.path.includes('list_ezyvet_attachment'))).toBe(false);});
test('attachment history wraps on a narrow viewport',async({page})=>{await page.setViewportSize({width:375,height:812});const f=await fixture(page);await f.open();expect(await f.section.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);});

test('next page recovers owned scan before and after one explicit metadata request',async({page})=>{const f=await fixture(page);f.state.running=true;await f.open();await f.section.getByRole('button',{name:'Read next attachment page'}).click();await expect(f.section.getByText(/Saved scan is complete or has reached/)).toBeVisible();const calls=f.state.calls.filter(c=>c.path.endsWith('recover_ezyvet_attachment_run')||c.path==='/functions/v1/ezyvet-import');expect(calls.map(c=>c.path.split('/').at(-1))).toEqual(['recover_ezyvet_attachment_run','ezyvet-import','recover_ezyvet_attachment_run']);expect(calls[1].body).toEqual({run_id:run,resource:'attachment',animal_link_id:link,parent_type:'Animal',parent_snapshot_id:uid(7),parent_payload_hash:'a'.repeat(64),parent_observed_head_version:1});await expect(f.section.getByRole('button',{name:'Read next attachment page'})).toBeDisabled();});
test('lost page response recovers committed state without replaying the page',async({page})=>{const f=await fixture(page);f.state.running=true;f.state.stageFails=true;await f.open();await f.section.getByRole('button',{name:'Read next attachment page'}).click();await expect(f.section.getByText(/Saved scan state was recovered/)).toBeVisible();expect(f.state.calls.filter(c=>c.path==='/functions/v1/ezyvet-import')).toHaveLength(1);await expect(f.section.getByRole('button',{name:'Read next attachment page'})).toBeDisabled();await expect(f.section.getByLabel('Find attachment history patient')).toBeEnabled();});
test('failed recovery locks patient switching until original scan can be recovered',async({page})=>{const f=await fixture(page);f.state.running=true;await f.open();f.state.recoveryFails=true;await f.section.getByRole('button',{name:'Read next attachment page'}).click();await expect(f.section.getByText(/Scan state is unconfirmed/)).toBeVisible();await expect(f.section.getByLabel('Find attachment history patient')).toBeDisabled();await expect(f.section.getByRole('button',{name:'Read next attachment page'})).toBeDisabled();expect(f.state.calls.filter(c=>c.path==='/functions/v1/ezyvet-import')).toHaveLength(0);f.state.recoveryFails=false;await f.section.getByRole('button',{name:'Recheck saved attachment scan'}).click();await expect(f.section.getByLabel('Find attachment history patient')).toBeEnabled();});
test('fresh recovery detects an active lease before any page request',async({page})=>{const f=await fixture(page);f.state.running=true;await f.open();f.state.lease=true;await f.section.getByRole('button',{name:'Read next attachment page'}).click();await expect(f.section.getByText('Another request is active for this scan. Recheck its saved state.')).toBeVisible();expect(f.state.calls.filter(c=>c.path==='/functions/v1/ezyvet-import')).toHaveLength(0);});

test('lost post-send recovery guards navigation and retries only the saved-state read',async({page})=>{const f=await fixture(page);f.state.running=true;f.state.failAfterStage=true;await f.open();await f.section.getByRole('button',{name:'Read next attachment page'}).click();await expect(f.section.getByText(/Scan state is unconfirmed/)).toBeVisible();await page.getByRole('button',{name:'Home',exact:true}).click();await expect(page.getByRole('heading',{name:'Leave import recovery?'})).toBeVisible();await page.getByRole('button',{name:'Stay with this run'}).click();await expect(page).toHaveURL(/\/hub\/tools\/ezyvet$/);f.state.recoveryFails=false;await f.section.getByRole('button',{name:'Recheck saved attachment scan'}).click();await expect(f.section.getByLabel('Find attachment history patient')).toBeEnabled();expect(f.state.calls.filter(c=>c.path==='/functions/v1/ezyvet-import')).toHaveLength(1);await expect(f.section.getByRole('button',{name:'Read next attachment page'})).toBeDisabled();});

test('stale parent explains required fresh scan and prevents repeated page requests',async({page})=>{const f=await fixture(page);f.state.running=true;f.state.stageCode='SOURCE_ATTACHMENT_PARENT_STALE';await f.open();await f.section.getByRole('button',{name:'Read next attachment page'}).click();await expect(f.section.getByText(/select fresh source context for a new scan/)).toBeVisible();await expect(f.section.getByRole('button',{name:'Read next attachment page'})).toBeDisabled();await f.section.getByRole('button',{name:'Recheck saved attachment scan'}).click();await expect(f.section.getByRole('button',{name:'Read next attachment page'})).toBeDisabled();await expect(f.section.getByLabel('Find attachment history patient')).toBeEnabled();expect(f.state.calls.filter(c=>c.path==='/functions/v1/ezyvet-import')).toHaveLength(1);});
test('source access setup error is actionable and keeps the original run available',async({page})=>{const f=await fixture(page);f.state.running=true;f.state.stageCode='IMPORT_DISABLED';await f.open();await f.section.getByRole('button',{name:'Read next attachment page'}).click();await expect(f.section.getByText(/Attachment source access is not commissioned/)).toBeVisible();await expect(f.section.getByLabel('Find attachment history patient')).toBeEnabled();});

test('patient scan creation saves exact source context without reading a provider page',async({page})=>{const f=await fixture(page);await f.select();await f.section.getByRole('button',{name:'Create patient attachment scan',exact:true}).click();await expect(f.section.getByText(/Scan saved. Select Read next/)).toBeVisible();const calls=f.state.calls.filter(c=>c.path.endsWith('prepare_ezyvet_attachment_scan'));expect(calls).toHaveLength(1);expect(calls[0].body).toMatchObject({p_animal_link_id:link,p_parent_type:'Animal',p_parent_snapshot_id:uid(7),p_parent_payload_hash:'a'.repeat(64),p_parent_observed_head_version:1});expect(f.state.calls.filter(c=>c.path.startsWith('/functions/'))).toHaveLength(0);await expect(f.section.getByRole('button',{name:'Read next attachment page'})).toBeEnabled();});
test('current consultation can be selected while historical source is disabled',async({page})=>{const f=await fixture(page);await f.select();await expect(f.section.getByRole('button',{name:'Create scan for consultation 92',exact:true})).toBeDisabled();await f.section.getByRole('button',{name:'Create scan for consultation 91',exact:true}).click();await expect(f.section.getByText(/Scan saved. Select Read next/)).toBeVisible();expect(f.state.calls.find(c=>c.path.endsWith('prepare_ezyvet_attachment_scan'))?.body).toMatchObject({p_parent_type:'Consult',p_parent_snapshot_id:uid(40),p_parent_payload_hash:'c'.repeat(64),p_parent_observed_head_version:1});});
test('lost preparation response restores original operation after reload',async({page})=>{const f=await fixture(page);f.state.preparationLost=true;await f.select();await f.section.getByRole('button',{name:'Create patient attachment scan',exact:true}).click();await expect(f.section.getByText(/Scan preparation is unconfirmed/)).toBeVisible();await expect(f.section.getByLabel('Find attachment history patient')).toBeDisabled();const id=f.state.calls.find(c=>c.path.endsWith('prepare_ezyvet_attachment_scan'))!.body.p_id;await page.reload();await f.select();await expect(f.section.getByText(/An earlier preparation is retained/)).toBeVisible();f.state.preparationLost=false;await f.section.getByRole('button',{name:'Recover scan preparation'}).click();await expect(f.section.getByText(/Scan saved. Select Read next/)).toBeVisible();expect(f.state.calls.filter(c=>c.path.endsWith('prepare_ezyvet_attachment_scan')).map(c=>c.body.p_id)).toEqual([id,id]);expect(await page.evaluate(()=>Object.keys(sessionStorage).filter(k=>k.startsWith('lrv-attachment-preparation:')))).toEqual([]);});
test('definitive stale preparation permits fresh source selection without reading a page',async({page})=>{const f=await fixture(page);f.state.preparationStale=true;await f.select();await f.section.getByRole('button',{name:'Create patient attachment scan',exact:true}).click();await expect(f.section.getByText(/source changed before this scan could be prepared/)).toBeVisible();await f.section.getByRole('button',{name:'Choose fresh source context',exact:true}).click();await expect(f.section.getByRole('button',{name:'Create patient attachment scan',exact:true})).toBeEnabled();expect(f.state.calls.some(c=>c.path.startsWith('/functions/'))).toBe(false);});

test('unreadable local preparation still permits server history discovery',async({page})=>{const f=await fixture(page);await page.evaluate(({actor,link})=>sessionStorage.setItem(`lrv-attachment-preparation:${actor}:${link}`,'{broken'),{actor,link});await f.open();await expect(f.section.getByText(/local preparation reference could not be read/)).toBeVisible();await expect(f.section.getByRole('button',{name:'Create patient attachment scan',exact:true})).toBeDisabled();await f.section.getByRole('button',{name:'Clear unreadable local reference',exact:true}).click();await expect(f.section.getByRole('button',{name:'Create patient attachment scan',exact:true})).toBeEnabled();expect(f.state.calls.filter(c=>c.path.endsWith('prepare_ezyvet_attachment_scan'))).toHaveLength(0);});
test('storage failure prevents creating an untracked scan request',async({page})=>{const f=await fixture(page);await f.select();await page.evaluate(()=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key.startsWith('lrv-attachment-preparation:'))throw new Error('synthetic storage unavailable');return original.call(this,key,value);};});await f.section.getByRole('button',{name:'Create patient attachment scan',exact:true}).click();await expect(f.section.getByText(/Preparation could not be confirmed/)).toBeVisible();expect(f.state.calls.filter(c=>c.path.endsWith('prepare_ezyvet_attachment_scan'))).toHaveLength(0);});

test('file preparation and private capture remain separate explicit actions',async({page})=>{const f=await fixture(page);await f.open();await f.section.getByRole('button',{name:'Prepare private file copy',exact:true}).click();await expect(f.section.getByText(/File request recovered/)).toBeVisible();expect(f.state.calls.some(c=>c.path==='/functions/v1/ezyvet-attachment-capture')).toBe(false);await f.section.getByRole('button',{name:'Capture file privately',exact:true}).click();await expect(f.section.getByText('Private source copy captured. Clinical review is still required.',{exact:true})).toBeVisible();expect(f.state.calls.filter(c=>c.path==='/functions/v1/ezyvet-attachment-capture')).toHaveLength(1);await expect(f.section.getByRole('button',{name:'Capture file privately',exact:true})).toBeDisabled();await expect(f.section.locator('a')).toHaveCount(0);});
test('lost capture acknowledgment recovers the stored receipt without another capture',async({page})=>{const f=await fixture(page);f.state.fileCaptureLost=true;await f.open();await f.section.getByRole('button',{name:'Prepare private file copy',exact:true}).click();await expect(f.section.getByRole('button',{name:'Capture file privately',exact:true})).toBeEnabled();await f.section.getByRole('button',{name:'Capture file privately',exact:true}).click();await expect(f.section.getByText('Private source copy captured. Clinical review is still required.',{exact:true})).toBeVisible();await f.section.getByRole('button',{name:'Recheck file request',exact:true}).click();expect(f.state.calls.filter(c=>c.path==='/functions/v1/ezyvet-attachment-capture')).toHaveLength(1);});
test('unconfirmed file recovery guards pagination and patient switching',async({page})=>{const f=await fixture(page);f.state.more=true;await f.open();await f.section.getByRole('button',{name:'Prepare private file copy',exact:true}).click();await expect(f.section.getByRole('button',{name:'Capture file privately',exact:true})).toBeEnabled();f.state.fileRecoveryFails=true;await f.section.getByRole('button',{name:'Capture file privately',exact:true}).click();await expect(f.section.getByLabel('Find attachment history patient')).toBeDisabled();await expect(f.section.getByRole('button',{name:'Next file page',exact:true})).toBeDisabled();expect(f.state.calls.some(c=>c.path==='/functions/v1/ezyvet-attachment-capture')).toBe(false);f.state.fileRecoveryFails=false;await f.section.getByRole('button',{name:'Recheck file request',exact:true}).click();await expect(f.section.getByLabel('Find attachment history patient')).toBeEnabled();});
test('disabled private capture reports commissioning requirement and retains preparation',async({page})=>{const f=await fixture(page);f.state.fileCaptureDisabled=true;await f.open();await f.section.getByRole('button',{name:'Prepare private file copy',exact:true}).click();await expect(f.section.getByRole('button',{name:'Capture file privately',exact:true})).toBeEnabled();await f.section.getByRole('button',{name:'Capture file privately',exact:true}).click();await expect(f.section.getByText(/Private file capture is not commissioned/)).toBeVisible();expect(f.state.fileRequest!.request.status).toBe('pending');});

test('unreadable file reference prevents duplicate preparation without locking scan history',async({page})=>{const f=await fixture(page);await page.evaluate(({actor,pet,run,snapshot})=>sessionStorage.setItem(`lrv-attachment-file:${actor}:${pet}:${run}:1:${snapshot}:1`,'{broken'),{actor,pet,run,snapshot});await f.open();await expect(f.section.getByText(/local file reference could not be read/)).toBeVisible();await expect(f.section.getByRole('button',{name:'Prepare private file copy',exact:true})).toBeDisabled();await expect(f.section.getByLabel('Find attachment history patient')).toBeEnabled();expect(f.state.calls.some(c=>c.path.endsWith('prepare_ezyvet_attachment_download'))).toBe(false);});
test('prepared file reopens after reload and recovers the same request',async({page})=>{const f=await fixture(page);await f.open();await f.section.getByRole('button',{name:'Prepare private file copy',exact:true}).click();await expect(f.section.getByRole('button',{name:'Capture file privately',exact:true})).toBeEnabled();const requestId=f.state.fileRequest!.request.id;await page.reload();await f.open();await expect(f.section.getByText(/An earlier file request is retained/)).toBeVisible();await f.section.getByRole('button',{name:'Recheck file request',exact:true}).click();await expect(f.section.getByRole('button',{name:'Capture file privately',exact:true})).toBeEnabled();expect(f.state.calls.filter(c=>c.path.endsWith('prepare_ezyvet_attachment_download'))).toHaveLength(1);expect(f.state.calls.filter(c=>c.path.endsWith('recover_ezyvet_attachment_download')).at(-1)?.body.p_id).toBe(requestId);});
