import { createHash } from "node:crypto";
import { test, expect, type Page } from '@playwright/test';
interface SyntheticFileRequest {
 request: { id: string; actor_id: string; pet_id: string; request_hash: string; status: string; request_payload: Record<string, unknown>; source_context: { schema_version: number; run_id: string; page: number; parent: Record<string, unknown>; attachment_snapshot_id: string; attachment_payload_hash: string; attachment_observed_head_version: number; attachment_external_id: string; attachment_metadata: Record<string, unknown> } };
 capture_intent: Record<string, unknown> | null; capture: Record<string, unknown> | null; worker: null; download_available: boolean;
}
const originalBytes=Buffer.from("%PDF-1.4\nSynthetic original inspection\n%%EOF");
const originalDigest=createHash("sha256").update(originalBytes).digest("hex");
const uid=(n:number)=>`de700000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const actor=uid(1),pet=uid(2),link=uid(3),run=uid(4),snapshot=uid(5),at='2026-09-13T12:00:00.123456+00:00';
async function fixture(page:Page,admin=true){
 const user={id:actor,aud:'authenticated',role:'authenticated',email:'synthetic@example.test',app_metadata:{provider:'email',providers:['email']},user_metadata:{},created_at:at};
 const exp=Math.floor(Date.now()/1000)+3600;
 const session={access_token:`eyJhbGciOiJIUzI1NiJ9.${Buffer.from(JSON.stringify({sub:actor,exp,role:'authenticated',aud:'authenticated'})).toString('base64url')}.synthetic`,refresh_token:'synthetic',token_type:'bearer',expires_in:3600,expires_at:exp,user};
 await page.addInitScript(s=>localStorage.setItem('sb-127-auth-token',JSON.stringify(s)),session);
 const mapping={link_id:link,pet_id:pet,patient_name:'Synthetic Juniper',household_name:'Synthetic Family',source_origin:'https://api.trial.ezyvet.com',source_site_uid:'synthetic-site',external_id:'77',patient_version:1};
 const parent={animal_link_id:link,pet_id:pet,client_id:uid(6),animal_external_id:'77',source_origin:mapping.source_origin,source_site_uid:mapping.source_site_uid,parent_type:'Animal',parent_external_id:'77',parent_snapshot_id:uid(7),parent_payload_hash:'a'.repeat(64),parent_observed_head_version:1};
 const state={stale:false,wrong:false,empty:false,more:false,running:false,recoveryFails:false,fileRequest:null as SyntheticFileRequest|null,fileTombstone:null as Record<string,unknown>|null,filePrepareFails:false,fileAbandonLost:false,historyWrong:false,historyMore:false,fileRecoveryFails:false,originalCorrupt:false,originalDenied:false,fileCaptureLost:false,fileReserveOnly:false,fileCaptureDisabled:false,prepared:null as Record<string,unknown>|null,preparationLost:false,preparationStale:false,stageCode:"",stageFails:false,failAfterStage:false,lease:false,nextPage:1,calls:[] as Array<{path:string;body:Record<string,unknown>}>};
 await page.route('**/*',r=>new URL(r.request().url()).origin==='http://127.0.0.1:8080'?r.continue():r.abort());
 await page.route('http://127.0.0.1:54321/**',async r=>{
  const path=new URL(r.request().url()).pathname,body=r.request().method()==='POST'?r.request().postDataJSON():{};
  if(path.startsWith('/storage/v1/object/ezyvet-attachments/'))return state.originalDenied?r.fulfill({status:403,json:{message:'denied'}}):r.fulfill({contentType:'application/pdf',body:state.originalCorrupt?Buffer.alloc(originalBytes.length):originalBytes});
  if(path==='/auth/v1/token')return r.fulfill({json:session});
  if(path==='/auth/v1/user')return r.fulfill({json:user});
  if(path==='/rest/v1/profiles')return r.fulfill({json:[{id:actor,first_name:'Synthetic',last_name:'Admin',full_name:'Synthetic Admin',role:admin?'ADMIN':'STAFF',is_active:true}]});
  if(path==='/rest/v1/user_roles')return r.fulfill({json:[{role:admin?'ADMIN':'STAFF'}]});
  state.calls.push({path,body});
  if(path.endsWith('search_ezyvet_mapped_patients'))return r.fulfill({json:[mapping,{...mapping,link_id:uid(30),pet_id:uid(31),patient_name:'Synthetic Other'}]});
  const saved={id:run,requested_by:actor,resource:'attachment',source_origin:mapping.source_origin,source_site_uid:mapping.source_site_uid,status:state.running?'running':'review_ready',next_page:state.nextPage,retry_after:null,last_error_code:null,created_at:at,updated_at:at,lease_active:state.lease,scope:'parent_scoped',parent_context:parent};
  if(path.endsWith('list_ezyvet_attachment_record_versions'))return r.fulfill({json:{request_id:body.p_request_id,pet_id:pet,animal_link_id:link,attachment_external_id:'701',latest_record_id:null,records:[],has_more:false,next_cursor:null}});
  if(path.endsWith('list_ezyvet_attachment_cleanups'))return r.fulfill({json:{request_id:body.p_id,pet_id:pet,cleanups:[],has_more:false,next_cursor:null}});
  if(path.endsWith('list_ezyvet_attachment_downloads')){
   if(state.fileTombstone)return r.fulfill({json:{requests:[state.fileTombstone],has_more:false,next_cursor:null}});
   const item=state.fileRequest?structuredClone(state.fileRequest):null;
   if(item){Object.assign(item.request,{created_at:at,resolved_at:item.request.status==='pending'?null:at,pet_id:state.historyWrong?uid(99):pet});delete (item.request.source_context as Record<string,unknown>).attachment_metadata;if(item.capture_intent){delete item.capture_intent.before_metadata;delete item.capture_intent.after_metadata;}}
   const more=!!item&&state.historyMore&&!body.p_before_id;
   return r.fulfill({json:{requests:item?[item]:[],has_more:more,next_cursor:more?{before_at:at,before_id:item!.request.id}:null}});
  }
  if(path.endsWith('prepare_ezyvet_attachment_download')){
   if(state.filePrepareFails)return r.fulfill({status:503,json:{message:'synthetic preparation unavailable'}});
   state.fileRequest??={request:{id:body.p_id,actor_id:actor,pet_id:pet,request_hash:'f'.repeat(64),status:'pending',request_payload:{run_id:body.p_run_id,page:body.p_page,snapshot_id:body.p_snapshot_id,payload_hash:body.p_payload_hash,observed_head_version:body.p_observed_head_version},source_context:{schema_version:1,run_id:run,page:1,parent,attachment_snapshot_id:snapshot,attachment_payload_hash:'b'.repeat(64),attachment_observed_head_version:1,attachment_external_id:'701',attachment_metadata:{id:701,name:'Original report',record_type:'Animal',record_id:77,mime_type:'application/pdf'}}},capture_intent:null,capture:null,worker:null,download_available:false};
   return r.fulfill({json:state.fileRequest});
  }
  if(path.endsWith('recover_ezyvet_attachment_download'))return state.fileRecoveryFails?r.fulfill({status:503,json:{message:'synthetic unavailable'}}):r.fulfill({json:state.fileTombstone??state.fileRequest});
  if(path.endsWith('abandon_ezyvet_attachment_download')){
   if(state.fileRequest)state.fileRequest.request.status='abandoned';
   else state.fileTombstone={request:{id:body.p_id,actor_id:actor,pet_id:pet,status:'abandoned',request_hash:null,request_payload:null,source_context:null,created_at:at,resolved_at:at},capture_intent:null,capture:null,worker:null,download_available:false};
   return state.fileAbandonLost?r.fulfill({status:503,json:{message:'synthetic reply lost'}}):r.fulfill({json:state.fileTombstone??state.fileRequest});
  }
  if(path==='/functions/v1/ezyvet-attachment-capture'){
   if(state.fileCaptureDisabled)return r.fulfill({status:503,json:{error:'CAPTURE_DISABLED'}});
   const request=state.fileRequest!.request,metadata=request.source_context.attachment_metadata;
   const common={request_id:request.id,actor_id:actor,pet_id:pet,request_hash:request.request_hash,intent_hash:'d'.repeat(64),bucket:'ezyvet-attachments',object_path:`${actor}/${pet}/${request.id}/${uid(75)}/original`,content_sha256:originalDigest,file_size:originalBytes.length,mime_type:'application/pdf'};
   state.fileRequest!.capture_intent={...common,before_metadata:metadata,after_metadata:metadata};state.fileRequest!.capture={...common,storage_object_id:uid(76),capture_hash:'e'.repeat(64)};request.status='captured';
   if(state.fileReserveOnly){state.fileRequest!.capture=null;request.status='pending';return r.fulfill({status:503,json:{error:'CAPTURE_UNAVAILABLE'}});}
   return state.fileCaptureLost?r.fulfill({status:503,json:{error:'CAPTURE_UNAVAILABLE'}}):r.fulfill({json:{request_id:request.id,status:'captured',capture_hash:'e'.repeat(64)}});
  }
  if(path.endsWith('get_ezyvet_attachment_animal_parent'))return r.fulfill({json:parent});
  if(path.endsWith('list_ezyvet_clinical_candidates'))return r.fulfill({json:{animal_link_id:link,resource:'consult',candidates:[{id:uid(40),payload:{id:91,animal_id:77},payload_hash:'c'.repeat(64),external_id:'91',resource:'consult',source_origin:mapping.source_origin,source_site_uid:mapping.source_site_uid,created_at:at,head_version:1,current_snapshot_id:uid(40),is_current:true,observed_head_version:1,current_head_scoped:true,is_current_snapshot:true,animal_link_id:link,pet_id:pet,client_id:uid(6)},{id:uid(41),payload:{id:92,animal_id:77},payload_hash:'d'.repeat(64),external_id:'92',resource:'consult',source_origin:mapping.source_origin,source_site_uid:mapping.source_site_uid,created_at:at,head_version:2,current_snapshot_id:uid(41),is_current:false,observed_head_version:1,current_head_scoped:false,is_current_snapshot:true,animal_link_id:link,pet_id:pet,client_id:uid(6)}],has_more:false,next_cursor:null}});
  if(path.endsWith('prepare_ezyvet_attachment_scan')){
   if(state.preparationStale)return r.fulfill({status:409,json:{code:'40001',message:'synthetic source changed'}});
   state.prepared??={...saved,id:body.p_id,status:'running',next_page:1,parent_context:{...parent,parent_type:body.p_parent_type,parent_external_id:body.p_parent_type==='Consult'?'91':'77',parent_snapshot_id:body.p_parent_snapshot_id,parent_payload_hash:body.p_parent_payload_hash,parent_observed_head_version:body.p_parent_observed_head_version}};
   return state.preparationLost?r.fulfill({status:503,json:{message:'synthetic response lost'}}):r.fulfill({json:state.prepared});
  }
  if(path.endsWith('recover_ezyvet_attachment_run'))return state.recoveryFails?r.fulfill({status:503,json:{message:'synthetic unavailable'}}):r.fulfill({json:saved});
  if(path==='/functions/v1/ezyvet-import'){if(state.stageCode)return r.fulfill({status:409,json:{error:state.stageCode}});if(state.failAfterStage)state.recoveryFails=true;state.nextPage++;state.running=false;return state.stageFails?r.fulfill({status:503,json:{error:'synthetic lost response'}}):r.fulfill({json:{run_id:run,review_only:true,status:'review_ready',next_page:state.nextPage}});}
  if(path.endsWith('list_ezyvet_attachment_runs'))return r.fulfill({json:{runs:state.empty||body.p_animal_link_id!==link?[]:[...(state.prepared?[state.prepared]:[]),saved],has_more:false,next_cursor:null}});
  if(path.endsWith('list_ezyvet_attachment_observations')){
   if(state.prepared&&body.p_run_id===state.prepared.id)return r.fulfill({json:{run_id:state.prepared.id,pet_id:pet,parent_context:state.prepared.parent_context,parent_is_current:true,observations:[],has_more:false,next_cursor:null}});
   const second=body.p_after_page!==null&&body.p_after_snapshot_id!=='00000000-0000-0000-0000-000000000000';
   return r.fulfill({json:{run_id:run,pet_id:state.wrong?uid(99):pet,parent_context:parent,parent_is_current:!state.stale,observations:[{run_id:run,pet_id:pet,page:second?2:1,snapshot_id:second?uid(8):snapshot,payload_hash:'b'.repeat(64),observed_head_version:1,external_id:second?'702':'701',current_snapshot_id:second?uid(8):snapshot,current_head_version:state.stale?2:1,is_current:!state.stale,metadata:{name:second?'Other source file':'Original report',mime_type:second?'text/plain':'application/pdf',file_id:null,notes:second?'Retained source notes':'<script>not executable</script>',notes_truncated:second,name_truncated:false}}],has_more:state.more&&!second,next_cursor:state.more&&!second?{after_page:1,after_snapshot_id:snapshot}:null}});
  }
  return r.fulfill({json:[]});
 });
 await page.goto('/hub/tools/ezyvet');
 const section=page.getByRole('region',{name:'Attachment scan history',exact:true});
 const select=async()=>{await section.getByLabel('Find attachment history patient').fill('Juniper');await section.getByRole('button',{name:'Synthetic Juniper · Synthetic Family',exact:true}).click();};
 const open=async()=>{await select();await section.getByRole('button',{name:`View files from scan ${run.slice(0,8)}`}).click();await expect(section.getByRole('heading',{name:'Original report'})).toBeVisible();};
 return {state,section,select,open};
}
test('operator finds scoped scan and sees escaped source metadata without file links',async({page})=>{const f=await fixture(page);await f.open();await expect(f.section.getByText('<script>not executable</script>',{exact:true})).toBeVisible();await expect(f.section.getByText('Latest observed file revision',{exact:true})).toBeVisible();await expect(f.section.locator('a')).toHaveCount(0);expect(f.state.calls.some(c=>c.path.startsWith('/functions/'))).toBe(false);});
test('changed source retains original observation and explains both stale states',async({page})=>{const f=await fixture(page);await f.open();f.state.stale=true;await f.section.getByRole('button',{name:'Recheck observed files'}).click();await expect(f.section.getByText('File source changed',{exact:true})).toBeVisible();await expect(f.section.getByText(/patient or consultation source has changed/)).toBeVisible();await expect(f.section.getByRole('heading',{name:'Original report'})).toBeVisible();});
test('file pagination preserves exact cursor and exposes unsupported file coverage',async({page})=>{const f=await fixture(page);f.state.more=true;await f.open();await f.section.getByRole('button',{name:'Next file page'}).click();await expect(f.section.getByRole('heading',{name:'Other source file'})).toBeVisible();await expect(f.section.getByText(/not supported by the current file capture/)).toBeVisible();await expect(f.section.getByText(/Notes preview shortened/)).toBeVisible();expect(f.state.calls.some(c=>c.body.p_after_page===1&&c.body.p_after_snapshot_id===snapshot)).toBe(true);await f.section.getByRole('button',{name:'First file page'}).click();await expect(f.section.getByRole('heading',{name:'Original report'})).toBeVisible();});
test('wrong-patient response hides cached evidence and exposes a recoverable error',async({page})=>{const f=await fixture(page);await f.open();f.state.wrong=true;await f.section.getByRole('button',{name:'Recheck observed files'}).click();await expect(f.section.getByRole('alert')).toContainText('File evidence is unavailable');await expect(f.section.getByRole('heading',{name:'Original report'})).toHaveCount(0);});
test('changing mapped patient clears selected scan without losing original history',async({page})=>{const f=await fixture(page);await f.open();await f.section.getByRole('button',{name:'Synthetic Other · Synthetic Family',exact:true}).click();await expect(f.section.getByText('No saved attachment scans on this page.')).toBeVisible();await expect(f.section.getByRole('heading',{name:'Original report'})).toHaveCount(0);});
test('non-administrator cannot see attachment discovery controls',async({page})=>{const f=await fixture(page,false);await expect(f.section).toHaveCount(0);expect(f.state.calls.some(c=>c.path.includes('list_ezyvet_attachment'))).toBe(false);});
test('attachment history wraps on a narrow viewport',async({page})=>{await page.setViewportSize({width:375,height:812});const f=await fixture(page);await f.open();expect(await f.section.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);});

test('next page recovers owned scan before and after one explicit metadata request',async({page})=>{const f=await fixture(page);f.state.running=true;await f.open();await f.section.getByRole('button',{name:'Read next attachment page'}).click();await expect(f.section.getByText(/Saved scan is complete or has reached/)).toBeVisible();const calls=f.state.calls.filter(c=>c.path.endsWith('recover_ezyvet_attachment_run')||c.path==='/functions/v1/ezyvet-import');expect(calls.map(c=>c.path.split('/').at(-1))).toEqual(['recover_ezyvet_attachment_run','ezyvet-import','recover_ezyvet_attachment_run']);expect(calls[1].body).toEqual({run_id:run,resource:'attachment',animal_link_id:link,parent_type:'Animal',parent_snapshot_id:uid(7),parent_payload_hash:'a'.repeat(64),parent_observed_head_version:1});await expect(f.section.getByRole('button',{name:'Read next attachment page'})).toBeDisabled();});
test('lost page response recovers committed state without replaying the page',async({page})=>{const f=await fixture(page);f.state.running=true;f.state.stageFails=true;await f.open();await f.section.getByRole('button',{name:'Read next attachment page'}).click();await expect(f.section.getByText(/Saved scan state was recovered/)).toBeVisible();expect(f.state.calls.filter(c=>c.path==='/functions/v1/ezyvet-import')).toHaveLength(1);await expect(f.section.getByRole('button',{name:'Read next attachment page'})).toBeDisabled();await expect(f.section.getByLabel('Find attachment history patient')).toBeEnabled();});
test('failed recovery locks patient switching until original scan can be recovered',async({page})=>{const f=await fixture(page);f.state.running=true;await f.open();f.state.recoveryFails=true;await f.section.getByRole('button',{name:'Read next attachment page'}).click();await expect(f.section.getByText(/Scan state is unconfirmed/)).toBeVisible();await expect(f.section.getByLabel('Find attachment history patient')).toBeDisabled();await expect(f.section.getByRole('button',{name:'Read next attachment page'})).toBeDisabled();expect(f.state.calls.filter(c=>c.path==='/functions/v1/ezyvet-import')).toHaveLength(0);f.state.recoveryFails=false;await f.section.getByRole('button',{name:'Recheck saved attachment scan'}).click();await expect(f.section.getByLabel('Find attachment history patient')).toBeEnabled();});
test('fresh recovery detects an active lease before any page request',async({page})=>{const f=await fixture(page);f.state.running=true;await f.open();f.state.lease=true;await f.section.getByRole('button',{name:'Read next attachment page'}).click();await expect(f.section.getByText('Another request is active for this scan. Recheck its saved state.')).toBeVisible();expect(f.state.calls.filter(c=>c.path==='/functions/v1/ezyvet-import')).toHaveLength(0);});

test('lost post-send recovery guards navigation and retries only the saved-state read',async({page})=>{const f=await fixture(page);f.state.running=true;f.state.failAfterStage=true;await f.open();await f.section.getByRole('button',{name:'Read next attachment page'}).click();await expect(f.section.getByText(/Scan state is unconfirmed/)).toBeVisible();await page.getByRole('button',{name:'Home',exact:true}).click();await expect(page.getByRole('heading',{name:'Leave import recovery?'})).toBeVisible();await page.getByRole('button',{name:'Stay with this run'}).click();await expect(page).toHaveURL(/\/hub\/tools\/ezyvet$/);f.state.recoveryFails=false;await f.section.getByRole('button',{name:'Recheck saved attachment scan'}).click();await expect(f.section.getByLabel('Find attachment history patient')).toBeEnabled();expect(f.state.calls.filter(c=>c.path==='/functions/v1/ezyvet-import')).toHaveLength(1);await expect(f.section.getByRole('button',{name:'Read next attachment page'})).toBeDisabled();});

test('stale parent explains required fresh scan and prevents repeated page requests',async({page})=>{const f=await fixture(page);f.state.running=true;f.state.stageCode='SOURCE_ATTACHMENT_PARENT_STALE';await f.open();await f.section.getByRole('button',{name:'Read next attachment page'}).click();await expect(f.section.getByText(/select fresh source context for a new scan/)).toBeVisible();await expect(f.section.getByRole('button',{name:'Read next attachment page'})).toBeDisabled();await f.section.getByRole('button',{name:'Recheck saved attachment scan'}).click();await expect(f.section.getByRole('button',{name:'Read next attachment page'})).toBeDisabled();await expect(f.section.getByLabel('Find attachment history patient')).toBeEnabled();expect(f.state.calls.filter(c=>c.path==='/functions/v1/ezyvet-import')).toHaveLength(1);});
test('source access setup error is actionable and keeps the original run available',async({page})=>{const f=await fixture(page);f.state.running=true;f.state.stageCode='IMPORT_DISABLED';await f.open();await f.section.getByRole('button',{name:'Read next attachment page'}).click();await expect(f.section.getByText(/Attachment source access is not commissioned/)).toBeVisible();await expect(f.section.getByLabel('Find attachment history patient')).toBeEnabled();});

test('patient scan creation saves exact source context without reading a provider page',async({page})=>{const f=await fixture(page);await f.select();await f.section.getByRole('button',{name:'Create patient attachment scan',exact:true}).click();await expect(f.section.getByText(/Scan saved. Select Read next/)).toBeVisible();const calls=f.state.calls.filter(c=>c.path.endsWith('prepare_ezyvet_attachment_scan'));expect(calls).toHaveLength(1);expect(calls[0].body).toMatchObject({p_animal_link_id:link,p_parent_type:'Animal',p_parent_snapshot_id:uid(7),p_parent_payload_hash:'a'.repeat(64),p_parent_observed_head_version:1});expect(f.state.calls.filter(c=>c.path.startsWith('/functions/'))).toHaveLength(0);await expect(f.section.getByRole('button',{name:'Read next attachment page'})).toBeEnabled();});
test('current consultation can be selected while historical source is disabled',async({page})=>{const f=await fixture(page);await f.select();await expect(f.section.getByRole('button',{name:'Create scan for consultation 92',exact:true})).toBeDisabled();await f.section.getByRole('button',{name:'Create scan for consultation 91',exact:true}).click();await expect(f.section.getByText(/Scan saved. Select Read next/)).toBeVisible();expect(f.state.calls.find(c=>c.path.endsWith('prepare_ezyvet_attachment_scan'))?.body).toMatchObject({p_parent_type:'Consult',p_parent_snapshot_id:uid(40),p_parent_payload_hash:'c'.repeat(64),p_parent_observed_head_version:1});});
test('lost preparation response restores original operation after reload',async({page})=>{const f=await fixture(page);f.state.preparationLost=true;await f.select();await f.section.getByRole('button',{name:'Create patient attachment scan',exact:true}).click();await expect(f.section.getByText(/Scan preparation is unconfirmed/)).toBeVisible();await expect(f.section.getByLabel('Find attachment history patient')).toBeDisabled();const id=f.state.calls.find(c=>c.path.endsWith('prepare_ezyvet_attachment_scan'))!.body.p_id;await page.reload();await f.select();await expect(f.section.getByText(/An earlier preparation is retained/)).toBeVisible();f.state.preparationLost=false;await f.section.getByRole('button',{name:'Recover scan preparation'}).click();await expect(f.section.getByText(/Scan saved. Select Read next/)).toBeVisible();expect(f.state.calls.filter(c=>c.path.endsWith('prepare_ezyvet_attachment_scan')).map(c=>c.body.p_id)).toEqual([id,id]);expect(await page.evaluate(()=>Object.keys(sessionStorage).filter(k=>k.startsWith('lrv-attachment-preparation:')))).toEqual([]);});
test('definitive stale preparation permits fresh source selection without reading a page',async({page})=>{const f=await fixture(page);f.state.preparationStale=true;await f.select();await f.section.getByRole('button',{name:'Create patient attachment scan',exact:true}).click();await expect(f.section.getByText(/source changed before this scan could be prepared/)).toBeVisible();await f.section.getByRole('button',{name:'Choose fresh source context',exact:true}).click();await expect(f.section.getByRole('button',{name:'Create patient attachment scan',exact:true})).toBeEnabled();expect(f.state.calls.some(c=>c.path.startsWith('/functions/'))).toBe(false);});

test('unreadable local preparation still permits server history discovery',async({page})=>{const f=await fixture(page);await page.evaluate(({actor,link})=>sessionStorage.setItem(`lrv-attachment-preparation:${actor}:${link}`,'{broken'),{actor,link});await f.open();await expect(f.section.getByText(/local preparation reference could not be read/)).toBeVisible();await expect(f.section.getByRole('button',{name:'Create patient attachment scan',exact:true})).toBeDisabled();await f.section.getByRole('button',{name:'Clear unreadable local reference',exact:true}).click();await expect(f.section.getByRole('button',{name:'Create patient attachment scan',exact:true})).toBeEnabled();expect(f.state.calls.filter(c=>c.path.endsWith('prepare_ezyvet_attachment_scan'))).toHaveLength(0);});
test('storage failure prevents creating an untracked scan request',async({page})=>{const f=await fixture(page);await f.select();await page.evaluate(()=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key.startsWith('lrv-attachment-preparation:'))throw new Error('synthetic storage unavailable');return original.call(this,key,value);};});await f.section.getByRole('button',{name:'Create patient attachment scan',exact:true}).click();await expect(f.section.getByText(/Preparation could not be confirmed/)).toBeVisible();expect(f.state.calls.filter(c=>c.path.endsWith('prepare_ezyvet_attachment_scan'))).toHaveLength(0);});

test('file preparation and private capture remain separate explicit actions',async({page})=>{const f=await fixture(page);await f.open();await f.section.getByRole('button',{name:'Prepare private file copy',exact:true}).click();await expect(f.section.getByText(/File request recovered/)).toBeVisible();expect(f.state.calls.some(c=>c.path==='/functions/v1/ezyvet-attachment-capture')).toBe(false);await f.section.getByRole('button',{name:'Capture file privately',exact:true}).click();await expect(f.section.getByText('Private source copy captured. Clinical review is still required.',{exact:true})).toBeVisible();expect(f.state.calls.filter(c=>c.path==='/functions/v1/ezyvet-attachment-capture')).toHaveLength(1);await expect(f.section.getByRole('button',{name:'Capture file privately',exact:true})).toBeDisabled();await expect(f.section.locator('a')).toHaveCount(0);await expect(f.section.getByRole('button',{name:'Abandon file request',exact:true})).toBeDisabled();});
test('lost capture acknowledgment recovers the stored receipt without another capture',async({page})=>{const f=await fixture(page);f.state.fileCaptureLost=true;await f.open();await f.section.getByRole('button',{name:'Prepare private file copy',exact:true}).click();await expect(f.section.getByRole('button',{name:'Capture file privately',exact:true})).toBeEnabled();await f.section.getByRole('button',{name:'Capture file privately',exact:true}).click();await expect(f.section.getByText('Private source copy captured. Clinical review is still required.',{exact:true})).toBeVisible();await f.section.getByRole('button',{name:'Recheck file request',exact:true}).click();expect(f.state.calls.filter(c=>c.path==='/functions/v1/ezyvet-attachment-capture')).toHaveLength(1);});
test('unconfirmed file recovery guards pagination and patient switching',async({page})=>{const f=await fixture(page);f.state.more=true;await f.open();await f.section.getByRole('button',{name:'Prepare private file copy',exact:true}).click();await expect(f.section.getByRole('button',{name:'Capture file privately',exact:true})).toBeEnabled();f.state.fileRecoveryFails=true;await f.section.getByRole('button',{name:'Capture file privately',exact:true}).click();await expect(f.section.getByLabel('Find attachment history patient')).toBeDisabled();await expect(f.section.getByRole('button',{name:'Next file page',exact:true})).toBeDisabled();expect(f.state.calls.some(c=>c.path==='/functions/v1/ezyvet-attachment-capture')).toBe(false);f.state.fileRecoveryFails=false;await f.section.getByRole('button',{name:'Recheck file request',exact:true}).click();await expect(f.section.getByLabel('Find attachment history patient')).toBeEnabled();});
test('disabled private capture reports commissioning requirement and retains preparation',async({page})=>{const f=await fixture(page);f.state.fileCaptureDisabled=true;await f.open();await f.section.getByRole('button',{name:'Prepare private file copy',exact:true}).click();await expect(f.section.getByRole('button',{name:'Capture file privately',exact:true})).toBeEnabled();await f.section.getByRole('button',{name:'Capture file privately',exact:true}).click();await expect(f.section.getByText(/Private file capture is not commissioned/)).toBeVisible();expect(f.state.fileRequest!.request.status).toBe('pending');});

test('unreadable file reference prevents duplicate preparation without locking scan history',async({page})=>{const f=await fixture(page);await page.evaluate(({actor,pet,run,snapshot})=>sessionStorage.setItem(`lrv-attachment-file:${actor}:${pet}:${run}:1:${snapshot}:1`,'{broken'),{actor,pet,run,snapshot});await f.open();await expect(f.section.getByText(/local file reference could not be read/)).toBeVisible();await expect(f.section.getByRole('button',{name:'Prepare private file copy',exact:true})).toBeDisabled();await expect(f.section.getByLabel('Find attachment history patient')).toBeEnabled();expect(f.state.calls.some(c=>c.path.endsWith('prepare_ezyvet_attachment_download'))).toBe(false);});
test('prepared file reopens after reload and recovers the same request',async({page})=>{const f=await fixture(page);await f.open();await f.section.getByRole('button',{name:'Prepare private file copy',exact:true}).click();await expect(f.section.getByRole('button',{name:'Capture file privately',exact:true})).toBeEnabled();const requestId=f.state.fileRequest!.request.id;await page.reload();await f.open();await expect(f.section.getByText(/An earlier file request is retained/)).toBeVisible();await f.section.getByRole('button',{name:'Recheck file request',exact:true}).click();await expect(f.section.getByRole('button',{name:'Capture file privately',exact:true})).toBeEnabled();expect(f.state.calls.filter(c=>c.path.endsWith('prepare_ezyvet_attachment_download'))).toHaveLength(1);expect(f.state.calls.filter(c=>c.path.endsWith('recover_ezyvet_attachment_download')).at(-1)?.body.p_id).toBe(requestId);});

test('server file history restores a lost local reference without preparing another copy',async({page})=>{const f=await fixture(page);await f.open();await f.section.getByRole('button',{name:'Prepare private file copy',exact:true}).click();await expect(f.section.getByRole('button',{name:'Capture file privately',exact:true})).toBeEnabled();const id=f.state.fileRequest!.request.id;await page.evaluate(()=>sessionStorage.clear());await page.reload();await f.select();const history=f.section.getByRole('region',{name:'Saved attachment file requests',exact:true});await history.getByRole('button',{name:`Recover file request ${id.slice(0,8)}`,exact:true}).click();await expect(history.getByText(/verified and reopened at its original source page/)).toBeVisible();await expect(f.section.getByRole('heading',{name:'Original report'})).toBeVisible();await f.section.getByRole('button',{name:'Recheck file request',exact:true}).click();await expect(f.section.getByRole('button',{name:'Capture file privately',exact:true})).toBeEnabled();expect(f.state.calls.filter(c=>c.path.endsWith('prepare_ezyvet_attachment_download'))).toHaveLength(1);expect(f.state.calls.some(c=>c.path==='/functions/v1/ezyvet-attachment-capture')).toBe(false);});
test('saved request history rejects a response scoped to another patient',async({page})=>{const f=await fixture(page);await f.open();await f.section.getByRole('button',{name:'Prepare private file copy',exact:true}).click();await expect(f.section.getByRole('button',{name:'Capture file privately',exact:true})).toBeEnabled();f.state.historyWrong=true;const history=f.section.getByRole('region',{name:'Saved attachment file requests',exact:true});await history.getByRole('button',{name:'Refresh saved file requests'}).click();await expect(history.getByRole('alert')).toContainText('Saved file requests are unavailable');await expect(history.getByRole('button',{name:/Recover file request/})).toHaveCount(0);});
test('file history pagination uses the server timestamp and UUID cursor',async({page})=>{const f=await fixture(page);f.state.historyMore=true;await f.open();await f.section.getByRole('button',{name:'Prepare private file copy',exact:true}).click();const history=f.section.getByRole('region',{name:'Saved attachment file requests',exact:true});await expect(history.getByRole('button',{name:'Older file requests',exact:true})).toBeEnabled();await history.getByRole('button',{name:'Older file requests',exact:true}).click();await expect(history.getByRole('button',{name:'Older file requests',exact:true})).toBeDisabled();expect(f.state.calls.some(c=>c.path.endsWith('list_ezyvet_attachment_downloads')&&c.body.p_before_at===at&&c.body.p_before_id===f.state.fileRequest!.request.id)).toBe(true);});
test('verified server history repairs a mismatched local request hash',async({page})=>{const f=await fixture(page);await f.open();await f.section.getByRole('button',{name:'Prepare private file copy',exact:true}).click();await expect(f.section.getByRole('button',{name:'Capture file privately',exact:true})).toBeEnabled();const id=f.state.fileRequest!.request.id;await page.evaluate(()=>{const key=Object.keys(sessionStorage).find(k=>k.startsWith('lrv-attachment-file:'))!;const value=JSON.parse(sessionStorage.getItem(key)!);value.requestHash='0'.repeat(64);sessionStorage.setItem(key,JSON.stringify(value));});await page.reload();await f.open();await f.section.getByRole('button',{name:'Recheck file request',exact:true}).click();await expect(f.section.getByLabel('Find attachment history patient')).toBeDisabled();const history=f.section.getByRole('region',{name:'Saved attachment file requests',exact:true});await expect(history.getByRole('button',{name:`Recover file request ${id.slice(0,8)}`,exact:true})).toBeEnabled();await history.getByRole('button',{name:`Recover file request ${id.slice(0,8)}`,exact:true}).click();await expect(history.getByText(/verified and reopened at its original source page/)).toBeVisible();await f.section.getByRole('button',{name:'Recheck file request',exact:true}).click();await expect(f.section.getByRole('button',{name:'Capture file privately',exact:true})).toBeEnabled();expect(f.state.calls.filter(c=>c.path.endsWith('prepare_ezyvet_attachment_download'))).toHaveLength(1);});

test('file abandonment requires confirmation and preserves the request in history',async({page})=>{const f=await fixture(page);await f.open();await f.section.getByRole('button',{name:'Prepare private file copy',exact:true}).click();await expect(f.section.getByRole('button',{name:'Capture file privately',exact:true})).toBeEnabled();await f.section.getByRole('button',{name:'Abandon file request',exact:true}).click();await page.getByRole('button',{name:'Keep file request',exact:true}).click();expect(f.state.calls.some(c=>c.path.endsWith('abandon_ezyvet_attachment_download'))).toBe(false);await f.section.getByRole('button',{name:'Abandon file request',exact:true}).click();await page.getByRole('button',{name:'Confirm file abandonment',exact:true}).click();await expect(f.section.getByText('This file request was abandoned. It cannot be resumed.',{exact:true})).toBeVisible();await expect(f.section.getByRole('button',{name:'Capture file privately',exact:true})).toBeDisabled();expect(f.state.calls.find(c=>c.path.endsWith('abandon_ezyvet_attachment_download'))?.body).toEqual({p_id:f.state.fileRequest!.request.id,p_pet_id:pet,p_confirmed:true});});
test('lost abandonment response recovers terminal state and allows a new explicit request',async({page})=>{const f=await fixture(page);f.state.fileAbandonLost=true;await f.open();await f.section.getByRole('button',{name:'Prepare private file copy',exact:true}).click();await expect(f.section.getByRole('button',{name:'Capture file privately',exact:true})).toBeEnabled();await f.section.getByRole('button',{name:'Abandon file request',exact:true}).click();await page.getByRole('button',{name:'Confirm file abandonment',exact:true}).click();await expect(f.section.getByText('This file request was abandoned. It cannot be resumed.',{exact:true})).toBeVisible();await f.section.getByRole('button',{name:'Start another file request',exact:true}).click();await expect(f.section.getByRole('button',{name:'Prepare private file copy',exact:true})).toBeEnabled();expect(f.state.calls.filter(c=>c.path.endsWith('abandon_ezyvet_attachment_download'))).toHaveLength(1);});
test('unconfirmed preparation can be abandoned before a source request exists',async({page})=>{const f=await fixture(page);f.state.filePrepareFails=true;await f.open();await f.section.getByRole('button',{name:'Prepare private file copy',exact:true}).click();await expect(f.section.getByLabel('Find attachment history patient')).toBeDisabled();await f.section.getByRole('button',{name:'Abandon file request',exact:true}).click();await page.getByRole('button',{name:'Confirm file abandonment',exact:true}).click();await expect(f.section.getByText('This file request was abandoned. It cannot be resumed.',{exact:true})).toBeVisible();await expect(f.section.getByLabel('Find attachment history patient')).toBeEnabled();expect(f.state.fileTombstone).not.toBeNull();expect(f.state.calls.some(c=>c.path==='/functions/v1/ezyvet-attachment-capture')).toBe(false);});


test('abandoned file cleanup history distinguishes receipts and unfinished attempts',async({page})=>{
 const f=await fixture(page); let older=false;
 await page.route('**/rest/v1/rpc/list_ezyvet_attachment_cleanups',async r=>{
  const body=r.request().postDataJSON(); older=!!body.p_before_id;
  const attempt={id:uid(80),request_id:body.p_id,actor_id:actor,pet_id:pet,request_hash:'a'.repeat(64),intent_hash:'b'.repeat(64),created_at:at,lease_until:'2026-09-13T12:01:30Z'};
  attempt.request_hash=f.state.fileRequest!.request.request_hash;
  await r.fulfill({json:{request_id:body.p_id,pet_id:pet,cleanups:[{attempt,receipt:older?null:{cleanup_id:attempt.id,request_id:body.p_id,actor_id:actor,intent_hash:attempt.intent_hash,verified_absent_at:'2026-09-13T12:00:01Z'},lease_active:false}],has_more:!older,next_cursor:older?null:{before_at:at,before_id:attempt.id}}});
 });
 await f.open();await f.section.getByRole('button',{name:'Prepare private file copy',exact:true}).click();
 await expect(f.section.getByRole('button',{name:'Capture file privately',exact:true})).toBeEnabled();
 await f.section.getByRole('button',{name:'Abandon file request',exact:true}).click();await page.getByRole('button',{name:'Confirm file abandonment',exact:true}).click();
 const history=f.section.getByRole('region',{name:'Temporary file cleanup history'});
 await expect(history.getByText(/Storage absence verified at/)).toBeVisible();
 await history.getByRole('button',{name:'Older cleanup attempts',exact:true}).click();
 await expect(history.getByText('Cleanup attempt ended without an absence receipt.',{exact:true})).toBeVisible();expect(older).toBe(true);
 expect(f.state.calls.some(c=>c.path==='/functions/v1/ezyvet-attachment-cleanup')).toBe(false);
});
test('unverified cleanup history never displays a deletion success',async({page})=>{
 const f=await fixture(page);await page.route('**/rest/v1/rpc/list_ezyvet_attachment_cleanups',r=>r.fulfill({status:503,json:{message:'untrusted failure'}}));
 await f.open();await f.section.getByRole('button',{name:'Prepare private file copy',exact:true}).click();await expect(f.section.getByRole('button',{name:'Capture file privately',exact:true})).toBeEnabled();await f.section.getByRole('button',{name:'Abandon file request',exact:true}).click();await page.getByRole('button',{name:'Confirm file abandonment',exact:true}).click();
 await expect(f.section.getByText('Cleanup history could not be verified. No file deletion is confirmed.',{exact:true})).toBeVisible();await expect(f.section.getByText(/Storage absence verified at/)).toHaveCount(0);
});


async function cleanupFixture(page:Page){
 const f=await fixture(page); f.state.fileReserveOnly=true;
 const state={saved:null as null|{attempt:Record<string,unknown>;receipt:Record<string,unknown>|null},lost:false,disabled:false,recoveryFails:false,calls:[] as Record<string,unknown>[]};
 await page.route('**/rest/v1/rpc/recover_ezyvet_attachment_cleanup',r=>state.recoveryFails?r.fulfill({status:503,json:{message:'synthetic unavailable'}}):r.fulfill({json:state.saved}));
 await page.route('**/rest/v1/rpc/list_ezyvet_attachment_cleanups',r=>r.fulfill({json:{request_id:r.request().postDataJSON().p_id,pet_id:pet,cleanups:state.saved?[{...state.saved,lease_active:!state.saved.receipt&&Date.parse(String(state.saved.attempt.lease_until))>Date.now()}]:[],has_more:false,next_cursor:null}}));
 await page.route('**/functions/v1/ezyvet-attachment-cleanup',r=>{
  const b=r.request().postDataJSON();state.calls.push(b);
  if(state.disabled)return r.fulfill({status:503,json:{error:'CLEANUP_DISABLED'}});
  const created=new Date(Date.now()-1000).toISOString();
  state.saved={attempt:{id:b.cleanup_id,request_id:b.request_id,actor_id:actor,pet_id:pet,request_hash:b.request_hash,intent_hash:'d'.repeat(64),created_at:created,lease_until:new Date(Date.now()+89000).toISOString()},receipt:{cleanup_id:b.cleanup_id,request_id:b.request_id,actor_id:actor,intent_hash:'d'.repeat(64),verified_absent_at:new Date().toISOString()}};
  return state.lost?r.fulfill({status:503,json:{error:'STORAGE_UNAVAILABLE'}}):r.fulfill({json:{status:'cleanup_recorded',request_id:b.request_id,cleanup_id:b.cleanup_id}});
 });
 await f.open();await f.section.getByRole('button',{name:'Prepare private file copy',exact:true}).click();await expect(f.section.getByRole('button',{name:'Capture file privately',exact:true})).toBeEnabled();await f.section.getByRole('button',{name:'Capture file privately',exact:true}).click();await expect(f.section.getByRole('button',{name:'Abandon file request',exact:true})).toBeEnabled();await f.section.getByRole('button',{name:'Abandon file request',exact:true}).click();await page.getByRole('button',{name:'Confirm file abandonment',exact:true}).click();await expect(f.section.getByRole('button',{name:'Clean up temporary file',exact:true})).toBeEnabled();return {...f,cleanup:state};
}
test('cleanup requires confirmation and recovers a lost completion reply',async({page})=>{const f=await cleanupFixture(page);f.cleanup.lost=true;await f.section.getByRole('button',{name:'Clean up temporary file',exact:true}).click();await page.getByRole('button',{name:'Keep temporary file',exact:true}).click();expect(f.cleanup.calls).toHaveLength(0);await f.section.getByRole('button',{name:'Clean up temporary file',exact:true}).click();await page.getByRole('button',{name:'Confirm temporary file cleanup',exact:true}).click();await expect(f.section.getByText(/This is a point-in-time receipt/)).toBeVisible();expect(f.cleanup.calls).toHaveLength(1);await expect(f.section.getByRole('button',{name:'Start another file request',exact:true})).toBeEnabled();});
test('disabled cleanup retains its identity for the same explicit retry',async({page})=>{const f=await cleanupFixture(page);f.cleanup.disabled=true;await f.section.getByRole('button',{name:'Clean up temporary file',exact:true}).click();await page.getByRole('button',{name:'Confirm temporary file cleanup',exact:true}).click();await expect(f.section.getByText('Temporary file cleanup is not commissioned. An administrator must finish server setup.',{exact:true})).toBeVisible();await expect(f.section.getByRole('button',{name:'Start another file request',exact:true})).toBeDisabled();f.cleanup.disabled=false;await f.section.getByRole('button',{name:'Retry original cleanup',exact:true}).click();await page.getByRole('button',{name:'Confirm temporary file cleanup',exact:true}).click();await expect(f.section.getByText(/This is a point-in-time receipt/)).toBeVisible();expect(f.cleanup.calls[0].cleanup_id).toBe(f.cleanup.calls[1].cleanup_id);});
test('cleanup reference survives reload and history repairs a lost local pointer',async({page})=>{const f=await cleanupFixture(page);await f.section.getByRole('button',{name:'Clean up temporary file',exact:true}).click();await page.getByRole('button',{name:'Confirm temporary file cleanup',exact:true}).click();await expect(f.section.getByText(/This is a point-in-time receipt/)).toBeVisible();await page.reload();await f.open();await f.section.getByRole('button',{name:'Recheck file request',exact:true}).click();await f.section.getByRole('button',{name:'Recheck cleanup attempt',exact:true}).click();await expect(f.section.getByText(/This is a point-in-time receipt/)).toBeVisible();await page.evaluate(()=>{for(const key of Object.keys(sessionStorage))if(key.startsWith('lrv-attachment-cleanup:'))sessionStorage.removeItem(key);});await page.reload();await f.open();await f.section.getByRole('button',{name:'Recheck file request',exact:true}).click();await f.section.getByRole('button',{name:/^Recover cleanup /}).click();await expect(f.section.getByText(/This is a point-in-time receipt/)).toBeVisible();expect(f.cleanup.calls).toHaveLength(1);});

test('expired cleanup attempt requires a new sweep and preserves the old reference',async({page})=>{const f=await cleanupFixture(page);f.cleanup.disabled=true;await f.section.getByRole('button',{name:'Clean up temporary file',exact:true}).click();await page.getByRole('button',{name:'Confirm temporary file cleanup',exact:true}).click();await expect(f.section.getByRole('button',{name:'Retry original cleanup',exact:true})).toBeEnabled();const b=f.cleanup.calls[0];f.cleanup.saved={attempt:{id:b.cleanup_id,request_id:b.request_id,actor_id:actor,pet_id:pet,request_hash:b.request_hash,intent_hash:'d'.repeat(64),created_at:'2026-01-01T00:00:00Z',lease_until:'2026-01-01T00:01:30Z'},receipt:null};await f.section.getByRole('button',{name:'Recheck cleanup attempt',exact:true}).click();await expect(f.section.getByRole('button',{name:'Start a new cleanup sweep',exact:true})).toBeEnabled();await expect(f.section.getByRole('button',{name:'Retry original cleanup',exact:true})).toBeDisabled();});
test('failed cleanup reference persistence sends no cleanup mutation',async({page})=>{const f=await cleanupFixture(page);await page.evaluate(()=>{const set=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key.startsWith('lrv-attachment-cleanup:'))throw new Error('synthetic unavailable');return set.call(this,key,value);};});await f.section.getByRole('button',{name:'Clean up temporary file',exact:true}).click();await page.getByRole('button',{name:'Confirm temporary file cleanup',exact:true}).click();await expect(f.section.getByText('The cleanup reference could not be saved or verified. No cleanup was started.',{exact:true})).toBeVisible();expect(f.cleanup.calls).toHaveLength(0);await expect(f.section.getByRole('button',{name:'Start another file request',exact:true})).toBeEnabled();});


async function capturedFixture(page:Page){const f=await fixture(page);await f.open();await f.section.getByRole('button',{name:'Prepare private file copy',exact:true}).click();await expect(f.section.getByRole('button',{name:'Capture file privately',exact:true})).toBeEnabled();await f.section.getByRole('button',{name:'Capture file privately',exact:true}).click();await expect(f.section.getByRole('button',{name:'Verify original for inspection',exact:true})).toBeEnabled();return f;}
test('captured original is verified before a private download is offered',async({page})=>{const f=await capturedFixture(page);await expect(f.section.getByRole('link',{name:'Download verified original',exact:true})).toHaveCount(0);await f.section.getByRole('button',{name:'Verify original for inspection',exact:true}).click();const link=f.section.getByRole('link',{name:'Download verified original',exact:true});await expect(link).toHaveAttribute('href',/^blob:/);await expect(link).toHaveAttribute('download','ezyvet-attachment-701.pdf');await expect(f.section.getByText(/this check is not approval/)).toBeVisible();});
for(const failure of ['originalCorrupt','originalDenied'] as const)test(`original inspection withholds download after ${failure}`,async({page})=>{const f=await capturedFixture(page);f.state[failure]=true;await f.section.getByRole('button',{name:'Verify original for inspection',exact:true}).click();await expect(f.section.getByText('The private original could not be verified. No download is available. Recheck the captured file and your access before trying again.',{exact:true})).toBeVisible();await expect(f.section.getByRole('link',{name:'Download verified original',exact:true})).toHaveCount(0);});
test('a failed original recheck removes the previous verified download',async({page})=>{const f=await capturedFixture(page);await f.section.getByRole('button',{name:'Verify original for inspection',exact:true}).click();await expect(f.section.getByRole('link',{name:'Download verified original',exact:true})).toBeVisible();f.state.originalCorrupt=true;await f.section.getByRole('button',{name:'Verify original for inspection',exact:true}).click();await expect(f.section.getByRole('link',{name:'Download verified original',exact:true})).toHaveCount(0);});

test('leaving the page clears the verified original and revokes its object URL',async({page})=>{const f=await capturedFixture(page);await f.section.getByRole('button',{name:'Verify original for inspection',exact:true}).click();const link=f.section.getByRole('link',{name:'Download verified original',exact:true});await expect(link).toBeVisible();const href=await link.getAttribute('href');await page.evaluate(()=>window.dispatchEvent(new Event('pagehide')));await expect(link).toHaveCount(0);expect(await page.evaluate(async url=>{try{await fetch(url!);return false;}catch{return true;}},href)).toBe(true);});

test('approval history keeps latest identity while paging through prior decisions',async({page})=>{
 const f=await capturedFixture(page);
 await page.route('**/rest/v1/rpc/list_ezyvet_attachment_record_versions',r=>{
  const b=r.request().postDataJSON(),old=!!b.p_before_id,request=f.state.fileRequest!.request;
  const {attachment_metadata: _metadata,...source}=request.source_context;void _metadata;
  const record={id:uid(old?90:91),actor_id:actor,request_id:request.id,pet_id:pet,animal_link_id:link,source_origin:'https://api.trial.ezyvet.com',source_site_uid:'synthetic-site',attachment_external_id:'701',request_hash:request.request_hash,capture_hash:'e'.repeat(64),source_context:source,title:old?'Original decision':'<script>Reviewed correction</script>',review_reason:'Synthetic original inspection',previous_record_id:old?null:uid(90),version:old?1:2,entry_method:'staff_reviewed_api_attachment_v1',record_hash:'f'.repeat(64),created_at:at};
  return r.fulfill({json:{request_id:request.id,pet_id:pet,animal_link_id:link,attachment_external_id:'701',latest_record_id:uid(91),records:[record],has_more:!old,next_cursor:old?null:{before_at:at,before_id:record.id}}});
 });
 const history=f.section.getByRole('region',{name:'API attachment approval history'});await history.getByRole('button',{name:'Recheck approval history',exact:true}).click();await expect(history.getByText('Version 2: <script>Reviewed correction</script>',{exact:true})).toBeVisible();await expect(history.getByText(/Latest saved approval/)).toBeVisible();await history.getByRole('button',{name:'Older approval versions',exact:true}).click();await expect(history.getByText('Version 1: Original decision',{exact:true})).toBeVisible();await expect(history.getByText(/Earlier approval version/)).toBeVisible();await expect(history.locator('script')).toHaveCount(0);
});
test('wrong-patient approval history is withheld',async({page})=>{const f=await capturedFixture(page);await page.route('**/rest/v1/rpc/list_ezyvet_attachment_record_versions',r=>r.fulfill({json:{request_id:f.state.fileRequest!.request.id,pet_id:uid(999),animal_link_id:link,attachment_external_id:'701',latest_record_id:null,records:[],has_more:false,next_cursor:null}}));const history=f.section.getByRole('region',{name:'API attachment approval history'});await history.getByRole('button',{name:'Recheck approval history',exact:true}).click();await expect(history.getByText('Approval history could not be verified. Recheck before making a review decision.',{exact:true})).toBeVisible();});
