import { test, expect, type Page } from "@playwright/test";
// Heterogeneous synthetic server envelopes model the strict public RPC boundary.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
interface Row { [key: string]: any }
const actor="10000000-0000-4000-8000-000000000001",pet="20000000-0000-4000-8000-000000000001",client="30000000-0000-4000-8000-000000000001",authId="60000000-0000-4000-8000-000000000001",draftId="70000000-0000-4000-8000-000000000001",hash="a".repeat(64),time="2026-09-16T10:00:00.123456Z";
async function fixture(page:Page,options:{lostCreate?:boolean;failQueue?:boolean}={}){
 const user={id:actor,aud:"authenticated",role:"authenticated",email:"synthetic@example.test",app_metadata:{provider:"email",providers:["email"]},user_metadata:{},created_at:time},exp=Math.floor(Date.now()/1000)+3600;
 const session={access_token:`eyJhbGciOiJIUzI1NiJ9.${Buffer.from(JSON.stringify({sub:actor,exp,role:"authenticated",aud:"authenticated"})).toString("base64url")}.synthetic`,refresh_token:"synthetic",token_type:"bearer",expires_in:3600,expires_at:exp,user};
 await page.addInitScript(s=>localStorage.setItem("sb-127-auth-token",JSON.stringify(s)),session);
 const state={refill:null as Row|null,events:[] as Row[],calls:[] as Row[],receipts:new Map<string,Row>(),lostCreate:!!options.lostCreate,wrongRecovery:false,failQueue:!!options.failQueue,stale:false,householdMoved:false,authorizationState:"active",legacyMore:false,legacyCalls:[] as Row[]};
 const usage={version:1,native_fill_accounting:"not_implemented",dispensed_quantity:null,used_fill_slots:null,remaining_quantity:null,external_fulfillment:"unknown"};
 const disclosure=()=>({version:1,refill:state.refill,head_id:state.events[0]?.id,current_household_id:state.householdMoved?actor:client,household_matches:!state.householdMoved,authorization_status:state.refill?.authorization_id?{authorization_id:authId,authorization_hash:hash,checked_at:time,state:state.authorizationState,reason:state.authorizationState==="active"?null:"DVM reviewed replacement",replacement_id:state.authorizationState==="replaced"?draftId:null}:null,authorization_usage:state.refill?.authorization_id?usage:null,operational_only:true});
 const linkContext=()=>({version:1,refill_id:state.refill!.id,refill_version:state.refill!.version,pet_id:pet,client_id:client,patient_version:1,authorization_id:authId,authorization_hash:hash,authorization_head_id:null,authorization_head_version:0,authorization_state:state.authorizationState});
 const legacy=(id:string,created=time)=>({record:{id,client_id:client,pet_id:pet,conversation_id:null,medication_name:"Historic requested medication",original_message:"Historic caller message",status:"APPROVED",assigned_to_id:null,notes:"Unverified original note",requested_at:created,approved_at:created,ready_at:null,picked_up_at:null,created_at:created,updated_at:created},client_name:"Synthetic Household",pet_name:"Juniper",assigned_to_name:null,read_only:true,clinical_authority:"unverified"});
 await page.route("**/*",r=>new URL(r.request().url()).origin==="http://127.0.0.1:8080"?r.continue():r.abort());
 await page.route("http://127.0.0.1:54321/**",async r=>{const url=new URL(r.request().url()),path=url.pathname;
  if(path==="/auth/v1/token")return r.fulfill({json:session});if(path==="/auth/v1/user")return r.fulfill({json:user});
  if(path==="/rest/v1/profiles")return r.fulfill({json:[{id:actor,first_name:"Synthetic",last_name:"Staff",full_name:"Synthetic Staff",role:"STAFF",is_active:true}]});if(path==="/rest/v1/user_roles")return r.fulfill({json:[{role:"STAFF"}]});
  if(path==="/rest/v1/rpc/search_clients")return r.fulfill({json:[{id:client,full_name:"Synthetic Household",first_name:"Synthetic",last_name:"Household"}]});
  if(path==="/rest/v1/clients")return r.fulfill({json:{id:client,full_name:"Synthetic Household",primary_email:"client@example.test",primary_phone:null}});
  if(path==="/rest/v1/pets"){const p={id:pet,client_id:client,name:"Juniper",species:"Dog"};return r.fulfill({json:url.searchParams.has('id')?p:[p]});}
  if(path==="/rest/v1/rpc/list_native_refills"){if(state.failQueue)return r.fulfill({status:503,json:{message:"synthetic unavailable"}});return r.fulfill({json:{version:1,refills:state.refill?[disclosure()]:[],has_more:false,next_cursor:null}});}
  if(path==="/rest/v1/rpc/read_native_refill")return r.fulfill({json:state.refill?disclosure():null});
  if(path==="/rest/v1/rpc/list_native_refill_events")return r.fulfill({json:{version:1,refill_id:state.refill!.id,pet_id:pet,events:state.events,has_more:false,next_cursor:null}});
  if(path==="/rest/v1/rpc/list_legacy_refills"){const input=r.request().postDataJSON();state.legacyCalls.push(input);const records=state.legacyMore&&!input.p_before_id?Array.from({length:20},(_,i)=>legacy(`80000000-0000-4000-8000-${String(30-i).padStart(12,'0')}`)):[legacy('80000000-0000-4000-8000-000000000001',state.legacyMore?'2026-09-15T10:00:00Z':time)];return r.fulfill({json:{version:1,records,has_more:state.legacyMore&&!input.p_before_id,next_cursor:state.legacyMore&&!input.p_before_id?{before_at:time,before_id:records.at(-1)!.record.id}:null}});}
  if(path==="/rest/v1/rpc/list_native_prescription_drafts")return r.fulfill({json:{version:1,pet_id:pet,drafts:[{id:draftId,pet_id:pet,client_id:client,version:1,status:"signed",authorization_id:authId,fields:{encounter_id:null,medication:{name:"Signed test medication",strength:"Authored strength",form:"Tablet",directions:"Clinician instructions",route:"Authored route"},quantity_per_fill:"2.500",unit:"tablet",refills_authorized:0,fulfillment_mode:"external_pharmacy",product_id:null,starts_on:"2026-09-16",expires_on:"2026-09-30"},created_by:actor,updated_by:actor,created_at:time,updated_at:time}],has_more:false,next_cursor:null}});
  if(path==="/rest/v1/rpc/preview_native_refill_link")return r.fulfill({json:{version:1,actor_id:actor,context:linkContext(),context_hash:hash,observed_at:time}});
  if(path==="/rest/v1/rpc/recover_native_refill_operation"){const receipt=state.receipts.get(r.request().postDataJSON().p_id);return r.fulfill({json:state.wrongRecovery&&receipt?{...receipt,actor_id:client}:receipt??null});}
  if(path==="/rest/v1/rpc/create_native_refill"||path==="/rest/v1/rpc/transition_native_refill"){
   const input=r.request().postDataJSON(),q=input.p_request;state.calls.push({path,...input});if(state.receipts.has(input.p_id))return r.fulfill({json:state.receipts.get(input.p_id)});if(state.stale)return r.fulfill({status:409,json:{code:"40001",message:"changed request"}});
   const create=path.endsWith('/create_native_refill'),before=state.refill?structuredClone(state.refill):null,version=create?1:before!.version+1,stamp=`2026-09-16T10:00:00.${String(version).padStart(6,'0')}Z`,action=create?'create':q.action,context=action==='link'?linkContext():null;
   const after=create?{id:q.refill_id,pet_id:q.pet_id,client_id:q.client_id,version:1,state:"open",medication_requested:q.medication_requested,requester_note:q.requester_note,channel:q.channel,assigned_to:null,authorization_id:null,authorization_hash:null,created_by:actor,created_at:stamp,updated_by:actor,updated_at:stamp}:{...before,version,updated_by:actor,updated_at:stamp,...(action==='assign'?{assigned_to:q.assigned_to}:action==='link'?{authorization_id:q.authorization_id,authorization_hash:hash}:action==='close'?{state:'closed'}:{state:'denied'})};
   const event={version:1,id:input.p_id,refill_id:q.refill_id,revision:version,action,actor_id:actor,reason:q.reason,prior_event_id:state.events[0]?.id??null,before,after,link_context:context,created_at:stamp};state.refill=after;state.events.unshift(event);const receipt={version:1,id:input.p_id,actor_id:actor,request:q,request_hash:hash,result:event,created_at:stamp};state.receipts.set(input.p_id,receipt);if(create&&state.lostCreate){state.lostCreate=false;return r.abort();}return r.fulfill({json:receipt});
  }
  return r.fulfill({json:[]});
 });
 await page.goto('/hub/tools/refills');return state;
}
async function intake(page:Page){await page.getByRole('button',{name:'New refill intake',exact:true}).click();await page.getByRole('button',{name:'Synthetic Household',exact:true}).click();await expect(page.getByLabel('Patient (required)',{exact:true})).toHaveValue('');await page.getByLabel('Patient (required)',{exact:true}).selectOption(pet);await page.getByLabel('Medication requested (not a prescription)',{exact:true}).fill('Requested test medication');await page.getByLabel('Request channel',{exact:true}).selectOption('phone');await page.getByLabel('Intake reason',{exact:true}).fill('Staff recorded client phone request');await page.getByRole('button',{name:'Review refill intake',exact:true}).click();await page.getByRole('checkbox',{name:/I reviewed the exact patient/}).check();await page.getByRole('button',{name:'Save reviewed refill intake',exact:true}).click();}
async function action(page:Page,label:string,reason:string){await page.getByRole('button',{name:label,exact:true}).click();await page.getByLabel('Reason for this operational action',{exact:true}).fill(reason);}
async function commitAction(page:Page){await page.getByRole('button',{name:'Review operational action',exact:true}).click();await page.getByRole('checkbox',{name:/I reviewed the exact patient/}).check();await page.getByRole('button',{name:'Save reviewed operational action',exact:true}).click();}
test('intake requires explicit patient; attribution, assignment and close are operational only',async({page})=>{const state=await fixture(page);await intake(page);await expect(page.getByRole('button',{name:'Assign request',exact:true})).toBeEnabled();await expect(page.getByRole('heading',{name:'Juniper · Synthetic Household',exact:true})).toBeVisible();expect(state.calls[0].p_request).toMatchObject({pet_id:pet,client_id:client,channel:'phone'});await action(page,'Assign request','Assigning to available staff');await page.getByLabel('Assign to',{exact:true}).selectOption(actor);await commitAction(page);await expect(page.getByRole('button',{name:'Close operational request',exact:true})).toBeEnabled();expect(state.refill!.assigned_to).toBe(actor);await action(page,'Close operational request','Client withdrew request');await commitAction(page);await expect(page.getByRole('region',{name:'Refill request workspace'})).toContainText('Requested test medication · closed');expect(state.events.map(e=>e.action)).toEqual(['close','assign','create']);await expect(page.getByRole('button',{name:'Assign request',exact:true})).toHaveCount(0);});
test('lost intake response locks selectors and navigation, rejects wrong recovery then restores exact request',async({page})=>{const state=await fixture(page,{lostCreate:true});await intake(page);await expect(page.getByRole('button',{name:'Recover original operation',exact:true})).toBeVisible();await expect(page.getByLabel('Patient (required)',{exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'New refill intake',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Clients',exact:true}).click();await expect(page.getByRole('alertdialog')).toHaveCount(1);await page.getByRole('button',{name:'Keep editing',exact:true}).click();state.wrongRecovery=true;await page.getByRole('button',{name:'Recover original operation',exact:true}).click();await expect(page.getByText(/Recovery could not be confirmed/)).toBeVisible();state.wrongRecovery=false;await page.getByRole('button',{name:'Recover original operation',exact:true}).click();await expect(page.getByRole('button',{name:'Assign request',exact:true})).toBeEnabled();expect(state.calls).toHaveLength(1);});
test('exact linked order discloses replacement without following it or granting allowance',async({page})=>{const state=await fixture(page);await intake(page);await action(page,'Link exact signed order','Associate exact existing order for review');await page.getByRole('button',{name:'Load signed order choices',exact:true}).click();await page.getByLabel('Exact signed authorization',{exact:true}).selectOption(authId);await page.getByRole('button',{name:'Review operational action',exact:true}).click();await expect(page.getByLabel('Reviewed refill link')).toContainText('not clinical approval');await page.getByRole('checkbox',{name:/I reviewed the exact patient/}).check();await page.getByRole('button',{name:'Save reviewed operational action',exact:true}).click();await expect(page.getByRole('region',{name:'Refill request workspace'})).toContainText(`Exact linked order: ${authId}`);state.authorizationState='replaced';await page.getByRole('button',{name:'Refresh request evidence',exact:true}).click();await expect(page.getByRole('region',{name:'Refill request workspace'})).toContainText('is not automatically linked');expect(state.refill!.authorization_id).toBe(authId);expect(state.calls[1].p_request).toMatchObject({action:'link',authorization_id:authId,expected_link_context_hash:hash});});
test('legacy approval stays read-only and paginated with no clinical status notification',async({page})=>{const state=await fixture(page);state.legacyMore=true;await page.getByRole('button',{name:'Show legacy history',exact:true}).click();const history=page.getByRole('region',{name:'Earlier refill history'});await expect(history.getByText('Legacy recorded status: APPROVED · unverified',{exact:true})).toHaveCount(20);await expect(history.getByRole('combobox')).toHaveCount(0);await expect(history.getByRole('button',{name:/Notify|Compose/})).toHaveCount(0);await page.getByRole('button',{name:'Load more legacy records',exact:true}).click();await expect(history.getByText('Legacy recorded status: APPROVED · unverified',{exact:true})).toHaveCount(21);expect(state.legacyCalls[1].p_before_id).toBe('80000000-0000-4000-8000-000000000011');expect(state.calls).toHaveLength(0);});
test('native query failure is explicit and retry does not claim an empty queue',async({page})=>{const state=await fixture(page,{failQueue:true});await expect(page.getByText('Current refill requests could not be loaded. This is not an empty queue.')).toBeVisible({timeout:15000});await expect(page.getByText('No current refill requests recorded.')).toHaveCount(0);state.failQueue=false;await page.getByRole('button',{name:'Retry current requests',exact:true}).click();await expect(page.getByText('No current refill requests recorded.')).toBeVisible();});
test('stale operational write retains reason and household change permits closing but not linking',async({page})=>{const state=await fixture(page);await intake(page);await action(page,'Assign request','Retain this explanation');state.stale=true;await commitAction(page);await expect(page.getByText(/The server rejected this operation/)).toBeVisible();await expect(page.getByLabel('Reason for this operational action',{exact:true})).toHaveValue('Retain this explanation');await page.getByRole('button',{name:'Discard operational review',exact:true}).click();state.stale=false;state.householdMoved=true;await page.getByRole('button',{name:'Refresh request evidence',exact:true}).click();await expect(page.getByRole('button',{name:'Assign request',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Link exact signed order',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Close operational request',exact:true})).toBeEnabled();});

test('neutral client draft makes no status claim and blocks competing intake',async({page})=>{await fixture(page);await intake(page);await expect(page.getByRole('button',{name:'Compose neutral client update',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Compose neutral client update',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.locator('button').filter({hasText:/^New refill intake$/})).toBeDisabled();const body=page.getByRole('dialog').locator('textarea');await expect(body).toHaveValue('We are following up on your medication request. Please reply if you have additional information for the practice team.');});
