import { test, expect, type Page } from "@playwright/test";
// Synthetic RPC server deliberately accepts heterogeneous request/receipt envelopes.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
interface RpcRow { [key: string]: any }
const actor="10000000-0000-4000-8000-000000000001",pet="20000000-0000-4000-8000-000000000001",client="30000000-0000-4000-8000-000000000001",hash="a".repeat(64),time="2026-09-16T10:00:00.123456Z";
async function fixture(page:Page, options:{lostSave?:boolean;admin?:boolean;dvm?:boolean}={}) {
  const user={id:actor,aud:"authenticated",role:"authenticated",email:"synthetic@example.test",app_metadata:{provider:"email",providers:["email"]},user_metadata:{},created_at:time};const exp=Math.floor(Date.now()/1000)+3600;
  const session={access_token:`eyJhbGciOiJIUzI1NiJ9.${Buffer.from(JSON.stringify({sub:actor,exp,role:"authenticated",aud:"authenticated"})).toString("base64url")}.synthetic`,refresh_token:"synthetic",token_type:"bearer",expires_in:3600,expires_at:exp,user};
  await page.addInitScript(s=>localStorage.setItem("sb-127-auth-token",JSON.stringify(s)),session);
  const state={lostSave:!!options.lostSave,lostChange:false,printReads:0,wrongPrint:false,events:[] as RpcRow[],authorizations:new Map<string,RpcRow>(),calls:[] as RpcRow[],drafts:[] as RpcRow[],receipts:new Map<string,RpcRow>(),authorization:null as RpcRow|null,stale:false,wrongRecovery:false,recoveryAbsent:false,patientMissing:false,patientReads:0,configured:!options.admin,config:null as RpcRow|null};
  const configFields={active:true,license_number:"DVM-123",license_state:"CO",license_expires_on:"2027-09-16",practice_name:"Living Room Vet",practice_address:"2619 Spruce Street",practice_phone:null,clinical_review_note:"Synthetic reviewed evidence"};
  if(state.configured)state.config={user_id:actor,version:1,fields:configFields,configured_by:actor,configured_at:time};
  const patient={id:pet,client_id:client,name:"Juniper",species:"Dog",breed:null,dob:null,birth_date_precision:"unknown",color:null,microchip_id:null,sex:"unknown",neuter_status:"unknown",archived_at:null,deceased_at:null,weight_lbs:null,allergies:null,version:1};
  const makeContext=(draft:RpcRow)=>({version:1,draft:structuredClone(draft),patient:{id:pet,version:1,name:"Juniper",species:"Dog"},household:{id:client,version:1,name:"Synthetic Household",address:"10 Test Street"},prescriber:{user_id:actor,name:"Dr. Synthetic",configuration:state.config},product:null,alerts:{source_hash:hash,snapshot:{schema_version:1,pet_id:pet,patient_version:1,important_problems:[{id:"60000000-0000-4000-8000-000000000001",version:1,title:"Vaccine reaction",notes:"Clinician review required",status:"active",importance:"high",onset_date:null,updated_at:time}],legacy_allergies:{text:"Existing allergy note",provenance:"Existing patient record"}}}});
  const makeAuthorization=(input:RpcRow,context:RpcRow)=>{const request=input.p_request,f=context.draft.fields,p=state.config!.fields;return {id:input.p_id,pet_id:pet,client_id:client,draft_id:request.draft_id,draft_version:request.expected_version,signed_by:actor,signed_at:time,context_hash:hash,context,authorization_hash:hash,artifact:{schema_version:1,authorization_id:input.p_id,authorization_hash:hash,signed_at:time,signature_name:"Dr. Synthetic",patient:{id:pet,name:"Juniper",species:"Dog"},household:{id:client,name:"Synthetic Household",address:"10 Test Street"},prescriber:{user_id:actor,name:"Dr. Synthetic",license_number:p.license_number,license_state:p.license_state,practice_name:p.practice_name,practice_address:p.practice_address,practice_phone:null},medication:f.medication,quantity_per_fill:f.quantity_per_fill,unit:f.unit,refills_authorized:f.refills_authorized,fulfillment_mode:f.fulfillment_mode,starts_on:f.starts_on,expires_on:f.expires_on}};};
  const usage=()=>({version:1,native_fill_accounting:"not_implemented",dispensed_quantity:null,used_fill_slots:null,remaining_quantity:null,external_fulfillment:"unknown"});
  const currentStatus=(id:string)=>{const event=state.events.find(e=>e.authorization_id===id);return {authorization_id:id,authorization_hash:hash,checked_at:time,state:event?(event.action==="cancel"?"cancelled":"replaced"):"active",reason:event?.reason??null,replacement_id:event?.replacement_id??null};};
  const changeContext=(id:string)=>{const current=state.events.find(e=>e.authorization_id===id),c=makeContext(state.drafts[0]);return {version:1,authorization:state.authorizations.get(id),head:{id:current?.id??null,version:current?.event_version??0,state:currentStatus(id).state,reason:current?.reason??null,replacement_id:current?.replacement_id??null},patient_current:{id:pet,client_id:client,version:1,archived_at:null,deceased_at:null},prescriber:c.prescriber,alerts:c.alerts,usage:usage()};};
  await page.route("**/*",r=>new URL(r.request().url()).origin==="http://127.0.0.1:8080"?r.continue():r.abort());
  await page.route("http://127.0.0.1:54321/**",async r=>{
    const path=new URL(r.request().url()).pathname;
    if(path==="/auth/v1/token")return r.fulfill({json:session});if(path==="/auth/v1/user")return r.fulfill({json:user});
    if(path==="/rest/v1/profiles")return r.fulfill({json:[{id:actor,first_name:"Dr.",last_name:"Synthetic",full_name:"Dr. Synthetic",role:options.admin?"ADMIN":"DVM",is_active:true}]});
    if(path==="/rest/v1/user_roles")return r.fulfill({json:[...(options.dvm===false?[]:[{role:"DVM"}]),{role:options.admin?"ADMIN":"STAFF"}]});
    if(path==="/rest/v1/pets"){state.patientReads++;return r.fulfill({json:state.patientMissing?null:patient});}
    if(path==="/rest/v1/clients")return r.fulfill({json:{id:client,full_name:"Synthetic Household",housecall_address:"10 Test Street"}});
    if(path==="/rest/v1/rpc/list_native_prescribers")return r.fulfill({json:{version:1,entries:[{user_id:actor,name:"Dr. Synthetic",active_staff:true,has_dvm_role:options.dvm!==false,configuration:state.config,eligible:!!state.config&&options.dvm!==false}],has_more:false,next_after_id:null}});
    if(path==="/rest/v1/rpc/list_native_prescription_drafts")return r.fulfill({json:{version:1,pet_id:pet,drafts:state.drafts,has_more:false,next_cursor:null}});
    if(path==="/rest/v1/rpc/read_native_prescription_draft")return r.fulfill({json:state.drafts.find(d=>d.id===r.request().postDataJSON().p_id)??null});
    if(path==="/rest/v1/rpc/read_native_prescription_authorization")return r.fulfill({json:state.authorizations.get(r.request().postDataJSON().p_id)??null});
    if(path==="/rest/v1/rpc/recover_native_prescription_operation"){const saved=state.receipts.get(r.request().postDataJSON().p_id)??null;return r.fulfill({json:state.recoveryAbsent?null:saved&&state.wrongRecovery?{...saved,actor_id:client}:saved});}
    if(path==="/rest/v1/rpc/preview_native_prescription_sign"){const d=state.drafts[0];return r.fulfill({json:{version:1,actor_id:actor,draft_id:d.id,pet_id:pet,context:makeContext(d),context_hash:hash,observed_at:time}});}
    if(path==="/rest/v1/rpc/read_native_prescription_status"){const id=r.request().postDataJSON().p_authorization_id,e=state.events.find(e=>e.authorization_id===id);return r.fulfill({json:{version:1,pet_id:pet,status:currentStatus(id),head_id:e?.id??null,head_version:e?.event_version??0,usage:usage()}});}
    if(path==="/rest/v1/rpc/list_native_prescription_events"){const id=r.request().postDataJSON().p_authorization_id;return r.fulfill({json:{version:1,pet_id:pet,authorization_id:id,events:state.events.filter(e=>e.authorization_id===id),has_more:false,next_cursor:null}});}
    if(path==="/rest/v1/rpc/read_native_prescription_print_v2"){state.printReads++;const id=r.request().postDataJSON().p_authorization_id,artifact=structuredClone(state.authorizations.get(id)!.artifact);if(state.wrongPrint)artifact.quantity_per_fill="999.000";return r.fulfill({json:{version:2,prescription:artifact,status:currentStatus(id),dispense:null,correction_summary:{"version":1,"event_count":0,"affected_dispense_count":0,"heads_hash":"4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945"},dispense_corrections:null,original_pickup:null}});}
    if(path==="/rest/v1/rpc/preview_native_prescription_cancel"||path==="/rest/v1/rpc/preview_native_prescription_replacement"){const input=r.request().postDataJSON(),prior=changeContext(input.p_authorization_id);return r.fulfill({json:{version:1,actor_id:actor,pet_id:pet,context:path.endsWith("_cancel")?prior:{version:1,prior,new_sign:makeContext(state.drafts.find(d=>d.id===input.p_draft_id)!),new_sign_context_hash:hash},context_hash:hash,observed_at:time}});}
    if(path==="/rest/v1/rpc/cancel_native_prescription"||path==="/rest/v1/rpc/replace_native_prescription"){
      const input=r.request().postDataJSON(),request=input.p_request;state.calls.push({path,...input});if(state.receipts.has(input.p_id))return r.fulfill({json:state.receipts.get(input.p_id)});if(state.stale)return r.fulfill({status:409,json:{code:"40001",message:"Context changed"}});
      const action=path.endsWith("/cancel_native_prescription")?"cancel":"replace",prior=changeContext(request.authorization_id),replacementContext=action==="replace"?makeContext(state.drafts.find(d=>d.id===request.draft_id)!):null;
      const event={version:1,id:input.p_id,authorization_id:request.authorization_id,authorization_hash:hash,pet_id:pet,action,prior_event_id:request.expected_event_id,event_version:1,replacement_id:action==="replace"?input.p_id:null,actor_id:actor,reason:request.reason,reviewed_context:action==="cancel"?prior:{version:1,prior,new_sign:replacementContext,new_sign_context_hash:hash},reviewed_context_hash:hash,reconciliation:action==="replace"?request.reconciliation:null,record_hash:hash,created_at:time};
      let result:RpcRow=event;if(replacementContext){const next=makeAuthorization(input,replacementContext);state.authorizations.set(next.id,next);state.authorization=next;state.drafts=state.drafts.map(d=>d.id===request.draft_id?{...d,status:"signed",authorization_id:next.id}:d);result={authorization:next,event};}
      state.events.push(event);const receipt={version:1,id:input.p_id,actor_id:actor,operation:action,pet_id:pet,request,request_hash:hash,result,created_at:time};state.receipts.set(input.p_id,receipt);if(state.lostChange){state.lostChange=false;return r.abort();}return r.fulfill({json:receipt});
    }
    if(["save_native_prescription_draft","sign_native_prescription","configure_native_prescriber"].some(name=>path.endsWith(`/${name}`))){
      const input=r.request().postDataJSON();state.calls.push({path,...input});if(state.receipts.has(input.p_id))return r.fulfill({json:state.receipts.get(input.p_id)});const request=input.p_request;let result:RpcRow,operation:string;
      if(path.endsWith("/save_native_prescription_draft")){operation="save_draft";result={id:request.draft_id,pet_id:pet,client_id:client,version:(request.expected_version??0)+1,fields:{...request.fields,quantity_per_fill:Number(request.fields.quantity_per_fill).toFixed(3)},status:"draft",authorization_id:null,created_by:actor,updated_by:actor,created_at:time,updated_at:time};state.drafts=[result,...state.drafts.filter(d=>d.id!==result.id)];}
      else if(path.endsWith("/configure_native_prescriber")){operation="configure_prescriber";result={user_id:request.user_id,version:(request.expected_version??0)+1,fields:request.fields,configured_by:actor,configured_at:time};state.config=result;}
      else {if(state.stale)return r.fulfill({status:409,json:{code:"40001",message:"Patient alerts changed"}});operation="sign";result=makeAuthorization(input,makeContext(state.drafts.find(d=>d.id===request.draft_id)!));state.authorization=result;state.authorizations.set(result.id,result);state.drafts=state.drafts.map(d=>d.id===request.draft_id?{...d,status:"signed",authorization_id:input.p_id}:d);}
      const receipt={version:1,id:input.p_id,actor_id:actor,operation,pet_id:operation==="configure_prescriber"?null:pet,request,request_hash:hash,result,created_at:time};state.receipts.set(input.p_id,receipt);
      if(state.lostSave&&operation==="save_draft"){state.lostSave=false;return r.abort();}return r.fulfill({json:receipt});
    }
    return r.fulfill({json:[]});
  });
  await page.goto(`/hub/patient/${pet}`);await expect(page.getByRole("button",{name:"New prescription draft"})).toBeEnabled();return state;
}
async function fill(page:Page){await page.getByRole("button",{name:"New prescription draft"}).click();await page.getByLabel("Dispensing destination",{exact:true}).selectOption("external_pharmacy");for(const [label,value]of [["Medication name","Authored medication"],["Strength","Authored strength"],["Dosage form","Tablet"],["Route","Authored route"],["Maximum quantity per fill","2.5"],["Quantity unit","tablet"],["Additional refills authorized","0"],["Start date","2026-09-16"],["Authorization expiry date","2026-09-30"],["Directions / SIG","Clinician authored directions"]])await page.getByRole("region",{name:"Native prescription editor"}).getByLabel(label,{exact:true}).fill(value);}
async function save(page:Page){await page.getByRole("button",{name:"Review draft save"}).click();await page.getByRole("checkbox",{name:/I reviewed the draft values/}).check();await page.getByRole("button",{name:"Save reviewed draft",exact:true}).click();}
test("native patient draft and DVM signing require reviewed alerts and preserve signed history",async({page})=>{const state=await fixture(page);await fill(page);await save(page);await expect(page.getByText("The saved operation was confirmed.",{exact:true}).first()).toBeVisible();expect(state.calls).toHaveLength(1);await page.getByRole("button",{name:"Review for signature"}).click();await expect(page.getByRole("region",{name:"Prescription signing review"})).toContainText("Vaccine reaction");await expect(page.getByRole("button",{name:"Sign reviewed prescription"})).toBeDisabled();await page.getByRole("checkbox",{name:/I reviewed this prescription, patient identity/}).check();await page.getByRole("button",{name:"Sign reviewed prescription"}).click();await expect(page.getByRole("region",{name:"Signed prescription snapshot"})).toContainText("Historical evidence only");expect(state.calls).toHaveLength(2);expect(state.calls[1].p_request).toMatchObject({pet_id:pet,expected_version:1,expected_context_hash:hash,signature_name:"Dr. Synthetic",attest_review:true});});
test("lost draft response preserves exact recovery identity and combined patient leave guard",async({page})=>{const state=await fixture(page,{lostSave:true});await fill(page);await save(page);await expect(page.getByRole("button",{name:"Recover original operation",exact:true})).toBeVisible();await expect(page.getByLabel("Medication name",{exact:true})).toBeDisabled();await expect(page.getByRole("button",{name:"Refresh prescription history"})).toBeDisabled();await page.getByRole("link",{name:"Synthetic Household",exact:true}).click();await expect(page.getByRole("alertdialog")).toHaveCount(1);await page.getByRole("button",{name:"Keep editing",exact:true}).click();state.wrongRecovery=true;await page.getByRole("button",{name:"Recover original operation",exact:true}).click();await expect(page.getByText(/Recovery could not be confirmed/)).toBeVisible();state.wrongRecovery=false;await page.getByRole("button",{name:"Recover original operation",exact:true}).click();await expect(page.getByText("The original saved operation was recovered.")).toBeVisible();expect(state.calls).toHaveLength(1);await expect(page.getByLabel("Maximum quantity per fill",{exact:true})).toHaveValue("2.500");});
test("stale sign context returns to retained draft and requires a new clinical review",async({page})=>{const state=await fixture(page);await fill(page);await save(page);await page.getByRole("button",{name:"Review for signature"}).click();await page.getByRole("checkbox",{name:/I reviewed this prescription, patient identity/}).check();state.stale=true;await page.getByRole("button",{name:"Sign reviewed prescription"}).click();await expect(page.getByText(/The server rejected this operation/)).toBeVisible();await expect(page.getByLabel("Medication name",{exact:true})).toHaveValue("Authored medication");expect(state.authorization).toBeNull();await expect(page.getByRole("button",{name:"Review for signature"})).toBeEnabled();});
test("administrator configuration requires explicit credentials and attestation; ADMIN alone cannot sign",async({page})=>{const state=await fixture(page,{admin:true,dvm:false});await page.getByLabel("Prescriber",{exact:true}).selectOption(actor);await expect(page.getByRole("checkbox",{name:/I reviewed these credentials/})).not.toBeChecked();for(const [label,value]of [["License number","Reviewed license"],["Licensing state / jurisdiction","CO"],["License expiration","2027-01-01"],["Practice name","Living Room Vet"],["Practice address","2619 Spruce Street"],["Credential and clinical workflow review evidence","Dr. Edler reviewed clinical forms and credential evidence"]])await page.getByLabel(label,{exact:true}).fill(value);await expect(page.getByRole("button",{name:"Review configuration",exact:true})).toBeDisabled();await page.getByRole("checkbox",{name:/I reviewed these credentials/}).check();await page.getByRole("button",{name:"Review configuration",exact:true}).click();await page.getByRole("button",{name:"Save reviewed configuration",exact:true}).click();await expect(page.getByRole("button",{name:"New prescription draft"})).toBeEnabled();expect(state.calls[0].p_request).toMatchObject({user_id:actor,attest_review:true,fields:{active:false}});await fill(page);await save(page);await expect(page.getByRole("button",{name:"Review for signature"})).toBeDisabled();});

test("absent recovery permits only the same frozen request retry",async({page})=>{const state=await fixture(page,{lostSave:true});await fill(page);await save(page);await expect(page.getByRole("button",{name:"Recover original operation",exact:true})).toBeVisible();state.recoveryAbsent=true;await page.getByRole("button",{name:"Recover original operation",exact:true}).click();await expect(page.getByText(/The original transaction may still be running/)).toBeVisible();await page.getByRole("button",{name:"Retry identical operation",exact:true}).click();await expect(page.getByText("The saved operation was confirmed.",{exact:true}).first()).toBeVisible();expect(state.calls).toHaveLength(2);expect(state.calls[1]).toEqual(state.calls[0]);expect(state.drafts).toHaveLength(1);});
async function sign(page:Page){await page.getByRole("button",{name:"Review for signature"}).click();await page.getByRole("checkbox",{name:/I reviewed this prescription, patient identity/}).check();await page.getByRole("button",{name:"Sign reviewed prescription"}).click();await expect(page.getByRole("button",{name:"Cancel this authorization",exact:true})).toBeEnabled();}
test("cancellation uses reviewed evidence, preserves recovery and prints a fresh cancellation notice",async({page})=>{const state=await fixture(page);await fill(page);await save(page);await sign(page);const original=structuredClone(state.authorization);await page.getByRole("button",{name:"Preview fresh order copy",exact:true}).click();await expect(page.frameLocator('iframe[title="Native prescription order copy"]').locator("body")).toContainText("Authored medication");expect(state.printReads).toBe(1);await page.getByRole("button",{name:"Cancel this authorization",exact:true}).click();await page.getByLabel("Clinical reason for cancellation",{exact:true}).fill("DVM reviewed cancellation");await page.getByRole("button",{name:"Load current evidence for review"}).click();await expect(page.getByRole("region",{name:"Frozen authorization change evidence"})).toContainText("Vaccine reaction");await expect(page.getByRole("button",{name:"Confirm authorization cancellation"})).toBeDisabled();await page.getByRole("checkbox",{name:/I reviewed the exact order, reason/}).check();state.lostChange=true;await page.getByRole("button",{name:"Confirm authorization cancellation"}).click();await expect(page.getByRole("button",{name:"Recover original operation",exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"New prescription draft"})).toBeDisabled();await expect(page.getByRole("button",{name:"Print fresh order copy"})).toBeDisabled();await page.getByRole("button",{name:"Recover original operation",exact:true}).click();await expect(page.getByRole("region",{name:"Prescription lifecycle"})).toContainText("CANCELLED");expect(state.authorization).toEqual(original);await page.getByRole("button",{name:"Preview fresh order copy",exact:true}).click();await expect(page.frameLocator('iframe[title="Native prescription order copy"]').locator("body")).toContainText("CANCELLED");expect(state.printReads).toBe(2);const [copy]=await Promise.all([page.waitForEvent("popup"),page.getByRole("button",{name:"Print fresh order copy",exact:true}).click()]);await expect(copy.locator("body")).toContainText("CANCELLED");expect(state.printReads).toBe(3);await copy.close();expect(state.calls.filter(c=>c.path.endsWith('/cancel_native_prescription'))).toHaveLength(1);});
test("replacement reviews explicit new allowance and external reconciliation in one atomic request",async({page})=>{const state=await fixture(page);await fill(page);await save(page);await sign(page);const originalId=state.authorization!.id;await fill(page);await page.getByLabel("Medication name",{exact:true}).fill("Independently authored replacement");await save(page);await page.getByRole("button",{name:"View signed snapshot",exact:true}).click();await page.getByRole("button",{name:"Replace with an unsigned draft"}).click();await page.getByLabel("Clinical reason for replacement",{exact:true}).fill("DVM reviewed therapy change");await page.getByLabel("Unsigned replacement draft",{exact:true}).selectOption(state.drafts.find(d=>d.status==='draft')!.id);for(const [label,value]of [["Review of unavailable native fill accounting","No native fill ledger available; reviewed manually"],["External-use review evidence","DVM documented prior external use review"],["Reason for the deliberately new quantity and refill allowance","New independently authored allowance was clinically reviewed"]])await page.getByLabel(label,{exact:true}).fill(value);await page.getByRole("checkbox",{name:/I reviewed prior use/}).check();await page.getByRole("button",{name:"Load current evidence for review"}).click();await expect(page.getByText(/An external order requires manually reconciled external use/)).toBeVisible();await page.getByLabel("External fulfillment review status",{exact:true}).selectOption("reconciled");await page.getByRole("checkbox",{name:/I reviewed prior use/}).check();await page.getByRole("button",{name:"Load current evidence for review"}).click();await expect(page.getByRole("region",{name:"Frozen authorization change evidence"})).toContainText("Independently authored replacement");await expect(page.getByRole("region",{name:"Frozen authorization change evidence"})).toContainText("remaining allowance: unavailable");await page.getByRole("checkbox",{name:/I reviewed both orders/}).check();await page.getByRole("button",{name:"Sign replacement and retire original"}).click();await expect(page.getByRole("region",{name:"Signed prescription snapshot"})).toContainText("Independently authored replacement");expect(state.calls.filter(c=>c.path.endsWith('/sign_native_prescription'))).toHaveLength(1);const replacements=state.calls.filter(c=>c.path.endsWith('/replace_native_prescription'));expect(replacements).toHaveLength(1);expect(replacements[0].p_request).toMatchObject({authorization_id:originalId,expected_event_id:null,reason:"DVM reviewed therapy change",reconciliation:{external_use_status:"reconciled",attest_review:true}});expect(state.events[0].replacement_id).toBe(state.authorization!.id);});
test("order copy refuses a mismatched frozen artifact",async({page})=>{const state=await fixture(page);await fill(page);await save(page);await sign(page);state.wrongPrint=true;await page.getByRole("button",{name:"Preview fresh order copy",exact:true}).click();await expect(page.getByText(/Current authorization evidence could not be confirmed/)).toBeVisible();await expect(page.locator('iframe[title="Native prescription order copy"]')).toHaveCount(0);expect(state.printReads).toBe(1);});
