import {test} from "node:test";
import assert from "node:assert/strict";
import {createHash} from "node:crypto";
import {createExternalRecordVerificationHandler,safeExternalRecord} from "../../supabase/functions/_shared/external-record-verification.ts";
import {hashPrivateLabResponse} from "../../supabase/functions/_shared/lab-report-verification.ts";
import type {ExternalRecordDependencies,PrivateExternalDocument} from "../../supabase/functions/_shared/external-record-verification.ts";
const id=(n:number)=>`10000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
const actor=id(1),receiptId=id(2),doc=id(3),pet=id(4),source=id(5),origin="https://thelivingroom.vet",at="2026-09-13T00:00:00.123Z",bytes=new TextEncoder().encode("%PDF-1.7\nSynthetic private report\n%%EOF"),digest=createHash("sha256").update(bytes).digest("hex");
const document:PrivateExternalDocument={id:doc,version:2,bucket:"patient-documents",file_path:`${actor}/${pet}/${doc}/original`,mime_type:"application/pdf",file_size:bytes.length};
function fixture(){
 const args={p_id:receiptId,p_animal_link_id:source,p_expected_pet_version:1,p_document_id:doc,p_document_version:2,p_export_reference:"Synthetic export",p_received_at:at,p_previous_record_id:null,p_review_reason:"Reviewed source mapping"};
 const row={id:receiptId,actor_id:actor,animal_link_id:source,pet_id:pet,pet_version:1,document_id:doc,document_version:2,source_origin:"https://api.trial.ezyvet.com",source_site_uid:"Synthetic site",source_animal_id:"77",export_reference:args.p_export_reference,received_at:at,previous_record_id:null,review_reason:args.p_review_reason,mime_type:document.mime_type,file_size:bytes.length,receipt_hash:"a".repeat(64),entry_method:"staff_reviewed_manual_export_v1",created_at:at};
 let saved:Record<string,unknown>|null=null,loseStage=false,loseCapture=false,deny=false,captureError="",downloads=0;
 const calls:string[]=[],captures:Record<string,unknown>[]=[];
 const deps:ExternalRecordDependencies={enabled:true,origin,authenticate:async()=>({actorId:actor,db:{rpc:async(name,input)=>{calls.push(name);if(deny)return {data:null,error:{code:"42501"}};if(name==="recover_external_record_receipt")return {data:saved,error:null};assert.equal(name,"stage_external_record_receipt");if(JSON.stringify(input)!==JSON.stringify(args))return {data:null,error:{code:"23505"}};saved??={receipt:row,capture:null,record:null};return {data:row,error:loseStage?new Error("Lost stage ACK"):null};}}}),
 service:{rpc:async(name,input)=>{calls.push(name);if(name==="external_record_capture_context")return {data:{receipt:row,document,capture:null},error:null};assert.equal(name,"capture_external_record_bytes");captures.push(input);if(captureError)return {data:null,error:{code:captureError}};saved={receipt:row,capture:{receipt_id:receiptId,actor_id:actor,receipt_hash:row.receipt_hash,document_version:2,content_sha256:input.p_content_sha256,file_size:bytes.length,mime_type:document.mime_type,capture_hash:"b".repeat(64),captured_at:at},record:null};return {data:null,error:loseCapture?new Error("Lost capture ACK"):null};}},
 download:async d=>{downloads++;assert.deepEqual(d,document);return new Response(bytes,{headers:{"Content-Type":"application/pdf","Content-Length":String(bytes.length)}});},
 };
 const send=(action="prepare",patch:Record<string,unknown>={})=>createExternalRecordVerificationHandler(deps)(new Request(origin,{method:"POST",headers:{Origin:origin,Authorization:"Bearer synthetic","Content-Type":"application/json"},body:JSON.stringify({action,...(action==="prepare"?args:{p_receipt_id:receiptId}),...patch})}));
 return {deps,send,calls,captures,get downloads(){return downloads;},get saved(){return saved;},set loseStage(v:boolean){loseStage=v;},set loseCapture(v:boolean){loseCapture=v;},set deny(v:boolean){deny=v;},set captureError(v:string){captureError=v;}};
}
test("service captures SHA256 of exact private bytes without exposing path or report",async()=>{const f=fixture();const r=await f.send();assert.equal(r.status,200);const body=await r.json();assert.equal(body.capture.content_sha256,digest);assert.equal(f.captures[0].p_expected_receipt_hash,"a".repeat(64));assert.equal(f.downloads,1);assert.doesNotMatch(JSON.stringify(body),/file_path|patient-documents|%PDF|private report/);assert.equal(r.headers.get("Cache-Control"),"no-store, private");});
test("captured exact retry and paused recovery require no file retrieval",async()=>{const f=fixture();await f.send();f.deps.download=async()=>{throw new Error("Should not download");};assert.equal((await f.send()).status,200);f.deps.enabled=false;assert.equal((await f.send("recover")).status,200);assert.equal((await f.send()).status,503);});
test("SQL changed timestamp rejection cannot be overridden by captured success",async()=>{const f=fixture();await f.send();const micro=at.replace("Z","001Z");assert.equal(Date.parse(micro),Date.parse(at));assert.equal((await f.send("prepare",{p_received_at:micro})).status,409);assert.equal(f.downloads,1);});
test("lost stage ACK retains receipt and never starts capture",async()=>{const f=fixture();f.loseStage=true;const r=await f.send();assert.equal(r.status,202);assert.equal((await r.json()).receipt_id,receiptId);assert.equal(f.downloads,0);f.loseStage=false;assert.equal((await f.send()).status,200);});
test("lost capture ACK recovers exact committed digest",async()=>{const f=fixture();f.loseCapture=true;assert.equal((await f.send()).status,200);assert.equal(f.downloads,1);});
test("document void/version conflict after download returns conflict with no invented capture",async()=>{const f=fixture();f.captureError="40001";assert.equal((await f.send()).status,409);assert.equal(f.saved?.capture,null);});
test("wrong MIME, short/oversized body and declared-size mismatch do not capture",async()=>{for(const response of [new Response(bytes,{headers:{"Content-Type":"text/html"}}),new Response(bytes.slice(1),{headers:{"Content-Type":"application/pdf"}}),new Response(new Uint8Array(bytes.length+1),{headers:{"Content-Type":"application/pdf"}}),new Response(bytes,{headers:{"Content-Type":"application/pdf","Content-Length":"999"}})]){const f=fixture();f.deps.download=async()=>response;assert.equal((await f.send()).status,202);assert.equal(f.captures.length,0);}});
test("redirect and oversized metadata fail before reading body",async()=>{await assert.rejects(()=>hashPrivateLabResponse(Response.redirect("https://other.test"),document));await assert.rejects(()=>hashPrivateLabResponse(new Response(bytes,{headers:{"Content-Type":"application/pdf"}}),{...document,file_size:20971521}));});
test("active admin SQL denial and caller-provided hash are rejected before download",async()=>{const f=fixture();f.deny=true;assert.equal((await f.send()).status,404);assert.equal((await f.send("prepare",{p_content_sha256:digest})).status,400);assert.equal(f.downloads,0);});
test("source context cannot substitute a different private object",async()=>{const f=fixture(),original=f.deps.service.rpc;f.deps.service.rpc=async(name,args)=>{const result=await original(name,args);if(name==="external_record_capture_context")return {...result,data:{...(result.data as object),document:{...document,file_path:`${actor}/${pet}/${id(9)}/original`}}};return result;};assert.equal((await f.send()).status,202);assert.equal(f.downloads,0);});
test("safe recovery binds original actor and strips extra service fields",async()=>{const f=fixture();await f.send();assert.throws(()=>safeExternalRecord(f.saved,id(9),receiptId));assert.equal("file_path"in safeExternalRecord({...f.saved,file_path:"private"},actor,receiptId)!,false);});
test("approved record recovery binds mapping, source intent and exact capture",async()=>{
 const f=fixture();await f.send();const envelope=f.saved!;const r=envelope.receipt as Record<string,unknown>,c=envelope.capture as Record<string,unknown>;
 const record={id:id(10),actor_id:actor,receipt_id:receiptId,animal_link_id:r.animal_link_id,pet_id:pet,pet_version:1,document_id:doc,document_version:2,receipt_hash:r.receipt_hash,capture_hash:c.capture_hash,export_reference:r.export_reference,previous_record_id:null,version:1,kind:"original",review_reason:r.review_reason,created_at:at};
 assert.equal(safeExternalRecord({...envelope,record},actor,receiptId)?.record?.id,id(10));
 assert.throws(()=>safeExternalRecord({...envelope,record:{...record,animal_link_id:id(9)}},actor,receiptId));
 assert.throws(()=>safeExternalRecord({...envelope,record:{...record,review_reason:"Changed"}},actor,receiptId));
});
