import type { IssuedCertificate } from "../../src/hub/features/certificates/print.ts";
export const certificate: IssuedCertificate = {
  id: "test-certificate",
  issued_at: "2026-09-12T19:00:00+00:00",
  signature_name: "Dr Test",
  attestation:
    "I reviewed this complete certificate and its due date, confirm this was a rabies vaccine administered by me or under my supervision by the named administrator trained in vaccine storage, handling, administration and adverse-event management, and explicitly sign this certificate.",
  replaces_id: null,
  snapshot: {
    schema_version: 1,
    kind: "rabies",
    patient: {
      id: "pet",
      name: "<script>alert(1)</script>",
      species: "Dog",
      breed: "Mixed",
      dob: "2020-01-01",
      birth_date_precision: "estimated",
      color: "Brown",
      sex: "female",
      neuter_status: "neutered",
      microchip_id: null,
    },
    owner: {
      id: "owner",
      name: "Owner & Family",
      address: "123 Test St",
      phone: "3035550100",
    },
    issuer: {
      user_id: "vet",
      full_name: "Dr Test",
      license_number: "TEST-ONLY",
      license_state: "CO",
      practice_name: "Synthetic practice",
      practice_address: "2619 Spruce Street",
      practice_phone: "3035550199",
    },
    vaccinations: [
      {
        treatment_id: "dose",
        historical: false,
        product_name: "Test vaccine",
        manufacturer: "Frozen manufacturer",
        lot_number: "LOT-1",
        lot_expires_on: "2027-01-01",
        dose: "1 mL",
        route: "SC",
        site: "Recorded site",
        veterinarian: "Dr Test",
        veterinarian_license: "TEST-ONLY",
        administered_on: "2026-09-12",
        next_due_on: "2027-09-12",
        source: "",
        age_at_administration: "6 years 8 mons 11 days",
      },
    ],
    details: {
      administrator: "Actual administrator",
      rabies_tag_number: "TAG-1",
      usda_duration: "1 year",
      vaccine_type: "Killed virus",
      size_description: "20–50 lb",
      initial_or_booster: "initial",
      owner_business_phone_unavailable: true,
      supervision_attested: true,
    },
  },
};
