const actor = "10000000-0000-4000-8000-000000000001",
  pet = "20000000-0000-4000-8000-000000000001",
  client = "30000000-0000-4000-8000-000000000001",
  draftId = "40000000-0000-4000-8000-000000000001",
  operationId = "50000000-0000-4000-8000-000000000001";
const time = "2026-09-16T10:00:00.123456Z",
  hash = "a".repeat(64);
const fields = {
  encounter_id: null,
  medication: {
    name: "Authored medication",
    strength: "Authored strength",
    form: "Tablet",
    directions: "Clinician authored directions",
    route: "Authored route",
  },
  quantity_per_fill: "2.5",
  unit: "tablet",
  refills_authorized: 0,
  fulfillment_mode: "practice_stock",
  product_id: "80000000-0000-4000-8000-000000000001",
  starts_on: "2026-09-16",
  expires_on: "2026-09-30",
};
const draft = () => ({
  id: draftId,
  pet_id: pet,
  client_id: client,
  version: 1,
  fields: { ...structuredClone(fields), quantity_per_fill: "2.500" },
  status: "draft",
  authorization_id: null,
  created_by: actor,
  updated_by: actor,
  created_at: time,
  updated_at: time,
});
const configuration = () => ({
  user_id: actor,
  version: 1,
  fields: {
    active: true,
    license_number: "Reviewed credential",
    license_state: "CO",
    license_expires_on: "2027-01-01",
    practice_name: "Living Room Vet",
    practice_address: "2619 Spruce Street",
    practice_phone: null,
    clinical_review_note: "Explicit commissioning evidence",
  },
  configured_by: actor,
  configured_at: time,
});
const context = () => ({
  version: 1,
  draft: draft(),
  patient: { id: pet, version: 1, name: "Patient", species: "Canine" },
  household: {
    id: client,
    version: 1,
    name: "Household",
    address: "Reviewed address",
  },
  prescriber: {
    user_id: actor,
    name: "Dr. Test",
    configuration: configuration(),
  },
  product: {
    id: fields.product_id,
    version: 1,
    name: "Stock medication",
    unit: "tablet",
  },
  alerts: {
    source_hash: hash,
    snapshot: {
      schema_version: 1,
      pet_id: pet,
      patient_version: 1,
      important_problems: [],
      legacy_allergies: { text: null, provenance: "Existing patient record" },
    },
  },
});
const signed = () => {
  const c = context(),
    f = c.draft.fields,
    p = c.prescriber.configuration.fields;
  return {
    id: operationId,
    pet_id: pet,
    client_id: client,
    draft_id: draftId,
    draft_version: 1,
    signed_by: actor,
    signed_at: time,
    context_hash: hash,
    context: c,
    authorization_hash: hash,
    artifact: {
      schema_version: 1,
      authorization_id: operationId,
      authorization_hash: hash,
      signed_at: time,
      signature_name: c.prescriber.name,
      patient: { id: pet, name: c.patient.name, species: c.patient.species },
      household: {
        id: client,
        name: c.household.name,
        address: c.household.address,
      },
      prescriber: {
        user_id: actor,
        name: c.prescriber.name,
        license_number: p.license_number,
        license_state: p.license_state,
        practice_name: p.practice_name,
        practice_address: p.practice_address,
        practice_phone: null,
      },
      medication: f.medication,
      quantity_per_fill: f.quantity_per_fill,
      unit: f.unit,
      refills_authorized: f.refills_authorized,
      fulfillment_mode: f.fulfillment_mode,
      starts_on: f.starts_on,
      expires_on: f.expires_on,
    },
  };
};
export { actor, pet, client, time, hash, signed };
export const id = (n: number) =>
  `90000000-0000-4000-8000-${String(n).padStart(12, "0")}`;
export const initialUsage = () => ({
  version: 2,
  native_fill_accounting: "implemented",
  dispensed_quantity: "0.000",
  used_fill_slots: 0,
  remaining_quantity: "2.500",
  forfeited_quantity: "0.000",
  unopened_fill_slots: 1,
  allowance_basis: "native_practice_stock",
  open_slot: null,
  fulfillment_head: { event_id: null, version: 0 },
  external_fulfillment: "unknown",
});
export const head = () => ({
  id: signed().id,
  hash,
  head_id: null,
  head_version: 0,
  state: "active",
});
export const target = () => ({
  authorization_id: signed().id,
  pet_id: pet,
  slot_index: 0,
  expected_slot_version: null,
  invoice_id: id(2),
  quantity: "1",
  allocations: [{ lot_id: id(3), quantity: "1" }],
  refill: null,
});
export const dispenseContext = () => ({
  version: 1,
  target: target(),
  denver_date: "2026-09-16",
  authorization: head(),
  signed_artifact: signed().artifact,
  patient: {
    id: pet,
    version: 1,
    client_id: client,
    archived_at: null,
    deceased_at: null,
  },
  household: { id: client, version: 1 },
  alerts: context().alerts,
  slot: null,
  previous_slot: null,
  usage: initialUsage(),
  invoice: {
    id: id(2),
    client_id: client,
    version: 1,
    status: "draft",
    currency: "usd",
    existing_items_hash: hash,
    existing_items_total_cents: "0",
  },
  product: {
    id: fields.product_id,
    version: 1,
    active: true,
    kind: "medication",
    name: "Stock medication",
    unit: "tablet",
    unit_price_cents: "100",
  },
  lots: [
    {
      id: id(3),
      product_id: fields.product_id,
      lot_number: "LOT-1",
      expires_on: "2026-09-16",
      location: "Clinic",
      balance: "10.000",
      quantity: "1.000",
    },
  ],
  refill: null,
  charge: {
    quantity: "1.000",
    unit_price_cents: "100",
    amount_cents: "100",
    projected_invoice_total_cents: "100",
  },
});
export const slot = () => ({
  id: id(4),
  authorization_id: signed().id,
  index: 0,
  version: 1,
  maximum_quantity: "2.500",
  dispensed_quantity: "1.000",
  remaining_quantity: "1.500",
  state: "open",
  closure_kind: null,
  opened_by: actor,
  opened_at: time,
  closed_by: null,
  closed_at: null,
  close_reason: null,
});
export const usedUsage = () => ({
  ...initialUsage(),
  dispensed_quantity: "1.000",
  used_fill_slots: 1,
  remaining_quantity: "1.500",
  unopened_fill_slots: 0,
  open_slot: { id: id(4), index: 0, version: 1, remaining_quantity: "1.500" },
  fulfillment_head: { event_id: id(1), version: 1 },
});
export const dispense = () => ({
  version: 1,
  id: id(1),
  authorization_id: signed().id,
  authorization_hash: hash,
  pet_id: pet,
  client_id: client,
  slot_id: id(4),
  slot_index: 0,
  slot_version_before: null,
  slot_version_after: 1,
  actor_id: actor,
  quantity: "1.000",
  unit: "tablet",
  reason: "Dispense reviewed",
  dispensed_at: time,
  reviewed_context: dispenseContext(),
  reviewed_context_hash: hash,
  allocations: [{ lot_id: id(3), quantity: "1.000", movement_id: id(5) }],
  invoice_id: id(2),
  invoice_item_id: id(6),
  invoice_version_before: 1,
  invoice_version_after: 2,
  amount_cents: "100",
  refill_id: null,
  refill_event_id: null,
  artifact: {
    id: id(1),
    authorization_id: signed().id,
    authorization_hash: hash,
    fill_index: 0,
    quantity: "1.000",
    unit: "tablet",
    dispensed_at: time,
    recorded_by: { user_id: actor, name: "Staff name" },
    invoice_id: id(2),
    lots: [
      {
        id: id(3),
        number: "LOT-1",
        expires_on: "2026-09-16",
        quantity: "1.000",
      },
    ],
  },
  artifact_hash: hash,
});
export const operation = () => ({
  id: id(1),
  kind: "dispense",
  payload: {
    ...target(),
    expected_context_hash: hash,
    reason: "Dispense reviewed",
    attest_alert_review: true,
    attest_dispense_review: true,
  },
});
export const receipt = () => ({
  version: 1,
  id: id(1),
  actor_id: actor,
  operation: "dispense",
  request: operation().payload,
  request_hash: hash,
  result: { dispense: dispense(), slot: slot(), refill_event: null },
  created_at: time,
});
export const closeOperation = () => ({
  id: id(7),
  kind: "close_slot",
  payload: {
    authorization_id: signed().id,
    pet_id: pet,
    slot_index: 0,
    expected_slot_version: 1,
    expected_context_hash: hash,
    reason: "Remainder forfeited",
    attest_forfeit: true,
  },
});
export const closure = () => ({
  version: 1,
  id: id(7),
  authorization_id: signed().id,
  pet_id: pet,
  slot_id: id(4),
  actor_id: actor,
  reason: "Remainder forfeited",
  forfeited_quantity: "1.500",
  before: slot(),
  after: {
    ...slot(),
    version: 2,
    remaining_quantity: "0.000",
    state: "closed",
    closure_kind: "forfeited",
    closed_by: actor,
    closed_at: time,
    close_reason: "Remainder forfeited",
  },
  reviewed_context: {
    version: 1,
    authorization: head(),
    slot: slot(),
    usage: usedUsage(),
  },
  reviewed_context_hash: hash,
  created_at: time,
});
export const pickupOperation = () => ({
  id: id(8),
  kind: "pickup",
  payload: {
    authorization_id: signed().id,
    pet_id: pet,
    dispense_id: id(1),
    expected_context_hash: hash,
    recipient_name: "Alex",
    recipient_relationship: "Owner",
    reason: "Physical handoff recorded",
    attest_handoff: true,
    refill_close: null,
  },
});
export const pickup = () => ({
  version: 1,
  id: id(8),
  authorization_id: signed().id,
  pet_id: pet,
  dispense_id: id(1),
  actor_id: actor,
  recipient_name: "Alex",
  recipient_relationship: "Owner",
  reason: "Physical handoff recorded",
  reviewed_context: {
    version: 1,
    authorization: head(),
    dispense: dispense(),
    existing_pickup_id: null,
    refill: null,
  },
  reviewed_context_hash: hash,
  refill_id: null,
  refill_event_id: null,
  picked_up_at: time,
});
