import { useState } from "react";
import { Link } from "react-router-dom";
import { useQueryClient } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/hub/contexts/auth-context";
import { usePageTitle } from "@/hooks/use-page-title";
import { PageHeader } from "@/hub/components/shared/PageHeader";
import { useLegacyRefills, useRefills, useRefillIdentity } from "@/hub/hooks/use-refills";
import { NativeRefillEditor } from "@/hub/features/refills/NativeRefillEditor";
import type { NativeRefillRead } from "@/hub/features/refills/refill-api";
import { useUnsavedChanges } from "@/hub/features/clinical/use-unsaved-changes";
import { SendToClientDialog } from "@/hub/components/shared/SendToClientDialog";
export default function RefillsPage() { const { user } = useAuth(); usePageTitle("Refills"); return user ? <RefillQueue key={user.id} actor={user.id} /> : null; }
function RefillQueue({ actor }: { actor: string }) {
  const [dirty, setDirty] = useState(false), [newSequence, setNewSequence] = useState(0), [selection, setSelection] = useState<NativeRefillRead | "new" | null>(null), [legacyOpen, setLegacyOpen] = useState(false), [notify, setNotify] = useState<NativeRefillRead | null>(null);
  const queue = useRefills(actor, !dirty), legacy = useLegacyRefills(actor, legacyOpen && !dirty), queryClient = useQueryClient();
  const navigationGuard = useUnsavedChanges(dirty), rows = queue.data?.pages.flatMap(page => page.refills) ?? [], oldRows = legacy.data?.pages.flatMap(page => page.records) ?? [];
  return <section className="mx-auto w-full max-w-5xl space-y-5 p-4 md:p-6" aria-label="Refill requests">
    {navigationGuard}
    <PageHeader title="Refill requests" description="Track requests separately from prescribing and dispensing." actions={<Button disabled={dirty || !!notify} onClick={() => { setNewSequence(n => n + 1); setSelection("new"); }}>New refill intake</Button>} />
    {selection && <NativeRefillEditor key={selection === "new" ? `new-${newSequence}` : selection.refill.id} actor={actor} disabled={!!notify} initial={selection === "new" ? null : selection} onDirtyChange={setDirty} onSaved={() => { void queryClient.invalidateQueries({ queryKey: ["native-refills", actor] }); }} onClose={() => setSelection(null)} />}
    <section className="space-y-3" aria-label="Current refill queue"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-lg font-semibold">Current refill requests</h2><Button variant="outline" disabled={dirty || queue.isFetching} onClick={() => void queue.refetch()}>Refresh current requests</Button></div>
      {queue.isLoading && <p role="status">Loading current requests…</p>}{queue.isError && <div role="alert"><p>Current refill requests could not be loaded. This is not an empty queue.</p><Button variant="outline" disabled={dirty || queue.isFetching} onClick={() => void queue.refetch()}>Retry current requests</Button></div>}{!queue.isLoading && !queue.isError && !rows.length && <p>No current refill requests recorded.</p>}
      {rows.map(row => <RefillQueueCard key={row.refill.id} actor={actor} row={row} disabled={dirty || !!notify} onOpen={() => setSelection(row)} onNotify={() => setNotify(row)} />)}
      {queue.hasNextPage && <Button variant="outline" disabled={dirty || queue.isFetching} onClick={() => void queue.fetchNextPage()}>Load more current requests</Button>}
    </section>
    <section className="space-y-3" aria-label="Earlier refill history"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-lg font-semibold">Earlier refill history</h2><Button variant="outline" disabled={dirty || !!notify} onClick={() => setLegacyOpen(!legacyOpen)}>{legacyOpen ? "Hide legacy history" : "Show legacy history"}</Button></div><p className="text-sm text-muted-foreground">Read-only, unverified records. Historical approval, ready and pickup statuses are preserved as recorded; they do not establish clinical authority, inventory use or handoff.</p>
      {legacyOpen && <>{legacy.isLoading && <p role="status">Loading legacy history…</p>}{legacy.isError && <div role="alert"><p>Earlier refill history could not be loaded.</p><Button variant="outline" disabled={dirty || legacy.isFetching} onClick={() => void legacy.refetch()}>Retry legacy history</Button></div>}{!legacy.isLoading && !legacy.isError && !oldRows.length && <p>No legacy refill records returned.</p>}{oldRows.map(({ record, client_name, pet_name, assigned_to_name }) => <article key={record.id} className="space-y-2 rounded-md border p-4"><h3 className="font-medium">{record.medication_name || "Medication not recorded"}</h3><p className="text-sm">{client_name || record.client_id} · {pet_name || record.pet_id || "Patient not recorded"}</p><p>Legacy recorded status: {record.status} · unverified</p><p className="text-sm">Requested: {record.requested_at}{record.approved_at ? ` · recorded approval: ${record.approved_at}` : ""}{record.ready_at ? ` · recorded ready: ${record.ready_at}` : ""}{record.picked_up_at ? ` · recorded pickup: ${record.picked_up_at}` : ""}</p>{assigned_to_name && <p className="text-sm">Recorded assignee: {assigned_to_name}</p>}{record.notes && <p className="whitespace-pre-wrap text-sm">{record.notes}</p>}{record.original_message && <p className="whitespace-pre-wrap text-sm">Original message: {record.original_message}</p>}<p className="break-all text-xs text-muted-foreground">Legacy reference {record.id}. No conversion to a signed order has occurred.</p></article>)}{legacy.hasNextPage && <Button variant="outline" disabled={dirty || legacy.isFetching} onClick={() => void legacy.fetchNextPage()}>Load more legacy records</Button>}</>}
    </section>
    {notify && <SendToClientDialog clientId={notify.refill.client_id} defaultSubject="Refill request follow-up" defaultBody="We are following up on your medication request. Please reply if you have additional information for the practice team." open onOpenChange={open => { if (!open) setNotify(null); }} />}
  </section>;
}

interface QueueCardProps { actor: string; row: NativeRefillRead; disabled: boolean; onOpen: () => void; onNotify: () => void }
function RefillQueueCard({ actor, row, disabled, onOpen, onNotify }: QueueCardProps) {
  const names = useRefillIdentity(actor, row.refill.pet_id, row.refill.client_id);
  return <article className="space-y-2 rounded-md border bg-card p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="font-medium">{names.data?.patient || "Patient name unavailable"} · {names.data?.client || "Household name unavailable"}</h3><p>{row.refill.medication_requested}</p><p className="text-sm">Operational state: {row.refill.state} · request channel: {row.refill.channel.replace("_", " ")}</p><p className="break-all text-xs text-muted-foreground">Patient {row.refill.pet_id} · saved household {row.refill.client_id} · revision {row.refill.version}</p></div><Button variant="outline" disabled={disabled} onClick={onOpen}>Open request</Button></div>{!row.household_matches && <p className="text-sm text-clinical-alert">Patient household has changed. Review before acting.</p>}{row.authorization_status ? <p className="break-all text-sm">Linked order {row.authorization_status.authorization_id}: {row.authorization_status.state}, checked {row.authorization_status.checked_at}. Linking does not grant fill authority.</p> : <p className="text-sm">No signed order linked. No approval or dispensing is implied.</p>}<div className="flex flex-wrap gap-3"><Link className="text-sm text-primary underline" to={`/hub/patient/${row.refill.pet_id}`}>Patient record</Link><Button variant="outline" disabled={disabled || !row.household_matches} onClick={onNotify}>Compose neutral client update</Button></div></article>;
}
