import { useEffect, useMemo, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";
import { useRefillApi, useRefillAssigneeSearch, useRefillClientSearch, useRefillIdentity, useRefillPatientSearch } from "@/hub/hooks/use-refills";
import { usePrescriptionOperation } from "../prescriptions/usePrescriptionOperation";
import { PrescriptionOperationControls } from "../prescriptions/PrescriptionOperationControls";
import { createPrescriptionApi } from "../prescriptions/prescription-api";
import type { PrescriptionCursor, PrescriptionDraft, PrescriptionRpc } from "../prescriptions/prescription-api";
import { refillAuthorizationIdSchema, refillCreateSchema, refillReasonSchema, refillTransitionSchema } from "./refill-api";
import type { NativeRefill, NativeRefillCursor, NativeRefillEvent, NativeRefillLinkPreview, NativeRefillRead } from "./refill-api";
interface Props { actor: string; disabled: boolean; initial: NativeRefillRead | null; onDirtyChange: (dirty: boolean) => void; onSaved: () => void; onClose: () => void }
interface ClientChoice { id: string; full_name: string }
const control = "h-10 w-full rounded-md border border-input bg-background px-3 text-sm";
export function NativeRefillEditor({ actor, disabled, initial, onDirtyChange, onSaved, onClose }: Props) {
  const api = useRefillApi(actor), alive = useRef(true), reading = useRef(false);
  const [row, setRow] = useState<NativeRefill | null>(initial?.refill ?? null), [disclosure, setDisclosure] = useState(initial);
  const [events, setEvents] = useState<NativeRefillEvent[]>([]), [historyCursor, setHistoryCursor] = useState<NativeRefillCursor | null>(null), [historyLoaded, setHistoryLoaded] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const [client, setClient] = useState<ClientChoice | null>(null), [clientSearch, setClientSearch] = useState(""), [petId, setPetId] = useState(initial?.refill.pet_id ?? ""), [petSearch, setPetSearch] = useState("");
  const [medication, setMedication] = useState(""), [note, setNote] = useState(""), [channel, setChannel] = useState(""), [reason, setReason] = useState(""), [ack, setAck] = useState(false), [refillId] = useState(() => crypto.randomUUID());
  const [action, setAction] = useState<"assign" | "link" | "close" | "deny" | null>(null), [assignedTo, setAssignedTo] = useState(""), [staffSearch, setStaffSearch] = useState("");
  const [orders, setOrders] = useState<PrescriptionDraft[]>([]), [orderCursor, setOrderCursor] = useState<PrescriptionCursor | null>(null), [ordersLoaded, setOrdersLoaded] = useState(false), [authorizationId, setAuthorizationId] = useState(""), [preview, setPreview] = useState<NativeRefillLinkPreview | null>(null);
  const patientId = row?.pet_id ?? petId;
  const prescriptionApi = useMemo(() => patientId ? createPrescriptionApi(supabase as unknown as PrescriptionRpc, actor, patientId) : null, [actor, patientId]);
  useEffect(() => { alive.current = true; return () => { alive.current = false; }; }, []);
  const operation = usePrescriptionOperation({ actor, patientId, execute: api.execute, recover: api.recover, onConfirmed: receipt => { setRow(receipt.result.after); setDisclosure(null); setEvents(previous => [receipt.result, ...previous.filter(e => e.id !== receipt.result.id)]); setAction(null); setAck(false); setPreview(null); setReason(""); onSaved(); } });
  const dirty = !row || action !== null || operation.dirty;
  useEffect(() => { onDirtyChange(dirty); }, [dirty, onDirtyChange]);
  useEffect(() => () => onDirtyChange(false), [onDirtyChange]);
  const locked = busy || operation.dirty || disabled;
  const clients = useRefillClientSearch(actor, clientSearch, !row && !locked && !client);
  const pets = useRefillPatientSearch(actor, client?.id ?? "", petSearch, !row && !locked);
  const staff = useRefillAssigneeSearch(actor, staffSearch, action === "assign" && !locked);
  const names = useRefillIdentity(actor, patientId, row?.client_id ?? client?.id ?? "");
  async function read(task: () => Promise<void>) { if (reading.current) return; reading.current = true; setBusy(true); setError(""); try { await task(); } catch { if (alive.current) setError("Refill evidence could not be loaded. Your current review is retained; retry before changing the request."); } finally { reading.current = false; if (alive.current) setBusy(false); } }
  async function refresh() { if (!row) return; await read(async () => { const [current, history] = await Promise.all([api.read(row.id, row.pet_id), api.history(row)]); if (!alive.current) return; if (!current) throw new Error("Request unavailable"); setRow(current.refill); setDisclosure(current); setEvents(history.events); setHistoryCursor(history.next_cursor); setHistoryLoaded(true); }); }
  useEffect(() => { if (!row) return; void read(async () => { const [current, history] = await Promise.all([api.read(row.id, row.pet_id), api.history(row)]); if (!alive.current) return; if (!current) throw new Error("Request unavailable"); setDisclosure(current); setEvents(history.events); setHistoryCursor(history.next_cursor); setHistoryLoaded(true); }); }, [api, row]);
  function reviewCreate() { const request = refillCreateSchema.safeParse({ refill_id: refillId, pet_id: petId, client_id: client?.id, medication_requested: medication, requester_note: note || null, channel, reason }); if (!request.success) { setError("Select a household and patient, a request channel, and enter the requested medication and intake reason. Text must be trimmed; medication is limited to 500 characters, notes to 4,000 and reason to 2,000."); return; } setError(""); setAck(false); operation.review({ id: crypto.randomUUID(), kind: "create_refill", payload: request.data }); }
  function begin(next: NonNullable<typeof action>) { operation.discard(); setAction(next); setReason(""); setAssignedTo(row?.assigned_to ?? ""); setAuthorizationId(""); setOrders([]); setOrderCursor(null); setOrdersLoaded(false); setPreview(null); setAck(false); setError(""); }
  async function loadOrders(more: boolean) { if (!prescriptionApi) return; await read(async () => { const page = await prescriptionApi.listDrafts(more ? orderCursor : null); if (!alive.current) return; setOrders(previous => more ? [...previous, ...page.drafts.filter(d => !previous.some(p => p.id === d.id))] : page.drafts); setOrderCursor(page.next_cursor); setOrdersLoaded(true); }); }
  async function reviewTransition() {
    if (!row || !action) return;
    const base = { refill_id: row.id, pet_id: row.pet_id, expected_version: row.version, action, reason, assigned_to: action === "assign" ? assignedTo || null : null, authorization_id: action === "link" ? authorizationId || null : null, expected_link_context_hash: null };
    if (!refillReasonSchema.safeParse(reason).success || (action === "link" ? !refillAuthorizationIdSchema.safeParse(authorizationId).success : !refillTransitionSchema.safeParse(base).success)) { setError("Enter an explicit trimmed reason (1–2,000 characters) and select the exact authorization for a link."); return; }
    if (action === "link") await read(async () => { const result = await api.previewLink(row, authorizationId); if (!alive.current) return; setPreview(result); setAck(false); operation.review({ id: crypto.randomUUID(), kind: "transition_refill", payload: refillTransitionSchema.parse({ ...base, expected_link_context_hash: result.context_hash }) }); });
    else { setError(""); setAck(false); operation.review({ id: crypto.randomUUID(), kind: "transition_refill", payload: base }); }
  }
  return <section className="space-y-4 rounded-md border bg-card p-4" aria-label="Refill request workspace">
    <header className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-lg font-semibold">{row ? "Refill request record" : "New refill intake"}</h2><Button variant="outline" disabled={locked} onClick={onClose}>{dirty ? "Discard local review / close" : "Close refill record"}</Button></header>
    <p className="text-sm text-muted-foreground">Operational tracking only. A request or linked signed order does not establish refill approval, remaining allowance, dispensing, readiness or pickup.</p>
    {busy && <p role="status">Loading refill evidence…</p>}{error && <p role="alert">{error}</p>}
    {!row && <fieldset disabled={locked} className="space-y-3"><legend className="sr-only">Refill intake details</legend>
      {!client ? <><Label htmlFor="refill-client-search">Find household</Label><Input id="refill-client-search" value={clientSearch} onChange={e => setClientSearch(e.target.value)} />{clients.isLoading && <p role="status">Searching households…</p>}{clients.isError && <p role="alert">Households could not be loaded. <Button variant="outline" onClick={() => void clients.refetch()}>Retry household search</Button></p>}{clients.data?.rows.map(c => <Button key={c.id} variant="outline" className="mr-2" onClick={() => { setClient(c); setPetId(""); setPetSearch(""); }}>{c.full_name}</Button>)}{clients.data?.hasMore && <p className="text-sm">First 20 households shown. Refine the search for more.</p>}{clients.data && !clients.data.rows.length && <p>No matching households.</p>}</> : <><p>Household: {client.full_name} · {client.id}</p><Button variant="outline" onClick={() => { setClient(null); setPetId(""); }}>Change household</Button><Label htmlFor="refill-pet-search">Find patient in this household</Label><Input id="refill-pet-search" value={petSearch} onChange={e => setPetSearch(e.target.value)} /><Label htmlFor="refill-patient">Patient (required)</Label><select id="refill-patient" className={control} value={petId} onChange={e => setPetId(e.target.value)}><option value="">Select a patient explicitly</option>{petId && !pets.data?.rows.some(p => p.id === petId) && <option value={petId}>Selected patient {petId}</option>}{pets.data?.rows.map(p => <option key={p.id} value={p.id}>{p.name} · {p.species}</option>)}</select>{pets.isError && <p role="alert">Patients could not be loaded. <Button variant="outline" onClick={() => void pets.refetch()}>Retry patient search</Button></p>}{pets.data?.hasMore && <p className="text-sm">First 20 patients shown. Refine the patient search for more.</p>}</>}
      <Label htmlFor="refill-medication">Medication requested (not a prescription)</Label><Input id="refill-medication" value={medication} onChange={e => setMedication(e.target.value)} /><Label htmlFor="refill-channel">Request channel</Label><select id="refill-channel" className={control} value={channel} onChange={e => setChannel(e.target.value)}><option value="">Select channel</option>{["phone", "email", "text", "in_person", "other"].map(c => <option key={c} value={c}>{c.replace("_", " ")}</option>)}</select><Label htmlFor="refill-note">Requester note (optional)</Label><Textarea id="refill-note" value={note} onChange={e => setNote(e.target.value)} /><Label htmlFor="refill-intake-reason">Intake reason</Label><Textarea id="refill-intake-reason" value={reason} onChange={e => setReason(e.target.value)} /><Button onClick={reviewCreate}>Review refill intake</Button>
    </fieldset>}
    {row && <><div className="space-y-2"><p className="font-medium">{row.medication_requested} · {row.state}</p><p className="whitespace-pre-wrap text-sm">{row.requester_note || "No requester note"}</p><p className="text-sm">{names.data?.patient || "Patient name unavailable"} · {names.data?.client || "Household name unavailable"}</p><p className="break-all text-xs text-muted-foreground">Request {row.id} · revision {row.version} · patient {row.pet_id} · saved household {row.client_id}</p><Link className="text-sm text-primary underline" to={`/hub/patient/${row.pet_id}`}>Open patient record</Link>{disclosure && disclosure.refill.version !== row.version && <p role="alert">This request changed. Refresh request evidence before preparing an action.</p>}{!disclosure && <p role="status">Current request disclosure has not been confirmed.</p>}{disclosure && !disclosure.household_matches && <p role="alert" className="text-clinical-alert">The patient now belongs to household {disclosure.current_household_id}. Assignment and linking are unavailable; closing or denying this operational request remains possible.</p>}{disclosure?.authorization_status && <div className="rounded-md border p-3"><p>Exact linked order: {disclosure.authorization_status.authorization_id}</p><p>Current linked-order status: {disclosure.authorization_status.state} · checked {disclosure.authorization_status.checked_at}</p>{disclosure.authorization_status.reason && <p>{disclosure.authorization_status.reason}</p>}{disclosure.authorization_status.replacement_id && <p>Replacement {disclosure.authorization_status.replacement_id} is not automatically linked.</p>}<p className="text-sm">Native fill accounting is unavailable; remaining quantity and used slots are unknown. External fulfillment is unknown.</p></div>}{disclosure && !row.authorization_id && <p className="text-sm">No signed order linked.</p>}</div>
      <div className="flex flex-wrap gap-2"><Button variant="outline" disabled={dirty || busy || disabled} onClick={() => void refresh()}>Refresh request evidence</Button>{row.state === "open" && !action && <>{(["assign", "link", "close", "deny"] as const).map(a => <Button key={a} variant="outline" disabled={disabled || busy || operation.dirty || !disclosure || disclosure.refill.version !== row.version || ((a === "assign" || a === "link") && !disclosure.household_matches)} onClick={() => begin(a)}>{({ assign: "Assign request", link: "Link exact signed order", close: "Close operational request", deny: "Deny operational request" })[a]}</Button>)}</>}</div>
    </>}
    {row && action && <fieldset disabled={locked} className="space-y-3"><legend className="font-medium">{action === "deny" ? "Operational denial — not a clinical prescribing decision" : `${action[0].toUpperCase()}${action.slice(1)} request`}</legend><Label htmlFor="refill-transition-reason">Reason for this operational action</Label><Textarea id="refill-transition-reason" value={reason} onChange={e => { setReason(e.target.value); setAck(false); }} />
      {action === "assign" && <><Label htmlFor="refill-staff-search">Find an assignee</Label><Input id="refill-staff-search" value={staffSearch} onChange={e => setStaffSearch(e.target.value)} /><p className="text-xs text-muted-foreground">Search shows active profiles. The server verifies current staff eligibility when saving; a profile alone does not grant access.</p><Label htmlFor="refill-assignee">Assign to</Label><select id="refill-assignee" className={control} value={assignedTo} onChange={e => setAssignedTo(e.target.value)}><option value="">Unassigned</option>{assignedTo && !staff.data?.rows.some(p => p.id === assignedTo) && <option value={assignedTo}>Selected staff ID {assignedTo}</option>}{staff.data?.rows.map(p => <option key={p.id} value={p.id}>{p.full_name}</option>)}</select>{staff.isError && <p role="alert">Staff lookup failed. <Button variant="outline" onClick={() => void staff.refetch()}>Retry staff search</Button></p>}{staff.data?.hasMore && <p>First 20 staff shown; refine the search.</p>}</>}
      {action === "link" && <><p className="text-sm">Choose the exact signed order. The server checks its current patient, household and status before linking; no refill allowance is created.</p><Button variant="outline" onClick={() => void loadOrders(false)}>Load signed order choices</Button>{ordersLoaded && !orders.some(d => d.status === "signed") && <p>No signed orders in these loaded results.</p>}<Label htmlFor="refill-authorization">Exact signed authorization</Label><select id="refill-authorization" className={control} value={authorizationId} onChange={e => setAuthorizationId(e.target.value)}><option value="">Select an exact authorization</option>{orders.filter(d => d.status === "signed").map(d => <option key={d.id} value={d.authorization_id!}>{d.fields.medication.name} · {d.fields.medication.strength} · {d.authorization_id}</option>)}</select>{orderCursor && <Button variant="outline" onClick={() => void loadOrders(true)}>Load more order choices</Button>}</>}
      <div className="flex flex-wrap gap-2"><Button onClick={() => void reviewTransition()}>Review operational action</Button><Button variant="outline" onClick={() => { setAction(null); setPreview(null); setAck(false); }}>Discard operational review</Button></div>
    </fieldset>}
    {preview && operation.dirty && <div className="space-y-2 rounded-md border p-3" aria-label="Reviewed refill link"><p>Authorization {preview.context.authorization_id} · {preview.context.authorization_state}</p><p>Patient {preview.context.pet_id} · household {preview.context.client_id}</p><p className="text-xs">Request revision {preview.context.refill_version}; patient revision {preview.context.patient_version}; authorization head {preview.context.authorization_head_id ?? "none"}, revision {preview.context.authorization_head_version}.</p><p className="text-sm">This link is operational tracking, not clinical approval or dispensing authority.</p></div>}
    {operation.state.phase === "review" && <label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={ack} onChange={e => setAck(e.target.checked)} />I reviewed the exact patient, household, request values and reason. This action does not approve or dispense medication.</label>}
    <PrescriptionOperationControls state={operation.state} error={operation.error} notice={operation.notice} commitLabel={row ? "Save reviewed operational action" : "Save reviewed refill intake"} reviewConfirmed={ack && !disabled} onCommit={operation.commit} onRecover={operation.recoverOriginal} onDiscard={() => { operation.discard(); setPreview(null); setAck(false); }} />
    {row && <section className="space-y-2" aria-label="Refill event history"><h3 className="font-medium">Attributed request history</h3>{historyLoaded && !events.length && <p>No request events were returned.</p>}{events.map(e => <div key={e.id} className="rounded-md border p-3"><p>{e.action} · revision {e.revision} · {e.created_at}</p><p className="whitespace-pre-wrap">{e.reason}</p><p className="break-all text-xs text-muted-foreground">Actor {e.actor_id} · event {e.id} · predecessor {e.prior_event_id ?? "none"}</p></div>)}{historyCursor && <Button variant="outline" disabled={dirty || busy || disabled} onClick={() => void read(async () => { const page = await api.history(row, historyCursor); if (!alive.current) return; setEvents(previous => [...previous, ...page.events.filter(e => !previous.some(p => p.id === e.id))]); setHistoryCursor(page.next_cursor); })}>Load more request events</Button>}</section>}
  </section>;
}
