import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {denverInstant,denverLocal} from '../scheduling/time';
import {Button} from '@/components/ui/button';
import {supabase} from '@/integrations/supabase/client';
import {useAuth} from '@/hub/contexts/auth-context';
import type {EstimateDraft} from './estimate-api';
import type {PrescriptionRpc} from '../prescriptions/prescription-api';
import {createEstimatePublicationApi,createEstimatePublicationEdge} from './publication-api';
import {createEstimateDecisionStaffApi,type StaffEstimateDecisionPage,type StaffEstimateDecisionState,type EstimateWitnessOperation,type EstimateWitnessReceipt} from './decision-staff-api';
import {createActorPinnedEstimateDecisionRpc} from './decision-staff-transport';
import {useEstimateWitnessOperation} from './useEstimateWitnessOperation';
interface Props {draft:EstimateDraft;onDirtyChange:(dirty:boolean)=>void}
interface StaffProps extends Props {actorId:string}
interface ReviewedDocument {url:string;filename:string;preview:Awaited<ReturnType<ReturnType<typeof createEstimateDecisionStaffApi>['preview']>>}
export function EstimateDecisionWorkspace(props:Props){const {user,profile}=useAuth();if(!user||!profile?.is_active)return <p role="alert">Active staff access is required to review estimate decisions.</p>;return <StaffWorkspace key={`${user.id}:${props.draft.id}:${props.draft.client_id}:${props.draft.pet_id}`} {...props} actorId={user.id}/>;}
function StaffWorkspace({draft,actorId,onDirtyChange}:StaffProps){
 const target=useMemo(()=>({estimate_id:draft.id,client_id:draft.client_id,pet_id:draft.pet_id}),[draft.id,draft.client_id,draft.pet_id]);
 const api=useMemo(()=>createEstimateDecisionStaffApi(createActorPinnedEstimateDecisionRpc({baseUrl:import.meta.env.VITE_SUPABASE_URL,publishableKey:import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,actorId,getSession:async()=>{const {data,error}=await supabase.auth.getSession();if(error)throw new Error('Staff session unavailable');return data.session;}}),actorId,target),[actorId,target]);
 const documents=useMemo(()=>createEstimatePublicationApi(supabase as unknown as PrescriptionRpc,actorId,target,createEstimatePublicationEdge(import.meta.env.VITE_SUPABASE_URL,async()=>{const {data,error}=await supabase.auth.getSession();if(error)throw error;if(data.session?.user.id!==actorId)throw new Error('Staff session changed');return data.session.access_token;},import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY)),[actorId,target]);
 const [state,setState]=useState<StaffEstimateDecisionState|null>(null),[history,setHistory]=useState<StaffEstimateDecisionPage|null>(null),[review,setReview]=useState<ReviewedDocument|null>(null);
 const [error,setError]=useState(''),[loading,setLoading]=useState(false),[name,setName]=useState(''),[relationship,setRelationship]=useState<'owner'|'authorized_agent'>('owner'),[choice,setChoice]=useState<'accept'|'decline'>('accept');
 const [channel,setChannel]=useState<'in_person'|'telephone'|'video'|'written'>('telephone'),[occurred,setOccurred]=useState(''),[note,setNote]=useState(''),[comment,setComment]=useState(''),[attest,setAttest]=useState(false);
 const alive=useRef(true),lock=useRef(false),url=useRef<string|null>(null),generation=useRef(0);
 const clearReview=useCallback(()=>{if(url.current)URL.revokeObjectURL(url.current);url.current=null;setReview(null);setAttest(false);},[]);
 useEffect(()=>()=>{alive.current=false;generation.current++;if(url.current)URL.revokeObjectURL(url.current);},[]);
 const refresh=useCallback(async()=>{const g=++generation.current;const [s,h]=await Promise.all([api.state(),api.history()]);if(alive.current&&g===generation.current){setState(s);setHistory(h);}},[api]);
 useEffect(()=>{void refresh().catch(()=>{if(alive.current)setError('Decision history could not be loaded. Try again.');});},[refresh]);
 const onResolved=useCallback((receipt:EstimateWitnessReceipt|null)=>{clearReview();if(receipt){setName('');setNote('');setComment('');setOccurred('');}void refresh().catch(()=>{if(alive.current)setError('Saved outcome confirmed, but current history could not be refreshed.');});},[clearReview,refresh]);
 const operation=useEstimateWitnessOperation<EstimateWitnessOperation,EstimateWitnessReceipt>({identity:`${actorId}:${draft.id}:${draft.client_id}:${draft.pet_id}`,actorId,parseOperation:api.parseOperation,execute:api.execute,recover:api.recover,close:api.close,onResolved});
 const dirty=operation.locked||loading||!!review||!!name||!!note||!!comment||!!occurred;
 useEffect(()=>{onDirtyChange(dirty);return()=>onDirtyChange(false);},[dirty,onDirtyChange]);
 async function loadDocument(){if(lock.current||operation.locked)return;lock.current=true;setLoading(true);setError('');clearReview();const g=++generation.current;
  try{const current=await api.state();if(!current.current_publication_id||current.current_decision)throw new Error('No undecided current publication');const preview=await api.preview(current.current_publication_id);const published=await documents.published(current.current_publication_id);
   if(published.status!=='open'||published.publication.content_hash!==preview.binding.content_hash||published.publication.artifact.sha256!==preview.binding.artifact_hash)throw new Error('Publication changed');
   const blob=await documents.download(published.publication.preparation_id,published.publication.artifact);if(!alive.current||g!==generation.current)return;const next=URL.createObjectURL(blob);url.current=next;setReview({url:next,filename:published.publication.artifact.filename,preview});setState(current);
  }catch{if(alive.current)setError('The exact current published document could not be reviewed. It may be decided, expired or replaced. Recover any earlier request separately.');}finally{lock.current=false;if(alive.current)setLoading(false);}
 }
 function save(){if(!review||!attest||operation.locked||loading)return;try{const q:EstimateWitnessOperation=api.parseOperation({id:crypto.randomUUID(),kind:'record_witnessed_estimate_decision',payload:{decision:{binding:review.preview.binding,grant_id:null,expected_publication_head:review.preview.publication_head,choice,signer_name:name.trim(),signer_relationship:relationship,comment:comment.trim()||null,acknowledgment_version:1,attest_document_review:true,attest_authority:true,attest_choice:true},witness:{channel,occurred_at:occurred.trim(),note:note.trim(),attest_direct_client_instruction:true}}});void operation.execute(q);}catch{setError('Enter the respondent, instruction date and time and witness note, then attest the reviewed instruction.');}}
 async function more(){if(lock.current||!history?.has_more)return;lock.current=true;setLoading(true);try{const g=generation.current;const page=await api.history(history.next_before_sequence);if(page.head.event_id!==history.head.event_id||page.head.record_hash!==history.head.record_hash)throw new Error('History changed; refresh first');if(alive.current&&g===generation.current)setHistory({...page,items:[...history.items,...page.items]});}catch{if(alive.current)setError('The next history page could not be verified.');}finally{lock.current=false;if(alive.current)setLoading(false);}}
 return <section aria-label="Estimate decisions and witness record" className="space-y-4 rounded-lg border border-border bg-card p-4 md:p-6">
  <h3 className="text-xl font-semibold">Estimate decisions</h3><p className="text-sm text-muted-foreground">Record a client’s direct instruction about the entire published estimate. This records staff-witnessed evidence, not a verified client signature, clinical consent, treatment or payment.</p>
  {error&&<p role="alert" className="text-destructive">{error}</p>}{operation.error&&<p role="alert" className="text-destructive">{operation.error}</p>}{operation.notice&&<p role="status">{operation.notice}</p>}
  {operation.pending&&<div className="space-y-2 rounded-md border border-border p-3"><h4 className="font-semibold">Resolve original witnessed decision</h4><p className="break-all text-sm">Request {operation.pending.id} · {operation.pending.payload.decision.choice} · {operation.pending.payload.decision.signer_name}</p><div className="flex flex-wrap gap-2"><Button disabled={operation.busy||operation.blocked} onClick={()=>void operation.recover()}>Recover original witnessed decision</Button><Button variant="outline" disabled={operation.busy||operation.blocked} onClick={()=>void operation.retry()}>Retry identical witnessed decision</Button><Button variant="outline" disabled={operation.busy||operation.blocked} onClick={()=>void operation.resolve()}>Resolve or close original witnessed request</Button></div><p className="text-sm">An absent recovery is not cancellation. Keep this original request until its exact outcome or permanent closure is confirmed.</p></div>}
  <div className="flex flex-wrap gap-2"><Button onClick={()=>void loadDocument()} disabled={operation.locked||loading}>Review current published estimate</Button><Button variant="outline" onClick={()=>void refresh().catch(()=>setError('History could not be refreshed.'))} disabled={operation.busy||loading}>Refresh decision history</Button></div>
  {state?.current_decision&&<p role="status">Current publication: {state.current_decision.choice==='accept'?'accepted':'declined'} by {state.current_decision.signer_name}.</p>}
  {review&&<><iframe title="Published estimate for witnessed decision" src={review.url} sandbox="" referrerPolicy="no-referrer" className="h-[28rem] w-full rounded-md border border-border"/><a href={review.url} download={review.filename} className="underline">Download reviewed published estimate</a><p className="text-sm">Acceptance deadline {new Date(review.preview.expires_at).toLocaleString('en-US',{timeZone:'America/Denver'})}, Mountain Time.</p></>}
  <fieldset disabled={!review||operation.locked||loading} className="space-y-3"><legend className="font-semibold">Direct client instruction</legend>
   <label className="block">Respondent name<input className="block w-full rounded-md border border-input bg-background p-2" value={name} onChange={e=>{setName(e.target.value);setAttest(false);}}/></label>
   <label className="block">Respondent relationship<select className="block w-full rounded-md border border-input bg-background p-2" value={relationship} onChange={e=>{setRelationship(e.target.value as typeof relationship);setAttest(false);}}><option value="owner">Reported owner</option><option value="authorized_agent">Reported authorized agent</option></select></label>
   <label className="block">Client decision<select className="block w-full rounded-md border border-input bg-background p-2" value={choice} onChange={e=>{setChoice(e.target.value as typeof choice);setAttest(false);}}><option value="accept">Accept entire estimate</option><option value="decline">Decline entire estimate</option></select></label>
   <label className="block">Instruction channel<select className="block w-full rounded-md border border-input bg-background p-2" value={channel} onChange={e=>{setChannel(e.target.value as typeof channel);setAttest(false);}}>{(['in_person','telephone','video','written'] as const).map(v=><option key={v} value={v}>{v.replace('_',' ')}</option>)}</select></label>
   <div className="space-y-2"><Button type="button" variant="outline" onClick={()=>{setOccurred(new Date().toISOString());setAttest(false);}}>Instruction received now</Button>{occurred&&<p className="text-sm">Instruction received {new Date(occurred).toLocaleString('en-US',{timeZone:'America/Denver'})}, Mountain Time.</p>}<label className="block">Earlier instruction date and time (Mountain Time)<input type="datetime-local" className="block w-full rounded-md border border-input bg-background p-2" value={occurred?denverLocal(occurred):''} onChange={e=>{setAttest(false);try{setOccurred(denverInstant(e.target.value));setError('');}catch(error){setOccurred('');setError(error instanceof Error?error.message:'Choose a valid instruction time.');}}}/></label></div>
   <label className="block">Witness note<textarea className="block w-full rounded-md border border-input bg-background p-2" value={note} onChange={e=>{setNote(e.target.value);setAttest(false);}}/></label><label className="block">Client comment (optional)<textarea className="block w-full rounded-md border border-input bg-background p-2" value={comment} onChange={e=>{setComment(e.target.value);setAttest(false);}}/></label>
   <label className="flex items-start gap-2"><input type="checkbox" checked={attest} onChange={e=>setAttest(e.target.checked)}/>I reviewed these exact published terms and directly received this decision from the named respondent, who stated authority to decide for this patient.</label>
   <Button onClick={save} disabled={!review||!attest||!name.trim()||!note.trim()||!occurred.trim()||operation.locked}>Record witnessed decision</Button>
  </fieldset>
  {(review||name||note||comment||occurred)&&!operation.locked&&<Button variant="outline" onClick={()=>{clearReview();setName('');setNote('');setComment('');setOccurred('');}}>Discard unsaved witness form</Button>}
  <div className="space-y-3"><h4 className="font-semibold">Immutable decision history</h4>{history?.items.map(d=><article key={d.id} className="space-y-1 rounded-md border border-border p-3"><p className="font-medium">{d.choice==='accept'?'Accepted':'Declined'} · {d.signer_name}</p><p className="text-sm">{d.provenance.kind==='grant'?'Private-link holder; self-reported identity':'Recorded by staff from direct client instruction'} · {new Date(d.recorded_at).toLocaleString('en-US',{timeZone:'America/Denver'})} Mountain Time</p>{d.provenance.kind==='staff_witness'&&<><p className="text-sm">{d.provenance.witness.channel} · occurred {new Date(d.provenance.witness.occurred_at).toLocaleString('en-US',{timeZone:'America/Denver'})} Mountain Time</p><p className="whitespace-pre-wrap">{d.provenance.witness.note}</p></>}{d.comment&&<p className="whitespace-pre-wrap">{d.comment}</p>}</article>)}{history?.has_more&&<Button variant="outline" disabled={loading} onClick={()=>void more()}>Load earlier decisions</Button>}</div>
 </section>;
}
