-- Make the application portable to projects without platform default DML grants.
-- RLS remains the authority for staff membership, ownership and administrator access.
-- Enumerate existing RLS-protected tables: do not grant future/unsecured tables.
-- Removing ALL also removes TRUNCATE, which bypasses RLS.
REVOKE ALL PRIVILEGES ON TABLE
  public.app_settings,
  public.appointment_reminders,
  public.appointments,
  public.audit_logs,
  public.call_logs,
  public.callback_queue,
  public.campaign_recipients,
  public.campaigns,
  public.client_files,
  public.client_notes,
  public.clients,
  public.consent_form_templates,
  public.consent_submissions,
  public.contact_submissions,
  public.conversations,
  public.follow_up_instances,
  public.follow_up_messages,
  public.follow_up_templates,
  public.lab_results,
  public.message_attachments,
  public.message_templates,
  public.messages,
  public.on_call_schedules,
  public.outbound_message_attempts,
  public.payment_links,
  public.pet_vaccinations,
  public.pets,
  public.profiles,
  public.refill_requests,
  public.response_metrics,
  public.sms_consent,
  public.survey_responses,
  public.surveys,
  public.tickets,
  public.time_entries,
  public.urgent_alerts,
  public.user_roles,
  public.voicemail_messages,
  public.waitlist_entries,
  public.wellness_reminders
FROM PUBLIC, anon, authenticated, service_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE
  public.app_settings,
  public.appointment_reminders,
  public.appointments,
  public.call_logs,
  public.callback_queue,
  public.campaign_recipients,
  public.campaigns,
  public.client_files,
  public.client_notes,
  public.clients,
  public.consent_form_templates,
  public.consent_submissions,
  public.conversations,
  public.follow_up_instances,
  public.follow_up_messages,
  public.follow_up_templates,
  public.lab_results,
  public.message_attachments,
  public.message_templates,
  public.on_call_schedules,
  public.payment_links,
  public.pet_vaccinations,
  public.pets,
  public.profiles,
  public.refill_requests,
  public.sms_consent,
  public.survey_responses,
  public.surveys,
  public.tickets,
  public.urgent_alerts,
  public.user_roles,
  public.voicemail_messages,
  public.waitlist_entries,
  public.wellness_reminders
TO authenticated;

-- Match the narrower policy contracts for system-authored data.
GRANT SELECT, INSERT, DELETE ON public.messages TO authenticated;
GRANT SELECT, DELETE ON public.outbound_message_attempts TO authenticated;
GRANT SELECT, UPDATE, DELETE ON public.time_entries TO authenticated;
GRANT SELECT ON public.audit_logs, public.response_metrics TO authenticated;
GRANT SELECT, INSERT ON public.contact_submissions TO authenticated;
GRANT INSERT ON public.contact_submissions TO anon;

-- Edge Functions use service_role for provider ingestion; BYPASSRLS alone does
-- not confer table privileges. No DDL, trigger or truncate grant is required.
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE
  public.app_settings,
  public.appointment_reminders,
  public.appointments,
  public.audit_logs,
  public.call_logs,
  public.callback_queue,
  public.campaign_recipients,
  public.campaigns,
  public.client_files,
  public.client_notes,
  public.clients,
  public.consent_form_templates,
  public.consent_submissions,
  public.contact_submissions,
  public.conversations,
  public.follow_up_instances,
  public.follow_up_messages,
  public.follow_up_templates,
  public.lab_results,
  public.message_attachments,
  public.message_templates,
  public.messages,
  public.on_call_schedules,
  public.outbound_message_attempts,
  public.payment_links,
  public.pet_vaccinations,
  public.pets,
  public.profiles,
  public.refill_requests,
  public.response_metrics,
  public.sms_consent,
  public.survey_responses,
  public.surveys,
  public.tickets,
  public.time_entries,
  public.urgent_alerts,
  public.user_roles,
  public.voicemail_messages,
  public.waitlist_entries,
  public.wellness_reminders
TO service_role;
