import { useEffect, useMemo, useRef, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hub/contexts/AuthContext";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { createPrescriptionApi, prescriptionFieldsSchema } from "./prescription-api";
import type { PrescriptionAuthorization, PrescriptionCursor, PrescriptionDraft, PrescriptionFields, PrescriptionRpc, PrescriptionSignPreview, PrescriberEntry } from "./prescription-api";
import { PrescriptionEditor } from "./PrescriptionEditor";
import type { PrescriptionDraftFields } from "./PrescriptionEditor";
import { emptyPrescriptionDraft } from "./prescription-draft";
import { usePrescriptionOperation } from "./usePrescriptionOperation";
import { PrescriptionOperationControls } from "./PrescriptionOperationControls";
import { PrescriptionSettings } from "./PrescriptionSettings";
interface Props { petId: string; clientId: string; inactive: boolean; disabled: boolean; onDirtyChange: (dirty: boolean) => void }
function editorFields(f: PrescriptionFields): PrescriptionDraftFields { return { medicationName: f.medication.name, strength: f.medication.strength, form: f.medication.form, directions: f.medication.directions, route: f.medication.route, quantity: f.quantity_per_fill, stockUnit: f.unit, refills: String(f.refills_authorized), startsOn: f.starts_on, expiresOn: f.expires_on, fulfillmentMode: f.fulfillment_mode, productId: f.product_id ?? "", encounterId: f.encounter_id ?? "" }; }
export function PatientPrescriptions(props: Props) {
  const { user, hasRole } = useAuth();
  return user ? <PrescriptionWorkspace key={`${user.id}:${props.petId}`} {...props} actor={user.id} isAdmin={hasRole("ADMIN")} isDvm={hasRole("DVM")} /> : null;
}
interface WorkspaceProps extends Props { actor: string; isAdmin: boolean; isDvm: boolean }
function PrescriptionWorkspace({ petId, clientId, actor, isAdmin, isDvm, inactive, disabled, onDirtyChange }: WorkspaceProps) {
  const api = useMemo(() => createPrescriptionApi(supabase as unknown as PrescriptionRpc, actor, petId), [actor, petId]);
  const alive = useRef(true), sequence = useRef(0), readLock = useRef(false);
  useEffect(() => { alive.current = true; return () => { alive.current = false; }; }, []);
  const [drafts, setDrafts] = useState<PrescriptionDraft[]>([]), [cursor, setCursor] = useState<PrescriptionCursor | null>(null), [loaded, setLoaded] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const [prescribers, setPrescribers] = useState<PrescriberEntry[]>([]), [prescriberAfter, setPrescriberAfter] = useState<string | null>(null);
  const [selected, setSelected] = useState<PrescriptionDraft | null>(null), [draftId, setDraftId] = useState(""), [editing, setEditing] = useState(false), [values, setValues] = useState(emptyPrescriptionDraft), [modified, setModified] = useState(false);
  const [preview, setPreview] = useState<PrescriptionSignPreview | null>(null), [history, setHistory] = useState<PrescriptionAuthorization | null>(null), [ack, setAck] = useState(false), [settingsDirty, setSettingsDirty] = useState(false), [search, setSearch] = useState("");
  const operation = usePrescriptionOperation({ actor, patientId: petId, execute: api.execute, recover: api.recover, onConfirmed: receipt => {
    if (receipt.operation === "save_draft") { setSelected(receipt.result); setValues(editorFields(receipt.result.fields)); setDrafts(previous => previous.some(d => d.id === receipt.result.id) ? previous.map(d => d.id === receipt.result.id ? receipt.result : d) : [receipt.result, ...previous]); }
    else if (receipt.operation === "sign") { setHistory(receipt.result); setEditing(false); setSelected(null); setDrafts(previous => previous.map(d => d.id === receipt.result.draft_id ? { ...d, status: "signed", authorization_id: receipt.result.id } : d)); }
    else throw new Error("Wrong patient operation receipt");
    setModified(false); setPreview(null); setAck(false);
  } });
  const draftDirty = modified || operation.dirty, dirty = draftDirty || settingsDirty;
  useEffect(() => { onDirtyChange(dirty); }, [dirty, onDirtyChange]);
  useEffect(() => () => onDirtyChange(false), [onDirtyChange]);
  const blocked = dirty || disabled || busy;
  async function read(action: () => Promise<void>) {
    if (readLock.current) return; readLock.current = true; setBusy(true); setError("");
    try { await action(); } catch { if (alive.current) setError("Prescription evidence could not be loaded. Existing drafts and uncertain operations have been retained. Retry when ready."); }
    finally { readLock.current = false; if (alive.current) setBusy(false); }
  }
  async function refresh() {
    await read(async () => { const generation = ++sequence.current; const [page, staff] = await Promise.all([api.listDrafts(), api.listPrescribers()]); if (!alive.current || sequence.current !== generation) return; setDrafts(page.drafts); setCursor(page.next_cursor); setPrescribers(staff.entries); setPrescriberAfter(staff.next_after_id); setLoaded(true); });
  }
  useEffect(() => { void read(async () => { const generation = ++sequence.current; const [page, staff] = await Promise.all([api.listDrafts(), api.listPrescribers()]); if (!alive.current || sequence.current !== generation) return; setDrafts(page.drafts); setCursor(page.next_cursor); setPrescribers(staff.entries); setPrescriberAfter(staff.next_after_id); setLoaded(true); }); }, [api]); // Identity-keyed workspace; never background-refetch an active review.
  const products = useQuery({ queryKey: ["prescription-products", actor, search], enabled: editing && !operation.dirty && !settingsDirty, refetchOnWindowFocus: false, refetchOnReconnect: false, queryFn: async () => {
    let query = supabase.from("catalog_products").select("id,name,unit").eq("kind", "medication").eq("active", true).order("name").order("id").limit(101);
    if (search.trim()) query = query.ilike("name", `%${search.trim().replace(/[%_\\]/g, "\\$&")}%`);
    const { data, error } = await query; if (error) throw error; return data;
  } });
  const encounters = useQuery({ queryKey: ["prescription-encounters", actor, petId], enabled: editing, refetchOnWindowFocus: false, refetchOnReconnect: false, queryFn: async () => { const { data, error } = await supabase.from("clinical_encounters").select("id,visit_at,visit_type").eq("pet_id", petId).order("visit_at", { ascending: false }).order("id").limit(101); if (error) throw error; return data; } });
  const me = prescribers.find(p => p.user_id === actor);
  function begin(draft: PrescriptionDraft | null) { operation.discard(); setSelected(draft); setDraftId(draft?.id ?? crypto.randomUUID()); setValues(draft ? editorFields(draft.fields) : emptyPrescriptionDraft()); setEditing(true); setModified(!draft); setHistory(null); setPreview(null); setAck(false); setError(""); }
  function reviewSave() {
    setError("");
    if (!/^\d+$/.test(values.refills)) { setError("Enter an explicit whole number of additional refills, including zero when appropriate."); return; }
    const result = prescriptionFieldsSchema.safeParse({ encounter_id: values.encounterId || null, medication: { name: values.medicationName, strength: values.strength, form: values.form, directions: values.directions, route: values.route }, quantity_per_fill: values.quantity, unit: values.stockUnit, refills_authorized: Number(values.refills), fulfillment_mode: values.fulfillmentMode, product_id: values.productId || null, starts_on: values.startsOn, expires_on: values.expiresOn });
    if (!result.success) { setError("Complete every prescription field with explicit values. Use a positive quantity with at most three decimal places, a whole number of refills, and an expiry on or after the start date."); return; }
    setAck(false); operation.review({ id: crypto.randomUUID(), kind: "save_draft", payload: { draft_id: draftId, pet_id: petId, client_id: selected?.client_id ?? clientId, expected_version: selected?.version ?? null, fields: result.data } });
  }
  async function reviewSign() { if (!selected) return; await read(async () => { const result = await api.preview(selected); if (!alive.current) return; setPreview(result); setAck(false); operation.review({ id: crypto.randomUUID(), kind: "sign", payload: { draft_id: selected.id, pet_id: petId, expected_version: selected.version, expected_context_hash: result.context_hash, signature_name: result.context.prescriber.name, attest_review: true } }); }); }
  const controls = <PrescriptionOperationControls state={operation.state} error={operation.error} notice={operation.notice} commitLabel={operation.state.operation?.kind === "sign" ? "Sign reviewed prescription" : "Save reviewed draft"} reviewConfirmed={ack && !disabled && !settingsDirty && !inactive && (operation.state.operation?.kind !== "sign" || isDvm)} onCommit={operation.commit} onRecover={operation.recoverOriginal} onDiscard={() => { operation.discard(); setPreview(null); setAck(false); }} />;
  return <Card><CardHeader><CardTitle>Practice prescriptions</CardTitle></CardHeader><CardContent className="space-y-5">
    <p className="text-sm text-muted-foreground">Prepare an order, review patient alerts and sign with an eligible prescriber. Signing does not dispense medication, create a charge or send the order. Fulfillment and current-status printing are not available in this release.</p>
    <p className="text-sm">Your prescribing configuration: {me?.eligible ? "eligible" : me?.configuration ? "configured, not currently eligible" : "not confirmed / not configured"}. {isDvm ? "The server checks current eligibility again before signing." : "A DVM role is required to sign."}</p>
    <div className="flex flex-wrap gap-2"><Button disabled={blocked || inactive || !loaded} onClick={() => begin(null)}>New prescription draft</Button><Button variant="outline" disabled={blocked} onClick={() => void refresh()}>Refresh prescription history</Button></div>
    {busy && <p role="status">Loading prescription evidence…</p>}{error && <p role="alert">{error}</p>}
    {editing && <section className="space-y-4 rounded-md border p-4" aria-label="Native prescription editor"><p className="break-all text-xs text-muted-foreground">Patient {petId} · household {selected?.client_id ?? clientId} · draft {draftId}{selected ? ` · revision ${selected.version}` : " · unsaved"}</p>
      <fieldset disabled={operation.dirty || disabled || settingsDirty || busy}><Label htmlFor="prescription-product-search">Find a stocked medication by name</Label><Input id="prescription-product-search" value={search} onChange={e => setSearch(e.target.value)} /></fieldset>
      {products.isError && <p role="alert">Stocked products could not be loaded. Retry the search before selecting a stocked product.</p>}{products.data && products.data.length > 100 && <p role="status">Showing the first 100 matching products. Refine the search to select another medication.</p>}
      {encounters.isError && <p role="alert">Encounters could not be loaded. An encounter link is optional; no encounter will be inferred.</p>}{encounters.data && encounters.data.length > 100 && <p role="status">Showing the 100 most recent encounters. Older encounter selection is not available here.</p>}
      <PrescriptionEditor identity={`rx-${petId}`} values={values} onChange={next => { setValues(next); setModified(true); setAck(false); setPreview(null); }} products={products.data?.slice(0, 100) ?? []} encounters={encounters.data?.slice(0, 100).map(e => ({ id: e.id, label: `${e.visit_at} · ${e.visit_type}` })) ?? []} disabled={operation.dirty || disabled || settingsDirty || busy || inactive} />
      {!operation.dirty && <div className="flex flex-wrap gap-2"><Button disabled={disabled || settingsDirty || busy || inactive || !modified} onClick={reviewSave}>Review draft save</Button><Button disabled={disabled || settingsDirty || busy || inactive || modified || !selected || !isDvm} onClick={() => void reviewSign()}>Review for signature</Button><Button variant="outline" disabled={disabled || settingsDirty || busy} onClick={() => { setEditing(false); setModified(false); setPreview(null); setAck(false); }}>Discard local edits / close draft</Button></div>}
      {preview && operation.state.operation?.kind === "sign" && <section className="space-y-3 rounded-md border p-4" aria-label="Prescription signing review"><h3 className="font-semibold">Review frozen signing evidence</h3><p>{preview.context.patient.name} · {preview.context.patient.species} · household {preview.context.household.name}</p><p className="whitespace-pre-wrap text-sm">{preview.context.household.address}</p><p className="text-sm">Prescriber: {preview.context.prescriber.name} · license {preview.context.prescriber.configuration.fields.license_number} ({preview.context.prescriber.configuration.fields.license_state}), expires {preview.context.prescriber.configuration.fields.license_expires_on}</p><p className="text-sm">{preview.context.product ? `Exact stock product: ${preview.context.product.name} · ${preview.context.product.id} · ${preview.context.product.unit}` : "External pharmacy order; no practice stock debit."}</p><h4 className="font-medium text-clinical-alert">Important patient alerts</h4>{preview.context.alerts.snapshot.important_problems.length ? preview.context.alerts.snapshot.important_problems.map(p => <div key={p.id} className="rounded border border-destructive p-2 text-clinical-alert"><p>{p.title} · {p.status}</p><p className="whitespace-pre-wrap text-sm">{p.notes}</p></div>) : <p className="text-sm">No structured high-importance problems in this reviewed snapshot.</p>}<p className="whitespace-pre-wrap text-sm">Existing allergy text: {preview.context.alerts.snapshot.legacy_allergies.text || "None recorded"}</p><p className="text-xs text-muted-foreground">{preview.context.alerts.snapshot.legacy_allergies.provenance}</p><p className="break-all text-xs text-muted-foreground">Context: {preview.context_hash}</p></section>}
      {operation.state.phase === "review" && <label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={ack} disabled={disabled || settingsDirty} onChange={e => setAck(e.target.checked)} />{preview ? `I reviewed this prescription, patient identity, alerts and credentials, and authorize signing as ${preview.context.prescriber.name}.` : "I reviewed the draft values. Saving a draft does not authorize treatment."}</label>}
    </section>}
    {controls}
    <section className="space-y-3" aria-label="Saved prescription history"><h3 className="font-medium">Saved drafts and signed orders</h3>{loaded && !drafts.length && <p className="text-sm">No native prescription drafts have been saved for this patient.</p>}{drafts.map(d => <div key={d.id} className="flex flex-wrap items-center justify-between gap-2 rounded-md border p-3"><div><p>{d.fields.medication.name} · {d.fields.medication.strength}</p><p className="text-sm text-muted-foreground">{d.status === "signed" ? "Signed order — historical authorization" : "Unsigned draft"} · revision {d.version}</p></div><Button variant="outline" disabled={blocked} onClick={() => void read(async () => { const current = await api.readDraft(d.id); if (!alive.current) return; if (!current) throw new Error("Draft unavailable"); if (current.status === "draft") begin(current); else { const saved = await api.readAuthorization(current.authorization_id!); if (!alive.current) return; if (!saved) throw new Error("Authorization unavailable"); setEditing(false); setSelected(null); setHistory(saved); } })}>{d.status === "draft" ? "Open draft" : "View signed snapshot"}</Button></div>)}{cursor && <Button variant="outline" disabled={blocked} onClick={() => void read(async () => { const page = await api.listDrafts(cursor); if (!alive.current) return; setDrafts(previous => [...previous, ...page.drafts.filter(d => !previous.some(p => p.id === d.id))]); setCursor(page.next_cursor); })}>Load more prescriptions</Button>}</section>
    {history && <section className="space-y-2 rounded-md border p-4" aria-label="Signed prescription snapshot"><h3 className="font-medium">Signed prescription snapshot</h3><p>{history.artifact.patient.name} · household {history.artifact.household.name}</p><p>{history.artifact.medication.name} · {history.artifact.medication.strength} · {history.artifact.medication.form}</p><p className="whitespace-pre-wrap">{history.artifact.medication.directions}</p><p>{history.artifact.medication.route} · maximum {history.artifact.quantity_per_fill} {history.artifact.unit} per fill · {history.artifact.refills_authorized} additional refills</p><p>{history.artifact.starts_on} through {history.artifact.expires_on} · {history.artifact.fulfillment_mode === "practice_stock" ? "Practice stock" : "External pharmacy"}</p><p className="text-sm">Signed by {history.artifact.signature_name} on {history.signed_at}</p><p className="break-all text-xs text-muted-foreground">Authorization {history.id}</p><p className="text-sm">Historical evidence only. This view does not confirm current dispensing permission, remaining fills or order delivery.</p></section>}
    <PrescriptionSettings api={api} actor={actor} patientId={petId} entries={prescribers} isAdmin={isAdmin} disabled={draftDirty || disabled || busy} onDirtyChange={setSettingsDirty} onSaved={() => { void refresh(); }} />
    {prescriberAfter && <Button variant="outline" disabled={blocked} onClick={() => void read(async () => { const page = await api.listPrescribers(prescriberAfter); if (!alive.current) return; setPrescribers(previous => [...previous, ...page.entries]); setPrescriberAfter(page.next_after_id); })}>Load more prescribers</Button>}
  </CardContent></Card>;
}
